import type { SupportedLocale } from './locales';

export type NetworkWorkspaceCopy = {
  editLayout: string;
  done: string;
  reset: string;
  cancel: string;
  groups: string;
  myGroups: string;
  newGroup: string;
  group: string;
  groupName: string;
  dropHere: string;
  members: string;
  createGroup: string;
  ungroup: string;
  removeFromGroup: string;
  expandGroup: string;
  collapseGroup: string;
  noGroups: string;
  fit: string;
  holdToMove: string;
  layoutSaved: string;
  needTwo: string;
};

export const NETWORK_WORKSPACE_COPY: Record<SupportedLocale, NetworkWorkspaceCopy> = {
  en: { editLayout: 'Edit layout', done: 'Done', reset: 'Reset', cancel: 'Cancel', groups: 'Groups', myGroups: 'My groups', newGroup: 'New group', group: 'Group', groupName: 'Group name', dropHere: 'Drag members here', members: 'members', createGroup: 'Create group', ungroup: 'Ungroup', removeFromGroup: 'Remove from group', expandGroup: 'Expand group', collapseGroup: 'Collapse group', noGroups: 'No groups yet', fit: 'Fit', holdToMove: 'Hold 0.5s to move', layoutSaved: 'Layout saved', needTwo: 'Add at least 2 members' },
  ko: { editLayout: '배치 편집', done: '완료', reset: '초기화', cancel: '취소', groups: '그룹', myGroups: '내 그룹', newGroup: '새 그룹', group: '그룹', groupName: '그룹 이름', dropHere: '멤버를 여기로 드래그', members: '명', createGroup: '그룹 만들기', ungroup: '그룹 해제', removeFromGroup: '그룹에서 빼기', expandGroup: '그룹 펼치기', collapseGroup: '그룹 접기', noGroups: '아직 그룹이 없어요', fit: '맞춤', holdToMove: '0.5초 길게 눌러 이동', layoutSaved: '배치가 저장됐어요', needTwo: '멤버를 2명 이상 추가하세요' },
  zh: { editLayout: '编辑布局', done: '完成', reset: '重置', cancel: '取消', groups: '分组', myGroups: '我的分组', newGroup: '新建分组', group: '分组', groupName: '分组名称', dropHere: '将成员拖到这里', members: '名成员', createGroup: '创建分组', ungroup: '取消分组', removeFromGroup: '移出分组', expandGroup: '展开分组', collapseGroup: '收起分组', noGroups: '暂无分组', fit: '适应', holdToMove: '长按 0.5 秒移动', layoutSaved: '布局已保存', needTwo: '请至少添加 2 名成员' },
  hi: { editLayout: 'लेआउट संपादित करें', done: 'पूर्ण', reset: 'रीसेट', cancel: 'रद्द करें', groups: 'समूह', myGroups: 'मेरे समूह', newGroup: 'नया समूह', group: 'समूह', groupName: 'समूह का नाम', dropHere: 'सदस्यों को यहाँ खींचें', members: 'सदस्य', createGroup: 'समूह बनाएँ', ungroup: 'समूह हटाएँ', removeFromGroup: 'समूह से निकालें', expandGroup: 'समूह खोलें', collapseGroup: 'समूह समेटें', noGroups: 'अभी कोई समूह नहीं', fit: 'फिट', holdToMove: 'स्थान बदलने के लिए 0.5 सेकंड दबाएँ', layoutSaved: 'लेआउट सहेजा गया', needTwo: 'कम से कम 2 सदस्य जोड़ें' },
  es: { editLayout: 'Editar diseño', done: 'Listo', reset: 'Restablecer', cancel: 'Cancelar', groups: 'Grupos', myGroups: 'Mis grupos', newGroup: 'Nuevo grupo', group: 'Grupo', groupName: 'Nombre del grupo', dropHere: 'Arrastra miembros aquí', members: 'miembros', createGroup: 'Crear grupo', ungroup: 'Desagrupar', removeFromGroup: 'Quitar del grupo', expandGroup: 'Expandir grupo', collapseGroup: 'Contraer grupo', noGroups: 'Aún no hay grupos', fit: 'Ajustar', holdToMove: 'Mantén 0,5 s para mover', layoutSaved: 'Diseño guardado', needTwo: 'Añade al menos 2 miembros' },
  ja: { editLayout: '配置を編集', done: '完了', reset: 'リセット', cancel: 'キャンセル', groups: 'グループ', myGroups: 'マイグループ', newGroup: '新しいグループ', group: 'グループ', groupName: 'グループ名', dropHere: 'メンバーをここにドラッグ', members: '人', createGroup: 'グループを作成', ungroup: 'グループ解除', removeFromGroup: 'グループから外す', expandGroup: 'グループを開く', collapseGroup: 'グループを閉じる', noGroups: 'グループはまだありません', fit: '全体表示', holdToMove: '0.5秒長押しで移動', layoutSaved: '配置を保存しました', needTwo: '2人以上追加してください' },
  it: { editLayout: 'Modifica layout', done: 'Fine', reset: 'Reimposta', cancel: 'Annulla', groups: 'Gruppi', myGroups: 'I miei gruppi', newGroup: 'Nuovo gruppo', group: 'Gruppo', groupName: 'Nome gruppo', dropHere: 'Trascina qui i membri', members: 'membri', createGroup: 'Crea gruppo', ungroup: 'Separa gruppo', removeFromGroup: 'Rimuovi dal gruppo', expandGroup: 'Espandi gruppo', collapseGroup: 'Comprimi gruppo', noGroups: 'Nessun gruppo', fit: 'Adatta', holdToMove: 'Tieni premuto 0,5 s per spostare', layoutSaved: 'Layout salvato', needTwo: 'Aggiungi almeno 2 membri' },
  tr: { editLayout: 'Düzeni düzenle', done: 'Bitti', reset: 'Sıfırla', cancel: 'İptal', groups: 'Gruplar', myGroups: 'Gruplarım', newGroup: 'Yeni grup', group: 'Grup', groupName: 'Grup adı', dropHere: 'Üyeleri buraya sürükle', members: 'üye', createGroup: 'Grup oluştur', ungroup: 'Grubu çöz', removeFromGroup: 'Gruptan çıkar', expandGroup: 'Grubu aç', collapseGroup: 'Grubu kapat', noGroups: 'Henüz grup yok', fit: 'Sığdır', holdToMove: 'Taşımak için 0,5 sn basılı tut', layoutSaved: 'Düzen kaydedildi', needTwo: 'En az 2 üye ekleyin' },
  nl: { editLayout: 'Indeling bewerken', done: 'Klaar', reset: 'Reset', cancel: 'Annuleren', groups: 'Groepen', myGroups: 'Mijn groepen', newGroup: 'Nieuwe groep', group: 'Groep', groupName: 'Groepsnaam', dropHere: 'Sleep leden hierheen', members: 'leden', createGroup: 'Groep maken', ungroup: 'Groep opheffen', removeFromGroup: 'Uit groep verwijderen', expandGroup: 'Groep uitklappen', collapseGroup: 'Groep inklappen', noGroups: 'Nog geen groepen', fit: 'Passend', holdToMove: 'Houd 0,5 s vast om te verplaatsen', layoutSaved: 'Indeling opgeslagen', needTwo: 'Voeg minimaal 2 leden toe' },
  de: { editLayout: 'Layout bearbeiten', done: 'Fertig', reset: 'Zurücksetzen', cancel: 'Abbrechen', groups: 'Gruppen', myGroups: 'Meine Gruppen', newGroup: 'Neue Gruppe', group: 'Gruppe', groupName: 'Gruppenname', dropHere: 'Mitglieder hierher ziehen', members: 'Mitglieder', createGroup: 'Gruppe erstellen', ungroup: 'Gruppierung aufheben', removeFromGroup: 'Aus Gruppe entfernen', expandGroup: 'Gruppe öffnen', collapseGroup: 'Gruppe schließen', noGroups: 'Noch keine Gruppen', fit: 'Einpassen', holdToMove: 'Zum Verschieben 0,5 s halten', layoutSaved: 'Layout gespeichert', needTwo: 'Mindestens 2 Mitglieder hinzufügen' },
  fr: { editLayout: 'Modifier la disposition', done: 'Terminé', reset: 'Réinitialiser', cancel: 'Annuler', groups: 'Groupes', myGroups: 'Mes groupes', newGroup: 'Nouveau groupe', group: 'Groupe', groupName: 'Nom du groupe', dropHere: 'Glissez les membres ici', members: 'membres', createGroup: 'Créer le groupe', ungroup: 'Dégrouper', removeFromGroup: 'Retirer du groupe', expandGroup: 'Développer le groupe', collapseGroup: 'Réduire le groupe', noGroups: 'Aucun groupe pour le moment', fit: 'Ajuster', holdToMove: 'Maintenez 0,5 s pour déplacer', layoutSaved: 'Disposition enregistrée', needTwo: 'Ajoutez au moins 2 membres' },
  ar: { editLayout: 'تعديل التخطيط', done: 'تم', reset: 'إعادة ضبط', cancel: 'إلغاء', groups: 'المجموعات', myGroups: 'مجموعاتي', newGroup: 'مجموعة جديدة', group: 'مجموعة', groupName: 'اسم المجموعة', dropHere: 'اسحب الأعضاء إلى هنا', members: 'أعضاء', createGroup: 'إنشاء مجموعة', ungroup: 'فك المجموعة', removeFromGroup: 'إزالة من المجموعة', expandGroup: 'توسيع المجموعة', collapseGroup: 'طي المجموعة', noGroups: 'لا توجد مجموعات بعد', fit: 'ملاءمة', holdToMove: 'اضغط 0.5 ثانية للتحريك', layoutSaved: 'تم حفظ التخطيط', needTwo: 'أضف عضوين على الأقل' },
  bn: { editLayout: 'লেআউট সম্পাদনা', done: 'সম্পন্ন', reset: 'রিসেট', cancel: 'বাতিল', groups: 'গ্রুপ', myGroups: 'আমার গ্রুপ', newGroup: 'নতুন গ্রুপ', group: 'গ্রুপ', groupName: 'গ্রুপের নাম', dropHere: 'সদস্যদের এখানে টানুন', members: 'সদস্য', createGroup: 'গ্রুপ তৈরি করুন', ungroup: 'গ্রুপ খুলুন', removeFromGroup: 'গ্রুপ থেকে সরান', expandGroup: 'গ্রুপ খুলুন', collapseGroup: 'গ্রুপ গুটান', noGroups: 'এখনও কোনো গ্রুপ নেই', fit: 'ফিট', holdToMove: 'সরাতে ০.৫ সেকেন্ড ধরে রাখুন', layoutSaved: 'লেআউট সংরক্ষিত', needTwo: 'কমপক্ষে ২ জন সদস্য যোগ করুন' },
  pt: { editLayout: 'Editar layout', done: 'Concluir', reset: 'Redefinir', cancel: 'Cancelar', groups: 'Grupos', myGroups: 'Meus grupos', newGroup: 'Novo grupo', group: 'Grupo', groupName: 'Nome do grupo', dropHere: 'Arraste membros aqui', members: 'membros', createGroup: 'Criar grupo', ungroup: 'Desagrupar', removeFromGroup: 'Remover do grupo', expandGroup: 'Expandir grupo', collapseGroup: 'Recolher grupo', noGroups: 'Ainda não há grupos', fit: 'Ajustar', holdToMove: 'Segure 0,5 s para mover', layoutSaved: 'Layout salvo', needTwo: 'Adicione pelo menos 2 membros' },
  ru: { editLayout: 'Изменить схему', done: 'Готово', reset: 'Сбросить', cancel: 'Отмена', groups: 'Группы', myGroups: 'Мои группы', newGroup: 'Новая группа', group: 'Группа', groupName: 'Название группы', dropHere: 'Перетащите участников сюда', members: 'участников', createGroup: 'Создать группу', ungroup: 'Разгруппировать', removeFromGroup: 'Удалить из группы', expandGroup: 'Развернуть группу', collapseGroup: 'Свернуть группу', noGroups: 'Групп пока нет', fit: 'Вписать', holdToMove: 'Удерживайте 0,5 с для перемещения', layoutSaved: 'Схема сохранена', needTwo: 'Добавьте минимум 2 участников' },
  id: { editLayout: 'Edit tata letak', done: 'Selesai', reset: 'Reset', cancel: 'Batal', groups: 'Grup', myGroups: 'Grup saya', newGroup: 'Grup baru', group: 'Grup', groupName: 'Nama grup', dropHere: 'Seret anggota ke sini', members: 'anggota', createGroup: 'Buat grup', ungroup: 'Lepas grup', removeFromGroup: 'Keluarkan dari grup', expandGroup: 'Buka grup', collapseGroup: 'Tutup grup', noGroups: 'Belum ada grup', fit: 'Sesuaikan', holdToMove: 'Tahan 0,5 dtk untuk memindahkan', layoutSaved: 'Tata letak tersimpan', needTwo: 'Tambahkan minimal 2 anggota' },
  vi: { editLayout: 'Chỉnh bố cục', done: 'Xong', reset: 'Đặt lại', cancel: 'Hủy', groups: 'Nhóm', myGroups: 'Nhóm của tôi', newGroup: 'Nhóm mới', group: 'Nhóm', groupName: 'Tên nhóm', dropHere: 'Kéo thành viên vào đây', members: 'thành viên', createGroup: 'Tạo nhóm', ungroup: 'Bỏ nhóm', removeFromGroup: 'Xóa khỏi nhóm', expandGroup: 'Mở nhóm', collapseGroup: 'Thu gọn nhóm', noGroups: 'Chưa có nhóm', fit: 'Vừa khung', holdToMove: 'Giữ 0,5 giây để di chuyển', layoutSaved: 'Đã lưu bố cục', needTwo: 'Thêm ít nhất 2 thành viên' },
  'zh-tw': { editLayout: '編輯版面', done: '完成', reset: '重設', cancel: '取消', groups: '群組', myGroups: '我的群組', newGroup: '新增群組', group: '群組', groupName: '群組名稱', dropHere: '將成員拖到這裡', members: '名成員', createGroup: '建立群組', ungroup: '取消群組', removeFromGroup: '移出群組', expandGroup: '展開群組', collapseGroup: '收合群組', noGroups: '尚未建立群組', fit: '符合畫面', holdToMove: '長按 0.5 秒移動', layoutSaved: '版面已儲存', needTwo: '請至少加入 2 名成員' },
  sv: { editLayout: 'Redigera layout', done: 'Klar', reset: 'Återställ', cancel: 'Avbryt', groups: 'Grupper', myGroups: 'Mina grupper', newGroup: 'Ny grupp', group: 'Grupp', groupName: 'Gruppnamn', dropHere: 'Dra medlemmar hit', members: 'medlemmar', createGroup: 'Skapa grupp', ungroup: 'Lös upp grupp', removeFromGroup: 'Ta bort från grupp', expandGroup: 'Expandera grupp', collapseGroup: 'Fäll ihop grupp', noGroups: 'Inga grupper ännu', fit: 'Anpassa', holdToMove: 'Håll 0,5 s för att flytta', layoutSaved: 'Layout sparad', needTwo: 'Lägg till minst 2 medlemmar' },
  ro: { editLayout: 'Editează aspectul', done: 'Gata', reset: 'Resetează', cancel: 'Anulează', groups: 'Grupuri', myGroups: 'Grupurile mele', newGroup: 'Grup nou', group: 'Grup', groupName: 'Numele grupului', dropHere: 'Trage membrii aici', members: 'membri', createGroup: 'Creează grup', ungroup: 'Degrupează', removeFromGroup: 'Scoate din grup', expandGroup: 'Extinde grupul', collapseGroup: 'Restrânge grupul', noGroups: 'Încă nu există grupuri', fit: 'Încadrează', holdToMove: 'Ține apăsat 0,5 s pentru mutare', layoutSaved: 'Aspect salvat', needTwo: 'Adaugă cel puțin 2 membri' },
  ur: { editLayout: 'لے آؤٹ میں ترمیم', done: 'مکمل', reset: 'ری سیٹ', cancel: 'منسوخ', groups: 'گروپس', myGroups: 'میرے گروپس', newGroup: 'نیا گروپ', group: 'گروپ', groupName: 'گروپ کا نام', dropHere: 'اراکین کو یہاں کھینچیں', members: 'اراکین', createGroup: 'گروپ بنائیں', ungroup: 'گروپ ختم کریں', removeFromGroup: 'گروپ سے نکالیں', expandGroup: 'گروپ کھولیں', collapseGroup: 'گروپ سمیٹیں', noGroups: 'ابھی کوئی گروپ نہیں', fit: 'فِٹ', holdToMove: 'منتقل کرنے کے لیے 0.5 سیکنڈ دبائیں', layoutSaved: 'لے آؤٹ محفوظ ہوگیا', needTwo: 'کم از کم 2 اراکین شامل کریں' },
  pcm: { editLayout: 'Edit layout', done: 'Done', reset: 'Reset', cancel: 'Cancel', groups: 'Groups', myGroups: 'My groups', newGroup: 'New group', group: 'Group', groupName: 'Group name', dropHere: 'Drag members come here', members: 'members', createGroup: 'Create group', ungroup: 'Scatter group', removeFromGroup: 'Comot from group', expandGroup: 'Open group', collapseGroup: 'Close group', noGroups: 'No group yet', fit: 'Fit', holdToMove: 'Hold am 0.5s to move', layoutSaved: 'Layout don save', needTwo: 'Add at least 2 members' },
  arz: { editLayout: 'عدّل الترتيب', done: 'تم', reset: 'رجّع', cancel: 'إلغاء', groups: 'الجروبات', myGroups: 'جروباتي', newGroup: 'جروب جديد', group: 'جروب', groupName: 'اسم الجروب', dropHere: 'اسحب الأعضاء هنا', members: 'أعضاء', createGroup: 'اعمل جروب', ungroup: 'فك الجروب', removeFromGroup: 'شيل من الجروب', expandGroup: 'افتح الجروب', collapseGroup: 'اقفل الجروب', noGroups: 'مفيش جروبات لسه', fit: 'ظبط', holdToMove: 'دوس 0.5 ثانية عشان تحرك', layoutSaved: 'الترتيب اتحفظ', needTwo: 'ضيف عضوين على الأقل' },
  mr: { editLayout: 'मांडणी संपादित करा', done: 'पूर्ण', reset: 'रीसेट', cancel: 'रद्द करा', groups: 'गट', myGroups: 'माझे गट', newGroup: 'नवा गट', group: 'गट', groupName: 'गटाचे नाव', dropHere: 'सदस्यांना येथे ड्रॅग करा', members: 'सदस्य', createGroup: 'गट तयार करा', ungroup: 'गट काढा', removeFromGroup: 'गटातून काढा', expandGroup: 'गट उघडा', collapseGroup: 'गट मिटवा', noGroups: 'अजून गट नाहीत', fit: 'फिट', holdToMove: 'हलवण्यासाठी 0.5 सेकंद दाबा', layoutSaved: 'मांडणी जतन झाली', needTwo: 'किमान 2 सदस्य जोडा' },
  te: { editLayout: 'లేఅవుట్ మార్చండి', done: 'పూర్తి', reset: 'రీసెట్', cancel: 'రద్దు', groups: 'గ్రూపులు', myGroups: 'నా గ్రూపులు', newGroup: 'కొత్త గ్రూప్', group: 'గ్రూప్', groupName: 'గ్రూప్ పేరు', dropHere: 'సభ్యులను ఇక్కడికి లాగండి', members: 'సభ్యులు', createGroup: 'గ్రూప్ సృష్టించండి', ungroup: 'గ్రూప్ తొలగించండి', removeFromGroup: 'గ్రూప్ నుంచి తీసేయండి', expandGroup: 'గ్రూప్ తెరవండి', collapseGroup: 'గ్రూప్ మూసేయండి', noGroups: 'ఇంకా గ్రూపులు లేవు', fit: 'ఫిట్', holdToMove: 'కదిలించడానికి 0.5 సెకన్లు నొక్కి ఉంచండి', layoutSaved: 'లేఅవుట్ సేవ్ అయింది', needTwo: 'కనీసం 2 సభ్యులను జోడించండి' },
  sw: { editLayout: 'Hariri mpangilio', done: 'Imekamilika', reset: 'Weka upya', cancel: 'Ghairi', groups: 'Makundi', myGroups: 'Makundi yangu', newGroup: 'Kundi jipya', group: 'Kundi', groupName: 'Jina la kundi', dropHere: 'Buruta wanachama hapa', members: 'wanachama', createGroup: 'Unda kundi', ungroup: 'Vunja kundi', removeFromGroup: 'Ondoa kwenye kundi', expandGroup: 'Fungua kundi', collapseGroup: 'Funga kundi', noGroups: 'Bado hakuna makundi', fit: 'Toshea', holdToMove: 'Shikilia sek 0.5 ili kusogeza', layoutSaved: 'Mpangilio umehifadhiwa', needTwo: 'Ongeza angalau wanachama 2' },
  ha: { editLayout: 'Gyara tsari', done: 'An gama', reset: 'Sake saita', cancel: 'Soke', groups: 'Rukuni', myGroups: 'Rukunaina', newGroup: 'Sabon rukuni', group: 'Rukuni', groupName: 'Sunan rukuni', dropHere: 'Ja mambobi nan', members: 'mambobi', createGroup: 'Ƙirƙiri rukuni', ungroup: 'Warware rukuni', removeFromGroup: 'Cire daga rukuni', expandGroup: 'Buɗe rukuni', collapseGroup: 'Rufe rukuni', noGroups: 'Babu rukuni tukuna', fit: 'Daidaita', holdToMove: 'Riƙe sakan 0.5 don motsawa', layoutSaved: 'An ajiye tsari', needTwo: 'Ƙara aƙalla mambobi 2' },
  el: { editLayout: 'Επεξεργασία διάταξης', done: 'Τέλος', reset: 'Επαναφορά', cancel: 'Ακύρωση', groups: 'Ομάδες', myGroups: 'Οι ομάδες μου', newGroup: 'Νέα ομάδα', group: 'Ομάδα', groupName: 'Όνομα ομάδας', dropHere: 'Σύρετε μέλη εδώ', members: 'μέλη', createGroup: 'Δημιουργία ομάδας', ungroup: 'Κατάργηση ομάδας', removeFromGroup: 'Αφαίρεση από ομάδα', expandGroup: 'Άνοιγμα ομάδας', collapseGroup: 'Σύμπτυξη ομάδας', noGroups: 'Δεν υπάρχουν ομάδες ακόμα', fit: 'Προσαρμογή', holdToMove: 'Κρατήστε 0,5 δευτ. για μετακίνηση', layoutSaved: 'Η διάταξη αποθηκεύτηκε', needTwo: 'Προσθέστε τουλάχιστον 2 μέλη' },
  cs: { editLayout: 'Upravit rozložení', done: 'Hotovo', reset: 'Obnovit', cancel: 'Zrušit', groups: 'Skupiny', myGroups: 'Moje skupiny', newGroup: 'Nová skupina', group: 'Skupina', groupName: 'Název skupiny', dropHere: 'Přetáhněte členy sem', members: 'členů', createGroup: 'Vytvořit skupinu', ungroup: 'Zrušit skupinu', removeFromGroup: 'Odebrat ze skupiny', expandGroup: 'Rozbalit skupinu', collapseGroup: 'Sbalit skupinu', noGroups: 'Zatím žádné skupiny', fit: 'Přizpůsobit', holdToMove: 'Podržte 0,5 s pro přesun', layoutSaved: 'Rozložení uloženo', needTwo: 'Přidejte alespoň 2 členy' },
};
