import type { SupportedLocale } from './locales';

export type NetworkExperienceCopy = {
  title: string;
  direct: string;
  qualified: string;
  thisRound: string;
  directNetwork: string;
  inProgress: string;
  rewarded: string;
  searchPlaceholder: string;
  noSearchResults: string;
  networkSize: string;
  recentGrowth: string;
  emptyTitle: string;
  emptyDescription: string;
  inviteFriend: string;
  connectTitle: string;
  connectDescription: string;
  connectWallet: string;
  loadError: string;
  retry: string;
  backToMine: string;
  invitedBy: string;
  showAll: string;
  noMatching: string;
};

export const NETWORK_EXPERIENCE_COPY: Record<SupportedLocale, NetworkExperienceCopy> = {
  en: {
    title: 'My Network', direct: 'Direct', qualified: 'Qualified', thisRound: 'This Round', directNetwork: 'Direct Network', inProgress: 'In Progress', rewarded: 'Rewarded', searchPlaceholder: 'Search wallet in your network', noSearchResults: 'No wallet found in your network.', networkSize: 'Network size', recentGrowth: 'Recent growth', emptyTitle: 'Your network starts here', emptyDescription: 'Invite an eligible new or returning user. Once they pass VeInvite entry checks, they will appear here automatically.', inviteFriend: 'Invite a friend', connectTitle: 'Connect to see your network', connectDescription: 'Your VeInvite network is available only in your verified wallet session.', connectWallet: 'Connect wallet', loadError: 'We could not load your network.', retry: 'Try again', backToMine: 'Back to my network', invitedBy: 'Invited by', showAll: 'Show all', noMatching: 'No matching direct branches.',
  },
  ko: {
    title: '내 네트워크', direct: '직접 초대', qualified: '미션 완료', thisRound: '이번 라운드', directNetwork: '직접 네트워크', inProgress: '진행 중', rewarded: '보상 완료', searchPlaceholder: '내 네트워크에서 지갑 검색', noSearchResults: '내 네트워크에서 일치하는 지갑을 찾지 못했어요.', networkSize: '네트워크 규모', recentGrowth: '최근 성장', emptyTitle: '여기서 네트워크가 시작돼요', emptyDescription: '자격을 갖춘 신규 또는 복귀 사용자를 초대해 보세요. VeInvite 참여 자격 검증을 통과하면 이곳에 자동으로 표시됩니다.', inviteFriend: '친구 초대하기', connectTitle: '지갑을 연결해 네트워크를 확인하세요', connectDescription: 'VeInvite 네트워크는 검증된 지갑 세션에서만 확인할 수 있어요.', connectWallet: '지갑 연결', loadError: '네트워크를 불러오지 못했어요.', retry: '다시 시도', backToMine: '내 네트워크로', invitedBy: '추천인', showAll: '전체 보기', noMatching: '조건에 맞는 직접 네트워크가 없어요.',
  },
  zh: {
    title: '我的网络', direct: '直接邀请', qualified: '已完成任务', thisRound: '本轮', directNetwork: '直接网络', inProgress: '进行中', rewarded: '已奖励', searchPlaceholder: '在我的网络中搜索钱包', noSearchResults: '你的网络中没有匹配的钱包。', networkSize: '网络规模', recentGrowth: '近期增长', emptyTitle: '你的网络从这里开始', emptyDescription: '邀请符合条件的新用户或回归用户。通过 VeInvite 参与资格验证后，他们会自动显示在这里。', inviteFriend: '邀请朋友', connectTitle: '连接钱包查看你的网络', connectDescription: 'VeInvite 网络仅能在已验证的钱包会话中查看。', connectWallet: '连接钱包', loadError: '无法加载你的网络。', retry: '重试', backToMine: '返回我的网络', invitedBy: '邀请人', showAll: '显示全部', noMatching: '没有符合条件的直接分支。',
  },
  hi: {
    title: 'मेरा नेटवर्क', direct: 'सीधे आमंत्रण', qualified: 'मिशन पूरा', thisRound: 'इस राउंड में', directNetwork: 'सीधा नेटवर्क', inProgress: 'जारी है', rewarded: 'रिवॉर्ड मिला', searchPlaceholder: 'अपने नेटवर्क में वॉलेट खोजें', noSearchResults: 'आपके नेटवर्क में कोई मेल खाता वॉलेट नहीं मिला।', networkSize: 'नेटवर्क का आकार', recentGrowth: 'हाल की बढ़त', emptyTitle: 'आपका नेटवर्क यहीं से शुरू होता है', emptyDescription: 'योग्य नए या लौटने वाले उपयोगकर्ता को आमंत्रित करें। VeInvite की पात्रता जाँच पास करते ही वे यहाँ अपने-आप दिखेंगे।', inviteFriend: 'दोस्त को आमंत्रित करें', connectTitle: 'अपना नेटवर्क देखने के लिए वॉलेट कनेक्ट करें', connectDescription: 'VeInvite नेटवर्क केवल सत्यापित वॉलेट सत्र में उपलब्ध है।', connectWallet: 'वॉलेट कनेक्ट करें', loadError: 'आपका नेटवर्क लोड नहीं हो सका।', retry: 'फिर कोशिश करें', backToMine: 'मेरे नेटवर्क पर वापस', invitedBy: 'आमंत्रित किया', showAll: 'सभी दिखाएँ', noMatching: 'कोई मेल खाती सीधी शाखा नहीं है।',
  },
  es: {
    title: 'Mi red', direct: 'Directos', qualified: 'Misión completada', thisRound: 'Esta ronda', directNetwork: 'Red directa', inProgress: 'En progreso', rewarded: 'Recompensado', searchPlaceholder: 'Buscar wallet en tu red', noSearchResults: 'No se encontró esa wallet en tu red.', networkSize: 'Tamaño de red', recentGrowth: 'Crecimiento reciente', emptyTitle: 'Tu red empieza aquí', emptyDescription: 'Invita a un usuario nuevo o recurrente elegible. Cuando supere la verificación de VeInvite, aparecerá aquí automáticamente.', inviteFriend: 'Invitar a un amigo', connectTitle: 'Conecta tu wallet para ver tu red', connectDescription: 'Tu red VeInvite solo está disponible en una sesión de wallet verificada.', connectWallet: 'Conectar wallet', loadError: 'No pudimos cargar tu red.', retry: 'Reintentar', backToMine: 'Volver a mi red', invitedBy: 'Invitado por', showAll: 'Mostrar todo', noMatching: 'No hay ramas directas que coincidan.',
  },
  ja: {
    title: 'マイネットワーク', direct: '直接招待', qualified: 'ミッション完了', thisRound: '今ラウンド', directNetwork: '直接ネットワーク', inProgress: '進行中', rewarded: '報酬済み', searchPlaceholder: 'ネットワーク内のウォレットを検索', noSearchResults: 'ネットワーク内に一致するウォレットがありません。', networkSize: 'ネットワーク規模', recentGrowth: '最近の成長', emptyTitle: 'ここからネットワークが始まります', emptyDescription: '対象となる新規・復帰ユーザーを招待してください。VeInvite の参加資格確認を通過すると自動的に表示されます。', inviteFriend: '友だちを招待', connectTitle: 'ウォレットを接続してネットワークを確認', connectDescription: 'VeInvite ネットワークは確認済みのウォレットセッションでのみ表示されます。', connectWallet: 'ウォレット接続', loadError: 'ネットワークを読み込めませんでした。', retry: '再試行', backToMine: '自分のネットワークへ', invitedBy: '招待者', showAll: 'すべて表示', noMatching: '一致する直接ネットワークはありません。',
  },
  it: {
    title: 'La mia rete', direct: 'Diretti', qualified: 'Missione completata', thisRound: 'Questo round', directNetwork: 'Rete diretta', inProgress: 'In corso', rewarded: 'Premiato', searchPlaceholder: 'Cerca un wallet nella tua rete', noSearchResults: 'Nessun wallet trovato nella tua rete.', networkSize: 'Dimensione rete', recentGrowth: 'Crescita recente', emptyTitle: 'La tua rete inizia qui', emptyDescription: 'Invita un nuovo utente o un utente di ritorno idoneo. Dopo i controlli di accesso VeInvite comparirà qui automaticamente.', inviteFriend: 'Invita un amico', connectTitle: 'Connetti il wallet per vedere la tua rete', connectDescription: 'La rete VeInvite è disponibile solo in una sessione wallet verificata.', connectWallet: 'Connetti wallet', loadError: 'Non siamo riusciti a caricare la tua rete.', retry: 'Riprova', backToMine: 'Torna alla mia rete', invitedBy: 'Invitato da', showAll: 'Mostra tutto', noMatching: 'Nessun ramo diretto corrispondente.',
  },
  tr: {
    title: 'Ağım', direct: 'Doğrudan', qualified: 'Görev tamamlandı', thisRound: 'Bu tur', directNetwork: 'Doğrudan ağ', inProgress: 'Devam ediyor', rewarded: 'Ödüllendirildi', searchPlaceholder: 'Ağında cüzdan ara', noSearchResults: 'Ağında eşleşen cüzdan bulunamadı.', networkSize: 'Ağ büyüklüğü', recentGrowth: 'Son büyüme', emptyTitle: 'Ağın burada başlıyor', emptyDescription: 'Uygun yeni veya geri dönen bir kullanıcıyı davet et. VeInvite giriş kontrollerini geçince burada otomatik görünür.', inviteFriend: 'Arkadaş davet et', connectTitle: 'Ağını görmek için cüzdanını bağla', connectDescription: 'VeInvite ağın yalnızca doğrulanmış cüzdan oturumunda görüntülenebilir.', connectWallet: 'Cüzdanı bağla', loadError: 'Ağın yüklenemedi.', retry: 'Tekrar dene', backToMine: 'Ağıma dön', invitedBy: 'Davet eden', showAll: 'Tümünü göster', noMatching: 'Eşleşen doğrudan dal yok.',
  },
  nl: {
    title: 'Mijn netwerk', direct: 'Direct', qualified: 'Missie voltooid', thisRound: 'Deze ronde', directNetwork: 'Direct netwerk', inProgress: 'Bezig', rewarded: 'Beloond', searchPlaceholder: 'Zoek wallet in je netwerk', noSearchResults: 'Geen wallet gevonden in je netwerk.', networkSize: 'Netwerkgrootte', recentGrowth: 'Recente groei', emptyTitle: 'Je netwerk begint hier', emptyDescription: 'Nodig een geschikte nieuwe of terugkerende gebruiker uit. Na de VeInvite-toelatingscontrole verschijnt die automatisch hier.', inviteFriend: 'Vriend uitnodigen', connectTitle: 'Verbind je wallet om je netwerk te bekijken', connectDescription: 'Je VeInvite-netwerk is alleen beschikbaar in een geverifieerde walletsessie.', connectWallet: 'Wallet verbinden', loadError: 'We konden je netwerk niet laden.', retry: 'Opnieuw proberen', backToMine: 'Terug naar mijn netwerk', invitedBy: 'Uitgenodigd door', showAll: 'Alles tonen', noMatching: 'Geen passende directe takken.',
  },
  de: {
    title: 'Mein Netzwerk', direct: 'Direkt', qualified: 'Mission abgeschlossen', thisRound: 'Diese Runde', directNetwork: 'Direktes Netzwerk', inProgress: 'In Arbeit', rewarded: 'Belohnt', searchPlaceholder: 'Wallet in deinem Netzwerk suchen', noSearchResults: 'Keine passende Wallet in deinem Netzwerk gefunden.', networkSize: 'Netzwerkgröße', recentGrowth: 'Jüngstes Wachstum', emptyTitle: 'Dein Netzwerk startet hier', emptyDescription: 'Lade einen berechtigten neuen oder zurückkehrenden Nutzer ein. Nach den VeInvite-Zugangsprüfungen erscheint er automatisch hier.', inviteFriend: 'Freund einladen', connectTitle: 'Wallet verbinden, um dein Netzwerk zu sehen', connectDescription: 'Dein VeInvite-Netzwerk ist nur in einer verifizierten Wallet-Sitzung verfügbar.', connectWallet: 'Wallet verbinden', loadError: 'Dein Netzwerk konnte nicht geladen werden.', retry: 'Erneut versuchen', backToMine: 'Zurück zu meinem Netzwerk', invitedBy: 'Eingeladen von', showAll: 'Alle anzeigen', noMatching: 'Keine passenden direkten Zweige.',
  },
  fr: {
    title: 'Mon réseau', direct: 'Directs', qualified: 'Mission terminée', thisRound: 'Ce round', directNetwork: 'Réseau direct', inProgress: 'En cours', rewarded: 'Récompensé', searchPlaceholder: 'Rechercher un wallet dans votre réseau', noSearchResults: 'Aucun wallet correspondant dans votre réseau.', networkSize: 'Taille du réseau', recentGrowth: 'Croissance récente', emptyTitle: 'Votre réseau commence ici', emptyDescription: 'Invitez un nouvel utilisateur ou un utilisateur de retour éligible. Après les contrôles VeInvite, il apparaîtra automatiquement ici.', inviteFriend: 'Inviter un ami', connectTitle: 'Connectez votre wallet pour voir votre réseau', connectDescription: 'Votre réseau VeInvite est disponible uniquement dans une session wallet vérifiée.', connectWallet: 'Connecter le wallet', loadError: 'Impossible de charger votre réseau.', retry: 'Réessayer', backToMine: 'Retour à mon réseau', invitedBy: 'Invité par', showAll: 'Tout afficher', noMatching: 'Aucune branche directe correspondante.',
  },
  ar: {
    title: 'شبكتي', direct: 'دعوات مباشرة', qualified: 'المهمة مكتملة', thisRound: 'هذه الجولة', directNetwork: 'الشبكة المباشرة', inProgress: 'قيد التقدم', rewarded: 'تمت المكافأة', searchPlaceholder: 'ابحث عن محفظة داخل شبكتك', noSearchResults: 'لم نعثر على محفظة مطابقة داخل شبكتك.', networkSize: 'حجم الشبكة', recentGrowth: 'النمو الأخير', emptyTitle: 'شبكتك تبدأ من هنا', emptyDescription: 'ادعُ مستخدمًا جديدًا أو عائدًا مؤهلًا. بعد اجتياز فحوصات VeInvite سيظهر هنا تلقائيًا.', inviteFriend: 'دعوة صديق', connectTitle: 'اربط محفظتك لعرض شبكتك', connectDescription: 'شبكة VeInvite متاحة فقط ضمن جلسة محفظة موثّقة.', connectWallet: 'ربط المحفظة', loadError: 'تعذر تحميل شبكتك.', retry: 'إعادة المحاولة', backToMine: 'العودة إلى شبكتي', invitedBy: 'تمت دعوته بواسطة', showAll: 'عرض الكل', noMatching: 'لا توجد فروع مباشرة مطابقة.',
  },
  bn: {
    title: 'আমার নেটওয়ার্ক', direct: 'সরাসরি', qualified: 'মিশন সম্পন্ন', thisRound: 'এই রাউন্ড', directNetwork: 'সরাসরি নেটওয়ার্ক', inProgress: 'চলছে', rewarded: 'পুরস্কৃত', searchPlaceholder: 'আপনার নেটওয়ার্কে ওয়ালেট খুঁজুন', noSearchResults: 'আপনার নেটওয়ার্কে মিল থাকা ওয়ালেট পাওয়া যায়নি।', networkSize: 'নেটওয়ার্কের আকার', recentGrowth: 'সাম্প্রতিক বৃদ্ধি', emptyTitle: 'আপনার নেটওয়ার্ক এখান থেকেই শুরু', emptyDescription: 'যোগ্য নতুন বা ফিরে আসা ব্যবহারকারীকে আমন্ত্রণ করুন। VeInvite-এর প্রবেশ যাচাই পাস করলে তারা এখানে স্বয়ংক্রিয়ভাবে দেখা যাবে।', inviteFriend: 'বন্ধুকে আমন্ত্রণ করুন', connectTitle: 'নেটওয়ার্ক দেখতে ওয়ালেট সংযুক্ত করুন', connectDescription: 'VeInvite নেটওয়ার্ক শুধু যাচাইকৃত ওয়ালেট সেশনে দেখা যায়।', connectWallet: 'ওয়ালেট সংযুক্ত করুন', loadError: 'আপনার নেটওয়ার্ক লোড করা যায়নি।', retry: 'আবার চেষ্টা করুন', backToMine: 'আমার নেটওয়ার্কে ফিরুন', invitedBy: 'আমন্ত্রণকারী', showAll: 'সব দেখুন', noMatching: 'মিল থাকা সরাসরি শাখা নেই।',
  },
  pt: {
    title: 'Minha rede', direct: 'Diretos', qualified: 'Missão concluída', thisRound: 'Nesta rodada', directNetwork: 'Rede direta', inProgress: 'Em andamento', rewarded: 'Recompensado', searchPlaceholder: 'Buscar carteira na sua rede', noSearchResults: 'Nenhuma carteira correspondente foi encontrada na sua rede.', networkSize: 'Tamanho da rede', recentGrowth: 'Crescimento recente', emptyTitle: 'Sua rede começa aqui', emptyDescription: 'Convide um usuário novo ou recorrente elegível. Depois de passar pelas verificações de entrada do VeInvite, ele aparecerá aqui automaticamente.', inviteFriend: 'Convidar um amigo', connectTitle: 'Conecte sua carteira para ver sua rede', connectDescription: 'Sua rede VeInvite só fica disponível em uma sessão de carteira verificada.', connectWallet: 'Conectar carteira', loadError: 'Não foi possível carregar sua rede.', retry: 'Tentar novamente', backToMine: 'Voltar à minha rede', invitedBy: 'Convidado por', showAll: 'Mostrar tudo', noMatching: 'Nenhum ramo direto correspondente.',
  },
  ru: {
    title: 'Моя сеть', direct: 'Прямые', qualified: 'Миссия выполнена', thisRound: 'Этот раунд', directNetwork: 'Прямая сеть', inProgress: 'В процессе', rewarded: 'Награждён', searchPlaceholder: 'Найти кошелёк в своей сети', noSearchResults: 'В вашей сети нет подходящего кошелька.', networkSize: 'Размер сети', recentGrowth: 'Недавний рост', emptyTitle: 'Ваша сеть начинается здесь', emptyDescription: 'Пригласите подходящего нового или вернувшегося пользователя. После проверки входных условий VeInvite он автоматически появится здесь.', inviteFriend: 'Пригласить друга', connectTitle: 'Подключите кошелёк, чтобы увидеть сеть', connectDescription: 'Сеть VeInvite доступна только в подтверждённой сессии кошелька.', connectWallet: 'Подключить кошелёк', loadError: 'Не удалось загрузить вашу сеть.', retry: 'Повторить', backToMine: 'Вернуться к моей сети', invitedBy: 'Пригласил', showAll: 'Показать все', noMatching: 'Нет подходящих прямых веток.',
  },
  id: {
    title: 'Jaringan saya', direct: 'Langsung', qualified: 'Misi selesai', thisRound: 'Ronde ini', directNetwork: 'Jaringan langsung', inProgress: 'Sedang berjalan', rewarded: 'Sudah diberi hadiah', searchPlaceholder: 'Cari wallet di jaringan Anda', noSearchResults: 'Wallet yang cocok tidak ditemukan di jaringan Anda.', networkSize: 'Ukuran jaringan', recentGrowth: 'Pertumbuhan terbaru', emptyTitle: 'Jaringan Anda dimulai di sini', emptyDescription: 'Undang pengguna baru atau kembali yang memenuhi syarat. Setelah lolos pemeriksaan masuk VeInvite, mereka akan muncul otomatis di sini.', inviteFriend: 'Undang teman', connectTitle: 'Hubungkan wallet untuk melihat jaringan Anda', connectDescription: 'Jaringan VeInvite hanya tersedia dalam sesi wallet yang terverifikasi.', connectWallet: 'Hubungkan wallet', loadError: 'Jaringan Anda tidak dapat dimuat.', retry: 'Coba lagi', backToMine: 'Kembali ke jaringan saya', invitedBy: 'Diundang oleh', showAll: 'Tampilkan semua', noMatching: 'Tidak ada cabang langsung yang cocok.',
  },
  vi: {
    title: 'Mạng lưới của tôi', direct: 'Mời trực tiếp', qualified: 'Đã hoàn thành', thisRound: 'Vòng này', directNetwork: 'Mạng trực tiếp', inProgress: 'Đang thực hiện', rewarded: 'Đã nhận thưởng', searchPlaceholder: 'Tìm ví trong mạng lưới của bạn', noSearchResults: 'Không tìm thấy ví phù hợp trong mạng lưới.', networkSize: 'Quy mô mạng', recentGrowth: 'Tăng trưởng gần đây', emptyTitle: 'Mạng lưới của bạn bắt đầu từ đây', emptyDescription: 'Mời người dùng mới hoặc quay lại đủ điều kiện. Sau khi vượt qua kiểm tra đầu vào VeInvite, họ sẽ tự động xuất hiện tại đây.', inviteFriend: 'Mời bạn bè', connectTitle: 'Kết nối ví để xem mạng lưới', connectDescription: 'Mạng lưới VeInvite chỉ hiển thị trong phiên ví đã được xác minh.', connectWallet: 'Kết nối ví', loadError: 'Không thể tải mạng lưới của bạn.', retry: 'Thử lại', backToMine: 'Về mạng lưới của tôi', invitedBy: 'Được mời bởi', showAll: 'Hiện tất cả', noMatching: 'Không có nhánh trực tiếp phù hợp.',
  },
  'zh-tw': {
    title: '我的網絡', direct: '直接邀請', qualified: '任務完成', thisRound: '本輪', directNetwork: '直接網絡', inProgress: '進行中', rewarded: '已獎勵', searchPlaceholder: '在我的網絡中搜尋錢包', noSearchResults: '你的網絡中沒有相符的錢包。', networkSize: '網絡規模', recentGrowth: '近期成長', emptyTitle: '你的網絡從這裡開始', emptyDescription: '邀請符合資格的新用戶或回歸用戶。通過 VeInvite 參與資格驗證後，他們會自動顯示在這裡。', inviteFriend: '邀請朋友', connectTitle: '連接錢包查看你的網絡', connectDescription: 'VeInvite 網絡僅能在已驗證的錢包工作階段查看。', connectWallet: '連接錢包', loadError: '無法載入你的網絡。', retry: '重試', backToMine: '返回我的網絡', invitedBy: '邀請人', showAll: '顯示全部', noMatching: '沒有符合條件的直接分支。',
  },
  sv: {
    title: 'Mitt nätverk', direct: 'Direkta', qualified: 'Uppdrag klart', thisRound: 'Denna runda', directNetwork: 'Direkt nätverk', inProgress: 'Pågår', rewarded: 'Belönad', searchPlaceholder: 'Sök plånbok i ditt nätverk', noSearchResults: 'Ingen matchande plånbok hittades i ditt nätverk.', networkSize: 'Nätverksstorlek', recentGrowth: 'Senaste tillväxt', emptyTitle: 'Ditt nätverk börjar här', emptyDescription: 'Bjud in en behörig ny eller återvändande användare. När VeInvite-kontrollerna är godkända visas personen automatiskt här.', inviteFriend: 'Bjud in en vän', connectTitle: 'Anslut plånboken för att se ditt nätverk', connectDescription: 'Ditt VeInvite-nätverk är endast tillgängligt i en verifierad plånbokssession.', connectWallet: 'Anslut plånbok', loadError: 'Ditt nätverk kunde inte laddas.', retry: 'Försök igen', backToMine: 'Tillbaka till mitt nätverk', invitedBy: 'Inbjuden av', showAll: 'Visa alla', noMatching: 'Inga matchande direkta grenar.',
  },
  ro: {
    title: 'Rețeaua mea', direct: 'Direcți', qualified: 'Misiune finalizată', thisRound: 'Runda aceasta', directNetwork: 'Rețea directă', inProgress: 'În desfășurare', rewarded: 'Recompensat', searchPlaceholder: 'Caută portofel în rețeaua ta', noSearchResults: 'Nu am găsit un portofel corespunzător în rețeaua ta.', networkSize: 'Mărimea rețelei', recentGrowth: 'Creștere recentă', emptyTitle: 'Rețeaua ta începe aici', emptyDescription: 'Invită un utilizator nou sau revenit eligibil. După verificările de acces VeInvite, va apărea automat aici.', inviteFriend: 'Invită un prieten', connectTitle: 'Conectează portofelul pentru a vedea rețeaua', connectDescription: 'Rețeaua VeInvite este disponibilă numai într-o sesiune de portofel verificată.', connectWallet: 'Conectează portofelul', loadError: 'Nu am putut încărca rețeaua ta.', retry: 'Încearcă din nou', backToMine: 'Înapoi la rețeaua mea', invitedBy: 'Invitat de', showAll: 'Arată tot', noMatching: 'Nu există ramuri directe corespunzătoare.',
  },
  ur: {
    title: 'میرا نیٹ ورک', direct: 'براہ راست', qualified: 'مشن مکمل', thisRound: 'اس راؤنڈ میں', directNetwork: 'براہ راست نیٹ ورک', inProgress: 'جاری ہے', rewarded: 'انعام مل گیا', searchPlaceholder: 'اپنے نیٹ ورک میں والٹ تلاش کریں', noSearchResults: 'آپ کے نیٹ ورک میں کوئی مماثل والٹ نہیں ملا۔', networkSize: 'نیٹ ورک کا سائز', recentGrowth: 'حالیہ اضافہ', emptyTitle: 'آپ کا نیٹ ورک یہاں سے شروع ہوتا ہے', emptyDescription: 'کسی اہل نئے یا واپس آنے والے صارف کو دعوت دیں۔ VeInvite کی اہلیت جانچ پاس کرتے ہی وہ خودکار طور پر یہاں نظر آئے گا۔', inviteFriend: 'دوست کو دعوت دیں', connectTitle: 'اپنا نیٹ ورک دیکھنے کے لیے والٹ جوڑیں', connectDescription: 'VeInvite نیٹ ورک صرف تصدیق شدہ والٹ سیشن میں دستیاب ہے۔', connectWallet: 'والٹ جوڑیں', loadError: 'آپ کا نیٹ ورک لوڈ نہیں ہو سکا۔', retry: 'دوبارہ کوشش کریں', backToMine: 'میرے نیٹ ورک پر واپس', invitedBy: 'دعوت دینے والا', showAll: 'سب دکھائیں', noMatching: 'کوئی مماثل براہ راست شاخ نہیں۔',
  },
  pcm: {
    title: 'My Network', direct: 'Direct invite', qualified: 'Mission don complete', thisRound: 'Dis round', directNetwork: 'Direct network', inProgress: 'E dey go on', rewarded: 'Reward don land', searchPlaceholder: 'Find wallet for your network', noSearchResults: 'We no find any matching wallet for your network.', networkSize: 'Network size', recentGrowth: 'Recent growth', emptyTitle: 'Your network dey start from here', emptyDescription: 'Invite new or returning user wey qualify. Once dem pass VeInvite entry check, dem go show here automatically.', inviteFriend: 'Invite friend', connectTitle: 'Connect wallet make you see your network', connectDescription: 'You fit see your VeInvite network only for verified wallet session.', connectWallet: 'Connect wallet', loadError: 'We no fit load your network.', retry: 'Try again', backToMine: 'Back to my network', invitedBy: 'Who invite am', showAll: 'Show all', noMatching: 'No direct branch match.',
  },
  arz: {
    title: 'شبكتي', direct: 'دعوات مباشرة', qualified: 'المهمة خلصت', thisRound: 'الجولة دي', directNetwork: 'الشبكة المباشرة', inProgress: 'شغالة', rewarded: 'خد المكافأة', searchPlaceholder: 'دوّر على محفظة جوه شبكتك', noSearchResults: 'ملقيناش محفظة مطابقة جوه شبكتك.', networkSize: 'حجم الشبكة', recentGrowth: 'النمو الأخير', emptyTitle: 'شبكتك بتبدأ من هنا', emptyDescription: 'اعزم مستخدم جديد أو راجع يكون مؤهل. أول ما يعدّي فحوصات VeInvite هيظهر هنا تلقائي.', inviteFriend: 'اعزم صاحبك', connectTitle: 'اربط محفظتك عشان تشوف شبكتك', connectDescription: 'شبكة VeInvite بتظهر بس في جلسة محفظة متأكد منها.', connectWallet: 'اربط المحفظة', loadError: 'مقدرناش نحمّل شبكتك.', retry: 'جرّب تاني', backToMine: 'ارجع لشبكتي', invitedBy: 'اتعزم بواسطة', showAll: 'اعرض الكل', noMatching: 'مفيش فروع مباشرة مطابقة.',
  },
  mr: {
    title: 'माझे नेटवर्क', direct: 'थेट आमंत्रणे', qualified: 'मिशन पूर्ण', thisRound: 'या राउंडमध्ये', directNetwork: 'थेट नेटवर्क', inProgress: 'सुरू आहे', rewarded: 'बक्षीस मिळाले', searchPlaceholder: 'तुमच्या नेटवर्कमध्ये वॉलेट शोधा', noSearchResults: 'तुमच्या नेटवर्कमध्ये जुळणारे वॉलेट सापडले नाही.', networkSize: 'नेटवर्कचा आकार', recentGrowth: 'अलीकडची वाढ', emptyTitle: 'तुमचे नेटवर्क इथून सुरू होते', emptyDescription: 'पात्र नवीन किंवा परत आलेल्या वापरकर्त्याला आमंत्रित करा. VeInvite प्रवेश तपासणी पूर्ण झाल्यावर ते येथे आपोआप दिसतील.', inviteFriend: 'मित्राला आमंत्रित करा', connectTitle: 'नेटवर्क पाहण्यासाठी वॉलेट जोडा', connectDescription: 'VeInvite नेटवर्क फक्त पडताळलेल्या वॉलेट सत्रात उपलब्ध आहे.', connectWallet: 'वॉलेट जोडा', loadError: 'तुमचे नेटवर्क लोड करता आले नाही.', retry: 'पुन्हा प्रयत्न करा', backToMine: 'माझ्या नेटवर्कवर परत', invitedBy: 'आमंत्रित करणारा', showAll: 'सर्व दाखवा', noMatching: 'जुळणाऱ्या थेट शाखा नाहीत.',
  },
  te: {
    title: 'నా నెట్‌వర్క్', direct: 'నేరుగా ఆహ్వానాలు', qualified: 'మిషన్ పూర్తైంది', thisRound: 'ఈ రౌండ్', directNetwork: 'నేరుగా నెట్‌వర్క్', inProgress: 'కొనసాగుతోంది', rewarded: 'రివార్డ్ పొందారు', searchPlaceholder: 'మీ నెట్‌వర్క్‌లో వాలెట్ వెతకండి', noSearchResults: 'మీ నెట్‌వర్క్‌లో సరిపోలే వాలెట్ దొరకలేదు.', networkSize: 'నెట్‌వర్క్ పరిమాణం', recentGrowth: 'ఇటీవలి వృద్ధి', emptyTitle: 'మీ నెట్‌వర్క్ ఇక్కడి నుంచే మొదలవుతుంది', emptyDescription: 'అర్హత ఉన్న కొత్త లేదా తిరిగి వచ్చిన వినియోగదారుని ఆహ్వానించండి. VeInvite ప్రవేశ తనిఖీలు పూర్తి చేసిన తర్వాత వారు ఇక్కడ ఆటోమేటిక్‌గా కనిపిస్తారు.', inviteFriend: 'స్నేహితుడిని ఆహ్వానించండి', connectTitle: 'నెట్‌వర్క్ చూడటానికి వాలెట్ కనెక్ట్ చేయండి', connectDescription: 'VeInvite నెట్‌వర్క్ ధృవీకరించిన వాలెట్ సెషన్‌లో మాత్రమే అందుబాటులో ఉంటుంది.', connectWallet: 'వాలెట్ కనెక్ట్ చేయండి', loadError: 'మీ నెట్‌వర్క్‌ను లోడ్ చేయలేకపోయాం.', retry: 'మళ్లీ ప్రయత్నించండి', backToMine: 'నా నెట్‌వర్క్‌కు తిరిగి', invitedBy: 'ఆహ్వానించిన వారు', showAll: 'అన్నీ చూపించు', noMatching: 'సరిపోలే నేరుగా శాఖలు లేవు.',
  },
  sw: {
    title: 'Mtandao wangu', direct: 'Mialiko ya moja kwa moja', qualified: 'Jukumu limekamilika', thisRound: 'Raundi hii', directNetwork: 'Mtandao wa moja kwa moja', inProgress: 'Inaendelea', rewarded: 'Amezawadiwa', searchPlaceholder: 'Tafuta pochi kwenye mtandao wako', noSearchResults: 'Hakuna pochi inayolingana iliyopatikana kwenye mtandao wako.', networkSize: 'Ukubwa wa mtandao', recentGrowth: 'Ukuaji wa karibuni', emptyTitle: 'Mtandao wako unaanzia hapa', emptyDescription: 'Alika mtumiaji mpya au anayerejea anayestahiki. Akipita ukaguzi wa kuingia VeInvite ataonekana hapa kiotomatiki.', inviteFriend: 'Alika rafiki', connectTitle: 'Unganisha pochi kuona mtandao wako', connectDescription: 'Mtandao wa VeInvite unapatikana tu kwenye kikao cha pochi kilichothibitishwa.', connectWallet: 'Unganisha pochi', loadError: 'Hatukuweza kupakia mtandao wako.', retry: 'Jaribu tena', backToMine: 'Rudi kwenye mtandao wangu', invitedBy: 'Amealikiwa na', showAll: 'Onyesha yote', noMatching: 'Hakuna matawi ya moja kwa moja yanayolingana.',
  },
  ha: {
    title: 'Cibiyata', direct: 'Gayyata kai tsaye', qualified: 'An kammala aiki', thisRound: 'Wannan zagaye', directNetwork: 'Cibiya kai tsaye', inProgress: 'Ana ci gaba', rewarded: 'An ba da lada', searchPlaceholder: 'Nemo wallet a cibiyarka', noSearchResults: 'Ba a sami wallet mai dacewa a cibiyarka ba.', networkSize: 'Girman cibiya', recentGrowth: 'Ci gaban kwanan nan', emptyTitle: 'Cibiyarka tana farawa daga nan', emptyDescription: 'Gayyaci sabon mai amfani ko wanda ya dawo kuma ya cancanta. Bayan ya wuce binciken shiga na VeInvite zai bayyana nan kai tsaye.', inviteFriend: 'Gayyaci aboki', connectTitle: 'Haɗa wallet don ganin cibiyarka', connectDescription: 'Ana ganin cibiyar VeInvite ne kawai a zaman wallet da aka tabbatar.', connectWallet: 'Haɗa wallet', loadError: 'Ba mu iya loda cibiyarka ba.', retry: 'Sake gwadawa', backToMine: 'Koma cibiyata', invitedBy: 'Wanda ya gayyata', showAll: 'Nuna duka', noMatching: 'Babu reshe kai tsaye da ya dace.',
  },
  el: {
    title: 'Το δίκτυό μου', direct: 'Άμεσες προσκλήσεις', qualified: 'Αποστολή ολοκληρώθηκε', thisRound: 'Αυτός ο γύρος', directNetwork: 'Άμεσο δίκτυο', inProgress: 'Σε εξέλιξη', rewarded: 'Ανταμείφθηκε', searchPlaceholder: 'Αναζήτηση wallet στο δίκτυό σου', noSearchResults: 'Δεν βρέθηκε αντίστοιχο wallet στο δίκτυό σου.', networkSize: 'Μέγεθος δικτύου', recentGrowth: 'Πρόσφατη ανάπτυξη', emptyTitle: 'Το δίκτυό σου ξεκινά εδώ', emptyDescription: 'Προσκάλεσε έναν επιλέξιμο νέο ή επιστρέφοντα χρήστη. Μόλις περάσει τους ελέγχους εισόδου του VeInvite, θα εμφανιστεί εδώ αυτόματα.', inviteFriend: 'Πρόσκληση φίλου', connectTitle: 'Σύνδεσε το wallet για να δεις το δίκτυό σου', connectDescription: 'Το δίκτυο VeInvite είναι διαθέσιμο μόνο σε επαληθευμένη συνεδρία wallet.', connectWallet: 'Σύνδεση wallet', loadError: 'Δεν μπορέσαμε να φορτώσουμε το δίκτυό σου.', retry: 'Δοκίμασε ξανά', backToMine: 'Πίσω στο δίκτυό μου', invitedBy: 'Προσκλήθηκε από', showAll: 'Εμφάνιση όλων', noMatching: 'Δεν υπάρχουν άμεσοι κλάδοι που ταιριάζουν.',
  },
};
