import type { SupportedLocale } from './locales';

export type NetworkExploreCopy = {
  exploreNetwork: string;
  exploreTitle: string;
  exploreDescription: string;
  myNetwork: string;
  publicSettings: string;
  publicEnabled: string;
  publicEnabledNote: string;
  discoverable: string;
  discoverableNote: string;
  noPublicNetworks: string;
  walletPlaceholder: string;
  openNetwork: string;
  backToMyNetwork: string;
  viewing: string;
  visibleNetwork: string;
  privateBranchesHidden: string;
  visibilityError: string;
  networkPrivate: string;
  maintenance: string;
};

export const NETWORK_EXPLORE_COPY: Record<SupportedLocale, NetworkExploreCopy> = {
  en: { exploreNetwork:'Explore Network', exploreTitle:'Explore public networks', exploreDescription:'Browse public VeInvite networks with the same interactive canvas. Private branches stay hidden.', myNetwork:'My Network', publicSettings:'Public Network', publicEnabled:'Public access', publicEnabledNote:'Allow people with your wallet address to view your public network.', discoverable:'Show in Explore', discoverableNote:'Let your network appear in the Explore list.', noPublicNetworks:'No public networks are discoverable yet.', walletPlaceholder:'Enter an exact wallet address', openNetwork:'Open network', backToMyNetwork:'Back to my network', viewing:'Exploring', visibleNetwork:'Public network', privateBranchesHidden:'Private branches are hidden', visibilityError:'Could not update Public Network settings.', networkPrivate:'This network is private.', maintenance:'Network is temporarily unavailable.' },
  ko: { exploreNetwork:'다른 네트워크 둘러보기', exploreTitle:'공개 네트워크 둘러보기', exploreDescription:'같은 인터랙티브 캔버스로 공개된 VeInvite 네트워크를 둘러보세요. 비공개 브랜치는 표시되지 않습니다.', myNetwork:'내 네트워크', publicSettings:'공개 네트워크', publicEnabled:'공개 허용', publicEnabledNote:'내 지갑 주소를 아는 사람이 공개 네트워크를 볼 수 있게 합니다.', discoverable:'Explore에 표시', discoverableNote:'내 네트워크가 둘러보기 목록에 나타나게 합니다.', noPublicNetworks:'아직 둘러볼 수 있는 공개 네트워크가 없습니다.', walletPlaceholder:'정확한 지갑 주소 입력', openNetwork:'네트워크 열기', backToMyNetwork:'내 네트워크로', viewing:'둘러보는 중', visibleNetwork:'공개 네트워크', privateBranchesHidden:'비공개 브랜치는 숨겨져 있습니다', visibilityError:'공개 네트워크 설정을 변경하지 못했습니다.', networkPrivate:'이 네트워크는 비공개입니다.', maintenance:'네트워크를 잠시 사용할 수 없습니다.' },
  zh: { exploreNetwork:'浏览网络', exploreTitle:'浏览公开网络', exploreDescription:'使用相同的交互画布浏览公开的 VeInvite 网络。私密分支会被隐藏。', myNetwork:'我的网络', publicSettings:'公开网络', publicEnabled:'公开访问', publicEnabledNote:'允许知道你钱包地址的人查看你的公开网络。', discoverable:'显示在浏览中', discoverableNote:'让你的网络出现在浏览列表中。', noPublicNetworks:'暂时没有可浏览的公开网络。', walletPlaceholder:'输入完整钱包地址', openNetwork:'打开网络', backToMyNetwork:'返回我的网络', viewing:'正在浏览', visibleNetwork:'公开网络', privateBranchesHidden:'私密分支已隐藏', visibilityError:'无法更新公开网络设置。', networkPrivate:'此网络为私密网络。', maintenance:'网络暂时不可用。' },
  hi: { exploreNetwork:'नेटवर्क देखें', exploreTitle:'सार्वजनिक नेटवर्क देखें', exploreDescription:'उसी इंटरैक्टिव कैनवास पर सार्वजनिक VeInvite नेटवर्क देखें। निजी शाखाएँ छिपी रहती हैं।', myNetwork:'मेरा नेटवर्क', publicSettings:'सार्वजनिक नेटवर्क', publicEnabled:'सार्वजनिक पहुँच', publicEnabledNote:'जिनके पास आपका वॉलेट पता है उन्हें आपका सार्वजनिक नेटवर्क देखने दें।', discoverable:'Explore में दिखाएँ', discoverableNote:'अपने नेटवर्क को Explore सूची में दिखाएँ।', noPublicNetworks:'अभी कोई सार्वजनिक नेटवर्क उपलब्ध नहीं है।', walletPlaceholder:'सटीक वॉलेट पता दर्ज करें', openNetwork:'नेटवर्क खोलें', backToMyNetwork:'मेरे नेटवर्क पर वापस', viewing:'देख रहे हैं', visibleNetwork:'सार्वजनिक नेटवर्क', privateBranchesHidden:'निजी शाखाएँ छिपी हैं', visibilityError:'सार्वजनिक नेटवर्क सेटिंग अपडेट नहीं हुई।', networkPrivate:'यह नेटवर्क निजी है।', maintenance:'नेटवर्क अस्थायी रूप से उपलब्ध नहीं है।' },
  es: { exploreNetwork:'Explorar red', exploreTitle:'Explorar redes públicas', exploreDescription:'Explora redes públicas de VeInvite con el mismo lienzo interactivo. Las ramas privadas permanecen ocultas.', myNetwork:'Mi red', publicSettings:'Red pública', publicEnabled:'Acceso público', publicEnabledNote:'Permite que quien conozca tu wallet vea tu red pública.', discoverable:'Mostrar en Explorar', discoverableNote:'Permite que tu red aparezca en la lista de Explorar.', noPublicNetworks:'Aún no hay redes públicas disponibles.', walletPlaceholder:'Introduce la dirección exacta', openNetwork:'Abrir red', backToMyNetwork:'Volver a mi red', viewing:'Explorando', visibleNetwork:'Red pública', privateBranchesHidden:'Las ramas privadas están ocultas', visibilityError:'No se pudo actualizar la configuración pública.', networkPrivate:'Esta red es privada.', maintenance:'La red no está disponible temporalmente.' },
  ja: { exploreNetwork:'ネットワークを見る', exploreTitle:'公開ネットワークを見る', exploreDescription:'同じインタラクティブキャンバスで公開 VeInvite ネットワークを閲覧できます。非公開ブランチは表示されません。', myNetwork:'マイネットワーク', publicSettings:'公開ネットワーク', publicEnabled:'公開アクセス', publicEnabledNote:'ウォレットアドレスを知っている人に公開ネットワークの閲覧を許可します。', discoverable:'Explore に表示', discoverableNote:'ネットワークを Explore 一覧に表示します。', noPublicNetworks:'現在閲覧できる公開ネットワークはありません。', walletPlaceholder:'正確なウォレットアドレスを入力', openNetwork:'ネットワークを開く', backToMyNetwork:'自分のネットワークへ', viewing:'閲覧中', visibleNetwork:'公開ネットワーク', privateBranchesHidden:'非公開ブランチは隠されています', visibilityError:'公開ネットワーク設定を更新できませんでした。', networkPrivate:'このネットワークは非公開です。', maintenance:'ネットワークは一時的に利用できません。' },
  it: { exploreNetwork:'Esplora rete', exploreTitle:'Esplora reti pubbliche', exploreDescription:'Esplora le reti VeInvite pubbliche con lo stesso canvas interattivo. I rami privati restano nascosti.', myNetwork:'La mia rete', publicSettings:'Rete pubblica', publicEnabled:'Accesso pubblico', publicEnabledNote:'Consenti a chi conosce il tuo wallet di vedere la rete pubblica.', discoverable:'Mostra in Esplora', discoverableNote:'Mostra la tua rete nell’elenco Esplora.', noPublicNetworks:'Non ci sono ancora reti pubbliche disponibili.', walletPlaceholder:'Inserisci l’indirizzo wallet esatto', openNetwork:'Apri rete', backToMyNetwork:'Torna alla mia rete', viewing:'Esplorazione', visibleNetwork:'Rete pubblica', privateBranchesHidden:'I rami privati sono nascosti', visibilityError:'Impossibile aggiornare le impostazioni pubbliche.', networkPrivate:'Questa rete è privata.', maintenance:'La rete non è temporaneamente disponibile.' },
  tr: { exploreNetwork:'Ağları keşfet', exploreTitle:'Herkese açık ağları keşfet', exploreDescription:'Aynı etkileşimli tuvalde herkese açık VeInvite ağlarını inceleyin. Özel dallar gizli kalır.', myNetwork:'Ağım', publicSettings:'Herkese açık ağ', publicEnabled:'Herkese açık erişim', publicEnabledNote:'Cüzdan adresinizi bilenlerin açık ağınızı görmesine izin verin.', discoverable:'Keşfet’te göster', discoverableNote:'Ağınız Keşfet listesinde görünsün.', noPublicNetworks:'Henüz keşfedilebilir açık ağ yok.', walletPlaceholder:'Tam cüzdan adresini girin', openNetwork:'Ağı aç', backToMyNetwork:'Ağıma dön', viewing:'Keşfediliyor', visibleNetwork:'Açık ağ', privateBranchesHidden:'Özel dallar gizlidir', visibilityError:'Açık ağ ayarları güncellenemedi.', networkPrivate:'Bu ağ özeldir.', maintenance:'Ağ geçici olarak kullanılamıyor.' },
  nl: { exploreNetwork:'Netwerk verkennen', exploreTitle:'Openbare netwerken verkennen', exploreDescription:'Bekijk openbare VeInvite-netwerken op hetzelfde interactieve canvas. Privétakken blijven verborgen.', myNetwork:'Mijn netwerk', publicSettings:'Openbaar netwerk', publicEnabled:'Openbare toegang', publicEnabledNote:'Laat mensen met je walletadres je openbare netwerk bekijken.', discoverable:'Tonen in Verkennen', discoverableNote:'Laat je netwerk verschijnen in de Verkennen-lijst.', noPublicNetworks:'Er zijn nog geen openbare netwerken beschikbaar.', walletPlaceholder:'Voer het exacte walletadres in', openNetwork:'Netwerk openen', backToMyNetwork:'Terug naar mijn netwerk', viewing:'Aan het verkennen', visibleNetwork:'Openbaar netwerk', privateBranchesHidden:'Privétakken zijn verborgen', visibilityError:'Openbare netwerkinstellingen konden niet worden bijgewerkt.', networkPrivate:'Dit netwerk is privé.', maintenance:'Netwerk is tijdelijk niet beschikbaar.' },
  de: { exploreNetwork:'Netzwerk erkunden', exploreTitle:'Öffentliche Netzwerke erkunden', exploreDescription:'Erkunde öffentliche VeInvite-Netzwerke auf derselben interaktiven Fläche. Private Zweige bleiben verborgen.', myNetwork:'Mein Netzwerk', publicSettings:'Öffentliches Netzwerk', publicEnabled:'Öffentlicher Zugriff', publicEnabledNote:'Erlaube Personen mit deiner Wallet-Adresse, dein öffentliches Netzwerk zu sehen.', discoverable:'In Entdecken anzeigen', discoverableNote:'Zeige dein Netzwerk in der Entdecken-Liste.', noPublicNetworks:'Noch keine öffentlichen Netzwerke verfügbar.', walletPlaceholder:'Exakte Wallet-Adresse eingeben', openNetwork:'Netzwerk öffnen', backToMyNetwork:'Zurück zu meinem Netzwerk', viewing:'Erkundet', visibleNetwork:'Öffentliches Netzwerk', privateBranchesHidden:'Private Zweige sind verborgen', visibilityError:'Öffentliche Netzwerkeinstellungen konnten nicht aktualisiert werden.', networkPrivate:'Dieses Netzwerk ist privat.', maintenance:'Netzwerk ist vorübergehend nicht verfügbar.' },
  fr: { exploreNetwork:'Explorer le réseau', exploreTitle:'Explorer les réseaux publics', exploreDescription:'Parcourez les réseaux VeInvite publics sur le même canevas interactif. Les branches privées restent masquées.', myNetwork:'Mon réseau', publicSettings:'Réseau public', publicEnabled:'Accès public', publicEnabledNote:'Autorisez les personnes connaissant votre wallet à voir votre réseau public.', discoverable:'Afficher dans Explorer', discoverableNote:'Affichez votre réseau dans la liste Explorer.', noPublicNetworks:'Aucun réseau public n’est encore disponible.', walletPlaceholder:'Saisir l’adresse exacte du wallet', openNetwork:'Ouvrir le réseau', backToMyNetwork:'Retour à mon réseau', viewing:'Exploration', visibleNetwork:'Réseau public', privateBranchesHidden:'Les branches privées sont masquées', visibilityError:'Impossible de mettre à jour les réglages publics.', networkPrivate:'Ce réseau est privé.', maintenance:'Le réseau est temporairement indisponible.' },
  ar: { exploreNetwork:'استكشاف الشبكة', exploreTitle:'استكشاف الشبكات العامة', exploreDescription:'استكشف شبكات VeInvite العامة على نفس اللوحة التفاعلية. تبقى الفروع الخاصة مخفية.', myNetwork:'شبكتي', publicSettings:'الشبكة العامة', publicEnabled:'وصول عام', publicEnabledNote:'اسمح لمن يعرف عنوان محفظتك برؤية شبكتك العامة.', discoverable:'إظهار في الاستكشاف', discoverableNote:'أظهر شبكتك في قائمة الاستكشاف.', noPublicNetworks:'لا توجد شبكات عامة متاحة بعد.', walletPlaceholder:'أدخل عنوان المحفظة الكامل', openNetwork:'فتح الشبكة', backToMyNetwork:'العودة إلى شبكتي', viewing:'جارٍ الاستكشاف', visibleNetwork:'الشبكة العامة', privateBranchesHidden:'الفروع الخاصة مخفية', visibilityError:'تعذر تحديث إعدادات الشبكة العامة.', networkPrivate:'هذه الشبكة خاصة.', maintenance:'الشبكة غير متاحة مؤقتًا.' },
  bn: { exploreNetwork:'নেটওয়ার্ক দেখুন', exploreTitle:'পাবলিক নেটওয়ার্ক দেখুন', exploreDescription:'একই ইন্টারঅ্যাকটিভ ক্যানভাসে পাবলিক VeInvite নেটওয়ার্ক দেখুন। ব্যক্তিগত শাখা লুকানো থাকবে।', myNetwork:'আমার নেটওয়ার্ক', publicSettings:'পাবলিক নেটওয়ার্ক', publicEnabled:'পাবলিক অ্যাক্সেস', publicEnabledNote:'যারা আপনার ওয়ালেট ঠিকানা জানে তাদের পাবলিক নেটওয়ার্ক দেখতে দিন।', discoverable:'Explore-এ দেখান', discoverableNote:'আপনার নেটওয়ার্ক Explore তালিকায় দেখান।', noPublicNetworks:'এখনও কোনো পাবলিক নেটওয়ার্ক নেই।', walletPlaceholder:'সঠিক ওয়ালেট ঠিকানা লিখুন', openNetwork:'নেটওয়ার্ক খুলুন', backToMyNetwork:'আমার নেটওয়ার্কে ফিরুন', viewing:'দেখছেন', visibleNetwork:'পাবলিক নেটওয়ার্ক', privateBranchesHidden:'ব্যক্তিগত শাখা লুকানো', visibilityError:'পাবলিক নেটওয়ার্ক সেটিং আপডেট করা যায়নি।', networkPrivate:'এই নেটওয়ার্ক ব্যক্তিগত।', maintenance:'নেটওয়ার্ক সাময়িকভাবে অনুপলব্ধ।' },
  pt: { exploreNetwork:'Explorar rede', exploreTitle:'Explorar redes públicas', exploreDescription:'Explore redes públicas do VeInvite no mesmo canvas interativo. Ramos privados ficam ocultos.', myNetwork:'Minha rede', publicSettings:'Rede pública', publicEnabled:'Acesso público', publicEnabledNote:'Permita que quem conhece sua carteira veja sua rede pública.', discoverable:'Mostrar no Explorar', discoverableNote:'Faça sua rede aparecer na lista Explorar.', noPublicNetworks:'Ainda não há redes públicas disponíveis.', walletPlaceholder:'Digite o endereço exato da carteira', openNetwork:'Abrir rede', backToMyNetwork:'Voltar para minha rede', viewing:'Explorando', visibleNetwork:'Rede pública', privateBranchesHidden:'Ramos privados estão ocultos', visibilityError:'Não foi possível atualizar as configurações públicas.', networkPrivate:'Esta rede é privada.', maintenance:'A rede está temporariamente indisponível.' },
  ru: { exploreNetwork:'Обзор сети', exploreTitle:'Обзор публичных сетей', exploreDescription:'Просматривайте публичные сети VeInvite на том же интерактивном холсте. Приватные ветви скрыты.', myNetwork:'Моя сеть', publicSettings:'Публичная сеть', publicEnabled:'Публичный доступ', publicEnabledNote:'Разрешите людям с адресом вашего кошелька видеть публичную сеть.', discoverable:'Показывать в обзоре', discoverableNote:'Показывайте свою сеть в списке обзора.', noPublicNetworks:'Публичных сетей пока нет.', walletPlaceholder:'Введите точный адрес кошелька', openNetwork:'Открыть сеть', backToMyNetwork:'Назад к моей сети', viewing:'Просмотр', visibleNetwork:'Публичная сеть', privateBranchesHidden:'Приватные ветви скрыты', visibilityError:'Не удалось обновить настройки публичной сети.', networkPrivate:'Эта сеть приватна.', maintenance:'Сеть временно недоступна.' },
  id: { exploreNetwork:'Jelajahi jaringan', exploreTitle:'Jelajahi jaringan publik', exploreDescription:'Jelajahi jaringan VeInvite publik di kanvas interaktif yang sama. Cabang privat tetap disembunyikan.', myNetwork:'Jaringan saya', publicSettings:'Jaringan publik', publicEnabled:'Akses publik', publicEnabledNote:'Izinkan orang yang mengetahui alamat wallet Anda melihat jaringan publik.', discoverable:'Tampilkan di Jelajahi', discoverableNote:'Tampilkan jaringan Anda di daftar Jelajahi.', noPublicNetworks:'Belum ada jaringan publik yang dapat dijelajahi.', walletPlaceholder:'Masukkan alamat wallet lengkap', openNetwork:'Buka jaringan', backToMyNetwork:'Kembali ke jaringan saya', viewing:'Menjelajahi', visibleNetwork:'Jaringan publik', privateBranchesHidden:'Cabang privat disembunyikan', visibilityError:'Pengaturan jaringan publik gagal diperbarui.', networkPrivate:'Jaringan ini privat.', maintenance:'Jaringan sementara tidak tersedia.' },
  vi: { exploreNetwork:'Khám phá mạng lưới', exploreTitle:'Khám phá mạng công khai', exploreDescription:'Khám phá các mạng VeInvite công khai trên cùng canvas tương tác. Nhánh riêng tư sẽ được ẩn.', myNetwork:'Mạng của tôi', publicSettings:'Mạng công khai', publicEnabled:'Truy cập công khai', publicEnabledNote:'Cho phép người biết địa chỉ ví xem mạng công khai của bạn.', discoverable:'Hiện trong Khám phá', discoverableNote:'Cho phép mạng của bạn xuất hiện trong danh sách Khám phá.', noPublicNetworks:'Chưa có mạng công khai để khám phá.', walletPlaceholder:'Nhập chính xác địa chỉ ví', openNetwork:'Mở mạng', backToMyNetwork:'Về mạng của tôi', viewing:'Đang khám phá', visibleNetwork:'Mạng công khai', privateBranchesHidden:'Các nhánh riêng tư đã được ẩn', visibilityError:'Không thể cập nhật cài đặt mạng công khai.', networkPrivate:'Mạng này là riêng tư.', maintenance:'Mạng tạm thời không khả dụng.' },
  'zh-tw': { exploreNetwork:'瀏覽網路', exploreTitle:'瀏覽公開網路', exploreDescription:'使用相同互動畫布瀏覽公開的 VeInvite 網路。私人分支會被隱藏。', myNetwork:'我的網路', publicSettings:'公開網路', publicEnabled:'公開存取', publicEnabledNote:'允許知道你錢包地址的人查看你的公開網路。', discoverable:'顯示於瀏覽', discoverableNote:'讓你的網路出現在瀏覽清單中。', noPublicNetworks:'目前沒有可瀏覽的公開網路。', walletPlaceholder:'輸入完整錢包地址', openNetwork:'開啟網路', backToMyNetwork:'返回我的網路', viewing:'正在瀏覽', visibleNetwork:'公開網路', privateBranchesHidden:'私人分支已隱藏', visibilityError:'無法更新公開網路設定。', networkPrivate:'此網路為私人網路。', maintenance:'網路暫時無法使用。' },
  sv: { exploreNetwork:'Utforska nätverk', exploreTitle:'Utforska offentliga nätverk', exploreDescription:'Utforska offentliga VeInvite-nätverk på samma interaktiva yta. Privata grenar förblir dolda.', myNetwork:'Mitt nätverk', publicSettings:'Offentligt nätverk', publicEnabled:'Offentlig åtkomst', publicEnabledNote:'Låt personer med din wallet-adress se ditt offentliga nätverk.', discoverable:'Visa i Utforska', discoverableNote:'Visa ditt nätverk i Utforska-listan.', noPublicNetworks:'Inga offentliga nätverk kan utforskas ännu.', walletPlaceholder:'Ange exakt wallet-adress', openNetwork:'Öppna nätverk', backToMyNetwork:'Tillbaka till mitt nätverk', viewing:'Utforskar', visibleNetwork:'Offentligt nätverk', privateBranchesHidden:'Privata grenar är dolda', visibilityError:'Kunde inte uppdatera offentliga inställningar.', networkPrivate:'Det här nätverket är privat.', maintenance:'Nätverket är tillfälligt otillgängligt.' },
  ro: { exploreNetwork:'Explorează rețeaua', exploreTitle:'Explorează rețele publice', exploreDescription:'Explorează rețele VeInvite publice pe aceeași pânză interactivă. Ramurile private rămân ascunse.', myNetwork:'Rețeaua mea', publicSettings:'Rețea publică', publicEnabled:'Acces public', publicEnabledNote:'Permite celor care îți cunosc walletul să vadă rețeaua publică.', discoverable:'Arată în Explore', discoverableNote:'Afișează rețeaua în lista Explore.', noPublicNetworks:'Nu există încă rețele publice disponibile.', walletPlaceholder:'Introdu adresa exactă a walletului', openNetwork:'Deschide rețeaua', backToMyNetwork:'Înapoi la rețeaua mea', viewing:'Explorezi', visibleNetwork:'Rețea publică', privateBranchesHidden:'Ramurile private sunt ascunse', visibilityError:'Setările rețelei publice nu au putut fi actualizate.', networkPrivate:'Această rețea este privată.', maintenance:'Rețeaua este temporar indisponibilă.' },
  ur: { exploreNetwork:'نیٹ ورک دیکھیں', exploreTitle:'عوامی نیٹ ورکس دیکھیں', exploreDescription:'اسی انٹرایکٹو کینوس پر عوامی VeInvite نیٹ ورکس دیکھیں۔ نجی شاخیں پوشیدہ رہتی ہیں۔', myNetwork:'میرا نیٹ ورک', publicSettings:'عوامی نیٹ ورک', publicEnabled:'عوامی رسائی', publicEnabledNote:'جن لوگوں کو آپ کا والٹ ایڈریس معلوم ہے انہیں عوامی نیٹ ورک دیکھنے دیں۔', discoverable:'Explore میں دکھائیں', discoverableNote:'اپنے نیٹ ورک کو Explore فہرست میں دکھائیں۔', noPublicNetworks:'ابھی کوئی عوامی نیٹ ورک دستیاب نہیں۔', walletPlaceholder:'درست والٹ ایڈریس درج کریں', openNetwork:'نیٹ ورک کھولیں', backToMyNetwork:'میرے نیٹ ورک پر واپس', viewing:'دیکھ رہے ہیں', visibleNetwork:'عوامی نیٹ ورک', privateBranchesHidden:'نجی شاخیں پوشیدہ ہیں', visibilityError:'عوامی نیٹ ورک کی ترتیبات اپ ڈیٹ نہیں ہو سکیں۔', networkPrivate:'یہ نیٹ ورک نجی ہے۔', maintenance:'نیٹ ورک عارضی طور پر دستیاب نہیں۔' },
  pcm: { exploreNetwork:'Explore network', exploreTitle:'Explore public networks', exploreDescription:'See public VeInvite networks for di same interactive canvas. Private branches no go show.', myNetwork:'My network', publicSettings:'Public network', publicEnabled:'Public access', publicEnabledNote:'Make people wey know your wallet address fit see your public network.', discoverable:'Show for Explore', discoverableNote:'Make your network show for Explore list.', noPublicNetworks:'No public network dey available yet.', walletPlaceholder:'Enter exact wallet address', openNetwork:'Open network', backToMyNetwork:'Back to my network', viewing:'Dey explore', visibleNetwork:'Public network', privateBranchesHidden:'Private branches hide', visibilityError:'We no fit update public network settings.', networkPrivate:'Dis network private.', maintenance:'Network no dey available for now.' },
  arz: { exploreNetwork:'استكشف الشبكة', exploreTitle:'استكشف الشبكات العامة', exploreDescription:'شوف شبكات VeInvite العامة على نفس اللوحة التفاعلية. الفروع الخاصة هتفضل مخفية.', myNetwork:'شبكتي', publicSettings:'الشبكة العامة', publicEnabled:'وصول عام', publicEnabledNote:'اسمح للي عارف عنوان محفظتك يشوف شبكتك العامة.', discoverable:'اظهر في الاستكشاف', discoverableNote:'خلي شبكتك تظهر في قائمة الاستكشاف.', noPublicNetworks:'مفيش شبكات عامة متاحة دلوقتي.', walletPlaceholder:'اكتب عنوان المحفظة كامل', openNetwork:'افتح الشبكة', backToMyNetwork:'ارجع لشبكتي', viewing:'بتستكشف', visibleNetwork:'الشبكة العامة', privateBranchesHidden:'الفروع الخاصة مخفية', visibilityError:'مقدرناش نحدث إعدادات الشبكة العامة.', networkPrivate:'الشبكة دي خاصة.', maintenance:'الشبكة مش متاحة مؤقتًا.' },
  mr: { exploreNetwork:'नेटवर्क पाहा', exploreTitle:'सार्वजनिक नेटवर्क पाहा', exploreDescription:'त्याच इंटरॅक्टिव्ह कॅनव्हासवर सार्वजनिक VeInvite नेटवर्क पाहा. खाजगी शाखा लपवलेल्या राहतात.', myNetwork:'माझे नेटवर्क', publicSettings:'सार्वजनिक नेटवर्क', publicEnabled:'सार्वजनिक प्रवेश', publicEnabledNote:'तुमचा वॉलेट पत्ता माहित असलेल्या लोकांना सार्वजनिक नेटवर्क पाहू द्या.', discoverable:'Explore मध्ये दाखवा', discoverableNote:'तुमचे नेटवर्क Explore यादीत दाखवा.', noPublicNetworks:'अजून कोणतेही सार्वजनिक नेटवर्क उपलब्ध नाही.', walletPlaceholder:'अचूक वॉलेट पत्ता टाका', openNetwork:'नेटवर्क उघडा', backToMyNetwork:'माझ्या नेटवर्ककडे परत', viewing:'पाहत आहात', visibleNetwork:'सार्वजनिक नेटवर्क', privateBranchesHidden:'खाजगी शाखा लपवल्या आहेत', visibilityError:'सार्वजनिक नेटवर्क सेटिंग अपडेट झाले नाही.', networkPrivate:'हे नेटवर्क खाजगी आहे.', maintenance:'नेटवर्क तात्पुरते उपलब्ध नाही.' },
  te: { exploreNetwork:'నెట్‌వర్క్ చూడండి', exploreTitle:'పబ్లిక్ నెట్‌వర్క్‌లను చూడండి', exploreDescription:'అదే ఇంటరాక్టివ్ కాన్వాస్‌లో పబ్లిక్ VeInvite నెట్‌వర్క్‌లను చూడండి. ప్రైవేట్ శాఖలు దాచబడతాయి.', myNetwork:'నా నెట్‌వర్క్', publicSettings:'పబ్లిక్ నెట్‌వర్క్', publicEnabled:'పబ్లిక్ యాక్సెస్', publicEnabledNote:'మీ వాలెట్ చిరునామా తెలిసినవారు మీ పబ్లిక్ నెట్‌వర్క్‌ను చూడగలరు.', discoverable:'Explore లో చూపించు', discoverableNote:'మీ నెట్‌వర్క్ Explore జాబితాలో కనిపించనివ్వండి.', noPublicNetworks:'ఇంకా పబ్లిక్ నెట్‌వర్క్‌లు లేవు.', walletPlaceholder:'ఖచ్చితమైన వాలెట్ చిరునామా నమోదు చేయండి', openNetwork:'నెట్‌వర్క్ తెరువు', backToMyNetwork:'నా నెట్‌వర్క్‌కు తిరుగు', viewing:'చూస్తున్నారు', visibleNetwork:'పబ్లిక్ నెట్‌వర్క్', privateBranchesHidden:'ప్రైవేట్ శాఖలు దాచబడ్డాయి', visibilityError:'పబ్లిక్ నెట్‌వర్క్ సెట్టింగ్ నవీకరించలేకపోయాం.', networkPrivate:'ఈ నెట్‌వర్క్ ప్రైవేట్.', maintenance:'నెట్‌వర్క్ తాత్కాలికంగా అందుబాటులో లేదు.' },
  sw: { exploreNetwork:'Gundua mtandao', exploreTitle:'Gundua mitandao ya umma', exploreDescription:'Gundua mitandao ya VeInvite ya umma kwenye turubai ileile shirikishi. Matawi ya faragha yanafichwa.', myNetwork:'Mtandao wangu', publicSettings:'Mtandao wa umma', publicEnabled:'Ufikiaji wa umma', publicEnabledNote:'Ruhusu wanaojua anwani ya pochi yako kuona mtandao wako wa umma.', discoverable:'Onyesha kwenye Gundua', discoverableNote:'Onyesha mtandao wako kwenye orodha ya Gundua.', noPublicNetworks:'Bado hakuna mitandao ya umma ya kugundua.', walletPlaceholder:'Weka anwani kamili ya pochi', openNetwork:'Fungua mtandao', backToMyNetwork:'Rudi kwenye mtandao wangu', viewing:'Unagundua', visibleNetwork:'Mtandao wa umma', privateBranchesHidden:'Matawi ya faragha yamefichwa', visibilityError:'Mipangilio ya mtandao wa umma haikuweza kusasishwa.', networkPrivate:'Mtandao huu ni wa faragha.', maintenance:'Mtandao haupatikani kwa muda.' },
  ha: { exploreNetwork:'Bincika network', exploreTitle:'Bincika public networks', exploreDescription:'Duba public VeInvite networks a kan interactive canvas iri ɗaya. Private branches suna ɓoye.', myNetwork:'Network dina', publicSettings:'Public network', publicEnabled:'Public access', publicEnabledNote:'Bari masu san wallet address ɗinka su ga public network ɗinka.', discoverable:'Nuna a Explore', discoverableNote:'Bari network ɗinka ya bayyana a jerin Explore.', noPublicNetworks:'Babu public network da za a bincika tukuna.', walletPlaceholder:'Shigar da cikakken wallet address', openNetwork:'Buɗe network', backToMyNetwork:'Koma network dina', viewing:'Ana bincike', visibleNetwork:'Public network', privateBranchesHidden:'Private branches suna ɓoye', visibilityError:'Ba a iya sabunta public network settings ba.', networkPrivate:'Wannan network private ne.', maintenance:'Network baya samuwa na ɗan lokaci.' },
  el: { exploreNetwork:'Εξερεύνηση δικτύου', exploreTitle:'Εξερεύνηση δημόσιων δικτύων', exploreDescription:'Εξερευνήστε δημόσια δίκτυα VeInvite στον ίδιο διαδραστικό καμβά. Οι ιδιωτικοί κλάδοι παραμένουν κρυφοί.', myNetwork:'Το δίκτυό μου', publicSettings:'Δημόσιο δίκτυο', publicEnabled:'Δημόσια πρόσβαση', publicEnabledNote:'Επιτρέψτε σε όσους γνωρίζουν τη διεύθυνση wallet να βλέπουν το δημόσιο δίκτυό σας.', discoverable:'Εμφάνιση στην Εξερεύνηση', discoverableNote:'Εμφανίστε το δίκτυό σας στη λίστα Εξερεύνησης.', noPublicNetworks:'Δεν υπάρχουν ακόμη δημόσια δίκτυα.', walletPlaceholder:'Εισαγάγετε την ακριβή διεύθυνση wallet', openNetwork:'Άνοιγμα δικτύου', backToMyNetwork:'Πίσω στο δίκτυό μου', viewing:'Εξερεύνηση', visibleNetwork:'Δημόσιο δίκτυο', privateBranchesHidden:'Οι ιδιωτικοί κλάδοι είναι κρυφοί', visibilityError:'Δεν ήταν δυνατή η ενημέρωση των δημόσιων ρυθμίσεων.', networkPrivate:'Αυτό το δίκτυο είναι ιδιωτικό.', maintenance:'Το δίκτυο δεν είναι προσωρινά διαθέσιμο.' },
};
