import type { SupportedLocale } from './locales';

export type NetworkHubCopy = {
  maintenanceTitle: string;
  maintenanceDescription: string;
  visibilityLoading: string;
  visibilityUnknown: string;
  publicConfirm: string;
};

export const NETWORK_HUB_COPY: Record<SupportedLocale, NetworkHubCopy> = {
  en: { maintenanceTitle:'Network is being prepared', maintenanceDescription:'We are preparing the new Network experience safely. Please check again shortly.', visibilityLoading:'Checking your Public Network setting…', visibilityUnknown:'Your Public Network setting could not be confirmed. Please try again.', publicConfirm:'Turn on Public Network? Your wallet address and the referral paths you explicitly make public can be viewed by other people. Mission, reward, and security details remain private.' },
  ko: { maintenanceTitle:'네트워크를 준비하고 있어요', maintenanceDescription:'새로운 네트워크 기능을 안전하게 준비 중입니다. 잠시 후 다시 확인해 주세요.', visibilityLoading:'공개 네트워크 설정을 확인하고 있어요…', visibilityUnknown:'공개 네트워크 설정 상태를 확인하지 못했습니다. 다시 시도해 주세요.', publicConfirm:'공개 네트워크를 켤까요? 내 지갑 주소와 내가 명시적으로 공개한 추천 경로를 다른 사람이 볼 수 있습니다. 미션, 보상, 보안 정보는 공개되지 않습니다.' },
  zh: { maintenanceTitle:'网络功能正在准备中', maintenanceDescription:'我们正在安全地准备新的网络体验，请稍后再试。', visibilityLoading:'正在检查公开网络设置…', visibilityUnknown:'无法确认你的公开网络设置，请重试。', publicConfirm:'开启公开网络吗？其他人将能够查看你的钱包地址以及你明确公开的推荐路径。任务、奖励和安全信息仍保持私密。' },
  hi: { maintenanceTitle:'नेटवर्क तैयार किया जा रहा है', maintenanceDescription:'हम नए Network अनुभव को सुरक्षित रूप से तैयार कर रहे हैं। कृपया थोड़ी देर बाद फिर देखें।', visibilityLoading:'Public Network सेटिंग जाँची जा रही है…', visibilityUnknown:'आपकी Public Network सेटिंग की पुष्टि नहीं हो सकी। फिर कोशिश करें।', publicConfirm:'Public Network चालू करें? आपका वॉलेट पता और वे referral paths जिन्हें आप स्पष्ट रूप से सार्वजनिक करते हैं, दूसरे लोग देख सकेंगे। Mission, reward और security जानकारी निजी रहेगी।' },
  es: { maintenanceTitle:'Estamos preparando Network', maintenanceDescription:'Estamos preparando de forma segura la nueva experiencia de Network. Vuelve a comprobarlo en breve.', visibilityLoading:'Comprobando tu configuración de Public Network…', visibilityUnknown:'No pudimos confirmar tu configuración de Public Network. Inténtalo de nuevo.', publicConfirm:'¿Activar Public Network? Otras personas podrán ver tu dirección de wallet y las rutas de referidos que hagas públicas explícitamente. Los datos de misiones, recompensas y seguridad seguirán siendo privados.' },
  ja: { maintenanceTitle:'ネットワークを準備しています', maintenanceDescription:'新しいネットワーク機能を安全に準備しています。しばらくしてからもう一度確認してください。', visibilityLoading:'公開ネットワーク設定を確認しています…', visibilityUnknown:'公開ネットワーク設定を確認できませんでした。もう一度お試しください。', publicConfirm:'公開ネットワークをオンにしますか？あなたのウォレットアドレスと、明示的に公開した紹介経路を他の人が閲覧できるようになります。ミッション、報酬、セキュリティ情報は非公開のままです。' },
  it: { maintenanceTitle:'Network è in preparazione', maintenanceDescription:'Stiamo preparando in sicurezza la nuova esperienza Network. Ricontrolla tra poco.', visibilityLoading:'Controllo delle impostazioni Public Network…', visibilityUnknown:'Non è stato possibile confermare le impostazioni Public Network. Riprova.', publicConfirm:'Attivare Public Network? Altre persone potranno vedere il tuo indirizzo wallet e i percorsi referral che rendi esplicitamente pubblici. Missioni, ricompense e dati di sicurezza resteranno privati.' },
  tr: { maintenanceTitle:'Network hazırlanıyor', maintenanceDescription:'Yeni Network deneyimini güvenli şekilde hazırlıyoruz. Lütfen kısa süre sonra tekrar kontrol edin.', visibilityLoading:'Public Network ayarın kontrol ediliyor…', visibilityUnknown:'Public Network ayarın doğrulanamadı. Lütfen tekrar dene.', publicConfirm:'Public Network açılsın mı? Cüzdan adresin ve açıkça herkese açtığın referral yolları başkaları tarafından görülebilir. Görev, ödül ve güvenlik bilgileri gizli kalır.' },
  nl: { maintenanceTitle:'Network wordt voorbereid', maintenanceDescription:'We bereiden de nieuwe Network-ervaring veilig voor. Probeer het binnenkort opnieuw.', visibilityLoading:'Je Public Network-instelling wordt gecontroleerd…', visibilityUnknown:'Je Public Network-instelling kon niet worden bevestigd. Probeer opnieuw.', publicConfirm:'Public Network inschakelen? Andere mensen kunnen je walletadres en de referralpaden zien die je expliciet openbaar maakt. Missie-, belonings- en beveiligingsgegevens blijven privé.' },
  de: { maintenanceTitle:'Network wird vorbereitet', maintenanceDescription:'Wir bereiten die neue Network-Erfahrung sicher vor. Bitte prüfe es in Kürze erneut.', visibilityLoading:'Public-Network-Einstellung wird geprüft…', visibilityUnknown:'Deine Public-Network-Einstellung konnte nicht bestätigt werden. Bitte erneut versuchen.', publicConfirm:'Public Network aktivieren? Andere können deine Wallet-Adresse und die von dir ausdrücklich freigegebenen Referral-Pfade sehen. Missions-, Belohnungs- und Sicherheitsdaten bleiben privat.' },
  fr: { maintenanceTitle:'Network est en préparation', maintenanceDescription:'Nous préparons la nouvelle expérience Network en toute sécurité. Réessayez dans un instant.', visibilityLoading:'Vérification de votre réglage Public Network…', visibilityUnknown:'Votre réglage Public Network n’a pas pu être confirmé. Réessayez.', publicConfirm:'Activer Public Network ? D’autres personnes pourront voir votre adresse wallet et les parcours de parrainage que vous rendez explicitement publics. Les informations de mission, de récompense et de sécurité resteront privées.' },
  ar: { maintenanceTitle:'يتم تجهيز الشبكة', maintenanceDescription:'نقوم بإعداد تجربة Network الجديدة بأمان. يرجى المحاولة مرة أخرى بعد قليل.', visibilityLoading:'جارٍ التحقق من إعداد Public Network…', visibilityUnknown:'تعذر تأكيد إعداد Public Network. يرجى المحاولة مرة أخرى.', publicConfirm:'هل تريد تشغيل Public Network؟ سيتمكن الآخرون من رؤية عنوان محفظتك ومسارات الإحالة التي تختار جعلها عامة صراحةً. ستظل تفاصيل المهام والمكافآت والأمان خاصة.' },
  bn: { maintenanceTitle:'Network প্রস্তুত করা হচ্ছে', maintenanceDescription:'নতুন Network অভিজ্ঞতাটি নিরাপদভাবে প্রস্তুত করা হচ্ছে। একটু পরে আবার দেখুন।', visibilityLoading:'Public Network সেটিং যাচাই করা হচ্ছে…', visibilityUnknown:'আপনার Public Network সেটিং নিশ্চিত করা যায়নি। আবার চেষ্টা করুন।', publicConfirm:'Public Network চালু করবেন? আপনার wallet address এবং আপনি স্পষ্টভাবে public করা referral path অন্যরা দেখতে পারবে। Mission, reward ও security তথ্য private থাকবে।' },
  pt: { maintenanceTitle:'Network está sendo preparado', maintenanceDescription:'Estamos preparando com segurança a nova experiência de Network. Verifique novamente em instantes.', visibilityLoading:'Verificando sua configuração de Public Network…', visibilityUnknown:'Não foi possível confirmar sua configuração de Public Network. Tente novamente.', publicConfirm:'Ativar Public Network? Outras pessoas poderão ver o endereço da sua wallet e os caminhos de indicação que você tornar explicitamente públicos. Dados de missão, recompensa e segurança continuarão privados.' },
  ru: { maintenanceTitle:'Network готовится', maintenanceDescription:'Мы безопасно подготавливаем новый интерфейс Network. Проверьте ещё раз чуть позже.', visibilityLoading:'Проверяем настройки Public Network…', visibilityUnknown:'Не удалось подтвердить настройки Public Network. Попробуйте снова.', publicConfirm:'Включить Public Network? Другие смогут видеть адрес вашего кошелька и пути рефералов, которые вы явно сделали публичными. Данные миссий, наград и безопасности останутся приватными.' },
  id: { maintenanceTitle:'Network sedang disiapkan', maintenanceDescription:'Kami sedang menyiapkan pengalaman Network baru dengan aman. Silakan cek lagi sebentar lagi.', visibilityLoading:'Memeriksa pengaturan Public Network…', visibilityUnknown:'Pengaturan Public Network Anda tidak dapat dikonfirmasi. Coba lagi.', publicConfirm:'Aktifkan Public Network? Orang lain dapat melihat alamat wallet Anda dan jalur referral yang Anda nyatakan publik. Detail misi, reward, dan keamanan tetap privat.' },
  vi: { maintenanceTitle:'Network đang được chuẩn bị', maintenanceDescription:'Chúng tôi đang chuẩn bị trải nghiệm Network mới một cách an toàn. Vui lòng kiểm tra lại sau ít phút.', visibilityLoading:'Đang kiểm tra cài đặt Public Network…', visibilityUnknown:'Không thể xác nhận cài đặt Public Network của bạn. Vui lòng thử lại.', publicConfirm:'Bật Public Network? Người khác có thể xem địa chỉ ví và các đường referral mà bạn chủ động công khai. Thông tin nhiệm vụ, phần thưởng và bảo mật vẫn được giữ riêng tư.' },
  'zh-tw': { maintenanceTitle:'網路功能正在準備中', maintenanceDescription:'我們正在安全地準備新的 Network 體驗，請稍後再試。', visibilityLoading:'正在確認 Public Network 設定…', visibilityUnknown:'無法確認你的 Public Network 設定，請再試一次。', publicConfirm:'要開啟 Public Network 嗎？其他人將能查看你的錢包地址以及你明確公開的推薦路徑。任務、獎勵與安全資訊仍會保持私密。' },
  sv: { maintenanceTitle:'Network förbereds', maintenanceDescription:'Vi förbereder den nya Network-upplevelsen på ett säkert sätt. Kontrollera igen om en liten stund.', visibilityLoading:'Kontrollerar din Public Network-inställning…', visibilityUnknown:'Din Public Network-inställning kunde inte bekräftas. Försök igen.', publicConfirm:'Aktivera Public Network? Andra kan se din wallet-adress och de referral-vägar som du uttryckligen gör offentliga. Uppgifter om uppdrag, belöningar och säkerhet förblir privata.' },
  ro: { maintenanceTitle:'Network este în pregătire', maintenanceDescription:'Pregătim în siguranță noua experiență Network. Verifică din nou în curând.', visibilityLoading:'Se verifică setarea Public Network…', visibilityUnknown:'Setarea Public Network nu a putut fi confirmată. Încearcă din nou.', publicConfirm:'Activezi Public Network? Alte persoane vor putea vedea adresa wallet și traseele referral pe care le faci publice în mod explicit. Detaliile despre misiuni, recompense și securitate rămân private.' },
  ur: { maintenanceTitle:'Network تیار کیا جا رہا ہے', maintenanceDescription:'ہم نئے Network تجربے کو محفوظ طریقے سے تیار کر رہے ہیں۔ تھوڑی دیر بعد دوبارہ دیکھیں۔', visibilityLoading:'Public Network سیٹنگ چیک کی جا رہی ہے…', visibilityUnknown:'آپ کی Public Network سیٹنگ کی تصدیق نہیں ہو سکی۔ دوبارہ کوشش کریں۔', publicConfirm:'Public Network آن کریں؟ آپ کا wallet address اور وہ referral paths جو آپ واضح طور پر public کریں گے دوسروں کو نظر آ سکتے ہیں۔ Mission، reward اور security معلومات private رہیں گی۔' },
  pcm: { maintenanceTitle:'Network dey prepare', maintenanceDescription:'We dey prepare di new Network experience safely. Abeg check again small time.', visibilityLoading:'We dey check your Public Network setting…', visibilityUnknown:'We no fit confirm your Public Network setting. Try again.', publicConfirm:'Make Public Network turn on? Other people fit see your wallet address and referral paths wey you clearly make public. Mission, reward and security details go remain private.' },
  arz: { maintenanceTitle:'Network بيتجهز', maintenanceDescription:'إحنا بنجهز تجربة Network الجديدة بشكل آمن. جرّب تاني كمان شوية.', visibilityLoading:'بنتأكد من إعداد Public Network…', visibilityUnknown:'مقدرناش نتأكد من إعداد Public Network. جرّب تاني.', publicConfirm:'تشغّل Public Network؟ الناس هتقدر تشوف عنوان المحفظة ومسارات الإحالة اللي إنت بتختار تخليها عامة بوضوح. تفاصيل المهمات والمكافآت والأمان هتفضل خاصة.' },
  mr: { maintenanceTitle:'Network तयार केले जात आहे', maintenanceDescription:'नवीन Network अनुभव सुरक्षितपणे तयार केला जात आहे. कृपया थोड्या वेळाने पुन्हा पाहा.', visibilityLoading:'Public Network सेटिंग तपासली जात आहे…', visibilityUnknown:'तुमची Public Network सेटिंग निश्चित करता आली नाही. पुन्हा प्रयत्न करा.', publicConfirm:'Public Network सुरू करायचे? तुमचा wallet address आणि तुम्ही स्पष्टपणे public केलेले referral paths इतरांना दिसू शकतात. Mission, reward आणि security माहिती private राहील.' },
  te: { maintenanceTitle:'Network సిద్ధం అవుతోంది', maintenanceDescription:'కొత్త Network అనుభవాన్ని సురక్షితంగా సిద్ధం చేస్తున్నాం. కొద్దిసేపటి తర్వాత మళ్లీ చూడండి.', visibilityLoading:'Public Network సెట్టింగ్‌ను తనిఖీ చేస్తున్నాం…', visibilityUnknown:'మీ Public Network సెట్టింగ్‌ను నిర్ధారించలేకపోయాం. మళ్లీ ప్రయత్నించండి.', publicConfirm:'Public Network ఆన్ చేయాలా? మీ wallet address మరియు మీరు స్పష్టంగా public చేసిన referral paths‌ను ఇతరులు చూడగలరు. Mission, reward, security వివరాలు privateగానే ఉంటాయి.' },
  sw: { maintenanceTitle:'Network inaandaliwa', maintenanceDescription:'Tunaandaa matumizi mapya ya Network kwa usalama. Tafadhali angalia tena baada ya muda mfupi.', visibilityLoading:'Tunakagua mpangilio wako wa Public Network…', visibilityUnknown:'Hatukuweza kuthibitisha mpangilio wako wa Public Network. Jaribu tena.', publicConfirm:'Washa Public Network? Watu wengine wataweza kuona anwani ya wallet yako na njia za referral unazoweka wazi kwa hiari. Taarifa za mission, reward na usalama zitaendelea kuwa za faragha.' },
  ha: { maintenanceTitle:'Ana shirya Network', maintenanceDescription:'Muna shirya sabon kwarewar Network cikin aminci. Da fatan za a sake dubawa nan ba da jimawa ba.', visibilityLoading:'Ana duba saitin Public Network naka…', visibilityUnknown:'Ba a iya tabbatar da saitin Public Network naka ba. Sake gwadawa.', publicConfirm:'A kunna Public Network? Wasu za su iya ganin adireshin wallet naka da referral paths da ka bayyana a fili a matsayin public. Bayanan mission, reward da security za su ci gaba da zama private.' },
  el: { maintenanceTitle:'Το Network προετοιμάζεται', maintenanceDescription:'Προετοιμάζουμε με ασφάλεια τη νέα εμπειρία Network. Ελέγξτε ξανά σε λίγο.', visibilityLoading:'Έλεγχος της ρύθμισης Public Network…', visibilityUnknown:'Δεν ήταν δυνατή η επιβεβαίωση της ρύθμισης Public Network. Δοκιμάστε ξανά.', publicConfirm:'Ενεργοποίηση Public Network; Άλλοι θα μπορούν να βλέπουν τη διεύθυνση wallet σας και τις referral διαδρομές που επιλέγετε ρητά να δημοσιοποιήσετε. Οι πληροφορίες mission, reward και security παραμένουν ιδιωτικές.' },
};
