import type { SupportedLocale } from './locales';

export type NetworkExploreCopy = {
  exploreNetwork: string;
  exploreTitle: string;
  myNetwork: string;
  noPublicNetworks: string;
  walletPlaceholder: string;
  openNetwork: string;
  backToMyNetwork: string;
  viewing: string;
  visibleNetwork: string;
  maintenance: string;
};

export const NETWORK_EXPLORE_COPY: Record<SupportedLocale, NetworkExploreCopy> = {
  en: { exploreNetwork:'Explore Network', exploreTitle:'Explore public networks', myNetwork:'My Network', noPublicNetworks:'No public networks are discoverable yet.', walletPlaceholder:'Enter an exact wallet address', openNetwork:'Open network', backToMyNetwork:'Back to my network', viewing:'Exploring', visibleNetwork:'Public network', maintenance:'Network is temporarily unavailable.' },
  ko: { exploreNetwork:'다른 네트워크 둘러보기', exploreTitle:'공개 네트워크 둘러보기', myNetwork:'내 네트워크', noPublicNetworks:'아직 둘러볼 수 있는 공개 네트워크가 없습니다.', walletPlaceholder:'정확한 지갑 주소 입력', openNetwork:'네트워크 열기', backToMyNetwork:'내 네트워크로', viewing:'둘러보는 중', visibleNetwork:'공개 네트워크', maintenance:'네트워크를 잠시 사용할 수 없습니다.' },
  zh: { exploreNetwork:'浏览网络', exploreTitle:'浏览公开网络', myNetwork:'我的网络', noPublicNetworks:'暂时没有可浏览的公开网络。', walletPlaceholder:'输入完整钱包地址', openNetwork:'打开网络', backToMyNetwork:'返回我的网络', viewing:'正在浏览', visibleNetwork:'公开网络', maintenance:'网络暂时不可用。' },
  hi: { exploreNetwork:'नेटवर्क देखें', exploreTitle:'सार्वजनिक नेटवर्क देखें', myNetwork:'मेरा नेटवर्क', noPublicNetworks:'अभी कोई सार्वजनिक नेटवर्क उपलब्ध नहीं है।', walletPlaceholder:'सटीक वॉलेट पता दर्ज करें', openNetwork:'नेटवर्क खोलें', backToMyNetwork:'मेरे नेटवर्क पर वापस', viewing:'देख रहे हैं', visibleNetwork:'सार्वजनिक नेटवर्क', maintenance:'नेटवर्क अस्थायी रूप से उपलब्ध नहीं है।' },
  es: { exploreNetwork:'Explorar red', exploreTitle:'Explorar redes públicas', myNetwork:'Mi red', noPublicNetworks:'Aún no hay redes públicas disponibles.', walletPlaceholder:'Introduce la dirección exacta', openNetwork:'Abrir red', backToMyNetwork:'Volver a mi red', viewing:'Explorando', visibleNetwork:'Red pública', maintenance:'La red no está disponible temporalmente.' },
  ja: { exploreNetwork:'ネットワークを見る', exploreTitle:'公開ネットワークを見る', myNetwork:'マイネットワーク', noPublicNetworks:'現在閲覧できる公開ネットワークはありません。', walletPlaceholder:'正確なウォレットアドレスを入力', openNetwork:'ネットワークを開く', backToMyNetwork:'自分のネットワークへ', viewing:'閲覧中', visibleNetwork:'公開ネットワーク', maintenance:'ネットワークは一時的に利用できません。' },
  it: { exploreNetwork:'Esplora rete', exploreTitle:'Esplora reti pubbliche', myNetwork:'La mia rete', noPublicNetworks:'Non ci sono ancora reti pubbliche disponibili.', walletPlaceholder:'Inserisci l’indirizzo wallet esatto', openNetwork:'Apri rete', backToMyNetwork:'Torna alla mia rete', viewing:'Esplorazione', visibleNetwork:'Rete pubblica', maintenance:'La rete non è temporaneamente disponibile.' },
  tr: { exploreNetwork:'Ağları keşfet', exploreTitle:'Herkese açık ağları keşfet', myNetwork:'Ağım', noPublicNetworks:'Henüz keşfedilebilir açık ağ yok.', walletPlaceholder:'Tam cüzdan adresini girin', openNetwork:'Ağı aç', backToMyNetwork:'Ağıma dön', viewing:'Keşfediliyor', visibleNetwork:'Açık ağ', maintenance:'Ağ geçici olarak kullanılamıyor.' },
  nl: { exploreNetwork:'Netwerk verkennen', exploreTitle:'Openbare netwerken verkennen', myNetwork:'Mijn netwerk', noPublicNetworks:'Er zijn nog geen openbare netwerken beschikbaar.', walletPlaceholder:'Voer het exacte walletadres in', openNetwork:'Netwerk openen', backToMyNetwork:'Terug naar mijn netwerk', viewing:'Aan het verkennen', visibleNetwork:'Openbaar netwerk', maintenance:'Netwerk is tijdelijk niet beschikbaar.' },
  de: { exploreNetwork:'Netzwerk erkunden', exploreTitle:'Öffentliche Netzwerke erkunden', myNetwork:'Mein Netzwerk', noPublicNetworks:'Noch keine öffentlichen Netzwerke verfügbar.', walletPlaceholder:'Exakte Wallet-Adresse eingeben', openNetwork:'Netzwerk öffnen', backToMyNetwork:'Zurück zu meinem Netzwerk', viewing:'Erkundet', visibleNetwork:'Öffentliches Netzwerk', maintenance:'Netzwerk ist vorübergehend nicht verfügbar.' },
  fr: { exploreNetwork:'Explorer le réseau', exploreTitle:'Explorer les réseaux publics', myNetwork:'Mon réseau', noPublicNetworks:'Aucun réseau public n’est encore disponible.', walletPlaceholder:'Saisir l’adresse exacte du wallet', openNetwork:'Ouvrir le réseau', backToMyNetwork:'Retour à mon réseau', viewing:'Exploration', visibleNetwork:'Réseau public', maintenance:'Le réseau est temporairement indisponible.' },
  ar: { exploreNetwork:'استكشاف الشبكة', exploreTitle:'استكشاف الشبكات العامة', myNetwork:'شبكتي', noPublicNetworks:'لا توجد شبكات عامة متاحة بعد.', walletPlaceholder:'أدخل عنوان المحفظة الكامل', openNetwork:'فتح الشبكة', backToMyNetwork:'العودة إلى شبكتي', viewing:'جارٍ الاستكشاف', visibleNetwork:'الشبكة العامة', maintenance:'الشبكة غير متاحة مؤقتًا.' },
  bn: { exploreNetwork:'নেটওয়ার্ক দেখুন', exploreTitle:'পাবলিক নেটওয়ার্ক দেখুন', myNetwork:'আমার নেটওয়ার্ক', noPublicNetworks:'এখনও কোনো পাবলিক নেটওয়ার্ক নেই।', walletPlaceholder:'সঠিক ওয়ালেট ঠিকানা লিখুন', openNetwork:'নেটওয়ার্ক খুলুন', backToMyNetwork:'আমার নেটওয়ার্কে ফিরুন', viewing:'দেখছেন', visibleNetwork:'পাবলিক নেটওয়ার্ক', maintenance:'নেটওয়ার্ক সাময়িকভাবে অনুপলব্ধ।' },
  pt: { exploreNetwork:'Explorar rede', exploreTitle:'Explorar redes públicas', myNetwork:'Minha rede', noPublicNetworks:'Ainda não há redes públicas disponíveis.', walletPlaceholder:'Digite o endereço exato da carteira', openNetwork:'Abrir rede', backToMyNetwork:'Voltar para minha rede', viewing:'Explorando', visibleNetwork:'Rede pública', maintenance:'A rede está temporariamente indisponível.' },
  ru: { exploreNetwork:'Обзор сети', exploreTitle:'Обзор публичных сетей', myNetwork:'Моя сеть', noPublicNetworks:'Публичных сетей пока нет.', walletPlaceholder:'Введите точный адрес кошелька', openNetwork:'Открыть сеть', backToMyNetwork:'Назад к моей сети', viewing:'Просмотр', visibleNetwork:'Публичная сеть', maintenance:'Сеть временно недоступна.' },
  id: { exploreNetwork:'Jelajahi jaringan', exploreTitle:'Jelajahi jaringan publik', myNetwork:'Jaringan saya', noPublicNetworks:'Belum ada jaringan publik yang dapat dijelajahi.', walletPlaceholder:'Masukkan alamat wallet lengkap', openNetwork:'Buka jaringan', backToMyNetwork:'Kembali ke jaringan saya', viewing:'Menjelajahi', visibleNetwork:'Jaringan publik', maintenance:'Jaringan sementara tidak tersedia.' },
  vi: { exploreNetwork:'Khám phá mạng lưới', exploreTitle:'Khám phá mạng công khai', myNetwork:'Mạng của tôi', noPublicNetworks:'Chưa có mạng công khai để khám phá.', walletPlaceholder:'Nhập chính xác địa chỉ ví', openNetwork:'Mở mạng', backToMyNetwork:'Về mạng của tôi', viewing:'Đang khám phá', visibleNetwork:'Mạng công khai', maintenance:'Mạng tạm thời không khả dụng.' },
  'zh-tw': { exploreNetwork:'瀏覽網路', exploreTitle:'瀏覽公開網路', myNetwork:'我的網路', noPublicNetworks:'目前沒有可瀏覽的公開網路。', walletPlaceholder:'輸入完整錢包地址', openNetwork:'開啟網路', backToMyNetwork:'返回我的網路', viewing:'正在瀏覽', visibleNetwork:'公開網路', maintenance:'網路暫時無法使用。' },
  sv: { exploreNetwork:'Utforska nätverk', exploreTitle:'Utforska offentliga nätverk', myNetwork:'Mitt nätverk', noPublicNetworks:'Inga offentliga nätverk kan utforskas ännu.', walletPlaceholder:'Ange exakt wallet-adress', openNetwork:'Öppna nätverk', backToMyNetwork:'Tillbaka till mitt nätverk', viewing:'Utforskar', visibleNetwork:'Offentligt nätverk', maintenance:'Nätverket är tillfälligt otillgängligt.' },
  ro: { exploreNetwork:'Explorează rețeaua', exploreTitle:'Explorează rețele publice', myNetwork:'Rețeaua mea', noPublicNetworks:'Nu există încă rețele publice disponibile.', walletPlaceholder:'Introdu adresa exactă a walletului', openNetwork:'Deschide rețeaua', backToMyNetwork:'Înapoi la rețeaua mea', viewing:'Explorezi', visibleNetwork:'Rețea publică', maintenance:'Rețeaua este temporar indisponibilă.' },
  ur: { exploreNetwork:'نیٹ ورک دیکھیں', exploreTitle:'عوامی نیٹ ورکس دیکھیں', myNetwork:'میرا نیٹ ورک', noPublicNetworks:'ابھی کوئی عوامی نیٹ ورک دستیاب نہیں۔', walletPlaceholder:'درست والٹ ایڈریس درج کریں', openNetwork:'نیٹ ورک کھولیں', backToMyNetwork:'میرے نیٹ ورک پر واپس', viewing:'دیکھ رہے ہیں', visibleNetwork:'عوامی نیٹ ورک', maintenance:'نیٹ ورک عارضی طور پر دستیاب نہیں۔' },
  pcm: { exploreNetwork:'Explore network', exploreTitle:'Explore public networks', myNetwork:'My network', noPublicNetworks:'No public network dey available yet.', walletPlaceholder:'Enter exact wallet address', openNetwork:'Open network', backToMyNetwork:'Back to my network', viewing:'Dey explore', visibleNetwork:'Public network', maintenance:'Network no dey available for now.' },
  arz: { exploreNetwork:'استكشف الشبكة', exploreTitle:'استكشف الشبكات العامة', myNetwork:'شبكتي', noPublicNetworks:'مفيش شبكات عامة متاحة دلوقتي.', walletPlaceholder:'اكتب عنوان المحفظة كامل', openNetwork:'افتح الشبكة', backToMyNetwork:'ارجع لشبكتي', viewing:'بتستكشف', visibleNetwork:'الشبكة العامة', maintenance:'الشبكة مش متاحة مؤقتًا.' },
  mr: { exploreNetwork:'नेटवर्क पाहा', exploreTitle:'सार्वजनिक नेटवर्क पाहा', myNetwork:'माझे नेटवर्क', noPublicNetworks:'अजून कोणतेही सार्वजनिक नेटवर्क उपलब्ध नाही.', walletPlaceholder:'अचूक वॉलेट पत्ता टाका', openNetwork:'नेटवर्क उघडा', backToMyNetwork:'माझ्या नेटवर्ककडे परत', viewing:'पाहत आहात', visibleNetwork:'सार्वजनिक नेटवर्क', maintenance:'नेटवर्क तात्पुरते उपलब्ध नाही.' },
  te: { exploreNetwork:'నెట్‌వర్క్ చూడండి', exploreTitle:'పబ్లిక్ నెట్‌వర్క్‌లను చూడండి', myNetwork:'నా నెట్‌వర్క్', noPublicNetworks:'ఇంకా పబ్లిక్ నెట్‌వర్క్‌లు లేవు.', walletPlaceholder:'ఖచ్చితమైన వాలెట్ చిరునామా నమోదు చేయండి', openNetwork:'నెట్‌వర్క్ తెరువు', backToMyNetwork:'నా నెట్‌వర్క్‌కు తిరుగు', viewing:'చూస్తున్నారు', visibleNetwork:'పబ్లిక్ నెట్‌వర్క్', maintenance:'నెట్‌వర్క్ తాత్కాలికంగా అందుబాటులో లేదు.' },
  sw: { exploreNetwork:'Gundua mtandao', exploreTitle:'Gundua mitandao ya umma', myNetwork:'Mtandao wangu', noPublicNetworks:'Bado hakuna mitandao ya umma ya kugundua.', walletPlaceholder:'Weka anwani kamili ya pochi', openNetwork:'Fungua mtandao', backToMyNetwork:'Rudi kwenye mtandao wangu', viewing:'Unagundua', visibleNetwork:'Mtandao wa umma', maintenance:'Mtandao haupatikani kwa muda.' },
  ha: { exploreNetwork:'Bincika network', exploreTitle:'Bincika public networks', myNetwork:'Network dina', noPublicNetworks:'Babu public network da za a bincika tukuna.', walletPlaceholder:'Shigar da cikakken wallet address', openNetwork:'Buɗe network', backToMyNetwork:'Koma network dina', viewing:'Ana bincike', visibleNetwork:'Public network', maintenance:'Network baya samuwa na ɗan lokaci.' },
  el: { exploreNetwork:'Εξερεύνηση δικτύου', exploreTitle:'Εξερεύνηση δημόσιων δικτύων', myNetwork:'Το δίκτυό μου', noPublicNetworks:'Δεν υπάρχουν ακόμη δημόσια δίκτυα.', walletPlaceholder:'Εισαγάγετε την ακριβή διεύθυνση wallet', openNetwork:'Άνοιγμα δικτύου', backToMyNetwork:'Πίσω στο δίκτυό μου', viewing:'Εξερεύνηση', visibleNetwork:'Δημόσιο δίκτυο', maintenance:'Το δίκτυο δεν είναι προσωρινά διαθέσιμο.' },
  cs: { exploreNetwork:'Prozkoumat síť', exploreTitle:'Prozkoumat veřejné sítě', myNetwork:'Moje síť', noPublicNetworks:'Zatím nejsou dostupné žádné veřejné sítě.', walletPlaceholder:'Zadej přesnou adresu peněženky', openNetwork:'Otevřít síť', backToMyNetwork:'Zpět na moji síť', viewing:'Prohlížíš', visibleNetwork:'Veřejná síť', maintenance:'Síť je dočasně nedostupná.' },
};
