import type { SupportedLocale } from './locales';

export type NetworkCanaryUiCopy = {
  groups: string;
  myGroups: string;
  savedCount: string;
  createGroup: string;
  zoomFirst: string;
  dropPersonOrTap: string;
  peopleCount: string;
  releaseAdd: string;
  emptyReady: string;
  collapsed: string;
  expanded: string;
  edit: string;
  noGroups: string;
  optional: string;
  selectedCount: string;
  willMoveCount: string;
  groupName: string;
  cancel: string;
  create: string;
  tapAddRemove: string;
  zeroAllowed: string;
  save: string;
  removeFromGroup: string;
  releaseHere: string;
  dragUngroup: string;
  undo: string;
  addPeople: string;
  dragOrTap: string;
  noPeopleSelected: string;
  move: string;
  editLayout: string;
  done: string;
  reset: string;
  fit: string;
  groupsCount: string;
  allCanvas: string;
  joining: string;
  available: string;
  hintEdit: string;
  hintCluster: string;
  hintView: string;
  empty: string;
  removed: string;
  newFriendJoining: string;
  verifiedAdding: string;
  newNodeAdded: string;
};

export const NETWORK_CANARY_UI_COPY = {
  en: { groups:'Groups', myGroups:'My groups', savedCount:'{count} saved here', createGroup:'Create group', zoomFirst:'Zoom in first to choose individual people', dropPersonOrTap:'Drop a person here or tap to create', peopleCount:'{count} people', releaseAdd:'Release to add', emptyReady:'Empty · ready for drop', collapsed:'Collapsed', expanded:'Expanded', edit:'Edit', noGroups:'No groups yet', optional:'People are optional', selectedCount:'{count} selected', willMoveCount:'{count} will move here', groupName:'Group name', cancel:'Cancel', create:'Create', tapAddRemove:'Tap people to add or remove', zeroAllowed:'0 people is allowed', save:'Save changes', removeFromGroup:'Remove from group', releaseHere:'Release here', dragUngroup:'Drag here to ungroup only', undo:'Undo', addPeople:'Add people', dragOrTap:'Drag from the network or tap to select', noPeopleSelected:'No people selected yet', move:'Move', editLayout:'Edit layout', done:'Done', reset:'Reset', fit:'Fit', groupsCount:'{count} groups', allCanvas:'All on one canvas', joining:'Joining', available:'Available', hintEdit:'Drag freely · tap background to finish', hintCluster:'Zoom in or tap +N to unfold · zoom out to group again', hintView:'Hold a node to edit · drag canvas · pinch to zoom', empty:'Empty', removed:'Removed', newFriendJoining:'New friend is joining…', verifiedAdding:'Verified · adding to this network', newNodeAdded:'New node added' },
  ko: { groups:'그룹', myGroups:'내 그룹', savedCount:'여기에 {count}개 저장', createGroup:'그룹 만들기', zoomFirst:'사람을 선택하려면 먼저 확대하세요', dropPersonOrTap:'사람을 여기로 끌어오거나 눌러서 만들기', peopleCount:'{count}명', releaseAdd:'놓아서 추가', emptyReady:'비어 있음 · 드롭 가능', collapsed:'접힘', expanded:'펼침', edit:'수정', noGroups:'아직 그룹이 없어요', optional:'사람 선택은 선택사항', selectedCount:'{count}명 선택', willMoveCount:'{count}명은 이 그룹으로 이동', groupName:'그룹 이름', cancel:'취소', create:'만들기', tapAddRemove:'사람을 눌러 추가하거나 빼세요', zeroAllowed:'0명도 가능', save:'변경 저장', removeFromGroup:'그룹에서 빼기', releaseHere:'여기에 놓기', dragUngroup:'그룹만 해제하려면 여기로 끌기', undo:'되돌리기', addPeople:'사람 추가', dragOrTap:'네트워크에서 끌거나 눌러 선택', noPeopleSelected:'아직 선택한 사람이 없어요', move:'이동', editLayout:'배치 편집', done:'완료', reset:'초기화', fit:'화면 맞춤', groupsCount:'그룹 {count}개', allCanvas:'한 화면에 모두 표시', joining:'참여 중', available:'초대 가능', hintEdit:'자유롭게 이동 · 배경을 눌러 종료', hintCluster:'확대하거나 +N을 눌러 펼치기 · 축소하면 다시 묶임', hintView:'노드를 길게 눌러 편집 · 화면 드래그 · 핀치로 확대/축소', empty:'비어 있음', removed:'삭제됨', newFriendJoining:'새 친구가 참여 중…', verifiedAdding:'확인 완료 · 이 네트워크에 추가 중', newNodeAdded:'새 노드가 추가됐어요' },
  zh: { groups:'分组', myGroups:'我的分组', savedCount:'已在此保存 {count} 个', createGroup:'创建分组', zoomFirst:'请先放大再选择具体用户', dropPersonOrTap:'把用户拖到这里，或点按创建', peopleCount:'{count} 人', releaseAdd:'松开以添加', emptyReady:'空分组 · 可拖入', collapsed:'已收起', expanded:'已展开', edit:'编辑', noGroups:'还没有分组', optional:'可不选择用户', selectedCount:'已选 {count} 人', willMoveCount:'{count} 人将移到这里', groupName:'分组名称', cancel:'取消', create:'创建', tapAddRemove:'点按用户以添加或移除', zeroAllowed:'允许 0 人', save:'保存更改', removeFromGroup:'移出分组', releaseHere:'在此松开', dragUngroup:'拖到这里仅解除分组', undo:'撤销', addPeople:'添加用户', dragOrTap:'从网络拖入或点按选择', noPeopleSelected:'尚未选择用户', move:'移动', editLayout:'编辑布局', done:'完成', reset:'重置', fit:'适配画面', groupsCount:'{count} 个分组', allCanvas:'全部显示在一个画布', joining:'加入中', available:'可邀请', hintEdit:'自由拖动 · 点按背景结束', hintCluster:'放大或点 +N 展开 · 缩小后重新分组', hintView:'长按节点编辑 · 拖动画布 · 双指缩放', empty:'空', removed:'已移除', newFriendJoining:'新朋友正在加入…', verifiedAdding:'已验证 · 正在加入此网络', newNodeAdded:'已添加新节点' },
  hi: { groups:'समूह', myGroups:'मेरे समूह', savedCount:'यहाँ {count} सहेजे गए', createGroup:'समूह बनाएँ', zoomFirst:'लोगों को चुनने के लिए पहले ज़ूम इन करें', dropPersonOrTap:'किसी व्यक्ति को यहाँ खींचें या बनाने के लिए टैप करें', peopleCount:'{count} लोग', releaseAdd:'जोड़ने के लिए छोड़ें', emptyReady:'खाली · ड्रॉप के लिए तैयार', collapsed:'सिमटा हुआ', expanded:'खुला हुआ', edit:'संपादित करें', noGroups:'अभी कोई समूह नहीं', optional:'लोग चुनना वैकल्पिक है', selectedCount:'{count} चुने गए', willMoveCount:'{count} यहाँ चले जाएँगे', groupName:'समूह का नाम', cancel:'रद्द करें', create:'बनाएँ', tapAddRemove:'लोगों को जोड़ने या हटाने के लिए टैप करें', zeroAllowed:'0 लोग भी मान्य हैं', save:'बदलाव सहेजें', removeFromGroup:'समूह से हटाएँ', releaseHere:'यहाँ छोड़ें', dragUngroup:'केवल समूह हटाने के लिए यहाँ खींचें', undo:'पूर्ववत करें', addPeople:'लोग जोड़ें', dragOrTap:'नेटवर्क से खींचें या चुनने के लिए टैप करें', noPeopleSelected:'अभी कोई व्यक्ति नहीं चुना गया', move:'स्थानांतरित करें', editLayout:'लेआउट संपादित करें', done:'पूर्ण', reset:'रीसेट', fit:'स्क्रीन में फिट', groupsCount:'{count} समूह', allCanvas:'सब एक ही कैनवास पर', joining:'जुड़ रहा है', available:'उपलब्ध', hintEdit:'स्वतंत्र रूप से खींचें · समाप्त करने के लिए पृष्ठभूमि टैप करें', hintCluster:'खोलने के लिए ज़ूम इन या +N टैप करें · फिर समूह करने के लिए ज़ूम आउट', hintView:'संपादन के लिए नोड दबाकर रखें · कैनवास खींचें · पिंच से ज़ूम करें', empty:'खाली', removed:'हटाया गया', newFriendJoining:'नया दोस्त जुड़ रहा है…', verifiedAdding:'सत्यापित · इस नेटवर्क में जोड़ा जा रहा है', newNodeAdded:'नया नोड जोड़ा गया' },
  es: { groups:'Grupos', myGroups:'Mis grupos', savedCount:'{count} guardados aquí', createGroup:'Crear grupo', zoomFirst:'Acerca primero para elegir personas', dropPersonOrTap:'Arrastra una persona aquí o toca para crear', peopleCount:'{count} personas', releaseAdd:'Suelta para añadir', emptyReady:'Vacío · listo para recibir', collapsed:'Contraído', expanded:'Expandido', edit:'Editar', noGroups:'Aún no hay grupos', optional:'Elegir personas es opcional', selectedCount:'{count} seleccionadas', willMoveCount:'{count} se moverán aquí', groupName:'Nombre del grupo', cancel:'Cancelar', create:'Crear', tapAddRemove:'Toca personas para añadirlas o quitarlas', zeroAllowed:'Se permiten 0 personas', save:'Guardar cambios', removeFromGroup:'Quitar del grupo', releaseHere:'Suelta aquí', dragUngroup:'Arrastra aquí solo para desagrupar', undo:'Deshacer', addPeople:'Añadir personas', dragOrTap:'Arrastra desde la red o toca para seleccionar', noPeopleSelected:'Aún no hay personas seleccionadas', move:'Mover', editLayout:'Editar diseño', done:'Listo', reset:'Restablecer', fit:'Ajustar vista', groupsCount:'{count} grupos', allCanvas:'Todo en un solo lienzo', joining:'Uniéndose', available:'Disponible', hintEdit:'Arrastra libremente · toca el fondo para terminar', hintCluster:'Acerca o toca +N para desplegar · aleja para agrupar', hintView:'Mantén un nodo para editar · arrastra el lienzo · pellizca para ampliar', empty:'Vacío', removed:'Eliminado', newFriendJoining:'Un nuevo amigo se está uniendo…', verifiedAdding:'Verificado · añadiendo a esta red', newNodeAdded:'Nuevo nodo añadido' },
  ja: { groups:'グループ', myGroups:'マイグループ', savedCount:'ここに {count} 件保存', createGroup:'グループを作成', zoomFirst:'個別に選ぶには先に拡大してください', dropPersonOrTap:'ここに人をドラッグするか、タップして作成', peopleCount:'{count}人', releaseAdd:'離して追加', emptyReady:'空 · ドロップ可能', collapsed:'折りたたみ', expanded:'展開中', edit:'編集', noGroups:'グループはまだありません', optional:'人の選択は任意です', selectedCount:'{count}人選択', willMoveCount:'{count}人がここへ移動', groupName:'グループ名', cancel:'キャンセル', create:'作成', tapAddRemove:'人をタップして追加・削除', zeroAllowed:'0人でも保存できます', save:'変更を保存', removeFromGroup:'グループから外す', releaseHere:'ここで離す', dragUngroup:'グループ解除だけならここへドラッグ', undo:'元に戻す', addPeople:'人を追加', dragOrTap:'ネットワークからドラッグするかタップして選択', noPeopleSelected:'まだ誰も選択されていません', move:'移動', editLayout:'配置を編集', done:'完了', reset:'リセット', fit:'画面に合わせる', groupsCount:'{count}グループ', allCanvas:'1つの画面にすべて表示', joining:'参加中', available:'招待可能', hintEdit:'自由に移動 · 背景をタップして終了', hintCluster:'拡大または +N で展開 · 縮小すると再グループ化', hintView:'ノードを長押しして編集 · 画面をドラッグ · ピンチで拡大縮小', empty:'空', removed:'削除済み', newFriendJoining:'新しい友だちが参加中…', verifiedAdding:'確認済み · このネットワークに追加中', newNodeAdded:'新しいノードを追加しました' },
  it: { groups:'Gruppi', myGroups:'I miei gruppi', savedCount:'{count} salvati qui', createGroup:'Crea gruppo', zoomFirst:'Ingrandisci prima per scegliere le persone', dropPersonOrTap:'Trascina qui una persona o tocca per creare', peopleCount:'{count} persone', releaseAdd:'Rilascia per aggiungere', emptyReady:'Vuoto · pronto al rilascio', collapsed:'Compresso', expanded:'Espanso', edit:'Modifica', noGroups:'Nessun gruppo ancora', optional:'Le persone sono facoltative', selectedCount:'{count} selezionate', willMoveCount:'{count} verranno spostate qui', groupName:'Nome gruppo', cancel:'Annulla', create:'Crea', tapAddRemove:'Tocca le persone per aggiungerle o rimuoverle', zeroAllowed:'Sono consentite 0 persone', save:'Salva modifiche', removeFromGroup:'Rimuovi dal gruppo', releaseHere:'Rilascia qui', dragUngroup:'Trascina qui solo per separare dal gruppo', undo:'Annulla ultima azione', addPeople:'Aggiungi persone', dragOrTap:'Trascina dalla rete o tocca per selezionare', noPeopleSelected:'Nessuna persona selezionata', move:'Sposta', editLayout:'Modifica layout', done:'Fatto', reset:'Ripristina', fit:'Adatta', groupsCount:'{count} gruppi', allCanvas:'Tutto su un solo canvas', joining:'In ingresso', available:'Disponibile', hintEdit:'Trascina liberamente · tocca lo sfondo per terminare', hintCluster:'Ingrandisci o tocca +N per aprire · riduci per raggruppare', hintView:'Tieni premuto un nodo per modificare · trascina il canvas · pizzica per zoomare', empty:'Vuoto', removed:'Rimosso', newFriendJoining:'Un nuovo amico sta entrando…', verifiedAdding:'Verificato · aggiunta a questa rete', newNodeAdded:'Nuovo nodo aggiunto' },
  tr: { groups:'Gruplar', myGroups:'Gruplarım', savedCount:'Burada {count} kayıtlı', createGroup:'Grup oluştur', zoomFirst:'Kişileri seçmek için önce yakınlaştır', dropPersonOrTap:'Bir kişiyi buraya sürükle veya oluşturmak için dokun', peopleCount:'{count} kişi', releaseAdd:'Eklemek için bırak', emptyReady:'Boş · bırakmaya hazır', collapsed:'Daraltıldı', expanded:'Genişletildi', edit:'Düzenle', noGroups:'Henüz grup yok', optional:'Kişi seçmek isteğe bağlıdır', selectedCount:'{count} seçildi', willMoveCount:'{count} kişi buraya taşınacak', groupName:'Grup adı', cancel:'İptal', create:'Oluştur', tapAddRemove:'Eklemek veya çıkarmak için kişilere dokun', zeroAllowed:'0 kişi olabilir', save:'Değişiklikleri kaydet', removeFromGroup:'Gruptan çıkar', releaseHere:'Buraya bırak', dragUngroup:'Yalnızca gruptan çıkarmak için buraya sürükle', undo:'Geri al', addPeople:'Kişi ekle', dragOrTap:'Ağdan sürükle veya seçmek için dokun', noPeopleSelected:'Henüz kimse seçilmedi', move:'Taşı', editLayout:'Yerleşimi düzenle', done:'Bitti', reset:'Sıfırla', fit:'Ekrana sığdır', groupsCount:'{count} grup', allCanvas:'Hepsi tek tuvalde', joining:'Katılıyor', available:'Uygun', hintEdit:'Serbestçe sürükle · bitirmek için arka plana dokun', hintCluster:'Açmak için yakınlaştır veya +N’e dokun · gruplamak için uzaklaştır', hintView:'Düzenlemek için düğümü basılı tut · tuvali sürükle · yakınlaştırmak için sıkıştır', empty:'Boş', removed:'Kaldırıldı', newFriendJoining:'Yeni bir arkadaş katılıyor…', verifiedAdding:'Doğrulandı · bu ağa ekleniyor', newNodeAdded:'Yeni düğüm eklendi' },
  nl: { groups:'Groepen', myGroups:'Mijn groepen', savedCount:'{count} hier opgeslagen', createGroup:'Groep maken', zoomFirst:'Zoom eerst in om personen te kiezen', dropPersonOrTap:'Sleep iemand hierheen of tik om te maken', peopleCount:'{count} personen', releaseAdd:'Loslaten om toe te voegen', emptyReady:'Leeg · klaar voor slepen', collapsed:'Ingeklapt', expanded:'Uitgeklapt', edit:'Bewerken', noGroups:'Nog geen groepen', optional:'Personen kiezen is optioneel', selectedCount:'{count} geselecteerd', willMoveCount:'{count} worden hierheen verplaatst', groupName:'Groepsnaam', cancel:'Annuleren', create:'Maken', tapAddRemove:'Tik op personen om toe te voegen of te verwijderen', zeroAllowed:'0 personen is toegestaan', save:'Wijzigingen opslaan', removeFromGroup:'Uit groep verwijderen', releaseHere:'Hier loslaten', dragUngroup:'Sleep hierheen om alleen uit de groep te halen', undo:'Ongedaan maken', addPeople:'Personen toevoegen', dragOrTap:'Sleep vanuit het netwerk of tik om te selecteren', noPeopleSelected:'Nog niemand geselecteerd', move:'Verplaatsen', editLayout:'Indeling bewerken', done:'Klaar', reset:'Herstellen', fit:'Passend maken', groupsCount:'{count} groepen', allCanvas:'Alles op één canvas', joining:'Bezig met deelnemen', available:'Beschikbaar', hintEdit:'Sleep vrij · tik op de achtergrond om te stoppen', hintCluster:'Zoom in of tik +N om uit te vouwen · zoom uit om te groeperen', hintView:'Houd een knooppunt vast om te bewerken · sleep het canvas · knijp om te zoomen', empty:'Leeg', removed:'Verwijderd', newFriendJoining:'Een nieuwe vriend sluit aan…', verifiedAdding:'Geverifieerd · wordt aan dit netwerk toegevoegd', newNodeAdded:'Nieuw knooppunt toegevoegd' },
  de: { groups:'Gruppen', myGroups:'Meine Gruppen', savedCount:'{count} hier gespeichert', createGroup:'Gruppe erstellen', zoomFirst:'Zum Auswählen zuerst vergrößern', dropPersonOrTap:'Person hierher ziehen oder zum Erstellen tippen', peopleCount:'{count} Personen', releaseAdd:'Zum Hinzufügen loslassen', emptyReady:'Leer · bereit zum Ablegen', collapsed:'Eingeklappt', expanded:'Ausgeklappt', edit:'Bearbeiten', noGroups:'Noch keine Gruppen', optional:'Personen sind optional', selectedCount:'{count} ausgewählt', willMoveCount:'{count} werden hierher verschoben', groupName:'Gruppenname', cancel:'Abbrechen', create:'Erstellen', tapAddRemove:'Personen zum Hinzufügen oder Entfernen antippen', zeroAllowed:'0 Personen sind möglich', save:'Änderungen speichern', removeFromGroup:'Aus Gruppe entfernen', releaseHere:'Hier loslassen', dragUngroup:'Hierher ziehen, um nur die Gruppierung zu lösen', undo:'Rückgängig', addPeople:'Personen hinzufügen', dragOrTap:'Aus dem Netzwerk ziehen oder zum Auswählen tippen', noPeopleSelected:'Noch keine Personen ausgewählt', move:'Verschieben', editLayout:'Anordnung bearbeiten', done:'Fertig', reset:'Zurücksetzen', fit:'Einpassen', groupsCount:'{count} Gruppen', allCanvas:'Alles auf einer Fläche', joining:'Tritt bei', available:'Verfügbar', hintEdit:'Frei ziehen · zum Beenden Hintergrund antippen', hintCluster:'Vergrößern oder +N antippen zum Öffnen · verkleinern zum Gruppieren', hintView:'Knoten halten zum Bearbeiten · Fläche ziehen · zum Zoomen auseinanderziehen', empty:'Leer', removed:'Entfernt', newFriendJoining:'Ein neuer Freund tritt bei…', verifiedAdding:'Bestätigt · wird diesem Netzwerk hinzugefügt', newNodeAdded:'Neuer Knoten hinzugefügt' },
  fr: { groups:'Groupes', myGroups:'Mes groupes', savedCount:'{count} enregistrés ici', createGroup:'Créer un groupe', zoomFirst:'Zoomez d’abord pour choisir des personnes', dropPersonOrTap:'Glissez une personne ici ou touchez pour créer', peopleCount:'{count} personnes', releaseAdd:'Relâchez pour ajouter', emptyReady:'Vide · prêt à recevoir', collapsed:'Réduit', expanded:'Déployé', edit:'Modifier', noGroups:'Aucun groupe pour le moment', optional:'Les personnes sont facultatives', selectedCount:'{count} sélectionnées', willMoveCount:'{count} seront déplacées ici', groupName:'Nom du groupe', cancel:'Annuler', create:'Créer', tapAddRemove:'Touchez les personnes à ajouter ou retirer', zeroAllowed:'0 personne est autorisée', save:'Enregistrer', removeFromGroup:'Retirer du groupe', releaseHere:'Relâchez ici', dragUngroup:'Glissez ici uniquement pour dissocier', undo:'Annuler', addPeople:'Ajouter des personnes', dragOrTap:'Glissez depuis le réseau ou touchez pour sélectionner', noPeopleSelected:'Aucune personne sélectionnée', move:'Déplacer', editLayout:'Modifier la disposition', done:'Terminé', reset:'Réinitialiser', fit:'Ajuster', groupsCount:'{count} groupes', allCanvas:'Tout sur un seul canevas', joining:'Connexion en cours', available:'Disponible', hintEdit:'Glissez librement · touchez le fond pour terminer', hintCluster:'Zoomez ou touchez +N pour déployer · dézoomez pour regrouper', hintView:'Maintenez un nœud pour modifier · glissez le canevas · pincez pour zoomer', empty:'Vide', removed:'Retiré', newFriendJoining:'Un nouvel ami rejoint le réseau…', verifiedAdding:'Vérifié · ajout à ce réseau', newNodeAdded:'Nouveau nœud ajouté' },
  ar: { groups:'المجموعات', myGroups:'مجموعاتي', savedCount:'تم حفظ {count} هنا', createGroup:'إنشاء مجموعة', zoomFirst:'كبّر أولًا لاختيار أشخاص محددين', dropPersonOrTap:'اسحب شخصًا هنا أو اضغط للإنشاء', peopleCount:'{count} أشخاص', releaseAdd:'أفلت للإضافة', emptyReady:'فارغة · جاهزة للإفلات', collapsed:'مطوية', expanded:'مفتوحة', edit:'تعديل', noGroups:'لا توجد مجموعات بعد', optional:'اختيار الأشخاص اختياري', selectedCount:'تم اختيار {count}', willMoveCount:'سيتم نقل {count} إلى هنا', groupName:'اسم المجموعة', cancel:'إلغاء', create:'إنشاء', tapAddRemove:'اضغط على الأشخاص للإضافة أو الإزالة', zeroAllowed:'يمكن حفظها بدون أشخاص', save:'حفظ التغييرات', removeFromGroup:'إزالة من المجموعة', releaseHere:'أفلت هنا', dragUngroup:'اسحب هنا لفك التجميع فقط', undo:'تراجع', addPeople:'إضافة أشخاص', dragOrTap:'اسحب من الشبكة أو اضغط للاختيار', noPeopleSelected:'لم يتم اختيار أشخاص بعد', move:'نقل', editLayout:'تعديل الترتيب', done:'تم', reset:'إعادة ضبط', fit:'ملاءمة العرض', groupsCount:'{count} مجموعات', allCanvas:'الكل في لوحة واحدة', joining:'جارٍ الانضمام', available:'متاح', hintEdit:'اسحب بحرية · اضغط الخلفية للإنهاء', hintCluster:'كبّر أو اضغط +N للفتح · صغّر لإعادة التجميع', hintView:'اضغط مطولًا على العقدة للتعديل · اسحب اللوحة · قرّب بإصبعين للتكبير', empty:'فارغة', removed:'تمت الإزالة', newFriendJoining:'صديق جديد ينضم…', verifiedAdding:'تم التحقق · جارٍ الإضافة إلى هذه الشبكة', newNodeAdded:'تمت إضافة عقدة جديدة' },
  bn: { groups:'গ্রুপ', myGroups:'আমার গ্রুপ', savedCount:'এখানে {count}টি সংরক্ষিত', createGroup:'গ্রুপ তৈরি করুন', zoomFirst:'ব্যক্তি বাছতে আগে জুম ইন করুন', dropPersonOrTap:'একজনকে এখানে টানুন বা তৈরি করতে ট্যাপ করুন', peopleCount:'{count} জন', releaseAdd:'যোগ করতে ছেড়ে দিন', emptyReady:'খালি · ড্রপের জন্য প্রস্তুত', collapsed:'গুটানো', expanded:'খোলা', edit:'সম্পাদনা', noGroups:'এখনও কোনো গ্রুপ নেই', optional:'ব্যক্তি বাছাই ঐচ্ছিক', selectedCount:'{count} জন নির্বাচিত', willMoveCount:'{count} জন এখানে সরবে', groupName:'গ্রুপের নাম', cancel:'বাতিল', create:'তৈরি করুন', tapAddRemove:'যোগ বা সরাতে ব্যক্তিকে ট্যাপ করুন', zeroAllowed:'০ জনও রাখা যায়', save:'পরিবর্তন সংরক্ষণ', removeFromGroup:'গ্রুপ থেকে সরান', releaseHere:'এখানে ছেড়ে দিন', dragUngroup:'শুধু গ্রুপ থেকে সরাতে এখানে টানুন', undo:'পূর্বাবস্থা', addPeople:'ব্যক্তি যোগ করুন', dragOrTap:'নেটওয়ার্ক থেকে টানুন বা বাছতে ট্যাপ করুন', noPeopleSelected:'এখনও কাউকে বাছা হয়নি', move:'সরান', editLayout:'বিন্যাস সম্পাদনা', done:'সম্পন্ন', reset:'রিসেট', fit:'পর্দায় মানান', groupsCount:'{count}টি গ্রুপ', allCanvas:'সব এক ক্যানভাসে', joining:'যোগ দিচ্ছে', available:'উপলব্ধ', hintEdit:'স্বাধীনভাবে টানুন · শেষ করতে পটভূমিতে ট্যাপ করুন', hintCluster:'খুলতে জুম ইন বা +N ট্যাপ করুন · আবার গ্রুপ করতে জুম আউট', hintView:'সম্পাদনার জন্য নোড ধরে রাখুন · ক্যানভাস টানুন · পিঞ্চ করে জুম করুন', empty:'খালি', removed:'সরানো হয়েছে', newFriendJoining:'নতুন বন্ধু যোগ দিচ্ছে…', verifiedAdding:'যাচাই হয়েছে · এই নেটওয়ার্কে যোগ হচ্ছে', newNodeAdded:'নতুন নোড যোগ হয়েছে' },
  pt: { groups:'Grupos', myGroups:'Meus grupos', savedCount:'{count} salvos aqui', createGroup:'Criar grupo', zoomFirst:'Aproxime primeiro para escolher pessoas', dropPersonOrTap:'Arraste uma pessoa aqui ou toque para criar', peopleCount:'{count} pessoas', releaseAdd:'Solte para adicionar', emptyReady:'Vazio · pronto para receber', collapsed:'Recolhido', expanded:'Expandido', edit:'Editar', noGroups:'Ainda não há grupos', optional:'Escolher pessoas é opcional', selectedCount:'{count} selecionadas', willMoveCount:'{count} serão movidas para cá', groupName:'Nome do grupo', cancel:'Cancelar', create:'Criar', tapAddRemove:'Toque nas pessoas para adicionar ou remover', zeroAllowed:'0 pessoas é permitido', save:'Salvar alterações', removeFromGroup:'Remover do grupo', releaseHere:'Solte aqui', dragUngroup:'Arraste aqui apenas para desagrupar', undo:'Desfazer', addPeople:'Adicionar pessoas', dragOrTap:'Arraste da rede ou toque para selecionar', noPeopleSelected:'Nenhuma pessoa selecionada ainda', move:'Mover', editLayout:'Editar layout', done:'Concluído', reset:'Redefinir', fit:'Ajustar à tela', groupsCount:'{count} grupos', allCanvas:'Tudo em uma única tela', joining:'Entrando', available:'Disponível', hintEdit:'Arraste livremente · toque no fundo para terminar', hintCluster:'Aproxime ou toque +N para abrir · afaste para agrupar', hintView:'Segure um nó para editar · arraste a tela · use pinça para ampliar', empty:'Vazio', removed:'Removido', newFriendJoining:'Um novo amigo está entrando…', verifiedAdding:'Verificado · adicionando a esta rede', newNodeAdded:'Novo nó adicionado' },
  ru: { groups:'Группы', myGroups:'Мои группы', savedCount:'Сохранено здесь: {count}', createGroup:'Создать группу', zoomFirst:'Сначала приблизьте, чтобы выбрать людей', dropPersonOrTap:'Перетащите человека сюда или нажмите для создания', peopleCount:'{count} чел.', releaseAdd:'Отпустите, чтобы добавить', emptyReady:'Пусто · готово к добавлению', collapsed:'Свернуто', expanded:'Развернуто', edit:'Изменить', noGroups:'Групп пока нет', optional:'Выбор людей необязателен', selectedCount:'Выбрано: {count}', willMoveCount:'Сюда будет перемещено: {count}', groupName:'Название группы', cancel:'Отмена', create:'Создать', tapAddRemove:'Нажимайте на людей, чтобы добавить или убрать', zeroAllowed:'Можно оставить 0 человек', save:'Сохранить изменения', removeFromGroup:'Убрать из группы', releaseHere:'Отпустите здесь', dragUngroup:'Перетащите сюда только для разгруппировки', undo:'Отменить', addPeople:'Добавить людей', dragOrTap:'Перетащите из сети или нажмите для выбора', noPeopleSelected:'Пока никто не выбран', move:'Переместить', editLayout:'Изменить расположение', done:'Готово', reset:'Сбросить', fit:'Вписать', groupsCount:'{count} групп', allCanvas:'Всё на одном полотне', joining:'Присоединяется', available:'Доступно', hintEdit:'Перетаскивайте свободно · нажмите фон для завершения', hintCluster:'Приблизьте или нажмите +N для раскрытия · отдалите для группировки', hintView:'Удерживайте узел для редактирования · перетаскивайте полотно · масштабируйте щипком', empty:'Пусто', removed:'Удалено', newFriendJoining:'Новый друг присоединяется…', verifiedAdding:'Проверено · добавляем в эту сеть', newNodeAdded:'Новый узел добавлен' },
  id: { groups:'Grup', myGroups:'Grup saya', savedCount:'{count} tersimpan di sini', createGroup:'Buat grup', zoomFirst:'Perbesar dulu untuk memilih orang', dropPersonOrTap:'Seret seseorang ke sini atau ketuk untuk membuat', peopleCount:'{count} orang', releaseAdd:'Lepas untuk menambahkan', emptyReady:'Kosong · siap menerima', collapsed:'Diciutkan', expanded:'Dibuka', edit:'Edit', noGroups:'Belum ada grup', optional:'Memilih orang bersifat opsional', selectedCount:'{count} dipilih', willMoveCount:'{count} akan dipindahkan ke sini', groupName:'Nama grup', cancel:'Batal', create:'Buat', tapAddRemove:'Ketuk orang untuk menambah atau menghapus', zeroAllowed:'0 orang diperbolehkan', save:'Simpan perubahan', removeFromGroup:'Keluarkan dari grup', releaseHere:'Lepas di sini', dragUngroup:'Seret ke sini hanya untuk melepas grup', undo:'Urungkan', addPeople:'Tambah orang', dragOrTap:'Seret dari jaringan atau ketuk untuk memilih', noPeopleSelected:'Belum ada orang yang dipilih', move:'Pindahkan', editLayout:'Edit tata letak', done:'Selesai', reset:'Atur ulang', fit:'Sesuaikan layar', groupsCount:'{count} grup', allCanvas:'Semua dalam satu kanvas', joining:'Sedang bergabung', available:'Tersedia', hintEdit:'Seret bebas · ketuk latar untuk selesai', hintCluster:'Perbesar atau ketuk +N untuk membuka · perkecil untuk mengelompokkan', hintView:'Tahan node untuk mengedit · seret kanvas · cubit untuk memperbesar', empty:'Kosong', removed:'Dihapus', newFriendJoining:'Teman baru sedang bergabung…', verifiedAdding:'Terverifikasi · menambahkan ke jaringan ini', newNodeAdded:'Node baru ditambahkan' },
  vi: { groups:'Nhóm', myGroups:'Nhóm của tôi', savedCount:'Đã lưu {count} nhóm ở đây', createGroup:'Tạo nhóm', zoomFirst:'Hãy phóng to trước để chọn từng người', dropPersonOrTap:'Kéo một người vào đây hoặc chạm để tạo', peopleCount:'{count} người', releaseAdd:'Thả để thêm', emptyReady:'Trống · sẵn sàng nhận', collapsed:'Đã thu gọn', expanded:'Đã mở', edit:'Sửa', noGroups:'Chưa có nhóm', optional:'Chọn người là tùy chọn', selectedCount:'Đã chọn {count}', willMoveCount:'{count} người sẽ chuyển vào đây', groupName:'Tên nhóm', cancel:'Hủy', create:'Tạo', tapAddRemove:'Chạm vào người để thêm hoặc xóa', zeroAllowed:'Có thể để 0 người', save:'Lưu thay đổi', removeFromGroup:'Xóa khỏi nhóm', releaseHere:'Thả tại đây', dragUngroup:'Kéo vào đây chỉ để bỏ nhóm', undo:'Hoàn tác', addPeople:'Thêm người', dragOrTap:'Kéo từ mạng hoặc chạm để chọn', noPeopleSelected:'Chưa chọn ai', move:'Di chuyển', editLayout:'Sửa bố cục', done:'Xong', reset:'Đặt lại', fit:'Vừa màn hình', groupsCount:'{count} nhóm', allCanvas:'Tất cả trên một màn hình', joining:'Đang tham gia', available:'Có thể mời', hintEdit:'Kéo tự do · chạm nền để kết thúc', hintCluster:'Phóng to hoặc chạm +N để mở · thu nhỏ để nhóm lại', hintView:'Giữ nút để chỉnh sửa · kéo màn hình · chụm để thu phóng', empty:'Trống', removed:'Đã xóa', newFriendJoining:'Một người bạn mới đang tham gia…', verifiedAdding:'Đã xác minh · đang thêm vào mạng này', newNodeAdded:'Đã thêm nút mới' },
  'zh-tw': { groups:'群組', myGroups:'我的群組', savedCount:'已在此儲存 {count} 個', createGroup:'建立群組', zoomFirst:'請先放大再選擇個別使用者', dropPersonOrTap:'把使用者拖到這裡，或點按建立', peopleCount:'{count} 人', releaseAdd:'放開以加入', emptyReady:'空群組 · 可拖入', collapsed:'已收合', expanded:'已展開', edit:'編輯', noGroups:'還沒有群組', optional:'可不選擇使用者', selectedCount:'已選 {count} 人', willMoveCount:'{count} 人將移到這裡', groupName:'群組名稱', cancel:'取消', create:'建立', tapAddRemove:'點按使用者以加入或移除', zeroAllowed:'允許 0 人', save:'儲存變更', removeFromGroup:'移出群組', releaseHere:'在此放開', dragUngroup:'拖到這裡只解除群組', undo:'復原', addPeople:'加入使用者', dragOrTap:'從網絡拖入或點按選擇', noPeopleSelected:'尚未選擇使用者', move:'移動', editLayout:'編輯配置', done:'完成', reset:'重設', fit:'符合畫面', groupsCount:'{count} 個群組', allCanvas:'全部顯示在同一畫布', joining:'加入中', available:'可邀請', hintEdit:'自由拖動 · 點按背景結束', hintCluster:'放大或點 +N 展開 · 縮小後重新分組', hintView:'長按節點編輯 · 拖動畫布 · 雙指縮放', empty:'空', removed:'已移除', newFriendJoining:'新朋友正在加入…', verifiedAdding:'已驗證 · 正在加入此網絡', newNodeAdded:'已加入新節點' },
  sv: { groups:'Grupper', myGroups:'Mina grupper', savedCount:'{count} sparade här', createGroup:'Skapa grupp', zoomFirst:'Zooma in först för att välja personer', dropPersonOrTap:'Dra en person hit eller tryck för att skapa', peopleCount:'{count} personer', releaseAdd:'Släpp för att lägga till', emptyReady:'Tom · redo att ta emot', collapsed:'Ihopfälld', expanded:'Utfälld', edit:'Redigera', noGroups:'Inga grupper ännu', optional:'Personer är valfria', selectedCount:'{count} valda', willMoveCount:'{count} flyttas hit', groupName:'Gruppnamn', cancel:'Avbryt', create:'Skapa', tapAddRemove:'Tryck på personer för att lägga till eller ta bort', zeroAllowed:'0 personer är tillåtet', save:'Spara ändringar', removeFromGroup:'Ta bort från grupp', releaseHere:'Släpp här', dragUngroup:'Dra hit för att endast ta bort gruppen', undo:'Ångra', addPeople:'Lägg till personer', dragOrTap:'Dra från nätverket eller tryck för att välja', noPeopleSelected:'Inga personer valda ännu', move:'Flytta', editLayout:'Redigera layout', done:'Klar', reset:'Återställ', fit:'Anpassa', groupsCount:'{count} grupper', allCanvas:'Allt på en yta', joining:'Ansluter', available:'Tillgänglig', hintEdit:'Dra fritt · tryck på bakgrunden för att avsluta', hintCluster:'Zooma in eller tryck +N för att öppna · zooma ut för att gruppera', hintView:'Håll en nod för att redigera · dra ytan · nyp för att zooma', empty:'Tom', removed:'Borttagen', newFriendJoining:'En ny vän ansluter…', verifiedAdding:'Verifierad · läggs till i nätverket', newNodeAdded:'Ny nod tillagd' },
  ro: { groups:'Grupuri', myGroups:'Grupurile mele', savedCount:'{count} salvate aici', createGroup:'Creează grup', zoomFirst:'Mărește mai întâi pentru a alege persoane', dropPersonOrTap:'Trage o persoană aici sau atinge pentru a crea', peopleCount:'{count} persoane', releaseAdd:'Eliberează pentru a adăuga', emptyReady:'Gol · pregătit pentru plasare', collapsed:'Restrâns', expanded:'Extins', edit:'Editează', noGroups:'Nu există grupuri încă', optional:'Persoanele sunt opționale', selectedCount:'{count} selectate', willMoveCount:'{count} vor fi mutate aici', groupName:'Numele grupului', cancel:'Anulează', create:'Creează', tapAddRemove:'Atinge persoane pentru a adăuga sau elimina', zeroAllowed:'Sunt permise 0 persoane', save:'Salvează modificările', removeFromGroup:'Elimină din grup', releaseHere:'Eliberează aici', dragUngroup:'Trage aici doar pentru a scoate din grup', undo:'Anulează', addPeople:'Adaugă persoane', dragOrTap:'Trage din rețea sau atinge pentru selectare', noPeopleSelected:'Nicio persoană selectată încă', move:'Mută', editLayout:'Editează aranjarea', done:'Gata', reset:'Resetează', fit:'Potrivește', groupsCount:'{count} grupuri', allCanvas:'Totul pe o singură suprafață', joining:'Se alătură', available:'Disponibil', hintEdit:'Trage liber · atinge fundalul pentru a termina', hintCluster:'Mărește sau atinge +N pentru deschidere · micșorează pentru grupare', hintView:'Ține apăsat un nod pentru editare · trage suprafața · apropie/departează cu două degete', empty:'Gol', removed:'Eliminat', newFriendJoining:'Un prieten nou se alătură…', verifiedAdding:'Verificat · se adaugă în această rețea', newNodeAdded:'Nod nou adăugat' },
  ur: { groups:'گروپس', myGroups:'میرے گروپس', savedCount:'یہاں {count} محفوظ ہیں', createGroup:'گروپ بنائیں', zoomFirst:'افراد منتخب کرنے کے لیے پہلے زوم اِن کریں', dropPersonOrTap:'کسی شخص کو یہاں گھسیٹیں یا بنانے کے لیے ٹیپ کریں', peopleCount:'{count} افراد', releaseAdd:'شامل کرنے کے لیے چھوڑیں', emptyReady:'خالی · ڈراپ کے لیے تیار', collapsed:'سمٹا ہوا', expanded:'کھلا ہوا', edit:'ترمیم', noGroups:'ابھی کوئی گروپ نہیں', optional:'افراد منتخب کرنا اختیاری ہے', selectedCount:'{count} منتخب', willMoveCount:'{count} یہاں منتقل ہوں گے', groupName:'گروپ کا نام', cancel:'منسوخ', create:'بنائیں', tapAddRemove:'شامل یا ہٹانے کے لیے افراد پر ٹیپ کریں', zeroAllowed:'0 افراد بھی ممکن ہیں', save:'تبدیلیاں محفوظ کریں', removeFromGroup:'گروپ سے ہٹائیں', releaseHere:'یہاں چھوڑیں', dragUngroup:'صرف گروپ ختم کرنے کے لیے یہاں گھسیٹیں', undo:'واپس کریں', addPeople:'افراد شامل کریں', dragOrTap:'نیٹ ورک سے گھسیٹیں یا منتخب کرنے کے لیے ٹیپ کریں', noPeopleSelected:'ابھی کوئی شخص منتخب نہیں', move:'منتقل کریں', editLayout:'ترتیب میں ترمیم', done:'مکمل', reset:'دوبارہ ترتیب', fit:'اسکرین میں فِٹ', groupsCount:'{count} گروپس', allCanvas:'سب ایک ہی کینوس پر', joining:'شامل ہو رہا ہے', available:'دستیاب', hintEdit:'آزادانہ گھسیٹیں · ختم کرنے کے لیے پس منظر پر ٹیپ کریں', hintCluster:'کھولنے کے لیے زوم اِن یا +N ٹیپ کریں · گروپ کے لیے زوم آؤٹ', hintView:'ترمیم کے لیے نوڈ دبائے رکھیں · کینوس گھسیٹیں · زوم کے لیے پِنچ کریں', empty:'خالی', removed:'ہٹا دیا گیا', newFriendJoining:'نیا دوست شامل ہو رہا ہے…', verifiedAdding:'تصدیق ہوگئی · اس نیٹ ورک میں شامل کیا جا رہا ہے', newNodeAdded:'نیا نوڈ شامل ہوگیا' },
  pcm: { groups:'Groups', myGroups:'My groups', savedCount:'{count} dey saved here', createGroup:'Create group', zoomFirst:'Zoom in first make you choose person', dropPersonOrTap:'Drag person come here or tap to create', peopleCount:'{count} people', releaseAdd:'Leave am here to add', emptyReady:'Empty · ready for drop', collapsed:'Folded', expanded:'Open', edit:'Edit', noGroups:'No group yet', optional:'People no compulsory', selectedCount:'{count} selected', willMoveCount:'{count} go move come here', groupName:'Group name', cancel:'Cancel', create:'Create', tapAddRemove:'Tap people to add or remove', zeroAllowed:'0 person dey okay', save:'Save changes', removeFromGroup:'Comot from group', releaseHere:'Leave am here', dragUngroup:'Drag come here only to comot group', undo:'Undo', addPeople:'Add people', dragOrTap:'Drag from network or tap to choose', noPeopleSelected:'You never choose anybody', move:'Move', editLayout:'Edit arrangement', done:'Done', reset:'Reset', fit:'Fit screen', groupsCount:'{count} groups', allCanvas:'Everything for one canvas', joining:'Dey join', available:'Available', hintEdit:'Drag anyhow · tap background to finish', hintCluster:'Zoom in or tap +N to open · zoom out to group again', hintView:'Hold node to edit · drag canvas · pinch to zoom', empty:'Empty', removed:'Removed', newFriendJoining:'New friend dey join…', verifiedAdding:'Verified · dey add am to this network', newNodeAdded:'New node don add' },
  arz: { groups:'المجموعات', myGroups:'مجموعاتي', savedCount:'متسجل هنا {count}', createGroup:'اعمل مجموعة', zoomFirst:'كبّر الأول عشان تختار أشخاص', dropPersonOrTap:'اسحب شخص هنا أو دوس عشان تعمل مجموعة', peopleCount:'{count} أشخاص', releaseAdd:'سيب عشان تضيف', emptyReady:'فاضية · جاهزة للإضافة', collapsed:'مقفولة', expanded:'مفتوحة', edit:'تعديل', noGroups:'مفيش مجموعات لسه', optional:'اختيار الأشخاص اختياري', selectedCount:'مختار {count}', willMoveCount:'{count} هيتنقلوا هنا', groupName:'اسم المجموعة', cancel:'إلغاء', create:'إنشاء', tapAddRemove:'دوس على الأشخاص عشان تضيف أو تشيل', zeroAllowed:'ينفع 0 أشخاص', save:'حفظ التغييرات', removeFromGroup:'شيل من المجموعة', releaseHere:'سيب هنا', dragUngroup:'اسحب هنا بس عشان تفك المجموعة', undo:'رجوع', addPeople:'ضيف أشخاص', dragOrTap:'اسحب من الشبكة أو دوس للاختيار', noPeopleSelected:'محدش متحدد لسه', move:'نقل', editLayout:'تعديل الترتيب', done:'تم', reset:'إعادة ضبط', fit:'ظبط على الشاشة', groupsCount:'{count} مجموعات', allCanvas:'الكل في شاشة واحدة', joining:'بينضم', available:'متاح', hintEdit:'اسحب براحتك · دوس على الخلفية عشان تخلص', hintCluster:'كبّر أو دوس +N عشان تفتح · صغّر عشان تجمع تاني', hintView:'اضغط مطول على العقدة للتعديل · اسحب الشاشة · قرّب بإصبعين', empty:'فاضية', removed:'اتشالت', newFriendJoining:'صديق جديد بينضم…', verifiedAdding:'اتأكدنا · بنضيفه للشبكة دي', newNodeAdded:'اتضافت عقدة جديدة' },
  mr: { groups:'गट', myGroups:'माझे गट', savedCount:'इथे {count} जतन केले', createGroup:'गट तयार करा', zoomFirst:'लोक निवडण्यासाठी आधी झूम इन करा', dropPersonOrTap:'एखाद्याला इथे ओढा किंवा तयार करण्यासाठी टॅप करा', peopleCount:'{count} जण', releaseAdd:'जोडण्यासाठी सोडा', emptyReady:'रिकामा · ड्रॉपसाठी तयार', collapsed:'मिटवलेला', expanded:'उघडलेला', edit:'संपादित करा', noGroups:'अजून गट नाहीत', optional:'लोक निवडणे ऐच्छिक आहे', selectedCount:'{count} निवडले', willMoveCount:'{count} इथे हलतील', groupName:'गटाचे नाव', cancel:'रद्द करा', create:'तयार करा', tapAddRemove:'जोडण्यासाठी किंवा काढण्यासाठी लोकांवर टॅप करा', zeroAllowed:'0 जणही चालतील', save:'बदल जतन करा', removeFromGroup:'गटातून काढा', releaseHere:'इथे सोडा', dragUngroup:'फक्त गटातून काढण्यासाठी इथे ओढा', undo:'पूर्ववत करा', addPeople:'लोक जोडा', dragOrTap:'नेटवर्कमधून ओढा किंवा निवडण्यासाठी टॅप करा', noPeopleSelected:'अजून कोणी निवडलेले नाही', move:'हलवा', editLayout:'मांडणी संपादित करा', done:'पूर्ण', reset:'रीसेट', fit:'स्क्रीनमध्ये बसवा', groupsCount:'{count} गट', allCanvas:'सगळे एका कॅनव्हासवर', joining:'सामील होत आहे', available:'उपलब्ध', hintEdit:'मोकळेपणाने ओढा · संपवण्यासाठी पार्श्वभूमीवर टॅप करा', hintCluster:'उघडण्यासाठी झूम इन किंवा +N टॅप करा · पुन्हा गटासाठी झूम आउट', hintView:'संपादनासाठी नोड धरून ठेवा · कॅनव्हास ओढा · पिंच करून झूम करा', empty:'रिकामा', removed:'काढले', newFriendJoining:'नवा मित्र सामील होत आहे…', verifiedAdding:'पडताळले · या नेटवर्कमध्ये जोडत आहे', newNodeAdded:'नवा नोड जोडला' },
  te: { groups:'గ్రూపులు', myGroups:'నా గ్రూపులు', savedCount:'ఇక్కడ {count} సేవ్ అయ్యాయి', createGroup:'గ్రూపు సృష్టించండి', zoomFirst:'వ్యక్తులను ఎంచుకోవడానికి ముందుగా జూమ్ ఇన్ చేయండి', dropPersonOrTap:'ఒకరిని ఇక్కడికి లాగండి లేదా సృష్టించడానికి ట్యాప్ చేయండి', peopleCount:'{count} మంది', releaseAdd:'జోడించడానికి వదలండి', emptyReady:'ఖాళీ · డ్రాప్‌కు సిద్ధం', collapsed:'ముడిచింది', expanded:'తెరిచింది', edit:'సవరించు', noGroups:'ఇంకా గ్రూపులు లేవు', optional:'వ్యక్తులను ఎంచుకోవడం ఐచ్ఛికం', selectedCount:'{count} మంది ఎంపిక', willMoveCount:'{count} మంది ఇక్కడికి మారతారు', groupName:'గ్రూపు పేరు', cancel:'రద్దు', create:'సృష్టించు', tapAddRemove:'జోడించడానికి లేదా తీసివేయడానికి వ్యక్తిని ట్యాప్ చేయండి', zeroAllowed:'0 మంది కూడా అనుమతి', save:'మార్పులు సేవ్ చేయండి', removeFromGroup:'గ్రూపు నుంచి తీసివేయి', releaseHere:'ఇక్కడ వదలండి', dragUngroup:'గ్రూపు మాత్రమే తొలగించడానికి ఇక్కడికి లాగండి', undo:'వెనక్కి', addPeople:'వ్యక్తులను జోడించు', dragOrTap:'నెట్‌వర్క్ నుంచి లాగండి లేదా ఎంచుకోవడానికి ట్యాప్ చేయండి', noPeopleSelected:'ఇంకా ఎవరినీ ఎంచుకోలేదు', move:'తరలించు', editLayout:'అమరిక సవరించు', done:'పూర్తి', reset:'రీసెట్', fit:'స్క్రీన్‌కు సరిపడు', groupsCount:'{count} గ్రూపులు', allCanvas:'అన్నీ ఒకే కాన్వాస్‌లో', joining:'చేరుతోంది', available:'అందుబాటులో', hintEdit:'స్వేచ్ఛగా లాగండి · ముగించడానికి నేపథ్యాన్ని ట్యాప్ చేయండి', hintCluster:'తెరవడానికి జూమ్ ఇన్ లేదా +N ట్యాప్ చేయండి · గ్రూపు చేయడానికి జూమ్ అవుట్', hintView:'సవరించడానికి నోడ్‌ను పట్టుకోండి · కాన్వాస్ లాగండి · పించ్‌తో జూమ్ చేయండి', empty:'ఖాళీ', removed:'తీసివేశారు', newFriendJoining:'కొత్త స్నేహితుడు చేరుతున్నాడు…', verifiedAdding:'ధృవీకరించబడింది · ఈ నెట్‌వర్క్‌కు జోడిస్తోంది', newNodeAdded:'కొత్త నోడ్ జోడించబడింది' },
  sw: { groups:'Vikundi', myGroups:'Vikundi vyangu', savedCount:'{count} vimehifadhiwa hapa', createGroup:'Unda kikundi', zoomFirst:'Kuza kwanza ili uchague watu', dropPersonOrTap:'Buruta mtu hapa au gusa ili kuunda', peopleCount:'Watu {count}', releaseAdd:'Achia ili kuongeza', emptyReady:'Tupu · tayari kupokea', collapsed:'Kimekunjwa', expanded:'Kimefunguliwa', edit:'Hariri', noGroups:'Bado hakuna vikundi', optional:'Kuchagua watu si lazima', selectedCount:'Wamechaguliwa {count}', willMoveCount:'{count} watahamia hapa', groupName:'Jina la kikundi', cancel:'Ghairi', create:'Unda', tapAddRemove:'Gusa watu ili kuongeza au kuondoa', zeroAllowed:'Watu 0 wanaruhusiwa', save:'Hifadhi mabadiliko', removeFromGroup:'Ondoa kwenye kikundi', releaseHere:'Achia hapa', dragUngroup:'Buruta hapa ili kuondoa kwenye kikundi tu', undo:'Tendua', addPeople:'Ongeza watu', dragOrTap:'Buruta kutoka mtandaoni au gusa ili kuchagua', noPeopleSelected:'Bado hakuna aliyechaguliwa', move:'Hamisha', editLayout:'Hariri mpangilio', done:'Imekamilika', reset:'Weka upya', fit:'Linganisha na skrini', groupsCount:'Vikundi {count}', allCanvas:'Yote kwenye eneo moja', joining:'Anaingia', available:'Inapatikana', hintEdit:'Buruta kwa uhuru · gusa mandharinyuma kumaliza', hintCluster:'Kuza au gusa +N kufungua · punguza ili kupanga tena', hintView:'Shikilia nodi kuhariri · buruta eneo · bana vidole kukuza', empty:'Tupu', removed:'Imeondolewa', newFriendJoining:'Rafiki mpya anaingia…', verifiedAdding:'Imethibitishwa · inaongezwa kwenye mtandao huu', newNodeAdded:'Nodi mpya imeongezwa' },
  ha: { groups:'Rukuni', myGroups:'Rukunina', savedCount:'An ajiye {count} a nan', createGroup:'Ƙirƙiri rukuni', zoomFirst:'Da farko ka ƙara girma domin zaɓar mutane', dropPersonOrTap:'Ja mutum nan ko danna don ƙirƙira', peopleCount:'Mutane {count}', releaseAdd:'Saki don ƙara', emptyReady:'Fanko · a shirye don karɓa', collapsed:'An naɗe', expanded:'An buɗe', edit:'Gyara', noGroups:'Babu rukuni tukuna', optional:'Zaɓar mutane ba dole ba ne', selectedCount:'An zaɓi {count}', willMoveCount:'Za a matsar da {count} nan', groupName:'Sunan rukuni', cancel:'Soke', create:'Ƙirƙira', tapAddRemove:'Danna mutane don ƙara ko cirewa', zeroAllowed:'Mutane 0 ma ya halatta', save:'Ajiye canje-canje', removeFromGroup:'Cire daga rukuni', releaseHere:'Saki a nan', dragUngroup:'Ja nan don cirewa daga rukuni kawai', undo:'Mayar baya', addPeople:'Ƙara mutane', dragOrTap:'Ja daga cibiyar ko danna don zaɓa', noPeopleSelected:'Ba a zaɓi kowa ba tukuna', move:'Matsar', editLayout:'Gyara tsari', done:'An gama', reset:'Sake saita', fit:'Daidaita allo', groupsCount:'Rukuni {count}', allCanvas:'Duka a wuri ɗaya', joining:'Yana shiga', available:'Akwai', hintEdit:'Ja yadda kake so · danna baya don gama', hintCluster:'Ƙara girma ko danna +N don buɗewa · rage don sake haɗawa', hintView:'Riƙe nodi don gyara · ja fili · matse yatsu don zuƙowa', empty:'Fanko', removed:'An cire', newFriendJoining:'Sabon aboki yana shiga…', verifiedAdding:'An tabbatar · ana ƙara shi cikin wannan cibiya', newNodeAdded:'An ƙara sabon nodi' },
  el: { groups:'Ομάδες', myGroups:'Οι ομάδες μου', savedCount:'{count} αποθηκευμένες εδώ', createGroup:'Δημιουργία ομάδας', zoomFirst:'Μεγέθυνε πρώτα για να επιλέξεις άτομα', dropPersonOrTap:'Σύρε ένα άτομο εδώ ή πάτησε για δημιουργία', peopleCount:'{count} άτομα', releaseAdd:'Άφησε για προσθήκη', emptyReady:'Κενή · έτοιμη για απόθεση', collapsed:'Συμπτυγμένη', expanded:'Αναπτυγμένη', edit:'Επεξεργασία', noGroups:'Δεν υπάρχουν ομάδες ακόμη', optional:'Η επιλογή ατόμων είναι προαιρετική', selectedCount:'{count} επιλεγμένα', willMoveCount:'{count} θα μετακινηθούν εδώ', groupName:'Όνομα ομάδας', cancel:'Ακύρωση', create:'Δημιουργία', tapAddRemove:'Πάτησε άτομα για προσθήκη ή αφαίρεση', zeroAllowed:'Επιτρέπονται 0 άτομα', save:'Αποθήκευση αλλαγών', removeFromGroup:'Αφαίρεση από ομάδα', releaseHere:'Άφησε εδώ', dragUngroup:'Σύρε εδώ μόνο για αποδέσμευση από ομάδα', undo:'Αναίρεση', addPeople:'Προσθήκη ατόμων', dragOrTap:'Σύρε από το δίκτυο ή πάτησε για επιλογή', noPeopleSelected:'Δεν έχει επιλεγεί άτομο ακόμη', move:'Μετακίνηση', editLayout:'Επεξεργασία διάταξης', done:'Τέλος', reset:'Επαναφορά', fit:'Προσαρμογή', groupsCount:'{count} ομάδες', allCanvas:'Όλα σε έναν καμβά', joining:'Συνδέεται', available:'Διαθέσιμο', hintEdit:'Σύρε ελεύθερα · πάτησε το φόντο για τέλος', hintCluster:'Μεγέθυνε ή πάτησε +N για ανάπτυξη · σμίκρυνε για ομαδοποίηση', hintView:'Κράτησε κόμβο για επεξεργασία · σύρε τον καμβά · τσίμπησε για ζουμ', empty:'Κενή', removed:'Αφαιρέθηκε', newFriendJoining:'Ένας νέος φίλος συνδέεται…', verifiedAdding:'Επαληθεύτηκε · προσθήκη σε αυτό το δίκτυο', newNodeAdded:'Προστέθηκε νέος κόμβος' }
  cs: { groups:'Skupiny', myGroups:'Moje skupiny', savedCount:'Uloženo zde: {count}', createGroup:'Vytvořit skupinu', zoomFirst:'Nejprve přibliž, abys mohl vybrat jednotlivé lidi', dropPersonOrTap:'Přetáhni sem člověka nebo klepni pro vytvoření', peopleCount:'Lidé: {count}', releaseAdd:'Pusť pro přidání', emptyReady:'Prázdné · připraveno k přetažení', collapsed:'Sbaleno', expanded:'Rozbaleno', edit:'Upravit', noGroups:'Zatím žádné skupiny', optional:'Výběr lidí je volitelný', selectedCount:'Vybráno: {count}', willMoveCount:'Sem se přesune: {count}', groupName:'Název skupiny', cancel:'Zrušit', create:'Vytvořit', tapAddRemove:'Klepnutím lidi přidáš nebo odebereš', zeroAllowed:'Skupina může zůstat prázdná', save:'Uložit změny', removeFromGroup:'Odebrat ze skupiny', releaseHere:'Pusť sem', dragUngroup:'Přetáhni sem pouze pro odebrání ze skupiny', undo:'Zpět', addPeople:'Přidat lidi', dragOrTap:'Přetáhni ze sítě nebo klepnutím vyber', noPeopleSelected:'Zatím nikdo není vybrán', move:'Přesunout', editLayout:'Upravit rozložení', done:'Hotovo', reset:'Obnovit', fit:'Přizpůsobit', groupsCount:'Skupiny: {count}', allCanvas:'Vše na jedné obrazovce', joining:'Připojuje se', available:'Lze pozvat', hintEdit:'Volně přetahuj · klepnutím na pozadí dokonči', hintCluster:'Přibliž nebo klepni na +N pro rozbalení · oddálením znovu seskupíš', hintView:'Podrž člověka pro úpravy · táhni obrazovku · sevřením prstů měň přiblížení', empty:'Prázdné', removed:'Odstraněno', newFriendJoining:'Připojuje se nový přítel…', verifiedAdding:'Ověřeno · přidává se do této sítě', newNodeAdded:'Přidán nový přítel' },
} satisfies Record<SupportedLocale, NetworkCanaryUiCopy>;

export function formatNetworkCanaryUiCopy(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}
