import type { SupportedLocale } from './locales';

type NotificationV2Copy = {
  dappProgressTitle: string;
  dappProgressBody: string;
  rewardReadyTitle: string;
  rewardReadyBody: string;
  summaryTitle: string;
  summaryBody: string;
  friendProgress: string;
};

export const NOTIFICATION_V2_COPY: Record<SupportedLocale, NotificationV2Copy> = {
  en: { dappProgressTitle: 'Friend progress updated', dappProgressBody: 'Your friend completed another qualifying dApp and received its B3TR reward.', rewardReadyTitle: 'Friend invite completed!', rewardReadyBody: 'Final verification passed, your reward is fixed, and the friend slot is available again.', summaryTitle: 'New friend progress', summaryBody: 'Several friends progressed while you were away. Here is their latest verified status.', friendProgress: 'Latest progress' },
  ko: { dappProgressTitle: '친구 진행 상황이 업데이트됐어요', dappProgressBody: '친구가 dApp을 하나 더 이용하고 해당 B3TR 보상까지 받았어요.', rewardReadyTitle: '친구 초대가 완료됐어요!', rewardReadyBody: '최종 확인을 통과해 보상이 확정됐고 친구 슬롯도 다시 사용할 수 있어요.', summaryTitle: '새로운 친구 진행 상황', summaryBody: '앱을 보지 않는 동안 여러 친구가 진행했어요. 현재 확인된 최신 상태만 보여드려요.', friendProgress: '최신 진행' },
  zh: { dappProgressTitle: '好友进度已更新', dappProgressBody: '好友又完成了一个符合条件的 dApp，并获得了对应的 B3TR 奖励。', rewardReadyTitle: '好友邀请已完成！', rewardReadyBody: '最终验证已通过，奖励金额已锁定，好友名额也可以再次使用。', summaryTitle: '好友有新进展', summaryBody: '你离开期间有多位好友取得了进展。这里显示各自最新的已验证状态。', friendProgress: '最新进度' },
  hi: { dappProgressTitle: 'दोस्त की प्रगति अपडेट हुई', dappProgressBody: 'आपके दोस्त ने एक और योग्य dApp पूरा किया और उसका B3TR रिवॉर्ड प्राप्त किया।', rewardReadyTitle: 'दोस्त का आमंत्रण पूरा हुआ!', rewardReadyBody: 'अंतिम सत्यापन पास हो गया, रिवॉर्ड तय हो गया और फ्रेंड स्लॉट फिर से उपलब्ध है।', summaryTitle: 'दोस्तों की नई प्रगति', summaryBody: 'आपके दूर रहने के दौरान कई दोस्तों ने प्रगति की। यहाँ उनकी नवीनतम सत्यापित स्थिति है।', friendProgress: 'नवीनतम प्रगति' },
  es: { dappProgressTitle: 'Progreso de tu amigo actualizado', dappProgressBody: 'Tu amigo completó otra dApp válida y recibió su recompensa en B3TR.', rewardReadyTitle: '¡Invitación completada!', rewardReadyBody: 'La verificación final fue aprobada, tu recompensa quedó fijada y el espacio de amigo vuelve a estar disponible.', summaryTitle: 'Nuevo progreso de tus amigos', summaryBody: 'Varios amigos avanzaron mientras no estabas. Aquí tienes su estado verificado más reciente.', friendProgress: 'Último progreso' },
  ja: { dappProgressTitle: '友だちの進捗が更新されました', dappProgressBody: '友だちが対象dAppをもう1つ完了し、そのB3TR報酬を受け取りました。', rewardReadyTitle: '友だちの招待が完了しました！', rewardReadyBody: '最終確認を通過し、報酬額が確定しました。友だちスロットも再び利用できます。', summaryTitle: '友だちに新しい進捗があります', summaryBody: '離れている間に複数の友だちが進みました。最新の確認済み状態を表示します。', friendProgress: '最新の進捗' },
  it: { dappProgressTitle: 'Progressi dell’amico aggiornati', dappProgressBody: 'Il tuo amico ha completato un’altra dApp valida e ricevuto la relativa ricompensa B3TR.', rewardReadyTitle: 'Invito completato!', rewardReadyBody: 'La verifica finale è superata, la ricompensa è fissata e lo slot amico è di nuovo disponibile.', summaryTitle: 'Nuovi progressi degli amici', summaryBody: 'Più amici hanno fatto progressi mentre eri via. Ecco il loro ultimo stato verificato.', friendProgress: 'Ultimo progresso' },
  tr: { dappProgressTitle: 'Arkadaş ilerlemesi güncellendi', dappProgressBody: 'Arkadaşın bir uygun dApp daha tamamladı ve ilgili B3TR ödülünü aldı.', rewardReadyTitle: 'Arkadaş daveti tamamlandı!', rewardReadyBody: 'Son doğrulama geçti, ödülün sabitlendi ve arkadaş slotu yeniden kullanılabilir.', summaryTitle: 'Arkadaşlarında yeni ilerleme', summaryBody: 'Sen yokken birden fazla arkadaş ilerledi. En son doğrulanmış durumları burada.', friendProgress: 'Son ilerleme' },
  nl: { dappProgressTitle: 'Voortgang van je vriend bijgewerkt', dappProgressBody: 'Je vriend voltooide nog een geldige dApp en ontving de bijbehorende B3TR-beloning.', rewardReadyTitle: 'Vrienduitnodiging voltooid!', rewardReadyBody: 'De eindcontrole is geslaagd, je beloning staat vast en het vriendenslot is weer beschikbaar.', summaryTitle: 'Nieuwe voortgang van vrienden', summaryBody: 'Meerdere vrienden maakten voortgang terwijl je weg was. Dit is hun nieuwste geverifieerde status.', friendProgress: 'Laatste voortgang' },
  de: { dappProgressTitle: 'Fortschritt deines Freundes aktualisiert', dappProgressBody: 'Dein Freund hat eine weitere gültige dApp abgeschlossen und die zugehörige B3TR-Belohnung erhalten.', rewardReadyTitle: 'Freundeseinladung abgeschlossen!', rewardReadyBody: 'Die Abschlussprüfung ist bestanden, deine Belohnung ist festgelegt und der Freundes-Slot ist wieder frei.', summaryTitle: 'Neue Fortschritte deiner Freunde', summaryBody: 'Mehrere Freunde haben Fortschritte gemacht. Hier siehst du den neuesten verifizierten Stand.', friendProgress: 'Neuester Fortschritt' },
  fr: { dappProgressTitle: 'Progression de votre ami mise à jour', dappProgressBody: 'Votre ami a terminé une autre dApp éligible et reçu la récompense B3TR correspondante.', rewardReadyTitle: 'Invitation terminée !', rewardReadyBody: 'La vérification finale est validée, votre récompense est fixée et le créneau ami est de nouveau disponible.', summaryTitle: 'Nouveaux progrès de vos amis', summaryBody: 'Plusieurs amis ont progressé pendant votre absence. Voici leur dernier état vérifié.', friendProgress: 'Dernière progression' },
  ar: { dappProgressTitle: 'تم تحديث تقدم صديقك', dappProgressBody: 'أكمل صديقك تطبيق dApp مؤهلاً إضافياً وحصل على مكافأة B3TR الخاصة به.', rewardReadyTitle: 'اكتملت دعوة الصديق!', rewardReadyBody: 'تم اجتياز التحقق النهائي وتثبيت مكافأتك وأصبح مكان الصديق متاحاً من جديد.', summaryTitle: 'تقدم جديد للأصدقاء', summaryBody: 'تقدم عدة أصدقاء أثناء غيابك. هذه أحدث حالاتهم التي تم التحقق منها.', friendProgress: 'أحدث تقدم' },
  bn: { dappProgressTitle: 'বন্ধুর অগ্রগতি আপডেট হয়েছে', dappProgressBody: 'আপনার বন্ধু আরও একটি যোগ্য dApp সম্পন্ন করেছে এবং তার B3TR রিওয়ার্ড পেয়েছে।', rewardReadyTitle: 'বন্ধুর আমন্ত্রণ সম্পন্ন!', rewardReadyBody: 'চূড়ান্ত যাচাই পাস হয়েছে, আপনার রিওয়ার্ড নির্ধারিত হয়েছে এবং বন্ধুর স্লট আবার ব্যবহার করা যাবে।', summaryTitle: 'বন্ধুদের নতুন অগ্রগতি', summaryBody: 'আপনি না থাকাকালে একাধিক বন্ধু এগিয়েছে। এখানে তাদের সর্বশেষ যাচাইকৃত অবস্থা রয়েছে।', friendProgress: 'সর্বশেষ অগ্রগতি' },
  pt: { dappProgressTitle: 'Progresso do amigo atualizado', dappProgressBody: 'Seu amigo concluiu outro dApp elegível e recebeu a recompensa B3TR correspondente.', rewardReadyTitle: 'Convite concluído!', rewardReadyBody: 'A verificação final foi aprovada, sua recompensa foi fixada e o espaço de amigo está disponível novamente.', summaryTitle: 'Novo progresso dos amigos', summaryBody: 'Vários amigos avançaram enquanto você estava fora. Veja o status verificado mais recente de cada um.', friendProgress: 'Progresso mais recente' },
  ru: { dappProgressTitle: 'Прогресс друга обновлён', dappProgressBody: 'Ваш друг выполнил ещё одно подходящее действие в dApp и получил соответствующую награду B3TR.', rewardReadyTitle: 'Приглашение друга завершено!', rewardReadyBody: 'Финальная проверка пройдена, награда зафиксирована, а слот друга снова доступен.', summaryTitle: 'Новый прогресс друзей', summaryBody: 'Пока вас не было, несколько друзей продвинулись. Здесь показан их последний подтверждённый статус.', friendProgress: 'Последний прогресс' },
  id: { dappProgressTitle: 'Progres teman diperbarui', dappProgressBody: 'Temanmu menyelesaikan satu dApp yang memenuhi syarat lagi dan menerima reward B3TR-nya.', rewardReadyTitle: 'Undangan teman selesai!', rewardReadyBody: 'Verifikasi akhir lolos, reward-mu sudah ditetapkan, dan slot teman bisa digunakan lagi.', summaryTitle: 'Progres baru dari teman', summaryBody: 'Beberapa teman maju saat kamu tidak membuka aplikasi. Ini status terverifikasi terbaru mereka.', friendProgress: 'Progres terbaru' },
  vi: { dappProgressTitle: 'Tiến độ của bạn bè đã cập nhật', dappProgressBody: 'Bạn của bạn đã hoàn thành thêm một dApp hợp lệ và nhận phần thưởng B3TR tương ứng.', rewardReadyTitle: 'Lời mời bạn bè đã hoàn tất!', rewardReadyBody: 'Xác minh cuối đã đạt, phần thưởng của bạn đã được chốt và ô bạn bè có thể dùng lại.', summaryTitle: 'Bạn bè có tiến độ mới', summaryBody: 'Nhiều người bạn đã tiến triển khi bạn không mở ứng dụng. Đây là trạng thái đã xác minh mới nhất.', friendProgress: 'Tiến độ mới nhất' },
  'zh-tw': { dappProgressTitle: '好友進度已更新', dappProgressBody: '好友又完成了一個符合條件的 dApp，並收到對應的 B3TR 獎勵。', rewardReadyTitle: '好友邀請已完成！', rewardReadyBody: '最終驗證已通過，獎勵金額已鎖定，好友名額也可以再次使用。', summaryTitle: '好友有新進度', summaryBody: '你離開期間有多位好友取得進展。這裡顯示各自最新的已驗證狀態。', friendProgress: '最新進度' },
  sv: { dappProgressTitle: 'Vännens framsteg uppdaterades', dappProgressBody: 'Din vän slutförde ytterligare en kvalificerad dApp och fick dess B3TR-belöning.', rewardReadyTitle: 'Väninbjudan är klar!', rewardReadyBody: 'Slutkontrollen är godkänd, din belöning är fastställd och vänplatsen kan användas igen.', summaryTitle: 'Nya framsteg från vänner', summaryBody: 'Flera vänner gjorde framsteg medan du var borta. Här är deras senaste verifierade status.', friendProgress: 'Senaste framsteg' },
  ro: { dappProgressTitle: 'Progresul prietenului a fost actualizat', dappProgressBody: 'Prietenul tău a finalizat încă un dApp eligibil și a primit recompensa B3TR aferentă.', rewardReadyTitle: 'Invitația prietenului este finalizată!', rewardReadyBody: 'Verificarea finală a fost trecută, recompensa este fixată, iar slotul de prieten poate fi folosit din nou.', summaryTitle: 'Progres nou al prietenilor', summaryBody: 'Mai mulți prieteni au progresat cât ai lipsit. Iată cea mai recentă stare verificată.', friendProgress: 'Ultimul progres' },
  ur: { dappProgressTitle: 'دوست کی پیش رفت اپ ڈیٹ ہوگئی', dappProgressBody: 'آپ کے دوست نے ایک اور اہل dApp مکمل کیا اور اس کا B3TR انعام حاصل کیا۔', rewardReadyTitle: 'دوست کی دعوت مکمل ہوگئی!', rewardReadyBody: 'آخری تصدیق کامیاب ہوگئی، آپ کا انعام مقرر ہوگیا اور دوست کا سلاٹ دوبارہ دستیاب ہے۔', summaryTitle: 'دوستوں کی نئی پیش رفت', summaryBody: 'آپ کی غیر موجودگی میں کئی دوست آگے بڑھے۔ یہاں ان کی تازہ ترین تصدیق شدہ حالت ہے۔', friendProgress: 'تازہ ترین پیش رفت' },
  pcm: { dappProgressTitle: 'Your friend don move forward', dappProgressBody: 'Your friend don finish another correct dApp and collect the B3TR reward for am.', rewardReadyTitle: 'Friend invite don complete!', rewardReadyBody: 'Final check don pass, your reward don lock, and the friend slot don free again.', summaryTitle: 'Your friends get new progress', summaryBody: 'Some friends move forward while you no dey. Na their latest verified status be this.', friendProgress: 'Latest progress' },
  arz: { dappProgressTitle: 'تقدم صاحبك اتحدّث', dappProgressBody: 'صاحبك خلّص dApp مؤهل كمان واستلم مكافأة B3TR بتاعته.', rewardReadyTitle: 'دعوة صاحبك اكتملت!', rewardReadyBody: 'التحقق النهائي نجح، مكافأتك اتثبتت ومكان الصديق بقى متاح تاني.', summaryTitle: 'في تقدم جديد لأصحابك', summaryBody: 'أكتر من صاحب اتقدم وإنت بعيد. دي أحدث حالة متحقق منها لكل واحد.', friendProgress: 'آخر تقدم' },
  mr: { dappProgressTitle: 'मित्राची प्रगती अपडेट झाली', dappProgressBody: 'तुमच्या मित्राने आणखी एक पात्र dApp पूर्ण केला आणि त्याचे B3TR रिवॉर्ड मिळवले.', rewardReadyTitle: 'मित्राचे आमंत्रण पूर्ण झाले!', rewardReadyBody: 'अंतिम पडताळणी पूर्ण झाली, तुमचे रिवॉर्ड निश्चित झाले आणि मित्र स्लॉट पुन्हा उपलब्ध आहे.', summaryTitle: 'मित्रांची नवीन प्रगती', summaryBody: 'तुम्ही दूर असताना अनेक मित्र पुढे गेले. ही त्यांची नवीनतम पडताळलेली स्थिती आहे.', friendProgress: 'नवीनतम प्रगती' },
  te: { dappProgressTitle: 'స్నేహితుడి పురోగతి అప్‌డేట్ అయింది', dappProgressBody: 'మీ స్నేహితుడు మరో అర్హమైన dApp పూర్తి చేసి దాని B3TR రివార్డ్ పొందాడు.', rewardReadyTitle: 'స్నేహితుడి ఆహ్వానం పూర్తైంది!', rewardReadyBody: 'తుది ధృవీకరణ పూర్తైంది, మీ రివార్డ్ స్థిరపడింది మరియు ఫ్రెండ్ స్లాట్ మళ్లీ అందుబాటులో ఉంది.', summaryTitle: 'స్నేహితుల కొత్త పురోగతి', summaryBody: 'మీరు దూరంగా ఉన్నప్పుడు పలువురు స్నేహితులు ముందుకు వెళ్లారు. ఇవి వారి తాజా ధృవీకరించిన స్థితులు.', friendProgress: 'తాజా పురోగతి' },
  sw: { dappProgressTitle: 'Maendeleo ya rafiki yamesasishwa', dappProgressBody: 'Rafiki yako amekamilisha dApp nyingine inayokubalika na kupokea zawadi yake ya B3TR.', rewardReadyTitle: 'Mwaliko wa rafiki umekamilika!', rewardReadyBody: 'Uthibitishaji wa mwisho umepita, zawadi yako imewekwa na nafasi ya rafiki inaweza kutumika tena.', summaryTitle: 'Maendeleo mapya ya marafiki', summaryBody: 'Marafiki kadhaa walisonga mbele ulipokuwa mbali. Hii ndiyo hali yao ya hivi karibuni iliyothibitishwa.', friendProgress: 'Maendeleo ya hivi karibuni' },
  ha: { dappProgressTitle: 'Ci gaban aboki ya sabunta', dappProgressBody: 'Abokinka ya kammala wani dApp da ya cancanta kuma ya karɓi ladan B3TR ɗinsa.', rewardReadyTitle: 'Gayyatar aboki ta kammala!', rewardReadyBody: 'Tabbatarwar ƙarshe ta wuce, an kulle ladan ka kuma gurbin aboki ya sake samuwa.', summaryTitle: 'Sabon ci gaban abokai', summaryBody: 'Abokai da dama sun ci gaba yayin da ba ka nan. Ga sabon matsayin su da aka tabbatar.', friendProgress: 'Sabon ci gaba' },
  el: { dappProgressTitle: 'Η πρόοδος του φίλου ενημερώθηκε', dappProgressBody: 'Ο φίλος σου ολοκλήρωσε ακόμη ένα επιλέξιμο dApp και έλαβε την ανταμοιβή B3TR.', rewardReadyTitle: 'Η πρόσκληση φίλου ολοκληρώθηκε!', rewardReadyBody: 'Ο τελικός έλεγχος πέρασε, η ανταμοιβή σου οριστικοποιήθηκε και η θέση φίλου είναι ξανά διαθέσιμη.', summaryTitle: 'Νέα πρόοδος φίλων', summaryBody: 'Αρκετοί φίλοι προχώρησαν όσο έλειπες. Εδώ είναι η τελευταία επαληθευμένη κατάστασή τους.', friendProgress: 'Τελευταία πρόοδος' },
};