import type { SupportedLocale } from './locales';

export type ProgressClaimCopy = {
  inviteFriend: string;
  sharePermanentLink: string;
  currentStep: string;
  finalCheck: string;
  rewardsTitle: string;
  rewardAvailable: string;
  fixedReward: string;
  claimReward: string;
  claiming: string;
  claimQueued: string;
  claimFailed: string;
  rewardsCount: (count: number) => string;
};

const withCount = (label: string) => (count: number) => `${label} ${count}`;

export const PROGRESS_CLAIM_COPY: Record<SupportedLocale, ProgressClaimCopy> = {
  en: { inviteFriend: 'Invite a friend', sharePermanentLink: 'Share permanent invite link', currentStep: 'Current step', finalCheck: 'Final verification', rewardsTitle: 'Rewards to claim', rewardAvailable: 'Reward ready', fixedReward: 'Fixed reward', claimReward: 'Claim reward', claiming: 'Requesting…', claimQueued: 'Payout requested', claimFailed: 'Could not request the reward.', rewardsCount: withCount('Ready') },
  ko: { inviteFriend: '친구 초대하기', sharePermanentLink: '영구 초대 링크 공유', currentStep: '현재 단계', finalCheck: '최종 확인 중', rewardsTitle: '받을 보상', rewardAvailable: '보상 수령 가능', fixedReward: '확정 보상', claimReward: '보상 받기', claiming: '요청 중…', claimQueued: '지급 요청 완료', claimFailed: '보상 요청에 실패했어요.', rewardsCount: (count) => `받을 보상 ${count}건` },
  zh: { inviteFriend: '邀请朋友', sharePermanentLink: '分享永久邀请链接', currentStep: '当前步骤', finalCheck: '最终验证中', rewardsTitle: '可领取奖励', rewardAvailable: '奖励可领取', fixedReward: '已锁定奖励', claimReward: '领取奖励', claiming: '请求中…', claimQueued: '已请求发放', claimFailed: '无法请求奖励。', rewardsCount: (count) => `可领取 ${count} 笔` },
  hi: { inviteFriend: 'दोस्त को आमंत्रित करें', sharePermanentLink: 'स्थायी आमंत्रण लिंक साझा करें', currentStep: 'वर्तमान चरण', finalCheck: 'अंतिम सत्यापन', rewardsTitle: 'लेने योग्य रिवॉर्ड', rewardAvailable: 'रिवॉर्ड तैयार है', fixedReward: 'तय रिवॉर्ड', claimReward: 'रिवॉर्ड लें', claiming: 'अनुरोध हो रहा है…', claimQueued: 'भुगतान अनुरोध भेजा गया', claimFailed: 'रिवॉर्ड का अनुरोध नहीं हो सका।', rewardsCount: (count) => `${count} रिवॉर्ड तैयार` },
  es: { inviteFriend: 'Invitar a un amigo', sharePermanentLink: 'Compartir enlace permanente', currentStep: 'Paso actual', finalCheck: 'Verificación final', rewardsTitle: 'Recompensas por cobrar', rewardAvailable: 'Recompensa disponible', fixedReward: 'Recompensa fijada', claimReward: 'Cobrar recompensa', claiming: 'Solicitando…', claimQueued: 'Pago solicitado', claimFailed: 'No se pudo solicitar la recompensa.', rewardsCount: (count) => `${count} por cobrar` },
  ja: { inviteFriend: '友達を招待', sharePermanentLink: '永久招待リンクを共有', currentStep: '現在のステップ', finalCheck: '最終確認中', rewardsTitle: '受け取れる報酬', rewardAvailable: '報酬を受け取れます', fixedReward: '確定報酬', claimReward: '報酬を受け取る', claiming: 'リクエスト中…', claimQueued: '支払いをリクエスト済み', claimFailed: '報酬をリクエストできませんでした。', rewardsCount: (count) => `${count}件の報酬` },
  it: { inviteFriend: 'Invita un amico', sharePermanentLink: 'Condividi link permanente', currentStep: 'Fase attuale', finalCheck: 'Verifica finale', rewardsTitle: 'Ricompense da riscuotere', rewardAvailable: 'Ricompensa disponibile', fixedReward: 'Ricompensa fissata', claimReward: 'Riscatta ricompensa', claiming: 'Richiesta…', claimQueued: 'Pagamento richiesto', claimFailed: 'Impossibile richiedere la ricompensa.', rewardsCount: (count) => `${count} da riscuotere` },
  tr: { inviteFriend: 'Arkadaşını davet et', sharePermanentLink: 'Kalıcı davet bağlantısını paylaş', currentStep: 'Mevcut adım', finalCheck: 'Son doğrulama', rewardsTitle: 'Alınacak ödüller', rewardAvailable: 'Ödül hazır', fixedReward: 'Sabitlenen ödül', claimReward: 'Ödülü al', claiming: 'İsteniyor…', claimQueued: 'Ödeme istendi', claimFailed: 'Ödül istenemedi.', rewardsCount: (count) => `${count} ödül hazır` },
  nl: { inviteFriend: 'Nodig een vriend uit', sharePermanentLink: 'Deel permanente uitnodigingslink', currentStep: 'Huidige stap', finalCheck: 'Laatste controle', rewardsTitle: 'Te claimen beloningen', rewardAvailable: 'Beloning klaar', fixedReward: 'Vastgezette beloning', claimReward: 'Beloning claimen', claiming: 'Aanvragen…', claimQueued: 'Uitbetaling aangevraagd', claimFailed: 'Beloning kon niet worden aangevraagd.', rewardsCount: (count) => `${count} klaar` },
  de: { inviteFriend: 'Freund einladen', sharePermanentLink: 'Permanenten Einladungslink teilen', currentStep: 'Aktueller Schritt', finalCheck: 'Abschlussprüfung', rewardsTitle: 'Abholbare Belohnungen', rewardAvailable: 'Belohnung verfügbar', fixedReward: 'Festgelegte Belohnung', claimReward: 'Belohnung abholen', claiming: 'Wird angefordert…', claimQueued: 'Auszahlung angefordert', claimFailed: 'Belohnung konnte nicht angefordert werden.', rewardsCount: (count) => `${count} verfügbar` },
  fr: { inviteFriend: 'Inviter un ami', sharePermanentLink: 'Partager le lien permanent', currentStep: 'Étape actuelle', finalCheck: 'Vérification finale', rewardsTitle: 'Récompenses à récupérer', rewardAvailable: 'Récompense disponible', fixedReward: 'Récompense fixée', claimReward: 'Récupérer la récompense', claiming: 'Demande…', claimQueued: 'Paiement demandé', claimFailed: 'Impossible de demander la récompense.', rewardsCount: (count) => `${count} à récupérer` },
  ar: { inviteFriend: 'دعوة صديق', sharePermanentLink: 'مشاركة رابط الدعوة الدائم', currentStep: 'الخطوة الحالية', finalCheck: 'التحقق النهائي', rewardsTitle: 'مكافآت جاهزة للاستلام', rewardAvailable: 'المكافأة جاهزة', fixedReward: 'المكافأة المثبتة', claimReward: 'استلام المكافأة', claiming: 'جارٍ الطلب…', claimQueued: 'تم طلب الدفع', claimFailed: 'تعذر طلب المكافأة.', rewardsCount: (count) => `${count} مكافآت جاهزة` },
  bn: { inviteFriend: 'বন্ধুকে আমন্ত্রণ করুন', sharePermanentLink: 'স্থায়ী আমন্ত্রণ লিংক শেয়ার করুন', currentStep: 'বর্তমান ধাপ', finalCheck: 'চূড়ান্ত যাচাই', rewardsTitle: 'নেওয়ার জন্য রিওয়ার্ড', rewardAvailable: 'রিওয়ার্ড প্রস্তুত', fixedReward: 'নির্ধারিত রিওয়ার্ড', claimReward: 'রিওয়ার্ড নিন', claiming: 'অনুরোধ হচ্ছে…', claimQueued: 'পেমেন্ট অনুরোধ করা হয়েছে', claimFailed: 'রিওয়ার্ড অনুরোধ করা যায়নি।', rewardsCount: (count) => `${count}টি রিওয়ার্ড প্রস্তুত` },
  pt: { inviteFriend: 'Convidar um amigo', sharePermanentLink: 'Compartilhar link permanente', currentStep: 'Etapa atual', finalCheck: 'Verificação final', rewardsTitle: 'Recompensas a receber', rewardAvailable: 'Recompensa disponível', fixedReward: 'Recompensa fixada', claimReward: 'Receber recompensa', claiming: 'Solicitando…', claimQueued: 'Pagamento solicitado', claimFailed: 'Não foi possível solicitar a recompensa.', rewardsCount: (count) => `${count} a receber` },
  ru: { inviteFriend: 'Пригласить друга', sharePermanentLink: 'Поделиться постоянной ссылкой', currentStep: 'Текущий этап', finalCheck: 'Финальная проверка', rewardsTitle: 'Награды к получению', rewardAvailable: 'Награда доступна', fixedReward: 'Зафиксированная награда', claimReward: 'Получить награду', claiming: 'Запрос…', claimQueued: 'Выплата запрошена', claimFailed: 'Не удалось запросить награду.', rewardsCount: (count) => `${count} доступно` },
  id: { inviteFriend: 'Undang teman', sharePermanentLink: 'Bagikan tautan undangan permanen', currentStep: 'Langkah saat ini', finalCheck: 'Verifikasi akhir', rewardsTitle: 'Reward yang bisa diklaim', rewardAvailable: 'Reward siap', fixedReward: 'Reward tetap', claimReward: 'Klaim reward', claiming: 'Meminta…', claimQueued: 'Pembayaran diminta', claimFailed: 'Reward tidak dapat diminta.', rewardsCount: (count) => `${count} siap` },
  vi: { inviteFriend: 'Mời bạn bè', sharePermanentLink: 'Chia sẻ liên kết mời vĩnh viễn', currentStep: 'Bước hiện tại', finalCheck: 'Xác minh cuối', rewardsTitle: 'Phần thưởng có thể nhận', rewardAvailable: 'Phần thưởng đã sẵn sàng', fixedReward: 'Phần thưởng đã chốt', claimReward: 'Nhận phần thưởng', claiming: 'Đang yêu cầu…', claimQueued: 'Đã yêu cầu thanh toán', claimFailed: 'Không thể yêu cầu phần thưởng.', rewardsCount: (count) => `${count} phần thưởng` },
  'zh-tw': { inviteFriend: '邀請朋友', sharePermanentLink: '分享永久邀請連結', currentStep: '目前步驟', finalCheck: '最終驗證中', rewardsTitle: '可領取獎勵', rewardAvailable: '獎勵可領取', fixedReward: '已鎖定獎勵', claimReward: '領取獎勵', claiming: '請求中…', claimQueued: '已請求發放', claimFailed: '無法請求獎勵。', rewardsCount: (count) => `可領取 ${count} 筆` },
  sv: { inviteFriend: 'Bjud in en vän', sharePermanentLink: 'Dela permanent inbjudningslänk', currentStep: 'Nuvarande steg', finalCheck: 'Slutlig verifiering', rewardsTitle: 'Belöningar att hämta', rewardAvailable: 'Belöning klar', fixedReward: 'Fastställd belöning', claimReward: 'Hämta belöning', claiming: 'Begär…', claimQueued: 'Utbetalning begärd', claimFailed: 'Belöningen kunde inte begäras.', rewardsCount: (count) => `${count} klara` },
  ro: { inviteFriend: 'Invită un prieten', sharePermanentLink: 'Distribuie linkul permanent', currentStep: 'Pasul curent', finalCheck: 'Verificare finală', rewardsTitle: 'Recompense de încasat', rewardAvailable: 'Recompensă disponibilă', fixedReward: 'Recompensă fixată', claimReward: 'Încasează recompensa', claiming: 'Se solicită…', claimQueued: 'Plată solicitată', claimFailed: 'Recompensa nu a putut fi solicitată.', rewardsCount: (count) => `${count} disponibile` },
  ur: { inviteFriend: 'دوست کو دعوت دیں', sharePermanentLink: 'مستقل دعوتی لنک شیئر کریں', currentStep: 'موجودہ مرحلہ', finalCheck: 'آخری تصدیق', rewardsTitle: 'وصول کرنے کے انعامات', rewardAvailable: 'انعام تیار ہے', fixedReward: 'مقرر انعام', claimReward: 'انعام وصول کریں', claiming: 'درخواست جاری…', claimQueued: 'ادائیگی کی درخواست ہوگئی', claimFailed: 'انعام کی درخواست نہیں ہو سکی۔', rewardsCount: (count) => `${count} انعام تیار` },
  pcm: { inviteFriend: 'Invite your friend', sharePermanentLink: 'Share permanent invite link', currentStep: 'Where e reach', finalCheck: 'Final check dey go on', rewardsTitle: 'Reward wey you fit collect', rewardAvailable: 'Reward don ready', fixedReward: 'Reward don lock', claimReward: 'Collect reward', claiming: 'E dey request…', claimQueued: 'Payment request don enter', claimFailed: 'Reward request no work.', rewardsCount: (count) => `${count} reward don ready` },
  arz: { inviteFriend: 'اعزم صاحبك', sharePermanentLink: 'شارك لينك الدعوة الدائم', currentStep: 'الخطوة الحالية', finalCheck: 'المراجعة النهائية', rewardsTitle: 'مكافآت جاهزة للاستلام', rewardAvailable: 'المكافأة جاهزة', fixedReward: 'المكافأة اتثبتت', claimReward: 'استلم المكافأة', claiming: 'جاري الطلب…', claimQueued: 'تم طلب الدفع', claimFailed: 'ماقدرناش نطلب المكافأة.', rewardsCount: (count) => `${count} مكافآت جاهزة` },
  mr: { inviteFriend: 'मित्राला आमंत्रित करा', sharePermanentLink: 'कायम आमंत्रण लिंक शेअर करा', currentStep: 'सध्याचा टप्पा', finalCheck: 'अंतिम पडताळणी', rewardsTitle: 'घ्यायची बक्षिसे', rewardAvailable: 'बक्षीस तयार आहे', fixedReward: 'निश्चित बक्षीस', claimReward: 'बक्षीस घ्या', claiming: 'विनंती सुरू…', claimQueued: 'पेमेंटची विनंती झाली', claimFailed: 'बक्षिसाची विनंती करता आली नाही.', rewardsCount: (count) => `${count} बक्षिसे तयार` },
  te: { inviteFriend: 'స్నేహితుడిని ఆహ్వానించండి', sharePermanentLink: 'శాశ్వత ఆహ్వాన లింక్‌ను షేర్ చేయండి', currentStep: 'ప్రస్తుత దశ', finalCheck: 'చివరి ధృవీకరణ', rewardsTitle: 'పొందాల్సిన రివార్డులు', rewardAvailable: 'రివార్డు సిద్ధంగా ఉంది', fixedReward: 'నిర్ధారించిన రివార్డు', claimReward: 'రివార్డు పొందండి', claiming: 'అభ్యర్థిస్తోంది…', claimQueued: 'చెల్లింపు అభ్యర్థించబడింది', claimFailed: 'రివార్డును అభ్యర్థించలేకపోయాం.', rewardsCount: (count) => `${count} రివార్డులు సిద్ధం` },
  sw: { inviteFriend: 'Alika rafiki', sharePermanentLink: 'Shiriki kiungo cha kudumu cha mwaliko', currentStep: 'Hatua ya sasa', finalCheck: 'Uhakiki wa mwisho', rewardsTitle: 'Zawadi za kudai', rewardAvailable: 'Zawadi iko tayari', fixedReward: 'Zawadi iliyothibitishwa', claimReward: 'Dai zawadi', claiming: 'Inaomba…', claimQueued: 'Malipo yameombwa', claimFailed: 'Haikuwezekana kuomba zawadi.', rewardsCount: (count) => `${count} tayari` },
  ha: { inviteFriend: 'Gayyaci aboki', sharePermanentLink: 'Raba mahaɗin gayyata na dindindin', currentStep: 'Mataki na yanzu', finalCheck: 'Tabbatarwa ta ƙarshe', rewardsTitle: 'Ladan da za a karɓa', rewardAvailable: 'Lada ya shirya', fixedReward: 'Ladan da aka kulle', claimReward: 'Karɓi lada', claiming: 'Ana nema…', claimQueued: 'An nemi biya', claimFailed: 'Ba a iya neman ladan ba.', rewardsCount: (count) => `${count} lada sun shirya` },
};
