import { GUIDE_FLOW_COPY } from './guideFlowCopy';
import { HOME_COPY } from './homeCopy';
import {
  SUPPORTED_LOCALES,
  type SupportedLocale,
} from './locales';

type ReferralLinkCopy = {
  badge: string;
  homeTitle: string;
  homeDescription: string;
  linkLabel: string;
  linkHelp: string;
  slotsLabel: string;
  slotAvailable: string;
  slotInProgress: string;
  slotReview: string;
  slotLegacyWaiting: string;
  slotBlockedReleased: string;
  slotsFullTitle: string;
  slotsFullHelp: string;
  retry: string;
  guideInviteDescription: string;
};

export const REFERRAL_LINK_COPY: Record<SupportedLocale, ReferralLinkCopy> = {
  en: { badge: '2 FRIEND SLOTS', homeTitle: 'Your permanent invite link', homeDescription: 'Share the same link anytime. Up to two eligible friends can be in progress at once, and simply opening the link never uses a slot.', linkLabel: 'Permanent invite link', linkHelp: 'This link stays the same after a friend finishes.', slotsLabel: 'Friends in progress', slotAvailable: 'Available · share your link with a friend', slotInProgress: 'In progress · friend is completing missions', slotReview: 'Final check · verifying this friend', slotLegacyWaiting: 'Legacy invite · waiting for this friend', slotBlockedReleased: 'Not approved · this slot is available again', slotsFullTitle: 'Both friend slots are in use', slotsFullHelp: 'Two friends are already in progress with this inviter. This permanent link is still valid, so please try it again later.', retry: 'Try again', guideInviteDescription: 'You have one permanent invite link and two reusable friend slots. Up to two eligible friends can progress at the same time. Opening the link alone never uses a slot; a slot is reserved only after eligibility is verified.' },
  ko: { badge: '친구 슬롯 2개', homeTitle: '내 영구 초대 링크', homeDescription: '항상 같은 링크를 공유하면 돼요. 자격을 충족한 친구는 동시에 최대 2명까지 진행할 수 있고, 링크를 열기만 해서는 슬롯을 사용하지 않아요.', linkLabel: '영구 초대 링크', linkHelp: '친구가 완료해도 이 링크는 그대로 사용할 수 있어요.', slotsLabel: '동시에 진행할 수 있는 친구', slotAvailable: '사용 가능 · 링크를 공유해 친구를 초대하세요', slotInProgress: '진행 중 · 친구가 미션을 수행하고 있어요', slotReview: '최종 확인 · 친구의 참여를 검증하고 있어요', slotLegacyWaiting: '기존 초대 · 이 친구의 참여를 기다리고 있어요', slotBlockedReleased: '승인되지 않음 · 이 슬롯은 다시 사용할 수 있어요', slotsFullTitle: '친구 슬롯 2개가 모두 사용 중이에요', slotsFullHelp: '현재 이 초대한 사람의 친구 2명이 진행 중이에요. 영구 링크는 계속 유효하니 나중에 같은 링크로 다시 시도해 주세요.', retry: '다시 확인', guideInviteDescription: '영구 초대 링크 1개와 재사용 가능한 친구 슬롯 2개가 있어요. 자격을 충족한 친구는 동시에 최대 2명까지 진행할 수 있어요. 링크를 열기만 해서는 슬롯을 사용하지 않고, 자격 확인을 통과한 뒤에만 슬롯이 배정돼요.' },
  zh: { badge: '2 个好友名额', homeTitle: '你的永久邀请链接', homeDescription: '随时分享同一个链接。最多可有两位符合资格的好友同时进行任务，仅打开链接不会占用名额。', linkLabel: '永久邀请链接', linkHelp: '好友完成后，这个链接仍可继续使用。', slotsLabel: '正在进行的好友', slotAvailable: '可用 · 分享链接邀请好友', slotInProgress: '进行中 · 好友正在完成任务', slotReview: '最终检查 · 正在验证好友', slotLegacyWaiting: '旧版邀请 · 等待好友加入', slotBlockedReleased: '未获批准 · 此名额已重新可用', slotsFullTitle: '两个好友名额都在使用中', slotsFullHelp: '目前已有两位好友正在进行。永久链接仍然有效，请稍后用同一链接重试。', retry: '重试', guideInviteDescription: '你有一个永久邀请链接和两个可重复使用的好友名额。最多两位符合资格的好友可同时进行。仅打开链接不会占用名额，只有通过资格验证后才会分配名额。' },
  hi: { badge: '2 मित्र स्लॉट', homeTitle: 'आपका स्थायी आमंत्रण लिंक', homeDescription: 'हर बार यही लिंक साझा करें। एक समय में अधिकतम दो पात्र मित्र आगे बढ़ सकते हैं, और केवल लिंक खोलने से कोई स्लॉट इस्तेमाल नहीं होता।', linkLabel: 'स्थायी आमंत्रण लिंक', linkHelp: 'मित्र के पूरा करने के बाद भी यही लिंक काम करता रहेगा।', slotsLabel: 'प्रगति कर रहे मित्र', slotAvailable: 'उपलब्ध · किसी मित्र से लिंक साझा करें', slotInProgress: 'प्रगति में · मित्र मिशन पूरा कर रहा है', slotReview: 'अंतिम जाँच · मित्र का सत्यापन हो रहा है', slotLegacyWaiting: 'पुराना आमंत्रण · मित्र का इंतज़ार है', slotBlockedReleased: 'मंज़ूर नहीं · यह स्लॉट फिर उपलब्ध है', slotsFullTitle: 'दोनों मित्र स्लॉट उपयोग में हैं', slotsFullHelp: 'इस समय दो मित्र प्रगति में हैं। स्थायी लिंक वैध है, इसलिए बाद में इसी लिंक से फिर कोशिश करें।', retry: 'फिर कोशिश करें', guideInviteDescription: 'आपके पास एक स्थायी आमंत्रण लिंक और दो दोबारा इस्तेमाल होने वाले मित्र स्लॉट हैं। एक समय में अधिकतम दो पात्र मित्र आगे बढ़ सकते हैं। लिंक खोलने भर से स्लॉट नहीं लगता; पात्रता सत्यापित होने के बाद ही स्लॉट आरक्षित होता है।' },
  es: { badge: '2 CUPOS PARA AMIGOS', homeTitle: 'Tu enlace de invitación permanente', homeDescription: 'Comparte siempre el mismo enlace. Hasta dos amigos elegibles pueden avanzar a la vez y abrir el enlace por sí solo no ocupa ningún cupo.', linkLabel: 'Enlace de invitación permanente', linkHelp: 'El enlace sigue siendo el mismo cuando un amigo termina.', slotsLabel: 'Amigos en curso', slotAvailable: 'Disponible · comparte el enlace con un amigo', slotInProgress: 'En curso · tu amigo está completando las misiones', slotReview: 'Comprobación final · verificando a este amigo', slotLegacyWaiting: 'Invitación anterior · esperando a este amigo', slotBlockedReleased: 'No aprobado · este cupo vuelve a estar disponible', slotsFullTitle: 'Los dos cupos están ocupados', slotsFullHelp: 'Ya hay dos amigos en curso. El enlace permanente sigue siendo válido; vuelve a intentarlo más tarde con el mismo enlace.', retry: 'Intentar de nuevo', guideInviteDescription: 'Tienes un enlace de invitación permanente y dos cupos reutilizables. Hasta dos amigos elegibles pueden avanzar al mismo tiempo. Abrir el enlace no ocupa un cupo; solo se reserva después de verificar la elegibilidad.' },
  ja: { badge: '友だち枠 2件', homeTitle: 'あなた専用の永久招待リンク', homeDescription: 'いつでも同じリンクを共有できます。対象となる友だちは同時に最大2人まで進行でき、リンクを開くだけでは枠を使用しません。', linkLabel: '永久招待リンク', linkHelp: '友だちが完了した後も同じリンクを使えます。', slotsLabel: '進行中の友だち', slotAvailable: '利用可能 · 友だちにリンクを共有してください', slotInProgress: '進行中 · 友だちがミッションに取り組んでいます', slotReview: '最終確認 · 友だちを検証しています', slotLegacyWaiting: '旧招待 · 友だちの参加待ちです', slotBlockedReleased: '未承認 · この枠は再び利用できます', slotsFullTitle: '2つの友だち枠が使用中です', slotsFullHelp: '現在2人の友だちが進行中です。永久リンクは有効なままなので、後で同じリンクからもう一度お試しください。', retry: 'もう一度確認', guideInviteDescription: '永久招待リンクは1つ、再利用できる友だち枠は2つです。対象となる友だちは同時に最大2人まで進行できます。リンクを開くだけでは枠は使われず、参加資格の確認後にのみ枠が確保されます。' },
  it: { badge: '2 POSTI AMICI', homeTitle: 'Il tuo link di invito permanente', homeDescription: 'Condividi sempre lo stesso link. Fino a due amici idonei possono procedere contemporaneamente e la sola apertura del link non occupa un posto.', linkLabel: 'Link di invito permanente', linkHelp: 'Il link resta lo stesso anche dopo che un amico termina.', slotsLabel: 'Amici in corso', slotAvailable: 'Disponibile · condividi il link con un amico', slotInProgress: 'In corso · l’amico sta completando le missioni', slotReview: 'Controllo finale · verifica dell’amico in corso', slotLegacyWaiting: 'Invito precedente · in attesa dell’amico', slotBlockedReleased: 'Non approvato · il posto è di nuovo disponibile', slotsFullTitle: 'Entrambi i posti sono occupati', slotsFullHelp: 'Due amici sono già in corso. Il link permanente resta valido: riprova più tardi con lo stesso link.', retry: 'Riprova', guideInviteDescription: 'Hai un link di invito permanente e due posti riutilizzabili. Fino a due amici idonei possono procedere insieme. Aprire il link non occupa un posto; il posto viene riservato solo dopo la verifica dell’idoneità.' },
  tr: { badge: '2 ARKADAŞ YUVASI', homeTitle: 'Kalıcı davet bağlantın', homeDescription: 'Her zaman aynı bağlantıyı paylaş. Aynı anda en fazla iki uygun arkadaş ilerleyebilir; bağlantıyı yalnızca açmak bir yuva kullanmaz.', linkLabel: 'Kalıcı davet bağlantısı', linkHelp: 'Bir arkadaş tamamladıktan sonra da aynı bağlantı kullanılabilir.', slotsLabel: 'Devam eden arkadaşlar', slotAvailable: 'Uygun · bağlantıyı bir arkadaşınla paylaş', slotInProgress: 'Devam ediyor · arkadaş görevleri tamamlıyor', slotReview: 'Son kontrol · arkadaş doğrulanıyor', slotLegacyWaiting: 'Eski davet · arkadaş bekleniyor', slotBlockedReleased: 'Onaylanmadı · bu yuva yeniden kullanılabilir', slotsFullTitle: 'İki arkadaş yuvası da kullanımda', slotsFullHelp: 'Şu anda iki arkadaş ilerliyor. Kalıcı bağlantı geçerli; daha sonra aynı bağlantıyla tekrar dene.', retry: 'Tekrar dene', guideInviteDescription: 'Bir kalıcı davet bağlantın ve yeniden kullanılabilen iki arkadaş yuvan var. Aynı anda en fazla iki uygun arkadaş ilerleyebilir. Bağlantıyı açmak yuva kullanmaz; yuva yalnızca uygunluk doğrulandıktan sonra ayrılır.' },
  nl: { badge: '2 VRIENDPLEKKEN', homeTitle: 'Je permanente uitnodigingslink', homeDescription: 'Deel steeds dezelfde link. Maximaal twee geschikte vrienden kunnen tegelijk bezig zijn; alleen de link openen gebruikt geen plek.', linkLabel: 'Permanente uitnodigingslink', linkHelp: 'De link blijft hetzelfde nadat een vriend klaar is.', slotsLabel: 'Vrienden in uitvoering', slotAvailable: 'Beschikbaar · deel de link met een vriend', slotInProgress: 'Bezig · je vriend voltooit de missies', slotReview: 'Laatste controle · vriend wordt geverifieerd', slotLegacyWaiting: 'Oude uitnodiging · wachten op deze vriend', slotBlockedReleased: 'Niet goedgekeurd · deze plek is weer beschikbaar', slotsFullTitle: 'Beide vriendplekken zijn bezet', slotsFullHelp: 'Er zijn al twee vrienden bezig. De permanente link blijft geldig; probeer het later opnieuw met dezelfde link.', retry: 'Opnieuw proberen', guideInviteDescription: 'Je hebt één permanente uitnodigingslink en twee herbruikbare vriendplekken. Maximaal twee geschikte vrienden kunnen tegelijk doorgaan. Alleen de link openen gebruikt geen plek; die wordt pas gereserveerd na de geschiktheidscontrole.' },
  de: { badge: '2 FREUND-PLÄTZE', homeTitle: 'Dein permanenter Einladungslink', homeDescription: 'Teile immer denselben Link. Bis zu zwei berechtigte Freunde können gleichzeitig teilnehmen; das bloße Öffnen des Links belegt keinen Platz.', linkLabel: 'Permanenter Einladungslink', linkHelp: 'Der Link bleibt auch nach dem Abschluss eines Freundes gleich.', slotsLabel: 'Freunde in Bearbeitung', slotAvailable: 'Verfügbar · teile den Link mit einem Freund', slotInProgress: 'In Bearbeitung · dein Freund erledigt die Missionen', slotReview: 'Letzte Prüfung · Freund wird verifiziert', slotLegacyWaiting: 'Alte Einladung · wartet auf diesen Freund', slotBlockedReleased: 'Nicht genehmigt · dieser Platz ist wieder frei', slotsFullTitle: 'Beide Freund-Plätze sind belegt', slotsFullHelp: 'Zwei Freunde sind bereits in Bearbeitung. Der permanente Link bleibt gültig; versuche es später mit demselben Link erneut.', retry: 'Erneut versuchen', guideInviteDescription: 'Du hast einen permanenten Einladungslink und zwei wiederverwendbare Freund-Plätze. Bis zu zwei berechtigte Freunde können gleichzeitig teilnehmen. Das Öffnen des Links belegt keinen Platz; er wird erst nach der Berechtigungsprüfung reserviert.' },
  fr: { badge: '2 PLACES AMIS', homeTitle: 'Votre lien d’invitation permanent', homeDescription: 'Partagez toujours le même lien. Jusqu’à deux amis éligibles peuvent avancer en même temps et le simple fait d’ouvrir le lien n’occupe aucune place.', linkLabel: 'Lien d’invitation permanent', linkHelp: 'Le lien reste identique lorsqu’un ami termine.', slotsLabel: 'Amis en cours', slotAvailable: 'Disponible · partagez le lien avec un ami', slotInProgress: 'En cours · votre ami réalise les missions', slotReview: 'Vérification finale · ami en cours de validation', slotLegacyWaiting: 'Ancienne invitation · en attente de cet ami', slotBlockedReleased: 'Non approuvé · cette place est de nouveau disponible', slotsFullTitle: 'Les deux places sont utilisées', slotsFullHelp: 'Deux amis sont déjà en cours. Le lien permanent reste valide ; réessayez plus tard avec le même lien.', retry: 'Réessayer', guideInviteDescription: 'Vous disposez d’un lien d’invitation permanent et de deux places réutilisables. Jusqu’à deux amis éligibles peuvent avancer simultanément. Ouvrir le lien ne prend pas de place ; elle n’est réservée qu’après validation de l’éligibilité.' },
  ar: { badge: 'مكانان للأصدقاء', homeTitle: 'رابط دعوتك الدائم', homeDescription: 'شارك الرابط نفسه في كل مرة. يمكن لصديقين مؤهلين كحد أقصى التقدم في الوقت نفسه، ومجرد فتح الرابط لا يشغل أي مكان.', linkLabel: 'رابط الدعوة الدائم', linkHelp: 'يبقى الرابط نفسه صالحًا بعد إكمال الصديق.', slotsLabel: 'الأصدقاء قيد التقدم', slotAvailable: 'متاح · شارك الرابط مع صديق', slotInProgress: 'قيد التقدم · الصديق يكمل المهام', slotReview: 'الفحص النهائي · جارٍ التحقق من الصديق', slotLegacyWaiting: 'دعوة سابقة · في انتظار الصديق', slotBlockedReleased: 'غير معتمد · المكان متاح من جديد', slotsFullTitle: 'المكانان مستخدمان حاليًا', slotsFullHelp: 'هناك صديقان قيد التقدم الآن. الرابط الدائم ما زال صالحًا، لذا حاول مرة أخرى لاحقًا باستخدام الرابط نفسه.', retry: 'حاول مرة أخرى', guideInviteDescription: 'لديك رابط دعوة دائم واحد ومكانان قابلان لإعادة الاستخدام. يمكن لصديقين مؤهلين كحد أقصى التقدم معًا. فتح الرابط وحده لا يشغل مكانًا؛ يتم حجزه فقط بعد التحقق من الأهلية.' },
  bn: { badge: 'বন্ধুর জন্য ২টি স্লট', homeTitle: 'আপনার স্থায়ী আমন্ত্রণ লিংক', homeDescription: 'সব সময় একই লিংক শেয়ার করুন। সর্বোচ্চ দুইজন যোগ্য বন্ধু একই সময়ে এগোতে পারবেন, আর শুধু লিংক খুললে কোনো স্লট ব্যবহৃত হবে না।', linkLabel: 'স্থায়ী আমন্ত্রণ লিংক', linkHelp: 'একজন বন্ধু শেষ করলেও এই লিংক একই থাকবে।', slotsLabel: 'চলমান বন্ধু', slotAvailable: 'খালি · বন্ধুর সঙ্গে লিংক শেয়ার করুন', slotInProgress: 'চলমান · বন্ধু মিশন শেষ করছে', slotReview: 'চূড়ান্ত যাচাই · বন্ধুকে যাচাই করা হচ্ছে', slotLegacyWaiting: 'পুরোনো আমন্ত্রণ · বন্ধুর অপেক্ষায়', slotBlockedReleased: 'অনুমোদিত নয় · স্লটটি আবার খালি', slotsFullTitle: 'দুটি স্লটই ব্যবহার হচ্ছে', slotsFullHelp: 'এখন দুইজন বন্ধু চলমান আছে। স্থায়ী লিংকটি বৈধ থাকবে, তাই পরে একই লিংক দিয়ে আবার চেষ্টা করুন।', retry: 'আবার চেষ্টা করুন', guideInviteDescription: 'আপনার একটি স্থায়ী আমন্ত্রণ লিংক ও দুটি পুনর্ব্যবহারযোগ্য বন্ধু স্লট আছে। সর্বোচ্চ দুইজন যোগ্য বন্ধু একই সময়ে এগোতে পারবেন। শুধু লিংক খুললে স্লট লাগে না; যোগ্যতা যাচাইয়ের পরেই স্লট সংরক্ষিত হয়।' },
  pt: { badge: '2 VAGAS PARA AMIGOS', homeTitle: 'Seu link de convite permanente', homeDescription: 'Compartilhe sempre o mesmo link. Até dois amigos elegíveis podem avançar ao mesmo tempo, e apenas abrir o link não ocupa nenhuma vaga.', linkLabel: 'Link de convite permanente', linkHelp: 'O link continua o mesmo depois que um amigo conclui.', slotsLabel: 'Amigos em andamento', slotAvailable: 'Disponível · compartilhe o link com um amigo', slotInProgress: 'Em andamento · o amigo está concluindo as missões', slotReview: 'Verificação final · amigo sendo validado', slotLegacyWaiting: 'Convite antigo · aguardando este amigo', slotBlockedReleased: 'Não aprovado · a vaga está disponível novamente', slotsFullTitle: 'As duas vagas estão em uso', slotsFullHelp: 'Dois amigos já estão em andamento. O link permanente continua válido; tente novamente mais tarde com o mesmo link.', retry: 'Tentar novamente', guideInviteDescription: 'Você tem um link de convite permanente e duas vagas reutilizáveis. Até dois amigos elegíveis podem avançar ao mesmo tempo. Abrir o link não ocupa vaga; ela só é reservada após a verificação de elegibilidade.' },
  ru: { badge: '2 МЕСТА ДЛЯ ДРУЗЕЙ', homeTitle: 'Ваша постоянная ссылка-приглашение', homeDescription: 'Делитесь одной и той же ссылкой. Одновременно могут участвовать до двух подходящих друзей, а простое открытие ссылки не занимает место.', linkLabel: 'Постоянная ссылка-приглашение', linkHelp: 'После завершения одним другом ссылка остаётся прежней.', slotsLabel: 'Друзья в процессе', slotAvailable: 'Свободно · поделитесь ссылкой с другом', slotInProgress: 'В процессе · друг выполняет задания', slotReview: 'Финальная проверка · друг проходит проверку', slotLegacyWaiting: 'Старое приглашение · ожидание друга', slotBlockedReleased: 'Не одобрено · место снова свободно', slotsFullTitle: 'Оба места заняты', slotsFullHelp: 'Сейчас уже участвуют два друга. Постоянная ссылка остаётся действительной — попробуйте позже по той же ссылке.', retry: 'Попробовать снова', guideInviteDescription: 'У вас одна постоянная ссылка и два многоразовых места для друзей. Одновременно могут участвовать до двух подходящих друзей. Открытие ссылки не занимает место — оно резервируется только после проверки права на участие.' },
  id: { badge: '2 SLOT TEMAN', homeTitle: 'Tautan undangan permanenmu', homeDescription: 'Bagikan tautan yang sama kapan saja. Maksimal dua teman yang memenuhi syarat dapat berjalan bersamaan, dan sekadar membuka tautan tidak memakai slot.', linkLabel: 'Tautan undangan permanen', linkHelp: 'Tautan tetap sama setelah seorang teman selesai.', slotsLabel: 'Teman yang sedang berjalan', slotAvailable: 'Tersedia · bagikan tautan ke teman', slotInProgress: 'Berjalan · teman sedang menyelesaikan misi', slotReview: 'Pemeriksaan akhir · teman sedang diverifikasi', slotLegacyWaiting: 'Undangan lama · menunggu teman ini', slotBlockedReleased: 'Tidak disetujui · slot tersedia lagi', slotsFullTitle: 'Kedua slot teman sedang digunakan', slotsFullHelp: 'Dua teman sedang berjalan. Tautan permanen tetap berlaku, jadi coba lagi nanti dengan tautan yang sama.', retry: 'Coba lagi', guideInviteDescription: 'Kamu memiliki satu tautan undangan permanen dan dua slot teman yang dapat digunakan kembali. Maksimal dua teman yang memenuhi syarat dapat berjalan bersamaan. Membuka tautan saja tidak memakai slot; slot baru dipesan setelah kelayakan terverifikasi.' },
  vi: { badge: '2 SUẤT BẠN BÈ', homeTitle: 'Liên kết mời vĩnh viễn của bạn', homeDescription: 'Luôn chia sẻ cùng một liên kết. Tối đa hai người bạn đủ điều kiện có thể cùng tham gia, và chỉ mở liên kết sẽ không chiếm suất.', linkLabel: 'Liên kết mời vĩnh viễn', linkHelp: 'Liên kết vẫn giữ nguyên sau khi một người bạn hoàn tất.', slotsLabel: 'Bạn bè đang tham gia', slotAvailable: 'Còn trống · chia sẻ liên kết với một người bạn', slotInProgress: 'Đang thực hiện · bạn của bạn đang hoàn thành nhiệm vụ', slotReview: 'Kiểm tra cuối · đang xác minh người bạn này', slotLegacyWaiting: 'Lời mời cũ · đang chờ người bạn này', slotBlockedReleased: 'Không được duyệt · suất này đã trống lại', slotsFullTitle: 'Cả hai suất đều đang được sử dụng', slotsFullHelp: 'Hiện đã có hai người bạn đang tham gia. Liên kết vĩnh viễn vẫn còn hiệu lực; hãy thử lại sau bằng chính liên kết này.', retry: 'Thử lại', guideInviteDescription: 'Bạn có một liên kết mời vĩnh viễn và hai suất bạn bè có thể tái sử dụng. Tối đa hai người bạn đủ điều kiện có thể cùng tham gia. Chỉ mở liên kết không chiếm suất; suất chỉ được giữ sau khi xác minh đủ điều kiện.' },
  'zh-tw': { badge: '2 個好友名額', homeTitle: '你的永久邀請連結', homeDescription: '隨時分享同一個連結。最多可有兩位符合資格的好友同時進行，單純開啟連結不會占用名額。', linkLabel: '永久邀請連結', linkHelp: '好友完成後，這個連結仍可繼續使用。', slotsLabel: '進行中的好友', slotAvailable: '可用 · 分享連結邀請好友', slotInProgress: '進行中 · 好友正在完成任務', slotReview: '最終檢查 · 正在驗證好友', slotLegacyWaiting: '舊版邀請 · 等待好友加入', slotBlockedReleased: '未通過 · 此名額已重新可用', slotsFullTitle: '兩個好友名額都在使用中', slotsFullHelp: '目前已有兩位好友正在進行。永久連結仍然有效，請稍後使用同一個連結再試一次。', retry: '再試一次', guideInviteDescription: '你有一個永久邀請連結和兩個可重複使用的好友名額。最多兩位符合資格的好友可以同時進行。只開啟連結不會占用名額，通過資格驗證後才會保留名額。' },
  sv: { badge: '2 VÄNPLATSER', homeTitle: 'Din permanenta inbjudningslänk', homeDescription: 'Dela samma länk varje gång. Upp till två behöriga vänner kan vara igång samtidigt, och att bara öppna länken använder ingen plats.', linkLabel: 'Permanent inbjudningslänk', linkHelp: 'Länken är densamma även när en vän är klar.', slotsLabel: 'Vänner som pågår', slotAvailable: 'Tillgänglig · dela länken med en vän', slotInProgress: 'Pågår · vännen slutför uppdragen', slotReview: 'Slutkontroll · vännen verifieras', slotLegacyWaiting: 'Äldre inbjudan · väntar på vännen', slotBlockedReleased: 'Inte godkänd · platsen är ledig igen', slotsFullTitle: 'Båda vänplatserna används', slotsFullHelp: 'Två vänner är redan igång. Den permanenta länken gäller fortfarande; försök igen senare med samma länk.', retry: 'Försök igen', guideInviteDescription: 'Du har en permanent inbjudningslänk och två återanvändbara vänplatser. Upp till två behöriga vänner kan delta samtidigt. Att öppna länken använder ingen plats; den reserveras först efter behörighetskontrollen.' },
  ro: { badge: '2 LOCURI PENTRU PRIETENI', homeTitle: 'Linkul tău permanent de invitație', homeDescription: 'Distribuie mereu același link. Până la doi prieteni eligibili pot participa simultan, iar simpla deschidere a linkului nu ocupă un loc.', linkLabel: 'Link permanent de invitație', linkHelp: 'Linkul rămâne același după ce un prieten finalizează.', slotsLabel: 'Prieteni în curs', slotAvailable: 'Disponibil · distribuie linkul unui prieten', slotInProgress: 'În curs · prietenul finalizează misiunile', slotReview: 'Verificare finală · prietenul este verificat', slotLegacyWaiting: 'Invitație veche · se așteaptă acest prieten', slotBlockedReleased: 'Neaprobat · locul este din nou disponibil', slotsFullTitle: 'Ambele locuri sunt ocupate', slotsFullHelp: 'Doi prieteni sunt deja în curs. Linkul permanent rămâne valabil; încearcă din nou mai târziu cu același link.', retry: 'Încearcă din nou', guideInviteDescription: 'Ai un link permanent de invitație și două locuri reutilizabile. Până la doi prieteni eligibili pot participa simultan. Deschiderea linkului nu ocupă un loc; acesta se rezervă doar după verificarea eligibilității.' },
  ur: { badge: 'دو دوست سلاٹس', homeTitle: 'آپ کا مستقل دعوتی لنک', homeDescription: 'ہر بار یہی لنک شیئر کریں۔ ایک وقت میں زیادہ سے زیادہ دو اہل دوست آگے بڑھ سکتے ہیں، اور صرف لنک کھولنے سے کوئی سلاٹ استعمال نہیں ہوتا۔', linkLabel: 'مستقل دعوتی لنک', linkHelp: 'دوست کے مکمل کرنے کے بعد بھی یہی لنک کام کرتا رہے گا۔', slotsLabel: 'جاری دوست', slotAvailable: 'دستیاب · دوست کے ساتھ لنک شیئر کریں', slotInProgress: 'جاری · دوست مشن مکمل کر رہا ہے', slotReview: 'آخری جانچ · دوست کی تصدیق ہو رہی ہے', slotLegacyWaiting: 'پرانا دعوت نامہ · دوست کا انتظار ہے', slotBlockedReleased: 'منظور نہیں · سلاٹ دوبارہ دستیاب ہے', slotsFullTitle: 'دونوں دوست سلاٹس استعمال میں ہیں', slotsFullHelp: 'اس وقت دو دوست آگے بڑھ رہے ہیں۔ مستقل لنک بدستور درست ہے، اس لیے بعد میں اسی لنک سے دوبارہ کوشش کریں۔', retry: 'دوبارہ کوشش کریں', guideInviteDescription: 'آپ کے پاس ایک مستقل دعوتی لنک اور دو دوبارہ استعمال ہونے والے دوست سلاٹس ہیں۔ ایک وقت میں زیادہ سے زیادہ دو اہل دوست آگے بڑھ سکتے ہیں۔ صرف لنک کھولنے سے سلاٹ استعمال نہیں ہوتا؛ اہلیت کی تصدیق کے بعد ہی سلاٹ محفوظ ہوتا ہے۔' },
  pcm: { badge: '2 FRIEND SLOT', homeTitle: 'Your permanent invite link', homeDescription: 'Na the same link you go dey share anytime. Up to two friends wey qualify fit dey do mission together, and just opening the link no go use any slot.', linkLabel: 'Permanent invite link', linkHelp: 'The link no go change after one friend finish.', slotsLabel: 'Friends wey dey progress', slotAvailable: 'E dey free · share the link give your friend', slotInProgress: 'E dey go · your friend dey complete missions', slotReview: 'Final check · dem dey verify your friend', slotLegacyWaiting: 'Old invite · dey wait for this friend', slotBlockedReleased: 'Dem no approve am · the slot don free again', slotsFullTitle: 'The two friend slots dey in use', slotsFullHelp: 'Two friends already dey progress now. The permanent link still valid, so try the same link again later.', retry: 'Try again', guideInviteDescription: 'You get one permanent invite link and two friend slots wey you fit reuse. Up to two friends wey qualify fit progress together. Just opening the link no use slot; na after eligibility check pass dem go reserve slot.' },
  arz: { badge: 'مكانين للصحاب', homeTitle: 'لينك دعوتك الدائم', homeDescription: 'شارك نفس اللينك كل مرة. ممكن لحد صاحبين مؤهلين يكملوا في نفس الوقت، ومجرد فتح اللينك مش بياخد مكان.', linkLabel: 'لينك الدعوة الدائم', linkHelp: 'اللينك بيفضل هو نفسه بعد ما صاحبك يخلص.', slotsLabel: 'الصحاب اللي شغالين', slotAvailable: 'متاح · شارك اللينك مع صاحبك', slotInProgress: 'شغال · صاحبك بيكمّل المهام', slotReview: 'الفحص الأخير · بنراجع صاحبك', slotLegacyWaiting: 'دعوة قديمة · مستنيين صاحبك', slotBlockedReleased: 'ما اتوافقش عليه · المكان متاح تاني', slotsFullTitle: 'المكانين مستخدمين دلوقتي', slotsFullHelp: 'في صاحبين شغالين دلوقتي. اللينك الدائم لسه صالح، جرّب بنفس اللينك بعدين.', retry: 'جرّب تاني', guideInviteDescription: 'عندك لينك دعوة دائم واحد ومكانين تقدر تستخدمهم تاني. ممكن لحد صاحبين مؤهلين يكملوا مع بعض. فتح اللينك لوحده مش بياخد مكان؛ المكان بيتحجز بس بعد ما الأهلية تتأكد.' },
  mr: { badge: 'मित्रांसाठी २ स्लॉट', homeTitle: 'तुमची कायमची आमंत्रण लिंक', homeDescription: 'नेहमी हीच लिंक शेअर करा. एकावेळी जास्तीत जास्त दोन पात्र मित्र पुढे जाऊ शकतात आणि फक्त लिंक उघडल्याने स्लॉट वापरला जात नाही.', linkLabel: 'कायमची आमंत्रण लिंक', linkHelp: 'मित्र पूर्ण केल्यानंतरही हीच लिंक वापरता येते.', slotsLabel: 'प्रगतीतील मित्र', slotAvailable: 'उपलब्ध · मित्रासोबत लिंक शेअर करा', slotInProgress: 'प्रगतीत · मित्र मिशन पूर्ण करत आहे', slotReview: 'अंतिम तपासणी · मित्राची पडताळणी सुरू आहे', slotLegacyWaiting: 'जुने आमंत्रण · मित्राची वाट पाहत आहे', slotBlockedReleased: 'मंजूर नाही · स्लॉट पुन्हा उपलब्ध आहे', slotsFullTitle: 'दोन्ही मित्र स्लॉट वापरात आहेत', slotsFullHelp: 'सध्या दोन मित्र प्रगतीत आहेत. कायमची लिंक वैध आहे; नंतर याच लिंकने पुन्हा प्रयत्न करा.', retry: 'पुन्हा प्रयत्न करा', guideInviteDescription: 'तुमच्याकडे एक कायमची आमंत्रण लिंक आणि पुन्हा वापरता येणारे दोन मित्र स्लॉट आहेत. एकावेळी जास्तीत जास्त दोन पात्र मित्र पुढे जाऊ शकतात. लिंक उघडल्याने स्लॉट वापरला जात नाही; पात्रता पडताळल्यानंतरच स्लॉट राखीव होतो.' },
  te: { badge: 'స్నేహితుల కోసం 2 స్లాట్‌లు', homeTitle: 'మీ శాశ్వత ఆహ్వాన లింక్', homeDescription: 'ఎప్పుడైనా ఇదే లింక్‌ను పంచుకోండి. అర్హత ఉన్న గరిష్టంగా ఇద్దరు స్నేహితులు ఒకేసారి కొనసాగవచ్చు; లింక్‌ను కేవలం తెరవడం వల్ల స్లాట్ ఉపయోగించబడదు.', linkLabel: 'శాశ్వత ఆహ్వాన లింక్', linkHelp: 'ఒక స్నేహితుడు పూర్తి చేసిన తర్వాత కూడా ఇదే లింక్ పనిచేస్తుంది.', slotsLabel: 'కొనసాగుతున్న స్నేహితులు', slotAvailable: 'అందుబాటులో ఉంది · స్నేహితుడితో లింక్ పంచుకోండి', slotInProgress: 'కొనసాగుతోంది · స్నేహితుడు మిషన్‌లు పూర్తి చేస్తున్నాడు', slotReview: 'చివరి తనిఖీ · స్నేహితుడిని ధృవీకరిస్తున్నారు', slotLegacyWaiting: 'పాత ఆహ్వానం · స్నేహితుడి కోసం వేచి ఉంది', slotBlockedReleased: 'ఆమోదం లేదు · స్లాట్ మళ్లీ అందుబాటులో ఉంది', slotsFullTitle: 'రెండు స్నేహితుల స్లాట్‌లు ఉపయోగంలో ఉన్నాయి', slotsFullHelp: 'ప్రస్తుతం ఇద్దరు స్నేహితులు కొనసాగుతున్నారు. శాశ్వత లింక్ చెల్లుబాటులోనే ఉంటుంది; తర్వాత ఇదే లింక్‌తో మళ్లీ ప్రయత్నించండి.', retry: 'మళ్లీ ప్రయత్నించండి', guideInviteDescription: 'మీకు ఒక శాశ్వత ఆహ్వాన లింక్ మరియు మళ్లీ ఉపయోగించగల రెండు స్నేహితుల స్లాట్‌లు ఉన్నాయి. గరిష్టంగా ఇద్దరు అర్హులైన స్నేహితులు ఒకేసారి కొనసాగవచ్చు. లింక్ తెరవడం వల్ల స్లాట్ ఉపయోగించబడదు; అర్హత ధృవీకరించిన తర్వాత మాత్రమే స్లాట్ కేటాయించబడుతుంది.' },
  sw: { badge: 'NAFASI 2 ZA MARAFIKI', homeTitle: 'Kiungo chako cha kudumu cha mwaliko', homeDescription: 'Shiriki kiungo kilekile wakati wowote. Hadi marafiki wawili wanaostahiki wanaweza kuendelea kwa wakati mmoja, na kufungua kiungo pekee hakutumii nafasi.', linkLabel: 'Kiungo cha kudumu cha mwaliko', linkHelp: 'Kiungo hubaki kilekile baada ya rafiki kukamilisha.', slotsLabel: 'Marafiki wanaoendelea', slotAvailable: 'Inapatikana · shiriki kiungo na rafiki', slotInProgress: 'Inaendelea · rafiki anakamilisha misheni', slotReview: 'Ukaguzi wa mwisho · rafiki anathibitishwa', slotLegacyWaiting: 'Mwaliko wa zamani · unasubiri rafiki huyu', slotBlockedReleased: 'Haijaidhinishwa · nafasi inapatikana tena', slotsFullTitle: 'Nafasi zote mbili zinatumika', slotsFullHelp: 'Marafiki wawili tayari wanaendelea. Kiungo cha kudumu bado ni halali; jaribu tena baadaye kwa kiungo kilekile.', retry: 'Jaribu tena', guideInviteDescription: 'Una kiungo kimoja cha kudumu cha mwaliko na nafasi mbili zinazoweza kutumika tena. Hadi marafiki wawili wanaostahiki wanaweza kuendelea pamoja. Kufungua kiungo hakutumii nafasi; nafasi huhifadhiwa baada tu ya kustahiki kuthibitishwa.' },
  ha: { badge: 'WURAREN ABOKAI 2', homeTitle: 'Dindindin mahadar gayyatarka', homeDescription: 'Ka rika tura mahada guda ɗaya. Abokai har biyu da suka cancanta za su iya ci gaba lokaci guda, kuma buɗe mahadar kawai ba ya amfani da wuri.', linkLabel: 'Dindindin mahadar gayyata', linkHelp: 'Mahadar ba ta canzawa bayan aboki ya kammala.', slotsLabel: 'Abokan da ke ci gaba', slotAvailable: 'Akwai · tura mahadar ga aboki', slotInProgress: 'Ana ci gaba · aboki yana kammala ayyuka', slotReview: 'Binciken ƙarshe · ana tabbatar da aboki', slotLegacyWaiting: 'Tsohuwar gayyata · ana jiran wannan aboki', slotBlockedReleased: 'Ba a amince ba · wurin ya sake samuwa', slotsFullTitle: 'Wuraren abokai biyu suna aiki', slotsFullHelp: 'Abokai biyu suna ci gaba yanzu. Dindindin mahadar tana nan da inganci; ka sake gwadawa daga baya da wannan mahadar.', retry: 'Sake gwadawa', guideInviteDescription: 'Kana da dindindin mahadar gayyata guda ɗaya da wuraren abokai biyu da za a sake amfani da su. Abokai har biyu da suka cancanta za su iya ci gaba tare. Buɗe mahadar kawai ba ya amfani da wuri; ana tanadar wurin ne bayan an tabbatar da cancanta.' },
  el: { badge: '2 ΘΕΣΕΙΣ ΦΙΛΩΝ', homeTitle: 'Ο μόνιμος σύνδεσμος πρόσκλησής σου', homeDescription: 'Μοιράσου τον ίδιο σύνδεσμο οποιαδήποτε στιγμή. Έως δύο επιλέξιμοι φίλοι μπορούν να προχωρούν ταυτόχρονα και το απλό άνοιγμα του συνδέσμου δεν χρησιμοποιεί θέση.', linkLabel: 'Μόνιμος σύνδεσμος πρόσκλησης', linkHelp: 'Ο σύνδεσμος παραμένει ο ίδιος αφού ολοκληρώσει ένας φίλος.', slotsLabel: 'Φίλοι σε εξέλιξη', slotAvailable: 'Διαθέσιμη · μοιράσου τον σύνδεσμο με έναν φίλο', slotInProgress: 'Σε εξέλιξη · ο φίλος ολοκληρώνει τις αποστολές', slotReview: 'Τελικός έλεγχος · επαληθεύεται αυτός ο φίλος', slotLegacyWaiting: 'Παλιά πρόσκληση · αναμονή αυτού του φίλου', slotBlockedReleased: 'Δεν εγκρίθηκε · η θέση είναι ξανά διαθέσιμη', slotsFullTitle: 'Και οι δύο θέσεις φίλων χρησιμοποιούνται', slotsFullHelp: 'Δύο φίλοι βρίσκονται ήδη σε εξέλιξη. Ο μόνιμος σύνδεσμος παραμένει έγκυρος, οπότε δοκίμασε ξανά αργότερα με τον ίδιο σύνδεσμο.', retry: 'Δοκίμασε ξανά', guideInviteDescription: 'Έχεις έναν μόνιμο σύνδεσμο πρόσκλησης και δύο επαναχρησιμοποιήσιμες θέσεις φίλων. Έως δύο επιλέξιμοι φίλοι μπορούν να προχωρούν ταυτόχρονα. Το απλό άνοιγμα του συνδέσμου δεν χρησιμοποιεί θέση· η θέση δεσμεύεται μόνο αφού επαληθευτεί η επιλεξιμότητα.' },
};

// Expanded locale packs are registered before this module. Keep every old
// single-invite sentence aligned with the permanent-link/two-slot product rule
// without duplicating the large legacy translation tables.
for (const locale of SUPPORTED_LOCALES) {
  const referral = REFERRAL_LINK_COPY[locale];
  const home = HOME_COPY[locale];
  const flow = GUIDE_FLOW_COPY[locale];

  if (home) {
    home.inviteAvailable = referral.badge;
    home.emptyTitle = referral.homeTitle;
    home.emptyDescription = referral.homeDescription;
    home.inviteReadyDescription = referral.homeDescription;
    home.cancelDescriptionWaiting = referral.slotLegacyWaiting;
    home.noActive = referral.slotAvailable;
    home.createLink = referral.linkLabel;
    home.linkCreated = referral.linkLabel;
    home.waitingForFriendStep = referral.slotLegacyWaiting;
  }

  if (flow) {
    flow.inviteDescription = referral.guideInviteDescription;
  }
}