import type { SupportedLocale } from './locales';

export type RewardForecastCopy = {
  eyebrow: string;
  eligibility: string;
  disclaimer: string;
  pendingTitle: string;
  pendingDescription: string;
  unavailable: string;
};

export const REWARD_FORECAST_COPY: Record<SupportedLocale, RewardForecastCopy> = {
  en: { eyebrow: 'ESTIMATED INVITE REWARD', eligibility: 'You can receive it when your invited friend completes all missions.', disclaimer: 'The estimated reward may change with allocation and participation.', pendingTitle: 'Invite reward estimate coming soon', pendingDescription: 'The estimate will appear automatically when VeInvite has enough real allocation data.', unavailable: 'The reward estimate is temporarily unavailable.' },
  ko: { eyebrow: '예상 초대 보상', eligibility: '친구가 모든 미션을 완료하면 받을 수 있습니다.', disclaimer: '예상 보상은 할당량과 참여 현황에 따라 달라질 수 있습니다.', pendingTitle: '예상 초대 보상 준비 중', pendingDescription: 'VeInvite의 실제 할당 데이터가 충분해지면 예상 보상이 자동으로 표시됩니다.', unavailable: '지금은 예상 보상을 불러올 수 없습니다.' },
  zh: { eyebrow: '预计邀请奖励', eligibility: '你邀请的好友完成全部任务后，你就可以获得奖励。', disclaimer: '预计奖励会根据分配额度和参与情况发生变化。', pendingTitle: '邀请奖励预估准备中', pendingDescription: '当 VeInvite 积累足够的实际分配数据后，预计奖励会自动显示。', unavailable: '暂时无法获取预计奖励。' },
  hi: { eyebrow: 'अनुमानित आमंत्रण इनाम', eligibility: 'आपके आमंत्रित मित्र के सभी मिशन पूरे करने पर आप यह इनाम पा सकते हैं।', disclaimer: 'अनुमानित इनाम आवंटन और भागीदारी के अनुसार बदल सकता है।', pendingTitle: 'आमंत्रण इनाम का अनुमान तैयार हो रहा है', pendingDescription: 'पर्याप्त वास्तविक आवंटन डेटा मिलने के बाद अनुमान अपने-आप दिखाई देगा।', unavailable: 'फिलहाल इनाम का अनुमान उपलब्ध नहीं है।' },
  es: { eyebrow: 'RECOMPENSA ESTIMADA POR INVITACIÓN', eligibility: 'Puedes recibirla cuando el amigo que invitaste complete todas las misiones.', disclaimer: 'La estimación puede variar según la asignación y la participación.', pendingTitle: 'Estimación de recompensa en preparación', pendingDescription: 'La estimación aparecerá automáticamente cuando VeInvite tenga suficientes datos reales de asignación.', unavailable: 'La estimación de recompensa no está disponible temporalmente.' },
  ja: { eyebrow: '招待報酬の予想', eligibility: '招待した友だちがすべてのミッションを完了すると受け取れます。', disclaimer: '予想報酬は配分額や参加状況により変動する場合があります。', pendingTitle: '招待報酬を予想中', pendingDescription: 'VeInviteに十分な実配分データが蓄積されると、予想報酬が自動表示されます。', unavailable: '現在、予想報酬を取得できません。' },
  it: { eyebrow: 'RICOMPENSA INVITO STIMATA', eligibility: 'Puoi riceverla quando l’amico che hai invitato completa tutte le missioni.', disclaimer: 'La stima può variare in base all’allocazione e alla partecipazione.', pendingTitle: 'Stima della ricompensa in preparazione', pendingDescription: 'La stima apparirà automaticamente quando VeInvite avrà dati reali sufficienti sulle allocazioni.', unavailable: 'La stima della ricompensa è temporaneamente non disponibile.' },
  tr: { eyebrow: 'TAHMİNİ DAVET ÖDÜLÜ', eligibility: 'Davet ettiğin arkadaşın tüm görevleri tamamladığında bu ödülü alabilirsin.', disclaimer: 'Tahmini ödül, tahsis ve katılıma göre değişebilir.', pendingTitle: 'Davet ödülü tahmini hazırlanıyor', pendingDescription: 'VeInvite yeterli gerçek tahsis verisine ulaştığında tahmin otomatik olarak görünecek.', unavailable: 'Ödül tahmini geçici olarak kullanılamıyor.' },
  nl: { eyebrow: 'GESCHATTE UITNODIGINGSBELONING', eligibility: 'Je kunt deze ontvangen zodra de vriend die je hebt uitgenodigd alle missies voltooit.', disclaimer: 'De schatting kan veranderen door de toewijzing en deelname.', pendingTitle: 'Beloningsschatting wordt voorbereid', pendingDescription: 'De schatting verschijnt automatisch zodra VeInvite voldoende werkelijke toewijzingsgegevens heeft.', unavailable: 'De beloningsschatting is tijdelijk niet beschikbaar.' },
  de: { eyebrow: 'GESCHÄTZTE EINLADUNGSBELOHNUNG', eligibility: 'Du kannst sie erhalten, sobald dein eingeladener Freund alle Missionen abgeschlossen hat.', disclaimer: 'Die Schätzung kann sich je nach Zuteilung und Teilnahme ändern.', pendingTitle: 'Belohnungsschätzung wird vorbereitet', pendingDescription: 'Die Schätzung erscheint automatisch, sobald VeInvite über ausreichend tatsächliche Zuteilungsdaten verfügt.', unavailable: 'Die Belohnungsschätzung ist vorübergehend nicht verfügbar.' },
  fr: { eyebrow: 'RÉCOMPENSE D’INVITATION ESTIMÉE', eligibility: 'Vous pouvez la recevoir lorsque votre ami invité termine toutes les missions.', disclaimer: 'L’estimation peut varier selon l’allocation et la participation.', pendingTitle: 'Estimation de la récompense en préparation', pendingDescription: 'L’estimation apparaîtra automatiquement lorsque VeInvite disposera de suffisamment de données réelles d’allocation.', unavailable: 'L’estimation de récompense est temporairement indisponible.' },
  ar: { eyebrow: 'مكافأة الدعوة التقديرية', eligibility: 'يمكنك الحصول عليها عندما يُكمل صديقك المدعو جميع المهام.', disclaimer: 'قد تتغير المكافأة التقديرية حسب التخصيص والمشاركة.', pendingTitle: 'تقدير مكافأة الدعوة قيد الإعداد', pendingDescription: 'سيظهر التقدير تلقائيًا عندما تتوفر لدى VeInvite بيانات فعلية كافية عن التخصيص.', unavailable: 'تقدير المكافأة غير متاح مؤقتًا.' },
  bn: { eyebrow: 'আনুমানিক আমন্ত্রণ রিওয়ার্ড', eligibility: 'আপনার আমন্ত্রিত বন্ধু সব মিশন সম্পন্ন করলে আপনি এই রিওয়ার্ড পেতে পারেন।', disclaimer: 'বরাদ্দ ও অংশগ্রহণের ওপর ভিত্তি করে আনুমানিক রিওয়ার্ড পরিবর্তিত হতে পারে।', pendingTitle: 'আমন্ত্রণ রিওয়ার্ডের হিসাব প্রস্তুত হচ্ছে', pendingDescription: 'VeInvite-এর পর্যাপ্ত বাস্তব বরাদ্দ তথ্য পাওয়া গেলে আনুমানিক রিওয়ার্ড স্বয়ংক্রিয়ভাবে দেখা যাবে।', unavailable: 'আনুমানিক রিওয়ার্ড সাময়িকভাবে পাওয়া যাচ্ছে না।' },
  pt: { eyebrow: 'RECOMPENSA ESTIMADA POR CONVITE', eligibility: 'Você pode recebê-la quando o amigo que convidou concluir todas as missões.', disclaimer: 'A recompensa estimada pode mudar conforme a alocação e a participação.', pendingTitle: 'Estimativa da recompensa em preparação', pendingDescription: 'A estimativa aparecerá automaticamente quando o VeInvite tiver dados reais suficientes de alocação.', unavailable: 'A estimativa da recompensa está temporariamente indisponível.' },
  ru: { eyebrow: 'ОЦЕНОЧНАЯ НАГРАДА ЗА ПРИГЛАШЕНИЕ', eligibility: 'Вы сможете получить её, когда приглашённый друг выполнит все задания.', disclaimer: 'Оценочная награда может меняться в зависимости от распределения и участия.', pendingTitle: 'Оценка награды за приглашение готовится', pendingDescription: 'Оценка появится автоматически, когда у VeInvite будет достаточно фактических данных о распределении.', unavailable: 'Оценка награды временно недоступна.' },
  id: { eyebrow: 'ESTIMASI REWARD UNDANGAN', eligibility: 'Anda dapat menerimanya setelah teman yang diundang menyelesaikan semua misi.', disclaimer: 'Estimasi reward dapat berubah sesuai alokasi dan tingkat partisipasi.', pendingTitle: 'Estimasi reward undangan sedang disiapkan', pendingDescription: 'Estimasi akan tampil otomatis setelah VeInvite memiliki cukup data alokasi aktual.', unavailable: 'Estimasi reward sementara tidak tersedia.' },
  vi: { eyebrow: 'PHẦN THƯỞNG MỜI ƯỚC TÍNH', eligibility: 'Bạn có thể nhận phần thưởng khi người bạn được mời hoàn thành tất cả nhiệm vụ.', disclaimer: 'Phần thưởng ước tính có thể thay đổi theo mức phân bổ và số người tham gia.', pendingTitle: 'Đang chuẩn bị ước tính phần thưởng mời', pendingDescription: 'Ước tính sẽ tự động xuất hiện khi VeInvite có đủ dữ liệu phân bổ thực tế.', unavailable: 'Ước tính phần thưởng hiện tạm thời không khả dụng.' },
  'zh-tw': { eyebrow: '預估邀請獎勵', eligibility: '你邀請的朋友完成所有任務後即可獲得獎勵。', disclaimer: '預估獎勵會依分配額度與參與情況而變動。', pendingTitle: '正在準備邀請獎勵預估', pendingDescription: 'VeInvite 累積足夠的實際分配資料後，預估獎勵會自動顯示。', unavailable: '目前暫時無法取得預估獎勵。' },
  sv: { eyebrow: 'UPPSKATTAD INBJUDNINGSBELÖNING', eligibility: 'Du kan få den när vännen du bjudit in har slutfört alla uppdrag.', disclaimer: 'Den uppskattade belöningen kan ändras med fördelning och deltagande.', pendingTitle: 'Belöningsprognosen förbereds', pendingDescription: 'Prognosen visas automatiskt när VeInvite har tillräckligt med verkliga fördelningsdata.', unavailable: 'Belöningsprognosen är tillfälligt otillgänglig.' },
  ro: { eyebrow: 'RECOMPENSĂ ESTIMATĂ PENTRU INVITAȚIE', eligibility: 'O poți primi după ce prietenul invitat finalizează toate misiunile.', disclaimer: 'Recompensa estimată poate varia în funcție de alocare și participare.', pendingTitle: 'Estimarea recompensei este în pregătire', pendingDescription: 'Estimarea va apărea automat când VeInvite va avea suficiente date reale de alocare.', unavailable: 'Estimarea recompensei este temporar indisponibilă.' },
  ur: { eyebrow: 'متوقع دعوتی انعام', eligibility: 'آپ یہ انعام اس وقت حاصل کر سکتے ہیں جب مدعو دوست تمام مشن مکمل کر لے۔', disclaimer: 'متوقع انعام allocation اور شرکت کے مطابق بدل سکتا ہے۔', pendingTitle: 'دعوتی انعام کا تخمینہ تیار ہو رہا ہے', pendingDescription: 'VeInvite کے پاس کافی حقیقی allocation data آنے پر تخمینہ خودکار طور پر دکھائی دے گا۔', unavailable: 'انعام کا تخمینہ عارضی طور پر دستیاب نہیں۔' },
  pcm: { eyebrow: 'ESTIMATED INVITE REWARD', eligibility: 'You fit get am when the person wey you invite finish all the missions.', disclaimer: 'The estimated reward fit change based on allocation and participation.', pendingTitle: 'Invite reward estimate dey prepare', pendingDescription: 'The estimate go show automatically when VeInvite get enough real allocation data.', unavailable: 'Reward estimate no dey available for now.' },
  arz: { eyebrow: 'مكافأة الدعوة المتوقعة', eligibility: 'تقدر تاخدها لما صاحبك اللي عزمته يكمّل كل المهام.', disclaimer: 'المكافأة المتوقعة ممكن تتغير حسب التخصيص وعدد المشاركين.', pendingTitle: 'بنجهّز تقدير مكافأة الدعوة', pendingDescription: 'التقدير هيظهر تلقائي لما يبقى عند VeInvite بيانات تخصيص فعلية كفاية.', unavailable: 'تقدير المكافأة مش متاح مؤقتًا.' },
  mr: { eyebrow: 'अंदाजे आमंत्रण रिवॉर्ड', eligibility: 'तुमच्या आमंत्रित मित्राने सर्व मिशन्स पूर्ण केल्यावर तुम्हाला हा रिवॉर्ड मिळू शकतो.', disclaimer: 'Allocation आणि participation नुसार अंदाजे रिवॉर्ड बदलू शकतो.', pendingTitle: 'आमंत्रण रिवॉर्डचा अंदाज तयार होत आहे', pendingDescription: 'VeInvite कडे पुरेसा वास्तविक allocation data आल्यावर अंदाज आपोआप दिसेल.', unavailable: 'रिवॉर्डचा अंदाज सध्या उपलब्ध नाही.' },
  te: { eyebrow: 'అంచనా ఆహ్వాన రివార్డ్', eligibility: 'మీరు ఆహ్వానించిన స్నేహితుడు అన్ని మిషన్లు పూర్తి చేసిన తర్వాత ఈ రివార్డ్ పొందవచ్చు.', disclaimer: 'Allocation మరియు participation ఆధారంగా అంచనా రివార్డ్ మారవచ్చు.', pendingTitle: 'ఆహ్వాన రివార్డ్ అంచనా సిద్ధమవుతోంది', pendingDescription: 'VeInvite వద్ద సరిపడిన actual allocation data వచ్చిన తర్వాత అంచనా ఆటోమేటిక్‌గా కనిపిస్తుంది.', unavailable: 'రివార్డ్ అంచనా ప్రస్తుతం అందుబాటులో లేదు.' },
  sw: { eyebrow: 'MAKADIRIO YA ZAWADI YA MWALIKO', eligibility: 'Unaweza kuipata baada ya rafiki uliyemwalika kukamilisha majukumu yote.', disclaimer: 'Makadirio ya zawadi yanaweza kubadilika kulingana na allocation na ushiriki.', pendingTitle: 'Makadirio ya zawadi yanaandaliwa', pendingDescription: 'Makadirio yataonekana moja kwa moja VeInvite ikipata data halisi ya allocation ya kutosha.', unavailable: 'Makadirio ya zawadi hayapatikani kwa sasa.' },
  ha: { eyebrow: 'KIMANTA INVITE REWARD', eligibility: 'Za ka iya samun reward idan abokin da ka gayyata ya kammala duk ayyukan.', disclaimer: 'Kimanta reward na iya canzawa bisa allocation da participation.', pendingTitle: 'Ana shirya kimanta invite reward', pendingDescription: 'Kimanta zai bayyana kai tsaye idan VeInvite ya samu isasshen real allocation data.', unavailable: 'Kimanta reward ba ya samuwa a yanzu.' },
  el: { eyebrow: 'ΕΚΤΙΜΩΜΕΝΗ ΑΝΤΑΜΟΙΒΗ ΠΡΟΣΚΛΗΣΗΣ', eligibility: 'Μπορείς να τη λάβεις όταν ο φίλος που προσκάλεσες ολοκληρώσει όλες τις αποστολές.', disclaimer: 'Η εκτιμώμενη ανταμοιβή μπορεί να αλλάξει ανάλογα με την κατανομή και τη συμμετοχή.', pendingTitle: 'Η εκτίμηση ανταμοιβής ετοιμάζεται', pendingDescription: 'Η εκτίμηση θα εμφανιστεί αυτόματα όταν το VeInvite έχει αρκετά πραγματικά δεδομένα κατανομής.', unavailable: 'Η εκτίμηση ανταμοιβής δεν είναι προσωρινά διαθέσιμη.' },
};
