import type { SupportedLocale } from './locales';

type RewardXPromotionCopy = {
  shareBonus: string;
  openHint: string;
  graceHint: string;
  postUrlPlaceholder: string;
  verifyPost: string;
  submitting: string;
  verifying: string;
  retention: string;
  reviewRequired: string;
  payoutPending: string;
  paid: string;
  expired: string;
  released: string;
  submitError: string;
};

export const REWARD_X_PROMOTION_COPY: Record<
  SupportedLocale,
  RewardXPromotionCopy
> = {
  en:{shareBonus:'Share on X and earn +{amount} B3TR',openHint:'Post within 24 hours. If the same public Post is still available after 24 hours, the bonus can be paid.',graceHint:'If you posted before the deadline, paste the Post link now.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Verify Post link',submitting:'Checking…',verifying:'Your X Post is being verified.',retention:'Post confirmed. Keep the same public Post available for 24 hours.',reviewRequired:'Verification needs an additional review.',payoutPending:'X promotion verified. Bonus payout is pending.',paid:'X promotion bonus paid.',expired:'The X promotion window has expired.',released:'This X promotion bonus is no longer available.',submitError:'The X Post could not be verified right now. Please try again.'},
  ko:{shareBonus:'X에 공유하고 +{amount} B3TR 받기',openHint:'24시간 안에 게시해 주세요. 같은 공개 게시물이 24시간 후에도 확인되면 보너스가 지급될 수 있어요.',graceHint:'마감 전에 게시했다면 지금 게시물 링크를 붙여 넣어 주세요.',postUrlPlaceholder:'https://x.com/사용자/status/...',verifyPost:'게시물 링크 확인',submitting:'확인 중…',verifying:'X 게시물을 확인하고 있어요.',retention:'게시물이 확인됐어요. 같은 공개 게시물을 24시간 유지해 주세요.',reviewRequired:'추가 확인이 필요한 상태예요.',payoutPending:'X 홍보 조건을 통과했어요. 보너스 지급 대기 중이에요.',paid:'X 홍보 보너스가 지급됐어요.',expired:'X 홍보 참여 시간이 만료됐어요.',released:'이 X 홍보 보너스는 더 이상 받을 수 없어요.',submitError:'지금은 X 게시물을 확인할 수 없어요. 잠시 후 다시 시도해 주세요.'},
  zh:{shareBonus:'分享到 X 并获得 +{amount} B3TR',openHint:'请在 24 小时内发布。若同一公开帖子在 24 小时后仍可查看，即可进入奖励支付。',graceHint:'如果你已在截止前发布，请现在粘贴帖子链接。',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'验证帖子链接',submitting:'验证中…',verifying:'正在验证你的 X 帖子。',retention:'帖子已确认，请保持同一公开帖子 24 小时。',reviewRequired:'此验证需要进一步审核。',payoutPending:'X 推广已验证，奖励等待支付。',paid:'X 推广奖励已支付。',expired:'X 推广参与时间已结束。',released:'此 X 推广奖励已不可领取。',submitError:'暂时无法验证 X 帖子，请稍后重试。'},
  hi:{shareBonus:'X पर शेयर करें और +{amount} B3TR पाएँ',openHint:'24 घंटे के भीतर पोस्ट करें। वही सार्वजनिक पोस्ट 24 घंटे बाद भी उपलब्ध होने पर बोनस दिया जा सकता है।',graceHint:'यदि आपने समय सीमा से पहले पोस्ट किया था, तो लिंक अभी पेस्ट करें।',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'पोस्ट लिंक जाँचें',submitting:'जाँच हो रही है…',verifying:'आपकी X पोस्ट की जाँच हो रही है।',retention:'पोस्ट की पुष्टि हो गई है। उसी सार्वजनिक पोस्ट को 24 घंटे उपलब्ध रखें।',reviewRequired:'इस सत्यापन को अतिरिक्त समीक्षा चाहिए।',payoutPending:'X प्रमोशन सत्यापित है। बोनस भुगतान लंबित है।',paid:'X प्रमोशन बोनस का भुगतान हो गया।',expired:'X प्रमोशन की समय सीमा समाप्त हो गई।',released:'यह X प्रमोशन बोनस अब उपलब्ध नहीं है।',submitError:'अभी X पोस्ट सत्यापित नहीं हो सकी। बाद में फिर कोशिश करें।'},
  es:{shareBonus:'Comparte en X y gana +{amount} B3TR',openHint:'Publica en 24 horas. Si la misma publicación pública sigue disponible 24 horas después, el bono podrá pagarse.',graceHint:'Si publicaste antes del límite, pega ahora el enlace.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Verificar publicación',submitting:'Verificando…',verifying:'Estamos verificando tu publicación en X.',retention:'Publicación confirmada. Mantén la misma publicación pública durante 24 horas.',reviewRequired:'La verificación necesita una revisión adicional.',payoutPending:'Promoción en X verificada. El bono está pendiente de pago.',paid:'Bono de promoción en X pagado.',expired:'El plazo de la promoción en X ha vencido.',released:'Este bono de promoción en X ya no está disponible.',submitError:'No se pudo verificar la publicación ahora. Inténtalo de nuevo.'},
  ja:{shareBonus:'Xでシェアして +{amount} B3TR',openHint:'24時間以内に投稿してください。同じ公開投稿が24時間後も確認できれば、ボーナス支払い対象になります。',graceHint:'期限前に投稿済みなら、投稿リンクを今貼り付けてください。',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'投稿リンクを確認',submitting:'確認中…',verifying:'X投稿を確認しています。',retention:'投稿を確認しました。同じ公開投稿を24時間維持してください。',reviewRequired:'追加確認が必要です。',payoutPending:'Xプロモーションを確認しました。ボーナス支払い待ちです。',paid:'Xプロモーションボーナスを支払いました。',expired:'Xプロモーションの受付時間が終了しました。',released:'このXプロモーションボーナスは利用できません。',submitError:'現在X投稿を確認できません。後でもう一度お試しください。'},
  it:{shareBonus:'Condividi su X e ottieni +{amount} B3TR',openHint:'Pubblica entro 24 ore. Se lo stesso Post pubblico è ancora disponibile dopo 24 ore, il bonus può essere pagato.',graceHint:'Se hai pubblicato prima della scadenza, incolla ora il link.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Verifica il Post',submitting:'Verifica…',verifying:'Stiamo verificando il tuo Post su X.',retention:'Post confermato. Mantieni lo stesso Post pubblico disponibile per 24 ore.',reviewRequired:'La verifica richiede un controllo aggiuntivo.',payoutPending:'Promozione X verificata. Bonus in attesa di pagamento.',paid:'Bonus promozione X pagato.',expired:'La finestra della promozione X è scaduta.',released:'Questo bonus promozione X non è più disponibile.',submitError:'Impossibile verificare ora il Post. Riprova più tardi.'},
  tr:{shareBonus:"X'te paylaş ve +{amount} B3TR kazan",openHint:'24 saat içinde paylaş. Aynı herkese açık gönderi 24 saat sonra da erişilebilirse bonus ödenebilir.',graceHint:'Son tarihten önce paylaştıysan gönderi bağlantısını şimdi yapıştır.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Gönderiyi doğrula',submitting:'Kontrol ediliyor…',verifying:'X gönderin doğrulanıyor.',retention:'Gönderi doğrulandı. Aynı herkese açık gönderiyi 24 saat erişilebilir tut.',reviewRequired:'Doğrulama ek inceleme gerektiriyor.',payoutPending:'X promosyonu doğrulandı. Bonus ödeme bekliyor.',paid:'X promosyon bonusu ödendi.',expired:'X promosyon süresi doldu.',released:'Bu X promosyon bonusu artık kullanılamıyor.',submitError:'X gönderisi şu anda doğrulanamadı. Tekrar dene.'},
  nl:{shareBonus:'Deel op X en verdien +{amount} B3TR',openHint:'Plaats binnen 24 uur. Als dezelfde openbare post 24 uur later nog beschikbaar is, kan de bonus worden betaald.',graceHint:'Heb je vóór de deadline gepost, plak dan nu de link.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Post verifiëren',submitting:'Controleren…',verifying:'Je X-post wordt gecontroleerd.',retention:'Post bevestigd. Houd dezelfde openbare post 24 uur beschikbaar.',reviewRequired:'De verificatie heeft extra controle nodig.',payoutPending:'X-promotie geverifieerd. Bonus wacht op betaling.',paid:'X-promotiebonus betaald.',expired:'De X-promotieperiode is verlopen.',released:'Deze X-promotiebonus is niet meer beschikbaar.',submitError:'De X-post kan nu niet worden geverifieerd. Probeer het later opnieuw.'},
  de:{shareBonus:'Auf X teilen und +{amount} B3TR verdienen',openHint:'Innerhalb von 24 Stunden posten. Ist derselbe öffentliche Post nach 24 Stunden noch verfügbar, kann der Bonus ausgezahlt werden.',graceHint:'Wenn du vor Ablauf gepostet hast, füge jetzt den Link ein.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Post prüfen',submitting:'Prüfung…',verifying:'Dein X-Post wird geprüft.',retention:'Post bestätigt. Lass denselben öffentlichen Post 24 Stunden verfügbar.',reviewRequired:'Die Prüfung benötigt eine zusätzliche Kontrolle.',payoutPending:'X-Promotion bestätigt. Bonus wartet auf Auszahlung.',paid:'X-Promotion-Bonus ausgezahlt.',expired:'Das Zeitfenster der X-Promotion ist abgelaufen.',released:'Dieser X-Promotion-Bonus ist nicht mehr verfügbar.',submitError:'Der X-Post kann gerade nicht geprüft werden. Bitte erneut versuchen.'},
  fr:{shareBonus:'Partager sur X et gagner +{amount} B3TR',openHint:'Publiez dans les 24 heures. Si le même Post public est encore disponible 24 heures plus tard, le bonus pourra être versé.',graceHint:'Si vous avez publié avant la limite, collez le lien maintenant.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Vérifier le Post',submitting:'Vérification…',verifying:'Votre Post X est en cours de vérification.',retention:'Post confirmé. Gardez le même Post public disponible pendant 24 heures.',reviewRequired:'La vérification nécessite un contrôle supplémentaire.',payoutPending:'Promotion X vérifiée. Le bonus est en attente de paiement.',paid:'Bonus de promotion X versé.',expired:'La période de promotion X est terminée.',released:'Ce bonus de promotion X n’est plus disponible.',submitError:'Le Post X ne peut pas être vérifié maintenant. Réessayez plus tard.'},
  ar:{shareBonus:'شارك على X واحصل على +{amount} B3TR',openHint:'انشر خلال 24 ساعة. إذا ظل نفس المنشور العام متاحًا بعد 24 ساعة، يمكن دفع المكافأة.',graceHint:'إذا نشرت قبل الموعد، الصق رابط المنشور الآن.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'تحقق من رابط المنشور',submitting:'جارٍ التحقق…',verifying:'جارٍ التحقق من منشور X.',retention:'تم تأكيد المنشور. أبقِ نفس المنشور العام متاحًا لمدة 24 ساعة.',reviewRequired:'يحتاج التحقق إلى مراجعة إضافية.',payoutPending:'تم التحقق من ترويج X. المكافأة بانتظار الدفع.',paid:'تم دفع مكافأة ترويج X.',expired:'انتهت مهلة ترويج X.',released:'لم تعد مكافأة ترويج X متاحة.',submitError:'تعذر التحقق من منشور X الآن. حاول مرة أخرى لاحقًا.'},
  bn:{shareBonus:'X-এ শেয়ার করে +{amount} B3TR পান',openHint:'২৪ ঘণ্টার মধ্যে পোস্ট করুন। একই পাবলিক পোস্ট ২৪ ঘণ্টা পরেও থাকলে বোনাস দেওয়া যেতে পারে।',graceHint:'সময়সীমার আগে পোস্ট করলে এখন লিংকটি দিন।',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'পোস্ট লিংক যাচাই',submitting:'যাচাই হচ্ছে…',verifying:'আপনার X পোস্ট যাচাই করা হচ্ছে।',retention:'পোস্ট নিশ্চিত হয়েছে। একই পাবলিক পোস্ট ২৪ ঘণ্টা রাখুন।',reviewRequired:'যাচাইয়ের জন্য অতিরিক্ত পর্যালোচনা দরকার।',payoutPending:'X প্রচার যাচাই হয়েছে। বোনাস পেমেন্ট অপেক্ষমাণ।',paid:'X প্রচার বোনাস দেওয়া হয়েছে।',expired:'X প্রচারের সময়সীমা শেষ।',released:'এই X প্রচার বোনাস আর পাওয়া যাবে না।',submitError:'এখন X পোস্ট যাচাই করা যাচ্ছে না। পরে আবার চেষ্টা করুন।'},
  pt:{shareBonus:'Compartilhe no X e ganhe +{amount} B3TR',openHint:'Publique em até 24 horas. Se o mesmo Post público continuar disponível após 24 horas, o bônus poderá ser pago.',graceHint:'Se publicou antes do prazo, cole o link agora.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Verificar Post',submitting:'Verificando…',verifying:'Seu Post no X está sendo verificado.',retention:'Post confirmado. Mantenha o mesmo Post público disponível por 24 horas.',reviewRequired:'A verificação precisa de revisão adicional.',payoutPending:'Promoção no X verificada. Bônus aguardando pagamento.',paid:'Bônus da promoção no X pago.',expired:'O prazo da promoção no X expirou.',released:'Este bônus da promoção no X não está mais disponível.',submitError:'Não foi possível verificar o Post agora. Tente novamente.'},
  ru:{shareBonus:'Поделиться в X и получить +{amount} B3TR',openHint:'Опубликуйте в течение 24 часов. Если тот же публичный пост будет доступен через 24 часа, бонус можно выплатить.',graceHint:'Если вы опубликовали до срока, вставьте ссылку сейчас.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Проверить пост',submitting:'Проверка…',verifying:'Ваш пост в X проверяется.',retention:'Пост подтверждён. Оставьте тот же публичный пост доступным 24 часа.',reviewRequired:'Требуется дополнительная проверка.',payoutPending:'Промо в X подтверждено. Бонус ожидает выплаты.',paid:'Бонус за промо в X выплачен.',expired:'Срок промо в X истёк.',released:'Этот бонус за промо в X больше недоступен.',submitError:'Сейчас пост X проверить нельзя. Попробуйте позже.'},
  id:{shareBonus:'Bagikan di X dan dapatkan +{amount} B3TR',openHint:'Posting dalam 24 jam. Jika Post publik yang sama masih tersedia setelah 24 jam, bonus dapat dibayar.',graceHint:'Jika sudah posting sebelum batas waktu, tempel tautannya sekarang.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Verifikasi Post',submitting:'Memeriksa…',verifying:'Post X Anda sedang diverifikasi.',retention:'Post dikonfirmasi. Biarkan Post publik yang sama tersedia selama 24 jam.',reviewRequired:'Verifikasi memerlukan pemeriksaan tambahan.',payoutPending:'Promosi X terverifikasi. Bonus menunggu pembayaran.',paid:'Bonus promosi X telah dibayar.',expired:'Waktu promosi X telah berakhir.',released:'Bonus promosi X ini sudah tidak tersedia.',submitError:'Post X belum dapat diverifikasi. Coba lagi nanti.'},
  vi:{shareBonus:'Chia sẻ lên X và nhận +{amount} B3TR',openHint:'Đăng trong vòng 24 giờ. Nếu cùng bài đăng công khai vẫn còn sau 24 giờ, tiền thưởng có thể được trả.',graceHint:'Nếu đã đăng trước hạn, hãy dán liên kết bài đăng ngay bây giờ.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Xác minh bài đăng',submitting:'Đang kiểm tra…',verifying:'Bài đăng X của bạn đang được xác minh.',retention:'Đã xác nhận bài đăng. Hãy giữ cùng bài đăng công khai trong 24 giờ.',reviewRequired:'Việc xác minh cần xem xét thêm.',payoutPending:'Đã xác minh quảng bá X. Tiền thưởng đang chờ trả.',paid:'Đã trả thưởng quảng bá X.',expired:'Thời gian quảng bá X đã hết.',released:'Phần thưởng quảng bá X này không còn khả dụng.',submitError:'Hiện chưa thể xác minh bài đăng X. Hãy thử lại sau.'},
  'zh-tw':{shareBonus:'分享到 X 並獲得 +{amount} B3TR',openHint:'請在 24 小時內發文。若同一公開貼文在 24 小時後仍可查看，即可進入獎勵付款。',graceHint:'如果你已在截止前發文，請現在貼上貼文連結。',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'驗證貼文連結',submitting:'驗證中…',verifying:'正在驗證你的 X 貼文。',retention:'貼文已確認，請讓同一公開貼文維持 24 小時。',reviewRequired:'此驗證需要進一步審查。',payoutPending:'X 推廣已驗證，獎勵等待付款。',paid:'X 推廣獎勵已付款。',expired:'X 推廣參與時間已結束。',released:'此 X 推廣獎勵已不可領取。',submitError:'目前無法驗證 X 貼文，請稍後再試。'},
  sv:{shareBonus:'Dela på X och få +{amount} B3TR',openHint:'Publicera inom 24 timmar. Om samma offentliga inlägg finns kvar efter 24 timmar kan bonusen betalas.',graceHint:'Om du publicerade före tidsgränsen, klistra in länken nu.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Verifiera inlägg',submitting:'Kontrollerar…',verifying:'Ditt X-inlägg verifieras.',retention:'Inlägget är bekräftat. Låt samma offentliga inlägg vara tillgängligt i 24 timmar.',reviewRequired:'Verifieringen behöver extra granskning.',payoutPending:'X-kampanjen är verifierad. Bonus väntar på utbetalning.',paid:'X-kampanjbonusen är utbetald.',expired:'Tiden för X-kampanjen har gått ut.',released:'Den här X-kampanjbonusen är inte längre tillgänglig.',submitError:'X-inlägget kan inte verifieras just nu. Försök igen senare.'},
  ro:{shareBonus:'Distribuie pe X și câștigă +{amount} B3TR',openHint:'Publică în 24 de ore. Dacă aceeași postare publică rămâne disponibilă după 24 de ore, bonusul poate fi plătit.',graceHint:'Dacă ai publicat înainte de termen, lipește linkul acum.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Verifică postarea',submitting:'Se verifică…',verifying:'Postarea ta de pe X este verificată.',retention:'Postare confirmată. Păstrează aceeași postare publică disponibilă 24 de ore.',reviewRequired:'Verificarea necesită o analiză suplimentară.',payoutPending:'Promovarea pe X a fost verificată. Bonusul așteaptă plata.',paid:'Bonusul pentru promovarea pe X a fost plătit.',expired:'Perioada promoției X a expirat.',released:'Acest bonus pentru promovarea pe X nu mai este disponibil.',submitError:'Postarea X nu poate fi verificată acum. Încearcă din nou.'},
  ur:{shareBonus:'X پر شیئر کریں اور +{amount} B3TR حاصل کریں',openHint:'24 گھنٹوں کے اندر پوسٹ کریں۔ اگر یہی عوامی پوسٹ 24 گھنٹے بعد بھی موجود ہو تو بونس ادا کیا جا سکتا ہے۔',graceHint:'اگر آپ نے آخری وقت سے پہلے پوسٹ کیا تھا تو اب لنک پیسٹ کریں۔',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'پوسٹ لنک کی تصدیق',submitting:'جانچ جاری ہے…',verifying:'آپ کی X پوسٹ کی تصدیق ہو رہی ہے۔',retention:'پوسٹ کی تصدیق ہو گئی۔ اسی عوامی پوسٹ کو 24 گھنٹے دستیاب رکھیں۔',reviewRequired:'تصدیق کے لیے مزید جائزہ درکار ہے۔',payoutPending:'X پروموشن کی تصدیق ہو گئی۔ بونس ادائیگی کا منتظر ہے۔',paid:'X پروموشن بونس ادا ہو گیا۔',expired:'X پروموشن کی مدت ختم ہو گئی۔',released:'یہ X پروموشن بونس اب دستیاب نہیں ہے۔',submitError:'ابھی X پوسٹ کی تصدیق نہیں ہو سکی۔ بعد میں دوبارہ کوشش کریں۔'},
  pcm:{shareBonus:'Share am for X collect +{amount} B3TR',openHint:'Post am within 24 hours. If the same public Post still dey after 24 hours, bonus fit pay.',graceHint:'If you post before deadline, paste the Post link now.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Check Post link',submitting:'Dey check…',verifying:'We dey verify your X Post.',retention:'Post don confirm. Leave the same public Post up for 24 hours.',reviewRequired:'This verification need extra review.',payoutPending:'X promotion don verify. Bonus dey wait for payment.',paid:'X promotion bonus don pay.',expired:'X promotion time don finish.',released:'This X promotion bonus no dey available again.',submitError:'We no fit verify the X Post now. Try again later.'},
  arz:{shareBonus:'شارك على X وخد +{amount} B3TR',openHint:'انشر خلال 24 ساعة. لو نفس البوست العام لسه موجود بعد 24 ساعة، البونص ممكن يتدفع.',graceHint:'لو نشرت قبل الميعاد، حط لينك البوست دلوقتي.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'تحقق من البوست',submitting:'بنتحقق…',verifying:'بنتحقق من بوست X بتاعك.',retention:'البوست اتأكد. خليه عام وموجود لمدة 24 ساعة.',reviewRequired:'التحقق محتاج مراجعة إضافية.',payoutPending:'ترويج X اتأكد. البونص مستني الدفع.',paid:'بونص ترويج X اتدفع.',expired:'وقت ترويج X انتهى.',released:'بونص ترويج X ده مش متاح دلوقتي.',submitError:'مش قادرين نتحقق من بوست X دلوقتي. جرّب تاني بعدين.'},
  mr:{shareBonus:'X वर शेअर करा आणि +{amount} B3TR मिळवा',openHint:'२४ तासांत पोस्ट करा. तीच सार्वजनिक पोस्ट २४ तासांनंतरही उपलब्ध असल्यास बोनस दिला जाऊ शकतो.',graceHint:'मुदतीपूर्वी पोस्ट केली असल्यास लिंक आत्ता पेस्ट करा.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'पोस्ट लिंक तपासा',submitting:'तपासत आहे…',verifying:'तुमची X पोस्ट तपासली जात आहे.',retention:'पोस्ट निश्चित झाली. तीच सार्वजनिक पोस्ट २४ तास उपलब्ध ठेवा.',reviewRequired:'तपासणीसाठी अतिरिक्त पुनरावलोकन आवश्यक आहे.',payoutPending:'X प्रमोशन सत्यापित झाले. बोनस पेमेंटची प्रतीक्षा आहे.',paid:'X प्रमोशन बोनस दिला आहे.',expired:'X प्रमोशनची वेळ संपली.',released:'हा X प्रमोशन बोनस आता उपलब्ध नाही.',submitError:'आत्ता X पोस्ट तपासता आली नाही. पुन्हा प्रयत्न करा.'},
  te:{shareBonus:'Xలో షేర్ చేసి +{amount} B3TR పొందండి',openHint:'24 గంటల్లో పోస్ట్ చేయండి. అదే పబ్లిక్ పోస్ట్ 24 గంటల తర్వాత కూడా అందుబాటులో ఉంటే బోనస్ చెల్లించవచ్చు.',graceHint:'గడువు ముందు పోస్ట్ చేసి ఉంటే ఇప్పుడు లింక్‌ను పేస్ట్ చేయండి.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'పోస్ట్ లింక్ ధృవీకరించండి',submitting:'తనిఖీ చేస్తోంది…',verifying:'మీ X పోస్ట్ ధృవీకరించబడుతోంది.',retention:'పోస్ట్ నిర్ధారించబడింది. అదే పబ్లిక్ పోస్ట్‌ను 24 గంటలు ఉంచండి.',reviewRequired:'ధృవీకరణకు అదనపు సమీక్ష అవసరం.',payoutPending:'X ప్రమోషన్ ధృవీకరించబడింది. బోనస్ చెల్లింపు పెండింగ్‌లో ఉంది.',paid:'X ప్రమోషన్ బోనస్ చెల్లించబడింది.',expired:'X ప్రమోషన్ సమయం ముగిసింది.',released:'ఈ X ప్రమోషన్ బోనస్ ఇక అందుబాటులో లేదు.',submitError:'ఇప్పుడు X పోస్ట్‌ను ధృవీకరించలేకపోయాం. మళ్లీ ప్రయత్నించండి.'},
  sw:{shareBonus:'Shiriki kwenye X upate +{amount} B3TR',openHint:'Chapisha ndani ya saa 24. Ikiwa Post hiyo hiyo ya umma bado ipo baada ya saa 24, bonasi inaweza kulipwa.',graceHint:'Ikiwa ulichapisha kabla ya muda kuisha, bandika kiungo sasa.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Thibitisha Post',submitting:'Inakaguliwa…',verifying:'Post yako ya X inathibitishwa.',retention:'Post imethibitishwa. Iache Post hiyo hiyo ya umma ipatikane kwa saa 24.',reviewRequired:'Uthibitishaji unahitaji ukaguzi wa ziada.',payoutPending:'Promosheni ya X imethibitishwa. Bonasi inasubiri malipo.',paid:'Bonasi ya promosheni ya X imelipwa.',expired:'Muda wa promosheni ya X umeisha.',released:'Bonasi hii ya promosheni ya X haipatikani tena.',submitError:'Post ya X haiwezi kuthibitishwa sasa. Jaribu tena baadaye.'},
  ha:{shareBonus:'Raba a X ka samu +{amount} B3TR',openHint:'Yi post cikin awa 24. Idan wannan post ɗin na jama’a yana nan bayan awa 24, ana iya biyan bonus.',graceHint:'Idan ka yi post kafin wa’adi, liƙa link ɗin yanzu.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Duba link ɗin post',submitting:'Ana dubawa…',verifying:'Ana tabbatar da post ɗinka na X.',retention:'An tabbatar da post. Bar wannan post ɗin na jama’a a nan na awa 24.',reviewRequired:'Tabbatarwar na buƙatar ƙarin dubawa.',payoutPending:'An tabbatar da tallan X. Bonus yana jiran biya.',paid:'An biya bonus na tallan X.',expired:'Lokacin tallan X ya ƙare.',released:'Wannan bonus na tallan X ba ya samuwa yanzu.',submitError:'Ba a iya tabbatar da post ɗin X yanzu ba. Sake gwadawa.'},
  el:{shareBonus:'Κοινοποίησε στο X και κέρδισε +{amount} B3TR',openHint:'Δημοσίευσε μέσα σε 24 ώρες. Αν το ίδιο δημόσιο Post παραμένει διαθέσιμο μετά από 24 ώρες, το μπόνους μπορεί να πληρωθεί.',graceHint:'Αν δημοσίευσες πριν τη λήξη, επικόλλησε τώρα τον σύνδεσμο.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Επαλήθευση Post',submitting:'Έλεγχος…',verifying:'Το X Post σου επαληθεύεται.',retention:'Το Post επιβεβαιώθηκε. Κράτησε το ίδιο δημόσιο Post διαθέσιμο για 24 ώρες.',reviewRequired:'Η επαλήθευση χρειάζεται επιπλέον έλεγχο.',payoutPending:'Η προώθηση X επαληθεύτηκε. Το μπόνους περιμένει πληρωμή.',paid:'Το μπόνους προώθησης X πληρώθηκε.',expired:'Το χρονικό παράθυρο της προώθησης X έληξε.',released:'Αυτό το μπόνους προώθησης X δεν είναι πλέον διαθέσιμο.',submitError:'Το X Post δεν μπορεί να επαληθευτεί τώρα. Δοκίμασε ξανά.'},
  cs:{shareBonus:'Sdílej na X a získej +{amount} B3TR',openHint:'Zveřejni do 24 hodin. Pokud bude stejný veřejný Post dostupný i po 24 hodinách, bonus může být vyplacen.',graceHint:'Pokud jsi zveřejnil(a) před termínem, vlož teď odkaz.',postUrlPlaceholder:'https://x.com/you/status/...',verifyPost:'Ověřit Post',submitting:'Ověřování…',verifying:'Tvůj X Post se ověřuje.',retention:'Post potvrzen. Nech stejný veřejný Post dostupný 24 hodin.',reviewRequired:'Ověření vyžaduje další kontrolu.',payoutPending:'X propagace ověřena. Bonus čeká na výplatu.',paid:'Bonus za X propagaci byl vyplacen.',expired:'Čas pro X propagaci vypršel.',released:'Tento bonus za X propagaci už není dostupný.',submitError:'X Post teď nelze ověřit. Zkus to znovu později.'},
};
