-- Persist an automatically signed VeInvite reward transaction before broadcast.
-- The raw signed transaction is not a private key or secret; once broadcast it
-- is public chain data. Keeping the exact bytes lets a serverless worker retry
-- the same transaction id after a network/process failure without creating a
-- second payout transaction.

begin;

create table if not exists public.reward_payout_signed_transactions (
  id bigint generated by default as identity primary key,
  manifest_id bigint not null unique
    references public.reward_payout_manifests(id) on delete restrict,
  round_id bigint not null unique
    references public.reward_rounds(id) on delete restrict,
  network text not null,
  manifest_hash text not null,
  tx_id text not null unique,
  operator_wallet text not null,
  raw_tx_hex text not null,
  created_at timestamptz not null default now(),
  constraint reward_payout_signed_transactions_network_check
    check (network in ('mainnet','testnet','testnet-staging')),
  constraint reward_payout_signed_transactions_hash_check
    check (manifest_hash ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_signed_transactions_tx_id_check
    check (tx_id ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_signed_transactions_operator_check
    check (operator_wallet ~ '^0x[0-9a-f]{40}$'),
  constraint reward_payout_signed_transactions_raw_check
    check (raw_tx_hex ~ '^0x[0-9a-f]+$')
);

alter table public.reward_payout_signed_transactions enable row level security;
revoke all on table public.reward_payout_signed_transactions
  from public, anon, authenticated;
grant select on table public.reward_payout_signed_transactions
  to service_role;

create or replace function public.reject_reward_payout_signed_transaction_mutation()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception 'automatic reward signed transactions are immutable';
end;
$$;

revoke all on function public.reject_reward_payout_signed_transaction_mutation()
  from public, anon, authenticated;

drop trigger if exists reward_payout_signed_transactions_immutable_guard
  on public.reward_payout_signed_transactions;
create trigger reward_payout_signed_transactions_immutable_guard
before update or delete on public.reward_payout_signed_transactions
for each row execute function public.reject_reward_payout_signed_transaction_mutation();

create or replace function public.register_reward_payout_signed_transaction(
  p_manifest_id bigint,
  p_tx_id text,
  p_operator_wallet text,
  p_raw_tx_hex text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_manifest public.reward_payout_manifests%rowtype;
  v_existing public.reward_payout_signed_transactions%rowtype;
  v_id bigint;
begin
  p_tx_id := lower(btrim(p_tx_id));
  p_operator_wallet := lower(btrim(p_operator_wallet));
  p_raw_tx_hex := lower(btrim(p_raw_tx_hex));

  if p_manifest_id is null or p_manifest_id < 1 then
    raise exception 'manifest_id must be positive';
  end if;
  if p_tx_id is null or p_tx_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'tx_id must be a lowercase 32-byte hex value';
  end if;
  if p_operator_wallet is null or p_operator_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'operator wallet must be a lowercase VeChain address';
  end if;
  if p_raw_tx_hex is null or p_raw_tx_hex !~ '^0x[0-9a-f]+$' then
    raise exception 'raw signed transaction must be lowercase hex';
  end if;

  select * into v_manifest
  from public.reward_payout_manifests
  where id = p_manifest_id;

  if not found then
    raise exception 'reward payout manifest not found';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_signed_tx_' || v_manifest.round_id::text,
      0
    )
  );

  if v_manifest.operator_wallet <> p_operator_wallet then
    raise exception 'operator wallet does not match payout manifest';
  end if;

  if not exists (
    select 1
    from public.reward_payout_manifest_chain_checkpoints c
    where c.manifest_id = v_manifest.id
  ) then
    raise exception 'payout manifest chain checkpoint must exist before signing';
  end if;

  if exists (
    select 1
    from public.reward_payout_transaction_settlements s
    where s.manifest_id = v_manifest.id
  ) then
    raise exception 'reward payout manifest is already finalized';
  end if;

  select * into v_existing
  from public.reward_payout_signed_transactions
  where manifest_id = v_manifest.id;

  if found then
    if v_existing.tx_id = p_tx_id
       and v_existing.operator_wallet = p_operator_wallet
       and v_existing.raw_tx_hex = p_raw_tx_hex
       and v_existing.manifest_hash = v_manifest.manifest_hash then
      return jsonb_build_object(
        'signed_transaction_id', v_existing.id,
        'created', false,
        'tx_id', v_existing.tx_id
      );
    end if;

    raise exception 'reward payout manifest already has a different signed transaction';
  end if;

  if exists (
    select 1 from public.reward_payout_signed_transactions s
    where s.tx_id = p_tx_id and s.manifest_id <> v_manifest.id
  ) then
    raise exception 'signed transaction is already bound to another manifest';
  end if;

  insert into public.reward_payout_signed_transactions(
    manifest_id,
    round_id,
    network,
    manifest_hash,
    tx_id,
    operator_wallet,
    raw_tx_hex
  ) values (
    v_manifest.id,
    v_manifest.round_id,
    v_manifest.network,
    v_manifest.manifest_hash,
    p_tx_id,
    p_operator_wallet,
    p_raw_tx_hex
  ) returning id into v_id;

  return jsonb_build_object(
    'signed_transaction_id', v_id,
    'created', true,
    'tx_id', p_tx_id
  );
end;
$$;

revoke all on function public.register_reward_payout_signed_transaction(
  bigint, text, text, text
) from public, anon, authenticated;
grant execute on function public.register_reward_payout_signed_transaction(
  bigint, text, text, text
) to service_role;

commit;
