create table if not exists public.operator_monitor_snapshots (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('mainnet', 'testnet', 'testnet-staging')),
  trigger_source text not null check (trigger_source in ('VERCEL_CRON', 'MANUAL_OPERATOR', 'SYSTEM_TEST')),
  severity text not null check (severity in ('NORMAL', 'WARNING', 'CRITICAL')),
  alert_count integer not null check (alert_count >= 0),
  metrics jsonb not null check (jsonb_typeof(metrics) = 'object'),
  alerts jsonb not null check (jsonb_typeof(alerts) = 'array'),
  captured_at timestamptz not null default now()
);

create index if not exists operator_monitor_snapshots_network_captured_idx
  on public.operator_monitor_snapshots (network, captured_at desc);

alter table public.operator_monitor_snapshots enable row level security;

revoke all on table public.operator_monitor_snapshots from public, anon, authenticated;
grant select, insert on table public.operator_monitor_snapshots to service_role;

do $$
begin
  if to_regclass('public.operator_monitor_snapshots_id_seq') is not null then
    revoke all on sequence public.operator_monitor_snapshots_id_seq from public, anon, authenticated;
    grant usage, select on sequence public.operator_monitor_snapshots_id_seq to service_role;
  end if;
end;
$$;

create or replace function public.prevent_operator_monitor_snapshot_mutation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception 'Operator monitor snapshots are append-only.';
end;
$$;

revoke all on function public.prevent_operator_monitor_snapshot_mutation() from public, anon, authenticated;
revoke all on function public.prevent_operator_monitor_snapshot_mutation() from service_role;

create trigger operator_monitor_snapshots_append_only
before update or delete on public.operator_monitor_snapshots
for each row execute function public.prevent_operator_monitor_snapshot_mutation();

create or replace function public.record_operator_anomaly_snapshot(
  p_network text,
  p_trigger_source text default 'VERCEL_CRON'
)
returns table (
  snapshot_id bigint,
  severity text,
  alert_count integer,
  metrics jsonb,
  alerts jsonb,
  captured_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_invites_24h bigint := 0;
  v_invites_prev_7d bigint := 0;
  v_claimed_24h bigint := 0;
  v_under_review_24h bigint := 0;
  v_open_under_review bigint := 0;
  v_top_inviter_wallet text := null;
  v_top_inviter_invites_24h bigint := 0;
  v_top_inviter_share_pct numeric := 0;
  v_baseline_daily_invites numeric := 0;
  v_under_review_ratio_pct numeric := 0;
  v_accepted_missing_entry_proof bigint := 0;
  v_unresolved_sybil_after_vote bigint := 0;
  v_completed_missing_impact_evidence bigint := 0;
  v_completed_missing_raw_reward_events bigint := 0;
  v_completed_missing_raw_vote_event bigint := 0;
  v_eligible_missing_raw_evidence bigint := 0;
  v_stale_incomplete_reconciliation bigint := 0;
  v_payout_state_mismatches bigint := 0;
  v_accounting_mismatch_rounds bigint := 0;
  v_data_integrity_faults bigint := 0;
  v_alerts jsonb := '[]'::jsonb;
  v_metrics jsonb;
  v_severity text := 'NORMAL';
  v_alert_count integer := 0;
begin
  if p_network not in ('mainnet', 'testnet', 'testnet-staging') then
    raise exception 'Unsupported monitoring network: %', p_network;
  end if;

  if p_trigger_source not in ('VERCEL_CRON', 'MANUAL_OPERATOR', 'SYSTEM_TEST') then
    raise exception 'Unsupported monitoring trigger: %', p_trigger_source;
  end if;

  select
    count(*) filter (
      where i.created_at >= v_now - interval '24 hours'
    )::bigint,
    count(*) filter (
      where i.created_at >= v_now - interval '8 days'
        and i.created_at < v_now - interval '24 hours'
    )::bigint,
    count(*) filter (
      where i.invitee_wallet is not null
        and i.activated_at >= v_now - interval '24 hours'
        and i.activation_network = p_network
    )::bigint,
    count(*) filter (
      where i.status = 'UNDER_REVIEW'
        and i.activated_at >= v_now - interval '24 hours'
        and i.activation_network = p_network
    )::bigint,
    count(*) filter (
      where i.status = 'UNDER_REVIEW'
        and i.activation_network = p_network
    )::bigint
  into
    v_invites_24h,
    v_invites_prev_7d,
    v_claimed_24h,
    v_under_review_24h,
    v_open_under_review
  from public.invitations i;

  select ranked.inviter_wallet, ranked.invites_by_inviter
  into v_top_inviter_wallet, v_top_inviter_invites_24h
  from (
    select
      i.inviter_wallet,
      count(*)::bigint as invites_by_inviter
    from public.invitations i
    where i.created_at >= v_now - interval '24 hours'
    group by i.inviter_wallet
    order by count(*) desc, i.inviter_wallet asc
    limit 1
  ) ranked;

  v_top_inviter_invites_24h := coalesce(v_top_inviter_invites_24h, 0);
  v_baseline_daily_invites := round(v_invites_prev_7d::numeric / 7, 2);
  v_top_inviter_share_pct := case
    when v_invites_24h > 0 then
      round(v_top_inviter_invites_24h::numeric * 100 / v_invites_24h, 2)
    else 0
  end;
  v_under_review_ratio_pct := case
    when v_claimed_24h > 0 then
      round(v_under_review_24h::numeric * 100 / v_claimed_24h, 2)
    else 0
  end;

  select
    coalesce(q.accepted_missing_entry_proof, 0),
    coalesce(q.unresolved_sybil_after_vote, 0),
    coalesce(q.completed_missing_impact_evidence, 0),
    coalesce(q.completed_missing_raw_reward_events, 0),
    coalesce(q.completed_missing_raw_vote_event, 0),
    coalesce(q.eligible_missing_raw_evidence, 0),
    coalesce(q.stale_incomplete_reconciliation, 0),
    coalesce(q.payout_state_mismatches, 0)
  into
    v_accepted_missing_entry_proof,
    v_unresolved_sybil_after_vote,
    v_completed_missing_impact_evidence,
    v_completed_missing_raw_reward_events,
    v_completed_missing_raw_vote_event,
    v_eligible_missing_raw_evidence,
    v_stale_incomplete_reconciliation,
    v_payout_state_mismatches
  from public.operator_data_quality q
  where q.network = p_network;

  v_accepted_missing_entry_proof := coalesce(v_accepted_missing_entry_proof, 0);
  v_unresolved_sybil_after_vote := coalesce(v_unresolved_sybil_after_vote, 0);
  v_completed_missing_impact_evidence := coalesce(v_completed_missing_impact_evidence, 0);
  v_completed_missing_raw_reward_events := coalesce(v_completed_missing_raw_reward_events, 0);
  v_completed_missing_raw_vote_event := coalesce(v_completed_missing_raw_vote_event, 0);
  v_eligible_missing_raw_evidence := coalesce(v_eligible_missing_raw_evidence, 0);
  v_stale_incomplete_reconciliation := coalesce(v_stale_incomplete_reconciliation, 0);
  v_payout_state_mismatches := coalesce(v_payout_state_mismatches, 0);

  v_data_integrity_faults :=
    v_accepted_missing_entry_proof +
    v_unresolved_sybil_after_vote +
    v_completed_missing_impact_evidence +
    v_completed_missing_raw_reward_events +
    v_completed_missing_raw_vote_event +
    v_eligible_missing_raw_evidence +
    v_payout_state_mismatches;

  select count(*)::bigint
  into v_accounting_mismatch_rounds
  from public.operator_vebetter_round_accounting a
  where a.network = p_network
    and (
      (
        a.reward_round_status = 'COMPLETED'
        and a.accounting_status <> 'SETTLED'
      )
      or coalesce(a.paid_b3tr_wei, 0) > coalesce(a.distributable_wei, 0)
      or coalesce(a.paid_referral_rewards, 0) > coalesce(a.eligible_count, 0)
    );

  v_metrics := jsonb_build_object(
    'invites24h', v_invites_24h,
    'baselineDailyInvites', v_baseline_daily_invites,
    'claimed24h', v_claimed_24h,
    'underReview24h', v_under_review_24h,
    'underReviewRatioPct', v_under_review_ratio_pct,
    'openUnderReview', v_open_under_review,
    'topInviterInvites24h', v_top_inviter_invites_24h,
    'topInviterSharePct', v_top_inviter_share_pct,
    'topInviterWallet', v_top_inviter_wallet,
    'dataQuality', jsonb_build_object(
      'acceptedMissingEntryProof', v_accepted_missing_entry_proof,
      'unresolvedSybilAfterVote', v_unresolved_sybil_after_vote,
      'completedMissingImpactEvidence', v_completed_missing_impact_evidence,
      'completedMissingRawRewardEvents', v_completed_missing_raw_reward_events,
      'completedMissingRawVoteEvent', v_completed_missing_raw_vote_event,
      'eligibleMissingRawEvidence', v_eligible_missing_raw_evidence,
      'staleIncompleteReconciliation', v_stale_incomplete_reconciliation,
      'payoutStateMismatches', v_payout_state_mismatches
    ),
    'accountingMismatchRounds', v_accounting_mismatch_rounds,
    'thresholds', jsonb_build_object(
      'inviteSpikeMinimum24h', 10,
      'inviteSpikeBaselineMultiplier', 3,
      'concentrationMinimumInvites24h', 10,
      'concentrationMinimumTopInviterInvites24h', 5,
      'concentrationTopInviterSharePct', 50,
      'reviewRatioMinimumClaims24h', 5,
      'reviewRatioMinimumUnderReview24h', 3,
      'reviewRatioPct', 40,
      'reviewBacklog', 5,
      'staleReconciliation', 5
    )
  );

  if v_data_integrity_faults > 0 then
    v_alerts := v_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'DATA_INTEGRITY_FAULT',
        'severity', 'CRITICAL',
        'observed', v_data_integrity_faults,
        'message', 'One or more proof, mission-evidence, or payout-state invariants are inconsistent.'
      )
    );
  end if;

  if v_accounting_mismatch_rounds > 0 then
    v_alerts := v_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'REWARD_ACCOUNTING_MISMATCH',
        'severity', 'CRITICAL',
        'observed', v_accounting_mismatch_rounds,
        'message', 'A completed reward round is not fully settled or its paid totals exceed the prepared plan.'
      )
    );
  end if;

  if
    v_invites_24h >= 10
    and v_invites_24h >= greatest(10, ceil(v_baseline_daily_invites * 3)::bigint)
  then
    v_alerts := v_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'INVITE_VOLUME_SPIKE',
        'severity', 'WARNING',
        'observed', v_invites_24h,
        'baselineDaily', v_baseline_daily_invites,
        'message', 'Invitation creation is at least three times the trailing seven-day daily baseline.'
      )
    );
  end if;

  if
    v_invites_24h >= 10
    and v_top_inviter_invites_24h >= 5
    and v_top_inviter_share_pct >= 50
  then
    v_alerts := v_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'REFERRAL_CONCENTRATION',
        'severity', 'WARNING',
        'observedTopInviterInvites', v_top_inviter_invites_24h,
        'observedTopInviterSharePct', v_top_inviter_share_pct,
        'wallet', v_top_inviter_wallet,
        'message', 'One inviter accounts for at least half of recent invitation creation.'
      )
    );
  end if;

  if
    v_claimed_24h >= 5
    and v_under_review_24h >= 3
    and v_under_review_ratio_pct >= 40
  then
    v_alerts := v_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'UNDER_REVIEW_RATIO_SPIKE',
        'severity', 'WARNING',
        'observedClaims', v_claimed_24h,
        'observedUnderReview', v_under_review_24h,
        'observedRatioPct', v_under_review_ratio_pct,
        'message', 'A high share of recently claimed referrals is entering security review.'
      )
    );
  end if;

  if v_open_under_review >= 5 then
    v_alerts := v_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'REVIEW_BACKLOG',
        'severity', 'WARNING',
        'observed', v_open_under_review,
        'message', 'The number of open referrals awaiting security review has reached the review-backlog threshold.'
      )
    );
  end if;

  if v_stale_incomplete_reconciliation >= 5 then
    v_alerts := v_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'STALE_RECONCILIATION',
        'severity', 'WARNING',
        'observed', v_stale_incomplete_reconciliation,
        'message', 'Several accepted referrals have incomplete evidence reconciliation beyond the normal freshness window.'
      )
    );
  end if;

  v_alert_count := jsonb_array_length(v_alerts);
  v_severity := case
    when v_alerts @> '[{"severity":"CRITICAL"}]'::jsonb then 'CRITICAL'
    when v_alert_count > 0 then 'WARNING'
    else 'NORMAL'
  end;

  insert into public.operator_monitor_snapshots (
    network,
    trigger_source,
    severity,
    alert_count,
    metrics,
    alerts,
    captured_at
  ) values (
    p_network,
    p_trigger_source,
    v_severity,
    v_alert_count,
    v_metrics,
    v_alerts,
    v_now
  )
  returning id into snapshot_id;

  severity := v_severity;
  alert_count := v_alert_count;
  metrics := v_metrics;
  alerts := v_alerts;
  captured_at := v_now;

  return next;
end;
$$;

revoke all on function public.record_operator_anomaly_snapshot(text, text) from public, anon, authenticated;
grant execute on function public.record_operator_anomaly_snapshot(text, text) to service_role;
