begin;

create table if not exists public.sybil_v2_post_payout_reviews (
  invite_code text primary key
    references public.invitations(invite_code)
    on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  subject_wallet text not null
    check (subject_wallet ~ '^0x[0-9a-f]{40}$'),
  state text not null
    check (state in ('HOLD','CLEARED','RESTRICTED')),
  risk_score integer not null
    check (risk_score between 0 and 100),
  revision bigint not null default 1
    check (revision >= 1),
  reason_codes jsonb not null default '[]'::jsonb
    check (jsonb_typeof(reason_codes) = 'array'),
  evidence_summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(evidence_summary) = 'object'),
  evidence_digest text not null
    check (evidence_digest ~ '^[0-9a-f]{32}$'),
  source text not null default 'SYSTEM'
    check (source in ('SYSTEM','OPERATOR')),
  opened_at timestamptz not null default now(),
  resolved_at timestamptz,
  operator_wallet text
    check (operator_wallet is null or operator_wallet ~ '^0x[0-9a-f]{40}$'),
  operator_reason text,
  updated_at timestamptz not null default now(),
  check (
    (state = 'HOLD' and resolved_at is null)
    or
    (state in ('CLEARED','RESTRICTED') and resolved_at is not null)
  )
);

create index if not exists sybil_v2_post_payout_reviews_state_idx
  on public.sybil_v2_post_payout_reviews(
    network, state, updated_at
  );

create index if not exists sybil_v2_post_payout_reviews_subject_idx
  on public.sybil_v2_post_payout_reviews(
    network, subject_wallet, updated_at desc
  );

create table if not exists public.sybil_v2_post_payout_review_events (
  id bigint generated by default as identity primary key,
  invite_code text not null
    references public.invitations(invite_code)
    on update cascade on delete restrict,
  network text not null,
  subject_wallet text not null,
  action text not null
    check (action in ('OPENED','REOPENED','CLEARED','RESTRICTED')),
  risk_score integer not null
    check (risk_score between 0 and 100),
  revision bigint not null
    check (revision >= 1),
  reason_codes jsonb not null default '[]'::jsonb
    check (jsonb_typeof(reason_codes) = 'array'),
  evidence_summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(evidence_summary) = 'object'),
  evidence_digest text not null,
  source text not null
    check (source in ('SYSTEM','OPERATOR')),
  operator_wallet text,
  operator_reason text,
  created_at timestamptz not null default now(),
  unique(invite_code, revision)
);

create index if not exists sybil_v2_post_payout_review_events_invite_idx
  on public.sybil_v2_post_payout_review_events(
    invite_code, revision desc
  );

alter table public.sybil_v2_post_payout_reviews enable row level security;
alter table public.sybil_v2_post_payout_review_events enable row level security;

revoke all on public.sybil_v2_post_payout_reviews
  from public, anon, authenticated;
revoke all on public.sybil_v2_post_payout_review_events
  from public, anon, authenticated;

grant select, insert, update on public.sybil_v2_post_payout_reviews
  to service_role;
grant select, insert on public.sybil_v2_post_payout_review_events
  to service_role;
grant usage, select on sequence
  public.sybil_v2_post_payout_review_events_id_seq
  to service_role;

drop trigger if exists sybil_v2_post_payout_review_events_append_only
  on public.sybil_v2_post_payout_review_events;
create trigger sybil_v2_post_payout_review_events_append_only
before update or delete on public.sybil_v2_post_payout_review_events
for each row execute function public.prevent_sybil_v2_append_only_mutation();

create or replace function public.record_sybil_v2_post_payout_review(
  p_invite_code text,
  p_network text,
  p_subject_wallet text,
  p_risk_score integer,
  p_reason_codes jsonb,
  p_evidence_summary jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_code text := upper(btrim(p_invite_code));
  v_network text := lower(btrim(p_network));
  v_subject text := lower(btrim(p_subject_wallet));
  v_reason_codes jsonb := coalesce(p_reason_codes,'[]'::jsonb);
  v_summary jsonb := coalesce(p_evidence_summary,'{}'::jsonb);
  v_digest text;
  v_existing public.sybil_v2_post_payout_reviews%rowtype;
  v_invitation public.invitations%rowtype;
  v_revision bigint := 1;
  v_action text := 'OPENED';
  v_now timestamptz := clock_timestamp();
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'INVALID_NETWORK';
  end if;
  if v_subject !~ '^0x[0-9a-f]{40}$' then
    raise exception 'INVALID_SUBJECT_WALLET';
  end if;
  if p_risk_score is null or p_risk_score not between 0 and 100 then
    raise exception 'INVALID_POST_PAYOUT_RISK_SCORE';
  end if;
  if jsonb_typeof(v_reason_codes) <> 'array'
     or jsonb_typeof(v_summary) <> 'object' then
    raise exception 'INVALID_POST_PAYOUT_EVIDENCE_SHAPE';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_post_payout_review_' || v_code,0)
  );

  select * into v_invitation
  from public.invitations i
  where i.invite_code = v_code;

  if not found
     or v_invitation.activation_network <> v_network
     or lower(v_invitation.inviter_wallet) <> v_subject
     or v_invitation.reward_status <> 'PAID' then
    return jsonb_build_object(
      'changed', false,
      'reason', 'PAID_INVITER_AUTHORITY_MISMATCH'
    );
  end if;

  v_digest := md5(
    jsonb_build_object(
      'riskScore', p_risk_score,
      'reasonCodes', v_reason_codes,
      'evidenceSummary', v_summary
    )::text
  );

  select * into v_existing
  from public.sybil_v2_post_payout_reviews r
  where r.invite_code = v_code
  for update;

  if found then
    if v_existing.state = 'RESTRICTED' then
      return jsonb_build_object(
        'changed', false,
        'reason', 'ALREADY_RESTRICTED',
        'revision', v_existing.revision
      );
    end if;

    if v_existing.evidence_digest = v_digest then
      return jsonb_build_object(
        'changed', false,
        'reason', 'EVIDENCE_ALREADY_REVIEWED',
        'state', v_existing.state,
        'revision', v_existing.revision
      );
    end if;

    v_revision := v_existing.revision + 1;
    v_action := 'REOPENED';

    update public.sybil_v2_post_payout_reviews
    set
      network = v_network,
      subject_wallet = v_subject,
      state = 'HOLD',
      risk_score = p_risk_score,
      revision = v_revision,
      reason_codes = v_reason_codes,
      evidence_summary = v_summary,
      evidence_digest = v_digest,
      source = 'SYSTEM',
      opened_at = v_now,
      resolved_at = null,
      operator_wallet = null,
      operator_reason = null,
      updated_at = v_now
    where invite_code = v_code;
  else
    insert into public.sybil_v2_post_payout_reviews(
      invite_code, network, subject_wallet, state, risk_score,
      revision, reason_codes, evidence_summary, evidence_digest,
      source, opened_at, updated_at
    ) values (
      v_code, v_network, v_subject, 'HOLD', p_risk_score,
      v_revision, v_reason_codes, v_summary, v_digest,
      'SYSTEM', v_now, v_now
    );
  end if;

  insert into public.sybil_v2_post_payout_review_events(
    invite_code, network, subject_wallet, action, risk_score,
    revision, reason_codes, evidence_summary, evidence_digest,
    source, created_at
  ) values (
    v_code, v_network, v_subject, v_action, p_risk_score,
    v_revision, v_reason_codes, v_summary, v_digest,
    'SYSTEM', v_now
  );

  return jsonb_build_object(
    'changed', true,
    'reason', v_action,
    'state', 'HOLD',
    'revision', v_revision
  );
end;
$$;

create or replace function public.resolve_sybil_v2_post_payout_review(
  p_invite_code text,
  p_decision text,
  p_reason text,
  p_expected_revision bigint,
  p_operator_wallet text,
  p_network text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_code text := upper(btrim(p_invite_code));
  v_decision text := upper(btrim(p_decision));
  v_reason text := nullif(btrim(coalesce(p_reason,'')), '');
  v_operator text := lower(btrim(p_operator_wallet));
  v_network text := lower(btrim(p_network));
  v_review public.sybil_v2_post_payout_reviews%rowtype;
  v_next_state text;
  v_action text;
  v_revision bigint;
  v_now timestamptz := clock_timestamp();
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;
  if v_decision not in ('CLEAR','BLACKLIST') then
    raise exception 'INVALID_POST_PAYOUT_REVIEW_DECISION';
  end if;
  if v_reason is null or length(v_reason) < 12 or length(v_reason) > 500 then
    raise exception 'POST_PAYOUT_REVIEW_REASON_LENGTH';
  end if;
  if p_expected_revision is null or p_expected_revision < 1 then
    raise exception 'INVALID_POST_PAYOUT_REVIEW_REVISION';
  end if;
  if v_operator !~ '^0x[0-9a-f]{40}$' then
    raise exception 'INVALID_OPERATOR_WALLET';
  end if;
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'INVALID_NETWORK';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_post_payout_review_' || v_code,0)
  );

  select * into v_review
  from public.sybil_v2_post_payout_reviews r
  where r.invite_code = v_code
  for update;

  if not found then
    raise exception 'POST_PAYOUT_REVIEW_NOT_FOUND';
  end if;
  if v_review.network <> v_network then
    raise exception 'POST_PAYOUT_REVIEW_NETWORK_MISMATCH';
  end if;
  if v_review.revision <> p_expected_revision then
    raise exception 'POST_PAYOUT_REVIEW_STATE_CHANGED';
  end if;
  if v_review.state <> 'HOLD' then
    raise exception 'POST_PAYOUT_REVIEW_NOT_HOLD';
  end if;

  v_revision := v_review.revision + 1;

  if v_decision = 'BLACKLIST' then
    if not exists (
      select 1
      from public.sybil_v2_wallet_restrictions r
      where r.network = v_network
        and r.wallet_address = v_review.subject_wallet
        and r.status = 'ACTIVE'
    ) then
      insert into public.sybil_v2_wallet_restrictions(
        wallet_address, network, status, reason_codes,
        evidence_summary, source, related_invite_code, imposed_at
      ) values (
        v_review.subject_wallet,
        v_network,
        'ACTIVE',
        v_review.reason_codes || jsonb_build_array('POST_PAYOUT_OPERATOR_BLACKLIST'),
        v_review.evidence_summary || jsonb_build_object(
          'operatorReason', v_reason,
          'operatorWallet', v_operator,
          'operatorDecision', 'BLACKLIST',
          'restrictionScope', 'REWARD_RECIPIENT_ONLY'
        ),
        'OPERATOR',
        v_code,
        v_now
      );
    end if;

    v_next_state := 'RESTRICTED';
    v_action := 'RESTRICTED';
  else
    v_next_state := 'CLEARED';
    v_action := 'CLEARED';
  end if;

  update public.sybil_v2_post_payout_reviews
  set
    state = v_next_state,
    revision = v_revision,
    source = 'OPERATOR',
    resolved_at = v_now,
    operator_wallet = v_operator,
    operator_reason = v_reason,
    updated_at = v_now
  where invite_code = v_code
  returning * into v_review;

  insert into public.sybil_v2_post_payout_review_events(
    invite_code, network, subject_wallet, action, risk_score,
    revision, reason_codes, evidence_summary, evidence_digest,
    source, operator_wallet, operator_reason, created_at
  ) values (
    v_review.invite_code,
    v_review.network,
    v_review.subject_wallet,
    v_action,
    v_review.risk_score,
    v_review.revision,
    v_review.reason_codes,
    v_review.evidence_summary,
    v_review.evidence_digest,
    'OPERATOR',
    v_operator,
    v_reason,
    v_now
  );

  return jsonb_build_object(
    'changed', true,
    'decision', v_decision,
    'state', v_next_state,
    'revision', v_revision,
    'restrictedWallet',
      case when v_next_state = 'RESTRICTED'
        then v_review.subject_wallet
        else null
      end,
    'pastRewardChanged', false
  );
end;
$$;

revoke all on function public.record_sybil_v2_post_payout_review(
  text,text,text,integer,jsonb,jsonb
) from public, anon, authenticated;
grant execute on function public.record_sybil_v2_post_payout_review(
  text,text,text,integer,jsonb,jsonb
) to service_role;

revoke all on function public.resolve_sybil_v2_post_payout_review(
  text,text,text,bigint,text,text
) from public, anon, authenticated;
grant execute on function public.resolve_sybil_v2_post_payout_review(
  text,text,text,bigint,text,text
) to service_role;

commit;
