-- VeInvite audited data-integrity foundation.
--
-- This migration makes accepted-user evidence, Sybil decisions and weekly
-- impact provenance auditable and removes reward-schema assumptions that are
-- unsafe at scale. It does not transfer B3TR.

begin;

-- Persist the exact network and the entry-eligibility check that admitted an
-- invitee. Sync watermark fields are used by later reconciliation/reporting.
alter table public.invitations
  add column if not exists activation_network text,
  add column if not exists eligibility_check_id bigint,
  add column if not exists impact_last_synced_block bigint,
  add column if not exists impact_last_synced_at timestamptz,
  add column if not exists impact_sync_complete_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'invitations_activation_network_check'
  ) then
    alter table public.invitations
      add constraint invitations_activation_network_check
      check (
        activation_network is null
        or activation_network in ('mainnet', 'testnet', 'testnet-staging')
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'invitations_impact_sync_block_check'
  ) then
    alter table public.invitations
      add constraint invitations_impact_sync_block_check
      check (
        impact_last_synced_block is null
        or (
          impact_last_synced_block >= 0
          and (
            activation_block is null
            or impact_last_synced_block >= activation_block
          )
        )
      );
  end if;
end
$$;

create table if not exists public.eligibility_check_events (
  id bigint generated by default as identity primary key,
  invite_code text not null
    references public.invitations(invite_code)
    on update cascade
    on delete restrict,
  wallet_address text not null,
  network text not null,
  checked_block bigint not null,
  outcome text not null,
  prior_reward_tx_id text,
  prior_vote_tx_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint eligibility_check_events_wallet_check
    check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  constraint eligibility_check_events_network_check
    check (network in ('mainnet', 'testnet', 'testnet-staging')),
  constraint eligibility_check_events_block_check
    check (checked_block >= 0),
  constraint eligibility_check_events_outcome_check
    check (
      outcome in (
        'ELIGIBLE',
        'EXISTING_VEBETTER_USER',
        'REVIEW',
        'REJECTED'
      )
    ),
  constraint eligibility_check_events_reward_tx_check
    check (
      prior_reward_tx_id is null
      or prior_reward_tx_id ~ '^0x[0-9a-f]{64}$'
    ),
  constraint eligibility_check_events_vote_tx_check
    check (
      prior_vote_tx_id is null
      or prior_vote_tx_id ~ '^0x[0-9a-f]{64}$'
    ),
  constraint eligibility_check_events_details_check
    check (jsonb_typeof(details) = 'object')
);

create index if not exists eligibility_check_events_invite_created_idx
  on public.eligibility_check_events(invite_code, created_at desc);
create index if not exists eligibility_check_events_wallet_created_idx
  on public.eligibility_check_events(wallet_address, created_at desc);

alter table public.eligibility_check_events enable row level security;
revoke all on table public.eligibility_check_events
  from public, anon, authenticated;
grant select, insert on table public.eligibility_check_events
  to service_role;
grant usage, select on sequence public.eligibility_check_events_id_seq
  to service_role;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'invitations_eligibility_check_id_fkey'
  ) then
    alter table public.invitations
      add constraint invitations_eligibility_check_id_fkey
      foreign key (eligibility_check_id)
      references public.eligibility_check_events(id)
      on delete restrict;
  end if;
end
$$;

-- Audit ledgers are append-only. Application code may append facts but may not
-- silently rewrite the history used for operator answers or public reports.
create or replace function public.prevent_operator_ledger_mutation()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception '% is append-only', tg_table_name;
end;
$$;

revoke all on function public.prevent_operator_ledger_mutation()
  from public, anon, authenticated;

revoke update, delete, truncate on table public.sybil_review_events
  from service_role;
revoke update, delete, truncate on table public.invite_impact_events
  from service_role;
revoke update, delete, truncate on table public.eligibility_check_events
  from service_role;

drop trigger if exists sybil_review_events_append_only
  on public.sybil_review_events;
create trigger sybil_review_events_append_only
before update or delete on public.sybil_review_events
for each row execute function public.prevent_operator_ledger_mutation();

drop trigger if exists invite_impact_events_append_only
  on public.invite_impact_events;
create trigger invite_impact_events_append_only
before update or delete on public.invite_impact_events
for each row execute function public.prevent_operator_ledger_mutation();

drop trigger if exists eligibility_check_events_append_only
  on public.eligibility_check_events;
create trigger eligibility_check_events_append_only
before update or delete on public.eligibility_check_events
for each row execute function public.prevent_operator_ledger_mutation();

-- An impact event must describe the same invitation, invitee and network, and
-- must occur on-chain after the invitation boundary.
create or replace function public.validate_invite_impact_event()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_invitee text;
  v_activation_block bigint;
  v_activation_network text;
  v_apps_completed_block bigint;
begin
  select
    invitee_wallet,
    activation_block,
    activation_network,
    apps_completed_block
  into
    v_invitee,
    v_activation_block,
    v_activation_network,
    v_apps_completed_block
  from public.invitations
  where invite_code = new.invite_code;

  if not found then
    raise exception 'Invitation % does not exist', new.invite_code;
  end if;

  if v_invitee is null
     or lower(v_invitee) <> lower(new.wallet_address) then
    raise exception 'Impact wallet does not match invitation %', new.invite_code;
  end if;

  if v_activation_network is null
     or lower(v_activation_network) <> lower(new.network) then
    raise exception 'Impact network does not match invitation %', new.invite_code;
  end if;

  if v_activation_block is null
     or new.block_number < v_activation_block then
    raise exception 'Impact block predates invitation activation %', new.invite_code;
  end if;

  if new.event_type = 'ALLOCATION_VOTE'
     and (
       v_apps_completed_block is null
       or new.block_number < v_apps_completed_block
     ) then
    raise exception
      'Vote impact predates three-app checkpoint for invitation %',
      new.invite_code;
  end if;

  return new;
end;
$$;

revoke all on function public.validate_invite_impact_event()
  from public, anon, authenticated;

drop trigger if exists invite_impact_events_validate
  on public.invite_impact_events;
create trigger invite_impact_events_validate
before insert on public.invite_impact_events
for each row execute function public.validate_invite_impact_event();

create unique index if not exists invite_impact_events_one_reward_per_app_idx
  on public.invite_impact_events(invite_code, app_id)
  where event_type = 'DAPP_REWARD';
create unique index if not exists invite_impact_events_one_vote_per_invite_idx
  on public.invite_impact_events(invite_code)
  where event_type = 'ALLOCATION_VOTE';

-- One on-chain payout transaction may later contain multiple clauses / settle
-- multiple per-invite rows, so tx_id must not be globally unique.
drop index if exists public.reward_payouts_invite_once;
drop index if exists public.reward_payouts_tx_unique;
drop index if exists public.reward_payouts_tx_id_uidx;
create index if not exists reward_payouts_tx_idx
  on public.reward_payouts(tx_id)
  where tx_id is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'reward_payouts_tx_id_check'
  ) then
    alter table public.reward_payouts
      add constraint reward_payouts_tx_id_check
      check (
        tx_id is null
        or tx_id ~ '^0x[0-9a-f]{64}$'
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reward_payouts_integer_wei_check'
  ) then
    alter table public.reward_payouts
      add constraint reward_payouts_integer_wei_check
      check (amount_wei = trunc(amount_wei));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reward_payouts_paid_shape_check'
  ) then
    alter table public.reward_payouts
      add constraint reward_payouts_paid_shape_check
      check (
        (
          status = 'PAID'
          and tx_id is not null
          and paid_at is not null
        )
        or (
          status <> 'PAID'
          and paid_at is null
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reward_rounds_network_check'
  ) then
    alter table public.reward_rounds
      add constraint reward_rounds_network_check
      check (network in ('mainnet', 'testnet', 'testnet-staging'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reward_rounds_app_id_check'
  ) then
    alter table public.reward_rounds
      add constraint reward_rounds_app_id_check
      check (app_id ~ '^0x[0-9a-f]{64}$');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'reward_rounds_integer_wei_check'
  ) then
    alter table public.reward_rounds
      add constraint reward_rounds_integer_wei_check
      check (
        observed_pool_balance_wei = trunc(observed_pool_balance_wei)
        and reserved_before_round_wei = trunc(reserved_before_round_wei)
        and distributable_wei = trunc(distributable_wei)
        and per_reward_wei = trunc(per_reward_wei)
        and remainder_wei = trunc(remainder_wei)
      );
  end if;
end
$$;

-- PAID is derived from an actual paid payout. A caller cannot promote an
-- invitation by only editing reward_status.
create or replace function public.sync_invitation_reward_eligibility()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_has_paid_payout boolean := false;
  v_has_eligible_entry_check boolean := false;
begin
  select exists(
    select 1
    from public.reward_payouts rp
    where rp.invite_code = new.invite_code
      and rp.status = 'PAID'
      and rp.tx_id is not null
      and rp.paid_at is not null
  ) into v_has_paid_payout;

  if v_has_paid_payout then
    new.reward_status := 'PAID';

    if new.reward_paid_at is null then
      select rp.paid_at
      into new.reward_paid_at
      from public.reward_payouts rp
      where rp.invite_code = new.invite_code
        and rp.status = 'PAID'
      order by rp.paid_at desc
      limit 1;
    end if;

    return new;
  end if;

  new.reward_paid_at := null;

  if new.status = 'CANCELLED'
     or new.sybil_status = 'BLOCKED' then
    new.reward_status := 'FORFEITED';
    new.reward_eligible_at := null;
    return new;
  end if;

  if new.invitee_wallet is null
     or new.activation_block is null
     or new.activation_network is null
     or coalesce(new.apps_completed, 0) < 3
     or new.apps_completed_block is null
     or new.apps_completed_block < new.activation_block then
    new.apps_completed_at := null;
    new.apps_completed_block := null;
    new.vote_completed := false;
    new.vote_completed_at := null;
    new.vote_completed_block := null;
    new.vote_round_id := null;
  else
    if coalesce(new.vote_completed, false) = false
       or new.vote_completed_at is null
       or new.vote_completed_block is null
       or new.vote_round_id is null
       or new.vote_completed_block < new.apps_completed_block then
      new.vote_completed := false;
      new.vote_completed_at := null;
      new.vote_completed_block := null;
      new.vote_round_id := null;
    end if;
  end if;

  if new.eligibility_check_id is not null then
    select exists(
      select 1
      from public.eligibility_check_events e
      where e.id = new.eligibility_check_id
        and e.invite_code = new.invite_code
        and e.wallet_address = lower(new.invitee_wallet)
        and e.network = new.activation_network
        and e.outcome = 'ELIGIBLE'
        and e.checked_block <= new.activation_block
    ) into v_has_eligible_entry_check;
  end if;

  if new.status = 'COMPLETED'
     and v_has_eligible_entry_check
     and new.invitee_wallet is not null
     and new.activation_block is not null
     and new.activation_network is not null
     and coalesce(new.apps_completed, 0) >= 3
     and new.apps_completed_block is not null
     and new.apps_completed_block >= new.activation_block
     and coalesce(new.vote_completed, false) = true
     and new.vote_completed_at is not null
     and new.vote_completed_block is not null
     and new.vote_round_id is not null
     and new.vote_completed_block >= new.apps_completed_block
     and new.sybil_status = 'CLEAR'
     and new.sybil_checked_at is not null
     and new.sybil_checked_at >= new.vote_completed_at then
    new.reward_status := 'ELIGIBLE';
    new.reward_eligible_at := coalesce(
      new.reward_eligible_at,
      new.sybil_checked_at,
      new.vote_completed_at,
      now()
    );
  elsif new.invitee_wallet is not null then
    new.reward_status := 'PENDING';
    new.reward_eligible_at := null;
  else
    new.reward_status := 'NONE';
    new.reward_eligible_at := null;
  end if;

  return new;
end;
$$;

-- A real paid payout atomically updates the invitation settlement state.
create or replace function public.sync_paid_payout_to_invitation()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.status = 'PAID' then
    update public.invitations
    set
      reward_status = 'PAID',
      reward_paid_at = new.paid_at
    where invite_code = new.invite_code;
  end if;

  return new;
end;
$$;

revoke all on function public.sync_paid_payout_to_invitation()
  from public, anon, authenticated;

drop trigger if exists reward_payouts_sync_invitation_paid
  on public.reward_payouts;
create trigger reward_payouts_sync_invitation_paid
after insert or update of status, tx_id, paid_at
on public.reward_payouts
for each row
when (new.status = 'PAID')
execute function public.sync_paid_payout_to_invitation();

-- Reward-round candidates are explicitly CLEAR, entry-eligible invitations
-- from the same network as the pool being settled.
create or replace function public.prepare_reward_round(
  p_network text,
  p_app_id text,
  p_pool_balance_wei numeric
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate_codes text[] := array[]::text[];
  v_eligible_count integer;
  v_reserved_existing numeric(78, 0);
  v_available_to_reserve numeric(78, 0);
  v_per_reward numeric(78, 0);
  v_remainder numeric(78, 0);
  v_round_id bigint;
  v_invalid_wallet_code text;
begin
  if p_pool_balance_wei is null
     or p_pool_balance_wei <= 0
     or p_pool_balance_wei <> trunc(p_pool_balance_wei) then
    return null;
  end if;

  p_network := lower(btrim(p_network));
  p_app_id := lower(p_app_id);

  if p_network not in ('mainnet', 'testnet', 'testnet-staging') then
    raise exception 'unsupported network';
  end if;

  if p_app_id is null
     or p_app_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'app_id must be a 32-byte hex value';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_round_' || p_network || '_' || p_app_id,
      0
    )
  );

  select coalesce(sum(rp.amount_wei), 0)
  into v_reserved_existing
  from public.reward_payouts rp
  join public.reward_rounds rr
    on rr.id = rp.round_id
  where rp.status in ('PENDING', 'SENDING', 'FAILED')
    and rr.network = p_network
    and rr.app_id = p_app_id;

  v_available_to_reserve := greatest(
    p_pool_balance_wei - v_reserved_existing,
    0
  );

  if v_available_to_reserve <= 0 then
    return null;
  end if;

  select coalesce(
    array_agg(c.invite_code order by c.reward_eligible_at, c.invite_code),
    array[]::text[]
  )
  into v_candidate_codes
  from (
    select i.invite_code, i.reward_eligible_at
    from public.invitations i
    where i.status = 'COMPLETED'
      and i.reward_status = 'ELIGIBLE'
      and i.reward_eligible_at is not null
      and i.sybil_status = 'CLEAR'
      and i.activation_network = p_network
      and i.eligibility_check_id is not null
      and not exists (
        select 1
        from public.reward_payouts rp
        where rp.invite_code = i.invite_code
      )
    order by i.reward_eligible_at, i.invite_code
    for update of i
  ) c;

  v_eligible_count := coalesce(cardinality(v_candidate_codes), 0);

  if v_eligible_count = 0 then
    return null;
  end if;

  select i.invite_code
  into v_invalid_wallet_code
  from public.invitations i
  where i.invite_code = any(v_candidate_codes)
    and (
      i.inviter_wallet is null
      or lower(i.inviter_wallet) !~ '^0x[0-9a-f]{40}$'
    )
  limit 1;

  if v_invalid_wallet_code is not null then
    raise exception
      'invalid inviter wallet for invite %',
      v_invalid_wallet_code;
  end if;

  v_per_reward := floor(
    v_available_to_reserve / v_eligible_count
  );

  if v_per_reward < 1 then
    return null;
  end if;

  v_remainder :=
    v_available_to_reserve
    - (v_per_reward * v_eligible_count);

  insert into public.reward_rounds (
    network,
    app_id,
    status,
    observed_pool_balance_wei,
    reserved_before_round_wei,
    distributable_wei,
    eligible_count,
    per_reward_wei,
    remainder_wei
  ) values (
    p_network,
    p_app_id,
    'CREATED',
    p_pool_balance_wei,
    v_reserved_existing,
    v_per_reward * v_eligible_count,
    v_eligible_count,
    v_per_reward,
    v_remainder
  )
  returning id into v_round_id;

  insert into public.reward_payouts (
    round_id,
    invite_code,
    recipient_wallet,
    amount_wei,
    status
  )
  select
    v_round_id,
    i.invite_code,
    lower(i.inviter_wallet),
    v_per_reward,
    'PENDING'
  from public.invitations i
  where i.invite_code = any(v_candidate_codes)
  order by i.reward_eligible_at, i.invite_code;

  return v_round_id;
end;
$$;

revoke all on function public.prepare_reward_round(text, text, numeric)
  from public, anon, authenticated;
grant execute on function public.prepare_reward_round(text, text, numeric)
  to service_role;

commit;
