begin;

create table if not exists public.sybil_v2_watch_followup_observations (
  id uuid primary key default gen_random_uuid(),
  invite_code text not null
    references public.invitations(invite_code)
    on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  subject_wallet text not null
    check (subject_wallet ~ '^0x[0-9a-f]{40}$'),
  horizon_hours integer not null
    check (horizon_hours in (24,168,720)),
  scan_from_block bigint not null
    check (scan_from_block >= 0),
  scan_to_block bigint not null
    check (scan_to_block >= scan_from_block),
  outgoing_transfer_count integer not null default 0
    check (outgoing_transfer_count >= 0),
  suspicious_destination_count integer not null default 0
    check (suspicious_destination_count >= 0),
  indicators jsonb not null default '[]'::jsonb
    check (jsonb_typeof(indicators) = 'array'),
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(invite_code, horizon_hours)
);

create index if not exists sybil_v2_watch_followup_subject_idx
  on public.sybil_v2_watch_followup_observations(
    network, subject_wallet, checked_at desc
  );

alter table public.sybil_v2_watch_followup_observations enable row level security;
revoke all on public.sybil_v2_watch_followup_observations
  from public, anon, authenticated;
grant select, insert on public.sybil_v2_watch_followup_observations
  to service_role;

drop trigger if exists sybil_v2_watch_followup_observations_append_only
  on public.sybil_v2_watch_followup_observations;
create trigger sybil_v2_watch_followup_observations_append_only
before update or delete on public.sybil_v2_watch_followup_observations
for each row execute function public.prevent_sybil_v2_append_only_mutation();

comment on table public.sybil_v2_watch_followup_observations is
  'Append-only 24h/7d/30d same-subject follow-up observations for invitee wallets that passed Sybil v2 as WATCH. Observation never changes a paid reward or creates a restriction by itself.';

create table if not exists public.sybil_v2_watch_followup_outflows (
  id bigint generated by default as identity primary key,
  invite_code text not null
    references public.invitations(invite_code)
    on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  subject_wallet text not null
    check (subject_wallet ~ '^0x[0-9a-f]{40}$'),
  destination_wallet text not null
    check (destination_wallet ~ '^0x[0-9a-f]{40}$'),
  block_number bigint not null
    check (block_number >= 0),
  block_timestamp timestamptz,
  tx_id text not null
    check (tx_id ~ '^0x[0-9a-f]{64}$'),
  amount_wei numeric(78,0) not null
    check (amount_wei > 0),
  first_observed_horizon_hours integer not null
    check (first_observed_horizon_hours in (24,168,720)),
  created_at timestamptz not null default now(),
  unique(invite_code, tx_id, destination_wallet, amount_wei)
);

create index if not exists sybil_v2_watch_followup_outflows_destination_idx
  on public.sybil_v2_watch_followup_outflows(
    network, destination_wallet, block_number
  );
create index if not exists sybil_v2_watch_followup_outflows_subject_idx
  on public.sybil_v2_watch_followup_outflows(
    network, subject_wallet, block_number
  );

alter table public.sybil_v2_watch_followup_outflows enable row level security;
revoke all on public.sybil_v2_watch_followup_outflows
  from public, anon, authenticated;
grant select, insert on public.sybil_v2_watch_followup_outflows
  to service_role;
grant usage, select on sequence
  public.sybil_v2_watch_followup_outflows_id_seq
  to service_role;

drop trigger if exists sybil_v2_watch_followup_outflows_append_only
  on public.sybil_v2_watch_followup_outflows;
create trigger sybil_v2_watch_followup_outflows_append_only
before update or delete on public.sybil_v2_watch_followup_outflows
for each row execute function public.prevent_sybil_v2_append_only_mutation();

comment on table public.sybil_v2_watch_followup_outflows is
  'Append-only B3TR outflows observed from the WATCH invitee itself after its WATCH assessment. These rows are monitoring evidence only and never auto-blacklist a wallet.';

create table if not exists public.sybil_v2_cluster_hub_allowlist (
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  wallet_address text not null
    check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  reason text not null
    check (length(reason) between 3 and 300),
  source text not null default 'SYSTEM'
    check (source in ('SYSTEM','OPERATOR')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(network, wallet_address)
);

alter table public.sybil_v2_cluster_hub_allowlist enable row level security;
revoke all on public.sybil_v2_cluster_hub_allowlist
  from public, anon, authenticated;
grant select, insert, update, delete on public.sybil_v2_cluster_hub_allowlist
  to service_role;

comment on table public.sybil_v2_cluster_hub_allowlist is
  'Known protocol/service destinations excluded from automatic B3TR concentration-hub candidate detection. Operator additions are allowed after verification.';

insert into public.sybil_v2_cluster_hub_allowlist(
  network, wallet_address, reason, source
) values
  ('mainnet','0x0000000000000000000000000000000000000000','zero address','SYSTEM'),
  ('mainnet','0x5ef79995fe8a89e0812330e4378eb2660cede699','reviewed B3TR contract','SYSTEM'),
  ('mainnet','0x76ca782b59c74d088c7d2cce2f211bc00836c602','reviewed VOT3 contract','SYSTEM'),
  ('mainnet','0x8392b7ccc763db03b47afcd8e8f5e24f9cf0554d','reviewed x2EarnApps contract','SYSTEM'),
  ('mainnet','0x6bee7ddab6c99d5b2af0554eaea484ce18f52631','reviewed x2EarnRewardsPool contract','SYSTEM'),
  ('mainnet','0x89a00bb0947a30ff95beef77a66aede3842fe5b7','reviewed xAllocationVoting contract','SYSTEM'),
  ('testnet','0x0000000000000000000000000000000000000000','zero address','SYSTEM'),
  ('testnet','0x026771d1be764467f8bdb78bb230df10c924b00d','reviewed B3TR contract','SYSTEM'),
  ('testnet','0xf7a08af15cb3501feee53ebe11f4428a966fa459','reviewed VOT3 contract','SYSTEM'),
  ('testnet','0x1ae6eee231bcf8229d42626b4d663d45a6abd889','reviewed x2EarnApps contract','SYSTEM'),
  ('testnet','0x23bca0fa2e0028c09bd962ec7f521e84b3b2561a','reviewed x2EarnRewardsPool contract','SYSTEM'),
  ('testnet','0xe3c043786e991bd446be5242e79dff757fbda348','reviewed xAllocationVoting contract','SYSTEM'),
  ('testnet-staging','0x0000000000000000000000000000000000000000','zero address','SYSTEM'),
  ('testnet-staging','0x95761346d18244bb91664181bf91193376197088','reviewed B3TR contract','SYSTEM'),
  ('testnet-staging','0x6e8b4a88d37897fc11f6ba12c805695f1c41f40e','reviewed VOT3 contract','SYSTEM'),
  ('testnet-staging','0x0b54a094b877a25bdc95b4431eaa1e2206b1ddfe','reviewed x2EarnApps contract','SYSTEM'),
  ('testnet-staging','0x2d2a2207c68a46fc79325d7718e639d1047b0d8b','reviewed x2EarnRewardsPool contract','SYSTEM'),
  ('testnet-staging','0x8800592c463f0b21ae08732559ee8e146db1d7b2','reviewed xAllocationVoting contract','SYSTEM')
on conflict (network, wallet_address) do nothing;

create or replace view public.operator_sybil_v2_watch_followup_due
with (security_invoker = true)
as
select
  a.invite_code,
  a.network,
  lower(i.inviter_wallet) as inviter_wallet,
  lower(i.invitee_wallet) as subject_wallet,
  a.updated_at as watch_started_at,
  h.horizon_hours,
  a.updated_at + make_interval(hours => h.horizon_hours) as due_at,
  greatest(
    coalesce(
      last_observation.last_scan_to_block + 1,
      greatest(
        coalesce(
          a.evidence_cutoff_block,
          i.vote_completed_block,
          i.activation_block,
          0
        ) + 1,
        0
      )
    ),
    0
  )::bigint as scan_from_block
from public.sybil_v2_referral_assessments a
join public.invitations i
  on i.invite_code = a.invite_code
 and i.activation_network = a.network
left join lateral (
  select max(o.scan_to_block)::bigint as last_scan_to_block
  from public.sybil_v2_watch_followup_observations o
  where o.invite_code = a.invite_code
    and o.network = a.network
) last_observation on true
cross join lateral (
  select v.horizon_hours
  from (values (24),(168),(720)) as v(horizon_hours)
  where a.updated_at + make_interval(hours => v.horizon_hours) <= clock_timestamp()
    and not exists (
      select 1
      from public.sybil_v2_watch_followup_observations o
      where o.invite_code = a.invite_code
        and o.network = a.network
        and o.horizon_hours = v.horizon_hours
    )
  order by v.horizon_hours
  limit 1
) h
where public.sybil_v2_enforcement_enabled()
  and a.state = 'WATCH'
  and i.invitee_wallet is not null
  and i.inviter_wallet is not null;

revoke all on public.operator_sybil_v2_watch_followup_due
  from public, anon, authenticated;
grant select on public.operator_sybil_v2_watch_followup_due
  to service_role;

comment on view public.operator_sybil_v2_watch_followup_due is
  'Service-only scheduler for same-subject WATCH follow-up at 24h, 7d, and 30d. The subject is always the invitee wallet that received the WATCH verdict, never the inviter reward recipient.';

create or replace view public.operator_sybil_v2_cluster_hub_candidates
with (security_invoker = true)
as
with flows as (
  select
    h.network,
    h.invite_code,
    lower(h.wallet_address) as sender_wallet,
    lower(h.destination_wallet) as wallet_address,
    h.block_number,
    coalesce(h.block_timestamp, h.created_at) as observed_at
  from public.sybil_v2_preactivation_b3tr_outflows h

  union all

  select
    f.network,
    f.invite_code,
    lower(f.subject_wallet) as sender_wallet,
    lower(f.destination_wallet) as wallet_address,
    f.block_number,
    coalesce(f.block_timestamp, f.created_at) as observed_at
  from public.sybil_v2_watch_followup_outflows f
),
eligible_flows as (
  select distinct
    f.network,
    f.invite_code,
    f.sender_wallet,
    f.wallet_address,
    f.block_number,
    f.observed_at
  from flows f
  where f.sender_wallet <> f.wallet_address
    and not exists (
      select 1
      from public.sybil_v2_cluster_hub_allowlist a
      where a.network = f.network
        and a.wallet_address = f.wallet_address
    )
),
classified as (
  select
    f.*,
    exists (
      select 1
      from public.sybil_v2_wallet_restrictions r
      where r.network = f.network
        and r.wallet_address = f.sender_wallet
        and r.status = 'ACTIVE'
    ) as active_blacklisted_sender,
    exists (
      select 1
      from public.sybil_v2_referral_assessments a
      where a.invite_code = f.invite_code
        and a.network = f.network
        and a.state in ('WATCH','HOLD','RESTRICTED')
    ) as watched_sender,
    exists (
      select 1
      from public.invitations i
      where i.invite_code = f.invite_code
        and i.status = 'COMPLETED'
    ) as completed_sender
  from eligible_flows f
),
aggregated as (
  select
    network,
    wallet_address,
    count(distinct sender_wallet)::bigint as sender_count,
    count(distinct sender_wallet) filter (
      where active_blacklisted_sender
    )::bigint as active_blacklisted_sender_count,
    count(distinct sender_wallet) filter (
      where watched_sender
    )::bigint as watched_sender_count,
    count(distinct sender_wallet) filter (
      where completed_sender
    )::bigint as completed_sender_count,
    count(distinct invite_code)::bigint as invite_count,
    min(observed_at) as first_seen_at,
    max(observed_at) as last_seen_at
  from classified
  group by network, wallet_address
)
select
  a.network,
  a.wallet_address,
  'WATCH'::text as state,
  case
    when a.active_blacklisted_sender_count >= 3
      or a.sender_count >= 20 then 'PRIORITY'
    when a.active_blacklisted_sender_count >= 1
      or a.watched_sender_count >= 3
      or a.sender_count >= 10 then 'HIGH'
    else 'WATCH'
  end::text as priority,
  a.sender_count,
  a.active_blacklisted_sender_count,
  a.watched_sender_count,
  a.completed_sender_count,
  a.invite_count,
  a.first_seen_at,
  a.last_seen_at,
  jsonb_build_object(
    'senderCount', a.sender_count,
    'activeBlacklistedSenderCount', a.active_blacklisted_sender_count,
    'watchedSenderCount', a.watched_sender_count,
    'completedSenderCount', a.completed_sender_count,
    'inviteCount', a.invite_count,
    'automaticRestriction', false,
    'operatorReviewRequiredBeforeAllowlistOrRestriction', true
  ) as evidence_summary
from aggregated a
where a.sender_count >= 3
  and (
    a.active_blacklisted_sender_count >= 1
    or a.watched_sender_count >= 2
    or a.sender_count >= 5
  );

revoke all on public.operator_sybil_v2_cluster_hub_candidates
  from public, anon, authenticated;
grant select on public.operator_sybil_v2_cluster_hub_candidates
  to service_role;

comment on view public.operator_sybil_v2_cluster_hub_candidates is
  'Service-only automatic B3TR concentration-hub watchlist. Hub linkage is monitoring evidence only: it never blacklists, restricts, invalidates a referral, or blocks a reward by itself.';

create or replace view public.operator_sybil_v2_watch_followup_flags
with (security_invoker = true)
as
select
  o.id,
  o.invite_code,
  o.network,
  o.subject_wallet,
  o.horizon_hours,
  o.scan_from_block,
  o.scan_to_block,
  o.outgoing_transfer_count,
  o.suspicious_destination_count,
  o.indicators,
  o.checked_at
from public.sybil_v2_watch_followup_observations o
where o.suspicious_destination_count > 0;

revoke all on public.operator_sybil_v2_watch_followup_flags
  from public, anon, authenticated;
grant select on public.operator_sybil_v2_watch_followup_flags
  to service_role;

comment on view public.operator_sybil_v2_watch_followup_flags is
  'Service-only WATCH follow-up findings that deserve operator attention. Findings do not create restrictions automatically.';

create or replace view public.operator_sybil_v2_historical_watch_followups
with (security_invoker = true)
as
select
  a.invite_code,
  a.network,
  lower(i.inviter_wallet) as inviter_wallet,
  lower(i.invitee_wallet) as wallet_address,
  i.status as invite_status,
  i.reward_status,
  a.state,
  a.risk_score,
  a.reason_codes,
  a.evidence_summary,
  a.policy_version,
  a.analyzer_version,
  a.updated_at as watch_updated_at,
  (
    coalesce(
      a.evidence_summary ->> 'postPayoutObservationEnabled',
      'false'
    ) = 'true'
  ) as legacy_reward_recipient_observation_enabled,
  'AUTOMATIC_SAME_SUBJECT_REVIEW'::text as followup_mode
from public.sybil_v2_referral_assessments a
join public.invitations i
  on i.invite_code = a.invite_code
 and i.activation_network = a.network
where a.state = 'WATCH'
  and a.source = 'OPERATOR'
  and i.reward_status = 'PAID';

revoke all on public.operator_sybil_v2_historical_watch_followups
  from public, anon, authenticated;
grant select on public.operator_sybil_v2_historical_watch_followups
  to service_role;

comment on view public.operator_sybil_v2_historical_watch_followups is
  'Service-only historical paid OPERATOR WATCH follow-up list. Follow-up is automatic and remains scoped to the invitee wallet; inviter reward-recipient behavior is kept separate.';

create or replace function public.enrich_operator_monitor_snapshot_sybil_v2_watch_followup()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_due bigint := 0;
  v_stale_due bigint := 0;
  v_flagged_24h bigint := 0;
  v_hubs bigint := 0;
  v_priority_hubs bigint := 0;
  v_extra_alerts jsonb := '[]'::jsonb;
begin
  if not public.sybil_v2_enforcement_enabled() then
    return new;
  end if;

  select count(*)::bigint
  into v_due
  from public.operator_sybil_v2_watch_followup_due d
  where d.network = new.network;

  select count(*)::bigint
  into v_stale_due
  from public.operator_sybil_v2_watch_followup_due d
  where d.network = new.network
    and d.due_at < clock_timestamp() - interval '2 hours';

  select count(*)::bigint
  into v_flagged_24h
  from public.operator_sybil_v2_watch_followup_flags f
  where f.network = new.network
    and f.checked_at >= clock_timestamp() - interval '24 hours';

  select count(*)::bigint,
         count(*) filter (where h.priority = 'PRIORITY')::bigint
  into v_hubs, v_priority_hubs
  from public.operator_sybil_v2_cluster_hub_candidates h
  where h.network = new.network;

  new.metrics := coalesce(new.metrics,'{}'::jsonb) ||
    jsonb_build_object(
      'sybilV2WatchFollowup',
      jsonb_build_object(
        'dueFollowups', v_due,
        'staleDueFollowups', v_stale_due,
        'flaggedFollowupsLast24h', v_flagged_24h,
        'clusterHubCandidates', v_hubs,
        'priorityClusterHubCandidates', v_priority_hubs,
        'followupHorizonsHours', jsonb_build_array(24,168,720),
        'automaticRestrictionFromHubOnly', false
      )
    );

  if v_stale_due > 0 then
    v_extra_alerts := v_extra_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'SYBIL_V2_WATCH_FOLLOWUP_STALE',
        'severity', 'WARNING',
        'observed', v_stale_due,
        'message', 'One or more WATCH invitee follow-up scans are over two hours late.'
      )
    );
  end if;

  if v_flagged_24h > 0 then
    v_extra_alerts := v_extra_alerts || jsonb_build_array(
      jsonb_build_object(
        'code', 'SYBIL_V2_WATCH_FOLLOWUP_FLAGGED',
        'severity', 'WARNING',
        'observed', v_flagged_24h,
        'message', 'A WATCH invitee produced new same-subject B3TR flow evidence that deserves operator review. No automatic restriction was applied.'
      )
    );
  end if;

  new.alerts := coalesce(new.alerts,'[]'::jsonb) || v_extra_alerts;
  new.alert_count := jsonb_array_length(new.alerts);
  new.severity := case
    when new.alerts @> '[{"severity":"CRITICAL"}]'::jsonb then 'CRITICAL'
    when new.alert_count > 0 then 'WARNING'
    else 'NORMAL'
  end;

  return new;
end;
$$;

revoke all on function public.enrich_operator_monitor_snapshot_sybil_v2_watch_followup()
  from public, anon, authenticated, service_role;

drop trigger if exists ad_operator_monitor_sybil_v2_watch_followup_enrichment
  on public.operator_monitor_snapshots;
create trigger ad_operator_monitor_sybil_v2_watch_followup_enrichment
before insert on public.operator_monitor_snapshots
for each row execute function public.enrich_operator_monitor_snapshot_sybil_v2_watch_followup();

commit;
