alter table public.invitations
  add column sybil_status text not null default 'NOT_CHECKED',
  add column sybil_risk_level text not null default 'NONE',
  add column sybil_risk_score integer not null default 0,
  add column sybil_reason text,
  add column sybil_checked_at timestamptz;

alter table public.invitations
  add constraint invitations_sybil_status_check
    check (sybil_status = any (array['NOT_CHECKED'::text, 'CLEAR'::text, 'REVIEW'::text, 'BLOCKED'::text])),
  add constraint invitations_sybil_risk_level_check
    check (sybil_risk_level = any (array['NONE'::text, 'LOW'::text, 'MEDIUM'::text, 'HIGH'::text])),
  add constraint invitations_sybil_risk_score_check
    check (sybil_risk_score between 0 and 100),
  add constraint invitations_sybil_reason_check
    check (
      sybil_status not in ('REVIEW', 'BLOCKED')
      or (sybil_reason is not null and length(btrim(sybil_reason)) > 0)
    );

create index invitations_sybil_status_idx
  on public.invitations (sybil_status, updated_at desc);

create table public.sybil_review_events (
  id bigint generated by default as identity primary key,
  invite_code text not null references public.invitations(invite_code) on update cascade on delete restrict,
  wallet_address text not null,
  resulting_status text not null,
  risk_level text not null,
  risk_score integer not null default 0,
  signal_code text,
  source text not null default 'SYSTEM',
  summary text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint sybil_review_events_wallet_check
    check (wallet_address ~ '^0x[0-9a-f]{40}$'::text),
  constraint sybil_review_events_status_check
    check (resulting_status = any (array['CLEAR'::text, 'REVIEW'::text, 'BLOCKED'::text])),
  constraint sybil_review_events_risk_level_check
    check (risk_level = any (array['NONE'::text, 'LOW'::text, 'MEDIUM'::text, 'HIGH'::text])),
  constraint sybil_review_events_risk_score_check
    check (risk_score between 0 and 100),
  constraint sybil_review_events_source_check
    check (source = any (array['SYSTEM'::text, 'VEPASSPORT'::text, 'ONCHAIN'::text, 'OPERATOR'::text])),
  constraint sybil_review_events_summary_check
    check (length(btrim(summary)) > 0),
  constraint sybil_review_events_details_check
    check (jsonb_typeof(details) = 'object'::text)
);

create index sybil_review_events_wallet_created_idx
  on public.sybil_review_events (wallet_address, created_at desc);
create index sybil_review_events_invite_created_idx
  on public.sybil_review_events (invite_code, created_at desc);
create index sybil_review_events_status_created_idx
  on public.sybil_review_events (resulting_status, created_at desc);

alter table public.sybil_review_events enable row level security;
revoke all on table public.sybil_review_events from public, anon, authenticated;
grant select, insert, update, delete on table public.sybil_review_events to service_role;
grant usage, select on sequence public.sybil_review_events_id_seq to service_role;

create or replace function public.sync_invitation_reward_eligibility()
returns trigger
language plpgsql
set search_path to 'public'
as $function$
begin
  -- Paid records are immutable settlement history.
  if coalesce(new.reward_status::text, '') = 'PAID' then
    return new;
  end if;

  new.reward_paid_at := null;

  -- A cancelled invitation can never become reward eligible.
  if new.status = 'CANCELLED' then
    new.reward_status := 'FORFEITED';
    new.reward_eligible_at := null;
    return new;
  end if;

  -- Confirmed abuse can never become reward eligible.
  if new.sybil_status = 'BLOCKED' then
    new.reward_status := 'FORFEITED';
    new.reward_eligible_at := null;
    return new;
  end if;

  -- App completion is only trustworthy with a valid activation checkpoint and
  -- an on-chain block at or after activation.
  if new.invitee_wallet is null
     or new.activation_block is null
     or coalesce(new.apps_completed, 0) < 3
     or new.apps_completed_block is null
     or new.apps_completed_block < new.activation_block then
    new.apps_completed_at := null;
    new.apps_completed_block := null;
    new.vote_completed := false;
    new.vote_completed_at := null;
    new.vote_completed_block := null;
    new.vote_round_id := null;
  else
    -- Vote evidence is only trustworthy when all fields exist and the vote
    -- happened no earlier than the third-app completion block.
    if coalesce(new.vote_completed, false) = false
       or new.vote_completed_block is null
       or new.vote_round_id is null
       or new.vote_completed_block < new.apps_completed_block then
      new.vote_completed := false;
      new.vote_completed_at := null;
      new.vote_completed_block := null;
      new.vote_round_id := null;
    end if;
  end if;

  -- Reward eligibility requires a fresh Sybil review performed after the
  -- governance vote was recorded. REVIEW/NOT_CHECKED remain safely pending.
  if new.status = 'COMPLETED'
     and new.invitee_wallet is not null
     and new.activation_block is not null
     and coalesce(new.apps_completed, 0) >= 3
     and new.apps_completed_block is not null
     and new.apps_completed_block >= new.activation_block
     and coalesce(new.vote_completed, false) = true
     and new.vote_completed_at is not null
     and new.vote_completed_block is not null
     and new.vote_round_id is not null
     and new.vote_completed_block >= new.apps_completed_block
     and new.sybil_status = 'CLEAR'
     and new.sybil_checked_at is not null
     and new.sybil_checked_at >= new.vote_completed_at then
    new.reward_status := 'ELIGIBLE';
    new.reward_eligible_at := coalesce(
      new.reward_eligible_at,
      new.sybil_checked_at,
      new.vote_completed_at,
      now()
    );
  elsif new.invitee_wallet is not null then
    new.reward_status := 'PENDING';
    new.reward_eligible_at := null;
  else
    new.reward_status := 'NONE';
    new.reward_eligible_at := null;
  end if;

  return new;
end;
$function$;

create view public.operator_sybil_watchlist
with (security_invoker = true)
as
select
  invite_code,
  inviter_wallet,
  invitee_wallet as wallet_address,
  status as invite_status,
  reward_status,
  sybil_status,
  sybil_risk_level,
  sybil_risk_score,
  sybil_reason,
  sybil_checked_at,
  updated_at
from public.invitations
where sybil_status in ('REVIEW', 'BLOCKED');

create view public.operator_reward_leaderboard
with (security_invoker = true)
as
select
  recipient_wallet as wallet_address,
  count(*) filter (where status = 'PAID')::bigint as paid_referral_count,
  coalesce(sum(amount_wei) filter (where status = 'PAID'), 0::numeric) as total_reward_wei,
  min(paid_at) filter (where status = 'PAID') as first_paid_at,
  max(paid_at) filter (where status = 'PAID') as last_paid_at
from public.reward_payouts
group by recipient_wallet;

create view public.operator_referral_leaderboard
with (security_invoker = true)
as
select
  inviter_wallet as wallet_address,
  count(*)::bigint as invitations_created,
  count(*) filter (where status = 'COMPLETED')::bigint as completed_referrals,
  count(*) filter (where reward_status = 'PAID')::bigint as paid_referrals,
  count(*) filter (where sybil_status in ('REVIEW', 'BLOCKED'))::bigint as flagged_referrals,
  min(created_at) as first_invite_at,
  max(updated_at) as last_activity_at
from public.invitations
group by inviter_wallet;

revoke all on table public.operator_sybil_watchlist from public, anon, authenticated;
revoke all on table public.operator_reward_leaderboard from public, anon, authenticated;
revoke all on table public.operator_referral_leaderboard from public, anon, authenticated;
grant select on table public.operator_sybil_watchlist to service_role;
grant select on table public.operator_reward_leaderboard to service_role;
grant select on table public.operator_referral_leaderboard to service_role;