alter table public.reward_runtime_config
  add column if not exists reward_boost_reserve_enabled boolean not null default false,
  add column if not exists reward_boost_reserve_shadow_enabled boolean not null default true,
  add column if not exists reward_boost_reserve_safety_buffer_bps integer not null default 1500,
  add column if not exists reward_boost_reserve_long_incomplete_rounds integer not null default 2;

alter table public.reward_runtime_config
  drop constraint if exists reward_runtime_config_boost_safety_bps_check,
  add constraint reward_runtime_config_boost_safety_bps_check
    check (reward_boost_reserve_safety_buffer_bps between 0 and 5000),
  drop constraint if exists reward_runtime_config_boost_long_incomplete_check,
  add constraint reward_runtime_config_boost_long_incomplete_check
    check (reward_boost_reserve_long_incomplete_rounds between 1 and 52);

create table if not exists public.reward_boost_reserve_ledger (
  id bigint generated by default as identity primary key,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null
    check (app_id ~ '^0x[0-9a-f]{64}$'),
  entry_kind text not null
    check (entry_kind in (
      'SOURCE_SWEEP',
      'BOOST_RELEASE',
      'LATE_COMPLETION_RELEASE'
    )),
  source_reward_cohort_round_id bigint,
  source_allocation_receipt_id bigint
    references public.vebetter_round_allocations(id),
  destination_reward_cohort_round_id bigint,
  destination_allocation_receipt_id bigint
    references public.vebetter_round_allocations(id),
  amount_wei numeric(78,0) not null
    check (amount_wei > 0 and amount_wei = trunc(amount_wei)),
  policy_version text not null
    check (char_length(btrim(policy_version)) between 1 and 80),
  reference_key text not null
    check (char_length(btrim(reference_key)) between 1 and 160),
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default now(),
  constraint reward_boost_reserve_ledger_reference_uidx
    unique (network, app_id, reference_key),
  constraint reward_boost_reserve_ledger_shape_check
    check (
      (
        entry_kind = 'SOURCE_SWEEP'
        and source_reward_cohort_round_id is not null
        and source_reward_cohort_round_id >= 1
        and source_allocation_receipt_id is not null
        and destination_reward_cohort_round_id is null
        and destination_allocation_receipt_id is null
      )
      or
      (
        entry_kind in ('BOOST_RELEASE','LATE_COMPLETION_RELEASE')
        and source_reward_cohort_round_id is null
        and source_allocation_receipt_id is null
        and destination_reward_cohort_round_id is not null
        and destination_reward_cohort_round_id >= 1
        and destination_allocation_receipt_id is not null
      )
    )
);

create index if not exists reward_boost_reserve_ledger_source_idx
  on public.reward_boost_reserve_ledger(
    network, app_id, source_reward_cohort_round_id, source_allocation_receipt_id
  )
  where source_allocation_receipt_id is not null;

create index if not exists reward_boost_reserve_ledger_destination_idx
  on public.reward_boost_reserve_ledger(
    network, app_id, destination_reward_cohort_round_id, destination_allocation_receipt_id
  )
  where destination_allocation_receipt_id is not null;

create index if not exists reward_boost_reserve_ledger_created_idx
  on public.reward_boost_reserve_ledger(created_at desc, id desc);

alter table public.reward_boost_reserve_ledger enable row level security;

revoke all on table public.reward_boost_reserve_ledger
  from public, anon, authenticated, service_role;
revoke all on sequence public.reward_boost_reserve_ledger_id_seq
  from public, anon, authenticated, service_role;
grant select, insert on table public.reward_boost_reserve_ledger
  to service_role;
grant usage, select on sequence public.reward_boost_reserve_ledger_id_seq
  to service_role;

create or replace function public.read_reward_boost_reserve_balance_wei(
  p_network text,
  p_app_id text
)
returns numeric
language plpgsql
stable
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_balance numeric(78,0);
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  if p_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'unsupported network';
  end if;
  if p_app_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'invalid app id';
  end if;

  select coalesce(sum(
    case
      when l.entry_kind = 'SOURCE_SWEEP' then l.amount_wei
      else -l.amount_wei
    end
  ),0)
  into v_balance
  from public.reward_boost_reserve_ledger l
  where l.network = p_network
    and l.app_id = p_app_id;

  if v_balance < 0 then
    raise exception 'REWARD_BOOST_RESERVE_LEDGER_NEGATIVE';
  end if;

  return v_balance;
end;
$$;

revoke all on function public.read_reward_boost_reserve_balance_wei(text,text)
  from public, anon, authenticated;
grant execute on function public.read_reward_boost_reserve_balance_wei(text,text)
  to service_role;

create or replace function public.read_reward_boost_reserve_cohort_net_flow_wei(
  p_network text,
  p_app_id text,
  p_reward_cohort_round_id bigint,
  p_allocation_receipt_id bigint
)
returns numeric
language plpgsql
stable
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
  v_inflow numeric(78,0) := 0;
  v_outflow numeric(78,0) := 0;
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id = p_allocation_receipt_id
    and a.network = p_network
    and a.app_id = p_app_id;

  if not found
     or v_receipt.vebetter_round_id + 1 <> p_reward_cohort_round_id then
    raise exception 'allocation receipt does not fund the requested reward cohort';
  end if;

  select coalesce(sum(l.amount_wei),0)
  into v_inflow
  from public.reward_boost_reserve_ledger l
  where l.network = p_network
    and l.app_id = p_app_id
    and l.destination_reward_cohort_round_id = p_reward_cohort_round_id
    and l.destination_allocation_receipt_id = p_allocation_receipt_id
    and l.entry_kind in ('BOOST_RELEASE','LATE_COMPLETION_RELEASE');

  select coalesce(sum(l.amount_wei),0)
  into v_outflow
  from public.reward_boost_reserve_ledger l
  where l.network = p_network
    and l.app_id = p_app_id
    and l.source_reward_cohort_round_id = p_reward_cohort_round_id
    and l.source_allocation_receipt_id = p_allocation_receipt_id
    and l.entry_kind = 'SOURCE_SWEEP';

  return v_inflow - v_outflow;
end;
$$;

revoke all on function public.read_reward_boost_reserve_cohort_net_flow_wei(text,text,bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.read_reward_boost_reserve_cohort_net_flow_wei(text,text,bigint,bigint)
  to service_role;

create or replace function public.read_reward_cohort_effective_budget_wei(
  p_network text,
  p_app_id text,
  p_reward_cohort_round_id bigint,
  p_allocation_receipt_id bigint
)
returns numeric
language plpgsql
stable
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
  v_adjustment numeric(78,0) := 0;
  v_net_flow numeric(78,0) := 0;
  v_budget numeric(78,0) := 0;
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id = p_allocation_receipt_id
    and a.network = p_network
    and a.app_id = p_app_id;

  if not found
     or v_receipt.vebetter_round_id + 1 <> p_reward_cohort_round_id then
    raise exception 'allocation receipt does not fund the requested reward cohort';
  end if;

  select coalesce(sum(a.amount_wei),0)
  into v_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network = p_network
    and a.app_id = p_app_id
    and a.reward_cohort_round_id = p_reward_cohort_round_id
    and a.allocation_receipt_id = p_allocation_receipt_id;

  v_net_flow := public.read_reward_boost_reserve_cohort_net_flow_wei(
    p_network,
    p_app_id,
    p_reward_cohort_round_id,
    p_allocation_receipt_id
  );

  v_budget :=
    v_receipt.rewards_allocation_amount_wei +
    v_adjustment +
    v_net_flow;

  if v_budget < 0 then
    raise exception 'REWARD_COHORT_EFFECTIVE_BUDGET_NEGATIVE';
  end if;

  return v_budget;
end;
$$;

revoke all on function public.read_reward_cohort_effective_budget_wei(text,text,bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.read_reward_cohort_effective_budget_wei(text,text,bigint,bigint)
  to service_role;

create or replace function public.validate_reward_boost_reserve_ledger()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_source_receipt public.vebetter_round_allocations%rowtype;
  v_destination_receipt public.vebetter_round_allocations%rowtype;
  v_budget numeric(78,0) := 0;
  v_committed numeric(78,0) := 0;
  v_balance numeric(78,0) := 0;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_reservation_' || new.network,
      0
    )
  );
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_boost_reserve_' || new.network || '_' || new.app_id,
      0
    )
  );

  if new.entry_kind = 'SOURCE_SWEEP' then
    select * into v_source_receipt
    from public.vebetter_round_allocations a
    where a.id = new.source_allocation_receipt_id;

    if not found
       or v_source_receipt.network <> new.network
       or v_source_receipt.app_id <> new.app_id
       or v_source_receipt.vebetter_round_id + 1 <>
          new.source_reward_cohort_round_id then
      raise exception 'REWARD_BOOST_RESERVE_SOURCE_MISMATCH';
    end if;

    v_budget := public.read_reward_cohort_effective_budget_wei(
      new.network,
      new.app_id,
      new.source_reward_cohort_round_id,
      new.source_allocation_receipt_id
    );

    v_committed := public.read_reward_cohort_committed_wei(
      new.network,
      new.app_id,
      new.source_reward_cohort_round_id,
      new.source_allocation_receipt_id
    );

    if new.amount_wei > greatest(v_budget - v_committed,0) then
      raise exception 'REWARD_BOOST_RESERVE_SOURCE_EXCEEDED';
    end if;
  else
    select * into v_destination_receipt
    from public.vebetter_round_allocations a
    where a.id = new.destination_allocation_receipt_id;

    if not found
       or v_destination_receipt.network <> new.network
       or v_destination_receipt.app_id <> new.app_id
       or v_destination_receipt.vebetter_round_id + 1 <>
          new.destination_reward_cohort_round_id then
      raise exception 'REWARD_BOOST_RESERVE_DESTINATION_MISMATCH';
    end if;

    v_balance := public.read_reward_boost_reserve_balance_wei(
      new.network,
      new.app_id
    );

    if new.amount_wei > v_balance then
      raise exception 'REWARD_BOOST_RESERVE_BALANCE_EXCEEDED';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function public.validate_reward_boost_reserve_ledger()
  from public, anon, authenticated;
grant execute on function public.validate_reward_boost_reserve_ledger()
  to service_role;

drop trigger if exists reward_boost_reserve_ledger_validate
  on public.reward_boost_reserve_ledger;
create trigger reward_boost_reserve_ledger_validate
before insert on public.reward_boost_reserve_ledger
for each row execute function public.validate_reward_boost_reserve_ledger();

create or replace function public.reject_reward_boost_reserve_ledger_mutation()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  raise exception 'Reward boost reserve ledger % is immutable', old.id;
end;
$$;

revoke all on function public.reject_reward_boost_reserve_ledger_mutation()
  from public, anon, authenticated;
grant execute on function public.reject_reward_boost_reserve_ledger_mutation()
  to service_role;

drop trigger if exists reward_boost_reserve_ledger_immutable_guard
  on public.reward_boost_reserve_ledger;
create trigger reward_boost_reserve_ledger_immutable_guard
before update or delete on public.reward_boost_reserve_ledger
for each row execute function public.reject_reward_boost_reserve_ledger_mutation();
