begin;

alter table public.invitations
  add column if not exists reward_cohort_round_id bigint,
  add column if not exists reward_funding_allocation_receipt_id bigint
    references public.vebetter_round_allocations(id);

alter table public.invitations
  drop constraint if exists invitations_reward_cohort_binding_check,
  add constraint invitations_reward_cohort_binding_check
    check (
      (reward_cohort_round_id is null and reward_funding_allocation_receipt_id is null)
      or
      (reward_cohort_round_id is not null and reward_cohort_round_id >= 1
        and reward_funding_allocation_receipt_id is not null)
    );

create index if not exists invitations_reward_cohort_idx
  on public.invitations(
    activation_network,
    reward_cohort_round_id,
    reward_funding_allocation_receipt_id,
    status
  )
  where reward_cohort_round_id is not null;

-- Manual or promotional funding is intentionally separate from official
-- VeBetter allocation evidence so it cannot pollute allocation history.
create table if not exists public.reward_cohort_funding_adjustments (
  id bigint generated by default as identity primary key,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null
    check (app_id ~ '^0x[0-9a-f]{64}$'),
  reward_cohort_round_id bigint not null
    check (reward_cohort_round_id >= 1),
  allocation_receipt_id bigint not null
    references public.vebetter_round_allocations(id),
  adjustment_type text not null
    check (adjustment_type in ('PROMOTION')),
  amount_wei numeric(78,0) not null
    check (amount_wei > 0 and amount_wei = trunc(amount_wei)),
  reference_key text not null
    check (length(btrim(reference_key)) between 1 and 120),
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default now(),
  constraint reward_cohort_funding_adjustments_uidx
    unique (network, app_id, reward_cohort_round_id, reference_key)
);

alter table public.reward_cohort_funding_adjustments enable row level security;
revoke all on table public.reward_cohort_funding_adjustments
  from public, anon, authenticated;
revoke all on sequence public.reward_cohort_funding_adjustments_id_seq
  from public, anon, authenticated;
grant select, insert on table public.reward_cohort_funding_adjustments to service_role;
grant usage, select on sequence public.reward_cohort_funding_adjustments_id_seq to service_role;

create index if not exists reward_cohort_funding_adjustments_lookup_idx
  on public.reward_cohort_funding_adjustments(
    network, app_id, reward_cohort_round_id, allocation_receipt_id
  );

create or replace function public.validate_reward_cohort_funding_adjustment()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
begin
  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id = new.allocation_receipt_id;

  if not found
     or v_receipt.network <> new.network
     or v_receipt.app_id <> new.app_id
     or v_receipt.vebetter_round_id + 1 <> new.reward_cohort_round_id then
    raise exception 'REWARD_COHORT_FUNDING_ADJUSTMENT_MISMATCH';
  end if;

  return new;
end;
$$;

revoke all on function public.validate_reward_cohort_funding_adjustment()
  from public, anon, authenticated;
grant execute on function public.validate_reward_cohort_funding_adjustment() to service_role;

drop trigger if exists reward_cohort_funding_adjustments_validate
  on public.reward_cohort_funding_adjustments;
create trigger reward_cohort_funding_adjustments_validate
before insert on public.reward_cohort_funding_adjustments
for each row execute function public.validate_reward_cohort_funding_adjustment();

create or replace function public.reject_reward_cohort_funding_adjustment_mutation()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception 'Reward cohort funding adjustment % is immutable', old.id;
end;
$$;

revoke all on function public.reject_reward_cohort_funding_adjustment_mutation()
  from public, anon, authenticated;
grant execute on function public.reject_reward_cohort_funding_adjustment_mutation() to service_role;

drop trigger if exists reward_cohort_funding_adjustments_immutable_guard
  on public.reward_cohort_funding_adjustments;
create trigger reward_cohort_funding_adjustments_immutable_guard
before update or delete on public.reward_cohort_funding_adjustments
for each row execute function public.reject_reward_cohort_funding_adjustment_mutation();

-- Existing genuine referrals were already onboarding during the first funded
-- cohort. Allocation round 113 is therefore explicitly bound to cohort 114.
with funding as (
  select a.id
  from public.vebetter_round_allocations a
  where a.network = 'mainnet'
    and a.app_id = '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e'
    and a.vebetter_round_id = 113
  order by a.id desc
  limit 1
)
update public.invitations i
set reward_cohort_round_id = 114,
    reward_funding_allocation_receipt_id = funding.id
from funding
where i.activation_network = 'mainnet'
  and i.activated_at is not null
  and i.eligibility_check_id is not null
  and i.status in ('ACTIVATING','UNDER_REVIEW','COMPLETED')
  and i.reward_cohort_round_id is null
  and i.reward_funding_allocation_receipt_id is null;

-- One-time Round 114 launch promotion: observed operator top-up of 1,217.33
-- B3TR. This row never enters vebetter_round_allocations.
insert into public.reward_cohort_funding_adjustments(
  network,
  app_id,
  reward_cohort_round_id,
  allocation_receipt_id,
  adjustment_type,
  amount_wei,
  reference_key,
  details
)
select
  'mainnet',
  a.app_id,
  114,
  a.id,
  'PROMOTION',
  1217330000000000000000,
  'round-114-launch-promo-20260904',
  jsonb_build_object(
    'source','operator_manual_topup',
    'observedPoolBeforeWei','886440000000000000000',
    'observedPoolAfterWei','2103770000000000000000',
    'purpose','round_114_launch_promotion'
  )
from public.vebetter_round_allocations a
where a.network = 'mainnet'
  and a.app_id = '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e'
  and a.vebetter_round_id = 113
order by a.id desc
limit 1
on conflict (network, app_id, reward_cohort_round_id, reference_key) do nothing;

create or replace function public.read_reward_cohort_planning_snapshot(
  p_network text,
  p_app_id text,
  p_reward_cohort_round_id bigint default null,
  p_allocation_receipt_id bigint default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_veinvite_app_id constant text :=
    '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e';
  v_receipt public.vebetter_round_allocations%rowtype;
  v_epoch public.reward_budget_epochs%rowtype;
  v_cohort_round bigint;
  v_reserved numeric(78,0) := 0;
  v_legacy_reserved numeric(78,0) := 0;
  v_cohort_reserved numeric(78,0) := 0;
  v_adjustment numeric(78,0) := 0;
  v_designated numeric(78,0) := 0;
  v_queued integer := 0;
  v_vote_ready integer := 0;
  v_vot3_ready integer := 0;
  v_apps_two integer := 0;
  v_apps_one integer := 0;
  v_activated_zero integer := 0;
  v_pending_acceptance integer := 0;
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  if p_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'unsupported network';
  end if;
  if p_app_id <> v_veinvite_app_id then
    raise exception 'cohort reward planning only supports the VeInvite app';
  end if;

  if p_allocation_receipt_id is null and p_reward_cohort_round_id is null then
    select * into v_receipt
    from public.vebetter_round_allocations a
    where a.network = p_network and a.app_id = p_app_id
    order by a.vebetter_round_id desc, a.id desc
    limit 1;
    if found then v_cohort_round := v_receipt.vebetter_round_id + 1; end if;
  elsif p_allocation_receipt_id is not null and p_reward_cohort_round_id is not null then
    select * into v_receipt
    from public.vebetter_round_allocations a
    where a.id = p_allocation_receipt_id
      and a.network = p_network
      and a.app_id = p_app_id;
    v_cohort_round := p_reward_cohort_round_id;
  else
    raise exception 'cohort round and allocation receipt must be provided together';
  end if;

  if v_receipt.id is null then
    return jsonb_build_object(
      'reservedExistingWei','0','cohortReservedWei','0',
      'fundingAdjustmentWei','0','designatedBudgetWei','0',
      'rewardCohortRoundId',null,
      'pipeline',jsonb_build_object(
        'queuedEligibleCount',0,'voteReadyCount',0,'vot3ReadyCount',0,
        'appsTwoCount',0,'appsOneCount',0,'activatedZeroCount',0,
        'pendingAcceptanceCount',0
      ),
      'latestAllocation',null,'activeEpoch',null
    );
  end if;

  if v_cohort_round < 1 or v_receipt.vebetter_round_id + 1 <> v_cohort_round then
    raise exception 'allocation receipt does not fund the requested reward cohort';
  end if;

  select coalesce(sum(q.reserved_amount_wei),0) into v_reserved
  from public.reward_queue_entries q
  where q.network = p_network
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED')
    and not exists (
      select 1 from public.reward_payouts paid
      where paid.invite_code = q.invite_code and paid.status = 'PAID'
    );

  select coalesce(sum(rp.amount_wei),0) into v_legacy_reserved
  from public.reward_payouts rp
  join public.reward_rounds rr on rr.id = rp.round_id
  where rr.network = p_network and rr.app_id = p_app_id
    and rp.status in ('PENDING','SENDING','FAILED')
    and not exists (
      select 1 from public.reward_queue_entries q
      where q.invite_code = rp.invite_code and q.reserved_amount_wei is not null
    );
  v_reserved := v_reserved + v_legacy_reserved;

  select coalesce(sum(q.reserved_amount_wei),0) into v_cohort_reserved
  from public.reward_queue_entries q
  join public.invitations i on i.invite_code = q.invite_code
  where q.network = p_network
    and i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.reward_cohort_round_id = v_cohort_round
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED')
    and not exists (
      select 1 from public.reward_payouts paid
      where paid.invite_code = q.invite_code and paid.status = 'PAID'
    );

  select coalesce(sum(a.amount_wei),0) into v_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network = p_network and a.app_id = p_app_id
    and a.reward_cohort_round_id = v_cohort_round
    and a.allocation_receipt_id = v_receipt.id;

  v_designated := v_receipt.rewards_allocation_amount_wei + v_adjustment;

  select count(*) into v_queued
  from public.invitations i
  where i.activation_network = p_network
    and i.reward_cohort_round_id = v_cohort_round
    and i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.status = 'COMPLETED'
    and i.reward_status = 'ELIGIBLE'
    and i.reward_eligible_at is not null
    and not exists (
      select 1 from public.reward_queue_entries q
      where q.invite_code = i.invite_code and q.reserved_amount_wei is not null
    )
    and not exists (
      select 1 from public.reward_reservation_legacy_exclusions x
      where x.invite_code = i.invite_code
    );

  select count(*) into v_vote_ready
  from public.invitations i
  where i.activation_network = p_network
    and i.reward_cohort_round_id = v_cohort_round
    and i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.status in ('ACTIVATING','UNDER_REVIEW')
    and i.reward_eligible_at is null and i.activated_at is not null
    and i.apps_completed >= 3
    and coalesce(i.vot3_converted,false) = true
    and coalesce(i.vote_completed,false) = false;

  select count(*) into v_vot3_ready
  from public.invitations i
  where i.activation_network = p_network
    and i.reward_cohort_round_id = v_cohort_round
    and i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.status in ('ACTIVATING','UNDER_REVIEW')
    and i.reward_eligible_at is null and i.activated_at is not null
    and i.apps_completed >= 3
    and coalesce(i.vot3_converted,false) = false;

  select count(*) into v_apps_two
  from public.invitations i
  where i.activation_network = p_network
    and i.reward_cohort_round_id = v_cohort_round
    and i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.status in ('ACTIVATING','UNDER_REVIEW')
    and i.reward_eligible_at is null and i.activated_at is not null
    and i.apps_completed = 2;

  select count(*) into v_apps_one
  from public.invitations i
  where i.activation_network = p_network
    and i.reward_cohort_round_id = v_cohort_round
    and i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.status in ('ACTIVATING','UNDER_REVIEW')
    and i.reward_eligible_at is null and i.activated_at is not null
    and i.apps_completed = 1;

  select count(*) into v_activated_zero
  from public.invitations i
  where i.activation_network = p_network
    and i.reward_cohort_round_id = v_cohort_round
    and i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.status in ('ACTIVATING','UNDER_REVIEW')
    and i.reward_eligible_at is null and i.activated_at is not null
    and i.apps_completed <= 0;

  select count(*) into v_pending_acceptance
  from public.invitations i
  where i.status = 'PENDING_ACCEPTANCE'
    and i.reward_eligible_at is null
    and i.reward_cohort_round_id is null;

  select * into v_epoch
  from public.reward_budget_epochs e
  where e.allocation_receipt_id = v_receipt.id;

  return jsonb_build_object(
    'reservedExistingWei',v_reserved::text,
    'cohortReservedWei',v_cohort_reserved::text,
    'fundingAdjustmentWei',v_adjustment::text,
    'designatedBudgetWei',v_designated::text,
    'rewardCohortRoundId',v_cohort_round,
    'pipeline',jsonb_build_object(
      'queuedEligibleCount',v_queued,'voteReadyCount',v_vote_ready,
      'vot3ReadyCount',v_vot3_ready,'appsTwoCount',v_apps_two,
      'appsOneCount',v_apps_one,'activatedZeroCount',v_activated_zero,
      'pendingAcceptanceCount',v_pending_acceptance
    ),
    'latestAllocation',jsonb_build_object(
      'id',v_receipt.id,'veBetterRoundId',v_receipt.vebetter_round_id,
      'rewardsAllocationWei',v_receipt.rewards_allocation_amount_wei::text,
      'claimBlockTimestamp',v_receipt.claim_block_timestamp
    ),
    'activeEpoch',case when v_epoch.id is null then null else jsonb_build_object(
      'id',v_epoch.id,'veBetterRoundId',v_epoch.vebetter_round_id,
      'allocationRewardsWei',v_epoch.allocation_rewards_wei::text,
      'openingPoolBalanceWei',v_epoch.opening_pool_balance_wei::text,
      'openingReservedWei',v_epoch.opening_reserved_wei::text,
      'expectedCompletions',v_epoch.expected_completions,
      'stressCompletions',v_epoch.stress_completions,
      'rewardPerInviteWei',v_epoch.reward_per_invite_wei::text,
      'algorithmVersion',v_epoch.algorithm_version,
      'pipelineSnapshot',v_epoch.pipeline_snapshot,'createdAt',v_epoch.created_at
    ) end
  );
end;
$$;

revoke all on function public.read_reward_cohort_planning_snapshot(text,text,bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.read_reward_cohort_planning_snapshot(text,text,bigint,bigint)
  to service_role;

create or replace function public.read_reward_reservation_candidates_v2(
  p_network text,
  p_limit integer default 25
)
returns table(
  invite_code text,
  completion_block bigint,
  completion_tx_index integer,
  completion_clause_index integer,
  reward_cohort_round_id bigint,
  reward_funding_allocation_receipt_id bigint
)
language sql
stable
set search_path = pg_catalog, public
as $$
  with parameters as (
    select lower(btrim(p_network)) as network,
           greatest(1,least(coalesce(p_limit,25),100)) as row_limit
  )
  select i.invite_code, completion.block_number::bigint,
         completion.tx_index::integer, completion.clause_index::integer,
         i.reward_cohort_round_id, i.reward_funding_allocation_receipt_id
  from public.invitations i
  cross join parameters p
  cross join lateral (
    select e.block_number,e.tx_index,e.clause_index
    from public.invite_impact_events e
    where e.invite_code = i.invite_code and e.network = p.network
      and e.event_type in ('DAPP_REWARD','VOT3_CONVERSION','ALLOCATION_VOTE')
      and e.block_number is not null and e.tx_index is not null
      and e.clause_index is not null
    order by e.block_number desc,e.tx_index desc,e.clause_index desc
    limit 1
  ) completion
  where i.activation_network = p.network
    and i.status = 'COMPLETED' and i.reward_status = 'ELIGIBLE'
    and i.reward_eligible_at is not null and i.sybil_status = 'CLEAR'
    and i.sybil_checked_at is not null and i.impact_sync_complete_at is not null
    and i.inviter_wallet is not null and i.invitee_wallet is not null
    and i.eligibility_check_id is not null
    and i.reward_cohort_round_id is not null
    and i.reward_funding_allocation_receipt_id is not null
    and not exists (
      select 1 from public.reward_queue_entries q where q.invite_code = i.invite_code
    )
    and not exists (
      select 1 from public.reward_reservation_legacy_exclusions x where x.invite_code = i.invite_code
    )
  order by completion.block_number,completion.tx_index,completion.clause_index,i.invite_code
  limit (select row_limit from parameters);
$$;

revoke all on function public.read_reward_reservation_candidates_v2(text,integer)
  from public, anon, authenticated;
grant execute on function public.read_reward_reservation_candidates_v2(text,integer)
  to service_role;

create or replace function public.read_next_claimed_reward_cohort(
  p_network text,
  p_app_id text
)
returns jsonb
language sql
stable
set search_path = pg_catalog, public
as $$
  select jsonb_build_object(
    'rewardCohortRoundId',i.reward_cohort_round_id,
    'allocationReceiptId',i.reward_funding_allocation_receipt_id
  )
  from public.reward_queue_entries q
  join public.invitations i on i.invite_code = q.invite_code
  join public.vebetter_round_allocations a
    on a.id = i.reward_funding_allocation_receipt_id
  where q.network = lower(btrim(p_network))
    and a.app_id = lower(btrim(p_app_id))
    and q.status = 'QUEUED' and q.assigned_round_id is null
    and q.claim_requested_at is not null
    and q.reserved_amount_wei is not null and q.reserved_amount_wei > 0
    and i.reward_cohort_round_id is not null
  order by q.claim_requested_at,q.invite_code
  limit 1;
$$;

revoke all on function public.read_next_claimed_reward_cohort(text,text)
  from public, anon, authenticated;
grant execute on function public.read_next_claimed_reward_cohort(text,text) to service_role;

create or replace function public.enforce_reward_queue_cohort_budget()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_invitation public.invitations%rowtype;
  v_receipt public.vebetter_round_allocations%rowtype;
  v_adjustment numeric(78,0) := 0;
  v_existing numeric(78,0) := 0;
  v_budget numeric(78,0) := 0;
begin
  if new.reserved_amount_wei is null then return new; end if;

  select * into v_invitation
  from public.invitations i where i.invite_code = new.invite_code;

  if not found or v_invitation.reward_cohort_round_id is null
     or v_invitation.reward_funding_allocation_receipt_id is null then
    raise exception 'REWARD_COHORT_BINDING_REQUIRED';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id = v_invitation.reward_funding_allocation_receipt_id;

  if not found or v_receipt.network <> new.network
     or v_receipt.vebetter_round_id + 1 <> v_invitation.reward_cohort_round_id then
    raise exception 'REWARD_COHORT_FUNDING_MISMATCH';
  end if;

  select coalesce(sum(a.amount_wei),0) into v_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network = v_receipt.network and a.app_id = v_receipt.app_id
    and a.reward_cohort_round_id = v_invitation.reward_cohort_round_id
    and a.allocation_receipt_id = v_receipt.id;
  v_budget := v_receipt.rewards_allocation_amount_wei + v_adjustment;

  select coalesce(sum(q.reserved_amount_wei),0) into v_existing
  from public.reward_queue_entries q
  join public.invitations i on i.invite_code = q.invite_code
  where i.reward_funding_allocation_receipt_id = v_receipt.id
    and i.reward_cohort_round_id = v_invitation.reward_cohort_round_id
    and q.invite_code <> new.invite_code
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED')
    and not exists (
      select 1 from public.reward_payouts paid
      where paid.invite_code = q.invite_code and paid.status = 'PAID'
    );

  if v_existing + new.reserved_amount_wei > v_budget then
    raise exception 'REWARD_COHORT_BUDGET_EXCEEDED';
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_reward_queue_cohort_budget()
  from public, anon, authenticated;
grant execute on function public.enforce_reward_queue_cohort_budget() to service_role;

drop trigger if exists reward_queue_cohort_budget_guard on public.reward_queue_entries;
create trigger reward_queue_cohort_budget_guard
before insert or update of reserved_amount_wei on public.reward_queue_entries
for each row execute function public.enforce_reward_queue_cohort_budget();

create or replace function public.prepare_reward_cohort_batch(
  p_network text,
  p_app_id text,
  p_pool_balance_wei numeric,
  p_allocation_receipt_id bigint,
  p_expected_completions integer,
  p_stress_completions integer,
  p_reward_per_invite_wei numeric,
  p_algorithm_version text,
  p_pipeline_snapshot jsonb
)
returns jsonb
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_veinvite_app_id constant text :=
    '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e';
  v_batch_limit constant integer := 25;
  v_receipt public.vebetter_round_allocations%rowtype;
  v_epoch public.reward_budget_epochs%rowtype;
  v_reserved_existing numeric(78,0) := 0;
  v_legacy_reserved numeric(78,0) := 0;
  v_candidate_codes text[] := array[]::text[];
  v_eligible_count integer := 0;
  v_round_id bigint;
  v_distributable numeric(78,0) := 0;
  v_remainder numeric(78,0) := 0;
  v_payout_count integer := 0;
  v_assigned_count integer := 0;
  v_epoch_created boolean := false;
  v_now timestamptz := now();
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));
  p_algorithm_version := btrim(p_algorithm_version);

  if p_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'unsupported network';
  end if;
  if p_app_id <> v_veinvite_app_id then
    raise exception 'cohort rewards can only target the VeInvite app';
  end if;
  if p_pool_balance_wei is null or p_pool_balance_wei < 0
     or p_pool_balance_wei <> trunc(p_pool_balance_wei) then
    raise exception 'pool balance must be a non-negative integer';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_predictive_reward_' || p_network || '_' || p_app_id,0)
  );

  if exists(
    select 1 from public.reward_rounds rr
    where rr.network = p_network and rr.app_id = p_app_id
      and rr.status in ('CREATED','PAYING')
  ) then
    raise exception 'Finish the current reward round before preparing another one';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id = p_allocation_receipt_id for share;

  if not found or v_receipt.network <> p_network or v_receipt.app_id <> p_app_id then
    raise exception 'VeBetter allocation receipt does not match the active reward pool';
  end if;

  select coalesce(sum(q.reserved_amount_wei),0) into v_reserved_existing
  from public.reward_queue_entries q
  where q.network = p_network and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED')
    and not exists (
      select 1 from public.reward_payouts paid
      where paid.invite_code = q.invite_code and paid.status = 'PAID'
    );

  select coalesce(sum(rp.amount_wei),0) into v_legacy_reserved
  from public.reward_payouts rp
  join public.reward_rounds rr on rr.id = rp.round_id
  where rr.network = p_network and rr.app_id = p_app_id
    and rp.status in ('PENDING','SENDING','FAILED')
    and not exists (
      select 1 from public.reward_queue_entries q
      where q.invite_code = rp.invite_code and q.reserved_amount_wei is not null
    );
  v_reserved_existing := v_reserved_existing + v_legacy_reserved;

  if v_reserved_existing > p_pool_balance_wei then
    raise exception 'reserved reward liability exceeds the observed reward pool';
  end if;

  select * into v_epoch
  from public.reward_budget_epochs e
  where e.allocation_receipt_id = v_receipt.id;

  if not found then
    insert into public.reward_budget_epochs(
      network,app_id,allocation_receipt_id,vebetter_round_id,
      allocation_rewards_wei,opening_pool_balance_wei,opening_reserved_wei,
      expected_completions,stress_completions,reward_per_invite_wei,
      algorithm_version,pipeline_snapshot
    ) values (
      p_network,p_app_id,v_receipt.id,v_receipt.vebetter_round_id,
      v_receipt.rewards_allocation_amount_wei,p_pool_balance_wei,v_reserved_existing,
      greatest(p_expected_completions,0),greatest(p_stress_completions,1),
      greatest(p_reward_per_invite_wei,0),p_algorithm_version,
      coalesce(p_pipeline_snapshot,'{}'::jsonb)
    ) returning * into v_epoch;
    v_epoch_created := true;
  end if;

  select coalesce(array_agg(c.invite_code order by c.claim_requested_at,c.invite_code),array[]::text[])
  into v_candidate_codes
  from (
    select q.invite_code,q.claim_requested_at
    from public.reward_queue_entries q
    join public.invitations i on i.invite_code = q.invite_code
    where q.network = p_network and q.status = 'QUEUED'
      and q.assigned_round_id is null and q.claim_requested_at is not null
      and q.claim_requested_by_wallet = q.recipient_wallet
      and q.reserved_amount_wei is not null and q.reserved_amount_wei > 0
      and q.reserved_at is not null
      and i.reward_funding_allocation_receipt_id = v_receipt.id
      and i.reward_cohort_round_id = v_receipt.vebetter_round_id + 1
      and i.status = 'COMPLETED' and i.reward_status = 'ELIGIBLE'
      and i.sybil_status = 'CLEAR' and lower(i.inviter_wallet) = q.recipient_wallet
      and not exists (
        select 1 from public.reward_payouts rp where rp.invite_code = q.invite_code
      )
    order by q.claim_requested_at,q.invite_code
    limit v_batch_limit
    for update of q,i
  ) c;

  v_eligible_count := coalesce(cardinality(v_candidate_codes),0);
  if v_eligible_count = 0 then
    return jsonb_build_object(
      'epochId',v_epoch.id,'roundId',null,'epochCreated',v_epoch_created,
      'reason','NO_CLAIMED_REWARDS'
    );
  end if;

  select coalesce(sum(q.reserved_amount_wei),0) into v_distributable
  from public.reward_queue_entries q
  where q.invite_code = any(v_candidate_codes);

  if v_distributable <= 0 or v_distributable > p_pool_balance_wei then
    raise exception 'claimed reward batch exceeds the observed reward pool';
  end if;
  v_remainder := p_pool_balance_wei - v_distributable;

  insert into public.reward_rounds(
    network,app_id,status,observed_pool_balance_wei,reserved_before_round_wei,
    distributable_wei,eligible_count,per_reward_wei,remainder_wei,reward_budget_epoch_id
  ) values (
    p_network,p_app_id,'CREATED',p_pool_balance_wei,v_reserved_existing,
    v_distributable,v_eligible_count,0,v_remainder,v_epoch.id
  ) returning id into v_round_id;

  insert into public.reward_payouts(round_id,invite_code,recipient_wallet,amount_wei,status)
  select v_round_id,q.invite_code,q.recipient_wallet,q.reserved_amount_wei,'PENDING'
  from public.reward_queue_entries q
  where q.invite_code = any(v_candidate_codes)
    and q.status = 'QUEUED' and q.assigned_round_id is null
  order by q.claim_requested_at,q.invite_code;
  get diagnostics v_payout_count = row_count;

  if v_payout_count <> v_eligible_count then
    raise exception 'reward payout count does not match claimed reservation count';
  end if;

  update public.reward_queue_entries q
  set status = 'ASSIGNED',assigned_round_id = v_round_id,assigned_at = v_now
  where q.invite_code = any(v_candidate_codes)
    and q.status = 'QUEUED' and q.assigned_round_id is null;
  get diagnostics v_assigned_count = row_count;

  if v_assigned_count <> v_eligible_count then
    raise exception 'reward queue assignment count does not match claimed reservation count';
  end if;

  return jsonb_build_object(
    'epochId',v_epoch.id,'roundId',v_round_id,'epochCreated',v_epoch_created,
    'reason','BATCH_PREPARED','recipientCount',v_eligible_count,
    'distributableWei',v_distributable::text,'remainingPoolWei',v_remainder::text,
    'amountMode','PER_INVITATION_FIXED_RESERVATION',
    'allocationReceiptId',v_receipt.id,
    'rewardCohortRoundId',v_receipt.vebetter_round_id + 1
  );
end;
$$;

revoke all on function public.prepare_reward_cohort_batch(
  text,text,numeric,bigint,integer,integer,numeric,text,jsonb
) from public, anon, authenticated;
grant execute on function public.prepare_reward_cohort_batch(
  text,text,numeric,bigint,integer,integer,numeric,text,jsonb
) to service_role;

commit;
