-- Persistent VeInvite notification history for the production notification center.
-- The history and read receipts are append-only, wallet-scoped through server
-- RPCs, and synchronized with the existing monotonic notification ack state.

begin;

create table public.invite_notification_history (
  id bigint generated by default as identity primary key,
  inviter_wallet text not null,
  invite_code text not null,
  kind text not null,
  stage smallint not null,
  event_at timestamptz not null,
  reward_amount_wei text,
  dapp_progress smallint,
  collapsed_progress boolean not null default false,
  friend_wallet text,
  dedupe_key text not null unique,
  created_at timestamptz not null default now(),
  constraint invite_notification_history_wallet_check
    check (inviter_wallet ~ '^0x[0-9a-f]{40}$'),
  constraint invite_notification_history_code_check
    check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  constraint invite_notification_history_kind_check
    check (kind in (
      'INVITE_ACCEPTED',
      'DAPP_PROGRESS',
      'VOT3_CONVERTED',
      'REWARD_READY',
      'REWARD_PAID',
      'INVITE_INELIGIBLE'
    )),
  constraint invite_notification_history_stage_check
    check (stage between 1 and 6),
  constraint invite_notification_history_dapp_progress_check
    check (dapp_progress is null or dapp_progress between 0 and 3),
  constraint invite_notification_history_reward_amount_check
    check (reward_amount_wei is null or reward_amount_wei ~ '^[0-9]+$'),
  constraint invite_notification_history_friend_wallet_check
    check (friend_wallet is null or friend_wallet ~ '^0x[0-9a-f]{40}$')
);

create index invite_notification_history_wallet_event_idx
  on public.invite_notification_history(inviter_wallet, event_at desc, id desc);

create index invite_notification_history_wallet_id_idx
  on public.invite_notification_history(inviter_wallet, id desc);

create table public.invite_notification_history_reads (
  notification_id bigint primary key
    references public.invite_notification_history(id) on delete restrict,
  inviter_wallet text not null,
  read_at timestamptz not null default now(),
  constraint invite_notification_history_reads_wallet_check
    check (inviter_wallet ~ '^0x[0-9a-f]{40}$')
);

create index invite_notification_history_reads_wallet_idx
  on public.invite_notification_history_reads(inviter_wallet, notification_id desc);

alter table public.invite_notification_history enable row level security;
alter table public.invite_notification_history_reads enable row level security;

revoke all on table public.invite_notification_history from anon, authenticated;
revoke all on table public.invite_notification_history_reads from anon, authenticated;
grant select, insert on table public.invite_notification_history to service_role;
grant select, insert on table public.invite_notification_history_reads to service_role;
grant usage, select on sequence public.invite_notification_history_id_seq to service_role;

create or replace function public.prevent_invite_notification_history_mutation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  raise exception 'invite notification history is append-only';
end;
$$;

create trigger invite_notification_history_append_only
before update or delete on public.invite_notification_history
for each row execute function public.prevent_invite_notification_history_mutation();

create trigger invite_notification_history_reads_append_only
before update or delete on public.invite_notification_history_reads
for each row execute function public.prevent_invite_notification_history_mutation();

create or replace function public.record_invite_notification_history(
  p_inviter_wallet text,
  p_invite_code text,
  p_kind text,
  p_stage integer,
  p_event_at timestamptz,
  p_reward_amount_wei text default null,
  p_dapp_progress integer default null,
  p_collapsed_progress boolean default false,
  p_friend_wallet text default null
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_wallet text := lower(btrim(p_inviter_wallet));
  v_invite_code text := upper(btrim(p_invite_code));
  v_kind text := upper(btrim(p_kind));
  v_friend text := case
    when p_friend_wallet is null or btrim(p_friend_wallet) = '' then null
    else lower(btrim(p_friend_wallet))
  end;
  v_dedupe_key text;
  v_id bigint;
begin
  if v_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'invalid inviter wallet';
  end if;
  if v_invite_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'invalid invite code';
  end if;
  if v_kind not in (
    'INVITE_ACCEPTED',
    'DAPP_PROGRESS',
    'VOT3_CONVERTED',
    'REWARD_READY',
    'REWARD_PAID',
    'INVITE_INELIGIBLE'
  ) then
    raise exception 'invalid notification kind';
  end if;
  if p_stage not between 1 and 6 then
    raise exception 'invalid notification stage';
  end if;
  if p_event_at is null then
    raise exception 'notification event time is required';
  end if;
  if p_dapp_progress is not null and p_dapp_progress not between 0 and 3 then
    raise exception 'invalid dapp progress';
  end if;
  if p_reward_amount_wei is not null and p_reward_amount_wei !~ '^[0-9]+$' then
    raise exception 'invalid reward amount';
  end if;
  if v_friend is not null and v_friend !~ '^0x[0-9a-f]{40}$' then
    raise exception 'invalid friend wallet';
  end if;
  if not exists (
    select 1
    from public.invitations i
    where i.invite_code = v_invite_code
      and lower(i.inviter_wallet) = v_wallet
  ) then
    raise exception 'invitation does not belong to inviter';
  end if;

  v_dedupe_key := concat_ws(
    ':',
    'v2',
    v_invite_code,
    v_kind,
    coalesce(p_dapp_progress::text, '-')
  );

  insert into public.invite_notification_history(
    inviter_wallet,
    invite_code,
    kind,
    stage,
    event_at,
    reward_amount_wei,
    dapp_progress,
    collapsed_progress,
    friend_wallet,
    dedupe_key
  ) values (
    v_wallet,
    v_invite_code,
    v_kind,
    p_stage::smallint,
    p_event_at,
    p_reward_amount_wei,
    p_dapp_progress::smallint,
    coalesce(p_collapsed_progress, false),
    v_friend,
    v_dedupe_key
  )
  on conflict (dedupe_key) do nothing
  returning id into v_id;

  if v_id is null then
    select h.id into v_id
    from public.invite_notification_history h
    where h.dedupe_key = v_dedupe_key
      and h.inviter_wallet = v_wallet
      and h.invite_code = v_invite_code;
  end if;

  if v_id is null then
    raise exception 'notification dedupe collision';
  end if;

  return v_id;
end;
$$;

create or replace function public.get_invite_notification_history(
  p_inviter_wallet text,
  p_before_id bigint default null,
  p_limit integer default 30
)
returns table (
  id bigint,
  invite_code text,
  kind text,
  stage smallint,
  event_at timestamptz,
  reward_amount_wei text,
  dapp_progress smallint,
  collapsed_progress boolean,
  friend_wallet text,
  read_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_wallet text := lower(btrim(p_inviter_wallet));
  v_limit integer := greatest(1, least(coalesce(p_limit, 30), 50));
begin
  if v_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'invalid inviter wallet';
  end if;

  return query
  select
    h.id,
    h.invite_code,
    h.kind,
    h.stage,
    h.event_at,
    h.reward_amount_wei,
    h.dapp_progress,
    h.collapsed_progress,
    h.friend_wallet,
    r.read_at
  from public.invite_notification_history h
  left join public.invite_notification_history_reads r
    on r.notification_id = h.id
   and r.inviter_wallet = v_wallet
  where h.inviter_wallet = v_wallet
    and (p_before_id is null or h.id < p_before_id)
  order by h.id desc
  limit v_limit;
end;
$$;

create or replace function public.count_invite_notification_history_unread(
  p_inviter_wallet text
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_wallet text := lower(btrim(p_inviter_wallet));
  v_count bigint;
begin
  if v_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'invalid inviter wallet';
  end if;

  select count(*) into v_count
  from public.invite_notification_history h
  where h.inviter_wallet = v_wallet
    and not exists (
      select 1
      from public.invite_notification_history_reads r
      where r.notification_id = h.id
        and r.inviter_wallet = v_wallet
    );

  return v_count;
end;
$$;

create or replace function public.acknowledge_invite_notification_history(
  p_inviter_wallet text,
  p_ids bigint[] default null,
  p_through_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_wallet text := lower(btrim(p_inviter_wallet));
  v_row public.invite_notification_history%rowtype;
  v_count integer := 0;
  v_stage integer;
begin
  if v_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'invalid inviter wallet';
  end if;

  if (p_ids is null and p_through_id is null)
     or (p_ids is not null and p_through_id is not null) then
    raise exception 'choose ids or through id';
  end if;

  if p_ids is not null then
    if cardinality(p_ids) < 1 or cardinality(p_ids) > 100 then
      raise exception 'invalid notification id count';
    end if;
  elsif p_through_id is null or p_through_id < 1 then
    raise exception 'invalid through id';
  end if;

  for v_row in
    select h.*
    from public.invite_notification_history h
    where h.inviter_wallet = v_wallet
      and (
        (p_ids is not null and h.id = any(p_ids))
        or (p_through_id is not null and h.id <= p_through_id)
      )
      and not exists (
        select 1
        from public.invite_notification_history_reads r
        where r.notification_id = h.id
      )
    order by h.id
  loop
    insert into public.invite_notification_history_reads(
      notification_id,
      inviter_wallet,
      read_at
    ) values (
      v_row.id,
      v_wallet,
      now()
    )
    on conflict (notification_id) do nothing;

    if found then
      v_stage := case
        when v_row.kind = 'DAPP_PROGRESS'
          and coalesce(v_row.dapp_progress, 0) < 3
        then null
        else v_row.stage
      end;

      perform public.acknowledge_invite_notification_v2(
        v_row.invite_code,
        v_wallet,
        v_stage,
        v_row.dapp_progress,
        v_row.kind = 'REWARD_READY'
      );
      v_count := v_count + 1;
    end if;
  end loop;

  return jsonb_build_object('acknowledged', v_count);
end;
$$;

revoke all on function public.prevent_invite_notification_history_mutation() from public, anon, authenticated;
revoke all on function public.record_invite_notification_history(text,text,text,integer,timestamptz,text,integer,boolean,text) from public, anon, authenticated;
revoke all on function public.get_invite_notification_history(text,bigint,integer) from public, anon, authenticated;
revoke all on function public.count_invite_notification_history_unread(text) from public, anon, authenticated;
revoke all on function public.acknowledge_invite_notification_history(text,bigint[],bigint) from public, anon, authenticated;
grant execute on function public.record_invite_notification_history(text,text,text,integer,timestamptz,text,integer,boolean,text) to service_role;
grant execute on function public.get_invite_notification_history(text,bigint,integer) to service_role;
grant execute on function public.count_invite_notification_history_unread(text) to service_role;
grant execute on function public.acknowledge_invite_notification_history(text,bigint[],bigint) to service_role;

commit;
