-- Read-optimized operator projections. Raw invitation, authentication and usage
-- tables remain authoritative; these rows exist only to make operator status
-- reads bounded and cheap as VeInvite grows.

begin;

create table if not exists public.operator_fast_wallets (
  wallet_address text primary key,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint operator_fast_wallets_address_check
    check (wallet_address ~ '^0x[0-9a-f]{40}$')
);

create table if not exists public.operator_fast_wallet_days (
  usage_date date not null,
  wallet_address text not null,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (usage_date, wallet_address),
  constraint operator_fast_wallet_days_address_check
    check (wallet_address ~ '^0x[0-9a-f]{40}$')
);

create table if not exists public.operator_fast_invitations (
  invitation_id uuid primary key,
  invite_code text not null unique,
  inviter_wallet text not null,
  invitee_wallet text,
  status text not null,
  funnel_bucket text not null,
  entry_class text,
  eligibility_outcome text,
  is_valid_participant boolean not null,
  apps_3_plus boolean not null,
  rewards_3_plus boolean not null,
  vot3_complete boolean not null,
  vote_complete boolean not null,
  all_missions_complete boolean not null,
  source_updated_at timestamptz not null,
  projected_at timestamptz not null default now()
);

create table if not exists public.operator_fast_usage_visitors (
  usage_date date not null,
  visitor_key text not null,
  session_count bigint not null default 0 check (session_count >= 0),
  wallet_connected boolean not null default false,
  returning_visitor boolean not null default false,
  engaged_sessions bigint not null default 0 check (engaged_sessions >= 0),
  view_count bigint not null default 0 check (view_count >= 0),
  total_active_seconds bigint not null default 0 check (total_active_seconds >= 0),
  current_locale text not null,
  last_seen_at timestamptz not null,
  excluded boolean not null default false,
  projected_at timestamptz not null default now(),
  primary key (usage_date, visitor_key),
  constraint operator_fast_usage_visitors_key_check
    check (visitor_key ~ '^[0-9a-f]{64}$'),
  constraint operator_fast_usage_visitors_locale_check
    check (current_locale ~ '^[a-z]{2,3}(-[a-z]{2})?$')
);

create table if not exists public.operator_fast_reconciliation_log (
  id bigint generated by default as identity primary key,
  usage_date date not null,
  metric_rule_version text not null,
  matches boolean not null,
  fast_snapshot jsonb not null,
  source_snapshot jsonb not null,
  details jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now()
);

create index if not exists operator_fast_wallet_days_wallet_idx
  on public.operator_fast_wallet_days (wallet_address, usage_date desc);
create index if not exists operator_fast_invitations_funnel_idx
  on public.operator_fast_invitations (funnel_bucket);
create index if not exists operator_fast_invitations_entry_idx
  on public.operator_fast_invitations (entry_class)
  where is_valid_participant;
create index if not exists operator_fast_usage_visitors_date_visible_idx
  on public.operator_fast_usage_visitors (usage_date, last_seen_at desc)
  where excluded = false;
create index if not exists operator_fast_usage_visitors_date_locale_idx
  on public.operator_fast_usage_visitors (usage_date, current_locale)
  where excluded = false;
create index if not exists operator_fast_reconciliation_log_checked_idx
  on public.operator_fast_reconciliation_log (checked_at desc);

alter table public.operator_fast_wallets enable row level security;
alter table public.operator_fast_wallet_days enable row level security;
alter table public.operator_fast_invitations enable row level security;
alter table public.operator_fast_usage_visitors enable row level security;
alter table public.operator_fast_reconciliation_log enable row level security;

revoke all on table public.operator_fast_wallets from public, anon, authenticated;
revoke all on table public.operator_fast_wallet_days from public, anon, authenticated;
revoke all on table public.operator_fast_invitations from public, anon, authenticated;
revoke all on table public.operator_fast_usage_visitors from public, anon, authenticated;
revoke all on table public.operator_fast_reconciliation_log from public, anon, authenticated;
grant select, insert, update, delete on table public.operator_fast_wallets to service_role;
grant select, insert, update, delete on table public.operator_fast_wallet_days to service_role;
grant select, insert, update, delete on table public.operator_fast_invitations to service_role;
grant select, insert, update, delete on table public.operator_fast_usage_visitors to service_role;
grant select, insert on table public.operator_fast_reconciliation_log to service_role;
grant usage, select on sequence public.operator_fast_reconciliation_log_id_seq to service_role;

create or replace function public.sync_operator_fast_wallet_projection()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_wallet text := lower(btrim(new.wallet_address));
  v_day date := (new.created_at at time zone 'Asia/Seoul')::date;
begin
  if v_wallet !~ '^0x[0-9a-f]{40}$' then return new; end if;

  insert into public.operator_fast_wallets (
    wallet_address, first_seen_at, last_seen_at, updated_at
  ) values (v_wallet, new.created_at, new.created_at, clock_timestamp())
  on conflict (wallet_address) do update
  set first_seen_at = least(public.operator_fast_wallets.first_seen_at, excluded.first_seen_at),
      last_seen_at = greatest(public.operator_fast_wallets.last_seen_at, excluded.last_seen_at),
      updated_at = clock_timestamp();

  insert into public.operator_fast_wallet_days (
    usage_date, wallet_address, first_seen_at, last_seen_at, updated_at
  ) values (v_day, v_wallet, new.created_at, new.created_at, clock_timestamp())
  on conflict (usage_date, wallet_address) do update
  set first_seen_at = least(public.operator_fast_wallet_days.first_seen_at, excluded.first_seen_at),
      last_seen_at = greatest(public.operator_fast_wallet_days.last_seen_at, excluded.last_seen_at),
      updated_at = clock_timestamp();

  return new;
end;
$$;

drop trigger if exists wallet_auth_sessions_sync_operator_fast_projection
  on public.wallet_auth_sessions;
create trigger wallet_auth_sessions_sync_operator_fast_projection
after insert on public.wallet_auth_sessions
for each row execute function public.sync_operator_fast_wallet_projection();

create or replace function public.sync_operator_fast_invitation_projection(
  p_invitation_id uuid
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  r record;
  b text;
  c text;
  o text;
  valid boolean;
begin
  select
    i.id,
    i.invite_code,
    lower(btrim(i.inviter_wallet)) as inviter_wallet,
    case when i.invitee_wallet is null then null else lower(btrim(i.invitee_wallet)) end as invitee_wallet,
    i.status,
    i.apps_completed,
    i.rewards_received,
    i.vot3_converted,
    i.vote_completed,
    i.apps_completed_block,
    i.vot3_converted_block,
    i.vote_completed_block,
    i.eligibility_check_id,
    i.ineligibility_check_id,
    i.updated_at,
    e.entry_class as modern_class,
    e.outcome as modern_outcome,
    l.entry_class as legacy_class,
    l.outcome as legacy_outcome
  into r
  from public.invitations i
  left join public.eligibility_check_events e on e.id = i.eligibility_check_id
  left join lateral (
    select x.entry_class, x.outcome
    from public.legacy_entry_classification_backfill x
    where x.invitation_id = i.id
      and x.classification_status = 'VERIFIED'
    order by x.recorded_at desc, x.id desc
    limit 1
  ) l on true
  where i.id = p_invitation_id;

  if not found then
    delete from public.operator_fast_invitations
    where invitation_id = p_invitation_id;
    return;
  end if;

  c := coalesce(r.modern_class, r.legacy_class);
  o := coalesce(r.modern_outcome, r.legacy_outcome);
  b := case
    when r.ineligibility_check_id is not null then 'INELIGIBLE_LIVE'
    when r.eligibility_check_id is null
      and r.legacy_outcome = 'EXISTING_VEBETTER_USER'
      and r.legacy_class = 'ACTIVE_EXISTING' then 'INELIGIBLE_LEGACY'
    when r.eligibility_check_id is not null
      and r.modern_outcome = 'ELIGIBLE'
      and r.modern_class in ('NEW', 'RETURNING') then 'ACCEPTED_MODERN'
    when r.eligibility_check_id is null
      and r.invitee_wallet is not null
      and r.legacy_outcome = 'ELIGIBLE'
      and r.legacy_class in ('NEW', 'RETURNING') then 'ACCEPTED_LEGACY'
    when r.status = 'PENDING_ACCEPTANCE' then 'PENDING_ACCEPTANCE'
    when r.status = 'CANCELLED' then 'CANCELLED_BY_INVITER'
    when r.invitee_wallet is not null and r.eligibility_check_id is null then 'LEGACY_UNCLASSIFIED'
    else 'OTHER'
  end;
  valid := b in ('ACCEPTED_MODERN', 'ACCEPTED_LEGACY');

  insert into public.operator_fast_invitations (
    invitation_id, invite_code, inviter_wallet, invitee_wallet, status,
    funnel_bucket, entry_class, eligibility_outcome, is_valid_participant,
    apps_3_plus, rewards_3_plus, vot3_complete, vote_complete,
    all_missions_complete, source_updated_at, projected_at
  ) values (
    r.id, r.invite_code, r.inviter_wallet, r.invitee_wallet, r.status,
    b, c, o, valid,
    valid and coalesce(r.apps_completed, 0) >= 3
      and (r.eligibility_check_id is null or r.apps_completed_block is not null),
    valid and coalesce(r.rewards_received, 0) >= 3,
    valid and coalesce(r.vot3_converted, false)
      and (r.eligibility_check_id is null or r.vot3_converted_block is not null),
    valid and coalesce(r.vote_completed, false)
      and (r.eligibility_check_id is null or r.vote_completed_block is not null),
    valid and coalesce(r.apps_completed, 0) >= 3
      and coalesce(r.rewards_received, 0) >= 3
      and coalesce(r.vot3_converted, false)
      and coalesce(r.vote_completed, false)
      and (
        r.eligibility_check_id is null
        or (
          r.apps_completed_block is not null
          and r.vot3_converted_block is not null
          and r.vote_completed_block is not null
        )
      ),
    r.updated_at, clock_timestamp()
  )
  on conflict (invitation_id) do update
  set invite_code = excluded.invite_code,
      inviter_wallet = excluded.inviter_wallet,
      invitee_wallet = excluded.invitee_wallet,
      status = excluded.status,
      funnel_bucket = excluded.funnel_bucket,
      entry_class = excluded.entry_class,
      eligibility_outcome = excluded.eligibility_outcome,
      is_valid_participant = excluded.is_valid_participant,
      apps_3_plus = excluded.apps_3_plus,
      rewards_3_plus = excluded.rewards_3_plus,
      vot3_complete = excluded.vot3_complete,
      vote_complete = excluded.vote_complete,
      all_missions_complete = excluded.all_missions_complete,
      source_updated_at = excluded.source_updated_at,
      projected_at = clock_timestamp();
end;
$$;

create or replace function public.trigger_sync_operator_fast_invitation_projection()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  perform public.sync_operator_fast_invitation_projection(
    case when tg_op = 'DELETE' then old.id else new.id end
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists invitations_sync_operator_fast_projection on public.invitations;
create trigger invitations_sync_operator_fast_projection
after insert or update or delete on public.invitations
for each row execute function public.trigger_sync_operator_fast_invitation_projection();

create or replace function public.trigger_sync_operator_fast_legacy_projection()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  perform public.sync_operator_fast_invitation_projection(
    case when tg_op = 'DELETE' then old.invitation_id else new.invitation_id end
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists legacy_entry_sync_operator_fast_projection
  on public.legacy_entry_classification_backfill;
create trigger legacy_entry_sync_operator_fast_projection
after insert or update or delete on public.legacy_entry_classification_backfill
for each row execute function public.trigger_sync_operator_fast_legacy_projection();

create or replace function public.sync_operator_fast_usage_projection()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  d date := (new.started_at at time zone 'Asia/Seoul')::date;
  x boolean;
begin
  select exists (
    select 1 from public.app_usage_excluded_visitors e
    where e.visitor_key = new.visitor_key
  ) into x;

  insert into public.operator_fast_usage_visitors (
    usage_date, visitor_key, session_count, wallet_connected,
    returning_visitor, engaged_sessions, view_count, total_active_seconds,
    current_locale, last_seen_at, excluded, projected_at
  )
  select
    d,
    s.visitor_key,
    count(*)::bigint,
    bool_or(s.wallet_connected),
    bool_or(s.returning_visitor),
    count(*) filter (where s.active_seconds >= 30)::bigint,
    coalesce(sum(s.view_count), 0)::bigint,
    coalesce(sum(s.active_seconds), 0)::bigint,
    (array_agg(
      s.current_locale
      order by s.last_seen_at desc, s.updated_at desc, s.session_id desc
    ))[1],
    max(s.last_seen_at),
    x,
    clock_timestamp()
  from public.app_usage_sessions s
  where s.visitor_key = new.visitor_key
    and (s.started_at at time zone 'Asia/Seoul')::date = d
  group by s.visitor_key
  on conflict (usage_date, visitor_key) do update
  set session_count = excluded.session_count,
      wallet_connected = excluded.wallet_connected,
      returning_visitor = excluded.returning_visitor,
      engaged_sessions = excluded.engaged_sessions,
      view_count = excluded.view_count,
      total_active_seconds = excluded.total_active_seconds,
      current_locale = excluded.current_locale,
      last_seen_at = excluded.last_seen_at,
      excluded = excluded.excluded,
      projected_at = clock_timestamp();

  return new;
end;
$$;

drop trigger if exists app_usage_sessions_sync_operator_fast_projection
  on public.app_usage_sessions;
create trigger app_usage_sessions_sync_operator_fast_projection
after insert or update of
  last_seen_at, active_seconds, view_count, current_locale,
  wallet_connected, returning_visitor
on public.app_usage_sessions
for each row execute function public.sync_operator_fast_usage_projection();

create or replace function public.mark_operator_fast_usage_visitor_excluded()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  update public.operator_fast_usage_visitors
  set excluded = true,
      projected_at = clock_timestamp()
  where visitor_key = new.visitor_key;
  return new;
end;
$$;

drop trigger if exists app_usage_excluded_visitors_sync_operator_fast_projection
  on public.app_usage_excluded_visitors;
create trigger app_usage_excluded_visitors_sync_operator_fast_projection
after insert on public.app_usage_excluded_visitors
for each row execute function public.mark_operator_fast_usage_visitor_excluded();

create or replace function public.rebuild_operator_fast_projections()
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_wallets bigint;
  v_days bigint;
  v_invitations bigint;
  v_usage bigint;
  v_invitation_id uuid;
begin
  delete from public.operator_fast_wallets;
  delete from public.operator_fast_wallet_days;
  delete from public.operator_fast_invitations;
  delete from public.operator_fast_usage_visitors;

  with e as (
    select lower(btrim(wallet_address)) as wallet_address, created_at as occurred_at
    from public.wallet_auth_sessions
    where lower(btrim(wallet_address)) ~ '^0x[0-9a-f]{40}$'
    union
    select lower(btrim(wallet_address)), occurred_at
    from public.veinvite_event_ledger
    where event_type = 'WALLET_AUTHENTICATED'
      and wallet_address is not null
      and lower(btrim(wallet_address)) ~ '^0x[0-9a-f]{40}$'
  )
  insert into public.operator_fast_wallets
  select wallet_address, min(occurred_at), max(occurred_at), clock_timestamp()
  from e group by wallet_address;
  get diagnostics v_wallets = row_count;

  with e as (
    select lower(btrim(wallet_address)) as wallet_address, created_at as occurred_at
    from public.wallet_auth_sessions
    where lower(btrim(wallet_address)) ~ '^0x[0-9a-f]{40}$'
    union
    select lower(btrim(wallet_address)), occurred_at
    from public.veinvite_event_ledger
    where event_type = 'WALLET_AUTHENTICATED'
      and wallet_address is not null
      and lower(btrim(wallet_address)) ~ '^0x[0-9a-f]{40}$'
  )
  insert into public.operator_fast_wallet_days
  select
    (occurred_at at time zone 'Asia/Seoul')::date,
    wallet_address,
    min(occurred_at),
    max(occurred_at),
    clock_timestamp()
  from e group by 1, 2;
  get diagnostics v_days = row_count;

  for v_invitation_id in select id from public.invitations loop
    perform public.sync_operator_fast_invitation_projection(v_invitation_id);
  end loop;
  select count(*) into v_invitations from public.operator_fast_invitations;

  insert into public.operator_fast_usage_visitors
  select
    (s.started_at at time zone 'Asia/Seoul')::date,
    s.visitor_key,
    count(*)::bigint,
    bool_or(s.wallet_connected),
    bool_or(s.returning_visitor),
    count(*) filter (where s.active_seconds >= 30)::bigint,
    coalesce(sum(s.view_count), 0)::bigint,
    coalesce(sum(s.active_seconds), 0)::bigint,
    (array_agg(
      s.current_locale
      order by s.last_seen_at desc, s.updated_at desc, s.session_id desc
    ))[1],
    max(s.last_seen_at),
    exists (
      select 1 from public.app_usage_excluded_visitors x
      where x.visitor_key = s.visitor_key
    ),
    clock_timestamp()
  from public.app_usage_sessions s
  group by 1, s.visitor_key;
  get diagnostics v_usage = row_count;

  return jsonb_build_object(
    'wallets', v_wallets,
    'walletDays', v_days,
    'invitations', v_invitations,
    'usageVisitors', v_usage,
    'rebuiltAt', clock_timestamp()
  );
end;
$$;

create or replace function public.read_operator_fast_status(
  p_usage_date date default ((now() at time zone 'Asia/Seoul')::date)
)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with x as (
  select wallet_address from public.analytics_excluded_wallets where active
), vi as (
  select p.*
  from public.operator_fast_invitations p
  where not exists (
    select 1 from x
    where wallet_address = p.inviter_wallet
       or wallet_address = p.invitee_wallet
  )
), im as (
  select
    count(*)::bigint as total,
    count(*) filter (where funnel_bucket = 'PENDING_ACCEPTANCE')::bigint as pending,
    count(*) filter (where funnel_bucket in ('INELIGIBLE_LIVE','INELIGIBLE_LEGACY'))::bigint as ineligible,
    count(*) filter (where funnel_bucket = 'CANCELLED_BY_INVITER')::bigint as cancelled,
    count(*) filter (where funnel_bucket = 'LEGACY_UNCLASSIFIED')::bigint as legacy,
    count(*) filter (where is_valid_participant)::bigint as valid,
    count(*) filter (where is_valid_participant and entry_class = 'NEW')::bigint as new_count,
    count(*) filter (where is_valid_participant and entry_class = 'RETURNING')::bigint as returning_count,
    count(*) filter (where apps_3_plus)::bigint as apps,
    count(*) filter (where rewards_3_plus)::bigint as rewards,
    count(*) filter (where vot3_complete)::bigint as vot3,
    count(*) filter (where vote_complete)::bigint as vote,
    count(*) filter (where all_missions_complete)::bigint as complete
  from vi
), u as (
  select
    count(*)::bigint as uv,
    count(*) filter (where not returning_visitor)::bigint as nv,
    count(*) filter (where returning_visitor)::bigint as rv,
    coalesce(sum(session_count),0)::bigint as sessions,
    count(*) filter (where wallet_connected)::bigint as connected,
    coalesce(sum(engaged_sessions),0)::bigint as engaged,
    coalesce(sum(view_count),0)::bigint as views,
    coalesce(sum(total_active_seconds),0)::bigint as seconds,
    case when coalesce(sum(session_count),0)=0 then 0::numeric
      else round(coalesce(sum(total_active_seconds),0)::numeric/sum(session_count)::numeric,1)
    end as avg_seconds,
    max(last_seen_at) as latest
  from public.operator_fast_usage_visitors
  where usage_date = p_usage_date and not excluded
), l as (
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'locale', current_locale,
        'uniqueVisitors', n,
        'sessions', s,
        'totalActiveSeconds', a
      ) order by n desc, current_locale
    ), '[]'::jsonb
  ) as value
  from (
    select
      current_locale,
      count(*)::bigint as n,
      coalesce(sum(session_count),0)::bigint as s,
      coalesce(sum(total_active_seconds),0)::bigint as a
    from public.operator_fast_usage_visitors
    where usage_date = p_usage_date and not excluded
    group by current_locale
  ) q
)
select jsonb_build_object(
  'metricRuleVersion','operator-fast-v1',
  'timezone','Asia/Seoul',
  'usageDate',p_usage_date,
  'generatedAt',now(),
  'users',jsonb_build_object(
    'authenticatedWalletsEver',(select count(*) from public.operator_fast_wallets w where not exists(select 1 from x where wallet_address=w.wallet_address)),
    'authenticatedWalletsToday',(select count(*) from public.operator_fast_wallet_days w where usage_date=p_usage_date and not exists(select 1 from x where wallet_address=w.wallet_address)),
    'invitationsTotal',im.total,
    'pendingAcceptance',im.pending,
    'ineligibleRejections',im.ineligible,
    'cancelledByInviter',im.cancelled,
    'legacyUnclassified',im.legacy,
    'validParticipants',im.valid,
    'new',im.new_count,
    'returning',im.returning_count,
    'apps3Plus',im.apps,
    'rewards3Plus',im.rewards,
    'vot3Complete',im.vot3,
    'voteComplete',im.vote,
    'allMissionsComplete',im.complete
  ),
  'visitors',jsonb_build_object(
    'uniqueVisitors',u.uv,
    'newVisitors',u.nv,
    'returningVisitors',u.rv,
    'sessions',u.sessions,
    'walletConnectedVisitors',u.connected,
    'engagedSessions',u.engaged,
    'viewCount',u.views,
    'totalActiveSeconds',u.seconds,
    'averageActiveSeconds',u.avg_seconds,
    'latestSeenAt',u.latest,
    'locales',l.value
  )
)
from im cross join u cross join l;
$$;

revoke all on function public.sync_operator_fast_wallet_projection()
  from public, anon, authenticated;
revoke all on function public.sync_operator_fast_invitation_projection(uuid)
  from public, anon, authenticated;
revoke all on function public.trigger_sync_operator_fast_invitation_projection()
  from public, anon, authenticated;
revoke all on function public.trigger_sync_operator_fast_legacy_projection()
  from public, anon, authenticated;
revoke all on function public.sync_operator_fast_usage_projection()
  from public, anon, authenticated;
revoke all on function public.mark_operator_fast_usage_visitor_excluded()
  from public, anon, authenticated;
revoke all on function public.rebuild_operator_fast_projections()
  from public, anon, authenticated;
revoke all on function public.read_operator_fast_status(date)
  from public, anon, authenticated;
grant execute on function public.rebuild_operator_fast_projections() to service_role;
grant execute on function public.read_operator_fast_status(date) to service_role;

select public.rebuild_operator_fast_projections();

commit;
