create table if not exists public.invite_impact_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  invite_code text not null references public.invitations(invite_code) on delete cascade,
  network text not null,
  wallet_address text not null,
  event_type text not null,
  tx_id text not null,
  block_number bigint not null,
  block_timestamp timestamptz not null,
  app_id text,
  vote_round_id bigint,
  detected_at timestamptz not null default now(),
  constraint invite_impact_events_network_check check (network in ('mainnet','testnet','testnet-staging')),
  constraint invite_impact_events_wallet_check check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  constraint invite_impact_events_type_check check (event_type in ('DAPP_REWARD','ALLOCATION_VOTE')),
  constraint invite_impact_events_tx_check check (tx_id ~ '^0x[0-9a-f]{64}$'),
  constraint invite_impact_events_block_check check (block_number >= 0),
  constraint invite_impact_events_app_check check (app_id is null or app_id ~ '^0x[0-9a-f]{64}$'),
  constraint invite_impact_events_round_check check (vote_round_id is null or vote_round_id >= 0),
  constraint invite_impact_events_shape_check check (
    (event_type = 'DAPP_REWARD' and app_id is not null and vote_round_id is null)
    or
    (event_type = 'ALLOCATION_VOTE' and app_id is null and vote_round_id is not null)
  )
);

create index if not exists invite_impact_events_timestamp_idx
  on public.invite_impact_events(block_timestamp desc);
create index if not exists invite_impact_events_wallet_timestamp_idx
  on public.invite_impact_events(wallet_address, block_timestamp desc);
create index if not exists invite_impact_events_invite_idx
  on public.invite_impact_events(invite_code, block_timestamp asc);

alter table public.invite_impact_events enable row level security;
revoke all on table public.invite_impact_events from public, anon, authenticated;
grant select, insert, update, delete on table public.invite_impact_events to service_role;
grant usage, select on sequence public.invite_impact_events_id_seq to service_role;

create or replace view public.operator_weekly_impact
with (security_invoker = true)
as
with week_keys as (
  select date_trunc('week', activated_at) as week_start
  from public.invitations
  where activated_at is not null
  union
  select date_trunc('week', block_timestamp)
  from public.invite_impact_events
  union
  select date_trunc('week', paid_at)
  from public.reward_payouts
  where paid_at is not null and status = 'PAID'
),
wallets as (
  select
    date_trunc('week', activated_at) as week_start,
    count(distinct invitee_wallet) as new_wallets_onboarded
  from public.invitations
  where activated_at is not null and invitee_wallet is not null
  group by 1
),
completions as (
  select
    date_trunc('week', vote_completed_at) as week_start,
    count(*) as successful_referrals_completed
  from public.invitations
  where vote_completed_at is not null
    and vote_completed = true
  group by 1
),
impact as (
  select
    date_trunc('week', block_timestamp) as week_start,
    count(distinct tx_id) as verified_onboarding_transactions,
    count(distinct tx_id) filter (where event_type = 'DAPP_REWARD') as verified_dapp_reward_transactions,
    count(*) filter (where event_type = 'DAPP_REWARD') as verified_dapp_reward_events,
    count(distinct tx_id) filter (where event_type = 'ALLOCATION_VOTE') as governance_vote_transactions,
    count(distinct wallet_address) as active_onboarded_wallets
  from public.invite_impact_events
  group by 1
),
payouts as (
  select
    date_trunc('week', paid_at) as week_start,
    count(*) as paid_referral_rewards,
    count(distinct recipient_wallet) as rewarded_wallets,
    coalesce(sum(amount_wei), 0::numeric) as b3tr_distributed_wei
  from public.reward_payouts
  where status = 'PAID' and paid_at is not null
  group by 1
)
select
  wk.week_start,
  wk.week_start + interval '7 days' as week_end,
  coalesce(w.new_wallets_onboarded, 0)::bigint as new_wallets_onboarded,
  coalesce(c.successful_referrals_completed, 0)::bigint as successful_referrals_completed,
  coalesce(i.active_onboarded_wallets, 0)::bigint as active_onboarded_wallets,
  coalesce(i.verified_onboarding_transactions, 0)::bigint as verified_onboarding_transactions,
  coalesce(i.verified_dapp_reward_transactions, 0)::bigint as verified_dapp_reward_transactions,
  coalesce(i.verified_dapp_reward_events, 0)::bigint as verified_dapp_reward_events,
  coalesce(i.governance_vote_transactions, 0)::bigint as governance_vote_transactions,
  coalesce(p.paid_referral_rewards, 0)::bigint as paid_referral_rewards,
  coalesce(p.rewarded_wallets, 0)::bigint as rewarded_wallets,
  coalesce(p.b3tr_distributed_wei, 0::numeric) as b3tr_distributed_wei,
  coalesce(p.b3tr_distributed_wei, 0::numeric) / 1000000000000000000::numeric as b3tr_distributed
from week_keys wk
left join wallets w using (week_start)
left join completions c using (week_start)
left join impact i using (week_start)
left join payouts p using (week_start)
order by wk.week_start desc;

revoke all on table public.operator_weekly_impact from public, anon, authenticated;
grant select on table public.operator_weekly_impact to service_role;