create table public.referral_slot_assignments (
    id bigint generated by default as identity primary key,
    relationship_id uuid not null references public.referral_relationships(id) on delete restrict,
    parent_wallet text not null,
    child_wallet text not null,
    slot integer not null,
    assignment_version text not null,
    assigned_at timestamptz not null default now(),
    assigned_by text not null,
    source_snapshot jsonb not null default '{}'::jsonb,
    constraint referral_slot_assignments_slot_check check (slot > 0),
    constraint referral_slot_assignments_parent_wallet_check check (parent_wallet ~ '^0x[0-9a-f]{40}$'),
    constraint referral_slot_assignments_child_wallet_check check (child_wallet ~ '^0x[0-9a-f]{40}$'),
    constraint referral_slot_assignments_different_wallets_check check (parent_wallet <> child_wallet),
    constraint referral_slot_assignments_assignment_version_check check (length(btrim(assignment_version)) > 0),
    constraint referral_slot_assignments_assigned_by_check check (length(btrim(assigned_by)) > 0),
    constraint referral_slot_assignments_source_snapshot_object_check check (jsonb_typeof(source_snapshot) = 'object'),
    constraint referral_slot_assignments_relationship_key unique (relationship_id)
);

create unique index referral_slot_assignments_parent_slot_key
    on public.referral_slot_assignments (lower(parent_wallet), slot);
create index referral_slot_assignments_child_idx
    on public.referral_slot_assignments (lower(child_wallet));

alter table public.referral_slot_assignments enable row level security;
revoke all on table public.referral_slot_assignments from public, anon, authenticated;
revoke all on sequence public.referral_slot_assignments_id_seq from public, anon, authenticated;
grant select, insert on table public.referral_slot_assignments to service_role;
grant usage, select on sequence public.referral_slot_assignments_id_seq to service_role;

create or replace function public.validate_referral_slot_assignment()
returns trigger
language plpgsql
set search_path to 'pg_catalog', 'public'
as $$
declare
    v_parent text;
    v_child text;
begin
    select lower(parent_wallet), lower(child_wallet)
      into v_parent, v_child
    from public.referral_relationships
    where id = new.relationship_id;

    if not found then
        raise exception 'referral relationship % does not exist', new.relationship_id;
    end if;

    if lower(btrim(new.parent_wallet)) <> v_parent
       or lower(btrim(new.child_wallet)) <> v_child then
        raise exception 'slot assignment wallets do not match canonical referral relationship';
    end if;

    new.parent_wallet := v_parent;
    new.child_wallet := v_child;
    return new;
end;
$$;
revoke all on function public.validate_referral_slot_assignment() from public, anon, authenticated, service_role;
create trigger referral_slot_assignments_validate
before insert on public.referral_slot_assignments
for each row execute function public.validate_referral_slot_assignment();

create or replace function public.prevent_referral_slot_assignment_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog', 'public'
as $$
begin
    raise exception 'referral_slot_assignments is append-only; update/delete is not permitted';
end;
$$;
revoke all on function public.prevent_referral_slot_assignment_mutation() from public, anon, authenticated, service_role;
create trigger referral_slot_assignments_append_only_update
before update on public.referral_slot_assignments
for each row execute function public.prevent_referral_slot_assignment_mutation();
create trigger referral_slot_assignments_append_only_delete
before delete on public.referral_slot_assignments
for each row execute function public.prevent_referral_slot_assignment_mutation();

create or replace function public.prevent_referral_relationship_cycle()
returns trigger
language plpgsql
set search_path to 'pg_catalog', 'public'
as $$
begin
    if lower(new.parent_wallet) = lower(new.child_wallet) then
        raise exception 'referral relationship cannot link a wallet to itself';
    end if;
    if exists (
        with recursive ancestors(wallet) as (
            select lower(new.parent_wallet)
            union
            select lower(r.parent_wallet)
            from public.referral_relationships r
            join ancestors a on lower(r.child_wallet) = a.wallet
        )
        select 1 from ancestors where wallet = lower(new.child_wallet)
    ) then
        raise exception 'referral relationship would create a cycle';
    end if;
    return new;
end;
$$;

create or replace function public.prevent_referral_relationship_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog', 'public'
as $$
begin
    raise exception 'referral_relationships is append-only; update/delete is not permitted';
end;
$$;

create or replace function public.capture_referral_network_snapshot(p_snapshot_type text default 'INTEGRITY'::text)
returns bigint
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
as $$
declare
    v_id bigint;
    v_relationship_count integer;
    v_unique_parent_count integer;
    v_unique_child_count integer;
    v_qualifying_invitation_count integer;
    v_missing_ledger_count integer;
    v_source_mismatch_count integer;
    v_cycle_count integer;
    v_missing_network_count integer;
    v_missing_activation_block_count integer;
    v_fingerprint text;
begin
    if p_snapshot_type not in ('BASELINE', 'INTEGRITY', 'MANUAL') then
        raise exception 'invalid snapshot type: %', p_snapshot_type;
    end if;

    select count(*)::integer,
           count(distinct lower(parent_wallet))::integer,
           count(distinct lower(child_wallet))::integer,
           count(*) filter (where network is null)::integer,
           count(*) filter (where relationship_effective_block is null)::integer,
           md5(coalesce(string_agg(
               lower(parent_wallet) || '>' || lower(child_wallet)
               || '@' || source_invitation_id::text
               || '#' || coalesce(source_invite_code, '')
               || '#' || relationship_effective_at::text
               || '#' || coalesce(relationship_effective_block::text, '')
               || '#' || coalesce(network, '')
               || '#' || rule_version,
               '|' order by lower(parent_wallet), lower(child_wallet), source_invitation_id::text
           ), ''))
      into v_relationship_count, v_unique_parent_count, v_unique_child_count,
           v_missing_network_count, v_missing_activation_block_count, v_fingerprint
    from public.referral_relationships;

    select count(*)::integer into v_qualifying_invitation_count
    from public.invitations i
    where i.invitee_wallet is not null
      and i.activated_at is not null
      and i.status in ('UNDER_REVIEW', 'ACTIVATING', 'COMPLETED');

    select count(*)::integer into v_missing_ledger_count
    from public.invitations i
    where i.invitee_wallet is not null
      and i.activated_at is not null
      and i.status in ('UNDER_REVIEW', 'ACTIVATING', 'COMPLETED')
      and not exists (select 1 from public.referral_relationships r where r.source_invitation_id = i.id);

    with expected as (
        select i.id,
               lower(btrim(i.inviter_wallet)) as parent_wallet,
               lower(btrim(i.invitee_wallet)) as child_wallet,
               i.invite_code,
               i.activated_at,
               i.activation_block,
               coalesce(i.activation_network, e.network) as expected_network
        from public.invitations i
        left join lateral (
            select ee.network
            from public.eligibility_check_events ee
            where (i.eligibility_check_id is not null and ee.id = i.eligibility_check_id)
               or (i.eligibility_check_id is null and ee.invite_code = i.invite_code)
            order by case when i.eligibility_check_id is not null and ee.id = i.eligibility_check_id then 0 else 1 end,
                     ee.created_at desc, ee.id desc
            limit 1
        ) e on true
    )
    select count(*)::integer into v_source_mismatch_count
    from public.referral_relationships r
    join expected x on x.id = r.source_invitation_id
    where x.parent_wallet <> lower(r.parent_wallet)
       or x.child_wallet <> lower(r.child_wallet)
       or x.invite_code is distinct from r.source_invite_code
       or x.activated_at is distinct from r.relationship_effective_at
       or x.activation_block is distinct from r.relationship_effective_block
       or x.expected_network is distinct from r.network;

    with recursive reach(ancestor, descendant) as (
        select lower(parent_wallet), lower(child_wallet) from public.referral_relationships
        union
        select reach.ancestor, lower(r.child_wallet)
        from reach join public.referral_relationships r on lower(r.parent_wallet) = reach.descendant
    )
    select count(*)::integer into v_cycle_count from reach where ancestor = descendant;

    insert into public.referral_network_snapshots (
        snapshot_type, rule_version, relationship_count, unique_parent_count,
        unique_child_count, qualifying_invitation_count, missing_ledger_count,
        source_mismatch_count, cycle_count, missing_network_count,
        missing_activation_block_count, relationship_fingerprint, details
    ) values (
        p_snapshot_type, 'v1_single_invite', v_relationship_count,
        v_unique_parent_count, v_unique_child_count, v_qualifying_invitation_count,
        v_missing_ledger_count, v_source_mismatch_count, v_cycle_count,
        v_missing_network_count, v_missing_activation_block_count, v_fingerprint,
        jsonb_build_object(
            'slot_policy', 'assignments_are_separate_append_only_records',
            'canonical_rule', 'invitee_wallet + activated_at + active lifecycle status',
            'fingerprint_version', 'v2_full_relationship_identity',
            'source_comparison', 'wallets + invite_code + activated_at + activation_block + resolved_network',
            'captured_by', 'database_integrity_function'
        )
    ) returning id into v_id;
    return v_id;
end;
$$;
revoke all on function public.capture_referral_network_snapshot(text) from public, anon, authenticated;
grant execute on function public.capture_referral_network_snapshot(text) to service_role;
