-- Store the exact dApp allocation(s) used by a referred wallet's
-- mission-qualifying VeBetterDAO allocation vote.
--
-- This table is analytics/audit-only. Mission eligibility and rewards remain
-- authoritative in the existing invitation / impact evidence flow.

create table if not exists public.invite_vote_allocations (
  id bigint generated by default as identity primary key,
  invitation_id uuid references public.invitations(id) on delete set null,
  invite_code text,
  network text not null,
  wallet_address text not null,
  tx_id text not null,
  block_number bigint,
  clause_index integer not null,
  round_id bigint,
  allocation_index integer not null,
  app_id text not null,
  vote_weight numeric(78, 0) not null,
  vote_kind text not null default 'MISSION_QUALIFYING',
  occurred_at timestamptz,
  created_at timestamptz not null default now(),

  constraint invite_vote_allocations_allocation_index_check
    check (allocation_index >= 0),
  constraint invite_vote_allocations_vote_weight_check
    check (vote_weight >= 0),
  constraint invite_vote_allocations_vote_kind_check
    check (vote_kind in ('MISSION_QUALIFYING', 'SUBSEQUENT')),
  constraint invite_vote_allocations_tx_shape_check
    check (tx_id ~ '^0x[0-9a-fA-F]{64}$'),
  constraint invite_vote_allocations_unique_allocation
    unique (network, tx_id, clause_index, allocation_index)
);

create index if not exists invite_vote_allocations_invitation_id_idx
  on public.invite_vote_allocations (invitation_id);

create index if not exists invite_vote_allocations_app_id_idx
  on public.invite_vote_allocations (app_id);

create index if not exists invite_vote_allocations_wallet_round_idx
  on public.invite_vote_allocations (wallet_address, round_id);

alter table public.invite_vote_allocations enable row level security;

comment on table public.invite_vote_allocations is
  'Server-only analytics/audit rows for dApp allocations in VeInvite-referred users'' governance votes. This table must not gate mission or reward eligibility.';
