begin;

create table if not exists public.sybil_v2_referral_assessments (
  invite_code text primary key
    references public.invitations(invite_code) on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  state text not null
    check (state in ('ANALYSIS_PENDING','ANALYSIS_FAILED','CLEAR','WATCH','HOLD','RESTRICTED')),
  risk_score integer not null default 0
    check (risk_score between 0 and 100),
  policy_version text not null,
  analyzer_version text not null,
  revision bigint not null default 1
    check (revision >= 1),
  evidence_cutoff_block bigint
    check (evidence_cutoff_block is null or evidence_cutoff_block >= 0),
  required_checks jsonb not null default '[]'::jsonb
    check (jsonb_typeof(required_checks) = 'array'),
  completed_checks jsonb not null default '[]'::jsonb
    check (jsonb_typeof(completed_checks) = 'array'),
  reason_codes jsonb not null default '[]'::jsonb
    check (jsonb_typeof(reason_codes) = 'array'),
  evidence_summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(evidence_summary) = 'object'),
  source text not null default 'SYSTEM'
    check (source in ('SYSTEM','OPERATOR')),
  assessed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sybil_v2_referral_assessments_state_idx
  on public.sybil_v2_referral_assessments(network, state, updated_at);

create table if not exists public.sybil_v2_assessment_events (
  id bigint generated by default as identity primary key,
  invite_code text not null
    references public.invitations(invite_code) on update cascade on delete restrict,
  network text not null,
  state text not null,
  risk_score integer not null,
  policy_version text not null,
  analyzer_version text not null,
  revision bigint not null,
  evidence_cutoff_block bigint,
  required_checks jsonb not null,
  completed_checks jsonb not null,
  reason_codes jsonb not null,
  evidence_summary jsonb not null,
  source text not null,
  created_at timestamptz not null default now(),
  unique(invite_code, revision)
);

create index if not exists sybil_v2_assessment_events_invite_idx
  on public.sybil_v2_assessment_events(invite_code, revision desc);

create table if not exists public.sybil_v2_evidence_records (
  id bigint generated by default as identity primary key,
  invite_code text not null
    references public.invitations(invite_code) on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  subject_wallet text not null
    check (subject_wallet ~ '^0x[0-9a-f]{40}$'),
  evidence_family text not null
    check (evidence_family in (
      'FUNDING',
      'HISTORICAL_REWARD',
      'HISTORICAL_CONSOLIDATION',
      'MISSION_BEHAVIOR',
      'SECURITY_IDENTITY',
      'POST_PAYOUT',
      'CLUSTER_LINK'
    )),
  signal_code text not null,
  strength text not null
    check (strength in ('INFO','LOW','MEDIUM','HIGH')),
  score integer not null default 0
    check (score between 0 and 100),
  related_wallet text
    check (related_wallet is null or related_wallet ~ '^0x[0-9a-f]{40}$'),
  app_id text
    check (app_id is null or app_id ~ '^0x[0-9a-f]{64}$'),
  observed_block bigint
    check (observed_block is null or observed_block >= 0),
  observed_at timestamptz,
  analyzer_version text not null,
  evidence jsonb not null default '{}'::jsonb
    check (jsonb_typeof(evidence) = 'object'),
  dedupe_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists sybil_v2_evidence_subject_idx
  on public.sybil_v2_evidence_records(network, subject_wallet, evidence_family, created_at desc);
create index if not exists sybil_v2_evidence_related_wallet_idx
  on public.sybil_v2_evidence_records(network, related_wallet)
  where related_wallet is not null;
create index if not exists sybil_v2_evidence_app_idx
  on public.sybil_v2_evidence_records(network, app_id)
  where app_id is not null;

create table if not exists public.sybil_v2_historical_reward_events (
  id bigint generated by default as identity primary key,
  invite_code text not null
    references public.invitations(invite_code) on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  wallet_address text not null
    check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  app_id text not null
    check (app_id ~ '^0x[0-9a-f]{64}$'),
  block_number bigint not null check (block_number >= 0),
  block_timestamp timestamptz,
  tx_id text not null check (tx_id ~ '^0x[0-9a-f]{64}$'),
  amount_wei numeric(78,0) not null default 0 check (amount_wei >= 0),
  analyzer_version text not null,
  created_at timestamptz not null default now(),
  unique(invite_code, tx_id, app_id)
);

create index if not exists sybil_v2_historical_reward_app_block_idx
  on public.sybil_v2_historical_reward_events(network, app_id, block_number);
create index if not exists sybil_v2_historical_reward_wallet_idx
  on public.sybil_v2_historical_reward_events(network, wallet_address, block_number);

create table if not exists public.sybil_v2_preactivation_b3tr_outflows (
  id bigint generated by default as identity primary key,
  invite_code text not null
    references public.invitations(invite_code) on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  wallet_address text not null
    check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  destination_wallet text not null
    check (destination_wallet ~ '^0x[0-9a-f]{40}$'),
  block_number bigint not null check (block_number >= 0),
  block_timestamp timestamptz,
  tx_id text not null check (tx_id ~ '^0x[0-9a-f]{64}$'),
  amount_wei numeric(78,0) not null check (amount_wei > 0),
  analyzer_version text not null,
  created_at timestamptz not null default now(),
  unique(invite_code, tx_id, destination_wallet, amount_wei)
);

create index if not exists sybil_v2_preactivation_b3tr_destination_idx
  on public.sybil_v2_preactivation_b3tr_outflows(network, destination_wallet, block_number);
create index if not exists sybil_v2_preactivation_b3tr_wallet_idx
  on public.sybil_v2_preactivation_b3tr_outflows(network, wallet_address, block_number);

create table if not exists public.sybil_v2_scan_checkpoints (
  invite_code text primary key
    references public.invitations(invite_code) on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  activation_block bigint not null check (activation_block > 0),
  historical_chain_status text not null default 'PENDING'
    check (historical_chain_status in ('PENDING','COMPLETE','FAILED')),
  funding_chain_status text not null default 'PENDING'
    check (funding_chain_status in ('PENDING','COMPLETE','FAILED')),
  historical_reward_event_count integer not null default 0
    check (historical_reward_event_count >= 0),
  preactivation_b3tr_outflow_count integer not null default 0
    check (preactivation_b3tr_outflow_count >= 0),
  attempt_count integer not null default 0
    check (attempt_count >= 0),
  last_error text,
  checked_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists sybil_v2_scan_checkpoints_status_idx
  on public.sybil_v2_scan_checkpoints(
    network, historical_chain_status, funding_chain_status, updated_at
  );

create table if not exists public.sybil_v2_wallet_restrictions (
  id uuid primary key default gen_random_uuid(),
  wallet_address text not null
    check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  status text not null
    check (status in ('ACTIVE','REINSTATED')),
  reason_codes jsonb not null default '[]'::jsonb
    check (jsonb_typeof(reason_codes) = 'array'),
  evidence_summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(evidence_summary) = 'object'),
  source text not null
    check (source in ('SYSTEM','OPERATOR')),
  related_invite_code text
    references public.invitations(invite_code) on update cascade on delete restrict,
  imposed_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  check (
    (status = 'ACTIVE' and resolved_at is null)
    or (status = 'REINSTATED' and resolved_at is not null)
  )
);

create unique index if not exists sybil_v2_wallet_restrictions_one_active_idx
  on public.sybil_v2_wallet_restrictions(network, wallet_address)
  where status = 'ACTIVE';
create index if not exists sybil_v2_wallet_restrictions_history_idx
  on public.sybil_v2_wallet_restrictions(network, wallet_address, imposed_at desc);

create table if not exists public.sybil_v2_reward_clearances (
  id uuid primary key default gen_random_uuid(),
  invite_code text not null
    references public.invitations(invite_code) on update cascade on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  verdict text not null
    check (verdict in ('CLEAR','WATCH')),
  policy_version text not null,
  analyzer_version text not null,
  assessment_revision bigint not null check (assessment_revision >= 1),
  evidence_cutoff_block bigint not null check (evidence_cutoff_block >= 0),
  risk_score integer not null check (risk_score between 0 and 100),
  reason_codes jsonb not null default '[]'::jsonb
    check (jsonb_typeof(reason_codes) = 'array'),
  evidence_digest text not null check (evidence_digest ~ '^[0-9a-f]{32}$'),
  issued_at timestamptz not null default now(),
  unique(invite_code, assessment_revision)
);

create index if not exists sybil_v2_reward_clearances_invite_idx
  on public.sybil_v2_reward_clearances(invite_code, assessment_revision desc);

create index if not exists sybil_v2_reward_clearances_network_idx
  on public.sybil_v2_reward_clearances(network, issued_at desc);

alter table public.reward_queue_entries
  add column if not exists sybil_clearance_id uuid
    references public.sybil_v2_reward_clearances(id) on delete restrict;

create index if not exists reward_queue_entries_sybil_clearance_idx
  on public.reward_queue_entries(sybil_clearance_id)
  where sybil_clearance_id is not null;

alter table public.sybil_v2_referral_assessments enable row level security;
alter table public.sybil_v2_assessment_events enable row level security;
alter table public.sybil_v2_evidence_records enable row level security;
alter table public.sybil_v2_historical_reward_events enable row level security;
alter table public.sybil_v2_preactivation_b3tr_outflows enable row level security;
alter table public.sybil_v2_scan_checkpoints enable row level security;
alter table public.sybil_v2_wallet_restrictions enable row level security;
alter table public.sybil_v2_reward_clearances enable row level security;

revoke all on public.sybil_v2_referral_assessments from public, anon, authenticated;
revoke all on public.sybil_v2_assessment_events from public, anon, authenticated;
revoke all on public.sybil_v2_evidence_records from public, anon, authenticated;
revoke all on public.sybil_v2_historical_reward_events from public, anon, authenticated;
revoke all on public.sybil_v2_preactivation_b3tr_outflows from public, anon, authenticated;
revoke all on public.sybil_v2_scan_checkpoints from public, anon, authenticated;
revoke all on public.sybil_v2_wallet_restrictions from public, anon, authenticated;
revoke all on public.sybil_v2_reward_clearances from public, anon, authenticated;

grant select, insert, update on public.sybil_v2_referral_assessments to service_role;
grant select, insert on public.sybil_v2_assessment_events to service_role;
grant select, insert on public.sybil_v2_evidence_records to service_role;
grant select, insert on public.sybil_v2_historical_reward_events to service_role;
grant select, insert on public.sybil_v2_preactivation_b3tr_outflows to service_role;
grant select, insert, update on public.sybil_v2_scan_checkpoints to service_role;
grant select, insert, update on public.sybil_v2_wallet_restrictions to service_role;
grant select, insert on public.sybil_v2_reward_clearances to service_role;
grant usage, select on sequence public.sybil_v2_assessment_events_id_seq to service_role;
grant usage, select on sequence public.sybil_v2_evidence_records_id_seq to service_role;
grant usage, select on sequence public.sybil_v2_historical_reward_events_id_seq to service_role;
grant usage, select on sequence public.sybil_v2_preactivation_b3tr_outflows_id_seq to service_role;

create or replace function public.prevent_sybil_v2_append_only_mutation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  raise exception 'SYBIL_V2_AUDIT_RECORD_IS_IMMUTABLE';
end;
$$;

drop trigger if exists sybil_v2_assessment_events_append_only on public.sybil_v2_assessment_events;
create trigger sybil_v2_assessment_events_append_only
before update or delete on public.sybil_v2_assessment_events
for each row execute function public.prevent_sybil_v2_append_only_mutation();

drop trigger if exists sybil_v2_evidence_records_append_only on public.sybil_v2_evidence_records;
create trigger sybil_v2_evidence_records_append_only
before update or delete on public.sybil_v2_evidence_records
for each row execute function public.prevent_sybil_v2_append_only_mutation();

drop trigger if exists sybil_v2_reward_clearances_append_only on public.sybil_v2_reward_clearances;
create trigger sybil_v2_reward_clearances_append_only
before update or delete on public.sybil_v2_reward_clearances
for each row execute function public.prevent_sybil_v2_append_only_mutation();

create or replace function public.record_sybil_v2_assessment(
  p_invite_code text,
  p_network text,
  p_state text,
  p_risk_score integer,
  p_policy_version text,
  p_analyzer_version text,
  p_evidence_cutoff_block bigint,
  p_required_checks jsonb,
  p_completed_checks jsonb,
  p_reason_codes jsonb,
  p_evidence_summary jsonb,
  p_source text default 'SYSTEM',
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_code text := upper(btrim(p_invite_code));
  v_network text := lower(btrim(p_network));
  v_state text := upper(btrim(p_state));
  v_source text := upper(btrim(p_source));
  v_existing public.sybil_v2_referral_assessments%rowtype;
  v_revision bigint := 1;
  v_now timestamptz := clock_timestamp();
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then raise exception 'INVALID_INVITE_CODE'; end if;
  if v_network not in ('mainnet','testnet','testnet-staging') then raise exception 'INVALID_NETWORK'; end if;
  if v_state not in ('ANALYSIS_PENDING','ANALYSIS_FAILED','CLEAR','WATCH','HOLD','RESTRICTED') then raise exception 'INVALID_SYBIL_V2_STATE'; end if;
  if p_risk_score is null or p_risk_score not between 0 and 100 then raise exception 'INVALID_SYBIL_V2_RISK_SCORE'; end if;
  if nullif(btrim(p_policy_version),'') is null or nullif(btrim(p_analyzer_version),'') is null then raise exception 'INVALID_SYBIL_V2_VERSION'; end if;
  if p_evidence_cutoff_block is not null and p_evidence_cutoff_block < 0 then raise exception 'INVALID_SYBIL_V2_CUTOFF'; end if;
  if jsonb_typeof(coalesce(p_required_checks,'[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_completed_checks,'[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_reason_codes,'[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_evidence_summary,'{}'::jsonb)) <> 'object'
  then
    raise exception 'INVALID_SYBIL_V2_EVIDENCE_SHAPE';
  end if;
  if v_source not in ('SYSTEM','OPERATOR') then raise exception 'INVALID_SYBIL_V2_SOURCE'; end if;

  if not exists (
    select 1 from public.invitations i
    where i.invite_code = v_code
      and i.activation_network = v_network
  ) then
    raise exception 'SYBIL_V2_INVITATION_NOT_FOUND';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('veinvite_sybil_v2_' || v_code,0));

  select * into v_existing
  from public.sybil_v2_referral_assessments a
  where a.invite_code = v_code
  for update;

  if found then
    if p_expected_revision is not null and p_expected_revision <> v_existing.revision then
      return jsonb_build_object(
        'updated', false,
        'reason', 'STALE_REVISION',
        'revision', v_existing.revision,
        'state', v_existing.state
      );
    end if;
    v_revision := v_existing.revision + 1;

    update public.sybil_v2_referral_assessments
    set
      network = v_network,
      state = v_state,
      risk_score = p_risk_score,
      policy_version = btrim(p_policy_version),
      analyzer_version = btrim(p_analyzer_version),
      revision = v_revision,
      evidence_cutoff_block = p_evidence_cutoff_block,
      required_checks = coalesce(p_required_checks,'[]'::jsonb),
      completed_checks = coalesce(p_completed_checks,'[]'::jsonb),
      reason_codes = coalesce(p_reason_codes,'[]'::jsonb),
      evidence_summary = coalesce(p_evidence_summary,'{}'::jsonb),
      source = v_source,
      assessed_at = v_now,
      updated_at = v_now
    where invite_code = v_code;
  else
    if p_expected_revision is not null and p_expected_revision <> 0 then
      return jsonb_build_object(
        'updated', false,
        'reason', 'STALE_REVISION',
        'revision', 0,
        'state', null
      );
    end if;

    insert into public.sybil_v2_referral_assessments(
      invite_code, network, state, risk_score, policy_version, analyzer_version,
      revision, evidence_cutoff_block, required_checks, completed_checks,
      reason_codes, evidence_summary, source, assessed_at, updated_at
    ) values (
      v_code, v_network, v_state, p_risk_score, btrim(p_policy_version), btrim(p_analyzer_version),
      v_revision, p_evidence_cutoff_block, coalesce(p_required_checks,'[]'::jsonb),
      coalesce(p_completed_checks,'[]'::jsonb), coalesce(p_reason_codes,'[]'::jsonb),
      coalesce(p_evidence_summary,'{}'::jsonb), v_source, v_now, v_now
    );
  end if;

  insert into public.sybil_v2_assessment_events(
    invite_code, network, state, risk_score, policy_version, analyzer_version,
    revision, evidence_cutoff_block, required_checks, completed_checks,
    reason_codes, evidence_summary, source, created_at
  ) values (
    v_code, v_network, v_state, p_risk_score, btrim(p_policy_version), btrim(p_analyzer_version),
    v_revision, p_evidence_cutoff_block, coalesce(p_required_checks,'[]'::jsonb),
    coalesce(p_completed_checks,'[]'::jsonb), coalesce(p_reason_codes,'[]'::jsonb),
    coalesce(p_evidence_summary,'{}'::jsonb), v_source, v_now
  );

  return jsonb_build_object(
    'updated', true,
    'revision', v_revision,
    'state', v_state
  );
end;
$$;

create or replace function public.issue_sybil_v2_reward_clearance(
  p_invite_code text,
  p_expected_revision bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_code text := upper(btrim(p_invite_code));
  v_assessment public.sybil_v2_referral_assessments%rowtype;
  v_invitation public.invitations%rowtype;
  v_existing public.sybil_v2_reward_clearances%rowtype;
  v_clearance public.sybil_v2_reward_clearances%rowtype;
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then raise exception 'INVALID_INVITE_CODE'; end if;
  if p_expected_revision is null or p_expected_revision < 1 then raise exception 'INVALID_ASSESSMENT_REVISION'; end if;

  perform pg_advisory_xact_lock(hashtextextended('veinvite_sybil_v2_' || v_code,0));

  select * into v_existing
  from public.sybil_v2_reward_clearances c
  where c.invite_code = v_code
    and c.assessment_revision = p_expected_revision;

  if found then
    return jsonb_build_object(
      'issued', true,
      'reason', 'ALREADY_ISSUED',
      'clearanceId', v_existing.id,
      'verdict', v_existing.verdict,
      'assessmentRevision', v_existing.assessment_revision
    );
  end if;

  select * into v_assessment
  from public.sybil_v2_referral_assessments a
  where a.invite_code = v_code
  for update;

  if not found then
    return jsonb_build_object('issued',false,'reason','ASSESSMENT_MISSING');
  end if;

  if v_assessment.revision <> p_expected_revision then
    return jsonb_build_object(
      'issued', false,
      'reason', 'STALE_REVISION',
      'assessmentRevision', v_assessment.revision
    );
  end if;

  if v_assessment.state not in ('CLEAR','WATCH') then
    return jsonb_build_object('issued',false,'reason','ASSESSMENT_NOT_CLEAR','state',v_assessment.state);
  end if;

  if not (v_assessment.required_checks <@ v_assessment.completed_checks) then
    return jsonb_build_object('issued',false,'reason','REQUIRED_CHECKS_INCOMPLETE');
  end if;

  if v_assessment.evidence_cutoff_block is null then
    return jsonb_build_object('issued',false,'reason','EVIDENCE_CUTOFF_MISSING');
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code = v_code
  for update;

  if not found
     or v_invitation.status <> 'COMPLETED'
     or v_invitation.reward_status <> 'ELIGIBLE'
     or v_invitation.reward_eligible_at is null
     or v_invitation.sybil_status <> 'CLEAR'
     or v_invitation.sybil_checked_at is null
     or v_invitation.vote_completed is not true
     or v_invitation.vote_completed_block is null
     or v_invitation.inviter_wallet is null
     or v_invitation.invitee_wallet is null
     or v_assessment.evidence_cutoff_block < v_invitation.vote_completed_block
     or not public.security_identity_reward_gate_passes(
       v_invitation.identity_link_status,
       v_invitation.identity_link_checked_at,
       v_invitation.vote_completed_at,
       v_invitation.identity_link_policy_version,
       v_invitation.identity_link_evidence
     )
  then
    return jsonb_build_object('issued',false,'reason','INVITATION_NOT_READY');
  end if;

  if exists (
    select 1
    from public.sybil_v2_wallet_restrictions r
    where r.network = v_assessment.network
      and r.status = 'ACTIVE'
      and r.wallet_address in (
        lower(v_invitation.inviter_wallet),
        lower(v_invitation.invitee_wallet)
      )
  ) then
    return jsonb_build_object('issued',false,'reason','ACTIVE_WALLET_RESTRICTION');
  end if;

  insert into public.sybil_v2_reward_clearances(
    invite_code, network, verdict, policy_version, analyzer_version,
    assessment_revision, evidence_cutoff_block, risk_score, reason_codes,
    evidence_digest, issued_at
  ) values (
    v_code, v_assessment.network, v_assessment.state, v_assessment.policy_version,
    v_assessment.analyzer_version, v_assessment.revision,
    v_assessment.evidence_cutoff_block, v_assessment.risk_score,
    v_assessment.reason_codes,
    md5(v_assessment.evidence_summary::text),
    clock_timestamp()
  )
  returning * into v_clearance;

  return jsonb_build_object(
    'issued', true,
    'reason', 'ISSUED',
    'clearanceId', v_clearance.id,
    'verdict', v_clearance.verdict,
    'assessmentRevision', v_clearance.assessment_revision
  );
end;
$$;

create or replace view public.operator_sybil_v2_health
with (security_invoker = true)
as
with relevant as (
  select i.invite_code, i.activation_network as network, i.status, i.reward_status,
         i.inviter_wallet, i.invitee_wallet
  from public.invitations i
  where i.activation_network is not null
    and i.invitee_wallet is not null
    and i.status in ('ACTIVATING','UNDER_REVIEW','COMPLETED')
), joined as (
  select r.*,
         a.state as assessment_state,
         a.updated_at as assessment_updated_at,
         c.id as clearance_id
  from relevant r
  left join public.sybil_v2_referral_assessments a on a.invite_code = r.invite_code
  left join public.sybil_v2_reward_clearances c on c.invite_code = r.invite_code
)
select
  network,
  count(*)::bigint as relevant_referrals,
  count(*) filter (where assessment_state is not null)::bigint as assessed_referrals,
  count(*) filter (where assessment_state = 'ANALYSIS_PENDING')::bigint as pending_referrals,
  count(*) filter (where assessment_state = 'ANALYSIS_FAILED')::bigint as failed_referrals,
  count(*) filter (where assessment_state = 'HOLD')::bigint as held_referrals,
  count(*) filter (where assessment_state = 'WATCH')::bigint as watch_referrals,
  count(*) filter (where clearance_id is not null)::bigint as cleared_for_reward_referrals,
  count(*) filter (
    where reward_status = 'ELIGIBLE' and clearance_id is null
  )::bigint as eligible_without_v2_clearance
from joined
group by network;

revoke all on public.operator_sybil_v2_health from public, anon, authenticated;
grant select on public.operator_sybil_v2_health to service_role;

create or replace function public.read_reward_reservation_candidates_v2(
  p_network text,
  p_limit integer default 25
)
returns table(
  invite_code text,
  completion_block bigint,
  completion_tx_index integer,
  completion_clause_index integer,
  reward_cohort_round_id bigint,
  reward_funding_allocation_receipt_id bigint
)
language sql
stable
set search_path = pg_catalog, public
as $$
  with parameters as (
    select lower(btrim(p_network)) as network,
           greatest(1,least(coalesce(p_limit,25),100)) as row_limit
  )
  select i.invite_code, completion.block_number::bigint,
         completion.tx_index::integer, completion.clause_index::integer,
         i.reward_cohort_round_id, i.reward_funding_allocation_receipt_id
  from public.invitations i
  cross join parameters p
  join public.sybil_v2_referral_assessments a
    on a.invite_code = i.invite_code
   and a.state in ('CLEAR','WATCH')
  join public.sybil_v2_reward_clearances c
    on c.invite_code = i.invite_code
   and c.network = p.network
   and c.verdict = a.state
   and c.assessment_revision = a.revision
  cross join lateral (
    select e.block_number,e.tx_index,e.clause_index
    from public.invite_impact_events e
    where e.invite_code = i.invite_code and e.network = p.network
      and e.event_type in ('DAPP_REWARD','VOT3_CONVERSION','ALLOCATION_VOTE')
      and e.block_number is not null and e.tx_index is not null
      and e.clause_index is not null
    order by e.block_number desc,e.tx_index desc,e.clause_index desc
    limit 1
  ) completion
  where i.activation_network = p.network
    and i.status = 'COMPLETED' and i.reward_status = 'ELIGIBLE'
    and i.reward_eligible_at is not null and i.sybil_status = 'CLEAR'
    and i.sybil_checked_at is not null and i.impact_sync_complete_at is not null
    and i.inviter_wallet is not null and i.invitee_wallet is not null
    and i.eligibility_check_id is not null
    and i.reward_cohort_round_id is not null
    and i.reward_funding_allocation_receipt_id is not null
    and not exists (
      select 1
      from public.sybil_v2_wallet_restrictions r
      where r.network = p.network
        and r.status = 'ACTIVE'
        and r.wallet_address in (
          lower(i.inviter_wallet),
          lower(i.invitee_wallet)
        )
    )
    and not exists (
      select 1 from public.reward_queue_entries q where q.invite_code = i.invite_code
    )
    and not exists (
      select 1 from public.reward_reservation_legacy_exclusions x where x.invite_code = i.invite_code
    )
  order by completion.block_number,completion.tx_index,completion.clause_index,i.invite_code
  limit (select row_limit from parameters);
$$;

create or replace function public.commit_reward_reservation(
  p_invite_code text,
  p_network text,
  p_observed_pool_balance_wei numeric,
  p_expected_reserved_before_wei numeric,
  p_amount_wei numeric,
  p_algorithm_version text,
  p_quote_snapshot_id bigint,
  p_finalized_block bigint,
  p_basis jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_code text := upper(btrim(p_invite_code));
  v_network text := lower(btrim(p_network));
  v_invitation public.invitations%rowtype;
  v_queue public.reward_queue_entries%rowtype;
  v_clearance public.sybil_v2_reward_clearances%rowtype;
  v_entry_class text;
  v_reserved numeric(78,0) := 0;
  v_legacy_payout_reserved numeric(78,0) := 0;
  v_completion_block bigint;
  v_completion_tx_index integer;
  v_completion_clause_index integer;
  v_mainnet_enabled boolean;
  v_emergency_paused boolean;
  v_now timestamptz := now();
begin
  if v_code is null or v_code='' then raise exception 'INVITE_CODE_REQUIRED'; end if;
  if v_network not in ('mainnet','testnet','testnet-staging') then raise exception 'UNSUPPORTED_NETWORK'; end if;
  if p_observed_pool_balance_wei is null or p_observed_pool_balance_wei < 0 or p_observed_pool_balance_wei <> trunc(p_observed_pool_balance_wei) then raise exception 'INVALID_OBSERVED_POOL_BALANCE'; end if;
  if p_expected_reserved_before_wei is null or p_expected_reserved_before_wei < 0 or p_expected_reserved_before_wei <> trunc(p_expected_reserved_before_wei) then raise exception 'INVALID_EXPECTED_RESERVED'; end if;
  if p_amount_wei is null or p_amount_wei <= 0 or p_amount_wei <> trunc(p_amount_wei) then raise exception 'INVALID_REWARD_AMOUNT'; end if;
  if p_finalized_block is null or p_finalized_block < 0 then raise exception 'INVALID_FINALIZED_BLOCK'; end if;
  if p_algorithm_version is null or length(btrim(p_algorithm_version)) not between 1 and 80 then raise exception 'INVALID_ALGORITHM_VERSION'; end if;
  if p_basis is null or jsonb_typeof(p_basis) <> 'object' then raise exception 'INVALID_RESERVATION_BASIS'; end if;

  perform pg_advisory_xact_lock(hashtextextended('veinvite_emergency_reward_pause',0));
  select mainnet_funded_rewards_enabled, emergency_rewards_paused into v_mainnet_enabled, v_emergency_paused from public.reward_runtime_config where id = 1;
  if not found then raise exception 'REWARD_RUNTIME_CONFIG_MISSING'; end if;
  if v_emergency_paused then raise exception 'REWARD_RESERVATION_PAUSED'; end if;
  if v_network = 'mainnet' and not v_mainnet_enabled then raise exception 'REWARD_RESERVATION_DISABLED'; end if;
  perform pg_advisory_xact_lock(hashtextextended('veinvite_reward_reservation_' || v_network,0));

  select * into v_invitation from public.invitations i where i.invite_code=v_code for update;
  if not found
     or v_invitation.activation_network <> v_network
     or v_invitation.status <> 'COMPLETED'
     or v_invitation.reward_status <> 'ELIGIBLE'
     or v_invitation.reward_eligible_at is null
     or v_invitation.sybil_status <> 'CLEAR'
     or v_invitation.sybil_checked_at is null
     or v_invitation.impact_sync_complete_at is null
     or v_invitation.inviter_wallet is null
     or v_invitation.invitee_wallet is null
     or v_invitation.eligibility_check_id is null then
    return jsonb_build_object('reserved',false,'reason','NOT_ELIGIBLE');
  end if;

  select c.* into v_clearance
  from public.sybil_v2_reward_clearances c
  join public.sybil_v2_referral_assessments a
    on a.invite_code = c.invite_code
   and a.revision = c.assessment_revision
   and a.state = c.verdict
  where c.invite_code = v_code
    and c.network = v_network
    and c.verdict in ('CLEAR','WATCH');

  if not found then
    return jsonb_build_object('reserved',false,'reason','SYBIL_V2_CLEARANCE_MISSING');
  end if;

  if exists (
    select 1
    from public.sybil_v2_wallet_restrictions r
    where r.network = v_network
      and r.status = 'ACTIVE'
      and r.wallet_address in (
        lower(v_invitation.inviter_wallet),
        lower(v_invitation.invitee_wallet)
      )
  ) then
    return jsonb_build_object('reserved',false,'reason','SYBIL_V2_RESTRICTED');
  end if;

  if exists(select 1 from public.reward_reservation_legacy_exclusions x where x.invite_code=v_code) then
    return jsonb_build_object('reserved',false,'reason','LEGACY_EXCLUDED');
  end if;

  select * into v_queue from public.reward_queue_entries q where q.invite_code=v_code for update;
  if found then
    if v_queue.reserved_amount_wei is not null then
      return jsonb_build_object('reserved',true,'reason','ALREADY_RESERVED','inviteCode',v_queue.invite_code,'amountWei',v_queue.reserved_amount_wei::text,'reservedAt',v_queue.reserved_at,'status',v_queue.status);
    end if;
    return jsonb_build_object('reserved',false,'reason','LEGACY_QUEUE_ENTRY');
  end if;

  select e.block_number::bigint,e.tx_index::integer,e.clause_index::integer into v_completion_block,v_completion_tx_index,v_completion_clause_index
  from public.invite_impact_events e
  where e.invite_code=v_code and e.network=v_network
    and e.event_type in ('DAPP_REWARD','VOT3_CONVERSION','ALLOCATION_VOTE')
    and e.block_number is not null and e.tx_index is not null and e.clause_index is not null
  order by e.block_number desc,e.tx_index desc,e.clause_index desc limit 1;
  if v_completion_block is null or v_completion_tx_index is null or v_completion_clause_index is null then return jsonb_build_object('reserved',false,'reason','COMPLETION_POSITION_MISSING'); end if;
  if v_completion_block > p_finalized_block then return jsonb_build_object('reserved',false,'reason','AWAITING_FINALITY','completionBlock',v_completion_block,'finalizedBlock',p_finalized_block); end if;

  select e.entry_class into v_entry_class
  from public.eligibility_check_events e
  where e.id=v_invitation.eligibility_check_id and e.invite_code=v_code and e.wallet_address=lower(v_invitation.invitee_wallet)
    and e.network=v_network and e.outcome='ELIGIBLE' and e.entry_class in ('NEW','RETURNING');
  if v_entry_class not in ('NEW','RETURNING') then return jsonb_build_object('reserved',false,'reason','ENTRY_PROOF_MISSING'); end if;

  select coalesce(sum(q.reserved_amount_wei),0) into v_reserved
  from public.reward_queue_entries q
  where q.network=v_network and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED')
    and not exists(select 1 from public.reward_payouts paid where paid.invite_code=q.invite_code and paid.status='PAID');

  select coalesce(sum(rp.amount_wei),0) into v_legacy_payout_reserved
  from public.reward_payouts rp join public.reward_rounds rr on rr.id=rp.round_id
  where rr.network=v_network and rp.status in ('PENDING','SENDING','FAILED')
    and not exists(select 1 from public.reward_queue_entries q where q.invite_code=rp.invite_code and q.reserved_amount_wei is not null);
  v_reserved := v_reserved + v_legacy_payout_reserved;

  if v_reserved <> p_expected_reserved_before_wei then return jsonb_build_object('reserved',false,'reason','RECALCULATE','reservedExistingWei',v_reserved::text); end if;
  if p_amount_wei > greatest(p_observed_pool_balance_wei-v_reserved,0) then return jsonb_build_object('reserved',false,'reason','RECALCULATE','reservedExistingWei',v_reserved::text,'availableWei',greatest(p_observed_pool_balance_wei-v_reserved,0)::text); end if;

  insert into public.reward_queue_entries(
    invite_code,recipient_wallet,eligibility_check_id,entry_class,network,eligible_at,status,
    reserved_amount_wei,reserved_at,reservation_algorithm_version,reservation_quote_snapshot_id,
    reservation_completion_block,reservation_completion_tx_index,reservation_completion_clause_index,reservation_basis,
    sybil_clearance_id
  ) values (
    v_code,lower(v_invitation.inviter_wallet),v_invitation.eligibility_check_id,v_entry_class,v_network,v_invitation.reward_eligible_at,'AWAITING_CLAIM',
    p_amount_wei,v_now,btrim(p_algorithm_version),p_quote_snapshot_id,v_completion_block,v_completion_tx_index,v_completion_clause_index,
    p_basis || jsonb_build_object(
      'observedPoolBalanceWei',p_observed_pool_balance_wei::text,
      'reservedBeforeWei',v_reserved::text,
      'finalizedBlock',p_finalized_block,
      'sybilClearanceId',v_clearance.id::text,
      'sybilVerdict',v_clearance.verdict,
      'sybilAssessmentRevision',v_clearance.assessment_revision
    ),
    v_clearance.id
  ) returning * into v_queue;

  return jsonb_build_object(
    'reserved',true,'reason','RESERVED','inviteCode',v_queue.invite_code,
    'amountWei',v_queue.reserved_amount_wei::text,'reservedAt',v_queue.reserved_at,
    'status',v_queue.status,'completionBlock',v_queue.reservation_completion_block,
    'completionTxIndex',v_queue.reservation_completion_tx_index,
    'completionClauseIndex',v_queue.reservation_completion_clause_index,
    'sybilClearanceId',v_queue.sybil_clearance_id
  );
end;
$$;

create or replace function public.request_reward_claim(
  p_invite_code text,
  p_recipient_wallet text
)
returns table(
  invite_code text,
  status text,
  claim_requested_at timestamptz,
  claim_requested_by_wallet text
)
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_code text := upper(btrim(p_invite_code));
  v_wallet text := lower(btrim(p_recipient_wallet));
  v_queue public.reward_queue_entries%rowtype;
  v_invitation public.invitations%rowtype;
  v_clearance public.sybil_v2_reward_clearances%rowtype;
begin
  if v_code is null or v_code='' then raise exception 'INVITE_CODE_REQUIRED'; end if;
  if v_wallet is null or v_wallet !~ '^0x[0-9a-f]{40}$' then raise exception 'INVALID_RECIPIENT_WALLET'; end if;
  perform pg_advisory_xact_lock(hashtextextended('veinvite_reward_claim_' || v_code,0));

  select * into v_queue from public.reward_queue_entries q where q.invite_code=v_code for update;
  if not found or v_queue.reserved_amount_wei is null or v_queue.reserved_amount_wei <= 0 or v_queue.reserved_at is null then raise exception 'REWARD_CLAIM_NOT_AVAILABLE'; end if;
  if v_queue.recipient_wallet <> v_wallet then raise exception 'REWARD_CLAIM_WALLET_MISMATCH'; end if;

  select * into v_invitation from public.invitations i where i.invite_code=v_code for update;

  if v_queue.sybil_clearance_id is not null then
    select * into v_clearance
    from public.sybil_v2_reward_clearances c
    where c.id = v_queue.sybil_clearance_id
      and c.invite_code = v_code
      and c.verdict in ('CLEAR','WATCH');

    if not found
       or v_invitation.status <> 'COMPLETED'
       or v_invitation.reward_status not in ('ELIGIBLE','PAID')
       or v_invitation.reward_eligible_at is null
       or lower(v_invitation.inviter_wallet) <> v_wallet
       or v_queue.eligible_at <> v_invitation.reward_eligible_at then
      raise exception 'REWARD_CLAIM_NOT_AVAILABLE';
    end if;
  else
    if not found
       or v_invitation.status <> 'COMPLETED'
       or v_invitation.reward_status not in ('ELIGIBLE','PAID')
       or v_invitation.reward_eligible_at is null
       or v_invitation.sybil_status <> 'CLEAR'
       or v_invitation.sybil_checked_at is null
       or lower(v_invitation.inviter_wallet) <> v_wallet
       or v_queue.eligible_at <> v_invitation.reward_eligible_at then
      raise exception 'REWARD_CLAIM_NOT_AVAILABLE';
    end if;
  end if;

  if v_queue.status='CANCELLED' then raise exception 'REWARD_CLAIM_CANCELLED'; end if;

  if v_queue.status='AWAITING_CLAIM' then
    update public.reward_queue_entries q
    set status='QUEUED',queued_at=coalesce(q.queued_at,now()),claim_requested_at=now(),claim_requested_by_wallet=v_wallet
    where q.id=v_queue.id returning q.* into v_queue;
  elsif v_queue.status not in ('QUEUED','ASSIGNED') then
    raise exception 'REWARD_CLAIM_NOT_AVAILABLE';
  end if;

  if v_queue.claim_requested_at is null or v_queue.claim_requested_by_wallet <> v_wallet then raise exception 'REWARD_CLAIM_STATE_INVALID'; end if;

  return query select v_queue.invite_code,v_queue.status,v_queue.claim_requested_at,v_queue.claim_requested_by_wallet;
end;
$$;

create or replace function public.enforce_same_security_client_block_policy()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $
begin
  if new.sybil_status = 'REVIEW'
     and new.sybil_source = 'SECURITY_CLIENT'
     and coalesce((new.identity_link_evidence ->> 'sameInviterClient')::boolean, false)
     and not coalesce((new.identity_link_evidence ->> 'operatorOverride')::boolean, false)
  then
    -- Sybil v2 policy: same-client evidence is strong review context, but it is
    -- not sufficient by itself to permanently block or forfeit a reward.
    -- Keep the referral on HOLD/UNDER_REVIEW until independent evidence or an
    -- operator decision corroborates it.
    new.sybil_status := 'REVIEW';
    new.sybil_risk_level := 'HIGH';
    new.sybil_risk_score := greatest(coalesce(new.sybil_risk_score,0), 90);
    new.sybil_reason := 'Invitee and inviter were observed in the same VeInvite security client; additional independent evidence is required before restriction.';
    new.sybil_checked_at := clock_timestamp();
    new.sybil_source := 'SECURITY_CLIENT';
    if new.status <> 'CANCELLED' then
      new.status := 'UNDER_REVIEW';
    end if;
  end if;

  return new;
end;
$;

create or replace function public.prevent_v2_cleared_reward_reversal()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if old.reward_status = 'ELIGIBLE'
     and new.reward_status not in ('ELIGIBLE','PAID')
     and exists (
       select 1
       from public.reward_queue_entries q
       where q.invite_code = old.invite_code
         and q.sybil_clearance_id is not null
         and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED')
     )
  then
    raise exception 'V2_CLEARED_REWARD_CANNOT_BE_REVERSED_AFTER_CLAIM_READY';
  end if;

  return new;
end;
$$;

drop trigger if exists invitations_lock_v2_cleared_reward_after_reservation on public.invitations;
create trigger invitations_lock_v2_cleared_reward_after_reservation
before update of reward_status on public.invitations
for each row execute function public.prevent_v2_cleared_reward_reversal();

revoke all on function public.record_sybil_v2_assessment(
  text,text,text,integer,text,text,bigint,jsonb,jsonb,jsonb,jsonb,text,bigint
) from public, anon, authenticated;
grant execute on function public.record_sybil_v2_assessment(
  text,text,text,integer,text,text,bigint,jsonb,jsonb,jsonb,jsonb,text,bigint
) to service_role;

revoke all on function public.issue_sybil_v2_reward_clearance(text,bigint)
  from public, anon, authenticated;
grant execute on function public.issue_sybil_v2_reward_clearance(text,bigint)
  to service_role;

revoke all on function public.prevent_sybil_v2_append_only_mutation()
  from public, anon, authenticated;
revoke all on function public.prevent_v2_cleared_reward_reversal()
  from public, anon, authenticated;

commit;
