create table if not exists public.reward_x_promotion_verification_attempts (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  invite_code text not null check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  submission_id bigint not null
    references public.reward_x_promotion_post_submissions(id),
  verification_id bigint
    references public.reward_x_promotion_post_verifications(id),
  phase text not null
    check (phase in ('INITIAL_RETRY','FINAL_CHECK')),
  x_post_id text not null
    check (x_post_id ~ '^[0-9]{1,32}$'),
  outcome text not null
    check (outcome in (
      'RETRY',
      'INITIAL_VERIFIED',
      'INVALIDATED',
      'REVIEW_REQUIRED',
      'FINAL_VERIFIED'
    )),
  reason text not null
    check (char_length(btrim(reason)) between 1 and 120),
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details)='object'),
  attempted_at timestamptz not null default now(),
  constraint reward_x_promotion_attempt_phase_shape_check check (
    (phase='INITIAL_RETRY' and verification_id is null)
    or
    (phase='FINAL_CHECK' and verification_id is not null)
  )
);

create index if not exists reward_x_promotion_attempt_submission_idx
  on public.reward_x_promotion_verification_attempts(
    submission_id,phase,attempted_at desc,id desc
  );

create index if not exists reward_x_promotion_attempt_verification_idx
  on public.reward_x_promotion_verification_attempts(
    verification_id,attempted_at desc,id desc
  )
  where verification_id is not null;

create or replace function public.validate_reward_x_promotion_verification_attempt_insert()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_submission public.reward_x_promotion_post_submissions%rowtype;
  v_verification public.reward_x_promotion_post_verifications%rowtype;
begin
  select * into v_submission
  from public.reward_x_promotion_post_submissions s
  where s.id=new.submission_id;

  if not found
     or v_submission.invite_code<>new.invite_code
     or v_submission.network<>new.network
     or v_submission.x_post_id<>new.x_post_id then
    raise exception 'REWARD_X_PROMOTION_ATTEMPT_SUBMISSION_MISMATCH';
  end if;

  if new.phase='INITIAL_RETRY' then
    if new.verification_id is not null then
      raise exception 'REWARD_X_PROMOTION_ATTEMPT_PHASE_MISMATCH';
    end if;
  else
    select * into v_verification
    from public.reward_x_promotion_post_verifications p
    where p.id=new.verification_id;

    if not found
       or v_verification.submission_id<>new.submission_id
       or v_verification.invite_code<>new.invite_code
       or v_verification.network<>new.network
       or v_verification.x_post_id<>new.x_post_id then
      raise exception 'REWARD_X_PROMOTION_ATTEMPT_VERIFICATION_MISMATCH';
    end if;
  end if;

  return new;
end;
$function$;

create or replace function public.reject_reward_x_promotion_verification_attempt_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'REWARD_X_PROMOTION_ATTEMPT_IMMUTABLE';
end;
$function$;

drop trigger if exists validate_reward_x_promotion_verification_attempt_insert_trigger
  on public.reward_x_promotion_verification_attempts;
create trigger validate_reward_x_promotion_verification_attempt_insert_trigger
before insert on public.reward_x_promotion_verification_attempts
for each row
execute function public.validate_reward_x_promotion_verification_attempt_insert();

drop trigger if exists reject_reward_x_promotion_verification_attempt_mutation_trigger
  on public.reward_x_promotion_verification_attempts;
create trigger reject_reward_x_promotion_verification_attempt_mutation_trigger
before update or delete on public.reward_x_promotion_verification_attempts
for each row
execute function public.reject_reward_x_promotion_verification_attempt_mutation();

alter table public.reward_x_promotion_verification_attempts
  enable row level security;

revoke all on table public.reward_x_promotion_verification_attempts
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_verification_attempts_id_seq
  from public,anon,authenticated,service_role;

grant select,insert on table public.reward_x_promotion_verification_attempts
  to service_role;
grant usage,select on sequence public.reward_x_promotion_verification_attempts_id_seq
  to service_role;

create or replace function public.record_reward_x_promotion_verification_attempt_v1(
  p_invite_code text,
  p_submission_id bigint,
  p_verification_id bigint,
  p_phase text,
  p_x_post_id text,
  p_outcome text,
  p_reason text,
  p_details jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(coalesce(p_invite_code,'')));
  v_phase text := upper(btrim(coalesce(p_phase,'')));
  v_post_id text := btrim(coalesce(p_x_post_id,''));
  v_outcome text := upper(btrim(coalesce(p_outcome,'')));
  v_reason text := upper(btrim(coalesce(p_reason,'')));
  v_submission public.reward_x_promotion_post_submissions%rowtype;
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_created public.reward_x_promotion_verification_attempts%rowtype;
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;
  if v_phase not in ('INITIAL_RETRY','FINAL_CHECK') then
    raise exception 'REWARD_X_PROMOTION_ATTEMPT_PHASE_INVALID';
  end if;
  if v_outcome not in (
    'RETRY','INITIAL_VERIFIED','INVALIDATED','REVIEW_REQUIRED','FINAL_VERIFIED'
  ) then
    raise exception 'REWARD_X_PROMOTION_ATTEMPT_OUTCOME_INVALID';
  end if;
  if v_post_id !~ '^[0-9]{1,32}$' then
    raise exception 'REWARD_X_PROMOTION_POST_ID_INVALID';
  end if;
  if char_length(v_reason) not between 1 and 120 then
    raise exception 'REWARD_X_PROMOTION_ATTEMPT_REASON_INVALID';
  end if;
  if p_details is null or jsonb_typeof(p_details)<>'object' then
    raise exception 'REWARD_X_PROMOTION_ATTEMPT_DETAILS_INVALID';
  end if;

  select * into v_submission
  from public.reward_x_promotion_post_submissions s
  where s.id=p_submission_id
    and s.invite_code=v_code
    and s.x_post_id=v_post_id;

  if not found then
    raise exception 'REWARD_X_PROMOTION_ATTEMPT_SUBMISSION_MISSING';
  end if;

  if v_phase='INITIAL_RETRY' then
    if p_verification_id is not null then
      raise exception 'REWARD_X_PROMOTION_ATTEMPT_PHASE_MISMATCH';
    end if;
  else
    if p_verification_id is null then
      raise exception 'REWARD_X_PROMOTION_ATTEMPT_VERIFICATION_REQUIRED';
    end if;

    select * into v_verification
    from public.reward_x_promotion_post_verifications p
    where p.id=p_verification_id
      and p.submission_id=v_submission.id
      and p.invite_code=v_code
      and p.x_post_id=v_post_id;

    if not found then
      raise exception 'REWARD_X_PROMOTION_ATTEMPT_VERIFICATION_MISSING';
    end if;
  end if;

  insert into public.reward_x_promotion_verification_attempts(
    network,invite_code,submission_id,verification_id,
    phase,x_post_id,outcome,reason,details
  ) values (
    v_submission.network,v_code,v_submission.id,p_verification_id,
    v_phase,v_post_id,v_outcome,v_reason,p_details
  )
  returning * into v_created;

  return jsonb_build_object(
    'recorded',true,
    'attemptId',v_created.id,
    'inviteCode',v_code,
    'phase',v_created.phase,
    'outcome',v_created.outcome,
    'attemptedAt',v_created.attempted_at
  );
end;
$function$;

create or replace function public.read_reward_x_promotion_pending_post_candidates_v1(
  p_network text,
  p_limit integer default 10
)
returns jsonb
language plpgsql
stable security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_limit integer := greatest(1,least(coalesce(p_limit,10),50));
  v_rows jsonb;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'inviteCode',c.invite_code,
        'submissionId',c.submission_id,
        'xPostId',c.x_post_id,
        'shareToken',c.share_token,
        'submittedAt',c.submitted_at
      )
      order by c.submitted_at,c.submission_id
    ),
    '[]'::jsonb
  )
  into v_rows
  from (
    select
      u.invite_code,
      u.id as submission_id,
      u.x_post_id,
      x.share_token::text as share_token,
      u.submitted_at
    from public.reward_x_promotion_post_submissions u
    join public.reward_x_promotion_opportunities x
      on x.id=u.opportunity_id
    join public.reward_x_promotion_obligations o
      on o.id=u.obligation_id
    left join lateral (
      select max(a.attempted_at) as latest_attempt_at
      from public.reward_x_promotion_verification_attempts a
      where a.submission_id=u.id
        and a.phase='INITIAL_RETRY'
    ) retry on true
    where u.network=v_network
      and u.submission_state='PENDING'
      and o.financial_state='HELD'
      and u.submitted_at <= now()-interval '10 minutes'
      and (
        retry.latest_attempt_at is null
        or retry.latest_attempt_at <= now()-interval '15 minutes'
      )
    order by
      coalesce(retry.latest_attempt_at,u.submitted_at),
      u.id
    limit v_limit
  ) c;

  return jsonb_build_object(
    'network',v_network,
    'candidateCount',jsonb_array_length(v_rows),
    'candidates',v_rows
  );
end;
$function$;

create or replace function public.read_reward_x_promotion_final_post_candidates_v1(
  p_network text,
  p_limit integer default 10
)
returns jsonb
language plpgsql
stable security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_limit integer := greatest(1,least(coalesce(p_limit,10),50));
  v_rows jsonb;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'inviteCode',c.invite_code,
        'submissionId',c.submission_id,
        'verificationId',c.verification_id,
        'xPostId',c.x_post_id,
        'xAuthorId',c.x_author_id,
        'shareToken',c.share_token,
        'verifyAfter',c.verify_after,
        'verificationState',c.verification_state
      )
      order by c.verify_after,c.verification_id
    ),
    '[]'::jsonb
  )
  into v_rows
  from (
    select
      p.invite_code,
      p.submission_id,
      p.id as verification_id,
      p.x_post_id,
      p.x_author_id,
      x.share_token::text as share_token,
      p.verify_after,
      p.verification_state
    from public.reward_x_promotion_post_verifications p
    join public.reward_x_promotion_opportunities x
      on x.id=p.opportunity_id
    join public.reward_x_promotion_obligations o
      on o.id=p.obligation_id
    left join lateral (
      select max(a.attempted_at) as latest_attempt_at
      from public.reward_x_promotion_verification_attempts a
      where a.verification_id=p.id
        and a.phase='FINAL_CHECK'
    ) retry on true
    where p.network=v_network
      and p.verification_state in ('INITIAL_VERIFIED','REVIEW_REQUIRED')
      and p.verify_after<=now()
      and o.financial_state='HELD'
      and (
        retry.latest_attempt_at is null
        or retry.latest_attempt_at <= now()-interval '60 minutes'
      )
    order by
      coalesce(retry.latest_attempt_at,p.verify_after),
      p.id
    limit v_limit
  ) c;

  return jsonb_build_object(
    'network',v_network,
    'candidateCount',jsonb_array_length(v_rows),
    'candidates',v_rows
  );
end;
$function$;

create or replace function public.mark_reward_x_promotion_post_review_required_v1(
  p_invite_code text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(coalesce(p_invite_code,'')));
  v_reason text := upper(btrim(coalesce(p_reason,'')));
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_now timestamptz := clock_timestamp();
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;
  if char_length(v_reason) not between 1 and 120 then
    raise exception 'REWARD_X_PROMOTION_REVIEW_REASON_INVALID';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_code,0)
  );

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.invite_code=v_code
  for update;

  if not found then
    raise exception 'REWARD_X_PROMOTION_POST_VERIFICATION_MISSING';
  end if;

  if v_verification.verification_state='REVIEW_REQUIRED' then
    return jsonb_build_object(
      'updated',false,
      'reason','ALREADY_REVIEW_REQUIRED',
      'inviteCode',v_code,
      'verificationId',v_verification.id,
      'state',v_verification.verification_state
    );
  end if;

  if v_verification.verification_state not in ('INITIAL_VERIFIED') then
    return jsonb_build_object(
      'updated',false,
      'reason','TERMINAL_STATE',
      'inviteCode',v_code,
      'verificationId',v_verification.id,
      'state',v_verification.verification_state
    );
  end if;

  update public.reward_x_promotion_post_verifications p
  set verification_state='REVIEW_REQUIRED',
      state_reason=v_reason,
      final_verified_at=null,
      invalidated_at=null,
      updated_at=v_now
  where p.id=v_verification.id
  returning * into v_verification;

  return jsonb_build_object(
    'updated',true,
    'reason',v_reason,
    'inviteCode',v_code,
    'verificationId',v_verification.id,
    'state',v_verification.verification_state
  );
end;
$function$;

create or replace function public.invalidate_reward_x_promotion_post_verification_v1(
  p_invite_code text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(coalesce(p_invite_code,'')));
  v_reason text := upper(btrim(coalesce(p_reason,'')));
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_now timestamptz := clock_timestamp();
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;
  if v_reason not in (
    'POST_NOT_FOUND',
    'SHARE_TOKEN_MISSING',
    'POST_NOT_ORIGINAL',
    'POST_IDENTITY_MISMATCH',
    'POST_AUTHOR_MISMATCH'
  ) then
    raise exception 'REWARD_X_PROMOTION_VERIFICATION_INVALID_REASON';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_code,0)
  );

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.invite_code=v_code
  for update;

  if not found then
    raise exception 'REWARD_X_PROMOTION_POST_VERIFICATION_MISSING';
  end if;

  if v_verification.verification_state='FINAL_VERIFIED' then
    raise exception 'REWARD_X_PROMOTION_FINAL_VERIFICATION_IMMUTABLE';
  end if;

  if v_verification.verification_state<>'INVALID' then
    update public.reward_x_promotion_post_verifications p
    set verification_state='INVALID',
        final_verified_at=null,
        invalidated_at=v_now,
        state_reason=v_reason,
        updated_at=v_now
    where p.id=v_verification.id
    returning * into v_verification;
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=v_verification.obligation_id
  for update;

  if not found then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_MISSING';
  end if;

  if v_obligation.financial_state='HELD' then
    update public.reward_x_promotion_obligations o
    set financial_state='RELEASED',
        released_at=v_now,
        release_reason='FINAL_' || v_reason,
        updated_at=v_now
    where o.id=v_obligation.id
    returning * into v_obligation;
  elsif v_obligation.financial_state<>'RELEASED' then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_NOT_RELEASABLE';
  end if;

  return jsonb_build_object(
    'invalidated',true,
    'reason',v_reason,
    'inviteCode',v_code,
    'verificationId',v_verification.id,
    'verificationState',v_verification.verification_state,
    'financialState',v_obligation.financial_state,
    'releasedAt',v_obligation.released_at
  );
end;
$function$;

create or replace function public.expire_reward_x_promotion_opportunities_v1(
  p_network text,
  p_limit integer default 25
)
returns jsonb
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_limit integer := greatest(1,least(coalesce(p_limit,25),100));
  v_candidate record;
  v_opportunity public.reward_x_promotion_opportunities%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_now timestamptz;
  v_considered integer := 0;
  v_released integer := 0;
  v_skipped integer := 0;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  for v_candidate in
    select x.invite_code
    from public.reward_x_promotion_opportunities x
    join public.reward_x_promotion_obligations o
      on o.id=x.obligation_id
    where x.network=v_network
      and o.financial_state='HELD'
      and now() >
        x.post_deadline_at +
        make_interval(secs=>x.submission_grace_seconds)
    order by x.post_deadline_at,x.id
    limit v_limit
  loop
    v_considered:=v_considered+1;

    perform pg_advisory_xact_lock(
      hashtextextended('veinvite_x_promotion_' || v_candidate.invite_code,0)
    );

    v_now:=clock_timestamp();

    select * into v_opportunity
    from public.reward_x_promotion_opportunities x
    where x.invite_code=v_candidate.invite_code;

    select * into v_obligation
    from public.reward_x_promotion_obligations o
    where o.invite_code=v_candidate.invite_code
    for update;

    if not found
       or v_obligation.financial_state<>'HELD'
       or v_now <=
          v_opportunity.post_deadline_at +
          make_interval(secs=>v_opportunity.submission_grace_seconds)
       or exists (
         select 1
         from public.reward_x_promotion_post_submissions s
         where s.opportunity_id=v_opportunity.id
           and s.submission_state in ('PENDING','VERIFIED')
       )
       or exists (
         select 1
         from public.reward_x_promotion_post_verifications p
         where p.opportunity_id=v_opportunity.id
           and p.verification_state in (
             'INITIAL_VERIFIED','REVIEW_REQUIRED','FINAL_VERIFIED'
           )
       ) then
      v_skipped:=v_skipped+1;
      continue;
    end if;

    update public.reward_x_promotion_obligations o
    set financial_state='RELEASED',
        released_at=v_now,
        release_reason='NO_VALID_POST_BEFORE_DEADLINE',
        updated_at=v_now
    where o.id=v_obligation.id;

    v_released:=v_released+1;
  end loop;

  return jsonb_build_object(
    'network',v_network,
    'consideredCount',v_considered,
    'releasedCount',v_released,
    'skippedCount',v_skipped
  );
end;
$function$;

create or replace function public.release_terminal_reward_x_promotion_security_v1(
  p_network text,
  p_limit integer default 25
)
returns jsonb
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_limit integer := greatest(1,least(coalesce(p_limit,25),100));
  v_candidate record;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_invitation public.invitations%rowtype;
  v_terminal boolean;
  v_invitation_found boolean;
  v_now timestamptz;
  v_considered integer := 0;
  v_released integer := 0;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  for v_candidate in
    select o.invite_code
    from public.reward_x_promotion_obligations o
    join public.invitations i
      on i.invite_code=o.invite_code
    where o.network=v_network
      and o.financial_state in ('RESERVED','HELD')
      and (
        public.is_sybil_v2_referral_invalidated(
          o.invite_code,
          v_network
        )
        or exists (
          select 1
          from public.sybil_v2_wallet_restrictions r
          where r.network=v_network
            and r.status='ACTIVE'
            and r.wallet_address in (
              lower(o.recipient_wallet),
              lower(i.invitee_wallet)
            )
        )
      )
    order by o.id
    limit v_limit
  loop
    v_considered:=v_considered+1;

    perform pg_advisory_xact_lock(
      hashtextextended('veinvite_x_promotion_' || v_candidate.invite_code,0)
    );

    select * into v_obligation
    from public.reward_x_promotion_obligations o
    where o.invite_code=v_candidate.invite_code
    for update;

    if not found
       or v_obligation.financial_state not in ('RESERVED','HELD') then
      continue;
    end if;

    select * into v_invitation
    from public.invitations i
    where i.invite_code=v_candidate.invite_code;
    v_invitation_found:=found;

    v_terminal :=
      public.is_sybil_v2_referral_invalidated(
        v_candidate.invite_code,
        v_network
      )
      or (
        v_invitation_found and exists (
          select 1
          from public.sybil_v2_wallet_restrictions r
          where r.network=v_network
            and r.status='ACTIVE'
            and r.wallet_address in (
              lower(v_obligation.recipient_wallet),
              lower(v_invitation.invitee_wallet)
            )
        )
      );

    if not v_terminal then
      continue;
    end if;

    v_now:=clock_timestamp();

    update public.reward_x_promotion_post_submissions s
    set submission_state='INVALID',
        verified_at=null,
        invalidated_at=v_now,
        state_reason='SECURITY_TERMINAL',
        updated_at=v_now
    where s.invite_code=v_candidate.invite_code
      and s.submission_state='PENDING';

    update public.reward_x_promotion_post_verifications p
    set verification_state='INVALID',
        final_verified_at=null,
        invalidated_at=v_now,
        state_reason='SECURITY_TERMINAL',
        updated_at=v_now
    where p.invite_code=v_candidate.invite_code
      and p.verification_state in ('INITIAL_VERIFIED','REVIEW_REQUIRED');

    update public.reward_x_promotion_obligations o
    set financial_state='RELEASED',
        released_at=v_now,
        release_reason='SYBIL_TERMINAL',
        updated_at=v_now
    where o.id=v_obligation.id;

    v_released:=v_released+1;
  end loop;

  return jsonb_build_object(
    'network',v_network,
    'consideredCount',v_considered,
    'releasedCount',v_released
  );
end;
$function$;

revoke all on function public.record_reward_x_promotion_verification_attempt_v1(
  text,bigint,bigint,text,text,text,text,jsonb
) from PUBLIC,anon,authenticated;
grant execute on function public.record_reward_x_promotion_verification_attempt_v1(
  text,bigint,bigint,text,text,text,text,jsonb
) to service_role;

revoke all on function public.read_reward_x_promotion_pending_post_candidates_v1(text,integer)
  from PUBLIC,anon,authenticated;
grant execute on function public.read_reward_x_promotion_pending_post_candidates_v1(text,integer)
  to service_role;

revoke all on function public.read_reward_x_promotion_final_post_candidates_v1(text,integer)
  from PUBLIC,anon,authenticated;
grant execute on function public.read_reward_x_promotion_final_post_candidates_v1(text,integer)
  to service_role;

revoke all on function public.mark_reward_x_promotion_post_review_required_v1(text,text)
  from PUBLIC,anon,authenticated;
grant execute on function public.mark_reward_x_promotion_post_review_required_v1(text,text)
  to service_role;

revoke all on function public.invalidate_reward_x_promotion_post_verification_v1(text,text)
  from PUBLIC,anon,authenticated;
grant execute on function public.invalidate_reward_x_promotion_post_verification_v1(text,text)
  to service_role;

revoke all on function public.expire_reward_x_promotion_opportunities_v1(text,integer)
  from PUBLIC,anon,authenticated;
grant execute on function public.expire_reward_x_promotion_opportunities_v1(text,integer)
  to service_role;

revoke all on function public.release_terminal_reward_x_promotion_security_v1(text,integer)
  from PUBLIC,anon,authenticated;
grant execute on function public.release_terminal_reward_x_promotion_security_v1(text,integer)
  to service_role;

revoke all on function public.validate_reward_x_promotion_verification_attempt_insert()
  from PUBLIC,anon,authenticated;
revoke all on function public.reject_reward_x_promotion_verification_attempt_mutation()
  from PUBLIC,anon,authenticated;

comment on table public.reward_x_promotion_verification_attempts is
  'Append-only audit of bounded X API verification retries. It is not a payout authority and cannot move promotion funds by itself.';
