begin;

-- Recovery obligations may come from either an actual paid receipt or from the
-- economic value already consumed by a recovery settlement. Keep exactly one
-- source authority per invalidation.
alter table public.reward_recovery_obligations
  alter column source_receipt_id drop not null;

alter table public.reward_recovery_obligations
  add column if not exists source_settlement_id uuid
    references public.reward_recovery_settlements(id) on delete restrict;

alter table public.reward_recovery_obligations
  drop constraint if exists reward_recovery_obligations_network_source_invalidation_id__key;

alter table public.reward_recovery_obligations
  drop constraint if exists reward_recovery_obligations_source_kind_check;

alter table public.reward_recovery_obligations
  add constraint reward_recovery_obligations_source_kind_check
  check (num_nonnulls(source_receipt_id,source_settlement_id)=1);

create unique index if not exists reward_recovery_obligations_invalidation_uidx
  on public.reward_recovery_obligations(source_invalidation_id);

create index if not exists reward_recovery_obligations_settlement_idx
  on public.reward_recovery_obligations(source_settlement_id)
  where source_settlement_id is not null;

create table if not exists public.reward_recovery_obligation_events (
  id bigint generated by default as identity primary key,
  obligation_id uuid not null
    references public.reward_recovery_obligations(id) on delete restrict,
  event_kind text not null
    check (event_kind in ('CREATED','ACTIVATED','TOPPED_UP','REVERSED','FROZEN')),
  previous_status text,
  new_status text,
  amount_wei numeric(78,0) not null
    check (amount_wei > 0 and amount_wei=trunc(amount_wei)),
  reason text not null,
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details)='object'),
  created_at timestamptz not null default clock_timestamp()
);

alter table public.reward_recovery_obligation_events enable row level security;
revoke all on public.reward_recovery_obligation_events
  from public, anon, authenticated;
grant select on public.reward_recovery_obligation_events to service_role;

create or replace function public.prevent_reward_recovery_obligation_event_mutation()
returns trigger
language plpgsql
set search_path=pg_catalog,public
as $$
begin
  raise exception 'REWARD_RECOVERY_OBLIGATION_EVENT_APPEND_ONLY';
end;
$$;

revoke all on function public.prevent_reward_recovery_obligation_event_mutation()
  from public,anon,authenticated,service_role;

drop trigger if exists reward_recovery_obligation_events_append_only
  on public.reward_recovery_obligation_events;
create trigger reward_recovery_obligation_events_append_only
before update or delete on public.reward_recovery_obligation_events
for each row execute function public.prevent_reward_recovery_obligation_event_mutation();

insert into public.reward_recovery_obligation_events(
  obligation_id,event_kind,previous_status,new_status,amount_wei,reason,details
)
select
  o.id,'CREATED',null,o.status,o.amount_wei,
  'MIGRATION_BACKFILL',
  jsonb_build_object(
    'sourceInvalidationId',o.source_invalidation_id::text,
    'sourceReceiptId',o.source_receipt_id::text
  )
from public.reward_recovery_obligations o
where not exists (
  select 1
  from public.reward_recovery_obligation_events e
  where e.obligation_id=o.id
);

create unique index if not exists reward_recovery_review_queue_obligation_reason_uidx
  on public.reward_recovery_review_queue(reason_kind,obligation_id)
  where obligation_id is not null;

-- A recovery settlement records an immutable economic event. Later Sybil
-- invalidation creates a new obligation instead of rewriting or disabling the
-- original settlement, which prevents double-consumption when a verdict flips.
create or replace function public.prevent_reward_recovery_settlement_mutation()
returns trigger
language plpgsql
set search_path=pg_catalog,public
as $$
begin
  raise exception 'REWARD_RECOVERY_SETTLEMENT_IMMUTABLE';
end;
$$;

revoke all on function public.prevent_reward_recovery_settlement_mutation()
  from public,anon,authenticated,service_role;

update public.reward_recovery_settlements
set state='ACTIVE',updated_at=clock_timestamp()
where state<>'ACTIVE';

drop trigger if exists reward_recovery_settlements_immutable
  on public.reward_recovery_settlements;
create trigger reward_recovery_settlements_immutable
before update or delete on public.reward_recovery_settlements
for each row execute function public.prevent_reward_recovery_settlement_mutation();

create or replace function public.read_reward_recovery_balance_wei(
  p_network text,
  p_recipient_wallet text
)
returns numeric
language sql
stable
security definer
set search_path=pg_catalog,public
as $$
  with consumed as (
    select
      a.obligation_id,
      coalesce(sum(a.amount_wei),0)::numeric as consumed_wei
    from public.reward_recovery_allocations a
    group by a.obligation_id
  )
  select coalesce(sum(
    greatest(o.amount_wei-coalesce(c.consumed_wei,0),0)
  ),0)::numeric
  from public.reward_recovery_obligations o
  left join consumed c on c.obligation_id=o.id
  where o.network=lower(btrim(p_network))
    and o.recipient_wallet=lower(btrim(p_recipient_wallet))
    and o.status='ACTIVE';
$$;

revoke all on function public.read_reward_recovery_balance_wei(text,text)
  from public,anon,authenticated;
grant execute on function public.read_reward_recovery_balance_wei(text,text)
  to service_role;

create or replace function public.upsert_reward_recovery_obligation_for_invalidation(
  p_invalidation_id uuid
)
returns uuid
language plpgsql
security definer
set search_path=pg_catalog,public
as $$
declare
  v_invalidation public.sybil_v2_referral_invalidations%rowtype;
  v_settlement public.reward_recovery_settlements%rowtype;
  v_receipt public.reward_receipts%rowtype;
  v_existing public.reward_recovery_obligations%rowtype;
  v_obligation public.reward_recovery_obligations%rowtype;
  v_desired numeric(78,0) := 0;
  v_previous_status text;
  v_event_kind text := 'ACTIVATED';
begin
  select * into v_invalidation
  from public.sybil_v2_referral_invalidations x
  where x.id=p_invalidation_id
  for update;

  if not found or v_invalidation.status<>'ACTIVE' then
    return null;
  end if;

  select * into v_settlement
  from public.reward_recovery_settlements s
  where s.network=lower(v_invalidation.network)
    and s.invite_code=v_invalidation.invite_code
  limit 1;

  select * into v_receipt
  from public.reward_receipts r
  where lower(r.network)=lower(v_invalidation.network)
    and r.invite_code=v_invalidation.invite_code
  order by r.id desc
  limit 1;

  if v_settlement.id is not null then
    -- The offset itself is real economic value even without a token transfer.
    -- Add the actual net receipt only if/when it was finalized on-chain.
    v_desired :=
      v_settlement.offset_amount_wei +
      coalesce(v_receipt.amount_wei,0);
  elsif v_receipt.id is not null then
    v_desired := v_receipt.amount_wei;
  else
    return null;
  end if;

  if v_desired<=0 then
    return null;
  end if;

  select * into v_existing
  from public.reward_recovery_obligations o
  where o.source_invalidation_id=v_invalidation.id
  for update;

  if found then
    v_previous_status := v_existing.status;
    v_event_kind := case
      when v_desired>v_existing.amount_wei then 'TOPPED_UP'
      else 'ACTIVATED'
    end;

    update public.reward_recovery_obligations o
    set
      recipient_wallet=case
        when v_settlement.id is not null
          then lower(v_settlement.recipient_wallet)
        else lower(v_receipt.recipient_wallet)
      end,
      source_receipt_id=case
        when v_settlement.id is null then v_receipt.id
        else null
      end,
      source_settlement_id=case
        when v_settlement.id is not null then v_settlement.id
        else null
      end,
      source_invite_code=v_invalidation.invite_code,
      amount_wei=greatest(o.amount_wei,v_desired),
      status='ACTIVE',
      status_reason='ACTIVE_REFERRAL_INVALIDATION',
      updated_at=clock_timestamp()
    where o.id=v_existing.id
    returning * into v_obligation;
  else
    insert into public.reward_recovery_obligations(
      network,recipient_wallet,source_invalidation_id,source_receipt_id,
      source_settlement_id,source_invite_code,amount_wei,status,status_reason
    ) values (
      lower(v_invalidation.network),
      case
        when v_settlement.id is not null
          then lower(v_settlement.recipient_wallet)
        else lower(v_receipt.recipient_wallet)
      end,
      v_invalidation.id,
      case when v_settlement.id is null then v_receipt.id else null end,
      case when v_settlement.id is not null then v_settlement.id else null end,
      v_invalidation.invite_code,
      v_desired,
      'ACTIVE',
      'ACTIVE_REFERRAL_INVALIDATION'
    )
    returning * into v_obligation;

    v_previous_status := null;
    v_event_kind := 'CREATED';
  end if;

  insert into public.reward_recovery_obligation_events(
    obligation_id,event_kind,previous_status,new_status,amount_wei,reason,details
  ) values (
    v_obligation.id,
    v_event_kind,
    v_previous_status,
    v_obligation.status,
    v_obligation.amount_wei,
    'ACTIVE_REFERRAL_INVALIDATION',
    jsonb_build_object(
      'invalidationId',v_invalidation.id::text,
      'inviteCode',v_invalidation.invite_code,
      'settlementId',case when v_settlement.id is not null then v_settlement.id::text else null end,
      'receiptId',case when v_receipt.id is not null then v_receipt.id::text else null end,
      'offsetWei',case when v_settlement.id is not null then v_settlement.offset_amount_wei::text else null end,
      'paidWei',case when v_receipt.id is not null then v_receipt.amount_wei::text else '0' end
    )
  );

  return v_obligation.id;
end;
$$;

revoke all on function public.upsert_reward_recovery_obligation_for_invalidation(uuid)
  from public,anon,authenticated;
grant execute on function public.upsert_reward_recovery_obligation_for_invalidation(uuid)
  to service_role;

create or replace function public.sync_reward_recovery_invalidation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,public
as $$
declare
  v_obligation public.reward_recovery_obligations%rowtype;
  v_consumed numeric(78,0) := 0;
  v_previous_status text;
begin
  if new.status='ACTIVE' then
    perform public.upsert_reward_recovery_obligation_for_invalidation(new.id);
    return new;
  end if;

  if new.status='REINSTATED' then
    for v_obligation in
      select *
      from public.reward_recovery_obligations o
      where o.source_invalidation_id=new.id
      for update
    loop
      select coalesce(sum(a.amount_wei),0)
      into v_consumed
      from public.reward_recovery_allocations a
      where a.obligation_id=v_obligation.id;

      v_previous_status := v_obligation.status;

      if v_consumed>0 then
        update public.reward_recovery_obligations
        set
          status='FROZEN',
          status_reason='SOURCE_INVALIDATION_REINSTATED_AFTER_CONSUMPTION',
          updated_at=clock_timestamp()
        where id=v_obligation.id
        returning * into v_obligation;

        insert into public.reward_recovery_review_queue(
          network,recipient_wallet,invite_code,obligation_id,settlement_id,
          reason_kind,details
        ) values (
          v_obligation.network,
          v_obligation.recipient_wallet,
          v_obligation.source_invite_code,
          v_obligation.id,
          v_obligation.source_settlement_id,
          'SOURCE_INVALIDATION_REINSTATED_AFTER_CONSUMPTION',
          jsonb_build_object(
            'consumedWei',v_consumed::text,
            'obligationWei',v_obligation.amount_wei::text,
            'invalidationId',new.id::text
          )
        )
        on conflict do nothing;

        insert into public.reward_recovery_obligation_events(
          obligation_id,event_kind,previous_status,new_status,amount_wei,reason,details
        ) values (
          v_obligation.id,'FROZEN',v_previous_status,'FROZEN',
          v_obligation.amount_wei,
          'SOURCE_INVALIDATION_REINSTATED_AFTER_CONSUMPTION',
          jsonb_build_object('consumedWei',v_consumed::text)
        );
      else
        update public.reward_recovery_obligations
        set
          status='REVERSED',
          status_reason='SOURCE_INVALIDATION_REINSTATED_BEFORE_CONSUMPTION',
          updated_at=clock_timestamp()
        where id=v_obligation.id
        returning * into v_obligation;

        insert into public.reward_recovery_obligation_events(
          obligation_id,event_kind,previous_status,new_status,amount_wei,reason,details
        ) values (
          v_obligation.id,'REVERSED',v_previous_status,'REVERSED',
          v_obligation.amount_wei,
          'SOURCE_INVALIDATION_REINSTATED_BEFORE_CONSUMPTION',
          jsonb_build_object('consumedWei','0')
        );
      end if;
    end loop;
  end if;

  return new;
end;
$$;

revoke all on function public.sync_reward_recovery_invalidation()
  from public,anon,authenticated,service_role;

drop trigger if exists sybil_v2_reward_recovery_sync
  on public.sybil_v2_referral_invalidations;
create trigger sybil_v2_reward_recovery_sync
after insert or update of status
on public.sybil_v2_referral_invalidations
for each row execute function public.sync_reward_recovery_invalidation();

-- If an invalid referral's positive net transfer finalizes after the
-- invalidation was already recorded, top the obligation up by the actual paid
-- receipt. This is idempotent because the invalidation is the unique source.
create or replace function public.sync_reward_recovery_receipt()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,public
as $$
declare
  v_invalidation_id uuid;
begin
  select x.id
  into v_invalidation_id
  from public.sybil_v2_referral_invalidations x
  where x.network=lower(new.network)
    and x.invite_code=new.invite_code
    and x.status='ACTIVE'
  order by x.decided_at desc,x.id desc
  limit 1;

  if v_invalidation_id is not null then
    perform public.upsert_reward_recovery_obligation_for_invalidation(
      v_invalidation_id
    );
  end if;

  return new;
end;
$$;

revoke all on function public.sync_reward_recovery_receipt()
  from public,anon,authenticated,service_role;

drop trigger if exists reward_receipt_recovery_sync
  on public.reward_receipts;
create trigger reward_receipt_recovery_sync
after insert on public.reward_receipts
for each row execute function public.sync_reward_recovery_receipt();

create or replace function public.read_reward_cohort_committed_wei(
  p_network text,
  p_app_id text,
  p_reward_cohort_round_id bigint,
  p_allocation_receipt_id bigint
)
returns numeric
language plpgsql
stable
security invoker
set search_path=pg_catalog,public
as $$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
  v_queue_committed numeric(78,0) := 0;
  v_offset_committed numeric(78,0) := 0;
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  if p_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'unsupported network';
  end if;
  if p_reward_cohort_round_id is null or p_reward_cohort_round_id<1 then
    raise exception 'invalid reward cohort round';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id=p_allocation_receipt_id
    and a.network=p_network
    and a.app_id=p_app_id;

  if not found
     or v_receipt.vebetter_round_id+1<>p_reward_cohort_round_id then
    raise exception 'allocation receipt does not fund the requested reward cohort';
  end if;

  select coalesce(sum(q.reserved_amount_wei),0)
  into v_queue_committed
  from public.reward_queue_entries q
  join public.invitations i on i.invite_code=q.invite_code
  where q.network=p_network
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=p_reward_cohort_round_id
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED');

  select coalesce(sum(s.offset_amount_wei),0)
  into v_offset_committed
  from public.reward_recovery_settlements s
  join public.invitations i on i.invite_code=s.invite_code
  where s.network=p_network
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=p_reward_cohort_round_id;

  return v_queue_committed+v_offset_committed;
end;
$$;

revoke all on function public.read_reward_cohort_committed_wei(text,text,bigint,bigint)
  from public,anon,authenticated;
grant execute on function public.read_reward_cohort_committed_wei(text,text,bigint,bigint)
  to service_role;

create or replace function public.enforce_reward_queue_cohort_budget()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,public
as $$
declare
  v_invitation public.invitations%rowtype;
  v_receipt public.vebetter_round_allocations%rowtype;
  v_adjustment numeric(78,0) := 0;
  v_existing_queue numeric(78,0) := 0;
  v_existing_offset numeric(78,0) := 0;
  v_current_offset numeric(78,0) := 0;
  v_budget numeric(78,0) := 0;
begin
  if new.reserved_amount_wei is null then return new; end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=new.invite_code;

  if not found
     or v_invitation.reward_cohort_round_id is null
     or v_invitation.reward_funding_allocation_receipt_id is null then
    raise exception 'REWARD_COHORT_BINDING_REQUIRED';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id=v_invitation.reward_funding_allocation_receipt_id;

  if not found
     or v_receipt.network<>new.network
     or v_receipt.vebetter_round_id+1<>v_invitation.reward_cohort_round_id then
    raise exception 'REWARD_COHORT_FUNDING_MISMATCH';
  end if;

  select coalesce(sum(a.amount_wei),0)
  into v_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network=v_receipt.network
    and a.app_id=v_receipt.app_id
    and a.reward_cohort_round_id=v_invitation.reward_cohort_round_id
    and a.allocation_receipt_id=v_receipt.id;

  v_budget:=v_receipt.rewards_allocation_amount_wei+v_adjustment;

  select coalesce(sum(q.reserved_amount_wei),0)
  into v_existing_queue
  from public.reward_queue_entries q
  join public.invitations i on i.invite_code=q.invite_code
  where q.network=new.network
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=v_invitation.reward_cohort_round_id
    and q.invite_code<>new.invite_code
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED');

  select coalesce(sum(s.offset_amount_wei),0)
  into v_existing_offset
  from public.reward_recovery_settlements s
  join public.invitations i on i.invite_code=s.invite_code
  where s.network=new.network
    and s.invite_code<>new.invite_code
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=v_invitation.reward_cohort_round_id;

  select coalesce(s.offset_amount_wei,0)
  into v_current_offset
  from public.reward_recovery_settlements s
  where s.invite_code=new.invite_code
    and s.network=new.network;

  if not found then v_current_offset:=0; end if;

  if v_existing_queue+v_existing_offset+
     new.reserved_amount_wei+v_current_offset>v_budget then
    raise exception 'REWARD_COHORT_BUDGET_EXCEEDED';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_reward_queue_cohort_budget()
  from public,anon,authenticated;
grant execute on function public.enforce_reward_queue_cohort_budget()
  to service_role;

create or replace function public.get_lifetime_recognized_referral_ranking_v3_internal(
  p_network text,
  p_max_block bigint default null
)
returns table(
  rank_position bigint,
  wallet_address text,
  completed_referrals bigint,
  total_reward_wei numeric,
  reached_count_block bigint,
  reached_count_tx_index integer,
  reached_count_clause_index integer,
  reached_count_tx_id text
)
language sql
stable
set search_path=public
as $$
  with parameters as (
    select lower(btrim(p_network)) as network
  ),
  paid_referrals as (
    select
      lower(btrim(r.recipient_wallet)) as wallet_address,
      r.invite_code,
      r.amount_wei::numeric as amount_wei,
      q.reservation_completion_block as completion_block,
      q.reservation_completion_tx_index as completion_tx_index,
      q.reservation_completion_clause_index as completion_clause_index,
      lower(btrim(s.tx_id)) as proof_tx_id
    from public.reward_receipts r
    join public.reward_payout_transaction_settlements s
      on s.id=r.settlement_id
    join public.reward_queue_entries q
      on q.invite_code=r.invite_code
     and lower(btrim(q.recipient_wallet))=lower(btrim(r.recipient_wallet))
    cross join parameters p
    where lower(btrim(r.network))=p.network
      and lower(btrim(s.network))=p.network
      and lower(btrim(q.network))=p.network
      and r.amount_wei>0
      and q.reservation_completion_block is not null
      and q.reservation_completion_tx_index is not null
      and q.reservation_completion_clause_index is not null
      and (
        p_max_block is null
        or (
          s.block_number<=p_max_block
          and q.reservation_completion_block<=p_max_block
        )
      )
      and not public.is_analytics_excluded_wallet(r.recipient_wallet)
      and not public.is_analytics_excluded_invite_code(r.invite_code)
      and not public.is_sybil_v2_referral_invalidated(r.invite_code,p.network)
  ),
  full_offset_referrals as (
    select
      lower(btrim(s.recipient_wallet)) as wallet_address,
      s.invite_code,
      0::numeric as amount_wei,
      s.completion_block,
      s.completion_tx_index,
      s.completion_clause_index,
      lower(btrim(s.completion_tx_id)) as proof_tx_id
    from public.reward_recovery_settlements s
    cross join parameters p
    where s.network=p.network
      and s.settlement_kind='FULL_OFFSET'
      and s.net_amount_wei=0
      and (
        p_max_block is null
        or s.completion_block<=p_max_block
      )
      and not public.is_analytics_excluded_wallet(s.recipient_wallet)
      and not public.is_analytics_excluded_invite_code(s.invite_code)
      and not public.is_sybil_v2_referral_invalidated(s.invite_code,p.network)
  ),
  recognized as (
    select * from paid_referrals
    union all
    select * from full_offset_referrals
  ),
  deduped as (
    select distinct on (wallet_address,invite_code)
      wallet_address,invite_code,amount_wei,
      completion_block,completion_tx_index,completion_clause_index,proof_tx_id
    from recognized
    order by
      wallet_address,invite_code,
      completion_block asc,completion_tx_index asc,completion_clause_index asc,
      proof_tx_id asc
  ),
  totals as (
    select
      wallet_address,
      count(*)::bigint as completed_referrals,
      coalesce(sum(amount_wei),0)::numeric as total_reward_wei
    from deduped
    group by wallet_address
  ),
  reached as (
    select distinct on (wallet_address)
      wallet_address,
      completion_block as reached_count_block,
      completion_tx_index as reached_count_tx_index,
      completion_clause_index as reached_count_clause_index,
      proof_tx_id as reached_count_tx_id
    from deduped
    order by
      wallet_address,
      completion_block desc,
      completion_tx_index desc,
      completion_clause_index desc,
      invite_code desc
  ),
  ranked as (
    select
      row_number() over (
        order by
          t.completed_referrals desc,
          r.reached_count_block asc,
          r.reached_count_tx_index asc,
          r.reached_count_clause_index asc,
          t.wallet_address asc
      )::bigint as rank_position,
      t.wallet_address,
      t.completed_referrals,
      t.total_reward_wei,
      r.reached_count_block,
      r.reached_count_tx_index,
      r.reached_count_clause_index,
      r.reached_count_tx_id
    from totals t
    join reached r using(wallet_address)
  )
  select * from ranked order by rank_position;
$$;

revoke all on function public.get_lifetime_recognized_referral_ranking_v3_internal(text,bigint)
  from public,anon,authenticated;
grant execute on function public.get_lifetime_recognized_referral_ranking_v3_internal(text,bigint)
  to service_role;

commit;
