create table if not exists public.reward_x_promotion_payout_checkpoints (
  intent_id bigint primary key
    references public.reward_x_promotion_payout_intents(id) on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  block_id text not null check (block_id ~ '^0x[0-9a-f]{64}$'),
  block_number bigint not null check (block_number >= 0),
  block_timestamp bigint not null check (block_timestamp >= 0),
  recorded_at timestamptz not null default now()
);

create table if not exists public.reward_x_promotion_payout_signed_transactions (
  id bigint generated by default as identity primary key,
  intent_id bigint not null unique
    references public.reward_x_promotion_payout_intents(id) on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  tx_id text not null unique check (tx_id ~ '^0x[0-9a-f]{64}$'),
  operator_wallet text not null check (operator_wallet ~ '^0x[0-9a-f]{40}$'),
  raw_tx_hex text not null check (raw_tx_hex ~ '^0x[0-9a-f]+$'),
  created_at timestamptz not null default now()
);

create table if not exists public.reward_x_promotion_payout_submissions (
  id bigint generated by default as identity primary key,
  intent_id bigint not null unique
    references public.reward_x_promotion_payout_intents(id) on delete restrict,
  signed_transaction_id bigint not null unique
    references public.reward_x_promotion_payout_signed_transactions(id) on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  tx_id text not null unique check (tx_id ~ '^0x[0-9a-f]{64}$'),
  operator_wallet text not null check (operator_wallet ~ '^0x[0-9a-f]{40}$'),
  registered_at timestamptz not null default now()
);

create table if not exists public.reward_x_promotion_payout_settlements (
  id bigint generated by default as identity primary key,
  intent_id bigint not null unique
    references public.reward_x_promotion_payout_intents(id) on delete restrict,
  submission_id bigint not null unique
    references public.reward_x_promotion_payout_submissions(id) on delete restrict,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  tx_id text not null unique check (tx_id ~ '^0x[0-9a-f]{64}$'),
  tx_origin text not null check (tx_origin ~ '^0x[0-9a-f]{40}$'),
  block_id text not null check (block_id ~ '^0x[0-9a-f]{64}$'),
  block_number bigint not null check (block_number >= 0),
  block_timestamp bigint not null check (block_timestamp >= 0),
  finalized_head_id text not null check (finalized_head_id ~ '^0x[0-9a-f]{64}$'),
  finalized_head_number bigint not null check (finalized_head_number >= block_number),
  clause_count integer not null check (clause_count = 1),
  verified_at timestamptz not null default now(),
  paid_at timestamptz not null
);

create table if not exists public.reward_x_promotion_receipts (
  id bigint generated by default as identity primary key,
  receipt_version text not null default 'veinvite-x-promotion-receipt-v1'
    check (receipt_version='veinvite-x-promotion-receipt-v1'),
  intent_id bigint not null unique
    references public.reward_x_promotion_payout_intents(id) on delete restrict,
  settlement_id bigint not null unique
    references public.reward_x_promotion_payout_settlements(id) on delete restrict,
  obligation_id bigint not null unique
    references public.reward_x_promotion_obligations(id) on delete restrict,
  split_id bigint not null unique
    references public.reward_x_promotion_splits(id) on delete restrict,
  invite_code text not null unique check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  source_reward_cohort_round_id bigint not null
    check (source_reward_cohort_round_id >= 1),
  source_allocation_receipt_id bigint not null
    references public.vebetter_round_allocations(id) on delete restrict,
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  amount_wei numeric(78,0) not null
    check (amount_wei > 0 and amount_wei=trunc(amount_wei)),
  public_proof_id uuid not null unique,
  x_post_id text not null unique check (x_post_id ~ '^[0-9]{1,32}$'),
  x_author_id text not null check (x_author_id ~ '^[0-9]{1,32}$'),
  tx_id text not null unique check (tx_id ~ '^0x[0-9a-f]{64}$'),
  paid_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists reward_x_promotion_payout_settlements_paid_idx
  on public.reward_x_promotion_payout_settlements(paid_at desc,id desc);
create index if not exists reward_x_promotion_receipts_wallet_paid_idx
  on public.reward_x_promotion_receipts(recipient_wallet,paid_at desc,id desc);
create index if not exists reward_x_promotion_receipts_source_idx
  on public.reward_x_promotion_receipts(
    network,source_reward_cohort_round_id,source_allocation_receipt_id
  );

alter table public.reward_x_promotion_payout_checkpoints enable row level security;
alter table public.reward_x_promotion_payout_signed_transactions enable row level security;
alter table public.reward_x_promotion_payout_submissions enable row level security;
alter table public.reward_x_promotion_payout_settlements enable row level security;
alter table public.reward_x_promotion_receipts enable row level security;

revoke all on table public.reward_x_promotion_payout_checkpoints
  from public,anon,authenticated,service_role;
revoke all on table public.reward_x_promotion_payout_signed_transactions
  from public,anon,authenticated,service_role;
revoke all on table public.reward_x_promotion_payout_submissions
  from public,anon,authenticated,service_role;
revoke all on table public.reward_x_promotion_payout_settlements
  from public,anon,authenticated,service_role;
revoke all on table public.reward_x_promotion_receipts
  from public,anon,authenticated,service_role;

revoke all on sequence public.reward_x_promotion_payout_signed_transactions_id_seq
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_payout_submissions_id_seq
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_payout_settlements_id_seq
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_receipts_id_seq
  from public,anon,authenticated,service_role;

grant select on table public.reward_x_promotion_payout_checkpoints to service_role;
grant select on table public.reward_x_promotion_payout_signed_transactions to service_role;
grant select on table public.reward_x_promotion_payout_submissions to service_role;
grant select on table public.reward_x_promotion_payout_settlements to service_role;
grant select on table public.reward_x_promotion_receipts to service_role;

create or replace function public.reject_reward_x_promotion_payout_journal_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'REWARD_X_PROMOTION_PAYOUT_JOURNAL_IMMUTABLE';
end;
$function$;

drop trigger if exists reward_x_promotion_payout_checkpoints_append_only
  on public.reward_x_promotion_payout_checkpoints;
create trigger reward_x_promotion_payout_checkpoints_append_only
before update or delete on public.reward_x_promotion_payout_checkpoints
for each row execute function public.reject_reward_x_promotion_payout_journal_mutation();

drop trigger if exists reward_x_promotion_payout_signed_transactions_append_only
  on public.reward_x_promotion_payout_signed_transactions;
create trigger reward_x_promotion_payout_signed_transactions_append_only
before update or delete on public.reward_x_promotion_payout_signed_transactions
for each row execute function public.reject_reward_x_promotion_payout_journal_mutation();

drop trigger if exists reward_x_promotion_payout_submissions_append_only
  on public.reward_x_promotion_payout_submissions;
create trigger reward_x_promotion_payout_submissions_append_only
before update or delete on public.reward_x_promotion_payout_submissions
for each row execute function public.reject_reward_x_promotion_payout_journal_mutation();

drop trigger if exists reward_x_promotion_payout_settlements_append_only
  on public.reward_x_promotion_payout_settlements;
create trigger reward_x_promotion_payout_settlements_append_only
before update or delete on public.reward_x_promotion_payout_settlements
for each row execute function public.reject_reward_x_promotion_payout_journal_mutation();

drop trigger if exists reward_x_promotion_receipts_append_only
  on public.reward_x_promotion_receipts;
create trigger reward_x_promotion_receipts_append_only
before update or delete on public.reward_x_promotion_receipts
for each row execute function public.reject_reward_x_promotion_payout_journal_mutation();

create or replace function public.reward_x_promotion_security_clear_v1(
  p_invite_code text,
  p_network text
)
returns boolean
language plpgsql
stable
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(coalesce(p_invite_code,'')));
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_invitation public.invitations%rowtype;
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$'
     or v_network not in ('mainnet','testnet','testnet-staging') then
    return false;
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=v_code
    and i.activation_network=v_network;

  if not found
     or v_invitation.inviter_wallet is null
     or v_invitation.invitee_wallet is null
     or v_invitation.sybil_status<>'CLEAR'
     or v_invitation.sybil_checked_at is null
     or public.is_sybil_v2_referral_invalidated(v_code,v_network)
     or exists (
       select 1
       from public.sybil_v2_wallet_restrictions r
       where r.network=v_network
         and r.status='ACTIVE'
         and r.wallet_address in (
           lower(v_invitation.inviter_wallet),
           lower(v_invitation.invitee_wallet)
         )
     ) then
    return false;
  end if;

  return exists (
    select 1
    from public.sybil_v2_reward_clearances c
    join public.sybil_v2_referral_assessments a
      on a.invite_code=c.invite_code
     and a.network=c.network
     and a.revision=c.assessment_revision
     and a.state=c.verdict
    where c.invite_code=v_code
      and c.network=v_network
      and c.verdict='CLEAR'
  );
end;
$function$;

create or replace function public.create_reward_x_promotion_payout_checkpoint_v1(
  p_intent_id bigint,
  p_block_id text,
  p_block_number bigint,
  p_block_timestamp bigint
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_intent public.reward_x_promotion_payout_intents%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_existing public.reward_x_promotion_payout_checkpoints%rowtype;
  v_cfg public.reward_runtime_config%rowtype;
begin
  p_block_id:=lower(btrim(coalesce(p_block_id,'')));

  if p_intent_id is null or p_intent_id<1 then
    raise exception 'REWARD_X_PROMOTION_INTENT_ID_INVALID';
  end if;
  if p_block_id !~ '^0x[0-9a-f]{64}$'
     or p_block_number is null or p_block_number<0
     or p_block_timestamp is null or p_block_timestamp<0 then
    raise exception 'REWARD_X_PROMOTION_CHECKPOINT_INVALID';
  end if;

  select * into v_intent
  from public.reward_x_promotion_payout_intents i
  where i.id=p_intent_id;

  if not found then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_MISSING';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_intent.invite_code,0)
  );

  select * into v_cfg
  from public.reward_runtime_config
  where id=1;

  if not found
     or not v_cfg.reward_x_promotion_enabled
     or v_cfg.reward_x_promotion_live_started_at is null then
    raise exception 'REWARD_X_PROMOTION_LIVE_DISABLED';
  end if;

  select * into v_existing
  from public.reward_x_promotion_payout_checkpoints c
  where c.intent_id=p_intent_id;

  if found then
    if v_existing.network=v_intent.network
       and v_existing.block_id=p_block_id
       and v_existing.block_number=p_block_number
       and v_existing.block_timestamp=p_block_timestamp then
      return jsonb_build_object(
        'created',false,'intentId',p_intent_id,
        'blockId',v_existing.block_id,
        'blockNumber',v_existing.block_number
      );
    end if;
    raise exception 'REWARD_X_PROMOTION_CHECKPOINT_IMMUTABLE_MISMATCH';
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=v_intent.obligation_id;

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.id=v_intent.verification_id;

  if v_obligation.id is null
     or v_obligation.financial_state<>'HELD'
     or v_verification.id is null
     or v_verification.verification_state<>'FINAL_VERIFIED'
     or not public.reward_x_promotion_security_clear_v1(
       v_intent.invite_code,
       v_intent.network
     ) then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_AUTHORITY_NOT_READY';
  end if;

  insert into public.reward_x_promotion_payout_checkpoints(
    intent_id,network,block_id,block_number,block_timestamp
  ) values (
    v_intent.id,v_intent.network,p_block_id,p_block_number,p_block_timestamp
  );

  return jsonb_build_object(
    'created',true,'intentId',p_intent_id,
    'blockId',p_block_id,'blockNumber',p_block_number
  );
end;
$function$;

create or replace function public.register_reward_x_promotion_signed_submission_v1(
  p_intent_id bigint,
  p_tx_id text,
  p_operator_wallet text,
  p_raw_tx_hex text
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_intent public.reward_x_promotion_payout_intents%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_checkpoint public.reward_x_promotion_payout_checkpoints%rowtype;
  v_existing_signed public.reward_x_promotion_payout_signed_transactions%rowtype;
  v_existing_submission public.reward_x_promotion_payout_submissions%rowtype;
  v_signed public.reward_x_promotion_payout_signed_transactions%rowtype;
  v_submission public.reward_x_promotion_payout_submissions%rowtype;
  v_cfg public.reward_runtime_config%rowtype;
begin
  p_tx_id:=lower(btrim(coalesce(p_tx_id,'')));
  p_operator_wallet:=lower(btrim(coalesce(p_operator_wallet,'')));
  p_raw_tx_hex:=lower(btrim(coalesce(p_raw_tx_hex,'')));

  if p_intent_id is null or p_intent_id<1
     or p_tx_id !~ '^0x[0-9a-f]{64}$'
     or p_operator_wallet !~ '^0x[0-9a-f]{40}$'
     or p_raw_tx_hex !~ '^0x[0-9a-f]+$' then
    raise exception 'REWARD_X_PROMOTION_SIGNED_SUBMISSION_INVALID';
  end if;

  select * into v_intent
  from public.reward_x_promotion_payout_intents i
  where i.id=p_intent_id;

  if not found then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_MISSING';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_intent.invite_code,0)
  );

  select * into v_cfg
  from public.reward_runtime_config
  where id=1;

  if not found
     or not v_cfg.reward_x_promotion_enabled
     or v_cfg.reward_x_promotion_live_started_at is null then
    raise exception 'REWARD_X_PROMOTION_LIVE_DISABLED';
  end if;

  select * into v_existing_signed
  from public.reward_x_promotion_payout_signed_transactions s
  where s.intent_id=p_intent_id;

  select * into v_existing_submission
  from public.reward_x_promotion_payout_submissions s
  where s.intent_id=p_intent_id;

  if v_existing_signed.id is not null
     or v_existing_submission.id is not null then
    if v_existing_signed.id is not null
       and v_existing_submission.id is not null
       and v_existing_signed.tx_id=p_tx_id
       and v_existing_signed.operator_wallet=p_operator_wallet
       and v_existing_signed.raw_tx_hex=p_raw_tx_hex
       and v_existing_submission.signed_transaction_id=v_existing_signed.id
       and v_existing_submission.tx_id=p_tx_id
       and v_existing_submission.operator_wallet=p_operator_wallet then
      return jsonb_build_object(
        'created',false,
        'signedTransactionId',v_existing_signed.id,
        'submissionId',v_existing_submission.id,
        'intentId',p_intent_id,
        'txId',p_tx_id
      );
    end if;
    raise exception 'REWARD_X_PROMOTION_SIGNED_SUBMISSION_PARTIAL_OR_MISMATCH';
  end if;

  if exists (
    select 1 from public.reward_payout_signed_transactions s
    where s.tx_id=p_tx_id
    union all
    select 1 from public.reward_payout_transaction_submissions s
    where s.tx_id=p_tx_id
    union all
    select 1 from public.reward_payout_transaction_settlements s
    where s.tx_id=p_tx_id
    union all
    select 1 from public.reward_payouts p
    where p.tx_id=p_tx_id
  ) then
    raise exception 'REWARD_X_PROMOTION_TX_ALREADY_USED_BY_REFERRAL_REWARD';
  end if;

  select * into v_checkpoint
  from public.reward_x_promotion_payout_checkpoints c
  where c.intent_id=p_intent_id;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=v_intent.obligation_id
  for update;

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.id=v_intent.verification_id;

  if v_checkpoint.intent_id is null
     or v_checkpoint.network<>v_intent.network
     or v_obligation.id is null
     or v_obligation.financial_state<>'HELD'
     or v_verification.id is null
     or v_verification.verification_state<>'FINAL_VERIFIED'
     or not public.reward_x_promotion_security_clear_v1(
       v_intent.invite_code,
       v_intent.network
     ) then
    raise exception 'REWARD_X_PROMOTION_SIGNING_AUTHORITY_NOT_READY';
  end if;

  insert into public.reward_x_promotion_payout_signed_transactions(
    intent_id,network,tx_id,operator_wallet,raw_tx_hex
  ) values (
    v_intent.id,v_intent.network,p_tx_id,p_operator_wallet,p_raw_tx_hex
  )
  returning * into v_signed;

  insert into public.reward_x_promotion_payout_submissions(
    intent_id,signed_transaction_id,network,tx_id,operator_wallet
  ) values (
    v_intent.id,v_signed.id,v_intent.network,p_tx_id,p_operator_wallet
  )
  returning * into v_submission;

  return jsonb_build_object(
    'created',true,
    'signedTransactionId',v_signed.id,
    'submissionId',v_submission.id,
    'intentId',p_intent_id,
    'txId',p_tx_id
  );
end;
$function$;

create or replace function public.finalize_reward_x_promotion_payout_v1(
  p_intent_id bigint,
  p_tx_id text,
  p_tx_origin text,
  p_block_id text,
  p_block_number bigint,
  p_block_timestamp bigint,
  p_finalized_head_id text,
  p_finalized_head_number bigint,
  p_clause_count integer
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_intent public.reward_x_promotion_payout_intents%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_checkpoint public.reward_x_promotion_payout_checkpoints%rowtype;
  v_signed public.reward_x_promotion_payout_signed_transactions%rowtype;
  v_submission public.reward_x_promotion_payout_submissions%rowtype;
  v_existing public.reward_x_promotion_payout_settlements%rowtype;
  v_settlement public.reward_x_promotion_payout_settlements%rowtype;
  v_receipt public.reward_x_promotion_receipts%rowtype;
  v_paid_at timestamptz;
begin
  p_tx_id:=lower(btrim(coalesce(p_tx_id,'')));
  p_tx_origin:=lower(btrim(coalesce(p_tx_origin,'')));
  p_block_id:=lower(btrim(coalesce(p_block_id,'')));
  p_finalized_head_id:=lower(btrim(coalesce(p_finalized_head_id,'')));

  if p_intent_id is null or p_intent_id<1
     or p_tx_id !~ '^0x[0-9a-f]{64}$'
     or p_tx_origin !~ '^0x[0-9a-f]{40}$'
     or p_block_id !~ '^0x[0-9a-f]{64}$'
     or p_finalized_head_id !~ '^0x[0-9a-f]{64}$'
     or p_block_number is null or p_block_number<0
     or p_block_timestamp is null or p_block_timestamp<0
     or p_finalized_head_number is null
     or p_finalized_head_number<p_block_number
     or p_clause_count<>1 then
    raise exception 'REWARD_X_PROMOTION_SETTLEMENT_INVALID';
  end if;

  select * into v_intent
  from public.reward_x_promotion_payout_intents i
  where i.id=p_intent_id;

  if not found then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_MISSING';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_intent.invite_code,0)
  );

  select * into v_existing
  from public.reward_x_promotion_payout_settlements s
  where s.intent_id=p_intent_id;

  if found then
    if v_existing.tx_id=p_tx_id
       and v_existing.tx_origin=p_tx_origin
       and v_existing.block_id=p_block_id
       and v_existing.block_number=p_block_number
       and v_existing.block_timestamp=p_block_timestamp
       and v_existing.finalized_head_id=p_finalized_head_id
       and v_existing.finalized_head_number=p_finalized_head_number
       and v_existing.clause_count=p_clause_count then
      return jsonb_build_object(
        'created',false,'settlementId',v_existing.id,
        'intentId',p_intent_id,'txId',v_existing.tx_id,
        'paidAt',v_existing.paid_at
      );
    end if;
    raise exception 'REWARD_X_PROMOTION_SETTLEMENT_IMMUTABLE_MISMATCH';
  end if;

  if exists (
    select 1 from public.reward_payout_transaction_settlements s
    where s.tx_id=p_tx_id
    union all
    select 1 from public.reward_payouts p
    where p.tx_id=p_tx_id
  ) then
    raise exception 'REWARD_X_PROMOTION_TX_ALREADY_USED_BY_REFERRAL_REWARD';
  end if;

  select * into v_checkpoint
  from public.reward_x_promotion_payout_checkpoints c
  where c.intent_id=p_intent_id;

  select * into v_signed
  from public.reward_x_promotion_payout_signed_transactions s
  where s.intent_id=p_intent_id;

  select * into v_submission
  from public.reward_x_promotion_payout_submissions s
  where s.intent_id=p_intent_id;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=v_intent.obligation_id
  for update;

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.id=v_intent.verification_id;

  if v_checkpoint.intent_id is null
     or v_signed.id is null
     or v_submission.id is null
     or v_signed.tx_id<>p_tx_id
     or v_submission.tx_id<>p_tx_id
     or v_signed.operator_wallet<>p_tx_origin
     or v_submission.operator_wallet<>p_tx_origin
     or v_signed.network<>v_intent.network
     or v_submission.network<>v_intent.network
     or v_obligation.id is null
     or v_obligation.financial_state<>'HELD'
     or v_verification.id is null
     or v_verification.verification_state<>'FINAL_VERIFIED'
     or p_block_number<=v_checkpoint.block_number then
    raise exception 'REWARD_X_PROMOTION_SETTLEMENT_PROOF_MISMATCH';
  end if;

  v_paid_at:=to_timestamp(p_block_timestamp);

  if v_paid_at < v_intent.created_at - interval '60 seconds' then
    raise exception 'REWARD_X_PROMOTION_SETTLEMENT_PREDATES_INTENT';
  end if;

  insert into public.reward_x_promotion_payout_settlements(
    intent_id,submission_id,network,tx_id,tx_origin,
    block_id,block_number,block_timestamp,
    finalized_head_id,finalized_head_number,clause_count,paid_at
  ) values (
    v_intent.id,v_submission.id,v_intent.network,p_tx_id,p_tx_origin,
    p_block_id,p_block_number,p_block_timestamp,
    p_finalized_head_id,p_finalized_head_number,p_clause_count,v_paid_at
  )
  returning * into v_settlement;

  insert into public.reward_x_promotion_receipts(
    intent_id,settlement_id,obligation_id,split_id,invite_code,network,
    source_reward_cohort_round_id,source_allocation_receipt_id,
    recipient_wallet,amount_wei,public_proof_id,x_post_id,x_author_id,
    tx_id,paid_at
  ) values (
    v_intent.id,v_settlement.id,v_intent.obligation_id,v_intent.split_id,
    v_intent.invite_code,v_intent.network,
    v_intent.source_reward_cohort_round_id,v_intent.source_allocation_receipt_id,
    v_intent.recipient_wallet,v_intent.amount_wei,v_intent.public_proof_id,
    v_intent.x_post_id,v_intent.x_author_id,p_tx_id,v_paid_at
  )
  returning * into v_receipt;

  update public.reward_x_promotion_obligations o
  set financial_state='PAID',
      paid_at=v_paid_at,
      released_at=null,
      release_reason=null,
      updated_at=now()
  where o.id=v_obligation.id
    and o.financial_state='HELD';

  if not found then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_PAID_TRANSITION_FAILED';
  end if;

  return jsonb_build_object(
    'created',true,'settlementId',v_settlement.id,
    'receiptId',v_receipt.id,'intentId',p_intent_id,
    'txId',p_tx_id,'paidAt',v_paid_at
  );
end;
$function$;

create or replace function public.guard_reward_x_promotion_obligation_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  if tg_op='DELETE' then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_DELETE_FORBIDDEN';
  end if;

  if old.split_id is distinct from new.split_id
     or old.invite_code is distinct from new.invite_code
     or old.network is distinct from new.network
     or old.recipient_wallet is distinct from new.recipient_wallet
     or old.promotion_amount_wei is distinct from new.promotion_amount_wei
     or old.source_reward_cohort_round_id is distinct from new.source_reward_cohort_round_id
     or old.source_allocation_receipt_id is distinct from new.source_allocation_receipt_id
     or old.policy_version is distinct from new.policy_version
     or old.created_at is distinct from new.created_at then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_IDENTITY_IMMUTABLE';
  end if;

  if old.financial_state=new.financial_state then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_STATE_CHANGE_REQUIRED';
  end if;

  if new.financial_state='PAID' then
    if old.financial_state<>'HELD'
       or new.held_at is null
       or new.released_at is not null
       or new.release_reason is not null
       or new.paid_at is null
       or not exists (
         select 1
         from public.reward_x_promotion_payout_intents i
         join public.reward_x_promotion_payout_settlements s
           on s.intent_id=i.id
         join public.reward_x_promotion_receipts r
           on r.intent_id=i.id
          and r.settlement_id=s.id
         where i.obligation_id=old.id
           and i.invite_code=old.invite_code
           and i.network=old.network
           and i.recipient_wallet=old.recipient_wallet
           and i.amount_wei=old.promotion_amount_wei
           and s.tx_id=r.tx_id
           and s.paid_at=new.paid_at
           and r.paid_at=new.paid_at
           and r.amount_wei=old.promotion_amount_wei
       ) then
      raise exception 'REWARD_X_PROMOTION_PAID_PROOF_MISSING';
    end if;
    return new;
  end if;

  if new.financial_state='RELEASED' then
    if exists (
      select 1
      from public.reward_x_promotion_payout_intents i
      join public.reward_x_promotion_payout_signed_transactions s
        on s.intent_id=i.id
      where i.obligation_id=old.id
    ) then
      raise exception 'REWARD_X_PROMOTION_SIGNED_TX_PREVENTS_RELEASE';
    end if;
  end if;

  if not (
    (old.financial_state='RESERVED' and new.financial_state in ('HELD','RELEASED'))
    or
    (old.financial_state='HELD' and new.financial_state='RELEASED')
  ) then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_TRANSITION_INVALID';
  end if;

  return new;
end;
$function$;

revoke all on function public.reject_reward_x_promotion_payout_journal_mutation()
  from public,anon,authenticated,service_role;
revoke all on function public.reward_x_promotion_security_clear_v1(text,text)
  from PUBLIC,anon,authenticated;
grant execute on function public.reward_x_promotion_security_clear_v1(text,text)
  to service_role;
revoke all on function public.create_reward_x_promotion_payout_checkpoint_v1(bigint,text,bigint,bigint)
  from PUBLIC,anon,authenticated;
grant execute on function public.create_reward_x_promotion_payout_checkpoint_v1(bigint,text,bigint,bigint)
  to service_role;
revoke all on function public.register_reward_x_promotion_signed_submission_v1(bigint,text,text,text)
  from PUBLIC,anon,authenticated;
grant execute on function public.register_reward_x_promotion_signed_submission_v1(bigint,text,text,text)
  to service_role;
revoke all on function public.finalize_reward_x_promotion_payout_v1(
  bigint,text,text,text,bigint,bigint,text,bigint,integer
) from PUBLIC,anon,authenticated;
grant execute on function public.finalize_reward_x_promotion_payout_v1(
  bigint,text,text,text,bigint,bigint,text,bigint,integer
) to service_role;
revoke all on function public.guard_reward_x_promotion_obligation_mutation()
  from public,anon,authenticated,service_role;

comment on table public.reward_x_promotion_payout_signed_transactions is
  'Immutable signed raw transaction journal for one X Promotion payout intent. Signed transaction and submission rows are created atomically after one final current-security check.';
comment on table public.reward_x_promotion_payout_settlements is
  'Immutable finalized on-chain settlement proof for one X Promotion payout intent.';
comment on table public.reward_x_promotion_receipts is
  'Immutable paid receipt for X Promotion only. It must not count as an additional referral.';
comment on function public.finalize_reward_x_promotion_payout_v1(
  bigint,text,text,text,bigint,bigint,text,bigint,integer
) is
  'Finalizes an already-submitted X Promotion transaction after independent on-chain verification. It remains callable after live is disabled so DB accounting can converge to chain truth.';
