begin;

create table public.vebetter_round_allocations (
  id bigint generated by default as identity primary key,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null
    check (app_id ~ '^0x[0-9a-f]{64}$'),
  vebetter_round_id bigint not null
    check (vebetter_round_id >= 1),
  x_allocation_pool_address text not null
    check (x_allocation_pool_address ~ '^0x[0-9a-f]{40}$'),
  claim_tx_id text not null
    check (claim_tx_id ~ '^0x[0-9a-f]{64}$'),
  claim_block_number bigint not null
    check (claim_block_number >= 0),
  claim_block_timestamp timestamptz not null,
  recipient_wallet text not null
    check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  caller_wallet text not null
    check (caller_wallet ~ '^0x[0-9a-f]{40}$'),
  total_amount_wei numeric(78,0) not null
    check (total_amount_wei >= 0),
  unallocated_amount_wei numeric(78,0) not null
    check (unallocated_amount_wei >= 0),
  team_allocation_amount_wei numeric(78,0) not null
    check (team_allocation_amount_wei >= 0),
  rewards_allocation_amount_wei numeric(78,0) not null
    check (rewards_allocation_amount_wei >= 0),
  observed_at timestamptz not null default now(),
  constraint vebetter_round_allocations_split_check
    check (
      total_amount_wei =
        team_allocation_amount_wei + rewards_allocation_amount_wei
    ),
  constraint vebetter_round_allocations_round_uidx
    unique (network, app_id, vebetter_round_id),
  constraint vebetter_round_allocations_claim_uidx
    unique (network, claim_tx_id, app_id)
);

alter table public.vebetter_round_allocations enable row level security;
revoke all on table public.vebetter_round_allocations
  from public, anon, authenticated;
revoke all on sequence public.vebetter_round_allocations_id_seq
  from public, anon, authenticated;
grant select, insert on table public.vebetter_round_allocations
  to service_role;
grant usage, select on sequence public.vebetter_round_allocations_id_seq
  to service_role;

create index vebetter_round_allocations_claim_block_idx
  on public.vebetter_round_allocations(network, app_id, claim_block_number desc);

create or replace function public.reject_vebetter_round_allocation_mutation()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception 'VeBetter allocation receipt % is immutable', old.id;
end;
$$;

revoke all on function public.reject_vebetter_round_allocation_mutation()
  from public, anon, authenticated;

drop trigger if exists vebetter_round_allocations_immutable_guard
  on public.vebetter_round_allocations;
create trigger vebetter_round_allocations_immutable_guard
before update or delete on public.vebetter_round_allocations
for each row execute function public.reject_vebetter_round_allocation_mutation();

alter table public.reward_rounds
  add column vebetter_round_id bigint,
  add column allocation_receipt_id bigint,
  add column allocation_rewards_wei numeric(78,0),
  add column opening_carryover_wei numeric(78,0),
  add constraint reward_rounds_vebetter_round_id_check
    check (vebetter_round_id is null or vebetter_round_id >= 1),
  add constraint reward_rounds_allocation_rewards_wei_check
    check (
      allocation_rewards_wei is null or
      (allocation_rewards_wei >= 0 and allocation_rewards_wei = trunc(allocation_rewards_wei))
    ),
  add constraint reward_rounds_opening_carryover_wei_check
    check (
      opening_carryover_wei is null or
      (opening_carryover_wei >= 0 and opening_carryover_wei = trunc(opening_carryover_wei))
    ),
  add constraint reward_rounds_allocation_binding_check
    check (
      (vebetter_round_id is null and allocation_receipt_id is null and allocation_rewards_wei is null and opening_carryover_wei is null)
      or
      (vebetter_round_id is not null and allocation_receipt_id is not null and allocation_rewards_wei is not null and opening_carryover_wei is not null)
    ),
  add constraint reward_rounds_allocation_receipt_fk
    foreign key (allocation_receipt_id)
    references public.vebetter_round_allocations(id);

create unique index reward_rounds_one_per_vebetter_round_idx
  on public.reward_rounds(network, app_id, vebetter_round_id)
  where vebetter_round_id is not null;

create unique index reward_rounds_allocation_receipt_uidx
  on public.reward_rounds(allocation_receipt_id)
  where allocation_receipt_id is not null;

create or replace function public.prepare_reward_round_with_allocation(
  p_network text,
  p_app_id text,
  p_pool_balance_wei numeric,
  p_vebetter_round_id bigint,
  p_allocation_receipt_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
  v_round_id bigint;
  v_reserved numeric(78,0);
  v_available numeric(78,0);
  v_opening_carryover numeric(78,0);
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  if p_vebetter_round_id is null or p_vebetter_round_id < 1 then
    raise exception 'VeBetter round id must be a positive integer';
  end if;

  select *
  into v_receipt
  from public.vebetter_round_allocations a
  where a.id = p_allocation_receipt_id
  for update;

  if not found then
    raise exception 'VeBetter allocation receipt not found';
  end if;

  if v_receipt.network <> p_network
     or v_receipt.app_id <> p_app_id
     or v_receipt.vebetter_round_id <> p_vebetter_round_id then
    raise exception 'VeBetter allocation receipt does not match the requested reward round';
  end if;

  if v_receipt.rewards_allocation_amount_wei <= 0 then
    return null;
  end if;

  if exists (
    select 1
    from public.vebetter_round_allocations newer
    where newer.network = p_network
      and newer.app_id = p_app_id
      and newer.vebetter_round_id > p_vebetter_round_id
  ) then
    raise exception 'VeBetter allocation receipt is not the latest observed funding round';
  end if;

  if exists (
    select 1
    from public.reward_rounds rr
    where rr.network = p_network
      and rr.app_id = p_app_id
      and rr.vebetter_round_id = p_vebetter_round_id
  ) then
    raise exception 'VeBetter allocation round already has a VeInvite reward round';
  end if;

  v_round_id := public.prepare_reward_round(
    p_network,
    p_app_id,
    p_pool_balance_wei
  );

  if v_round_id is null then
    return null;
  end if;

  select rr.reserved_before_round_wei
  into v_reserved
  from public.reward_rounds rr
  where rr.id = v_round_id
  for update;

  v_available := greatest(p_pool_balance_wei - v_reserved, 0);

  if v_receipt.rewards_allocation_amount_wei > v_available then
    raise exception 'Observed VeBetter allocation exceeds the currently available reward pool';
  end if;

  v_opening_carryover :=
    v_available - v_receipt.rewards_allocation_amount_wei;

  update public.reward_rounds
  set
    vebetter_round_id = p_vebetter_round_id,
    allocation_receipt_id = p_allocation_receipt_id,
    allocation_rewards_wei = v_receipt.rewards_allocation_amount_wei,
    opening_carryover_wei = v_opening_carryover
  where id = v_round_id;

  return v_round_id;
end;
$$;

revoke all on function public.prepare_reward_round_with_allocation(text, text, numeric, bigint, bigint)
  from public, anon, authenticated;
grant execute on function public.prepare_reward_round_with_allocation(text, text, numeric, bigint, bigint)
  to service_role;

commit;
