do $$
declare
  v_enabled boolean;
begin
  select reward_x_promotion_enabled
  into v_enabled
  from public.reward_runtime_config
  where id=1;

  if coalesce(v_enabled,false) then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_FOUNDATION_REQUIRES_LIVE_DISABLED';
  end if;
end $$;

create table if not exists public.reward_x_promotion_payout_manifests (
  id bigint generated by default as identity primary key,
  intent_id bigint not null unique
    references public.reward_x_promotion_payout_intents(id) on delete restrict,
  manifest_version text not null default 'veinvite-x-promotion-payout-manifest-v1'
    check (manifest_version='veinvite-x-promotion-payout-manifest-v1'),
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null
    check (app_id ~ '^0x[0-9a-f]{64}$'),
  x2earn_rewards_pool_address text not null
    check (x2earn_rewards_pool_address ~ '^0x[0-9a-f]{40}$'),
  operator_wallet text not null
    check (operator_wallet ~ '^0x[0-9a-f]{40}$'),
  manifest_hash text not null unique
    check (manifest_hash ~ '^0x[0-9a-f]{64}$'),
  invite_code text not null unique
    check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  recipient_wallet text not null
    check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  amount_wei numeric(78,0) not null
    check (amount_wei>0 and amount_wei=trunc(amount_wei)),
  public_proof_id uuid not null unique,
  proof_text text not null,
  proof_link text not null,
  description text not null,
  clause jsonb not null
    check (jsonb_typeof(clause)='object'),
  created_at timestamptz not null default now(),
  constraint reward_x_promotion_manifest_proof_text_check
    check (
      proof_text=
        'veinvite:x-promotion:v1:proof:' || public_proof_id::text
    ),
  constraint reward_x_promotion_manifest_proof_link_check
    check (
      proof_link=
        'https://veinvite.vercel.app/promotion-proofs/' ||
        public_proof_id::text
    ),
  constraint reward_x_promotion_manifest_description_check
    check (description='VeInvite verified X promotion bonus.'),
  constraint reward_x_promotion_manifest_clause_identity_check
    check (
      clause->>'intentId'=intent_id::text
      and clause->>'inviteCode'=invite_code
      and clause->>'recipientWallet'=recipient_wallet
      and clause->>'amountWei'=amount_wei::text
      and clause->>'publicProofId'=public_proof_id::text
      and clause->>'proof'=proof_text
      and clause->>'description'=description
      and clause->>'appId'=app_id
      and clause->>'to'=x2earn_rewards_pool_address
      and clause->>'value'='0x0'
      and coalesce(clause->>'data','') ~ '^0x[0-9a-f]+$'
      and jsonb_typeof(clause->'proofTypes')='array'
      and jsonb_array_length(clause->'proofTypes')=2
      and clause #>> '{proofTypes,0}'='text'
      and clause #>> '{proofTypes,1}'='link'
      and jsonb_typeof(clause->'proofValues')='array'
      and jsonb_array_length(clause->'proofValues')=2
      and clause #>> '{proofValues,0}'=proof_text
      and clause #>> '{proofValues,1}'=proof_link
      and clause->'impactCodes'='[]'::jsonb
      and clause->'impactValues'='[]'::jsonb
    )
);

create index if not exists reward_x_promotion_payout_manifests_network_created_idx
  on public.reward_x_promotion_payout_manifests(network,created_at,id);

create or replace function public.validate_reward_x_promotion_payout_manifest_v1()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_cfg public.reward_runtime_config%rowtype;
  v_intent public.reward_x_promotion_payout_intents%rowtype;
begin
  select * into v_cfg
  from public.reward_runtime_config
  where id=1;

  if not found
     or not v_cfg.reward_x_promotion_enabled
     or v_cfg.reward_x_promotion_live_started_at is null then
    raise exception 'REWARD_X_PROMOTION_LIVE_DISABLED';
  end if;

  select * into v_intent
  from public.reward_x_promotion_payout_intents i
  where i.id=new.intent_id;

  if not found
     or v_intent.network<>new.network
     or v_intent.invite_code<>new.invite_code
     or v_intent.recipient_wallet<>new.recipient_wallet
     or v_intent.amount_wei<>new.amount_wei
     or v_intent.public_proof_id<>new.public_proof_id then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_INTENT_MISMATCH';
  end if;

  if new.app_id<>
     '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e' then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_APP_MISMATCH';
  end if;

  if not public.reward_x_promotion_security_clear_v1(
    new.invite_code,
    new.network
  ) then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_SECURITY_NOT_CLEAR';
  end if;

  if exists (
    select 1
    from public.reward_x_promotion_payout_signed_transactions s
    where s.intent_id=new.intent_id
  ) then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_TOO_LATE';
  end if;

  return new;
end;
$function$;

create or replace function public.reject_reward_x_promotion_payout_manifest_mutation_v1()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_IMMUTABLE';
end;
$function$;

drop trigger if exists validate_reward_x_promotion_payout_manifest_v1_trigger
  on public.reward_x_promotion_payout_manifests;
create trigger validate_reward_x_promotion_payout_manifest_v1_trigger
before insert on public.reward_x_promotion_payout_manifests
for each row execute function public.validate_reward_x_promotion_payout_manifest_v1();

drop trigger if exists reject_reward_x_promotion_payout_manifest_mutation_v1_trigger
  on public.reward_x_promotion_payout_manifests;
create trigger reject_reward_x_promotion_payout_manifest_mutation_v1_trigger
before update or delete on public.reward_x_promotion_payout_manifests
for each row execute function public.reject_reward_x_promotion_payout_manifest_mutation_v1();

create or replace function public.create_reward_x_promotion_payout_manifest_v1(
  p_intent_id bigint,
  p_app_id text,
  p_x2earn_rewards_pool_address text,
  p_operator_wallet text,
  p_manifest_hash text,
  p_proof_text text,
  p_proof_link text,
  p_description text,
  p_clause jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_intent public.reward_x_promotion_payout_intents%rowtype;
  v_existing public.reward_x_promotion_payout_manifests%rowtype;
  v_manifest public.reward_x_promotion_payout_manifests%rowtype;
begin
  if p_intent_id is null or p_intent_id<1 then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_INTENT_INVALID';
  end if;

  p_app_id:=lower(btrim(coalesce(p_app_id,'')));
  p_x2earn_rewards_pool_address:=
    lower(btrim(coalesce(p_x2earn_rewards_pool_address,'')));
  p_operator_wallet:=lower(btrim(coalesce(p_operator_wallet,'')));
  p_manifest_hash:=lower(btrim(coalesce(p_manifest_hash,'')));
  p_proof_text:=btrim(coalesce(p_proof_text,''));
  p_proof_link:=btrim(coalesce(p_proof_link,''));
  p_description:=btrim(coalesce(p_description,''));

  select * into v_intent
  from public.reward_x_promotion_payout_intents i
  where i.id=p_intent_id;

  if not found then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_MISSING';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_intent.invite_code,0)
  );

  select * into v_existing
  from public.reward_x_promotion_payout_manifests m
  where m.intent_id=p_intent_id;

  if found then
    if v_existing.app_id=p_app_id
       and v_existing.x2earn_rewards_pool_address=p_x2earn_rewards_pool_address
       and v_existing.operator_wallet=p_operator_wallet
       and v_existing.manifest_hash=p_manifest_hash
       and v_existing.proof_text=p_proof_text
       and v_existing.proof_link=p_proof_link
       and v_existing.description=p_description
       and v_existing.clause=p_clause then
      return jsonb_build_object(
        'created',false,
        'manifestId',v_existing.id,
        'intentId',v_existing.intent_id,
        'manifestHash',v_existing.manifest_hash
      );
    end if;

    raise exception 'REWARD_X_PROMOTION_PAYOUT_MANIFEST_IMMUTABLE_MISMATCH';
  end if;

  insert into public.reward_x_promotion_payout_manifests(
    intent_id,
    network,
    app_id,
    x2earn_rewards_pool_address,
    operator_wallet,
    manifest_hash,
    invite_code,
    recipient_wallet,
    amount_wei,
    public_proof_id,
    proof_text,
    proof_link,
    description,
    clause
  ) values (
    v_intent.id,
    v_intent.network,
    p_app_id,
    p_x2earn_rewards_pool_address,
    p_operator_wallet,
    p_manifest_hash,
    v_intent.invite_code,
    v_intent.recipient_wallet,
    v_intent.amount_wei,
    v_intent.public_proof_id,
    p_proof_text,
    p_proof_link,
    p_description,
    p_clause
  )
  returning * into v_manifest;

  return jsonb_build_object(
    'created',true,
    'manifestId',v_manifest.id,
    'intentId',v_manifest.intent_id,
    'manifestHash',v_manifest.manifest_hash
  );
end;
$function$;

alter table public.reward_x_promotion_payout_manifests enable row level security;

revoke all on table public.reward_x_promotion_payout_manifests
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_payout_manifests_id_seq
  from public,anon,authenticated,service_role;

grant select on table public.reward_x_promotion_payout_manifests to service_role;

revoke all on function public.validate_reward_x_promotion_payout_manifest_v1()
  from public,anon,authenticated,service_role;
revoke all on function public.reject_reward_x_promotion_payout_manifest_mutation_v1()
  from public,anon,authenticated,service_role;
revoke all on function public.create_reward_x_promotion_payout_manifest_v1(
  bigint,text,text,text,text,text,text,text,jsonb
) from public,anon,authenticated;
grant execute on function public.create_reward_x_promotion_payout_manifest_v1(
  bigint,text,text,text,text,text,text,text,jsonb
) to service_role;

comment on table public.reward_x_promotion_payout_manifests is
  'Immutable one-clause structured-proof manifest for an X Promotion payout intent. It freezes the exact chain target, recipient, amount, proof metadata, and encoded clause before signing.';
