begin;

create table public.reward_forecast_snapshots (
  id bigint generated by default as identity primary key,
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null
    check (app_id ~ '^0x[0-9a-f]{64}$'),
  generated_at timestamptz not null,
  basis_allocation_round_id bigint not null
    check (basis_allocation_round_id >= 1),
  projected_funding_round_id bigint not null
    check (projected_funding_round_id >= basis_allocation_round_id),
  earliest_completion_round_id bigint not null
    check (earliest_completion_round_id >= projected_funding_round_id),
  allocation_sample_count integer not null
    check (allocation_sample_count >= 1),
  recipient_history_round_count integer not null
    check (recipient_history_round_count >= 0),
  projected_allocation_wei numeric(78,0) not null
    check (projected_allocation_wei >= 0 and projected_allocation_wei = trunc(projected_allocation_wei)),
  projected_allocation_low_wei numeric(78,0) not null
    check (projected_allocation_low_wei >= 0 and projected_allocation_low_wei = trunc(projected_allocation_low_wei)),
  projected_allocation_high_wei numeric(78,0) not null
    check (projected_allocation_high_wei >= 0 and projected_allocation_high_wei = trunc(projected_allocation_high_wei)),
  observed_pool_balance_wei numeric(78,0) not null
    check (observed_pool_balance_wei >= 0 and observed_pool_balance_wei = trunc(observed_pool_balance_wei)),
  reserved_existing_wei numeric(78,0) not null
    check (reserved_existing_wei >= 0 and reserved_existing_wei = trunc(reserved_existing_wei)),
  expected_recipients integer not null
    check (expected_recipients >= 1),
  recipient_low integer not null
    check (recipient_low >= 1),
  recipient_high integer not null
    check (recipient_high >= 1),
  estimated_reward_wei numeric(78,0) not null
    check (estimated_reward_wei >= 0 and estimated_reward_wei = trunc(estimated_reward_wei)),
  estimated_reward_low_wei numeric(78,0) not null
    check (estimated_reward_low_wei >= 0 and estimated_reward_low_wei = trunc(estimated_reward_low_wei)),
  estimated_reward_high_wei numeric(78,0) not null
    check (estimated_reward_high_wei >= 0 and estimated_reward_high_wei = trunc(estimated_reward_high_wei)),
  model_version text not null
    check (length(btrim(model_version)) between 1 and 80),
  input_snapshot jsonb not null
    check (jsonb_typeof(input_snapshot) = 'object'),
  created_at timestamptz not null default now(),
  constraint reward_forecast_allocation_range_check
    check (
      projected_allocation_low_wei <= projected_allocation_wei
      and projected_allocation_wei <= projected_allocation_high_wei
    ),
  constraint reward_forecast_recipient_range_check
    check (
      recipient_low <= expected_recipients
      and expected_recipients <= recipient_high
    ),
  constraint reward_forecast_reward_range_check
    check (
      estimated_reward_low_wei <= estimated_reward_wei
      and estimated_reward_wei <= estimated_reward_high_wei
    )
);

comment on table public.reward_forecast_snapshots is
  'Append-only public-display forecasts. Forecasts are read-only planning data and never authorize or determine reward payouts.';

alter table public.reward_forecast_snapshots enable row level security;
revoke all on table public.reward_forecast_snapshots
  from public, anon, authenticated;
revoke all on sequence public.reward_forecast_snapshots_id_seq
  from public, anon, authenticated;
grant select, insert on table public.reward_forecast_snapshots
  to service_role;
grant usage, select on sequence public.reward_forecast_snapshots_id_seq
  to service_role;

create index reward_forecast_snapshots_latest_idx
  on public.reward_forecast_snapshots(network, app_id, generated_at desc, id desc);

create or replace function public.reject_reward_forecast_snapshot_mutation()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception 'Reward forecast snapshot % is immutable', old.id;
end;
$$;

revoke all on function public.reject_reward_forecast_snapshot_mutation()
  from public, anon, authenticated;
grant execute on function public.reject_reward_forecast_snapshot_mutation()
  to service_role;

create trigger reward_forecast_snapshots_immutable_guard
before update or delete on public.reward_forecast_snapshots
for each row execute function public.reject_reward_forecast_snapshot_mutation();

commit;
