do $$
begin
  if exists (
    select 1
    from public.reward_x_promotion_splits s
    where s.mode='LIVE'
  ) then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_FOUNDATION_REQUIRES_NO_LIVE_SPLITS';
  end if;
end $$;

create table if not exists public.reward_x_promotion_obligations (
  id bigint generated by default as identity primary key,
  split_id bigint not null references public.reward_x_promotion_splits(id),
  invite_code text not null check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  promotion_amount_wei numeric(78,0) not null
    check (promotion_amount_wei > 0 and promotion_amount_wei=trunc(promotion_amount_wei)),
  source_reward_cohort_round_id bigint not null
    check (source_reward_cohort_round_id >= 1),
  source_allocation_receipt_id bigint not null
    references public.vebetter_round_allocations(id),
  policy_version text not null
    check (char_length(btrim(policy_version)) between 1 and 80),
  financial_state text not null default 'RESERVED'
    check (financial_state in ('RESERVED','HELD','RELEASED','PAID')),
  held_at timestamptz,
  released_at timestamptz,
  paid_at timestamptz,
  release_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reward_x_promotion_obligations_split_uidx unique(split_id),
  constraint reward_x_promotion_obligations_invite_uidx unique(invite_code),
  constraint reward_x_promotion_obligations_state_shape_check check (
    (
      financial_state='RESERVED'
      and held_at is null
      and released_at is null
      and paid_at is null
      and release_reason is null
    )
    or
    (
      financial_state='HELD'
      and held_at is not null
      and released_at is null
      and paid_at is null
      and release_reason is null
    )
    or
    (
      financial_state='RELEASED'
      and released_at is not null
      and paid_at is null
      and release_reason is not null
      and char_length(btrim(release_reason)) between 1 and 120
    )
    or
    (
      financial_state='PAID'
      and held_at is not null
      and released_at is null
      and paid_at is not null
      and release_reason is null
    )
  )
);

create index if not exists reward_x_promotion_obligations_network_state_idx
  on public.reward_x_promotion_obligations(network,financial_state);
create index if not exists reward_x_promotion_obligations_source_idx
  on public.reward_x_promotion_obligations(
    network,
    source_reward_cohort_round_id,
    source_allocation_receipt_id,
    financial_state
  );

create table if not exists public.reward_x_promotion_obligation_events (
  id bigint generated by default as identity primary key,
  obligation_id bigint not null
    references public.reward_x_promotion_obligations(id),
  invite_code text not null check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  previous_state text
    check (previous_state is null or previous_state in ('RESERVED','HELD','RELEASED','PAID')),
  new_state text not null
    check (new_state in ('RESERVED','HELD','RELEASED','PAID')),
  reason text not null check (char_length(btrim(reason)) between 1 and 120),
  database_actor text not null,
  occurred_at timestamptz not null default now()
);

create index if not exists reward_x_promotion_obligation_events_obligation_idx
  on public.reward_x_promotion_obligation_events(obligation_id,id);
create index if not exists reward_x_promotion_obligation_events_invite_idx
  on public.reward_x_promotion_obligation_events(invite_code,id);

alter table public.reward_x_promotion_obligations enable row level security;
alter table public.reward_x_promotion_obligation_events enable row level security;

revoke all on table public.reward_x_promotion_obligations
  from public,anon,authenticated,service_role;
revoke all on table public.reward_x_promotion_obligation_events
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_obligations_id_seq
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_obligation_events_id_seq
  from public,anon,authenticated,service_role;

grant select on table public.reward_x_promotion_obligations to service_role;
grant select on table public.reward_x_promotion_obligation_events to service_role;

create or replace function public.validate_reward_x_promotion_obligation_insert()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_split public.reward_x_promotion_splits%rowtype;
begin
  if new.financial_state<>'RESERVED'
     or new.held_at is not null
     or new.released_at is not null
     or new.paid_at is not null
     or new.release_reason is not null then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_INITIAL_STATE_INVALID';
  end if;

  select * into v_split
  from public.reward_x_promotion_splits s
  where s.id=new.split_id;

  if not found
     or v_split.mode<>'LIVE'
     or v_split.promotion_amount_wei<=0
     or v_split.invite_code<>new.invite_code
     or v_split.network<>new.network
     or v_split.recipient_wallet<>new.recipient_wallet
     or v_split.promotion_amount_wei<>new.promotion_amount_wei
     or v_split.source_reward_cohort_round_id<>new.source_reward_cohort_round_id
     or v_split.source_allocation_receipt_id<>new.source_allocation_receipt_id
     or btrim(v_split.policy_version)<>btrim(new.policy_version) then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_SPLIT_MISMATCH';
  end if;

  return new;
end;
$function$;

create or replace function public.guard_reward_x_promotion_obligation_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  if tg_op='DELETE' then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_DELETE_FORBIDDEN';
  end if;

  if old.split_id is distinct from new.split_id
     or old.invite_code is distinct from new.invite_code
     or old.network is distinct from new.network
     or old.recipient_wallet is distinct from new.recipient_wallet
     or old.promotion_amount_wei is distinct from new.promotion_amount_wei
     or old.source_reward_cohort_round_id is distinct from new.source_reward_cohort_round_id
     or old.source_allocation_receipt_id is distinct from new.source_allocation_receipt_id
     or old.policy_version is distinct from new.policy_version
     or old.created_at is distinct from new.created_at then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_IDENTITY_IMMUTABLE';
  end if;

  if old.financial_state=new.financial_state then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_STATE_CHANGE_REQUIRED';
  end if;

  if not (
    (old.financial_state='RESERVED' and new.financial_state in ('HELD','RELEASED'))
    or
    (old.financial_state='HELD' and new.financial_state='RELEASED')
  ) then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_TRANSITION_INVALID';
  end if;

  return new;
end;
$function$;

create or replace function public.create_reward_x_promotion_obligation_from_split()
returns trigger
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
begin
  if new.mode='LIVE' and new.promotion_amount_wei>0 then
    insert into public.reward_x_promotion_obligations(
      split_id,
      invite_code,
      network,
      recipient_wallet,
      promotion_amount_wei,
      source_reward_cohort_round_id,
      source_allocation_receipt_id,
      policy_version,
      financial_state
    ) values (
      new.id,
      new.invite_code,
      new.network,
      new.recipient_wallet,
      new.promotion_amount_wei,
      new.source_reward_cohort_round_id,
      new.source_allocation_receipt_id,
      new.policy_version,
      'RESERVED'
    );
  end if;

  return new;
end;
$function$;

create or replace function public.log_reward_x_promotion_obligation_event()
returns trigger
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
begin
  if tg_op='INSERT' then
    insert into public.reward_x_promotion_obligation_events(
      obligation_id,invite_code,network,previous_state,new_state,reason,database_actor
    ) values (
      new.id,new.invite_code,new.network,null,new.financial_state,'CREATED',current_user
    );
  elsif old.financial_state is distinct from new.financial_state then
    insert into public.reward_x_promotion_obligation_events(
      obligation_id,invite_code,network,previous_state,new_state,reason,database_actor
    ) values (
      new.id,
      new.invite_code,
      new.network,
      old.financial_state,
      new.financial_state,
      case
        when new.financial_state='HELD' then 'BASE_PAID_HOLD'
        when new.financial_state='RELEASED' then new.release_reason
        else 'STATE_TRANSITION'
      end,
      current_user
    );
  end if;

  return new;
end;
$function$;

create or replace function public.reject_reward_x_promotion_obligation_event_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'REWARD_X_PROMOTION_OBLIGATION_EVENT_IMMUTABLE';
end;
$function$;

drop trigger if exists validate_reward_x_promotion_obligation_insert_trigger
  on public.reward_x_promotion_obligations;
create trigger validate_reward_x_promotion_obligation_insert_trigger
before insert on public.reward_x_promotion_obligations
for each row execute function public.validate_reward_x_promotion_obligation_insert();

drop trigger if exists guard_reward_x_promotion_obligation_mutation_trigger
  on public.reward_x_promotion_obligations;
create trigger guard_reward_x_promotion_obligation_mutation_trigger
before update or delete on public.reward_x_promotion_obligations
for each row execute function public.guard_reward_x_promotion_obligation_mutation();

drop trigger if exists create_reward_x_promotion_obligation_from_split_trigger
  on public.reward_x_promotion_splits;
create trigger create_reward_x_promotion_obligation_from_split_trigger
after insert on public.reward_x_promotion_splits
for each row execute function public.create_reward_x_promotion_obligation_from_split();

drop trigger if exists log_reward_x_promotion_obligation_event_trigger
  on public.reward_x_promotion_obligations;
create trigger log_reward_x_promotion_obligation_event_trigger
after insert or update of financial_state on public.reward_x_promotion_obligations
for each row execute function public.log_reward_x_promotion_obligation_event();

drop trigger if exists reward_x_promotion_obligation_events_append_only
  on public.reward_x_promotion_obligation_events;
create trigger reward_x_promotion_obligation_events_append_only
before update or delete on public.reward_x_promotion_obligation_events
for each row execute function public.reject_reward_x_promotion_obligation_event_mutation();

create or replace function public.activate_reward_x_promotion_obligation_v1(
  p_invite_code text
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(p_invite_code));
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_split public.reward_x_promotion_splits%rowtype;
  v_payout public.reward_payouts%rowtype;
  v_invitation public.invitations%rowtype;
  v_now timestamptz := clock_timestamp();
begin
  if v_code is null or v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_code,0)
  );

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.invite_code=v_code
  for update;

  if not found then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_MISSING';
  end if;

  if v_obligation.financial_state='HELD' then
    return jsonb_build_object(
      'activated',true,
      'reason','ALREADY_HELD',
      'inviteCode',v_code,
      'amountWei',v_obligation.promotion_amount_wei::text,
      'heldAt',v_obligation.held_at
    );
  end if;

  if v_obligation.financial_state<>'RESERVED' then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_NOT_RESERVABLE';
  end if;

  select * into v_split
  from public.reward_x_promotion_splits s
  where s.id=v_obligation.split_id
    and s.mode='LIVE';

  if not found then
    raise exception 'REWARD_X_PROMOTION_LIVE_SPLIT_MISSING';
  end if;

  select * into v_payout
  from public.reward_payouts p
  where p.invite_code=v_code
    and p.status='PAID';

  if not found
     or v_payout.amount_wei<>v_split.base_amount_wei
     or v_payout.paid_at is null then
    raise exception 'REWARD_X_PROMOTION_BASE_PAYOUT_MISMATCH';
  end if;

  if not exists (
    select 1
    from public.reward_receipts r
    where r.payout_id=v_payout.id
      and r.invite_code=v_code
      and r.network=v_obligation.network
      and r.recipient_wallet=v_obligation.recipient_wallet
      and r.amount_wei=v_split.base_amount_wei
      and r.paid_at is not null
  ) then
    raise exception 'REWARD_X_PROMOTION_BASE_RECEIPT_MISSING';
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=v_code;

  if not found
     or public.is_sybil_v2_referral_invalidated(v_code,v_obligation.network)
     or exists (
       select 1
       from public.sybil_v2_wallet_restrictions r
       where r.network=v_obligation.network
         and r.status='ACTIVE'
         and r.wallet_address in (
           lower(v_obligation.recipient_wallet),
           lower(v_invitation.invitee_wallet)
         )
     ) then
    raise exception 'REWARD_X_PROMOTION_SECURITY_NOT_CLEAR';
  end if;

  update public.reward_x_promotion_obligations o
  set financial_state='HELD',
      held_at=v_now,
      updated_at=v_now
  where o.id=v_obligation.id
  returning * into v_obligation;

  return jsonb_build_object(
    'activated',true,
    'reason','HELD',
    'inviteCode',v_code,
    'amountWei',v_obligation.promotion_amount_wei::text,
    'heldAt',v_obligation.held_at
  );
end;
$function$;

create or replace function public.release_reward_x_promotion_obligation_v1(
  p_invite_code text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(p_invite_code));
  v_reason text := btrim(coalesce(p_reason,''));
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_now timestamptz := clock_timestamp();
begin
  if v_code is null or v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;

  if char_length(v_reason) not between 1 and 120 then
    raise exception 'REWARD_X_PROMOTION_RELEASE_REASON_INVALID';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_code,0)
  );

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.invite_code=v_code
  for update;

  if not found then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_MISSING';
  end if;

  if v_obligation.financial_state='RELEASED' then
    return jsonb_build_object(
      'released',true,
      'reason','ALREADY_RELEASED',
      'inviteCode',v_code,
      'amountWei',v_obligation.promotion_amount_wei::text,
      'releasedAt',v_obligation.released_at
    );
  end if;

  if v_obligation.financial_state not in ('RESERVED','HELD') then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_NOT_RELEASABLE';
  end if;

  update public.reward_x_promotion_obligations o
  set financial_state='RELEASED',
      released_at=v_now,
      release_reason=v_reason,
      updated_at=v_now
  where o.id=v_obligation.id
  returning * into v_obligation;

  return jsonb_build_object(
    'released',true,
    'reason',v_reason,
    'inviteCode',v_code,
    'amountWei',v_obligation.promotion_amount_wei::text,
    'releasedAt',v_obligation.released_at
  );
end;
$function$;

create or replace function public.read_reward_x_promotion_post_base_liability_wei(
  p_network text,
  p_app_id text
)
returns numeric
language plpgsql
stable
set search_path to 'pg_catalog','public'
as $function$
declare
  v_veinvite_app_id constant text :=
    '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e';
  v_network text := lower(btrim(p_network));
  v_app_id text := lower(btrim(p_app_id));
  v_amount numeric(78,0) := 0;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;
  if v_app_id<>v_veinvite_app_id then
    raise exception 'REWARD_X_PROMOTION_APP_MISMATCH';
  end if;

  select coalesce(sum(o.promotion_amount_wei),0)
  into v_amount
  from public.reward_x_promotion_obligations o
  where o.network=v_network
    and o.financial_state='HELD';

  return v_amount;
end;
$function$;

create or replace function public.read_reward_x_promotion_cohort_released_wei(
  p_network text,
  p_app_id text,
  p_reward_cohort_round_id bigint,
  p_allocation_receipt_id bigint
)
returns numeric
language plpgsql
stable
set search_path to 'pg_catalog','public'
as $function$
declare
  v_veinvite_app_id constant text :=
    '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e';
  v_network text := lower(btrim(p_network));
  v_app_id text := lower(btrim(p_app_id));
  v_receipt public.vebetter_round_allocations%rowtype;
  v_amount numeric(78,0) := 0;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;
  if v_app_id<>v_veinvite_app_id then
    raise exception 'REWARD_X_PROMOTION_APP_MISMATCH';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id=p_allocation_receipt_id
    and a.network=v_network
    and a.app_id=v_app_id;

  if not found
     or v_receipt.vebetter_round_id+1<>p_reward_cohort_round_id then
    raise exception 'REWARD_X_PROMOTION_SOURCE_MISMATCH';
  end if;

  select coalesce(sum(o.promotion_amount_wei),0)
  into v_amount
  from public.reward_x_promotion_obligations o
  where o.network=v_network
    and o.source_reward_cohort_round_id=p_reward_cohort_round_id
    and o.source_allocation_receipt_id=p_allocation_receipt_id
    and o.financial_state='RELEASED';

  return v_amount;
end;
$function$;

revoke all on function public.create_reward_x_promotion_obligation_from_split()
  from public,anon,authenticated,service_role;
revoke all on function public.log_reward_x_promotion_obligation_event()
  from public,anon,authenticated,service_role;
revoke all on function public.validate_reward_x_promotion_obligation_insert()
  from public,anon,authenticated,service_role;
revoke all on function public.guard_reward_x_promotion_obligation_mutation()
  from public,anon,authenticated,service_role;
revoke all on function public.reject_reward_x_promotion_obligation_event_mutation()
  from public,anon,authenticated,service_role;

revoke all on function public.activate_reward_x_promotion_obligation_v1(text)
  from public,anon,authenticated,service_role;
grant execute on function public.activate_reward_x_promotion_obligation_v1(text)
  to service_role;

revoke all on function public.release_reward_x_promotion_obligation_v1(text,text)
  from public,anon,authenticated,service_role;
grant execute on function public.release_reward_x_promotion_obligation_v1(text,text)
  to service_role;

revoke all on function public.read_reward_x_promotion_post_base_liability_wei(text,text)
  from public,anon,authenticated;
grant execute on function public.read_reward_x_promotion_post_base_liability_wei(text,text)
  to service_role;

revoke all on function public.read_reward_x_promotion_cohort_released_wei(text,text,bigint,bigint)
  from public,anon,authenticated;
grant execute on function public.read_reward_x_promotion_cohort_released_wei(text,text,bigint,bigint)
  to service_role;

comment on table public.reward_x_promotion_obligations is
  'Financial state for the optional X promotion portion of a LIVE reward split. Foundation only: core reward liability and cohort commitment readers do not consume this table yet.';
comment on function public.read_reward_x_promotion_post_base_liability_wei(text,text) is
  'Reads HELD X promotion value that will become separately outstanding only after base payout finalization. Not yet wired into core liability.';
comment on function public.read_reward_x_promotion_cohort_released_wei(text,text,bigint,bigint) is
  'Reads released X promotion value for a source cohort. Not yet wired into core cohort commitment.';
