alter table public.reward_runtime_config
  add column if not exists reward_boost_reserve_enabled boolean not null default false,
  add column if not exists reward_boost_reserve_shadow_enabled boolean not null default true,
  add column if not exists reward_boost_reserve_long_incomplete_rounds integer not null default 2,
  add column if not exists reward_boost_reserve_promotion_reserve_bps integer not null default 1500;

alter table public.reward_runtime_config
  drop constraint if exists reward_runtime_config_boost_long_incomplete_check,
  add constraint reward_runtime_config_boost_long_incomplete_check
    check (reward_boost_reserve_long_incomplete_rounds between 1 and 52),
  drop constraint if exists reward_runtime_config_boost_promotion_reserve_bps_check,
  add constraint reward_runtime_config_boost_promotion_reserve_bps_check
    check (reward_boost_reserve_promotion_reserve_bps between 0 and 5000);

update public.reward_runtime_config
set reward_boost_reserve_enabled=false,
    reward_boost_reserve_shadow_enabled=true,
    reward_boost_reserve_long_incomplete_rounds=2,
    reward_boost_reserve_promotion_reserve_bps=1500
where id=1;

create table if not exists public.reward_boost_reserve_ledger (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null check (app_id ~ '^0x[0-9a-f]{64}$'),
  entry_kind text not null check (entry_kind in ('SOURCE_SWEEP','BOOST_RELEASE','LATE_COMPLETION_RELEASE')),
  source_reward_cohort_round_id bigint,
  source_allocation_receipt_id bigint references public.vebetter_round_allocations(id),
  destination_reward_cohort_round_id bigint,
  destination_allocation_receipt_id bigint references public.vebetter_round_allocations(id),
  amount_wei numeric(78,0) not null check (amount_wei > 0 and amount_wei=trunc(amount_wei)),
  policy_version text not null check (char_length(btrim(policy_version)) between 1 and 80),
  reference_key text not null check (char_length(btrim(reference_key)) between 1 and 160),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details)='object'),
  created_at timestamptz not null default now(),
  constraint reward_boost_reserve_ledger_reference_uidx unique(network,app_id,reference_key),
  constraint reward_boost_reserve_ledger_shape_check check (
    (
      entry_kind='SOURCE_SWEEP'
      and source_reward_cohort_round_id is not null
      and source_reward_cohort_round_id>=1
      and source_allocation_receipt_id is not null
      and destination_reward_cohort_round_id is null
      and destination_allocation_receipt_id is null
    )
    or
    (
      entry_kind in ('BOOST_RELEASE','LATE_COMPLETION_RELEASE')
      and source_reward_cohort_round_id is null
      and source_allocation_receipt_id is null
      and destination_reward_cohort_round_id is not null
      and destination_reward_cohort_round_id>=1
      and destination_allocation_receipt_id is not null
    )
  )
);

create index if not exists reward_boost_reserve_ledger_source_idx
  on public.reward_boost_reserve_ledger(network,app_id,source_reward_cohort_round_id,source_allocation_receipt_id)
  where source_allocation_receipt_id is not null;
create index if not exists reward_boost_reserve_ledger_destination_idx
  on public.reward_boost_reserve_ledger(network,app_id,destination_reward_cohort_round_id,destination_allocation_receipt_id)
  where destination_allocation_receipt_id is not null;
create index if not exists reward_boost_reserve_ledger_created_idx
  on public.reward_boost_reserve_ledger(created_at desc,id desc);
create index if not exists reward_boost_reserve_ledger_source_receipt_idx
  on public.reward_boost_reserve_ledger(source_allocation_receipt_id)
  where source_allocation_receipt_id is not null;
create index if not exists reward_boost_reserve_ledger_destination_receipt_idx
  on public.reward_boost_reserve_ledger(destination_allocation_receipt_id)
  where destination_allocation_receipt_id is not null;

create table if not exists public.reward_boost_reserve_source_protections (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null check (app_id ~ '^0x[0-9a-f]{64}$'),
  source_reward_cohort_round_id bigint not null check (source_reward_cohort_round_id>=1),
  source_allocation_receipt_id bigint not null references public.vebetter_round_allocations(id),
  baseline_effective_budget_wei numeric(78,0) not null check (baseline_effective_budget_wei>=0),
  baseline_committed_wei numeric(78,0) not null check (baseline_committed_wei>=0),
  promotion_original_wei numeric(78,0) not null check (promotion_original_wei>=0),
  promotion_reserve_wei numeric(78,0) not null check (promotion_reserve_wei>=0),
  late_reward_wei numeric(78,0) not null check (late_reward_wei>=0),
  queued_eligible_count integer not null check (queued_eligible_count>=0),
  long_incomplete_count integer not null check (long_incomplete_count>=0),
  late_weighted_bps numeric(78,0) not null check (late_weighted_bps>=0),
  late_weighted_liability_wei numeric(78,0) not null check (late_weighted_liability_wei>=0),
  max_sweepable_wei numeric(78,0) not null check (max_sweepable_wei>=0),
  source_revision text not null check (char_length(btrim(source_revision))>=1),
  policy_version text not null check (char_length(btrim(policy_version)) between 1 and 80),
  created_at timestamptz not null default now(),
  unique(network,app_id,source_reward_cohort_round_id,source_allocation_receipt_id)
);
create index if not exists reward_boost_source_protection_receipt_idx
  on public.reward_boost_reserve_source_protections(source_allocation_receipt_id);

create table if not exists public.reward_boost_reserve_destination_plans (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  app_id text not null check (app_id ~ '^0x[0-9a-f]{64}$'),
  destination_reward_cohort_round_id bigint not null check (destination_reward_cohort_round_id>=1),
  destination_allocation_receipt_id bigint not null references public.vebetter_round_allocations(id),
  baseline_fresh_designated_wei numeric(78,0) not null check (baseline_fresh_designated_wei>=0),
  baseline_committed_wei numeric(78,0) not null check (baseline_committed_wei>=0),
  baseline_fresh_pricing_capacity_wei numeric(78,0) not null check (baseline_fresh_pricing_capacity_wei>=0),
  bank_balance_before_wei numeric(78,0) not null check (bank_balance_before_wei>=0),
  bank_stress_reserve_wei numeric(78,0) not null check (bank_stress_reserve_wei>=0),
  recent_cohort_protected_wei numeric(78,0) not null check (recent_cohort_protected_wei>=0),
  source_retained_protection_wei numeric(78,0) not null check (source_retained_protection_wei>=0),
  observed_pool_balance_wei numeric(78,0) not null check (observed_pool_balance_wei>=0),
  reserved_existing_wei numeric(78,0) not null check (reserved_existing_wei>=0),
  physical_extra_headroom_wei numeric(78,0) not null check (physical_extra_headroom_wei>=0),
  max_boost_release_wei numeric(78,0) not null check (max_boost_release_wei>=0),
  policy_version text not null check (char_length(btrim(policy_version)) between 1 and 80),
  created_at timestamptz not null default now(),
  unique(network,app_id,destination_reward_cohort_round_id,destination_allocation_receipt_id)
);
create index if not exists reward_boost_destination_plan_receipt_idx
  on public.reward_boost_reserve_destination_plans(destination_allocation_receipt_id);

alter table public.reward_boost_reserve_ledger enable row level security;
alter table public.reward_boost_reserve_source_protections enable row level security;
alter table public.reward_boost_reserve_destination_plans enable row level security;

revoke all on table public.reward_boost_reserve_ledger from public,anon,authenticated,service_role;
revoke all on table public.reward_boost_reserve_source_protections from public,anon,authenticated,service_role;
revoke all on table public.reward_boost_reserve_destination_plans from public,anon,authenticated,service_role;
revoke all on sequence public.reward_boost_reserve_ledger_id_seq from public,anon,authenticated,service_role;
revoke all on sequence public.reward_boost_reserve_source_protections_id_seq from public,anon,authenticated,service_role;
revoke all on sequence public.reward_boost_reserve_destination_plans_id_seq from public,anon,authenticated,service_role;

grant select on table public.reward_boost_reserve_ledger to service_role;
grant select on table public.reward_boost_reserve_source_protections to service_role;
grant select on table public.reward_boost_reserve_destination_plans to service_role;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_balance_wei(p_network text, p_app_id text)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_balance numeric(78,0);
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  if p_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'unsupported network';
  end if;
  if p_app_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'invalid app id';
  end if;

  select coalesce(sum(
    case
      when l.entry_kind = 'SOURCE_SWEEP' then l.amount_wei
      else -l.amount_wei
    end
  ),0)
  into v_balance
  from public.reward_boost_reserve_ledger l
  where l.network = p_network
    and l.app_id = p_app_id;

  if v_balance < 0 then
    raise exception 'REWARD_BOOST_RESERVE_LEDGER_NEGATIVE';
  end if;

  return v_balance;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_cohort_net_flow_wei(p_network text, p_app_id text, p_reward_cohort_round_id bigint, p_allocation_receipt_id bigint)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
  v_inflow numeric(78,0) := 0;
  v_outflow numeric(78,0) := 0;
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id = p_allocation_receipt_id
    and a.network = p_network
    and a.app_id = p_app_id;

  if not found
     or v_receipt.vebetter_round_id + 1 <> p_reward_cohort_round_id then
    raise exception 'allocation receipt does not fund the requested reward cohort';
  end if;

  select coalesce(sum(l.amount_wei),0)
  into v_inflow
  from public.reward_boost_reserve_ledger l
  where l.network = p_network
    and l.app_id = p_app_id
    and l.destination_reward_cohort_round_id = p_reward_cohort_round_id
    and l.destination_allocation_receipt_id = p_allocation_receipt_id
    and l.entry_kind in ('BOOST_RELEASE','LATE_COMPLETION_RELEASE');

  select coalesce(sum(l.amount_wei),0)
  into v_outflow
  from public.reward_boost_reserve_ledger l
  where l.network = p_network
    and l.app_id = p_app_id
    and l.source_reward_cohort_round_id = p_reward_cohort_round_id
    and l.source_allocation_receipt_id = p_allocation_receipt_id
    and l.entry_kind = 'SOURCE_SWEEP';

  return v_inflow - v_outflow;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_cohort_effective_budget_wei(p_network text, p_app_id text, p_reward_cohort_round_id bigint, p_allocation_receipt_id bigint)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
  v_adjustment numeric(78,0) := 0;
  v_net_flow numeric(78,0) := 0;
  v_budget numeric(78,0) := 0;
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id = p_allocation_receipt_id
    and a.network = p_network
    and a.app_id = p_app_id;

  if not found
     or v_receipt.vebetter_round_id + 1 <> p_reward_cohort_round_id then
    raise exception 'allocation receipt does not fund the requested reward cohort';
  end if;

  select coalesce(sum(a.amount_wei),0)
  into v_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network = p_network
    and a.app_id = p_app_id
    and a.reward_cohort_round_id = p_reward_cohort_round_id
    and a.allocation_receipt_id = p_allocation_receipt_id;

  v_net_flow := public.read_reward_boost_reserve_cohort_net_flow_wei(
    p_network,
    p_app_id,
    p_reward_cohort_round_id,
    p_allocation_receipt_id
  );

  v_budget :=
    v_receipt.rewards_allocation_amount_wei +
    v_adjustment +
    v_net_flow;

  if v_budget < 0 then
    raise exception 'REWARD_COHORT_EFFECTIVE_BUDGET_NEGATIVE';
  end if;

  return v_budget;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reject_reward_boost_reserve_ledger_mutation()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public'
AS $function$
begin
  raise exception 'Reward boost reserve ledger % is immutable', old.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reject_reward_boost_source_protection_mutation()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public'
AS $function$
begin
  raise exception 'Reward boost source protection % is immutable', old.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reject_reward_boost_destination_plan_mutation()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public'
AS $function$
begin
  raise exception 'Reward boost destination plan % is immutable', old.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_source_revision(p_network text, p_app_id text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_current_cohort bigint;
  v_long_rounds integer;
  v_promo_bps integer;
  v_payload jsonb;
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  select
    reward_boost_reserve_long_incomplete_rounds,
    reward_boost_reserve_promotion_reserve_bps
  into
    v_long_rounds,
    v_promo_bps
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  select max(a.vebetter_round_id+1)
  into v_current_cohort
  from public.vebetter_round_allocations a
  where a.network=p_network
    and a.app_id=p_app_id;

  if v_current_cohort is null then
    return md5(
      jsonb_build_object(
        'longRounds',v_long_rounds,
        'promotionReserveBps',v_promo_bps,
        'sources','[]'::jsonb
      )::text
    );
  end if;

  select jsonb_build_object(
    'longRounds',v_long_rounds,
    'promotionReserveBps',v_promo_bps,
    'sources',coalesce(
      jsonb_agg(
        jsonb_build_object(
          'receiptId',a.id,
          'cohortRound',a.vebetter_round_id+1,
          'officialWei',a.rewards_allocation_amount_wei::text,
          'promoWei',coalesce(f.promo_wei,0)::text,
          'committedWei',
            public.read_reward_cohort_committed_wei(
              p_network,p_app_id,a.vebetter_round_id+1,a.id
            )::text,
          'clearedQueued',
            public.read_sybil_v2_cleared_unreserved_count(
              p_network,a.vebetter_round_id+1,a.id
            ),
          'invitationState',
            coalesce(i.invitation_state,'[]'::jsonb)
        )
        order by a.vebetter_round_id,a.id
      ),
      '[]'::jsonb
    )
  )
  into v_payload
  from public.vebetter_round_allocations a
  left join lateral (
    select coalesce(sum(x.amount_wei),0) as promo_wei
    from public.reward_cohort_funding_adjustments x
    where x.network=p_network
      and x.app_id=p_app_id
      and x.reward_cohort_round_id=a.vebetter_round_id+1
      and x.allocation_receipt_id=a.id
      and x.adjustment_type='PROMOTION'
  ) f on true
  left join lateral (
    select jsonb_agg(
      jsonb_build_array(
        inv.invite_code,
        inv.status,
        inv.reward_status,
        inv.sybil_status,
        coalesce(inv.apps_completed,0),
        coalesce(inv.vot3_converted,false),
        coalesce(inv.vote_completed,false),
        lower(coalesce(inv.invitee_wallet,'')),
        exists (
          select 1
          from public.sybil_v2_wallet_restrictions r
          where r.network=p_network
            and inv.invitee_wallet is not null
            and lower(r.wallet_address)=lower(inv.invitee_wallet)
            and r.status='ACTIVE'
        ),
        inv.reward_eligible_at,
        inv.updated_at
      )
      order by inv.invite_code
    ) as invitation_state
    from public.invitations inv
    where inv.activation_network=p_network
      and inv.reward_cohort_round_id=a.vebetter_round_id+1
      and inv.reward_funding_allocation_receipt_id=a.id
      and inv.status in (
        'ACTIVATING','UNDER_REVIEW','COMPLETED','CANCELLED'
      )
  ) i on true
  where a.network=p_network
    and a.app_id=p_app_id
    and a.vebetter_round_id+1 <=
      v_current_cohort-v_long_rounds;

  return md5(v_payload::text);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_source_candidate(p_network text, p_app_id text, p_source_reward_cohort_round_id bigint, p_source_allocation_receipt_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_cfg public.reward_runtime_config%rowtype;
  v_receipt public.vebetter_round_allocations%rowtype;
  v_current_cohort bigint;
  v_planning jsonb;
  v_effective_budget numeric(78,0);
  v_committed numeric(78,0);
  v_available numeric(78,0);
  v_promo numeric(78,0);
  v_promo_consumed numeric(78,0);
  v_promo_remaining numeric(78,0);
  v_promo_reserve numeric(78,0);
  v_queued integer;
  v_apps0 integer;
  v_apps1 integer;
  v_apps2 integer;
  v_vot3_ready integer;
  v_vote_ready integer;
  v_expected_bps numeric(78,0);
  v_stress_bps numeric(78,0);
  v_expected_n integer;
  v_stress_growth_n integer;
  v_stress_n integer;
  v_late_reward numeric(78,0);
  v_incomplete_count integer;
  v_incomplete_bps numeric(78,0);
  v_total_weighted_bps numeric(78,0);
  v_weighted_liability numeric(78,0);
  v_max_sweepable numeric(78,0);
  v_revision text;
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  select * into v_cfg
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id=p_source_allocation_receipt_id
    and a.network=p_network
    and a.app_id=p_app_id;

  if not found
     or v_receipt.vebetter_round_id+1<>
        p_source_reward_cohort_round_id then
    raise exception 'REWARD_BOOST_RESERVE_SOURCE_MISMATCH';
  end if;

  select max(a.vebetter_round_id+1)
  into v_current_cohort
  from public.vebetter_round_allocations a
  where a.network=p_network
    and a.app_id=p_app_id;

  if v_current_cohort is null
     or p_source_reward_cohort_round_id >
        v_current_cohort-v_cfg.reward_boost_reserve_long_incomplete_rounds then
    raise exception 'REWARD_BOOST_RESERVE_SOURCE_NOT_MATURE';
  end if;

  if exists (
    select 1
    from public.reward_boost_reserve_ledger l
    where l.network=p_network
      and l.app_id=p_app_id
      and l.source_reward_cohort_round_id=
          p_source_reward_cohort_round_id
      and l.source_allocation_receipt_id=
          p_source_allocation_receipt_id
      and l.entry_kind='SOURCE_SWEEP'
  ) then
    raise exception 'REWARD_BOOST_RESERVE_SOURCE_ALREADY_SWEPT';
  end if;

  v_effective_budget :=
    public.read_reward_cohort_effective_budget_wei(
      p_network,
      p_app_id,
      p_source_reward_cohort_round_id,
      p_source_allocation_receipt_id
    );

  v_committed :=
    public.read_reward_cohort_committed_wei(
      p_network,
      p_app_id,
      p_source_reward_cohort_round_id,
      p_source_allocation_receipt_id
    );

  v_available:=greatest(v_effective_budget-v_committed,0);

  select coalesce(sum(a.amount_wei),0)
  into v_promo
  from public.reward_cohort_funding_adjustments a
  where a.network=p_network
    and a.app_id=p_app_id
    and a.reward_cohort_round_id=
        p_source_reward_cohort_round_id
    and a.allocation_receipt_id=
        p_source_allocation_receipt_id
    and a.adjustment_type='PROMOTION';

  v_promo_consumed:=least(v_committed,v_promo);
  v_promo_remaining:=greatest(v_promo-v_promo_consumed,0);
  v_promo_reserve:=least(
    v_promo_remaining,
    ceil(
      v_promo *
      v_cfg.reward_boost_reserve_promotion_reserve_bps /
      10000
    )
  );

  v_planning:=public.read_reward_cohort_planning_snapshot(
    p_network,
    p_app_id,
    p_source_reward_cohort_round_id,
    p_source_allocation_receipt_id
  );

  v_queued:=coalesce(
    public.read_sybil_v2_cleared_unreserved_count(
      p_network,
      p_source_reward_cohort_round_id,
      p_source_allocation_receipt_id
    ),
    0
  )::integer;

  v_apps0:=coalesce(
    (v_planning->'pipeline'->>'activatedZeroCount')::integer,0
  );
  v_apps1:=coalesce(
    (v_planning->'pipeline'->>'appsOneCount')::integer,0
  );
  v_apps2:=coalesce(
    (v_planning->'pipeline'->>'appsTwoCount')::integer,0
  );
  v_vot3_ready:=coalesce(
    (v_planning->'pipeline'->>'vot3ReadyCount')::integer,0
  );
  v_vote_ready:=coalesce(
    (v_planning->'pipeline'->>'voteReadyCount')::integer,0
  );

  v_expected_bps :=
      v_queued*10000::numeric
    + v_vote_ready*9500::numeric
    + v_vot3_ready*9000::numeric
    + v_apps2*6000::numeric
    + v_apps1*4000::numeric
    + v_apps0*2500::numeric;

  v_stress_bps :=
      v_queued*10000::numeric
    + v_vote_ready*10000::numeric
    + v_vot3_ready*9500::numeric
    + v_apps2*8000::numeric
    + v_apps1*6000::numeric
    + v_apps0*4500::numeric;

  v_expected_n:=ceil(v_expected_bps/10000)::integer;
  v_stress_growth_n:=
    ceil(v_stress_bps*12500/100000000)::integer;

  v_stress_n:=greatest(
    4,
    v_queued,
    v_expected_n,
    v_stress_growth_n+2
  );

  v_late_reward:=
    case
      when v_stress_n>0 then floor(v_available/v_stress_n)
      else 0
    end;

  select
    count(*)::integer,
    coalesce(sum(
      case
        when coalesce(i.vote_completed,false) then 10000
        when coalesce(i.apps_completed,0)>=3
          and coalesce(i.vot3_converted,false) then 9500
        when coalesce(i.apps_completed,0)>=3 then 9000
        when coalesce(i.apps_completed,0)=2 then 6000
        when coalesce(i.apps_completed,0)=1 then 4000
        else 2500
      end
    ),0)::numeric
  into
    v_incomplete_count,
    v_incomplete_bps
  from public.invitations i
  where i.activation_network=p_network
    and i.reward_cohort_round_id=
        p_source_reward_cohort_round_id
    and i.reward_funding_allocation_receipt_id=
        p_source_allocation_receipt_id
    and i.status in ('ACTIVATING','UNDER_REVIEW')
    and coalesce(i.sybil_status,'')<>'BLOCKED'
    and not exists (
      select 1
      from public.sybil_v2_wallet_restrictions r
      where r.network=p_network
        and lower(r.wallet_address)=lower(i.invitee_wallet)
        and r.status='ACTIVE'
    );

  v_total_weighted_bps:=
    v_incomplete_bps + v_queued*10000::numeric;

  v_weighted_liability:=
    ceil(v_late_reward*v_total_weighted_bps/10000);

  v_max_sweepable:=greatest(
    v_available-v_promo_reserve-v_weighted_liability,
    0
  );

  v_revision:=
    public.read_reward_boost_reserve_source_revision(
      p_network,
      p_app_id
    );

  return jsonb_build_object(
    'network',p_network,
    'appId',p_app_id,
    'sourceRewardCohortRoundId',
      p_source_reward_cohort_round_id,
    'sourceAllocationReceiptId',
      p_source_allocation_receipt_id,
    'baselineEffectiveBudgetWei',
      v_effective_budget::text,
    'baselineCommittedWei',v_committed::text,
    'availableWei',v_available::text,
    'promotionOriginalWei',v_promo::text,
    'promotionReserveWei',v_promo_reserve::text,
    'lateRewardWei',v_late_reward::text,
    'stressRecipients',v_stress_n,
    'queuedEligibleCount',v_queued,
    'longIncompleteCount',v_incomplete_count,
    'lateWeightedBps',v_total_weighted_bps::text,
    'lateWeightedLiabilityWei',
      v_weighted_liability::text,
    'maxSweepableWei',v_max_sweepable::text,
    'sourceRevision',v_revision
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_bank_stress_reserve_wei(p_network text, p_app_id text)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_amount numeric(78,0);
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  select coalesce(max(p.late_reward_wei),0)
  into v_amount
  from public.reward_boost_reserve_source_protections p
  where p.network=p_network
    and p.app_id=p_app_id
    and p.long_incomplete_count>0;

  return v_amount;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_source_retained_wei(p_network text, p_app_id text)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_total numeric(78,0);
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  select coalesce(sum(
    p.promotion_reserve_wei +
    greatest(
      p.late_weighted_liability_wei -
      greatest(
        public.read_reward_cohort_committed_wei(
          p.network,
          p.app_id,
          p.source_reward_cohort_round_id,
          p.source_allocation_receipt_id
        ) - p.baseline_committed_wei,
        0
      ),
      0
    )
  ),0)
  into v_total
  from public.reward_boost_reserve_source_protections p
  where p.network=p_network
    and p.app_id=p_app_id;

  return v_total;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_recent_protected_wei(p_network text, p_app_id text, p_current_reward_cohort_round_id bigint)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_long_rounds integer;
  v_total numeric(78,0);
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  select reward_boost_reserve_long_incomplete_rounds
  into v_long_rounds
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  select coalesce(sum(
    greatest(
      public.read_reward_cohort_effective_budget_wei(
        a.network,
        a.app_id,
        a.vebetter_round_id+1,
        a.id
      ) -
      public.read_reward_cohort_committed_wei(
        a.network,
        a.app_id,
        a.vebetter_round_id+1,
        a.id
      ),
      0
    )
  ),0)
  into v_total
  from public.vebetter_round_allocations a
  where a.network=p_network
    and a.app_id=p_app_id
    and a.vebetter_round_id+1 <
      p_current_reward_cohort_round_id
    and a.vebetter_round_id+1 >
      p_current_reward_cohort_round_id-v_long_rounds;

  return v_total;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_reward_boost_reserve_ledger()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_source_receipt public.vebetter_round_allocations%rowtype;
  v_destination_receipt public.vebetter_round_allocations%rowtype;
  v_protection public.reward_boost_reserve_source_protections%rowtype;
  v_destination_plan public.reward_boost_reserve_destination_plans%rowtype;
  v_budget numeric(78,0) := 0;
  v_committed numeric(78,0) := 0;
  v_balance numeric(78,0) := 0;
  v_stress_reserve numeric(78,0) := 0;
  v_releaseable numeric(78,0) := 0;
  v_existing_source_sweep numeric(78,0) := 0;
  v_existing_boost_release numeric(78,0) := 0;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_reservation_' || new.network,
      0
    )
  );
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_boost_reserve_' ||
      new.network || '_' || new.app_id,
      0
    )
  );

  if new.entry_kind = 'SOURCE_SWEEP' then
    select * into v_source_receipt
    from public.vebetter_round_allocations a
    where a.id = new.source_allocation_receipt_id;

    if not found
       or v_source_receipt.network <> new.network
       or v_source_receipt.app_id <> new.app_id
       or v_source_receipt.vebetter_round_id + 1 <>
          new.source_reward_cohort_round_id then
      raise exception 'REWARD_BOOST_RESERVE_SOURCE_MISMATCH';
    end if;

    select * into v_protection
    from public.reward_boost_reserve_source_protections p
    where p.network=new.network
      and p.app_id=new.app_id
      and p.source_reward_cohort_round_id=
          new.source_reward_cohort_round_id
      and p.source_allocation_receipt_id=
          new.source_allocation_receipt_id;

    if not found then
      raise exception 'REWARD_BOOST_RESERVE_SOURCE_PROTECTION_REQUIRED';
    end if;

    select coalesce(sum(l.amount_wei),0)
    into v_existing_source_sweep
    from public.reward_boost_reserve_ledger l
    where l.network=new.network
      and l.app_id=new.app_id
      and l.entry_kind='SOURCE_SWEEP'
      and l.source_reward_cohort_round_id=
          new.source_reward_cohort_round_id
      and l.source_allocation_receipt_id=
          new.source_allocation_receipt_id;

    if v_existing_source_sweep + new.amount_wei >
       v_protection.max_sweepable_wei then
      raise exception 'REWARD_BOOST_RESERVE_SOURCE_PROTECTION_EXCEEDED';
    end if;

    v_budget := public.read_reward_cohort_effective_budget_wei(
      new.network,new.app_id,
      new.source_reward_cohort_round_id,
      new.source_allocation_receipt_id
    );

    v_committed := public.read_reward_cohort_committed_wei(
      new.network,new.app_id,
      new.source_reward_cohort_round_id,
      new.source_allocation_receipt_id
    );

    if new.amount_wei > greatest(v_budget-v_committed,0) then
      raise exception 'REWARD_BOOST_RESERVE_SOURCE_EXCEEDED';
    end if;
  else
    select * into v_destination_receipt
    from public.vebetter_round_allocations a
    where a.id = new.destination_allocation_receipt_id;

    if not found
       or v_destination_receipt.network <> new.network
       or v_destination_receipt.app_id <> new.app_id
       or v_destination_receipt.vebetter_round_id + 1 <>
          new.destination_reward_cohort_round_id then
      raise exception 'REWARD_BOOST_RESERVE_DESTINATION_MISMATCH';
    end if;

    v_balance := public.read_reward_boost_reserve_balance_wei(
      new.network,new.app_id
    );

    if new.entry_kind='BOOST_RELEASE' then
      select * into v_destination_plan
      from public.reward_boost_reserve_destination_plans d
      where d.network=new.network
        and d.app_id=new.app_id
        and d.destination_reward_cohort_round_id=
            new.destination_reward_cohort_round_id
        and d.destination_allocation_receipt_id=
            new.destination_allocation_receipt_id;

      if not found then
        raise exception 'REWARD_BOOST_DESTINATION_PLAN_REQUIRED';
      end if;

      select coalesce(sum(l.amount_wei),0)
      into v_existing_boost_release
      from public.reward_boost_reserve_ledger l
      where l.network=new.network
        and l.app_id=new.app_id
        and l.entry_kind='BOOST_RELEASE'
        and l.destination_reward_cohort_round_id=
            new.destination_reward_cohort_round_id
        and l.destination_allocation_receipt_id=
            new.destination_allocation_receipt_id;

      if v_existing_boost_release + new.amount_wei >
         v_destination_plan.max_boost_release_wei then
        raise exception 'REWARD_BOOST_DESTINATION_PLAN_EXCEEDED';
      end if;

      v_stress_reserve :=
        public.read_reward_boost_reserve_bank_stress_reserve_wei(
          new.network,new.app_id
        );
      v_releaseable:=greatest(v_balance-v_stress_reserve,0);

      if new.amount_wei > v_releaseable then
        raise exception 'REWARD_BOOST_RESERVE_STRESS_RESERVE_PROTECTED';
      end if;
    elsif new.amount_wei > v_balance then
      raise exception 'REWARD_BOOST_RESERVE_BALANCE_EXCEEDED';
    end if;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.seal_and_sweep_reward_boost_reserve_source(p_network text, p_app_id text, p_source_reward_cohort_round_id bigint, p_source_allocation_receipt_id bigint, p_policy_version text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_cfg public.reward_runtime_config%rowtype;
  v_existing public.reward_boost_reserve_source_protections%rowtype;
  v_existing_ledger_id bigint;
  v_candidate jsonb;
  v_revision_before text;
  v_revision_after text;
  v_protection public.reward_boost_reserve_source_protections%rowtype;
  v_ledger public.reward_boost_reserve_ledger%rowtype;
  v_amount numeric(78,0);
  v_reference_key text;
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));
  p_policy_version:=btrim(p_policy_version);

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_reservation_' || p_network,0
    )
  );
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_boost_reserve_' ||
      p_network || '_' || p_app_id,0
    )
  );

  select * into v_cfg
  from public.reward_runtime_config
  where id=1
  for update;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;
  if not v_cfg.reward_boost_reserve_enabled then
    raise exception 'REWARD_BOOST_RESERVE_DISABLED';
  end if;
  if v_cfg.emergency_rewards_paused then
    raise exception 'REWARD_BOOST_RESERVE_PAUSED';
  end if;
  if p_network='mainnet'
     and not v_cfg.mainnet_funded_rewards_enabled then
    raise exception 'REWARD_BOOST_RESERVE_MAINNET_DISABLED';
  end if;

  select * into v_existing
  from public.reward_boost_reserve_source_protections p
  where p.network=p_network
    and p.app_id=p_app_id
    and p.source_reward_cohort_round_id=
        p_source_reward_cohort_round_id
    and p.source_allocation_receipt_id=
        p_source_allocation_receipt_id;

  if found then
    select l.id
    into v_existing_ledger_id
    from public.reward_boost_reserve_ledger l
    where l.network=p_network
      and l.app_id=p_app_id
      and l.entry_kind='SOURCE_SWEEP'
      and l.source_reward_cohort_round_id=
          p_source_reward_cohort_round_id
      and l.source_allocation_receipt_id=
          p_source_allocation_receipt_id
      and (l.details->>'protectionId')::bigint=v_existing.id
    order by l.id
    limit 1;

    return jsonb_build_object(
      'changed',false,
      'protectionId',v_existing.id,
      'sourceSweepLedgerId',v_existing_ledger_id,
      'maxSweepableWei',
        v_existing.max_sweepable_wei::text,
      'sourceRevision',v_existing.source_revision
    );
  end if;

  perform 1
  from public.invitations i
  where i.activation_network=p_network
    and i.reward_cohort_round_id=
      p_source_reward_cohort_round_id
    and i.reward_funding_allocation_receipt_id=
      p_source_allocation_receipt_id
  for update;

  v_revision_before:=
    public.read_reward_boost_reserve_source_revision(
      p_network,p_app_id
    );

  v_candidate:=
    public.read_reward_boost_reserve_source_candidate(
      p_network,p_app_id,
      p_source_reward_cohort_round_id,
      p_source_allocation_receipt_id
    );

  v_revision_after:=
    public.read_reward_boost_reserve_source_revision(
      p_network,p_app_id
    );

  if v_revision_before<>v_revision_after
     or v_candidate->>'sourceRevision'<>v_revision_after then
    raise exception 'REWARD_BOOST_RESERVE_RECALCULATE';
  end if;

  insert into public.reward_boost_reserve_source_protections(
    network,app_id,
    source_reward_cohort_round_id,
    source_allocation_receipt_id,
    baseline_effective_budget_wei,
    baseline_committed_wei,
    promotion_original_wei,
    promotion_reserve_wei,
    late_reward_wei,
    queued_eligible_count,
    long_incomplete_count,
    late_weighted_bps,
    late_weighted_liability_wei,
    max_sweepable_wei,
    source_revision,
    policy_version
  ) values (
    p_network,p_app_id,
    p_source_reward_cohort_round_id,
    p_source_allocation_receipt_id,
    (v_candidate->>'baselineEffectiveBudgetWei')::numeric,
    (v_candidate->>'baselineCommittedWei')::numeric,
    (v_candidate->>'promotionOriginalWei')::numeric,
    (v_candidate->>'promotionReserveWei')::numeric,
    (v_candidate->>'lateRewardWei')::numeric,
    (v_candidate->>'queuedEligibleCount')::integer,
    (v_candidate->>'longIncompleteCount')::integer,
    (v_candidate->>'lateWeightedBps')::numeric,
    (v_candidate->>'lateWeightedLiabilityWei')::numeric,
    (v_candidate->>'maxSweepableWei')::numeric,
    v_revision_after,
    p_policy_version
  )
  returning * into v_protection;

  v_amount:=v_protection.max_sweepable_wei;

  if v_amount>0 then
    v_reference_key:=
      'source-protection:' ||
      p_source_allocation_receipt_id::text || ':' ||
      v_protection.source_revision;

    insert into public.reward_boost_reserve_ledger(
      network,app_id,entry_kind,
      source_reward_cohort_round_id,
      source_allocation_receipt_id,
      amount_wei,policy_version,reference_key,details
    ) values (
      p_network,p_app_id,'SOURCE_SWEEP',
      p_source_reward_cohort_round_id,
      p_source_allocation_receipt_id,
      v_amount,p_policy_version,v_reference_key,
      jsonb_build_object(
        'protectionId',v_protection.id,
        'sourceRevision',v_protection.source_revision,
        'promotionReserveWei',
          v_protection.promotion_reserve_wei::text,
        'lateWeightedLiabilityWei',
          v_protection.late_weighted_liability_wei::text
      )
    )
    returning * into v_ledger;
  end if;

  return jsonb_build_object(
    'changed',true,
    'protectionId',v_protection.id,
    'sourceSweepLedgerId',
      case when v_amount>0 then v_ledger.id else null end,
    'maxSweepableWei',v_amount::text,
    'promotionReserveWei',
      v_protection.promotion_reserve_wei::text,
    'lateRewardWei',v_protection.late_reward_wei::text,
    'lateWeightedLiabilityWei',
      v_protection.late_weighted_liability_wei::text,
    'sourceRevision',v_protection.source_revision
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.seal_and_release_reward_boost_destination(p_network text, p_app_id text, p_observed_pool_balance_wei numeric, p_policy_version text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_cfg public.reward_runtime_config%rowtype;
  v_receipt public.vebetter_round_allocations%rowtype;
  v_existing public.reward_boost_reserve_destination_plans%rowtype;
  v_existing_ledger_id bigint;
  v_plan public.reward_boost_reserve_destination_plans%rowtype;
  v_ledger public.reward_boost_reserve_ledger%rowtype;
  v_current_round bigint;
  v_planning jsonb;
  v_funding_adjustment numeric(78,0);
  v_fresh_designated numeric(78,0);
  v_committed numeric(78,0);
  v_fresh_available numeric(78,0);
  v_reserved_existing numeric(78,0);
  v_physical_unreserved numeric(78,0);
  v_bank_balance numeric(78,0);
  v_bank_stress numeric(78,0);
  v_bank_available numeric(78,0);
  v_recent_protected numeric(78,0);
  v_source_retained numeric(78,0);
  v_current_pricing numeric(78,0);
  v_physical_headroom numeric(78,0);
  v_max_release numeric(78,0);
  v_reference_key text;
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));
  p_policy_version:=btrim(p_policy_version);

  if p_observed_pool_balance_wei is null
     or p_observed_pool_balance_wei<0
     or p_observed_pool_balance_wei<>
        trunc(p_observed_pool_balance_wei) then
    raise exception 'INVALID_REWARD_BOOST_OBSERVED_POOL';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_reservation_' || p_network,0
    )
  );
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_boost_reserve_' ||
      p_network || '_' || p_app_id,0
    )
  );

  select * into v_cfg
  from public.reward_runtime_config
  where id=1
  for update;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;
  if not v_cfg.reward_boost_reserve_enabled then
    raise exception 'REWARD_BOOST_RESERVE_DISABLED';
  end if;
  if v_cfg.emergency_rewards_paused then
    raise exception 'REWARD_BOOST_RESERVE_PAUSED';
  end if;
  if p_network='mainnet'
     and not v_cfg.mainnet_funded_rewards_enabled then
    raise exception 'REWARD_BOOST_RESERVE_MAINNET_DISABLED';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.network=p_network
    and a.app_id=p_app_id
  order by a.vebetter_round_id desc,a.id desc
  limit 1;

  if not found then
    return jsonb_build_object(
      'changed',false,
      'reason','ALLOCATION_UNAVAILABLE'
    );
  end if;

  v_current_round:=v_receipt.vebetter_round_id+1;

  select * into v_existing
  from public.reward_boost_reserve_destination_plans d
  where d.network=p_network
    and d.app_id=p_app_id
    and d.destination_reward_cohort_round_id=v_current_round
    and d.destination_allocation_receipt_id=v_receipt.id;

  if found then
    select l.id
    into v_existing_ledger_id
    from public.reward_boost_reserve_ledger l
    where l.network=p_network
      and l.app_id=p_app_id
      and l.entry_kind='BOOST_RELEASE'
      and l.destination_reward_cohort_round_id=v_current_round
      and l.destination_allocation_receipt_id=v_receipt.id
      and (l.details->>'destinationPlanId')::bigint=
          v_existing.id
    order by l.id
    limit 1;

    return jsonb_build_object(
      'changed',false,
      'planId',v_existing.id,
      'boostReleaseLedgerId',v_existing_ledger_id,
      'maxBoostReleaseWei',
        v_existing.max_boost_release_wei::text
    );
  end if;

  if exists (
    select 1
    from public.reward_boost_reserve_ledger l
    where l.network=p_network
      and l.app_id=p_app_id
      and l.entry_kind='BOOST_RELEASE'
      and l.destination_reward_cohort_round_id=v_current_round
      and l.destination_allocation_receipt_id=v_receipt.id
  ) then
    raise exception 'REWARD_BOOST_DESTINATION_UNPLANNED_RELEASE_EXISTS';
  end if;

  select coalesce(sum(a.amount_wei),0)
  into v_funding_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network=p_network
    and a.app_id=p_app_id
    and a.reward_cohort_round_id=v_current_round
    and a.allocation_receipt_id=v_receipt.id;

  v_fresh_designated:=
    v_receipt.rewards_allocation_amount_wei +
    v_funding_adjustment;

  v_committed:=
    public.read_reward_cohort_committed_wei(
      p_network,p_app_id,v_current_round,v_receipt.id
    );

  v_fresh_available:=greatest(
    v_fresh_designated-v_committed,
    0
  );

  v_planning:=public.read_reward_cohort_planning_snapshot(
    p_network,
    p_app_id,
    v_current_round,
    v_receipt.id
  );

  v_reserved_existing:=
    coalesce(
      nullif(v_planning->>'reservedExistingWei','')::numeric,
      0
    );

  v_physical_unreserved:=greatest(
    p_observed_pool_balance_wei-v_reserved_existing,
    0
  );

  v_bank_balance:=
    public.read_reward_boost_reserve_balance_wei(
      p_network,p_app_id
    );
  v_bank_stress:=
    public.read_reward_boost_reserve_bank_stress_reserve_wei(
      p_network,p_app_id
    );
  v_bank_available:=greatest(
    v_bank_balance-v_bank_stress,
    0
  );

  v_recent_protected:=
    public.read_reward_boost_reserve_recent_protected_wei(
      p_network,p_app_id,v_current_round
    );

  v_source_retained:=
    public.read_reward_boost_reserve_source_retained_wei(
      p_network,p_app_id
    );

  v_current_pricing:=least(
    v_fresh_available,
    v_physical_unreserved
  );

  v_physical_headroom:=greatest(
    v_physical_unreserved -
    v_current_pricing -
    v_recent_protected -
    v_source_retained -
    v_bank_stress,
    0
  );

  v_max_release:=least(
    v_current_pricing,
    v_bank_available,
    v_physical_headroom
  );

  if v_max_release<=0 then
    return jsonb_build_object(
      'changed',false,
      'reason','NO_SAFE_BOOST_CAPACITY',
      'currentRewardCohortRoundId',v_current_round,
      'bankBalanceWei',v_bank_balance::text,
      'bankStressReserveWei',v_bank_stress::text,
      'recentCohortProtectedWei',v_recent_protected::text,
      'sourceRetainedProtectionWei',v_source_retained::text,
      'physicalExtraHeadroomWei',v_physical_headroom::text
    );
  end if;

  insert into public.reward_boost_reserve_destination_plans(
    network,app_id,
    destination_reward_cohort_round_id,
    destination_allocation_receipt_id,
    baseline_fresh_designated_wei,
    baseline_committed_wei,
    baseline_fresh_pricing_capacity_wei,
    bank_balance_before_wei,
    bank_stress_reserve_wei,
    recent_cohort_protected_wei,
    source_retained_protection_wei,
    observed_pool_balance_wei,
    reserved_existing_wei,
    physical_extra_headroom_wei,
    max_boost_release_wei,
    policy_version
  ) values (
    p_network,p_app_id,
    v_current_round,v_receipt.id,
    v_fresh_designated,
    v_committed,
    v_current_pricing,
    v_bank_balance,
    v_bank_stress,
    v_recent_protected,
    v_source_retained,
    p_observed_pool_balance_wei,
    v_reserved_existing,
    v_physical_headroom,
    v_max_release,
    p_policy_version
  )
  returning * into v_plan;

  v_reference_key:=
    'boost-destination:' ||
    v_receipt.id::text || ':' ||
    v_plan.id::text;

  insert into public.reward_boost_reserve_ledger(
    network,app_id,entry_kind,
    destination_reward_cohort_round_id,
    destination_allocation_receipt_id,
    amount_wei,policy_version,reference_key,details
  ) values (
    p_network,p_app_id,'BOOST_RELEASE',
    v_current_round,v_receipt.id,
    v_max_release,p_policy_version,v_reference_key,
    jsonb_build_object(
      'destinationPlanId',v_plan.id,
      'bankStressReserveWei',v_bank_stress::text,
      'recentCohortProtectedWei',v_recent_protected::text,
      'sourceRetainedProtectionWei',v_source_retained::text,
      'physicalExtraHeadroomWei',v_physical_headroom::text
    )
  )
  returning * into v_ledger;

  return jsonb_build_object(
    'changed',true,
    'planId',v_plan.id,
    'boostReleaseLedgerId',v_ledger.id,
    'destinationRewardCohortRoundId',v_current_round,
    'destinationAllocationReceiptId',v_receipt.id,
    'maxBoostReleaseWei',v_max_release::text,
    'freshPricingCapacityWei',v_current_pricing::text,
    'bankBalanceWei',v_bank_balance::text,
    'bankStressReserveWei',v_bank_stress::text,
    'recentCohortProtectedWei',v_recent_protected::text,
    'sourceRetainedProtectionWei',v_source_retained::text,
    'physicalExtraHeadroomWei',v_physical_headroom::text
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.append_reward_boost_reserve_release(p_network text, p_app_id text, p_entry_kind text, p_destination_reward_cohort_round_id bigint, p_destination_allocation_receipt_id bigint, p_amount_wei numeric, p_policy_version text, p_reference_key text, p_details jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_cfg public.reward_runtime_config%rowtype;
  v_kind text := upper(btrim(p_entry_kind));
  v_existing public.reward_boost_reserve_ledger%rowtype;
  v_row public.reward_boost_reserve_ledger%rowtype;
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));
  p_policy_version := btrim(p_policy_version);
  p_reference_key := btrim(p_reference_key);

  if v_kind not in ('BOOST_RELEASE','LATE_COMPLETION_RELEASE') then
    raise exception 'INVALID_REWARD_BOOST_RESERVE_RELEASE_KIND';
  end if;
  if p_amount_wei is null
     or p_amount_wei <= 0
     or p_amount_wei <> trunc(p_amount_wei) then
    raise exception 'INVALID_REWARD_BOOST_RESERVE_AMOUNT';
  end if;
  if p_details is null or jsonb_typeof(p_details) <> 'object' then
    raise exception 'INVALID_REWARD_BOOST_RESERVE_DETAILS';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_reward_reservation_' || p_network,0)
  );
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_boost_reserve_' || p_network || '_' || p_app_id,
      0
    )
  );

  select * into v_existing
  from public.reward_boost_reserve_ledger l
  where l.network=p_network
    and l.app_id=p_app_id
    and l.reference_key=p_reference_key;

  if found then
    if v_existing.entry_kind<>v_kind
       or v_existing.destination_reward_cohort_round_id<>p_destination_reward_cohort_round_id
       or v_existing.destination_allocation_receipt_id<>p_destination_allocation_receipt_id
       or v_existing.amount_wei<>p_amount_wei
       or v_existing.policy_version<>p_policy_version then
      raise exception 'REWARD_BOOST_RESERVE_REFERENCE_KEY_CONFLICT';
    end if;

    return jsonb_build_object(
      'changed',false,
      'id',v_existing.id,
      'entryKind',v_existing.entry_kind,
      'amountWei',v_existing.amount_wei::text,
      'referenceKey',v_existing.reference_key,
      'createdAt',v_existing.created_at
    );
  end if;

  select * into v_cfg
  from public.reward_runtime_config
  where id=1
  for update;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;
  if not v_cfg.reward_boost_reserve_enabled then
    raise exception 'REWARD_BOOST_RESERVE_DISABLED';
  end if;
  if v_cfg.emergency_rewards_paused then
    raise exception 'REWARD_BOOST_RESERVE_PAUSED';
  end if;
  if p_network='mainnet' and not v_cfg.mainnet_funded_rewards_enabled then
    raise exception 'REWARD_BOOST_RESERVE_MAINNET_DISABLED';
  end if;

  insert into public.reward_boost_reserve_ledger(
    network,
    app_id,
    entry_kind,
    destination_reward_cohort_round_id,
    destination_allocation_receipt_id,
    amount_wei,
    policy_version,
    reference_key,
    details
  ) values (
    p_network,
    p_app_id,
    v_kind,
    p_destination_reward_cohort_round_id,
    p_destination_allocation_receipt_id,
    p_amount_wei,
    p_policy_version,
    p_reference_key,
    p_details
  )
  returning * into v_row;

  return jsonb_build_object(
    'changed',true,
    'id',v_row.id,
    'entryKind',v_row.entry_kind,
    'amountWei',v_row.amount_wei::text,
    'referenceKey',v_row.reference_key,
    'createdAt',v_row.created_at
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_late_quote(p_network text, p_invite_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_enabled boolean;
  v_invitation public.invitations%rowtype;
  v_protection public.reward_boost_reserve_source_protections%rowtype;
begin
  p_network:=lower(btrim(p_network));
  p_invite_code:=upper(btrim(p_invite_code));

  select reward_boost_reserve_enabled
  into v_enabled
  from public.reward_runtime_config
  where id=1;

  if not coalesce(v_enabled,false) then
    return null;
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=p_invite_code
    and i.activation_network=p_network;

  if not found
     or v_invitation.reward_cohort_round_id is null
     or v_invitation.reward_funding_allocation_receipt_id is null then
    return null;
  end if;

  select * into v_protection
  from public.reward_boost_reserve_source_protections p
  where p.network=p_network
    and p.app_id=
      '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e'
    and p.source_reward_cohort_round_id=
      v_invitation.reward_cohort_round_id
    and p.source_allocation_receipt_id=
      v_invitation.reward_funding_allocation_receipt_id;

  if not found then
    return null;
  end if;

  return jsonb_build_object(
    'protectionId',v_protection.id,
    'amountWei',v_protection.late_reward_wei::text,
    'sourceRewardCohortRoundId',
      v_protection.source_reward_cohort_round_id,
    'sourceAllocationReceiptId',
      v_protection.source_allocation_receipt_id,
    'baselineEffectiveBudgetWei',
      v_protection.baseline_effective_budget_wei::text,
    'baselineCommittedWei',
      v_protection.baseline_committed_wei::text,
    'promotionReserveWei',
      v_protection.promotion_reserve_wei::text,
    'lateWeightedLiabilityWei',
      v_protection.late_weighted_liability_wei::text,
    'sourceRevision',v_protection.source_revision,
    'policyVersion',v_protection.policy_version
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.commit_reward_reservation_with_late_reserve(p_invite_code text, p_network text, p_observed_pool_balance_wei numeric, p_expected_reserved_before_wei numeric, p_amount_wei numeric, p_algorithm_version text, p_quote_snapshot_id bigint, p_finalized_block bigint, p_basis jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_code text := upper(btrim(p_invite_code));
  v_network text := lower(btrim(p_network));
  v_invitation public.invitations%rowtype;
  v_protection public.reward_boost_reserve_source_protections%rowtype;
  v_current_cohort bigint;
  v_long_rounds integer;
  v_reserve_enabled boolean;
  v_effective_budget numeric(78,0) := 0;
  v_committed numeric(78,0) := 0;
  v_required_release numeric(78,0) := 0;
  v_reference_key text;
  v_result jsonb;
  v_failure jsonb;
  v_message text;
  v_basis jsonb := coalesce(p_basis,'{}'::jsonb);
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_reward_reservation_' || v_network,0)
  );

  select
    reward_boost_reserve_enabled,
    reward_boost_reserve_long_incomplete_rounds
  into
    v_reserve_enabled,
    v_long_rounds
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=v_code
    and i.activation_network=v_network
  for update;

  if not found
     or v_invitation.reward_cohort_round_id is null
     or v_invitation.reward_funding_allocation_receipt_id is null then
    return public.commit_reward_reservation(
      p_invite_code,p_network,p_observed_pool_balance_wei,
      p_expected_reserved_before_wei,p_amount_wei,
      p_algorithm_version,p_quote_snapshot_id,
      p_finalized_block,p_basis
    );
  end if;

  select max(a.vebetter_round_id+1)
  into v_current_cohort
  from public.vebetter_round_allocations a
  where a.network=v_network
    and a.app_id=
      '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e';

  if v_current_cohort is null
     or v_invitation.reward_cohort_round_id >
        v_current_cohort-v_long_rounds then
    return public.commit_reward_reservation(
      p_invite_code,p_network,p_observed_pool_balance_wei,
      p_expected_reserved_before_wei,p_amount_wei,
      p_algorithm_version,p_quote_snapshot_id,
      p_finalized_block,p_basis
    );
  end if;

  select * into v_protection
  from public.reward_boost_reserve_source_protections p
  where p.network=v_network
    and p.app_id=
      '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e'
    and p.source_reward_cohort_round_id=
      v_invitation.reward_cohort_round_id
    and p.source_allocation_receipt_id=
      v_invitation.reward_funding_allocation_receipt_id;

  if not found or not v_reserve_enabled then
    return public.commit_reward_reservation(
      p_invite_code,p_network,p_observed_pool_balance_wei,
      p_expected_reserved_before_wei,p_amount_wei,
      p_algorithm_version,p_quote_snapshot_id,
      p_finalized_block,p_basis
    );
  end if;

  if p_amount_wei<>v_protection.late_reward_wei then
    return jsonb_build_object(
      'reserved',false,
      'reason','RECALCULATE',
      'expectedLateRewardWei',
        v_protection.late_reward_wei::text
    );
  end if;

  v_effective_budget :=
    public.read_reward_cohort_effective_budget_wei(
      v_network,
      '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e',
      v_invitation.reward_cohort_round_id,
      v_invitation.reward_funding_allocation_receipt_id
    );

  v_committed :=
    public.read_reward_cohort_committed_wei(
      v_network,
      '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e',
      v_invitation.reward_cohort_round_id,
      v_invitation.reward_funding_allocation_receipt_id
    );

  v_required_release :=
    greatest(
      v_committed +
      p_amount_wei +
      v_protection.promotion_reserve_wei -
      v_effective_budget,
      0
    );

  v_reference_key :=
    'late-completion:' || v_network || ':' || v_code;

  v_basis := v_basis || jsonb_build_object(
    'lateCompletion',true,
    'lateCompletionProtectionId',v_protection.id,
    'lateCompletionCurrentCohortRoundId',v_current_cohort,
    'lateCompletionOriginalCohortRoundId',
      v_invitation.reward_cohort_round_id,
    'lateCompletionProtectedRewardWei',
      v_protection.late_reward_wei::text,
    'lateCompletionReserveTopUpWei',
      v_required_release::text,
    'lateCompletionReserveReferenceKey',
      v_reference_key,
    'lateCompletionSourceRevision',
      v_protection.source_revision
  );

  begin
    if v_required_release>0 then
      perform public.append_reward_boost_reserve_release(
        v_network,
        '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e',
        'LATE_COMPLETION_RELEASE',
        v_invitation.reward_cohort_round_id,
        v_invitation.reward_funding_allocation_receipt_id,
        v_required_release,
        'late-completion-reserve-v1',
        v_reference_key,
        jsonb_build_object(
          'inviteCode',v_code,
          'protectionId',v_protection.id,
          'currentCohortRoundId',v_current_cohort,
          'originalCohortRoundId',
            v_invitation.reward_cohort_round_id
        )
      );
    end if;

    v_result := public.commit_reward_reservation(
      p_invite_code,p_network,p_observed_pool_balance_wei,
      p_expected_reserved_before_wei,p_amount_wei,
      p_algorithm_version,p_quote_snapshot_id,
      p_finalized_block,v_basis
    );

    if coalesce((v_result->>'reserved')::boolean,false) then
      return v_result || jsonb_build_object(
        'lateCompletion',true,
        'reserveTopUpWei',v_required_release::text,
        'protectedRewardWei',
          v_protection.late_reward_wei::text
      );
    end if;

    v_failure:=v_result;
    raise exception 'LATE_RESERVE_ROLLBACK';
  exception
    when raise_exception then
      get stacked diagnostics v_message=message_text;
      if v_message='LATE_RESERVE_ROLLBACK' then
        return v_failure;
      end if;
      raise;
  end;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_unprotected_sources(p_network text, p_app_id text)
 RETURNS TABLE(reward_cohort_round_id bigint, allocation_receipt_id bigint)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_long_rounds integer;
  v_current_cohort bigint;
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  select reward_boost_reserve_long_incomplete_rounds
  into v_long_rounds
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  select max(a.vebetter_round_id+1)
  into v_current_cohort
  from public.vebetter_round_allocations a
  where a.network=p_network
    and a.app_id=p_app_id;

  if v_current_cohort is null then
    return;
  end if;

  return query
  select
    a.vebetter_round_id+1,
    a.id
  from public.vebetter_round_allocations a
  where a.network=p_network
    and a.app_id=p_app_id
    and a.vebetter_round_id+1 <=
      v_current_cohort-v_long_rounds
    and not exists (
      select 1
      from public.reward_boost_reserve_source_protections p
      where p.network=p_network
        and p.app_id=p_app_id
        and p.source_reward_cohort_round_id=
            a.vebetter_round_id+1
        and p.source_allocation_receipt_id=a.id
    )
  order by a.vebetter_round_id,a.id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.read_reward_boost_reserve_audit_snapshot(p_network text, p_app_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public'
AS $function$
declare
  v_enabled boolean;
  v_shadow_enabled boolean;
  v_current_cohort bigint;
  v_source_inflow numeric(78,0);
  v_boost_outflow numeric(78,0);
  v_late_outflow numeric(78,0);
  v_bank_balance numeric(78,0);
  v_bank_stress numeric(78,0);
  v_source_retained numeric(78,0);
  v_recent_protected numeric(78,0);
  v_source_protection_count integer;
  v_destination_plan_count integer;
  v_unprotected_count integer;
  v_source_overrun_count integer;
  v_destination_overrun_count integer;
begin
  p_network:=lower(btrim(p_network));
  p_app_id:=lower(btrim(p_app_id));

  select
    reward_boost_reserve_enabled,
    reward_boost_reserve_shadow_enabled
  into
    v_enabled,
    v_shadow_enabled
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  select max(a.vebetter_round_id+1)
  into v_current_cohort
  from public.vebetter_round_allocations a
  where a.network=p_network
    and a.app_id=p_app_id;

  select
    coalesce(sum(l.amount_wei) filter (
      where l.entry_kind='SOURCE_SWEEP'
    ),0),
    coalesce(sum(l.amount_wei) filter (
      where l.entry_kind='BOOST_RELEASE'
    ),0),
    coalesce(sum(l.amount_wei) filter (
      where l.entry_kind='LATE_COMPLETION_RELEASE'
    ),0)
  into
    v_source_inflow,
    v_boost_outflow,
    v_late_outflow
  from public.reward_boost_reserve_ledger l
  where l.network=p_network
    and l.app_id=p_app_id;

  v_bank_balance :=
    v_source_inflow-v_boost_outflow-v_late_outflow;

  v_bank_stress :=
    public.read_reward_boost_reserve_bank_stress_reserve_wei(
      p_network,p_app_id
    );

  v_source_retained :=
    public.read_reward_boost_reserve_source_retained_wei(
      p_network,p_app_id
    );

  v_recent_protected :=
    case
      when v_current_cohort is null then 0
      else public.read_reward_boost_reserve_recent_protected_wei(
        p_network,p_app_id,v_current_cohort
      )
    end;

  select count(*)::integer
  into v_source_protection_count
  from public.reward_boost_reserve_source_protections p
  where p.network=p_network
    and p.app_id=p_app_id;

  select count(*)::integer
  into v_destination_plan_count
  from public.reward_boost_reserve_destination_plans d
  where d.network=p_network
    and d.app_id=p_app_id;

  select count(*)::integer
  into v_unprotected_count
  from public.read_reward_boost_reserve_unprotected_sources(
    p_network,p_app_id
  );

  select count(*)::integer
  into v_source_overrun_count
  from (
    select
      p.id,
      p.max_sweepable_wei,
      coalesce(sum(l.amount_wei),0) as swept_wei
    from public.reward_boost_reserve_source_protections p
    left join public.reward_boost_reserve_ledger l
      on l.network=p.network
     and l.app_id=p.app_id
     and l.entry_kind='SOURCE_SWEEP'
     and l.source_reward_cohort_round_id=
         p.source_reward_cohort_round_id
     and l.source_allocation_receipt_id=
         p.source_allocation_receipt_id
    where p.network=p_network
      and p.app_id=p_app_id
    group by p.id,p.max_sweepable_wei
    having coalesce(sum(l.amount_wei),0)>
           p.max_sweepable_wei
  ) x;

  select count(*)::integer
  into v_destination_overrun_count
  from (
    select
      d.id,
      d.max_boost_release_wei,
      coalesce(sum(l.amount_wei),0) as released_wei
    from public.reward_boost_reserve_destination_plans d
    left join public.reward_boost_reserve_ledger l
      on l.network=d.network
     and l.app_id=d.app_id
     and l.entry_kind='BOOST_RELEASE'
     and l.destination_reward_cohort_round_id=
         d.destination_reward_cohort_round_id
     and l.destination_allocation_receipt_id=
         d.destination_allocation_receipt_id
    where d.network=p_network
      and d.app_id=p_app_id
    group by d.id,d.max_boost_release_wei
    having coalesce(sum(l.amount_wei),0)>
           d.max_boost_release_wei
  ) x;

  return jsonb_build_object(
    'enabled',v_enabled,
    'shadowEnabled',v_shadow_enabled,
    'currentRewardCohortRoundId',v_current_cohort,
    'sourceInflowWei',v_source_inflow::text,
    'boostOutflowWei',v_boost_outflow::text,
    'lateCompletionOutflowWei',v_late_outflow::text,
    'bankBalanceWei',v_bank_balance::text,
    'bankStressReserveWei',v_bank_stress::text,
    'ordinaryBoostAvailableWei',
      greatest(v_bank_balance-v_bank_stress,0)::text,
    'sourceRetainedProtectionWei',v_source_retained::text,
    'recentCohortProtectedWei',v_recent_protected::text,
    'sourceProtectionCount',v_source_protection_count,
    'destinationPlanCount',v_destination_plan_count,
    'unprotectedMatureSourceCount',v_unprotected_count,
    'sourceOverrunCount',v_source_overrun_count,
    'destinationOverrunCount',v_destination_overrun_count,
    'conservationOk',
      v_bank_balance=
        v_source_inflow-v_boost_outflow-v_late_outflow,
    'stressReserveCovered',
      v_bank_balance>=v_bank_stress
  );
end;
$function$
;


drop trigger if exists reward_boost_reserve_ledger_validate on public.reward_boost_reserve_ledger;
create trigger reward_boost_reserve_ledger_validate
before insert on public.reward_boost_reserve_ledger
for each row execute function public.validate_reward_boost_reserve_ledger();

drop trigger if exists reward_boost_reserve_ledger_immutable_guard on public.reward_boost_reserve_ledger;
create trigger reward_boost_reserve_ledger_immutable_guard
before update or delete on public.reward_boost_reserve_ledger
for each row execute function public.reject_reward_boost_reserve_ledger_mutation();

drop trigger if exists reward_boost_source_protection_immutable_guard on public.reward_boost_reserve_source_protections;
create trigger reward_boost_source_protection_immutable_guard
before update or delete on public.reward_boost_reserve_source_protections
for each row execute function public.reject_reward_boost_source_protection_mutation();

drop trigger if exists reward_boost_destination_plan_immutable_guard on public.reward_boost_reserve_destination_plans;
create trigger reward_boost_destination_plan_immutable_guard
before update or delete on public.reward_boost_reserve_destination_plans
for each row execute function public.reject_reward_boost_destination_plan_mutation();

revoke all on function public.read_reward_boost_reserve_balance_wei(text,text) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_balance_wei(text,text) to service_role;
revoke all on function public.read_reward_boost_reserve_cohort_net_flow_wei(text,text,bigint,bigint) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_cohort_net_flow_wei(text,text,bigint,bigint) to service_role;
revoke all on function public.read_reward_cohort_effective_budget_wei(text,text,bigint,bigint) from public,anon,authenticated;
grant execute on function public.read_reward_cohort_effective_budget_wei(text,text,bigint,bigint) to service_role;

revoke all on function public.reject_reward_boost_reserve_ledger_mutation() from public,anon,authenticated;
revoke all on function public.reject_reward_boost_source_protection_mutation() from public,anon,authenticated;
revoke all on function public.reject_reward_boost_destination_plan_mutation() from public,anon,authenticated;
revoke all on function public.validate_reward_boost_reserve_ledger() from public,anon,authenticated;

revoke all on function public.read_reward_boost_reserve_source_revision(text,text) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_source_revision(text,text) to service_role;
revoke all on function public.read_reward_boost_reserve_source_candidate(text,text,bigint,bigint) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_source_candidate(text,text,bigint,bigint) to service_role;
revoke all on function public.read_reward_boost_reserve_bank_stress_reserve_wei(text,text) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_bank_stress_reserve_wei(text,text) to service_role;
revoke all on function public.read_reward_boost_reserve_source_retained_wei(text,text) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_source_retained_wei(text,text) to service_role;
revoke all on function public.read_reward_boost_reserve_recent_protected_wei(text,text,bigint) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_recent_protected_wei(text,text,bigint) to service_role;

revoke all on function public.seal_and_sweep_reward_boost_reserve_source(text,text,bigint,bigint,text) from public,anon,authenticated,service_role;
grant execute on function public.seal_and_sweep_reward_boost_reserve_source(text,text,bigint,bigint,text) to service_role;
revoke all on function public.seal_and_release_reward_boost_destination(text,text,numeric,text) from public,anon,authenticated,service_role;
grant execute on function public.seal_and_release_reward_boost_destination(text,text,numeric,text) to service_role;

revoke all on function public.append_reward_boost_reserve_release(text,text,text,bigint,bigint,numeric,text,text,jsonb)
from public,anon,authenticated,service_role;

revoke all on function public.read_reward_boost_reserve_late_quote(text,text) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_late_quote(text,text) to service_role;
revoke all on function public.commit_reward_reservation_with_late_reserve(text,text,numeric,numeric,numeric,text,bigint,bigint,jsonb)
from public,anon,authenticated,service_role;
grant execute on function public.commit_reward_reservation_with_late_reserve(text,text,numeric,numeric,numeric,text,bigint,bigint,jsonb)
to service_role;
revoke all on function public.read_reward_boost_reserve_unprotected_sources(text,text) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_unprotected_sources(text,text) to service_role;
revoke all on function public.read_reward_boost_reserve_audit_snapshot(text,text) from public,anon,authenticated;
grant execute on function public.read_reward_boost_reserve_audit_snapshot(text,text) to service_role;

update public.reward_runtime_config
set reward_boost_reserve_enabled=false
where id=1;
