create table if not exists public.reward_x_promotion_opportunities (
  id bigint generated by default as identity primary key,
  obligation_id bigint not null references public.reward_x_promotion_obligations(id),
  split_id bigint not null references public.reward_x_promotion_splits(id),
  invite_code text not null check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  promotion_amount_wei numeric(78,0) not null
    check (promotion_amount_wei>0 and promotion_amount_wei=trunc(promotion_amount_wei)),
  policy_version text not null
    check (char_length(btrim(policy_version)) between 1 and 80),
  offer_window_seconds integer not null
    check (offer_window_seconds between 60 and 604800),
  opened_at timestamptz not null,
  post_deadline_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint reward_x_promotion_opportunities_obligation_uidx unique(obligation_id),
  constraint reward_x_promotion_opportunities_split_uidx unique(split_id),
  constraint reward_x_promotion_opportunities_invite_uidx unique(invite_code),
  constraint reward_x_promotion_opportunities_window_check
    check (
      post_deadline_at =
      opened_at + make_interval(secs => offer_window_seconds)
    )
);

create index if not exists reward_x_promotion_opportunities_network_deadline_idx
  on public.reward_x_promotion_opportunities(network,post_deadline_at,id);

alter table public.reward_x_promotion_opportunities enable row level security;

revoke all on table public.reward_x_promotion_opportunities
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_opportunities_id_seq
  from public,anon,authenticated,service_role;

grant select,insert on table public.reward_x_promotion_opportunities
  to service_role;
grant usage,select on sequence public.reward_x_promotion_opportunities_id_seq
  to service_role;

create or replace function public.validate_reward_x_promotion_opportunity_insert()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_split public.reward_x_promotion_splits%rowtype;
  v_payout public.reward_payouts%rowtype;
  v_invitation public.invitations%rowtype;
begin
  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=new.obligation_id;

  if not found
     or v_obligation.invite_code<>new.invite_code
     or v_obligation.network<>new.network
     or v_obligation.recipient_wallet<>new.recipient_wallet
     or v_obligation.promotion_amount_wei<>new.promotion_amount_wei
     or v_obligation.policy_version<>new.policy_version
     or v_obligation.financial_state<>'HELD'
     or v_obligation.held_at is null
     or new.opened_at<v_obligation.held_at then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_OBLIGATION_MISMATCH';
  end if;

  select * into v_split
  from public.reward_x_promotion_splits x
  where x.id=new.split_id;

  if not found
     or v_split.id<>v_obligation.split_id
     or v_split.invite_code<>new.invite_code
     or v_split.network<>new.network
     or v_split.recipient_wallet<>new.recipient_wallet
     or v_split.promotion_amount_wei<>new.promotion_amount_wei
     or v_split.policy_version<>new.policy_version
     or v_split.policy_version<>'x-promotion-split-v1'
     or v_split.mode<>'LIVE' then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_SPLIT_MISMATCH';
  end if;

  if new.offer_window_seconds<>86400
     or new.post_deadline_at<>
        new.opened_at+make_interval(secs=>new.offer_window_seconds) then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_WINDOW_MISMATCH';
  end if;

  select * into v_payout
  from public.reward_payouts p
  where p.invite_code=new.invite_code
    and p.status='PAID';

  if not found
     or v_payout.amount_wei<>v_split.base_amount_wei
     or v_payout.paid_at is null
     or not exists (
       select 1
       from public.reward_receipts r
       where r.payout_id=v_payout.id
         and r.invite_code=new.invite_code
         and r.network=new.network
         and r.recipient_wallet=new.recipient_wallet
         and r.amount_wei=v_split.base_amount_wei
         and r.paid_at is not null
     ) then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_BASE_PROOF_MISSING';
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=new.invite_code;

  if not found
     or public.is_sybil_v2_referral_invalidated(new.invite_code,new.network)
     or exists (
       select 1
       from public.sybil_v2_wallet_restrictions r
       where r.network=new.network
         and r.status='ACTIVE'
         and r.wallet_address in (
           lower(new.recipient_wallet),
           lower(v_invitation.invitee_wallet)
         )
     ) then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_SECURITY_NOT_CLEAR';
  end if;

  return new;
end;
$function$;

revoke all on function public.validate_reward_x_promotion_opportunity_insert()
  from public,anon,authenticated,service_role;

drop trigger if exists validate_reward_x_promotion_opportunity_insert_trigger
  on public.reward_x_promotion_opportunities;
create trigger validate_reward_x_promotion_opportunity_insert_trigger
before insert on public.reward_x_promotion_opportunities
for each row execute function public.validate_reward_x_promotion_opportunity_insert();

create or replace function public.reject_reward_x_promotion_opportunity_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_IMMUTABLE';
end;
$function$;

revoke all on function public.reject_reward_x_promotion_opportunity_mutation()
  from public,anon,authenticated,service_role;

drop trigger if exists reject_reward_x_promotion_opportunity_mutation_trigger
  on public.reward_x_promotion_opportunities;
create trigger reject_reward_x_promotion_opportunity_mutation_trigger
before update or delete on public.reward_x_promotion_opportunities
for each row execute function public.reject_reward_x_promotion_opportunity_mutation();

create or replace function public.create_reward_x_promotion_opportunity_v1(
  p_invite_code text
)
returns jsonb
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(coalesce(p_invite_code,'')));
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_split public.reward_x_promotion_splits%rowtype;
  v_existing public.reward_x_promotion_opportunities%rowtype;
  v_created public.reward_x_promotion_opportunities%rowtype;
  v_payout public.reward_payouts%rowtype;
  v_opened_at timestamptz := clock_timestamp();
  v_window_seconds constant integer := 86400;
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_code,0)
  );

  select * into v_existing
  from public.reward_x_promotion_opportunities o
  where o.invite_code=v_code;

  if found then
    return jsonb_build_object(
      'created',false,
      'reason','ALREADY_EXISTS',
      'inviteCode',v_code,
      'opportunityId',v_existing.id,
      'openedAt',v_existing.opened_at,
      'postDeadlineAt',v_existing.post_deadline_at
    );
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.invite_code=v_code
  for update;

  if not found then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_MISSING';
  end if;

  if v_obligation.financial_state<>'HELD'
     or v_obligation.held_at is null then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_NOT_HELD';
  end if;

  select * into v_split
  from public.reward_x_promotion_splits s
  where s.id=v_obligation.split_id
    and s.invite_code=v_code
    and s.mode='LIVE';

  if not found
     or v_split.network<>v_obligation.network
     or v_split.recipient_wallet<>v_obligation.recipient_wallet
     or v_split.promotion_amount_wei<>v_obligation.promotion_amount_wei
     or v_split.policy_version<>v_obligation.policy_version
     or v_split.policy_version<>'x-promotion-split-v1' then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_SPLIT_MISMATCH';
  end if;

  select * into v_payout
  from public.reward_payouts p
  where p.invite_code=v_code
    and p.status='PAID';

  if not found
     or v_payout.amount_wei<>v_split.base_amount_wei
     or v_payout.paid_at is null
     or not exists (
       select 1
       from public.reward_receipts r
       where r.payout_id=v_payout.id
         and r.invite_code=v_code
         and r.network=v_obligation.network
         and r.recipient_wallet=v_obligation.recipient_wallet
         and r.amount_wei=v_split.base_amount_wei
         and r.paid_at is not null
     ) then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_BASE_PROOF_MISSING';
  end if;

  insert into public.reward_x_promotion_opportunities(
    obligation_id,
    split_id,
    invite_code,
    network,
    recipient_wallet,
    promotion_amount_wei,
    policy_version,
    offer_window_seconds,
    opened_at,
    post_deadline_at
  ) values (
    v_obligation.id,
    v_split.id,
    v_code,
    v_obligation.network,
    v_obligation.recipient_wallet,
    v_obligation.promotion_amount_wei,
    v_obligation.policy_version,
    v_window_seconds,
    v_opened_at,
    v_opened_at + make_interval(secs => v_window_seconds)
  )
  returning * into v_created;

  return jsonb_build_object(
    'created',true,
    'reason','CREATED',
    'inviteCode',v_code,
    'opportunityId',v_created.id,
    'amountWei',v_created.promotion_amount_wei::text,
    'openedAt',v_created.opened_at,
    'postDeadlineAt',v_created.post_deadline_at,
    'offerWindowSeconds',v_created.offer_window_seconds
  );
end;
$function$;

revoke all on function public.create_reward_x_promotion_opportunity_v1(text)
  from public,anon,authenticated;
grant execute on function public.create_reward_x_promotion_opportunity_v1(text)
  to service_role;

create or replace function public.sync_reward_x_promotion_opportunities_v1(
  p_network text,
  p_limit integer default 25
)
returns jsonb
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_limit integer := greatest(1,least(coalesce(p_limit,25),100));
  v_candidate record;
  v_activation jsonb;
  v_creation jsonb;
  v_considered integer := 0;
  v_activated integer := 0;
  v_created integer := 0;
  v_already integer := 0;
  v_failed integer := 0;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  for v_candidate in
    select
      o.invite_code,
      o.financial_state
    from public.reward_x_promotion_obligations o
    join public.reward_x_promotion_splits s
      on s.id=o.split_id
     and s.mode='LIVE'
    where o.network=v_network
      and o.financial_state in ('RESERVED','HELD')
      and not exists (
        select 1
        from public.reward_x_promotion_opportunities x
        where x.obligation_id=o.id
      )
      and (
        o.financial_state='HELD'
        or exists (
          select 1
          from public.reward_payouts p
          join public.reward_receipts r
            on r.payout_id=p.id
          where p.invite_code=o.invite_code
            and p.recipient_wallet=o.recipient_wallet
            and p.status='PAID'
            and p.amount_wei=s.base_amount_wei
            and p.paid_at is not null
            and r.invite_code=o.invite_code
            and r.network=o.network
            and r.recipient_wallet=o.recipient_wallet
            and r.amount_wei=s.base_amount_wei
            and r.paid_at is not null
        )
      )
    order by o.id
    limit v_limit
  loop
    v_considered:=v_considered+1;

    begin
      if v_candidate.financial_state='RESERVED' then
        v_activation :=
          public.activate_reward_x_promotion_obligation_v1(
            v_candidate.invite_code
          );
        if coalesce((v_activation->>'activated')::boolean,false) then
          v_activated:=v_activated+1;
        end if;
      end if;

      v_creation :=
        public.create_reward_x_promotion_opportunity_v1(
          v_candidate.invite_code
        );

      if coalesce((v_creation->>'created')::boolean,false) then
        v_created:=v_created+1;
      else
        v_already:=v_already+1;
      end if;
    exception when others then
      -- This is intentionally fail-soft and isolated from the core referral
      -- payout. The unchanged RESERVED/HELD row is eligible for a later retry.
      v_failed:=v_failed+1;
    end;
  end loop;

  return jsonb_build_object(
    'network',v_network,
    'consideredCount',v_considered,
    'activatedCount',v_activated,
    'createdCount',v_created,
    'alreadyExistsCount',v_already,
    'failedCount',v_failed
  );
end;
$function$;

revoke all on function public.sync_reward_x_promotion_opportunities_v1(text,integer)
  from public,anon,authenticated;
grant execute on function public.sync_reward_x_promotion_opportunities_v1(text,integer)
  to service_role;

create or replace function public.read_reward_x_promotion_opportunity_audit(
  p_network text
)
returns jsonb
language plpgsql
stable
set search_path to 'pg_catalog','public'
as $function$
declare
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_total integer := 0;
  v_binding_mismatch integer := 0;
  v_window_mismatch integer := 0;
  v_without_held integer := 0;
  v_held_without_opportunity integer := 0;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  select
    count(*)::integer,
    count(*) filter (
      where o.id is null
         or s.id is null
         or s.mode<>'LIVE'
         or x.split_id<>s.id
         or x.invite_code<>o.invite_code
         or x.network<>o.network
         or x.recipient_wallet<>o.recipient_wallet
         or x.promotion_amount_wei<>o.promotion_amount_wei
         or x.policy_version<>o.policy_version
    )::integer,
    count(*) filter (
      where x.offer_window_seconds<>86400
         or x.post_deadline_at<>
            x.opened_at+make_interval(secs=>x.offer_window_seconds)
    )::integer,
    count(*) filter (
      where o.financial_state not in ('HELD','RELEASED','PAID')
    )::integer
  into
    v_total,
    v_binding_mismatch,
    v_window_mismatch,
    v_without_held
  from public.reward_x_promotion_opportunities x
  left join public.reward_x_promotion_obligations o
    on o.id=x.obligation_id
  left join public.reward_x_promotion_splits s
    on s.id=x.split_id
  where x.network=v_network;

  select count(*)::integer
  into v_held_without_opportunity
  from public.reward_x_promotion_obligations o
  join public.reward_x_promotion_splits s
    on s.id=o.split_id
   and s.mode='LIVE'
  where o.network=v_network
    and o.financial_state='HELD'
    and not exists (
      select 1
      from public.reward_x_promotion_opportunities x
      where x.obligation_id=o.id
    );

  return jsonb_build_object(
    'ok',
      v_binding_mismatch=0
      and v_window_mismatch=0
      and v_without_held=0
      and v_held_without_opportunity=0,
    'network',v_network,
    'totalCount',v_total,
    'violations',jsonb_build_object(
      'binding',v_binding_mismatch,
      'window',v_window_mismatch,
      'opportunityWithoutHeldHistory',v_without_held,
      'heldWithoutOpportunity',v_held_without_opportunity
    )
  );
end;
$function$;

revoke all on function public.read_reward_x_promotion_opportunity_audit(text)
  from public,anon,authenticated;
grant execute on function public.read_reward_x_promotion_opportunity_audit(text)
  to service_role;

comment on table public.reward_x_promotion_opportunities is
  'Immutable user opportunity window created only after a LIVE promotion obligation is HELD. This table carries no payout authority and cannot block the core referral payout.';
