create table if not exists public.reward_x_promotion_runtime_events (
  id bigint generated by default as identity primary key,
  config_id smallint not null,
  previous_shadow_enabled boolean not null,
  shadow_enabled boolean not null,
  previous_live_enabled boolean not null,
  live_enabled boolean not null,
  previous_policy_version text not null,
  policy_version text not null,
  previous_shadow_started_at timestamptz,
  shadow_started_at timestamptz,
  previous_live_started_at timestamptz,
  live_started_at timestamptz,
  database_actor text not null,
  recorded_at timestamptz not null default now(),
  constraint reward_x_promotion_runtime_events_policy_check
    check (
      char_length(btrim(previous_policy_version)) between 1 and 80
      and char_length(btrim(policy_version)) between 1 and 80
    )
);

alter table public.reward_x_promotion_runtime_events enable row level security;

revoke all on table public.reward_x_promotion_runtime_events
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_runtime_events_id_seq
  from public,anon,authenticated,service_role;

grant select on table public.reward_x_promotion_runtime_events to service_role;

create or replace function public.log_reward_x_promotion_runtime_event()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  if new.reward_x_promotion_shadow_enabled
       is distinct from old.reward_x_promotion_shadow_enabled
     or new.reward_x_promotion_enabled
       is distinct from old.reward_x_promotion_enabled
     or new.reward_x_promotion_policy_version
       is distinct from old.reward_x_promotion_policy_version
     or new.reward_x_promotion_shadow_started_at
       is distinct from old.reward_x_promotion_shadow_started_at
     or new.reward_x_promotion_live_started_at
       is distinct from old.reward_x_promotion_live_started_at
  then
    insert into public.reward_x_promotion_runtime_events(
      config_id,
      previous_shadow_enabled,
      shadow_enabled,
      previous_live_enabled,
      live_enabled,
      previous_policy_version,
      policy_version,
      previous_shadow_started_at,
      shadow_started_at,
      previous_live_started_at,
      live_started_at,
      database_actor
    ) values (
      new.id,
      old.reward_x_promotion_shadow_enabled,
      new.reward_x_promotion_shadow_enabled,
      old.reward_x_promotion_enabled,
      new.reward_x_promotion_enabled,
      old.reward_x_promotion_policy_version,
      new.reward_x_promotion_policy_version,
      old.reward_x_promotion_shadow_started_at,
      new.reward_x_promotion_shadow_started_at,
      old.reward_x_promotion_live_started_at,
      new.reward_x_promotion_live_started_at,
      current_user
    );
  end if;

  return new;
end;
$function$;

create or replace function public.guard_reward_x_promotion_activation_timestamps()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  if old.reward_x_promotion_shadow_started_at is not null
     and new.reward_x_promotion_shadow_started_at
       is distinct from old.reward_x_promotion_shadow_started_at then
    raise exception 'REWARD_X_PROMOTION_SHADOW_START_IMMUTABLE';
  end if;

  if old.reward_x_promotion_live_started_at is not null
     and new.reward_x_promotion_live_started_at
       is distinct from old.reward_x_promotion_live_started_at then
    raise exception 'REWARD_X_PROMOTION_LIVE_START_IMMUTABLE';
  end if;

  return new;
end;
$function$;

drop trigger if exists reward_x_promotion_runtime_audit
  on public.reward_runtime_config;
create trigger reward_x_promotion_runtime_audit
after update of
  reward_x_promotion_shadow_enabled,
  reward_x_promotion_enabled,
  reward_x_promotion_policy_version,
  reward_x_promotion_shadow_started_at,
  reward_x_promotion_live_started_at
on public.reward_runtime_config
for each row execute function public.log_reward_x_promotion_runtime_event();

drop trigger if exists reward_x_promotion_activation_timestamp_guard
  on public.reward_runtime_config;
create trigger reward_x_promotion_activation_timestamp_guard
before update of
  reward_x_promotion_shadow_started_at,
  reward_x_promotion_live_started_at
on public.reward_runtime_config
for each row execute function public.guard_reward_x_promotion_activation_timestamps();

drop trigger if exists reward_x_promotion_runtime_events_append_only
  on public.reward_x_promotion_runtime_events;
create trigger reward_x_promotion_runtime_events_append_only
before update or delete on public.reward_x_promotion_runtime_events
for each row execute function public.prevent_operator_ledger_mutation();

revoke all on function public.log_reward_x_promotion_runtime_event()
  from public,anon,authenticated;
revoke all on function public.guard_reward_x_promotion_activation_timestamps()
  from public,anon,authenticated;

comment on table public.reward_x_promotion_runtime_events is
  'Append-only audit trail for X promotion runtime switches, policy version, and activation timestamps.';
