begin;

alter table public.reward_runtime_config
  add column if not exists reward_recovery_enabled boolean not null default false;

comment on column public.reward_runtime_config.reward_recovery_enabled is
  'Enables future-referral reward recovery offsets for previously paid referrals that were later invalidated. Existing payout receipts remain immutable.';

create table if not exists public.reward_recovery_obligations (
  id uuid primary key default gen_random_uuid(),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  source_invalidation_id uuid not null
    references public.sybil_v2_referral_invalidations(id) on delete restrict,
  source_receipt_id bigint not null
    references public.reward_receipts(id) on delete restrict,
  source_invite_code text not null
    references public.invitations(invite_code) on delete restrict,
  amount_wei numeric(78,0) not null
    check (amount_wei > 0 and amount_wei = trunc(amount_wei)),
  status text not null default 'ACTIVE'
    check (status in ('ACTIVE','REVERSED','FROZEN')),
  status_reason text,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  unique (network, source_invalidation_id, source_receipt_id)
);

create index if not exists reward_recovery_obligations_wallet_idx
  on public.reward_recovery_obligations(network, recipient_wallet, status);

create table if not exists public.reward_recovery_settlements (
  id uuid primary key default gen_random_uuid(),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  invite_code text not null unique
    references public.invitations(invite_code) on delete restrict,
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  settlement_kind text not null
    check (settlement_kind in ('FULL_OFFSET','PARTIAL_OFFSET')),
  state text not null default 'ACTIVE'
    check (state in ('ACTIVE','INVALIDATED','REVIEW')),
  gross_amount_wei numeric(78,0) not null
    check (gross_amount_wei > 0 and gross_amount_wei = trunc(gross_amount_wei)),
  offset_amount_wei numeric(78,0) not null
    check (offset_amount_wei > 0 and offset_amount_wei = trunc(offset_amount_wei)),
  net_amount_wei numeric(78,0) not null
    check (net_amount_wei >= 0 and net_amount_wei = trunc(net_amount_wei)),
  sybil_clearance_id uuid
    references public.sybil_v2_reward_clearances(id) on delete restrict,
  completion_block bigint not null check (completion_block >= 0),
  completion_tx_index integer not null check (completion_tx_index >= 0),
  completion_clause_index integer not null check (completion_clause_index >= 0),
  completion_tx_id text not null check (completion_tx_id ~ '^0x[0-9a-f]{64}$'),
  settled_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  check (gross_amount_wei = offset_amount_wei + net_amount_wei),
  check (
    (settlement_kind = 'FULL_OFFSET' and net_amount_wei = 0)
    or
    (settlement_kind = 'PARTIAL_OFFSET' and net_amount_wei > 0)
  )
);

create index if not exists reward_recovery_settlements_wallet_idx
  on public.reward_recovery_settlements(network, recipient_wallet, state);

create table if not exists public.reward_recovery_allocations (
  id bigint generated by default as identity primary key,
  settlement_id uuid not null
    references public.reward_recovery_settlements(id) on delete restrict,
  obligation_id uuid not null
    references public.reward_recovery_obligations(id) on delete restrict,
  amount_wei numeric(78,0) not null
    check (amount_wei > 0 and amount_wei = trunc(amount_wei)),
  created_at timestamptz not null default clock_timestamp(),
  unique (settlement_id, obligation_id)
);

create index if not exists reward_recovery_allocations_obligation_idx
  on public.reward_recovery_allocations(obligation_id);

create table if not exists public.reward_recovery_review_queue (
  id uuid primary key default gen_random_uuid(),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  invite_code text,
  obligation_id uuid references public.reward_recovery_obligations(id) on delete restrict,
  settlement_id uuid references public.reward_recovery_settlements(id) on delete restrict,
  reason_kind text not null
    check (reason_kind in (
      'SOURCE_INVALIDATION_REINSTATED_AFTER_CONSUMPTION',
      'SETTLEMENT_INVALIDATION_REINSTATED'
    )),
  status text not null default 'OPEN' check (status in ('OPEN','RESOLVED')),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default clock_timestamp(),
  resolved_at timestamptz,
  unique (reason_kind, obligation_id, settlement_id)
);

alter table public.reward_recovery_obligations enable row level security;
alter table public.reward_recovery_settlements enable row level security;
alter table public.reward_recovery_allocations enable row level security;
alter table public.reward_recovery_review_queue enable row level security;

revoke all on public.reward_recovery_obligations from public, anon, authenticated;
revoke all on public.reward_recovery_settlements from public, anon, authenticated;
revoke all on public.reward_recovery_allocations from public, anon, authenticated;
revoke all on public.reward_recovery_review_queue from public, anon, authenticated;

grant select on public.reward_recovery_obligations to service_role;
grant select on public.reward_recovery_settlements to service_role;
grant select on public.reward_recovery_allocations to service_role;
grant select on public.reward_recovery_review_queue to service_role;

create or replace function public.prevent_reward_recovery_allocation_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  raise exception 'REWARD_RECOVERY_ALLOCATION_APPEND_ONLY';
end;
$$;

revoke all on function public.prevent_reward_recovery_allocation_mutation()
  from public, anon, authenticated, service_role;

drop trigger if exists reward_recovery_allocations_append_only
  on public.reward_recovery_allocations;
create trigger reward_recovery_allocations_append_only
before update or delete on public.reward_recovery_allocations
for each row execute function public.prevent_reward_recovery_allocation_mutation();

insert into public.reward_recovery_obligations(
  network,
  recipient_wallet,
  source_invalidation_id,
  source_receipt_id,
  source_invite_code,
  amount_wei,
  status,
  status_reason
)
select
  lower(r.network),
  lower(r.recipient_wallet),
  x.id,
  r.id,
  r.invite_code,
  r.amount_wei,
  'ACTIVE',
  'ACTIVE_HISTORICAL_REFERRAL_INVALIDATION'
from public.sybil_v2_referral_invalidations x
join public.reward_receipts r
  on r.invite_code = x.invite_code
 and lower(r.network) = lower(x.network)
where x.status = 'ACTIVE'
  and r.amount_wei > 0
on conflict (network, source_invalidation_id, source_receipt_id)
do nothing;

create or replace function public.read_reward_recovery_balance_wei(
  p_network text,
  p_recipient_wallet text
)
returns numeric
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  with consumed as (
    select
      a.obligation_id,
      coalesce(sum(a.amount_wei),0)::numeric as consumed_wei
    from public.reward_recovery_allocations a
    join public.reward_recovery_settlements s
      on s.id = a.settlement_id
     and s.state = 'ACTIVE'
    group by a.obligation_id
  )
  select coalesce(sum(
    greatest(o.amount_wei - coalesce(c.consumed_wei,0),0)
  ),0)::numeric
  from public.reward_recovery_obligations o
  left join consumed c on c.obligation_id = o.id
  where o.network = lower(btrim(p_network))
    and o.recipient_wallet = lower(btrim(p_recipient_wallet))
    and o.status = 'ACTIVE';
$$;

revoke all on function public.read_reward_recovery_balance_wei(text,text)
  from public, anon, authenticated;
grant execute on function public.read_reward_recovery_balance_wei(text,text)
  to service_role;

create or replace view public.operator_reward_recovery_balances
with (security_invoker = true)
as
select
  o.network,
  o.recipient_wallet,
  count(*) filter (where o.status = 'ACTIVE')::bigint as active_obligation_count,
  coalesce(sum(o.amount_wei) filter (where o.status = 'ACTIVE'),0)::numeric as active_obligation_wei,
  public.read_reward_recovery_balance_wei(o.network,o.recipient_wallet) as remaining_recovery_wei,
  (
    select count(*)::bigint
    from public.reward_recovery_review_queue q
    where q.network = o.network
      and q.recipient_wallet = o.recipient_wallet
      and q.status = 'OPEN'
  ) as open_review_count
from public.reward_recovery_obligations o
group by o.network,o.recipient_wallet;

revoke all on public.operator_reward_recovery_balances
  from public, anon, authenticated;
grant select on public.operator_reward_recovery_balances to service_role;

create or replace function public.sync_reward_recovery_invalidation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_obligation public.reward_recovery_obligations%rowtype;
  v_consumed numeric(78,0) := 0;
  v_settlement public.reward_recovery_settlements%rowtype;
begin
  if new.status = 'ACTIVE' then
    insert into public.reward_recovery_obligations(
      network,recipient_wallet,source_invalidation_id,source_receipt_id,
      source_invite_code,amount_wei,status,status_reason
    )
    select
      lower(r.network),lower(r.recipient_wallet),new.id,r.id,r.invite_code,
      r.amount_wei,'ACTIVE','ACTIVE_REFERRAL_INVALIDATION'
    from public.reward_receipts r
    where r.invite_code = new.invite_code
      and lower(r.network) = lower(new.network)
      and r.amount_wei > 0
    on conflict (network,source_invalidation_id,source_receipt_id)
    do update set
      status='ACTIVE',
      status_reason='REFERRAL_REINVALIDATED',
      updated_at=clock_timestamp();

    update public.reward_recovery_settlements s
    set
      state='INVALIDATED',
      updated_at=clock_timestamp()
    where s.network=lower(new.network)
      and s.invite_code=new.invite_code
      and s.state='ACTIVE';

    return new;
  end if;

  if new.status = 'REINSTATED' then
    for v_obligation in
      select *
      from public.reward_recovery_obligations o
      where o.source_invalidation_id = new.id
      for update
    loop
      select coalesce(sum(a.amount_wei),0)
      into v_consumed
      from public.reward_recovery_allocations a
      join public.reward_recovery_settlements s
        on s.id=a.settlement_id
       and s.state='ACTIVE'
      where a.obligation_id=v_obligation.id;

      if v_consumed > 0 then
        update public.reward_recovery_obligations
        set
          status='FROZEN',
          status_reason='SOURCE_INVALIDATION_REINSTATED_AFTER_CONSUMPTION',
          updated_at=clock_timestamp()
        where id=v_obligation.id;

        insert into public.reward_recovery_review_queue(
          network,recipient_wallet,invite_code,obligation_id,settlement_id,
          reason_kind,details
        ) values (
          v_obligation.network,
          v_obligation.recipient_wallet,
          v_obligation.source_invite_code,
          v_obligation.id,
          null,
          'SOURCE_INVALIDATION_REINSTATED_AFTER_CONSUMPTION',
          jsonb_build_object(
            'consumedWei',v_consumed::text,
            'obligationWei',v_obligation.amount_wei::text,
            'invalidationId',new.id::text
          )
        )
        on conflict (reason_kind,obligation_id,settlement_id) do nothing;
      else
        update public.reward_recovery_obligations
        set
          status='REVERSED',
          status_reason='SOURCE_INVALIDATION_REINSTATED_BEFORE_CONSUMPTION',
          updated_at=clock_timestamp()
        where id=v_obligation.id;
      end if;
    end loop;

    select *
    into v_settlement
    from public.reward_recovery_settlements s
    where s.network=lower(new.network)
      and s.invite_code=new.invite_code
      and s.state='INVALIDATED'
    for update;

    if found then
      update public.reward_recovery_settlements
      set state='REVIEW',updated_at=clock_timestamp()
      where id=v_settlement.id;

      insert into public.reward_recovery_review_queue(
        network,recipient_wallet,invite_code,obligation_id,settlement_id,
        reason_kind,details
      ) values (
        v_settlement.network,
        v_settlement.recipient_wallet,
        v_settlement.invite_code,
        null,
        v_settlement.id,
        'SETTLEMENT_INVALIDATION_REINSTATED',
        jsonb_build_object(
          'grossWei',v_settlement.gross_amount_wei::text,
          'offsetWei',v_settlement.offset_amount_wei::text,
          'netWei',v_settlement.net_amount_wei::text,
          'invalidationId',new.id::text
        )
      )
      on conflict (reason_kind,obligation_id,settlement_id) do nothing;
    end if;
  end if;

  return new;
end;
$$;

revoke all on function public.sync_reward_recovery_invalidation()
  from public, anon, authenticated, service_role;

drop trigger if exists sybil_v2_reward_recovery_sync
  on public.sybil_v2_referral_invalidations;
create trigger sybil_v2_reward_recovery_sync
after insert or update of status
on public.sybil_v2_referral_invalidations
for each row execute function public.sync_reward_recovery_invalidation();

create or replace function public.read_reward_cohort_committed_wei(
  p_network text,
  p_app_id text,
  p_reward_cohort_round_id bigint,
  p_allocation_receipt_id bigint
)
returns numeric
language plpgsql
stable
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_receipt public.vebetter_round_allocations%rowtype;
  v_queue_committed numeric(78,0) := 0;
  v_offset_committed numeric(78,0) := 0;
begin
  p_network := lower(btrim(p_network));
  p_app_id := lower(btrim(p_app_id));

  if p_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'unsupported network';
  end if;
  if p_reward_cohort_round_id is null or p_reward_cohort_round_id < 1 then
    raise exception 'invalid reward cohort round';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id=p_allocation_receipt_id
    and a.network=p_network
    and a.app_id=p_app_id;

  if not found
     or v_receipt.vebetter_round_id + 1 <> p_reward_cohort_round_id then
    raise exception 'allocation receipt does not fund the requested reward cohort';
  end if;

  select coalesce(sum(q.reserved_amount_wei),0)
  into v_queue_committed
  from public.reward_queue_entries q
  join public.invitations i on i.invite_code=q.invite_code
  where q.network=p_network
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=p_reward_cohort_round_id
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED');

  select coalesce(sum(s.offset_amount_wei),0)
  into v_offset_committed
  from public.reward_recovery_settlements s
  join public.invitations i on i.invite_code=s.invite_code
  where s.network=p_network
    and s.state='ACTIVE'
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=p_reward_cohort_round_id;

  return v_queue_committed + v_offset_committed;
end;
$$;

revoke all on function public.read_reward_cohort_committed_wei(text,text,bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.read_reward_cohort_committed_wei(text,text,bigint,bigint)
  to service_role;

create or replace function public.enforce_reward_queue_cohort_budget()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_invitation public.invitations%rowtype;
  v_receipt public.vebetter_round_allocations%rowtype;
  v_adjustment numeric(78,0) := 0;
  v_existing_queue numeric(78,0) := 0;
  v_existing_offset numeric(78,0) := 0;
  v_current_offset numeric(78,0) := 0;
  v_budget numeric(78,0) := 0;
begin
  if new.reserved_amount_wei is null then return new; end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=new.invite_code;

  if not found
     or v_invitation.reward_cohort_round_id is null
     or v_invitation.reward_funding_allocation_receipt_id is null then
    raise exception 'REWARD_COHORT_BINDING_REQUIRED';
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id=v_invitation.reward_funding_allocation_receipt_id;

  if not found
     or v_receipt.network<>new.network
     or v_receipt.vebetter_round_id + 1<>v_invitation.reward_cohort_round_id then
    raise exception 'REWARD_COHORT_FUNDING_MISMATCH';
  end if;

  select coalesce(sum(a.amount_wei),0)
  into v_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network=v_receipt.network
    and a.app_id=v_receipt.app_id
    and a.reward_cohort_round_id=v_invitation.reward_cohort_round_id
    and a.allocation_receipt_id=v_receipt.id;

  v_budget := v_receipt.rewards_allocation_amount_wei + v_adjustment;

  select coalesce(sum(q.reserved_amount_wei),0)
  into v_existing_queue
  from public.reward_queue_entries q
  join public.invitations i on i.invite_code=q.invite_code
  where q.network=new.network
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=v_invitation.reward_cohort_round_id
    and q.invite_code<>new.invite_code
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED');

  select coalesce(sum(s.offset_amount_wei),0)
  into v_existing_offset
  from public.reward_recovery_settlements s
  join public.invitations i on i.invite_code=s.invite_code
  where s.network=new.network
    and s.state='ACTIVE'
    and s.invite_code<>new.invite_code
    and i.reward_funding_allocation_receipt_id=v_receipt.id
    and i.reward_cohort_round_id=v_invitation.reward_cohort_round_id;

  select coalesce(s.offset_amount_wei,0)
  into v_current_offset
  from public.reward_recovery_settlements s
  where s.invite_code=new.invite_code
    and s.network=new.network
    and s.state='ACTIVE';

  if not found then v_current_offset := 0; end if;

  if v_existing_queue + v_existing_offset
     + new.reserved_amount_wei + v_current_offset > v_budget then
    raise exception 'REWARD_COHORT_BUDGET_EXCEEDED';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_reward_queue_cohort_budget()
  from public, anon, authenticated;
grant execute on function public.enforce_reward_queue_cohort_budget()
  to service_role;

create or replace function public.commit_reward_reservation(
  p_invite_code text,
  p_network text,
  p_observed_pool_balance_wei numeric,
  p_expected_reserved_before_wei numeric,
  p_amount_wei numeric,
  p_algorithm_version text,
  p_quote_snapshot_id bigint,
  p_finalized_block bigint,
  p_basis jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_code text := upper(btrim(p_invite_code));
  v_network text := lower(btrim(p_network));
  v_invitation public.invitations%rowtype;
  v_queue public.reward_queue_entries%rowtype;
  v_clearance public.sybil_v2_reward_clearances%rowtype;
  v_existing_settlement public.reward_recovery_settlements%rowtype;
  v_settlement public.reward_recovery_settlements%rowtype;
  v_receipt public.vebetter_round_allocations%rowtype;
  v_obligation record;
  v_entry_class text;
  v_reserved numeric(78,0) := 0;
  v_legacy_payout_reserved numeric(78,0) := 0;
  v_recovery_balance numeric(78,0) := 0;
  v_offset numeric(78,0) := 0;
  v_net numeric(78,0) := 0;
  v_remaining_offset numeric(78,0) := 0;
  v_take numeric(78,0) := 0;
  v_cohort_committed numeric(78,0) := 0;
  v_adjustment numeric(78,0) := 0;
  v_budget numeric(78,0) := 0;
  v_completion_block bigint;
  v_completion_tx_index integer;
  v_completion_clause_index integer;
  v_completion_tx_id text;
  v_mainnet_enabled boolean;
  v_emergency_paused boolean;
  v_sybil_v2_enforced boolean := false;
  v_recovery_enabled boolean := false;
  v_now timestamptz := clock_timestamp();
  v_basis jsonb;
begin
  if v_code is null or v_code='' then raise exception 'INVITE_CODE_REQUIRED'; end if;
  if v_network not in ('mainnet','testnet','testnet-staging') then raise exception 'UNSUPPORTED_NETWORK'; end if;
  if p_observed_pool_balance_wei is null or p_observed_pool_balance_wei<0 or p_observed_pool_balance_wei<>trunc(p_observed_pool_balance_wei) then raise exception 'INVALID_OBSERVED_POOL_BALANCE'; end if;
  if p_expected_reserved_before_wei is null or p_expected_reserved_before_wei<0 or p_expected_reserved_before_wei<>trunc(p_expected_reserved_before_wei) then raise exception 'INVALID_EXPECTED_RESERVED'; end if;
  if p_amount_wei is null or p_amount_wei<=0 or p_amount_wei<>trunc(p_amount_wei) then raise exception 'INVALID_REWARD_AMOUNT'; end if;
  if p_finalized_block is null or p_finalized_block<0 then raise exception 'INVALID_FINALIZED_BLOCK'; end if;
  if p_algorithm_version is null or length(btrim(p_algorithm_version)) not between 1 and 80 then raise exception 'INVALID_ALGORITHM_VERSION'; end if;
  if p_basis is null or jsonb_typeof(p_basis)<>'object' then raise exception 'INVALID_RESERVATION_BASIS'; end if;

  perform pg_advisory_xact_lock(hashtextextended('veinvite_emergency_reward_pause',0));

  select
    mainnet_funded_rewards_enabled,
    emergency_rewards_paused,
    sybil_v2_enforcement_enabled,
    reward_recovery_enabled
  into
    v_mainnet_enabled,
    v_emergency_paused,
    v_sybil_v2_enforced,
    v_recovery_enabled
  from public.reward_runtime_config
  where id=1;

  if not found then raise exception 'REWARD_RUNTIME_CONFIG_MISSING'; end if;
  if v_emergency_paused then raise exception 'REWARD_RESERVATION_PAUSED'; end if;
  if v_network='mainnet' and not v_mainnet_enabled then raise exception 'REWARD_RESERVATION_DISABLED'; end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_reward_reservation_' || v_network,0)
  );

  select * into v_invitation
  from public.invitations i
  where i.invite_code=v_code
  for update;

  if not found
     or v_invitation.activation_network<>v_network
     or v_invitation.status<>'COMPLETED'
     or v_invitation.reward_status<>'ELIGIBLE'
     or v_invitation.reward_eligible_at is null
     or v_invitation.sybil_status<>'CLEAR'
     or v_invitation.sybil_checked_at is null
     or v_invitation.impact_sync_complete_at is null
     or v_invitation.inviter_wallet is null
     or v_invitation.invitee_wallet is null
     or v_invitation.eligibility_check_id is null then
    return jsonb_build_object('reserved',false,'reason','NOT_ELIGIBLE');
  end if;

  select c.* into v_clearance
  from public.sybil_v2_reward_clearances c
  join public.sybil_v2_referral_assessments a
    on a.invite_code=c.invite_code
   and a.revision=c.assessment_revision
   and a.state=c.verdict
  where c.invite_code=v_code
    and c.network=v_network
    and c.verdict='CLEAR';

  if v_sybil_v2_enforced and not found then
    return jsonb_build_object('reserved',false,'reason','SYBIL_V2_CLEARANCE_MISSING');
  end if;

  if v_sybil_v2_enforced and exists (
    select 1
    from public.sybil_v2_wallet_restrictions r
    where r.network=v_network
      and r.status='ACTIVE'
      and r.wallet_address in (
        lower(v_invitation.inviter_wallet),
        lower(v_invitation.invitee_wallet)
      )
  ) then
    return jsonb_build_object('reserved',false,'reason','SYBIL_V2_RESTRICTED');
  end if;

  if exists (
    select 1
    from public.reward_reservation_legacy_exclusions x
    where x.invite_code=v_code
  ) then
    return jsonb_build_object('reserved',false,'reason','LEGACY_EXCLUDED');
  end if;

  select * into v_queue
  from public.reward_queue_entries q
  where q.invite_code=v_code
  for update;

  if found then
    if v_queue.reserved_amount_wei is not null then
      return jsonb_build_object(
        'reserved',true,
        'reason','ALREADY_RESERVED',
        'inviteCode',v_queue.invite_code,
        'amountWei',v_queue.reserved_amount_wei::text,
        'reservedAt',v_queue.reserved_at,
        'status',v_queue.status
      );
    end if;
    return jsonb_build_object('reserved',false,'reason','LEGACY_QUEUE_ENTRY');
  end if;

  select * into v_existing_settlement
  from public.reward_recovery_settlements s
  where s.invite_code=v_code
  for update;

  if found then
    return jsonb_build_object(
      'reserved',true,
      'reason','ALREADY_RECOVERY_SETTLED',
      'inviteCode',v_existing_settlement.invite_code,
      'amountWei',v_existing_settlement.net_amount_wei::text,
      'reservedAt',v_existing_settlement.settled_at,
      'status',case
        when v_existing_settlement.net_amount_wei=0 then 'RECOVERY_SETTLED'
        else 'AWAITING_CLAIM'
      end
    );
  end if;

  select
    e.block_number::bigint,
    e.tx_index::integer,
    e.clause_index::integer,
    lower(e.tx_id)
  into
    v_completion_block,
    v_completion_tx_index,
    v_completion_clause_index,
    v_completion_tx_id
  from public.invite_impact_events e
  where e.invite_code=v_code
    and e.network=v_network
    and e.event_type in ('DAPP_REWARD','VOT3_CONVERSION','ALLOCATION_VOTE')
    and e.block_number is not null
    and e.tx_index is not null
    and e.clause_index is not null
    and e.tx_id ~ '^0x[0-9a-fA-F]{64}$'
  order by e.block_number desc,e.tx_index desc,e.clause_index desc
  limit 1;

  if v_completion_block is null
     or v_completion_tx_index is null
     or v_completion_clause_index is null
     or v_completion_tx_id is null then
    return jsonb_build_object('reserved',false,'reason','COMPLETION_POSITION_MISSING');
  end if;

  if v_completion_block>p_finalized_block then
    return jsonb_build_object(
      'reserved',false,
      'reason','AWAITING_FINALITY',
      'completionBlock',v_completion_block,
      'finalizedBlock',p_finalized_block
    );
  end if;

  select e.entry_class into v_entry_class
  from public.eligibility_check_events e
  where e.id=v_invitation.eligibility_check_id
    and e.invite_code=v_code
    and e.wallet_address=lower(v_invitation.invitee_wallet)
    and e.network=v_network
    and e.outcome='ELIGIBLE'
    and e.entry_class in ('NEW','RETURNING');

  if v_entry_class not in ('NEW','RETURNING') then
    return jsonb_build_object('reserved',false,'reason','ENTRY_PROOF_MISSING');
  end if;

  select coalesce(sum(q.reserved_amount_wei),0)
  into v_reserved
  from public.reward_queue_entries q
  where q.network=v_network
    and q.reserved_amount_wei is not null
    and q.status in ('AWAITING_CLAIM','QUEUED','ASSIGNED')
    and not exists (
      select 1
      from public.reward_payouts paid
      where paid.invite_code=q.invite_code
        and paid.status='PAID'
    );

  select coalesce(sum(rp.amount_wei),0)
  into v_legacy_payout_reserved
  from public.reward_payouts rp
  join public.reward_rounds rr on rr.id=rp.round_id
  where rr.network=v_network
    and rp.status in ('PENDING','SENDING','FAILED')
    and not exists (
      select 1
      from public.reward_queue_entries q
      where q.invite_code=rp.invite_code
        and q.reserved_amount_wei is not null
    );

  v_reserved := v_reserved + v_legacy_payout_reserved;

  if v_reserved<>p_expected_reserved_before_wei then
    return jsonb_build_object(
      'reserved',false,
      'reason','RECALCULATE',
      'reservedExistingWei',v_reserved::text
    );
  end if;

  select * into v_receipt
  from public.vebetter_round_allocations a
  where a.id=v_invitation.reward_funding_allocation_receipt_id;

  if not found
     or v_receipt.network<>v_network
     or v_receipt.vebetter_round_id + 1<>v_invitation.reward_cohort_round_id then
    raise exception 'REWARD_COHORT_FUNDING_MISMATCH';
  end if;

  select coalesce(sum(a.amount_wei),0)
  into v_adjustment
  from public.reward_cohort_funding_adjustments a
  where a.network=v_receipt.network
    and a.app_id=v_receipt.app_id
    and a.reward_cohort_round_id=v_invitation.reward_cohort_round_id
    and a.allocation_receipt_id=v_receipt.id;

  v_budget := v_receipt.rewards_allocation_amount_wei + v_adjustment;
  v_cohort_committed := public.read_reward_cohort_committed_wei(
    v_network,
    v_receipt.app_id,
    v_invitation.reward_cohort_round_id,
    v_receipt.id
  );

  if v_cohort_committed + p_amount_wei > v_budget then
    return jsonb_build_object(
      'reserved',false,
      'reason','RECALCULATE',
      'cohortCommittedWei',v_cohort_committed::text,
      'cohortBudgetWei',v_budget::text
    );
  end if;

  v_net := p_amount_wei;

  if v_recovery_enabled then
    perform pg_advisory_xact_lock(
      hashtextextended(
        'veinvite_reward_recovery_' || v_network || '_' || lower(v_invitation.inviter_wallet),
        0
      )
    );

    v_recovery_balance := public.read_reward_recovery_balance_wei(
      v_network,
      lower(v_invitation.inviter_wallet)
    );
    v_offset := least(p_amount_wei,v_recovery_balance);
    v_net := p_amount_wei - v_offset;
  end if;

  if v_net>greatest(p_observed_pool_balance_wei-v_reserved,0) then
    return jsonb_build_object(
      'reserved',false,
      'reason','RECALCULATE',
      'reservedExistingWei',v_reserved::text,
      'availableWei',greatest(p_observed_pool_balance_wei-v_reserved,0)::text
    );
  end if;

  v_basis := p_basis || jsonb_build_object(
    'observedPoolBalanceWei',p_observed_pool_balance_wei::text,
    'reservedBeforeWei',v_reserved::text,
    'finalizedBlock',p_finalized_block,
    'sybilV2Enforced',v_sybil_v2_enforced,
    'sybilClearanceId',case when v_sybil_v2_enforced then v_clearance.id::text else null end,
    'sybilVerdict',case when v_sybil_v2_enforced then v_clearance.verdict else null end,
    'sybilAssessmentRevision',case when v_sybil_v2_enforced then v_clearance.assessment_revision else null end
  );

  if v_offset>0 then
    insert into public.reward_recovery_settlements(
      network,invite_code,recipient_wallet,settlement_kind,state,
      gross_amount_wei,offset_amount_wei,net_amount_wei,sybil_clearance_id,
      completion_block,completion_tx_index,completion_clause_index,completion_tx_id,
      settled_at,updated_at
    ) values (
      v_network,
      v_code,
      lower(v_invitation.inviter_wallet),
      case when v_net=0 then 'FULL_OFFSET' else 'PARTIAL_OFFSET' end,
      'ACTIVE',
      p_amount_wei,
      v_offset,
      v_net,
      case when v_sybil_v2_enforced then v_clearance.id else null end,
      v_completion_block,
      v_completion_tx_index,
      v_completion_clause_index,
      v_completion_tx_id,
      v_now,
      v_now
    )
    returning * into v_settlement;

    v_remaining_offset := v_offset;

    for v_obligation in
      with consumed as (
        select
          a.obligation_id,
          coalesce(sum(a.amount_wei),0)::numeric as consumed_wei
        from public.reward_recovery_allocations a
        join public.reward_recovery_settlements s
          on s.id=a.settlement_id
         and s.state='ACTIVE'
        group by a.obligation_id
      )
      select
        o.id,
        greatest(o.amount_wei-coalesce(c.consumed_wei,0),0)::numeric as remaining_wei
      from public.reward_recovery_obligations o
      left join consumed c on c.obligation_id=o.id
      where o.network=v_network
        and o.recipient_wallet=lower(v_invitation.inviter_wallet)
        and o.status='ACTIVE'
        and greatest(o.amount_wei-coalesce(c.consumed_wei,0),0)>0
      order by o.created_at,o.id
    loop
      exit when v_remaining_offset<=0;
      v_take := least(v_remaining_offset,v_obligation.remaining_wei);

      insert into public.reward_recovery_allocations(
        settlement_id,obligation_id,amount_wei
      ) values (
        v_settlement.id,v_obligation.id,v_take
      );

      v_remaining_offset := v_remaining_offset-v_take;
    end loop;

    if v_remaining_offset<>0 then
      raise exception 'REWARD_RECOVERY_ALLOCATION_MISMATCH';
    end if;

    v_basis := v_basis || jsonb_build_object(
      'recoverySettlementId',v_settlement.id::text,
      'grossRewardWei',p_amount_wei::text,
      'recoveryOffsetWei',v_offset::text,
      'netPayableWei',v_net::text
    );
  end if;

  if v_net>0 then
    insert into public.reward_queue_entries(
      invite_code,recipient_wallet,eligibility_check_id,entry_class,network,eligible_at,status,
      reserved_amount_wei,reserved_at,reservation_algorithm_version,reservation_quote_snapshot_id,
      reservation_completion_block,reservation_completion_tx_index,reservation_completion_clause_index,
      reservation_basis,sybil_clearance_id
    ) values (
      v_code,
      lower(v_invitation.inviter_wallet),
      v_invitation.eligibility_check_id,
      v_entry_class,
      v_network,
      v_invitation.reward_eligible_at,
      'AWAITING_CLAIM',
      v_net,
      v_now,
      btrim(p_algorithm_version),
      p_quote_snapshot_id,
      v_completion_block,
      v_completion_tx_index,
      v_completion_clause_index,
      v_basis,
      case when v_sybil_v2_enforced then v_clearance.id else null end
    )
    returning * into v_queue;

    return jsonb_build_object(
      'reserved',true,
      'reason',case when v_offset>0 then 'RECOVERY_PARTIAL_RESERVED' else 'RESERVED' end,
      'inviteCode',v_queue.invite_code,
      'amountWei',v_queue.reserved_amount_wei::text,
      'reservedAt',v_queue.reserved_at,
      'status',v_queue.status,
      'completionBlock',v_queue.reservation_completion_block,
      'completionTxIndex',v_queue.reservation_completion_tx_index,
      'completionClauseIndex',v_queue.reservation_completion_clause_index,
      'sybilClearanceId',v_queue.sybil_clearance_id
    );
  end if;

  if v_offset<=0 or v_settlement.id is null then
    raise exception 'REWARD_RECOVERY_FULL_OFFSET_STATE_INVALID';
  end if;

  update public.invitations i
  set slot_released_at=coalesce(i.slot_released_at,v_now)
  where i.invite_code=v_code
    and i.status='COMPLETED';

  insert into public.invite_notification_history(
    inviter_wallet,recipient_wallet,invite_code,kind,stage,event_at,
    reward_amount_wei,dapp_progress,collapsed_progress,friend_wallet,dedupe_key
  ) values (
    lower(v_invitation.inviter_wallet),
    lower(v_invitation.inviter_wallet),
    v_code,
    'REWARD_ADJUSTED',
    4,
    v_now,
    null,
    null,
    false,
    lower(v_invitation.invitee_wallet),
    'reward-recovery-adjusted:' || v_settlement.id::text
  )
  on conflict (dedupe_key) do nothing;

  return jsonb_build_object(
    'reserved',true,
    'reason','RECOVERY_FULLY_SETTLED',
    'inviteCode',v_code,
    'amountWei','0',
    'reservedAt',v_now,
    'status','RECOVERY_SETTLED',
    'completionBlock',v_completion_block,
    'completionTxIndex',v_completion_tx_index,
    'completionClauseIndex',v_completion_clause_index,
    'sybilClearanceId',case when v_sybil_v2_enforced then v_clearance.id else null end
  );
end;
$$;

revoke all on function public.commit_reward_reservation(
  text,text,numeric,numeric,numeric,text,bigint,bigint,jsonb
) from public, anon, authenticated;
grant execute on function public.commit_reward_reservation(
  text,text,numeric,numeric,numeric,text,bigint,bigint,jsonb
) to service_role;

create or replace function public.read_reward_reservation_candidates_v2(
  p_network text,
  p_limit integer default 25
)
returns table(
  invite_code text,
  completion_block bigint,
  completion_tx_index integer,
  completion_clause_index integer,
  reward_cohort_round_id bigint,
  reward_funding_allocation_receipt_id bigint
)
language sql
stable
set search_path = pg_catalog, public
as $$
  with parameters as (
    select lower(btrim(p_network)) as network,
           greatest(1,least(coalesce(p_limit,25),100)) as row_limit
  )
  select
    i.invite_code,
    completion.block_number::bigint,
    completion.tx_index::integer,
    completion.clause_index::integer,
    i.reward_cohort_round_id,
    i.reward_funding_allocation_receipt_id
  from public.invitations i
  cross join parameters p
  left join public.sybil_v2_referral_assessments a
    on a.invite_code=i.invite_code
  left join public.sybil_v2_reward_clearances c
    on c.invite_code=i.invite_code
   and c.network=p.network
   and c.verdict='CLEAR'
   and c.verdict=a.state
   and c.assessment_revision=a.revision
  cross join lateral (
    select e.block_number,e.tx_index,e.clause_index
    from public.invite_impact_events e
    where e.invite_code=i.invite_code
      and e.network=p.network
      and e.event_type in ('DAPP_REWARD','VOT3_CONVERSION','ALLOCATION_VOTE')
      and e.block_number is not null
      and e.tx_index is not null
      and e.clause_index is not null
    order by e.block_number desc,e.tx_index desc,e.clause_index desc
    limit 1
  ) completion
  where i.activation_network=p.network
    and i.status='COMPLETED'
    and i.reward_status='ELIGIBLE'
    and i.reward_eligible_at is not null
    and i.sybil_status='CLEAR'
    and i.sybil_checked_at is not null
    and i.impact_sync_complete_at is not null
    and i.inviter_wallet is not null
    and i.invitee_wallet is not null
    and i.eligibility_check_id is not null
    and i.reward_cohort_round_id is not null
    and i.reward_funding_allocation_receipt_id is not null
    and (
      not public.sybil_v2_enforcement_enabled()
      or (a.state='CLEAR' and c.id is not null)
    )
    and (
      not public.sybil_v2_enforcement_enabled()
      or not exists (
        select 1
        from public.sybil_v2_wallet_restrictions r
        where r.network=p.network
          and r.status='ACTIVE'
          and r.wallet_address in (
            lower(i.inviter_wallet),
            lower(i.invitee_wallet)
          )
      )
    )
    and not exists (
      select 1 from public.reward_queue_entries q
      where q.invite_code=i.invite_code
    )
    and not exists (
      select 1 from public.reward_recovery_settlements s
      where s.invite_code=i.invite_code
    )
    and not exists (
      select 1 from public.reward_reservation_legacy_exclusions x
      where x.invite_code=i.invite_code
    )
  order by completion.block_number,completion.tx_index,completion.clause_index,i.invite_code
  limit (select row_limit from parameters);
$$;

revoke all on function public.read_reward_reservation_candidates_v2(text,integer)
  from public, anon, authenticated;
grant execute on function public.read_reward_reservation_candidates_v2(text,integer)
  to service_role;

create or replace function public.read_sybil_v2_cleared_unreserved_count(
  p_network text,
  p_reward_cohort_round_id bigint,
  p_allocation_receipt_id bigint
)
returns integer
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select count(*)::integer
  from public.invitations i
  left join public.sybil_v2_referral_assessments a
    on a.invite_code=i.invite_code
  left join public.sybil_v2_reward_clearances c
    on c.invite_code=i.invite_code
   and c.network=lower(btrim(p_network))
   and c.assessment_revision=a.revision
   and c.verdict='CLEAR'
   and c.verdict=a.state
  where i.activation_network=lower(btrim(p_network))
    and i.reward_cohort_round_id=p_reward_cohort_round_id
    and i.reward_funding_allocation_receipt_id=p_allocation_receipt_id
    and i.status='COMPLETED'
    and i.reward_status='ELIGIBLE'
    and i.reward_eligible_at is not null
    and (
      not public.sybil_v2_enforcement_enabled()
      or (a.state='CLEAR' and c.id is not null)
    )
    and not exists (
      select 1
      from public.reward_queue_entries q
      where q.invite_code=i.invite_code
        and q.reserved_amount_wei is not null
    )
    and not exists (
      select 1
      from public.reward_recovery_settlements s
      where s.invite_code=i.invite_code
    )
    and (
      not public.sybil_v2_enforcement_enabled()
      or not exists (
        select 1
        from public.sybil_v2_wallet_restrictions r
        where r.network=i.activation_network
          and r.status='ACTIVE'
          and r.wallet_address in (
            lower(i.inviter_wallet),
            lower(i.invitee_wallet)
          )
      )
    )
    and not exists (
      select 1
      from public.reward_reservation_legacy_exclusions x
      where x.invite_code=i.invite_code
    );
$$;

revoke all on function public.read_sybil_v2_cleared_unreserved_count(text,bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.read_sybil_v2_cleared_unreserved_count(text,bigint,bigint)
  to service_role;

alter table public.invite_notification_history
  drop constraint if exists invite_notification_history_kind_check;

alter table public.invite_notification_history
  add constraint invite_notification_history_kind_check
  check (kind = any(array[
    'INVITE_ACCEPTED'::text,
    'DAPP_PROGRESS'::text,
    'VOT3_CONVERTED'::text,
    'REWARD_READY'::text,
    'REWARD_PAID'::text,
    'REWARD_ADJUSTED'::text,
    'INVITE_INELIGIBLE'::text,
    'SECURITY_REVIEW_STARTED'::text,
    'SECURITY_REVIEW_CLEARED'::text,
    'SECURITY_POST_PAYOUT_REVIEW_STARTED'::text,
    'SECURITY_POST_PAYOUT_REVIEW_CLEARED'::text,
    'SECURITY_RESTRICTION_CONFIRMED'::text,
    'SECURITY_INVITER_WATCH'::text,
    'SECURITY_INVITER_HOLD'::text,
    'SECURITY_INVITER_RESTRICTED'::text,
    'SECURITY_INVITER_ACCESS_RESTORED'::text,
    'SECURITY_REFERRAL_INVALIDATED'::text,
    'SECURITY_REFERRAL_RESTORED'::text
  ]));

create or replace function public.get_lifetime_recognized_referral_ranking_v3_internal(
  p_network text,
  p_max_block bigint default null
)
returns table(
  rank_position bigint,
  wallet_address text,
  completed_referrals bigint,
  total_reward_wei numeric,
  reached_count_block bigint,
  reached_count_tx_index integer,
  reached_count_clause_index integer,
  reached_count_tx_id text
)
language sql
stable
set search_path = public
as $$
  with parameters as (
    select lower(btrim(p_network)) as network
  ),
  paid_referrals as (
    select
      lower(btrim(r.recipient_wallet)) as wallet_address,
      r.invite_code,
      r.amount_wei::numeric as amount_wei,
      q.reservation_completion_block as completion_block,
      q.reservation_completion_tx_index as completion_tx_index,
      q.reservation_completion_clause_index as completion_clause_index,
      lower(btrim(s.tx_id)) as proof_tx_id
    from public.reward_receipts r
    join public.reward_payout_transaction_settlements s
      on s.id=r.settlement_id
    join public.reward_queue_entries q
      on q.invite_code=r.invite_code
     and lower(btrim(q.recipient_wallet))=lower(btrim(r.recipient_wallet))
    cross join parameters p
    where lower(btrim(r.network))=p.network
      and lower(btrim(s.network))=p.network
      and lower(btrim(q.network))=p.network
      and r.amount_wei>0
      and q.reservation_completion_block is not null
      and q.reservation_completion_tx_index is not null
      and q.reservation_completion_clause_index is not null
      and (
        p_max_block is null
        or (
          s.block_number<=p_max_block
          and q.reservation_completion_block<=p_max_block
        )
      )
      and not public.is_analytics_excluded_wallet(r.recipient_wallet)
      and not public.is_analytics_excluded_invite_code(r.invite_code)
      and not public.is_sybil_v2_referral_invalidated(r.invite_code,p.network)
  ),
  full_offset_referrals as (
    select
      lower(btrim(s.recipient_wallet)) as wallet_address,
      s.invite_code,
      0::numeric as amount_wei,
      s.completion_block,
      s.completion_tx_index,
      s.completion_clause_index,
      lower(btrim(s.completion_tx_id)) as proof_tx_id
    from public.reward_recovery_settlements s
    cross join parameters p
    where s.network=p.network
      and s.state='ACTIVE'
      and s.settlement_kind='FULL_OFFSET'
      and s.net_amount_wei=0
      and (
        p_max_block is null
        or s.completion_block<=p_max_block
      )
      and not public.is_analytics_excluded_wallet(s.recipient_wallet)
      and not public.is_analytics_excluded_invite_code(s.invite_code)
      and not public.is_sybil_v2_referral_invalidated(s.invite_code,p.network)
  ),
  recognized as (
    select * from paid_referrals
    union all
    select * from full_offset_referrals
  ),
  deduped as (
    select distinct on (wallet_address,invite_code)
      wallet_address,invite_code,amount_wei,
      completion_block,completion_tx_index,completion_clause_index,proof_tx_id
    from recognized
    order by
      wallet_address,invite_code,
      completion_block asc,completion_tx_index asc,completion_clause_index asc,
      proof_tx_id asc
  ),
  totals as (
    select
      wallet_address,
      count(*)::bigint as completed_referrals,
      coalesce(sum(amount_wei),0)::numeric as total_reward_wei
    from deduped
    group by wallet_address
  ),
  reached as (
    select distinct on (wallet_address)
      wallet_address,
      completion_block as reached_count_block,
      completion_tx_index as reached_count_tx_index,
      completion_clause_index as reached_count_clause_index,
      proof_tx_id as reached_count_tx_id
    from deduped
    order by
      wallet_address,
      completion_block desc,
      completion_tx_index desc,
      completion_clause_index desc,
      invite_code desc
  ),
  ranked as (
    select
      row_number() over (
        order by
          t.completed_referrals desc,
          r.reached_count_block asc,
          r.reached_count_tx_index asc,
          r.reached_count_clause_index asc,
          t.wallet_address asc
      )::bigint as rank_position,
      t.wallet_address,
      t.completed_referrals,
      t.total_reward_wei,
      r.reached_count_block,
      r.reached_count_tx_index,
      r.reached_count_clause_index,
      r.reached_count_tx_id
    from totals t
    join reached r using (wallet_address)
  )
  select * from ranked order by rank_position;
$$;

revoke all on function public.get_lifetime_recognized_referral_ranking_v3_internal(text,bigint)
  from public, anon, authenticated;
grant execute on function public.get_lifetime_recognized_referral_ranking_v3_internal(text,bigint)
  to service_role;

create or replace function public.get_lifetime_referral_ranking_by_version(
  p_network text,
  p_max_block bigint,
  p_ranking_algorithm_version text
)
returns table(
  rank_position bigint,
  wallet_address text,
  completed_referrals bigint,
  total_reward_wei numeric,
  reached_count_block bigint,
  reached_count_tx_index integer,
  reached_count_clause_index integer,
  reached_count_tx_id text
)
language sql
stable
set search_path = public
as $$
  select *
  from public.get_lifetime_paid_referral_ranking_v2_internal(p_network,p_max_block)
  where p_ranking_algorithm_version='paid_referrals_v2'
  union all
  select *
  from public.get_lifetime_recognized_referral_ranking_v3_internal(p_network,p_max_block)
  where p_ranking_algorithm_version='recognized_referrals_v3';
$$;

revoke all on function public.get_lifetime_referral_ranking_by_version(text,bigint,text)
  from public, anon, authenticated;
grant execute on function public.get_lifetime_referral_ranking_by_version(text,bigint,text)
  to service_role;

create or replace function public.get_public_lifetime_leaderboard_v2(
  p_network text,
  p_wallet text default null,
  p_limit integer default 5,
  p_comparison_round_id bigint default null,
  p_ranking_algorithm_version text default 'recognized_referrals_v3'
)
returns table(
  rank_position bigint,
  wallet_address text,
  completed_referrals bigint,
  total_reward_wei text,
  is_current_wallet boolean,
  previous_rank bigint,
  rank_change bigint,
  rank_movement text
)
language sql
stable
set search_path = public
as $$
  with parameters as (
    select
      lower(nullif(btrim(coalesce(p_wallet,'')),'')) as current_wallet,
      greatest(1,least(coalesce(p_limit,5),100)) as entry_limit
  ),
  baseline as (
    select id
    from public.leaderboard_round_snapshots
    where lower(btrim(network))=lower(btrim(p_network))
      and round_id=p_comparison_round_id
      and ranking_algorithm_version=p_ranking_algorithm_version
    limit 1
  ),
  current_ranked as (
    select *
    from public.get_lifetime_referral_ranking_by_version(
      p_network,null,p_ranking_algorithm_version
    )
  )
  select
    c.rank_position,
    c.wallet_address,
    c.completed_referrals,
    c.total_reward_wei::text,
    c.wallet_address=p.current_wallet as is_current_wallet,
    prev.rank_position as previous_rank,
    case
      when b.id is null or prev.rank_position is null then null
      else prev.rank_position-c.rank_position
    end as rank_change,
    case
      when b.id is null then 'UNAVAILABLE'
      when prev.rank_position is null then 'NEW'
      when prev.rank_position>c.rank_position then 'UP'
      when prev.rank_position<c.rank_position then 'DOWN'
      else 'SAME'
    end as rank_movement
  from current_ranked c
  cross join parameters p
  left join baseline b on true
  left join public.leaderboard_round_snapshot_rows prev
    on prev.snapshot_id=b.id
   and prev.wallet_address=c.wallet_address
  where c.rank_position<=p.entry_limit
     or c.wallet_address=p.current_wallet
  order by c.rank_position;
$$;

revoke all on function public.get_public_lifetime_leaderboard_v2(
  text,text,integer,bigint,text
) from public, anon, authenticated;
grant execute on function public.get_public_lifetime_leaderboard_v2(
  text,text,integer,bigint,text
) to service_role;

insert into public.leaderboard_snapshot_activation(
  network,ranking_algorithm_version,activated_at
)
values
  ('mainnet','recognized_referrals_v3',clock_timestamp()),
  ('testnet','recognized_referrals_v3',clock_timestamp()),
  ('testnet-staging','recognized_referrals_v3',clock_timestamp())
on conflict (network,ranking_algorithm_version) do nothing;

create or replace function public.publish_leaderboard_round_snapshot_if_missing(
  p_network text,
  p_round_id bigint,
  p_round_end_block bigint,
  p_round_end_at timestamptz,
  p_ranking_algorithm_version text default 'recognized_referrals_v3'
)
returns jsonb
language plpgsql
set search_path to 'public','extensions'
as $$
declare
  v_network text := lower(btrim(p_network));
  v_activation timestamptz;
  v_existing public.leaderboard_round_snapshots%rowtype;
  v_snapshot_id bigint;
  v_published_at timestamptz;
  v_expected_count integer;
  v_actual_count integer;
  v_expected_hash text;
  v_actual_hash text;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'unsupported leaderboard network';
  end if;

  if p_ranking_algorithm_version not in (
    'paid_referrals_v2','recognized_referrals_v3'
  ) then
    raise exception 'unsupported leaderboard ranking algorithm version';
  end if;

  if p_round_id is null or p_round_id<1 then
    raise exception 'round_id must be positive';
  end if;
  if p_round_end_block is null or p_round_end_block<0 then
    raise exception 'round_end_block must be non-negative';
  end if;
  if p_round_end_at is null then
    raise exception 'round_end_at is required';
  end if;

  select activated_at into v_activation
  from public.leaderboard_snapshot_activation
  where network=v_network
    and ranking_algorithm_version=p_ranking_algorithm_version;

  if v_activation is null then
    raise exception 'leaderboard snapshot activation is missing';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_leaderboard_snapshot_' || v_network || '_' ||
      p_round_id::text || '_' || p_ranking_algorithm_version,
      0
    )
  );

  select * into v_existing
  from public.leaderboard_round_snapshots
  where network=v_network
    and round_id=p_round_id
    and ranking_algorithm_version=p_ranking_algorithm_version
  limit 1;

  if found then
    if v_existing.round_end_block<>p_round_end_block then
      raise exception 'existing leaderboard snapshot round end block does not match the reviewed chain';
    end if;
    return jsonb_build_object(
      'network',v_network,
      'roundId',p_round_id,
      'roundEndBlock',v_existing.round_end_block,
      'rankingAlgorithmVersion',p_ranking_algorithm_version,
      'ready',true,
      'created',false,
      'snapshotId',v_existing.id,
      'rowCount',v_existing.row_count,
      'publishedAt',v_existing.published_at
    );
  end if;

  if p_round_end_at<v_activation then
    return jsonb_build_object(
      'network',v_network,
      'roundId',p_round_id,
      'roundEndBlock',p_round_end_block,
      'rankingAlgorithmVersion',p_ranking_algorithm_version,
      'ready',false,
      'created',false,
      'snapshotId',null,
      'rowCount',null,
      'publishedAt',null,
      'reason','ROUND_PRECEDES_SNAPSHOT_ACTIVATION'
    );
  end if;

  if exists (
    select 1
    from public.reward_payout_transaction_submissions sub
    join public.reward_payout_manifest_chain_checkpoints cp
      on cp.manifest_id=sub.manifest_id
    join public.reward_rounds rr
      on rr.id=sub.round_id
    left join public.reward_payout_transaction_settlements settled
      on settled.manifest_id=sub.manifest_id
    where lower(btrim(sub.network))=v_network
      and lower(btrim(rr.network))=v_network
      and rr.status in ('CREATED','PAYING')
      and cp.block_number<=p_round_end_block
      and settled.id is null
  ) then
    return jsonb_build_object(
      'network',v_network,
      'roundId',p_round_id,
      'roundEndBlock',p_round_end_block,
      'rankingAlgorithmVersion',p_ranking_algorithm_version,
      'ready',false,
      'created',false,
      'snapshotId',null,
      'rowCount',null,
      'publishedAt',null,
      'reason','AWAITING_PRE_BOUNDARY_PAYOUT_FINALITY'
    );
  end if;

  if p_ranking_algorithm_version='paid_referrals_v2'
     and not exists (
       select 1
       from public.reward_payout_transaction_settlements s
       where lower(btrim(s.network))=v_network
         and s.block_number>p_round_end_block
     ) then
    return jsonb_build_object(
      'network',v_network,
      'roundId',p_round_id,
      'roundEndBlock',p_round_end_block,
      'rankingAlgorithmVersion',p_ranking_algorithm_version,
      'ready',false,
      'created',false,
      'snapshotId',null,
      'rowCount',null,
      'publishedAt',null,
      'reason','AWAITING_CURRENT_ROUND_PAID_ACTIVITY'
    );
  end if;

  select
    count(*)::integer,
    encode(
      extensions.digest(
        convert_to(
          coalesce(
            string_agg(
              concat_ws(
                '|',
                rank_position::text,
                wallet_address,
                completed_referrals::text,
                total_reward_wei::text,
                reached_count_block::text,
                reached_count_tx_index::text,
                reached_count_clause_index::text,
                reached_count_tx_id
              ),
              E'\n' order by rank_position
            ),
            ''
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    )
  into v_expected_count,v_expected_hash
  from public.get_lifetime_referral_ranking_by_version(
    v_network,p_round_end_block,p_ranking_algorithm_version
  );

  insert into public.leaderboard_round_snapshots(
    network,round_id,round_end_block,source_checked_through_block,
    ranking_algorithm_version,row_count,content_sha256
  ) values (
    v_network,p_round_id,p_round_end_block,p_round_end_block,
    p_ranking_algorithm_version,v_expected_count,v_expected_hash
  )
  returning id,published_at into v_snapshot_id,v_published_at;

  insert into public.leaderboard_round_snapshot_rows(
    snapshot_id,wallet_address,rank_position,completed_referrals,total_reward_wei,
    reached_count_block,reached_count_tx_id,reached_count_tx_index,reached_count_clause_index
  )
  select
    v_snapshot_id,wallet_address,rank_position,completed_referrals,total_reward_wei,
    reached_count_block,reached_count_tx_id,reached_count_tx_index,reached_count_clause_index
  from public.get_lifetime_referral_ranking_by_version(
    v_network,p_round_end_block,p_ranking_algorithm_version
  );

  select
    count(*)::integer,
    encode(
      extensions.digest(
        convert_to(
          coalesce(
            string_agg(
              concat_ws(
                '|',
                rank_position::text,
                wallet_address,
                completed_referrals::text,
                total_reward_wei::text,
                reached_count_block::text,
                reached_count_tx_index::text,
                reached_count_clause_index::text,
                reached_count_tx_id
              ),
              E'\n' order by rank_position
            ),
            ''
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    )
  into v_actual_count,v_actual_hash
  from public.leaderboard_round_snapshot_rows
  where snapshot_id=v_snapshot_id;

  if v_actual_count<>v_expected_count or v_actual_hash<>v_expected_hash then
    raise exception 'leaderboard snapshot validation failed for round %',p_round_id;
  end if;

  return jsonb_build_object(
    'network',v_network,
    'roundId',p_round_id,
    'roundEndBlock',p_round_end_block,
    'rankingAlgorithmVersion',p_ranking_algorithm_version,
    'ready',true,
    'created',true,
    'snapshotId',v_snapshot_id,
    'rowCount',v_expected_count,
    'publishedAt',v_published_at
  );
end;
$$;

revoke all on function public.publish_leaderboard_round_snapshot_if_missing(
  text,bigint,bigint,timestamptz,text
) from public, anon, authenticated;
grant execute on function public.publish_leaderboard_round_snapshot_if_missing(
  text,bigint,bigint,timestamptz,text
) to service_role;

commit;
