begin;

alter table public.reward_runtime_config
  add column if not exists emergency_rewards_paused boolean not null default false,
  add column if not exists emergency_pause_reason text,
  add column if not exists emergency_pause_changed_at timestamptz,
  add column if not exists emergency_pause_changed_by text,
  add column if not exists emergency_pause_network text;

alter table public.reward_runtime_config
  drop constraint if exists reward_runtime_config_emergency_reason_check,
  add constraint reward_runtime_config_emergency_reason_check
    check (
      emergency_pause_reason is null
      or char_length(btrim(emergency_pause_reason)) between 12 and 500
    ),
  drop constraint if exists reward_runtime_config_emergency_wallet_check,
  add constraint reward_runtime_config_emergency_wallet_check
    check (
      emergency_pause_changed_by is null
      or emergency_pause_changed_by ~ '^0x[0-9a-f]{40}$'
    ),
  drop constraint if exists reward_runtime_config_emergency_network_check,
  add constraint reward_runtime_config_emergency_network_check
    check (
      emergency_pause_network is null
      or emergency_pause_network in ('mainnet','testnet','testnet-staging')
    );

create table if not exists public.reward_emergency_pause_events (
  id bigint generated by default as identity primary key,
  paused boolean not null,
  reason text not null,
  operator_wallet text not null,
  network text not null,
  created_at timestamptz not null default now(),

  constraint reward_emergency_pause_events_reason_check
    check (char_length(btrim(reason)) between 12 and 500),
  constraint reward_emergency_pause_events_wallet_check
    check (operator_wallet ~ '^0x[0-9a-f]{40}$'),
  constraint reward_emergency_pause_events_network_check
    check (network in ('mainnet','testnet','testnet-staging'))
);

create index if not exists reward_emergency_pause_events_created_idx
  on public.reward_emergency_pause_events(created_at desc);

alter table public.reward_emergency_pause_events enable row level security;

revoke all on table public.reward_emergency_pause_events
  from public, anon, authenticated, service_role;
grant select on table public.reward_emergency_pause_events
  to service_role;

create or replace function public.set_reward_emergency_pause(
  p_paused boolean,
  p_reason text,
  p_operator_wallet text,
  p_network text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reason text := btrim(coalesce(p_reason, ''));
  v_wallet text := lower(btrim(coalesce(p_operator_wallet, '')));
  v_network text := lower(btrim(coalesce(p_network, '')));
  v_current boolean;
  v_now timestamptz := now();
begin
  if p_paused is null then
    raise exception 'paused state is required';
  end if;

  if char_length(v_reason) < 12 or char_length(v_reason) > 500 then
    raise exception 'pause/resume reason must be between 12 and 500 characters';
  end if;

  if v_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'operator wallet is invalid';
  end if;

  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'network is invalid';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_emergency_reward_pause', 0)
  );

  select emergency_rewards_paused
  into v_current
  from public.reward_runtime_config
  where id = 1
  for update;

  if not found then
    raise exception 'reward runtime configuration is missing';
  end if;

  if v_current = p_paused then
    return jsonb_build_object(
      'changed', false,
      'paused', v_current,
      'changedAt', null
    );
  end if;

  update public.reward_runtime_config
  set
    emergency_rewards_paused = p_paused,
    emergency_pause_reason = v_reason,
    emergency_pause_changed_at = v_now,
    emergency_pause_changed_by = v_wallet,
    emergency_pause_network = v_network,
    updated_at = v_now
  where id = 1;

  insert into public.reward_emergency_pause_events(
    paused,
    reason,
    operator_wallet,
    network,
    created_at
  ) values (
    p_paused,
    v_reason,
    v_wallet,
    v_network,
    v_now
  );

  return jsonb_build_object(
    'changed', true,
    'paused', p_paused,
    'changedAt', v_now
  );
end;
$$;

revoke all on function public.set_reward_emergency_pause(boolean, text, text, text)
  from public, anon, authenticated;
grant execute on function public.set_reward_emergency_pause(boolean, text, text, text)
  to service_role;

commit;
