-- VeInvite security-client identity gate v1
--
-- Goals:
-- 1. Record a pseudonymous browser/client -> verified wallet relationship.
-- 2. Keep this security identity completely separate from product analytics.
-- 3. Treat shared-client evidence as REVIEW only; never auto-BLOCK in v1.
-- 4. Invalidate stale CLEAR decisions only when a client becomes shared by wallets.
-- 5. Preserve auditable operator overrides until genuinely new evidence arrives.
-- 6. Keep all new security tables server-only and assessment history append-only.

begin;

alter table public.invitations
  add column if not exists identity_link_status text not null default 'UNKNOWN',
  add column if not exists identity_link_risk_score integer not null default 0,
  add column if not exists identity_link_reason text,
  add column if not exists identity_link_checked_at timestamptz,
  add column if not exists identity_link_policy_version text,
  add column if not exists identity_link_evidence jsonb not null default '{}'::jsonb;

alter table public.invitations
  drop constraint if exists invitations_identity_link_status_check;
alter table public.invitations
  add constraint invitations_identity_link_status_check
  check (
    identity_link_status in (
      'UNKNOWN',
      'NO_KNOWN_LINK',
      'REVIEW',
      'LINKED_EXISTING',
      'OPERATOR_CLEARED'
    )
  );

alter table public.invitations
  drop constraint if exists invitations_identity_link_risk_score_check;
alter table public.invitations
  add constraint invitations_identity_link_risk_score_check
  check (identity_link_risk_score between 0 and 100);

alter table public.invitations
  drop constraint if exists invitations_identity_link_reason_check;
alter table public.invitations
  add constraint invitations_identity_link_reason_check
  check (
    identity_link_status not in (
      'REVIEW',
      'LINKED_EXISTING',
      'OPERATOR_CLEARED'
    )
    or (
      identity_link_reason is not null
      and length(btrim(identity_link_reason)) > 0
    )
  );

-- SECURITY_CLIENT is a distinct source so audit logs can distinguish this
-- relationship evidence from VePassport, on-chain, system and operator checks.
alter table public.invitations
  drop constraint if exists invitations_sybil_source_check;
alter table public.invitations
  add constraint invitations_sybil_source_check
  check (
    sybil_source in (
      'SYSTEM',
      'VEPASSPORT',
      'ONCHAIN',
      'SECURITY_CLIENT',
      'OPERATOR'
    )
  );

alter table public.sybil_review_events
  drop constraint if exists sybil_review_events_source_check;
alter table public.sybil_review_events
  add constraint sybil_review_events_source_check
  check (
    source in (
      'SYSTEM',
      'VEPASSPORT',
      'ONCHAIN',
      'SECURITY_CLIENT',
      'OPERATOR'
    )
  );

create table if not exists public.security_clients (
  id uuid primary key default gen_random_uuid(),
  client_hash text not null unique
    check (client_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  check (last_seen_at >= created_at)
);

create table if not exists public.security_client_wallet_observations (
  id bigint generated by default as identity primary key,
  client_id uuid not null
    references public.security_clients(id)
    on delete restrict,
  wallet_address text not null
    check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  auth_count integer not null default 1
    check (auth_count > 0),
  unique (client_id, wallet_address),
  check (last_seen_at >= first_seen_at)
);

create index if not exists security_client_wallet_observations_wallet_idx
  on public.security_client_wallet_observations(
    wallet_address,
    first_seen_at desc
  );

create index if not exists security_client_wallet_observations_client_idx
  on public.security_client_wallet_observations(
    client_id,
    first_seen_at desc
  );

create table if not exists public.security_identity_assessment_events (
  id bigint generated by default as identity primary key,
  invite_code text not null,
  wallet_address text not null
    check (wallet_address ~ '^0x[0-9a-f]{40}$'),
  identity_link_status text not null
    check (
      identity_link_status in (
        'UNKNOWN',
        'NO_KNOWN_LINK',
        'REVIEW',
        'LINKED_EXISTING',
        'OPERATOR_CLEARED'
      )
    ),
  risk_score integer not null
    check (risk_score between 0 and 100),
  reason text,
  policy_version text not null,
  evidence jsonb not null default '{}'::jsonb,
  assessed_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists security_identity_assessment_events_invite_idx
  on public.security_identity_assessment_events(
    invite_code,
    assessed_at desc,
    id desc
  );

create index if not exists security_identity_assessment_events_wallet_idx
  on public.security_identity_assessment_events(
    wallet_address,
    assessed_at desc,
    id desc
  );

alter table public.security_clients enable row level security;
alter table public.security_client_wallet_observations enable row level security;
alter table public.security_identity_assessment_events enable row level security;

-- These are server-side fraud-prevention records, not client-facing analytics.
revoke all on table public.security_clients
  from public, anon, authenticated;
revoke all on table public.security_client_wallet_observations
  from public, anon, authenticated;
revoke all on table public.security_identity_assessment_events
  from public, anon, authenticated;

grant select, insert, update
  on table public.security_clients
  to service_role;
grant select, insert, update
  on table public.security_client_wallet_observations
  to service_role;
grant select, insert
  on table public.security_identity_assessment_events
  to service_role;

grant usage, select
  on sequence public.security_client_wallet_observations_id_seq
  to service_role;
grant usage, select
  on sequence public.security_identity_assessment_events_id_seq
  to service_role;

create or replace function public.record_security_client_wallet_observation(
  p_client_hash text,
  p_wallet_address text,
  p_observed_at timestamptz default now()
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_hash text := lower(btrim(p_client_hash));
  v_wallet text := lower(btrim(p_wallet_address));
  v_client_id uuid;
  v_observation_id bigint;
  v_created boolean := false;
begin
  if v_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid security client hash';
  end if;

  if v_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'invalid security client wallet';
  end if;

  if p_observed_at is null then
    raise exception 'security client observation timestamp is required';
  end if;

  -- Serialize first use of one pseudonymous client so simultaneous wallet
  -- session checks cannot create duplicate client rows or mappings.
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_security_client_' || v_hash,
      0
    )
  );

  insert into public.security_clients(
    client_hash,
    created_at,
    last_seen_at
  )
  values (
    v_hash,
    p_observed_at,
    p_observed_at
  )
  on conflict (client_hash) do update
    set last_seen_at = greatest(
      public.security_clients.last_seen_at,
      excluded.last_seen_at
    )
  returning id into v_client_id;

  select id
  into v_observation_id
  from public.security_client_wallet_observations
  where client_id = v_client_id
    and wallet_address = v_wallet
  for update;

  if found then
    update public.security_client_wallet_observations
    set
      last_seen_at = greatest(last_seen_at, p_observed_at),
      auth_count = auth_count + 1
    where id = v_observation_id;
  else
    insert into public.security_client_wallet_observations(
      client_id,
      wallet_address,
      first_seen_at,
      last_seen_at,
      auth_count
    )
    values (
      v_client_id,
      v_wallet,
      p_observed_at,
      p_observed_at,
      1
    )
    returning id into v_observation_id;

    v_created := true;
  end if;

  return jsonb_build_object(
    'clientId', v_client_id,
    'observationId', v_observation_id,
    'newWalletMapping', v_created
  );
end;
$$;

revoke execute
  on function public.record_security_client_wallet_observation(
    text,
    text,
    timestamptz
  )
  from public, anon, authenticated;
grant execute
  on function public.record_security_client_wallet_observation(
    text,
    text,
    timestamptz
  )
  to service_role;

create or replace function public.enforce_security_client_identity_gate()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_invitee text;
  v_inviter text;
  v_related_wallet_count integer := 0;
  v_same_inviter_client boolean := false;
  v_related_participant boolean := false;
  v_related_rewarded boolean := false;
  v_status text := 'NO_KNOWN_LINK';
  v_score integer := 0;
  v_reason text := null;
  v_now timestamptz := clock_timestamp();
  v_evidence jsonb := '{}'::jsonb;
  v_new_operator_override boolean := false;
  v_preserved_operator_override boolean := false;
  v_operator_override boolean := false;
begin
  -- The gate is intentionally placed on attempts to CLEAR. NOT_CHECKED,
  -- REVIEW and BLOCKED retain their existing conservative semantics.
  if new.invitee_wallet is null
     or new.sybil_status <> 'CLEAR' then
    return new;
  end if;

  v_invitee := lower(btrim(new.invitee_wallet));
  v_inviter := lower(btrim(new.inviter_wallet));
  v_new_operator_override := new.sybil_source = 'OPERATOR';

  if tg_op = 'UPDATE' then
    v_preserved_operator_override :=
      old.identity_link_status = 'OPERATOR_CLEARED';
  end if;

  v_operator_override :=
    v_new_operator_override
    or v_preserved_operator_override;

  with invitee_clients as (
    select distinct o.client_id
    from public.security_client_wallet_observations o
    where o.wallet_address = v_invitee
  ),
  related_wallets as (
    select distinct o.wallet_address
    from public.security_client_wallet_observations o
    join invitee_clients c
      on c.client_id = o.client_id
    where o.wallet_address <> v_invitee
  )
  select
    count(*)::integer,
    coalesce(
      bool_or(r.wallet_address = v_inviter),
      false
    ),
    coalesce(
      bool_or(
        exists (
          select 1
          from public.invitations i
          where lower(btrim(i.invitee_wallet)) = r.wallet_address
            and i.invite_code <> new.invite_code
            and i.eligibility_check_id is not null
            and i.ineligibility_check_id is null
            and i.status in (
              'ACTIVATING',
              'UNDER_REVIEW',
              'COMPLETED'
            )
        )
      ),
      false
    ),
    coalesce(
      bool_or(
        exists (
          select 1
          from public.invitations i
          where lower(btrim(i.invitee_wallet)) = r.wallet_address
            and i.invite_code <> new.invite_code
            and (
              i.reward_status in ('ELIGIBLE', 'PAID')
              or i.status = 'COMPLETED'
            )
        )
      ),
      false
    )
  into
    v_related_wallet_count,
    v_same_inviter_client,
    v_related_participant,
    v_related_rewarded
  from related_wallets r;

  if v_same_inviter_client then
    v_status := 'REVIEW';
    v_score := 90;
    v_reason :=
      'Invitee and inviter were observed in the same VeInvite security client.';
  elsif v_related_rewarded then
    v_status := 'REVIEW';
    v_score := 80;
    v_reason :=
      'The invitee shares a VeInvite security client with another completed or rewarded participant wallet.';
  elsif v_related_participant then
    v_status := 'REVIEW';
    v_score := 60;
    v_reason :=
      'The invitee shares a VeInvite security client with another active participant wallet.';
  end if;

  v_evidence := jsonb_build_object(
    'relatedWalletCount', v_related_wallet_count,
    'sameInviterClient', v_same_inviter_client,
    'relatedActiveParticipant', v_related_participant,
    'relatedCompletedOrRewardedParticipant', v_related_rewarded,
    'operatorOverride', v_operator_override,
    'signalFamily', 'SECURITY_CLIENT'
  );

  if v_operator_override
     and v_status = 'REVIEW' then
    new.identity_link_status := 'OPERATOR_CLEARED';
  else
    new.identity_link_status := v_status;
  end if;

  new.identity_link_risk_score := v_score;
  new.identity_link_reason := case
    when new.identity_link_status = 'OPERATOR_CLEARED'
         and v_new_operator_override
      then 'Operator cleared a security-client relationship review: '
        || v_reason
    when new.identity_link_status = 'OPERATOR_CLEARED'
         and v_preserved_operator_override
      then old.identity_link_reason
    else v_reason
  end;
  new.identity_link_checked_at := case
    when v_preserved_operator_override
         and not v_new_operator_override
      then old.identity_link_checked_at
    else v_now
  end;
  new.identity_link_policy_version := 'security_client_v1';
  new.identity_link_evidence := v_evidence;

  -- v1 never auto-BLOCKS. Ambiguous shared-device evidence pauses the reward
  -- and enters the existing manual-review path.
  if v_status = 'REVIEW'
     and not v_operator_override then
    new.sybil_status := 'REVIEW';
    new.sybil_risk_level := case
      when v_score >= 80 then 'HIGH'
      else 'MEDIUM'
    end;
    new.sybil_risk_score := greatest(
      coalesce(new.sybil_risk_score, 0),
      v_score
    );
    new.sybil_reason := v_reason;
    new.sybil_checked_at := v_now;
    new.sybil_source := 'SECURITY_CLIENT';

    if new.status <> 'CANCELLED' then
      new.status := 'UNDER_REVIEW';
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.log_security_identity_assessment()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.invitee_wallet is null
     or new.identity_link_checked_at is null then
    return new;
  end if;

  if tg_op = 'UPDATE'
     and new.identity_link_status
       is not distinct from old.identity_link_status
     and new.identity_link_risk_score
       is not distinct from old.identity_link_risk_score
     and new.identity_link_reason
       is not distinct from old.identity_link_reason
     and new.identity_link_checked_at
       is not distinct from old.identity_link_checked_at
     and new.identity_link_policy_version
       is not distinct from old.identity_link_policy_version
     and new.identity_link_evidence
       is not distinct from old.identity_link_evidence then
    return new;
  end if;

  insert into public.security_identity_assessment_events(
    invite_code,
    wallet_address,
    identity_link_status,
    risk_score,
    reason,
    policy_version,
    evidence,
    assessed_at
  )
  values (
    new.invite_code,
    lower(new.invitee_wallet),
    new.identity_link_status,
    new.identity_link_risk_score,
    new.identity_link_reason,
    coalesce(
      new.identity_link_policy_version,
      'security_client_v1'
    ),
    new.identity_link_evidence,
    new.identity_link_checked_at
  );

  return new;
end;
$$;

create or replace function public.invalidate_security_identity_on_new_wallet_mapping()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  -- A wallet appearing alone on a new browser/client is a normal device change,
  -- not relationship evidence. Re-evaluate only when this client now contains
  -- at least one other verified wallet.
  if not exists (
    select 1
    from public.security_client_wallet_observations o
    where o.client_id = new.client_id
      and o.wallet_address <> new.wallet_address
  ) then
    return new;
  end if;

  -- A new cross-wallet relationship makes prior client-identity assessments
  -- stale. Never mutate already settled/assigned rewards.
  update public.invitations i
  set
    identity_link_status = 'UNKNOWN',
    identity_link_risk_score = 0,
    identity_link_reason = null,
    identity_link_checked_at = null,
    identity_link_policy_version = 'security_client_v1',
    identity_link_evidence = jsonb_build_object(
      'staleBecause',
      'NEW_SHARED_SECURITY_CLIENT_WALLET_MAPPING',
      'observedAt',
      new.first_seen_at
    ),
    sybil_status = case
      when i.sybil_status = 'CLEAR' then 'REVIEW'
      else i.sybil_status
    end,
    sybil_risk_level = case
      when i.sybil_status = 'CLEAR' then 'MEDIUM'
      else i.sybil_risk_level
    end,
    sybil_risk_score = case
      when i.sybil_status = 'CLEAR'
        then greatest(i.sybil_risk_score, 50)
      else i.sybil_risk_score
    end,
    sybil_reason = case
      when i.sybil_status = 'CLEAR'
        then 'A new shared security-client wallet relationship was observed after the previous Sybil check.'
      else i.sybil_reason
    end,
    sybil_checked_at = case
      when i.sybil_status = 'CLEAR'
        then clock_timestamp()
      else i.sybil_checked_at
    end,
    sybil_source = case
      when i.sybil_status = 'CLEAR'
        then 'SECURITY_CLIENT'
      else i.sybil_source
    end,
    status = case
      when i.sybil_status = 'CLEAR'
           and i.status <> 'CANCELLED'
        then 'UNDER_REVIEW'
      else i.status
    end
  where i.invitee_wallet is not null
    and lower(btrim(i.invitee_wallet)) in (
      select o.wallet_address
      from public.security_client_wallet_observations o
      where o.client_id = new.client_id
    )
    and i.reward_status <> 'PAID'
    and not exists (
      select 1
      from public.reward_queue_entries q
      where q.invite_code = i.invite_code
        and q.status = 'ASSIGNED'
        and q.assigned_round_id is not null
    );

  return new;
end;
$$;

drop trigger if exists ab_invitations_security_client_gate
  on public.invitations;
create trigger ab_invitations_security_client_gate
before insert or update of
  sybil_status,
  invitee_wallet,
  vote_completed_at
on public.invitations
for each row
execute function public.enforce_security_client_identity_gate();

drop trigger if exists invitations_log_security_identity_assessment
  on public.invitations;
create trigger invitations_log_security_identity_assessment
after insert or update
on public.invitations
for each row
execute function public.log_security_identity_assessment();

drop trigger if exists security_client_wallet_mapping_invalidate
  on public.security_client_wallet_observations;
create trigger security_client_wallet_mapping_invalidate
after insert
on public.security_client_wallet_observations
for each row
execute function public.invalidate_security_identity_on_new_wallet_mapping();

drop trigger if exists security_identity_assessment_events_append_only
  on public.security_identity_assessment_events;
create trigger security_identity_assessment_events_append_only
before update or delete
on public.security_identity_assessment_events
for each row
execute function public.prevent_operator_ledger_mutation();

revoke execute
  on function public.enforce_security_client_identity_gate()
  from public, anon, authenticated;
revoke execute
  on function public.log_security_identity_assessment()
  from public, anon, authenticated;
revoke execute
  on function public.invalidate_security_identity_on_new_wallet_mapping()
  from public, anon, authenticated;

commit;
