-- Foundation only: create an immutable X-promotion payout intent after final
-- verification. No signing, broadcast, settlement, or PAID transition is added.
-- LIVE must remain disabled while this migration is applied.

do $$
declare
  v_enabled boolean;
begin
  select reward_x_promotion_enabled
  into v_enabled
  from public.reward_runtime_config
  where id=1;

  if coalesce(v_enabled,false) then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_FOUNDATION_REQUIRES_LIVE_DISABLED';
  end if;
end $$;

create table if not exists public.reward_x_promotion_payout_intents (
  id bigint generated by default as identity primary key,
  obligation_id bigint not null
    references public.reward_x_promotion_obligations(id) on delete restrict,
  verification_id bigint not null
    references public.reward_x_promotion_post_verifications(id) on delete restrict,
  split_id bigint not null
    references public.reward_x_promotion_splits(id) on delete restrict,
  invite_code text not null
    check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  network text not null
    check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null
    check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  amount_wei numeric(78,0) not null
    check (amount_wei > 0 and amount_wei=trunc(amount_wei)),
  source_reward_cohort_round_id bigint not null
    check (source_reward_cohort_round_id >= 1),
  source_allocation_receipt_id bigint not null
    references public.vebetter_round_allocations(id) on delete restrict,
  x_post_id text not null
    check (x_post_id ~ '^[0-9]{1,32}$'),
  x_author_id text not null
    check (x_author_id ~ '^[0-9]{1,32}$'),
  public_proof_id uuid not null default gen_random_uuid(),
  policy_version text not null
    check (char_length(btrim(policy_version)) between 1 and 80),
  created_at timestamptz not null default now(),
  constraint reward_x_promotion_payout_intents_obligation_uidx
    unique(obligation_id),
  constraint reward_x_promotion_payout_intents_verification_uidx
    unique(verification_id),
  constraint reward_x_promotion_payout_intents_split_uidx
    unique(split_id),
  constraint reward_x_promotion_payout_intents_invite_uidx
    unique(invite_code),
  constraint reward_x_promotion_payout_intents_proof_uidx
    unique(public_proof_id)
);

create index if not exists reward_x_promotion_payout_intents_network_created_idx
  on public.reward_x_promotion_payout_intents(network,created_at,id);

create or replace function public.validate_reward_x_promotion_payout_intent_v1()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_cfg public.reward_runtime_config%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_invitation public.invitations%rowtype;
begin
  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || new.invite_code,0)
  );

  select * into v_cfg
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  if not v_cfg.reward_x_promotion_enabled
     or v_cfg.reward_x_promotion_live_started_at is null then
    raise exception 'REWARD_X_PROMOTION_LIVE_DISABLED';
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=new.obligation_id
  for update;

  if not found
     or v_obligation.financial_state<>'HELD'
     or v_obligation.held_at is null
     or v_obligation.released_at is not null
     or v_obligation.paid_at is not null
     or v_obligation.split_id<>new.split_id
     or v_obligation.invite_code<>new.invite_code
     or v_obligation.network<>new.network
     or v_obligation.recipient_wallet<>new.recipient_wallet
     or v_obligation.promotion_amount_wei<>new.amount_wei
     or v_obligation.source_reward_cohort_round_id<>new.source_reward_cohort_round_id
     or v_obligation.source_allocation_receipt_id<>new.source_allocation_receipt_id
     or v_obligation.policy_version<>new.policy_version then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_OBLIGATION_MISMATCH';
  end if;

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.id=new.verification_id;

  if not found
     or v_verification.verification_state<>'FINAL_VERIFIED'
     or v_verification.final_verified_at is null
     or v_verification.invalidated_at is not null
     or v_verification.obligation_id<>new.obligation_id
     or v_verification.split_id<>new.split_id
     or v_verification.invite_code<>new.invite_code
     or v_verification.network<>new.network
     or v_verification.recipient_wallet<>new.recipient_wallet
     or v_verification.x_post_id<>new.x_post_id
     or v_verification.x_author_id<>new.x_author_id then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_VERIFICATION_MISMATCH';
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=new.invite_code;

  if not found
     or v_invitation.sybil_status<>'CLEAR'
     or public.is_sybil_v2_referral_invalidated(new.invite_code,new.network)
     or exists (
       select 1
       from public.sybil_v2_wallet_restrictions r
       where r.network=new.network
         and r.status='ACTIVE'
         and r.wallet_address in (
           new.recipient_wallet,
           lower(v_invitation.invitee_wallet)
         )
     )
     or (
       public.sybil_v2_enforcement_enabled()
       and not exists (
         select 1
         from public.sybil_v2_referral_assessments a
         join public.sybil_v2_reward_clearances c
           on c.invite_code=a.invite_code
          and c.network=a.network
          and c.assessment_revision=a.revision
          and c.verdict='CLEAR'
         where a.invite_code=new.invite_code
           and a.network=new.network
           and a.state='CLEAR'
       )
     ) then
    raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_SECURITY_NOT_CLEAR';
  end if;

  return new;
end;
$function$;

create or replace function public.reject_reward_x_promotion_payout_intent_mutation_v1()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'REWARD_X_PROMOTION_PAYOUT_INTENT_IMMUTABLE';
end;
$function$;

drop trigger if exists validate_reward_x_promotion_payout_intent_v1_trigger
  on public.reward_x_promotion_payout_intents;
create trigger validate_reward_x_promotion_payout_intent_v1_trigger
before insert on public.reward_x_promotion_payout_intents
for each row execute function public.validate_reward_x_promotion_payout_intent_v1();

drop trigger if exists reject_reward_x_promotion_payout_intent_mutation_v1_trigger
  on public.reward_x_promotion_payout_intents;
create trigger reject_reward_x_promotion_payout_intent_mutation_v1_trigger
before update or delete on public.reward_x_promotion_payout_intents
for each row execute function public.reject_reward_x_promotion_payout_intent_mutation_v1();

create or replace function public.create_reward_x_promotion_payout_intent_v1(
  p_verification_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_existing public.reward_x_promotion_payout_intents%rowtype;
  v_intent public.reward_x_promotion_payout_intents%rowtype;
begin
  if p_verification_id is null or p_verification_id<1 then
    raise exception 'REWARD_X_PROMOTION_VERIFICATION_ID_INVALID';
  end if;

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.id=p_verification_id;

  if not found then
    raise exception 'REWARD_X_PROMOTION_POST_VERIFICATION_MISSING';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_x_promotion_' || v_verification.invite_code,
      0
    )
  );

  select * into v_existing
  from public.reward_x_promotion_payout_intents i
  where i.verification_id=p_verification_id;

  if found then
    return jsonb_build_object(
      'created',false,
      'reason','ALREADY_EXISTS',
      'intentId',v_existing.id,
      'inviteCode',v_existing.invite_code,
      'amountWei',v_existing.amount_wei::text,
      'publicProofId',v_existing.public_proof_id::text
    );
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=v_verification.obligation_id;

  if not found then
    raise exception 'REWARD_X_PROMOTION_OBLIGATION_MISSING';
  end if;

  insert into public.reward_x_promotion_payout_intents(
    obligation_id,
    verification_id,
    split_id,
    invite_code,
    network,
    recipient_wallet,
    amount_wei,
    source_reward_cohort_round_id,
    source_allocation_receipt_id,
    x_post_id,
    x_author_id,
    policy_version
  ) values (
    v_obligation.id,
    v_verification.id,
    v_obligation.split_id,
    v_obligation.invite_code,
    v_obligation.network,
    v_obligation.recipient_wallet,
    v_obligation.promotion_amount_wei,
    v_obligation.source_reward_cohort_round_id,
    v_obligation.source_allocation_receipt_id,
    v_verification.x_post_id,
    v_verification.x_author_id,
    v_obligation.policy_version
  )
  returning * into v_intent;

  return jsonb_build_object(
    'created',true,
    'reason','CREATED',
    'intentId',v_intent.id,
    'inviteCode',v_intent.invite_code,
    'amountWei',v_intent.amount_wei::text,
    'publicProofId',v_intent.public_proof_id::text
  );
end;
$function$;

alter table public.reward_x_promotion_payout_intents enable row level security;

revoke all on table public.reward_x_promotion_payout_intents
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_payout_intents_id_seq
  from public,anon,authenticated,service_role;

grant select on table public.reward_x_promotion_payout_intents to service_role;

revoke all on function public.validate_reward_x_promotion_payout_intent_v1()
  from public,anon,authenticated,service_role;
revoke all on function public.reject_reward_x_promotion_payout_intent_mutation_v1()
  from public,anon,authenticated,service_role;
revoke all on function public.create_reward_x_promotion_payout_intent_v1(bigint)
  from public,anon,authenticated;
grant execute on function public.create_reward_x_promotion_payout_intent_v1(bigint)
  to service_role;

comment on table public.reward_x_promotion_payout_intents is
  'Immutable X-promotion payout intent created only from an exact HELD obligation and FINAL_VERIFIED post. Foundation only: this table does not sign, submit, settle, or mark any obligation PAID.';
