-- X promotion post verification foundation.
-- LIVE activation remains hard-blocked. This migration adds no X API calls,
-- no promotion payout path, and no user-facing behavior.

do $$
declare
  v_enabled boolean;
begin
  select reward_x_promotion_enabled
  into v_enabled
  from public.reward_runtime_config
  where id=1;

  if coalesce(v_enabled,false) then
    raise exception 'REWARD_X_PROMOTION_POST_FOUNDATION_REQUIRES_LIVE_DISABLED';
  end if;
end $$;

alter table public.reward_x_promotion_opportunities
  add column if not exists share_token uuid not null default gen_random_uuid(),
  add column if not exists submission_grace_seconds integer not null default 900;

alter table public.reward_x_promotion_opportunities
  drop constraint if exists reward_x_promotion_opportunities_submission_grace_check,
  add constraint reward_x_promotion_opportunities_submission_grace_check
    check (submission_grace_seconds=900);

create unique index if not exists reward_x_promotion_opportunities_share_token_uidx
  on public.reward_x_promotion_opportunities(share_token);

create table if not exists public.reward_x_promotion_x_identities (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  x_author_id text not null check (x_author_id ~ '^[0-9]{1,32}$'),
  policy_version text not null check (char_length(btrim(policy_version)) between 1 and 80),
  first_verified_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint reward_x_promotion_x_identity_wallet_uidx
    unique(network,recipient_wallet),
  constraint reward_x_promotion_x_identity_author_uidx
    unique(network,x_author_id)
);

create table if not exists public.reward_x_promotion_post_verifications (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null
    references public.reward_x_promotion_opportunities(id),
  obligation_id bigint not null
    references public.reward_x_promotion_obligations(id),
  split_id bigint not null
    references public.reward_x_promotion_splits(id),
  invite_code text not null check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  x_post_id text not null check (x_post_id ~ '^[0-9]{1,32}$'),
  x_author_id text not null check (x_author_id ~ '^[0-9]{1,32}$'),
  x_post_created_at timestamptz not null,
  matched_expanded_url text not null
    check (
      char_length(matched_expanded_url) between 1 and 2048
      and matched_expanded_url ~* '^https://veinvite\.vercel\.app/'
    ),
  initial_verified_at timestamptz not null,
  retention_seconds integer not null default 86400
    check (retention_seconds=86400),
  verify_after timestamptz not null,
  verification_state text not null default 'INITIAL_VERIFIED'
    check (
      verification_state in (
        'INITIAL_VERIFIED','REVIEW_REQUIRED','FINAL_VERIFIED','INVALID'
      )
    ),
  final_verified_at timestamptz,
  invalidated_at timestamptz,
  state_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reward_x_promotion_post_verification_opportunity_uidx
    unique(opportunity_id),
  constraint reward_x_promotion_post_verification_post_uidx
    unique(x_post_id),
  constraint reward_x_promotion_post_verification_state_shape_check
    check (
      (
        verification_state='INITIAL_VERIFIED'
        and final_verified_at is null
        and invalidated_at is null
        and state_reason is null
      )
      or
      (
        verification_state='REVIEW_REQUIRED'
        and final_verified_at is null
        and invalidated_at is null
        and state_reason is not null
        and char_length(btrim(state_reason)) between 1 and 120
      )
      or
      (
        verification_state='FINAL_VERIFIED'
        and final_verified_at is not null
        and invalidated_at is null
        and state_reason is null
      )
      or
      (
        verification_state='INVALID'
        and final_verified_at is null
        and invalidated_at is not null
        and state_reason is not null
        and char_length(btrim(state_reason)) between 1 and 120
      )
    )
);

create index if not exists reward_x_promotion_post_verification_due_idx
  on public.reward_x_promotion_post_verifications(
    network,verification_state,verify_after
  )
  where verification_state in ('INITIAL_VERIFIED','REVIEW_REQUIRED');

create index if not exists reward_x_promotion_post_verification_author_idx
  on public.reward_x_promotion_post_verifications(network,x_author_id);

alter table public.reward_x_promotion_x_identities enable row level security;
alter table public.reward_x_promotion_post_verifications enable row level security;

revoke all on table public.reward_x_promotion_x_identities
  from public,anon,authenticated,service_role;
revoke all on table public.reward_x_promotion_post_verifications
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_x_identities_id_seq
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_post_verifications_id_seq
  from public,anon,authenticated,service_role;

grant select on table public.reward_x_promotion_x_identities to service_role;
grant select on table public.reward_x_promotion_post_verifications to service_role;

create or replace function public.reject_reward_x_promotion_x_identity_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'REWARD_X_PROMOTION_X_IDENTITY_IMMUTABLE';
end;
$function$;

drop trigger if exists reward_x_promotion_x_identity_immutable
  on public.reward_x_promotion_x_identities;
create trigger reward_x_promotion_x_identity_immutable
before update or delete on public.reward_x_promotion_x_identities
for each row execute function public.reject_reward_x_promotion_x_identity_mutation();

create or replace function public.validate_reward_x_promotion_post_verification_insert()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_opportunity public.reward_x_promotion_opportunities%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_split public.reward_x_promotion_splits%rowtype;
  v_identity public.reward_x_promotion_x_identities%rowtype;
begin
  select * into v_opportunity
  from public.reward_x_promotion_opportunities x
  where x.id=new.opportunity_id;

  if not found
     or v_opportunity.obligation_id<>new.obligation_id
     or v_opportunity.split_id<>new.split_id
     or v_opportunity.invite_code<>new.invite_code
     or v_opportunity.network<>new.network
     or v_opportunity.recipient_wallet<>new.recipient_wallet
     or v_opportunity.policy_version<>'x-promotion-split-v1'
     or v_opportunity.submission_grace_seconds<>900 then
    raise exception 'REWARD_X_PROMOTION_POST_OPPORTUNITY_MISMATCH';
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=new.obligation_id;

  if not found
     or v_obligation.split_id<>new.split_id
     or v_obligation.invite_code<>new.invite_code
     or v_obligation.network<>new.network
     or v_obligation.recipient_wallet<>new.recipient_wallet
     or v_obligation.financial_state<>'HELD'
     or v_obligation.held_at is null then
    raise exception 'REWARD_X_PROMOTION_POST_OBLIGATION_MISMATCH';
  end if;

  select * into v_split
  from public.reward_x_promotion_splits s
  where s.id=new.split_id;

  if not found
     or v_split.mode<>'LIVE'
     or v_split.invite_code<>new.invite_code
     or v_split.network<>new.network
     or v_split.recipient_wallet<>new.recipient_wallet
     or v_split.policy_version<>'x-promotion-split-v1' then
    raise exception 'REWARD_X_PROMOTION_POST_SPLIT_MISMATCH';
  end if;

  select * into v_identity
  from public.reward_x_promotion_x_identities i
  where i.network=new.network
    and i.recipient_wallet=new.recipient_wallet;

  if not found
     or v_identity.x_author_id<>new.x_author_id
     or v_identity.policy_version<>'x-promotion-split-v1' then
    raise exception 'REWARD_X_PROMOTION_POST_IDENTITY_MISMATCH';
  end if;

  if new.verification_state<>'INITIAL_VERIFIED'
     or new.final_verified_at is not null
     or new.invalidated_at is not null
     or new.state_reason is not null then
    raise exception 'REWARD_X_PROMOTION_POST_INITIAL_STATE_INVALID';
  end if;

  if new.x_post_created_at<v_opportunity.opened_at
     or new.x_post_created_at>v_opportunity.post_deadline_at
     or new.initial_verified_at<new.x_post_created_at
     or new.initial_verified_at>
        v_opportunity.post_deadline_at +
        make_interval(secs=>v_opportunity.submission_grace_seconds)
     or new.retention_seconds<>86400
     or new.verify_after<>
        new.initial_verified_at+make_interval(secs=>new.retention_seconds) then
    raise exception 'REWARD_X_PROMOTION_POST_WINDOW_MISMATCH';
  end if;

  if position(v_opportunity.share_token::text in new.matched_expanded_url)=0 then
    raise exception 'REWARD_X_PROMOTION_POST_SHARE_TOKEN_MISSING';
  end if;

  return new;
end;
$function$;

create or replace function public.guard_reward_x_promotion_post_verification_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  if tg_op='DELETE' then
    raise exception 'REWARD_X_PROMOTION_POST_DELETE_FORBIDDEN';
  end if;

  if old.opportunity_id is distinct from new.opportunity_id
     or old.obligation_id is distinct from new.obligation_id
     or old.split_id is distinct from new.split_id
     or old.invite_code is distinct from new.invite_code
     or old.network is distinct from new.network
     or old.recipient_wallet is distinct from new.recipient_wallet
     or old.x_post_id is distinct from new.x_post_id
     or old.x_author_id is distinct from new.x_author_id
     or old.x_post_created_at is distinct from new.x_post_created_at
     or old.matched_expanded_url is distinct from new.matched_expanded_url
     or old.initial_verified_at is distinct from new.initial_verified_at
     or old.retention_seconds is distinct from new.retention_seconds
     or old.verify_after is distinct from new.verify_after
     or old.created_at is distinct from new.created_at then
    raise exception 'REWARD_X_PROMOTION_POST_IDENTITY_IMMUTABLE';
  end if;

  if old.verification_state=new.verification_state then
    raise exception 'REWARD_X_PROMOTION_POST_STATE_CHANGE_REQUIRED';
  end if;

  if not (
    (
      old.verification_state='INITIAL_VERIFIED'
      and new.verification_state in ('REVIEW_REQUIRED','FINAL_VERIFIED','INVALID')
    )
    or
    (
      old.verification_state='REVIEW_REQUIRED'
      and new.verification_state in ('FINAL_VERIFIED','INVALID')
    )
  ) then
    raise exception 'REWARD_X_PROMOTION_POST_TRANSITION_INVALID';
  end if;

  new.updated_at:=clock_timestamp();
  return new;
end;
$function$;

drop trigger if exists validate_reward_x_promotion_post_verification_insert_trigger
  on public.reward_x_promotion_post_verifications;
create trigger validate_reward_x_promotion_post_verification_insert_trigger
before insert on public.reward_x_promotion_post_verifications
for each row execute function public.validate_reward_x_promotion_post_verification_insert();

drop trigger if exists guard_reward_x_promotion_post_verification_mutation_trigger
  on public.reward_x_promotion_post_verifications;
create trigger guard_reward_x_promotion_post_verification_mutation_trigger
before update or delete on public.reward_x_promotion_post_verifications
for each row execute function public.guard_reward_x_promotion_post_verification_mutation();

create or replace function public.record_reward_x_promotion_initial_post_verification_v1(
  p_invite_code text,
  p_x_post_id text,
  p_x_author_id text,
  p_x_post_created_at timestamptz,
  p_matched_expanded_url text
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(coalesce(p_invite_code,'')));
  v_post_id text := btrim(coalesce(p_x_post_id,''));
  v_author_id text := btrim(coalesce(p_x_author_id,''));
  v_url text := btrim(coalesce(p_matched_expanded_url,''));
  v_now timestamptz := clock_timestamp();
  v_opportunity public.reward_x_promotion_opportunities%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_identity public.reward_x_promotion_x_identities%rowtype;
  v_existing public.reward_x_promotion_post_verifications%rowtype;
  v_created public.reward_x_promotion_post_verifications%rowtype;
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;
  if v_post_id !~ '^[0-9]{1,32}$' then
    raise exception 'REWARD_X_PROMOTION_POST_ID_INVALID';
  end if;
  if v_author_id !~ '^[0-9]{1,32}$' then
    raise exception 'REWARD_X_PROMOTION_AUTHOR_ID_INVALID';
  end if;
  if p_x_post_created_at is null then
    raise exception 'REWARD_X_PROMOTION_POST_CREATED_AT_REQUIRED';
  end if;
  if char_length(v_url) not between 1 and 2048
     or v_url !~* '^https://veinvite\.vercel\.app/' then
    raise exception 'REWARD_X_PROMOTION_MATCHED_URL_INVALID';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_code,0)
  );

  select * into v_opportunity
  from public.reward_x_promotion_opportunities x
  where x.invite_code=v_code;

  if not found then
    raise exception 'REWARD_X_PROMOTION_OPPORTUNITY_MISSING';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_x_promotion_wallet_' || v_opportunity.network || '_' ||
      v_opportunity.recipient_wallet,
      0
    )
  );
  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_x_promotion_author_' || v_opportunity.network || '_' ||
      v_author_id,
      0
    )
  );

  if v_now>
     v_opportunity.post_deadline_at +
     make_interval(secs=>v_opportunity.submission_grace_seconds) then
    raise exception 'REWARD_X_PROMOTION_POST_SUBMISSION_EXPIRED';
  end if;

  if p_x_post_created_at<v_opportunity.opened_at
     or p_x_post_created_at>v_opportunity.post_deadline_at then
    raise exception 'REWARD_X_PROMOTION_POST_CREATED_OUTSIDE_WINDOW';
  end if;

  if position(v_opportunity.share_token::text in v_url)=0 then
    raise exception 'REWARD_X_PROMOTION_POST_SHARE_TOKEN_MISSING';
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=v_opportunity.obligation_id
  for update;

  if not found
     or v_obligation.financial_state<>'HELD'
     or v_obligation.recipient_wallet<>v_opportunity.recipient_wallet then
    raise exception 'REWARD_X_PROMOTION_POST_OBLIGATION_NOT_HELD';
  end if;

  select * into v_existing
  from public.reward_x_promotion_post_verifications p
  where p.opportunity_id=v_opportunity.id;

  if found then
    if v_existing.x_post_id=v_post_id
       and v_existing.x_author_id=v_author_id then
      return jsonb_build_object(
        'recorded',true,
        'reason','ALREADY_RECORDED',
        'inviteCode',v_code,
        'verificationId',v_existing.id,
        'verifyAfter',v_existing.verify_after,
        'state',v_existing.verification_state
      );
    end if;
    raise exception 'REWARD_X_PROMOTION_POST_ALREADY_SUBMITTED';
  end if;

  if exists (
    select 1
    from public.reward_x_promotion_post_verifications p
    where p.x_post_id=v_post_id
  ) then
    raise exception 'REWARD_X_PROMOTION_POST_ALREADY_USED';
  end if;

  select * into v_identity
  from public.reward_x_promotion_x_identities i
  where i.network=v_opportunity.network
    and i.recipient_wallet=v_opportunity.recipient_wallet;

  if found then
    if v_identity.x_author_id<>v_author_id then
      raise exception 'REWARD_X_PROMOTION_WALLET_AUTHOR_MISMATCH';
    end if;
  else
    select * into v_identity
    from public.reward_x_promotion_x_identities i
    where i.network=v_opportunity.network
      and i.x_author_id=v_author_id;

    if found and v_identity.recipient_wallet<>v_opportunity.recipient_wallet then
      raise exception 'REWARD_X_PROMOTION_AUTHOR_ALREADY_BOUND';
    end if;

    if not found then
      insert into public.reward_x_promotion_x_identities(
        network,
        recipient_wallet,
        x_author_id,
        policy_version,
        first_verified_at
      ) values (
        v_opportunity.network,
        v_opportunity.recipient_wallet,
        v_author_id,
        v_opportunity.policy_version,
        v_now
      )
      returning * into v_identity;
    end if;
  end if;

  insert into public.reward_x_promotion_post_verifications(
    opportunity_id,
    obligation_id,
    split_id,
    invite_code,
    network,
    recipient_wallet,
    x_post_id,
    x_author_id,
    x_post_created_at,
    matched_expanded_url,
    initial_verified_at,
    retention_seconds,
    verify_after,
    verification_state
  ) values (
    v_opportunity.id,
    v_opportunity.obligation_id,
    v_opportunity.split_id,
    v_code,
    v_opportunity.network,
    v_opportunity.recipient_wallet,
    v_post_id,
    v_author_id,
    p_x_post_created_at,
    v_url,
    v_now,
    86400,
    v_now+make_interval(secs=>86400),
    'INITIAL_VERIFIED'
  )
  returning * into v_created;

  return jsonb_build_object(
    'recorded',true,
    'reason','INITIAL_VERIFIED',
    'inviteCode',v_code,
    'verificationId',v_created.id,
    'xPostId',v_created.x_post_id,
    'verifyAfter',v_created.verify_after,
    'state',v_created.verification_state
  );
end;
$function$;

create or replace function public.finalize_reward_x_promotion_post_verification_v1(
  p_invite_code text,
  p_x_post_id text,
  p_x_author_id text,
  p_matched_expanded_url text
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog','public'
as $function$
declare
  v_code text := upper(btrim(coalesce(p_invite_code,'')));
  v_post_id text := btrim(coalesce(p_x_post_id,''));
  v_author_id text := btrim(coalesce(p_x_author_id,''));
  v_url text := btrim(coalesce(p_matched_expanded_url,''));
  v_now timestamptz := clock_timestamp();
  v_verification public.reward_x_promotion_post_verifications%rowtype;
  v_opportunity public.reward_x_promotion_opportunities%rowtype;
  v_obligation public.reward_x_promotion_obligations%rowtype;
  v_invitation public.invitations%rowtype;
begin
  if v_code !~ '^[A-HJ-NP-Z2-9]{7}$' then
    raise exception 'INVALID_INVITE_CODE';
  end if;
  if v_post_id !~ '^[0-9]{1,32}$'
     or v_author_id !~ '^[0-9]{1,32}$' then
    raise exception 'REWARD_X_PROMOTION_POST_IDENTITY_INVALID';
  end if;
  if char_length(v_url) not between 1 and 2048
     or v_url !~* '^https://veinvite\.vercel\.app/' then
    raise exception 'REWARD_X_PROMOTION_MATCHED_URL_INVALID';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('veinvite_x_promotion_' || v_code,0)
  );

  select * into v_verification
  from public.reward_x_promotion_post_verifications p
  where p.invite_code=v_code
  for update;

  if not found then
    raise exception 'REWARD_X_PROMOTION_POST_VERIFICATION_MISSING';
  end if;

  if v_verification.verification_state='FINAL_VERIFIED' then
    return jsonb_build_object(
      'finalized',true,
      'reason','ALREADY_FINAL_VERIFIED',
      'inviteCode',v_code,
      'verificationId',v_verification.id,
      'finalVerifiedAt',v_verification.final_verified_at
    );
  end if;

  if v_verification.verification_state not in ('INITIAL_VERIFIED','REVIEW_REQUIRED') then
    raise exception 'REWARD_X_PROMOTION_POST_NOT_FINALIZABLE';
  end if;

  if v_now<v_verification.verify_after then
    raise exception 'REWARD_X_PROMOTION_POST_RETENTION_PENDING';
  end if;

  if v_verification.x_post_id<>v_post_id
     or v_verification.x_author_id<>v_author_id then
    raise exception 'REWARD_X_PROMOTION_POST_IDENTITY_MISMATCH';
  end if;

  select * into v_opportunity
  from public.reward_x_promotion_opportunities x
  where x.id=v_verification.opportunity_id;

  if not found
     or position(v_opportunity.share_token::text in v_url)=0 then
    raise exception 'REWARD_X_PROMOTION_POST_SHARE_TOKEN_MISSING';
  end if;

  select * into v_obligation
  from public.reward_x_promotion_obligations o
  where o.id=v_verification.obligation_id;

  if not found or v_obligation.financial_state<>'HELD' then
    raise exception 'REWARD_X_PROMOTION_POST_OBLIGATION_NOT_HELD';
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=v_code;

  if not found
     or public.is_sybil_v2_referral_invalidated(v_code,v_verification.network)
     or exists (
       select 1
       from public.sybil_v2_wallet_restrictions r
       where r.network=v_verification.network
         and r.status='ACTIVE'
         and r.wallet_address in (
           lower(v_verification.recipient_wallet),
           lower(v_invitation.invitee_wallet)
         )
     ) then
    raise exception 'REWARD_X_PROMOTION_POST_SECURITY_NOT_CLEAR';
  end if;

  update public.reward_x_promotion_post_verifications p
  set verification_state='FINAL_VERIFIED',
      final_verified_at=v_now,
      invalidated_at=null,
      state_reason=null,
      updated_at=v_now
  where p.id=v_verification.id
  returning * into v_verification;

  return jsonb_build_object(
    'finalized',true,
    'reason','FINAL_VERIFIED',
    'inviteCode',v_code,
    'verificationId',v_verification.id,
    'finalVerifiedAt',v_verification.final_verified_at
  );
end;
$function$;

create or replace function public.read_reward_x_promotion_post_verification_audit(
  p_network text
)
returns jsonb
language plpgsql
stable
set search_path to 'pg_catalog','public'
as $function$
declare
  v_network text := lower(btrim(coalesce(p_network,'')));
  v_total integer := 0;
  v_binding integer := 0;
  v_identity integer := 0;
  v_window integer := 0;
  v_token integer := 0;
  v_final_too_early integer := 0;
begin
  if v_network not in ('mainnet','testnet','testnet-staging') then
    raise exception 'UNSUPPORTED_NETWORK';
  end if;

  select
    count(*)::integer,
    count(*) filter (
      where x.id is null
         or o.id is null
         or s.id is null
         or p.obligation_id<>x.obligation_id
         or p.split_id<>x.split_id
         or p.invite_code<>x.invite_code
         or p.network<>x.network
         or p.recipient_wallet<>x.recipient_wallet
         or o.id<>p.obligation_id
         or o.split_id<>p.split_id
         or s.id<>p.split_id
         or s.mode<>'LIVE'
    )::integer,
    count(*) filter (
      where i.id is null
         or i.recipient_wallet<>p.recipient_wallet
         or i.x_author_id<>p.x_author_id
    )::integer,
    count(*) filter (
      where p.x_post_created_at<x.opened_at
         or p.x_post_created_at>x.post_deadline_at
         or p.initial_verified_at<p.x_post_created_at
         or p.initial_verified_at>
            x.post_deadline_at+make_interval(secs=>x.submission_grace_seconds)
         or p.retention_seconds<>86400
         or p.verify_after<>
            p.initial_verified_at+make_interval(secs=>p.retention_seconds)
    )::integer,
    count(*) filter (
      where position(x.share_token::text in p.matched_expanded_url)=0
    )::integer,
    count(*) filter (
      where p.verification_state='FINAL_VERIFIED'
        and (
          p.final_verified_at is null
          or p.final_verified_at<p.verify_after
        )
    )::integer
  into
    v_total,
    v_binding,
    v_identity,
    v_window,
    v_token,
    v_final_too_early
  from public.reward_x_promotion_post_verifications p
  left join public.reward_x_promotion_opportunities x
    on x.id=p.opportunity_id
  left join public.reward_x_promotion_obligations o
    on o.id=p.obligation_id
  left join public.reward_x_promotion_splits s
    on s.id=p.split_id
  left join public.reward_x_promotion_x_identities i
    on i.network=p.network
   and i.recipient_wallet=p.recipient_wallet
  where p.network=v_network;

  return jsonb_build_object(
    'ok',
      v_binding=0
      and v_identity=0
      and v_window=0
      and v_token=0
      and v_final_too_early=0,
    'network',v_network,
    'totalCount',v_total,
    'violations',jsonb_build_object(
      'binding',v_binding,
      'identity',v_identity,
      'window',v_window,
      'shareToken',v_token,
      'finalTooEarly',v_final_too_early
    )
  );
end;
$function$;

revoke all on function public.reject_reward_x_promotion_x_identity_mutation()
  from public,anon,authenticated;
revoke all on function public.validate_reward_x_promotion_post_verification_insert()
  from public,anon,authenticated;
revoke all on function public.guard_reward_x_promotion_post_verification_mutation()
  from public,anon,authenticated;
revoke all on function public.record_reward_x_promotion_initial_post_verification_v1(
  text,text,text,timestamptz,text
) from public,anon,authenticated;
revoke all on function public.finalize_reward_x_promotion_post_verification_v1(
  text,text,text,text
) from public,anon,authenticated;
revoke all on function public.read_reward_x_promotion_post_verification_audit(text)
  from public,anon,authenticated;

grant execute on function public.record_reward_x_promotion_initial_post_verification_v1(
  text,text,text,timestamptz,text
) to service_role;
grant execute on function public.finalize_reward_x_promotion_post_verification_v1(
  text,text,text,text
) to service_role;
grant execute on function public.read_reward_x_promotion_post_verification_audit(text)
  to service_role;

comment on table public.reward_x_promotion_post_verifications is
  'Server-only X Post verification state. Foundation only: no API caller or promotion payout is wired by this migration.';
