-- Freeze each prepared reward round into one immutable, auditable payout plan.
-- This migration does not sign or submit VeChain transactions and cannot move B3TR.

begin;

create table if not exists public.reward_payout_manifests (
  id bigint generated by default as identity primary key,
  round_id bigint not null unique references public.reward_rounds(id) on delete restrict,
  manifest_version text not null default 'veinvite-payout-manifest-v1',
  network text not null,
  app_id text not null,
  x2earn_rewards_pool_address text not null,
  operator_wallet text not null,
  manifest_hash text not null unique,
  payout_count integer not null,
  total_amount_wei numeric(78,0) not null,
  clauses jsonb not null,
  created_at timestamptz not null default now(),
  constraint reward_payout_manifests_version_check
    check (manifest_version = 'veinvite-payout-manifest-v1'),
  constraint reward_payout_manifests_network_check
    check (network in ('mainnet','testnet','testnet-staging')),
  constraint reward_payout_manifests_app_id_check
    check (app_id ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_manifests_pool_address_check
    check (x2earn_rewards_pool_address ~ '^0x[0-9a-f]{40}$'),
  constraint reward_payout_manifests_operator_wallet_check
    check (operator_wallet ~ '^0x[0-9a-f]{40}$'),
  constraint reward_payout_manifests_hash_check
    check (manifest_hash ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_manifests_count_check
    check (payout_count > 0),
  constraint reward_payout_manifests_amount_check
    check (total_amount_wei > 0 and total_amount_wei = trunc(total_amount_wei)),
  constraint reward_payout_manifests_clauses_check
    check (jsonb_typeof(clauses) = 'array' and jsonb_array_length(clauses) = payout_count)
);

alter table public.reward_payout_manifests enable row level security;

revoke all on table public.reward_payout_manifests from public, anon, authenticated;
grant select on table public.reward_payout_manifests to service_role;

create or replace function public.enforce_reward_payout_manifest_immutable()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception 'reward payout manifests are immutable';
end;
$$;

revoke all on function public.enforce_reward_payout_manifest_immutable()
  from public, anon, authenticated;

drop trigger if exists reward_payout_manifests_immutable_guard
  on public.reward_payout_manifests;
create trigger reward_payout_manifests_immutable_guard
before update or delete on public.reward_payout_manifests
for each row execute function public.enforce_reward_payout_manifest_immutable();

create or replace function public.create_reward_payout_manifest(
  p_round_id bigint,
  p_operator_wallet text,
  p_pool_address text,
  p_manifest_hash text,
  p_clauses jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_veinvite_app_id constant text :=
    '0x29acc8863cf2ab7a82d16c62d61ca84b6650cede4c4fd69073148c875349021e';
  v_round public.reward_rounds%rowtype;
  v_existing public.reward_payout_manifests%rowtype;
  v_total_count integer := 0;
  v_pending_count integer := 0;
  v_total_amount numeric(78,0) := 0;
  v_matching_clause_count integer := 0;
  v_manifest_id bigint;
begin
  p_operator_wallet := lower(btrim(p_operator_wallet));
  p_pool_address := lower(btrim(p_pool_address));
  p_manifest_hash := lower(btrim(p_manifest_hash));

  if p_round_id is null or p_round_id < 1 then
    raise exception 'round_id must be positive';
  end if;

  if p_operator_wallet is null or p_operator_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'operator wallet must be a lowercase VeChain address';
  end if;

  if p_pool_address is null or p_pool_address !~ '^0x[0-9a-f]{40}$' then
    raise exception 'pool address must be a lowercase VeChain address';
  end if;

  if p_manifest_hash is null or p_manifest_hash !~ '^0x[0-9a-f]{64}$' then
    raise exception 'manifest hash must be a lowercase 32-byte hex value';
  end if;

  if p_clauses is null or jsonb_typeof(p_clauses) <> 'array' or jsonb_array_length(p_clauses) < 1 then
    raise exception 'manifest clauses must be a non-empty JSON array';
  end if;

  select *
  into v_round
  from public.reward_rounds
  where id = p_round_id
  for update;

  if not found then
    raise exception 'reward round not found';
  end if;

  if v_round.status <> 'CREATED' then
    raise exception 'reward round must be CREATED before manifest generation';
  end if;

  if v_round.app_id <> v_veinvite_app_id then
    raise exception 'manifest can only target the VeInvite app';
  end if;

  select *
  into v_existing
  from public.reward_payout_manifests
  where round_id = p_round_id;

  if found then
    if v_existing.manifest_hash = p_manifest_hash
       and v_existing.operator_wallet = p_operator_wallet
       and v_existing.x2earn_rewards_pool_address = p_pool_address
       and v_existing.clauses = p_clauses then
      return jsonb_build_object(
        'manifest_id', v_existing.id,
        'created', false
      );
    end if;

    raise exception 'reward round already has a different immutable payout manifest';
  end if;

  select
    count(*),
    count(*) filter (where status = 'PENDING' and tx_id is null),
    coalesce(sum(amount_wei), 0)
  into
    v_total_count,
    v_pending_count,
    v_total_amount
  from public.reward_payouts
  where round_id = p_round_id;

  if v_total_count < 1 then
    raise exception 'reward round has no payouts';
  end if;

  if v_pending_count <> v_total_count then
    raise exception 'all payouts must be PENDING with no tx_id before manifest generation';
  end if;

  if v_total_count <> v_round.eligible_count then
    raise exception 'payout count does not match reward round eligible_count';
  end if;

  if v_total_amount <> v_round.distributable_wei then
    raise exception 'payout total does not match reward round distributable amount';
  end if;

  if jsonb_array_length(p_clauses) <> v_total_count then
    raise exception 'manifest clause count does not match payout count';
  end if;

  with expected as (
    select
      row_number() over (order by rp.id) as ordinal,
      rp.id::text as payout_id,
      rp.invite_code,
      lower(rp.recipient_wallet) as recipient_wallet,
      rp.amount_wei::text as amount_wei
    from public.reward_payouts rp
    where rp.round_id = p_round_id
  ), provided as (
    select
      ordinality as ordinal,
      value as clause
    from jsonb_array_elements(p_clauses) with ordinality
  )
  select count(*)
  into v_matching_clause_count
  from expected e
  join provided p using (ordinal)
  where p.clause->>'payoutId' = e.payout_id
    and p.clause->>'inviteCode' = e.invite_code
    and lower(p.clause->>'recipientWallet') = e.recipient_wallet
    and p.clause->>'amountWei' = e.amount_wei
    and lower(p.clause->>'to') = p_pool_address
    and p.clause->>'value' = '0x0'
    and p.clause->>'data' ~ '^0x[0-9a-fA-F]+$';

  if v_matching_clause_count <> v_total_count then
    raise exception 'manifest clauses do not match reserved payout identities';
  end if;

  insert into public.reward_payout_manifests(
    round_id,
    network,
    app_id,
    x2earn_rewards_pool_address,
    operator_wallet,
    manifest_hash,
    payout_count,
    total_amount_wei,
    clauses
  ) values (
    p_round_id,
    v_round.network,
    v_round.app_id,
    p_pool_address,
    p_operator_wallet,
    p_manifest_hash,
    v_total_count,
    v_total_amount,
    p_clauses
  )
  returning id into v_manifest_id;

  return jsonb_build_object(
    'manifest_id', v_manifest_id,
    'created', true
  );
end;
$$;

revoke all on function public.create_reward_payout_manifest(bigint, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.create_reward_payout_manifest(bigint, text, text, text, jsonb)
  to service_role;

commit;
