-- Persist the exact payout transaction id as soon as the operator wallet has
-- confirmed it, before VeChain finality. This does not mark any payout PAID.
-- Final settlement remains gated by the finalized on-chain verifier.

begin;

create table if not exists public.reward_payout_transaction_submissions (
  id bigint generated by default as identity primary key,
  manifest_id bigint not null unique references public.reward_payout_manifests(id) on delete restrict,
  round_id bigint not null unique references public.reward_rounds(id) on delete restrict,
  network text not null,
  manifest_hash text not null,
  tx_id text not null unique,
  operator_wallet text not null,
  registered_at timestamptz not null default now(),
  constraint reward_payout_tx_submissions_network_check
    check (network in ('mainnet','testnet','testnet-staging')),
  constraint reward_payout_tx_submissions_hash_check
    check (manifest_hash ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_tx_submissions_tx_id_check
    check (tx_id ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_tx_submissions_operator_check
    check (operator_wallet ~ '^0x[0-9a-f]{40}$')
);

alter table public.reward_payout_transaction_submissions enable row level security;

revoke all on table public.reward_payout_transaction_submissions
  from public, anon, authenticated;
grant select on table public.reward_payout_transaction_submissions
  to service_role;

create or replace function public.enforce_reward_payout_transaction_submission_immutable()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception 'reward payout transaction submissions are immutable';
end;
$$;

revoke all on function public.enforce_reward_payout_transaction_submission_immutable()
  from public, anon, authenticated;

drop trigger if exists reward_payout_transaction_submissions_immutable_guard
  on public.reward_payout_transaction_submissions;
create trigger reward_payout_transaction_submissions_immutable_guard
before update or delete on public.reward_payout_transaction_submissions
for each row execute function public.enforce_reward_payout_transaction_submission_immutable();

create or replace function public.register_reward_payout_transaction_submission(
  p_manifest_id bigint,
  p_tx_id text,
  p_operator_wallet text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_manifest public.reward_payout_manifests%rowtype;
  v_round public.reward_rounds%rowtype;
  v_existing public.reward_payout_transaction_submissions%rowtype;
  v_payout_count integer := 0;
  v_pending_count integer := 0;
  v_submission_id bigint;
begin
  p_tx_id := lower(btrim(p_tx_id));
  p_operator_wallet := lower(btrim(p_operator_wallet));

  if p_manifest_id is null or p_manifest_id < 1 then
    raise exception 'manifest_id must be positive';
  end if;

  if p_tx_id is null or p_tx_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'tx_id must be a lowercase 32-byte hex value';
  end if;

  if p_operator_wallet is null or p_operator_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'operator wallet must be a lowercase VeChain address';
  end if;

  select *
  into v_manifest
  from public.reward_payout_manifests
  where id = p_manifest_id;

  if not found then
    raise exception 'reward payout manifest not found';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_submission_' || v_manifest.round_id::text,
      0
    )
  );

  if v_manifest.operator_wallet <> p_operator_wallet then
    raise exception 'operator wallet does not match payout manifest';
  end if;

  if not exists (
    select 1
    from public.reward_payout_manifest_chain_checkpoints c
    where c.manifest_id = v_manifest.id
  ) then
    raise exception 'payout manifest chain checkpoint must exist before transaction registration';
  end if;

  if exists (
    select 1
    from public.reward_payout_transaction_settlements s
    where s.manifest_id = v_manifest.id
  ) then
    raise exception 'reward payout manifest is already finalized';
  end if;

  select *
  into v_existing
  from public.reward_payout_transaction_submissions
  where manifest_id = v_manifest.id;

  if found then
    if v_existing.tx_id = p_tx_id
       and v_existing.operator_wallet = p_operator_wallet
       and v_existing.manifest_hash = v_manifest.manifest_hash then
      return jsonb_build_object(
        'submission_id', v_existing.id,
        'created', false,
        'round_id', v_existing.round_id,
        'tx_id', v_existing.tx_id,
        'registered_at', v_existing.registered_at
      );
    end if;

    raise exception 'reward payout manifest already has a different immutable transaction submission';
  end if;

  if exists (
    select 1
    from public.reward_payout_transaction_submissions s
    where s.tx_id = p_tx_id
      and s.manifest_id <> v_manifest.id
  ) or exists (
    select 1
    from public.reward_payout_transaction_settlements s
    where s.tx_id = p_tx_id
      and s.manifest_id <> v_manifest.id
  ) then
    raise exception 'transaction is already bound to another reward manifest';
  end if;

  select *
  into v_round
  from public.reward_rounds
  where id = v_manifest.round_id
  for update;

  if not found then
    raise exception 'reward round not found';
  end if;

  if v_round.status <> 'CREATED' then
    raise exception 'reward round must be CREATED before transaction registration';
  end if;

  if v_round.network <> v_manifest.network
     or v_round.app_id <> v_manifest.app_id then
    raise exception 'reward round identity does not match payout manifest';
  end if;

  select
    count(*),
    count(*) filter (where status = 'PENDING' and tx_id is null)
  into
    v_payout_count,
    v_pending_count
  from public.reward_payouts
  where round_id = v_manifest.round_id;

  if v_payout_count <> v_manifest.payout_count
     or v_pending_count <> v_payout_count then
    raise exception 'all manifest payouts must remain PENDING with no tx_id before transaction registration';
  end if;

  insert into public.reward_payout_transaction_submissions(
    manifest_id,
    round_id,
    network,
    manifest_hash,
    tx_id,
    operator_wallet
  ) values (
    v_manifest.id,
    v_manifest.round_id,
    v_manifest.network,
    v_manifest.manifest_hash,
    p_tx_id,
    p_operator_wallet
  )
  returning id into v_submission_id;

  return jsonb_build_object(
    'submission_id', v_submission_id,
    'created', true,
    'round_id', v_manifest.round_id,
    'tx_id', p_tx_id,
    'registered_at', now()
  );
end;
$$;

revoke all on function public.register_reward_payout_transaction_submission(bigint, text, text)
  from public, anon, authenticated;
grant execute on function public.register_reward_payout_transaction_submission(bigint, text, text)
  to service_role;

create or replace function public.require_registered_reward_submission_before_settlement()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.reward_payout_transaction_submissions s
    where s.manifest_id = new.manifest_id
      and s.round_id = new.round_id
      and s.network = new.network
      and s.manifest_hash = new.manifest_hash
      and s.tx_id = new.tx_id
      and s.operator_wallet = new.tx_origin
  ) then
    raise exception 'verified settlement requires a matching registered payout transaction submission';
  end if;

  return new;
end;
$$;

revoke all on function public.require_registered_reward_submission_before_settlement()
  from public, anon, authenticated;

drop trigger if exists reward_payout_settlement_requires_registered_submission
  on public.reward_payout_transaction_settlements;
create trigger reward_payout_settlement_requires_registered_submission
before insert on public.reward_payout_transaction_settlements
for each row execute function public.require_registered_reward_submission_before_settlement();

commit;
