alter table public.reward_runtime_config
  add column if not exists reward_x_promotion_enabled boolean not null default false,
  add column if not exists reward_x_promotion_shadow_enabled boolean not null default false,
  add column if not exists reward_x_promotion_policy_version text not null default 'x-promotion-split-v1';

alter table public.reward_runtime_config
  drop constraint if exists reward_runtime_config_x_promotion_policy_version_check,
  add constraint reward_runtime_config_x_promotion_policy_version_check
    check (char_length(btrim(reward_x_promotion_policy_version)) between 1 and 80);

update public.reward_runtime_config
set reward_x_promotion_enabled=false,
    reward_x_promotion_shadow_enabled=false,
    reward_x_promotion_policy_version='x-promotion-split-v1'
where id=1;

create table if not exists public.reward_x_promotion_splits (
  id bigint generated by default as identity primary key,
  queue_entry_id bigint not null references public.reward_queue_entries(id),
  invite_code text not null check (invite_code ~ '^[A-HJ-NP-Z2-9]{7}$'),
  network text not null check (network in ('mainnet','testnet','testnet-staging')),
  recipient_wallet text not null check (recipient_wallet ~ '^0x[0-9a-f]{40}$'),
  reservation_amount_wei numeric(78,0) not null
    check (reservation_amount_wei > 0 and reservation_amount_wei=trunc(reservation_amount_wei)),
  base_amount_wei numeric(78,0) not null
    check (base_amount_wei > 0 and base_amount_wei=trunc(base_amount_wei)),
  promotion_amount_wei numeric(78,0) not null
    check (promotion_amount_wei >= 0 and promotion_amount_wei=trunc(promotion_amount_wei)),
  source_reward_cohort_round_id bigint not null
    check (source_reward_cohort_round_id >= 1),
  source_allocation_receipt_id bigint not null
    references public.vebetter_round_allocations(id),
  mode text not null check (mode in ('SHADOW','LIVE')),
  policy_version text not null
    check (char_length(btrim(policy_version)) between 1 and 80),
  created_at timestamptz not null default now(),
  constraint reward_x_promotion_splits_queue_uidx unique(queue_entry_id),
  constraint reward_x_promotion_splits_invite_uidx unique(invite_code),
  constraint reward_x_promotion_splits_conservation_check
    check (reservation_amount_wei = base_amount_wei + promotion_amount_wei)
);

create index if not exists reward_x_promotion_splits_source_idx
  on public.reward_x_promotion_splits(
    network,
    source_reward_cohort_round_id,
    source_allocation_receipt_id
  );

create or replace function public.validate_reward_x_promotion_split()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
declare
  v_queue public.reward_queue_entries%rowtype;
  v_invitation public.invitations%rowtype;
  v_cfg public.reward_runtime_config%rowtype;
begin
  select * into v_cfg
  from public.reward_runtime_config
  where id=1;

  if not found then
    raise exception 'REWARD_RUNTIME_CONFIG_MISSING';
  end if;

  if btrim(new.policy_version)<>btrim(v_cfg.reward_x_promotion_policy_version) then
    raise exception 'REWARD_X_PROMOTION_POLICY_MISMATCH';
  end if;

  if new.mode='LIVE' and not v_cfg.reward_x_promotion_enabled then
    raise exception 'REWARD_X_PROMOTION_LIVE_DISABLED';
  end if;

  if new.mode='SHADOW' and not v_cfg.reward_x_promotion_shadow_enabled then
    raise exception 'REWARD_X_PROMOTION_SHADOW_DISABLED';
  end if;

  select * into v_queue
  from public.reward_queue_entries q
  where q.id=new.queue_entry_id;

  if not found
     or v_queue.invite_code<>new.invite_code
     or v_queue.network<>new.network
     or lower(v_queue.recipient_wallet)<>new.recipient_wallet
     or v_queue.reserved_amount_wei is null
     or v_queue.reserved_amount_wei<>new.reservation_amount_wei
     or v_queue.reserved_at is null then
    raise exception 'REWARD_X_PROMOTION_QUEUE_MISMATCH';
  end if;

  select * into v_invitation
  from public.invitations i
  where i.invite_code=new.invite_code;

  if not found
     or lower(v_invitation.inviter_wallet)<>new.recipient_wallet
     or v_invitation.activation_network<>new.network
     or v_invitation.reward_cohort_round_id<>new.source_reward_cohort_round_id
     or v_invitation.reward_funding_allocation_receipt_id<>new.source_allocation_receipt_id then
    raise exception 'REWARD_X_PROMOTION_SOURCE_MISMATCH';
  end if;

  if new.mode='LIVE' and exists (
    select 1
    from public.reward_payouts rp
    where rp.invite_code=new.invite_code
  ) then
    raise exception 'REWARD_X_PROMOTION_SPLIT_TOO_LATE';
  end if;

  return new;
end;
$function$;

create or replace function public.reject_reward_x_promotion_split_mutation()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $function$
begin
  raise exception 'Reward X promotion split % is immutable', old.id;
end;
$function$;

drop trigger if exists validate_reward_x_promotion_split_trigger
  on public.reward_x_promotion_splits;
create trigger validate_reward_x_promotion_split_trigger
before insert on public.reward_x_promotion_splits
for each row execute function public.validate_reward_x_promotion_split();

drop trigger if exists reject_reward_x_promotion_split_mutation_trigger
  on public.reward_x_promotion_splits;
create trigger reject_reward_x_promotion_split_mutation_trigger
before update or delete on public.reward_x_promotion_splits
for each row execute function public.reject_reward_x_promotion_split_mutation();

alter table public.reward_x_promotion_splits enable row level security;

revoke all on table public.reward_x_promotion_splits
  from public,anon,authenticated,service_role;
revoke all on sequence public.reward_x_promotion_splits_id_seq
  from public,anon,authenticated,service_role;

grant select,insert on table public.reward_x_promotion_splits to service_role;
grant usage,select on sequence public.reward_x_promotion_splits_id_seq to service_role;

revoke all on function public.validate_reward_x_promotion_split()
  from public,anon,authenticated;
revoke all on function public.reject_reward_x_promotion_split_mutation()
  from public,anon,authenticated;

comment on table public.reward_x_promotion_splits is
  'Immutable accounting-only split of an existing fixed net reward reservation. Foundation only: no payout path reads this table until a later explicitly enabled migration/code rollout.';
