-- Finalize a reward manifest only after the exact VeChain transaction has
-- been independently verified against the immutable payout manifest and a
-- finalized canonical block. This migration cannot submit transactions.

begin;

create table if not exists public.reward_payout_transaction_settlements (
  id bigint generated by default as identity primary key,
  manifest_id bigint not null unique references public.reward_payout_manifests(id) on delete restrict,
  round_id bigint not null unique references public.reward_rounds(id) on delete restrict,
  network text not null,
  manifest_hash text not null,
  tx_id text not null unique,
  tx_origin text not null,
  block_id text not null,
  block_number bigint not null,
  block_timestamp bigint not null,
  finalized_head_id text not null,
  finalized_head_number bigint not null,
  clause_count integer not null,
  verified_at timestamptz not null default now(),
  paid_at timestamptz not null,
  constraint reward_payout_tx_settlements_network_check
    check (network in ('mainnet','testnet','testnet-staging')),
  constraint reward_payout_tx_settlements_hash_check
    check (manifest_hash ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_tx_settlements_tx_id_check
    check (tx_id ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_tx_settlements_origin_check
    check (tx_origin ~ '^0x[0-9a-f]{40}$'),
  constraint reward_payout_tx_settlements_block_id_check
    check (block_id ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_tx_settlements_finalized_head_id_check
    check (finalized_head_id ~ '^0x[0-9a-f]{64}$'),
  constraint reward_payout_tx_settlements_block_number_check
    check (block_number >= 0),
  constraint reward_payout_tx_settlements_block_timestamp_check
    check (block_timestamp >= 0),
  constraint reward_payout_tx_settlements_finalized_number_check
    check (finalized_head_number >= block_number),
  constraint reward_payout_tx_settlements_clause_count_check
    check (clause_count > 0)
);

alter table public.reward_payout_transaction_settlements enable row level security;

revoke all on table public.reward_payout_transaction_settlements
  from public, anon, authenticated;
grant select on table public.reward_payout_transaction_settlements
  to service_role;

create or replace function public.enforce_reward_payout_transaction_settlement_immutable()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  raise exception 'reward payout transaction settlements are immutable';
end;
$$;

revoke all on function public.enforce_reward_payout_transaction_settlement_immutable()
  from public, anon, authenticated;

drop trigger if exists reward_payout_transaction_settlements_immutable_guard
  on public.reward_payout_transaction_settlements;
create trigger reward_payout_transaction_settlements_immutable_guard
before update or delete on public.reward_payout_transaction_settlements
for each row execute function public.enforce_reward_payout_transaction_settlement_immutable();

create or replace function public.finalize_reward_payout_manifest(
  p_manifest_id bigint,
  p_manifest_hash text,
  p_tx_id text,
  p_tx_origin text,
  p_block_id text,
  p_block_number bigint,
  p_block_timestamp bigint,
  p_finalized_head_id text,
  p_finalized_head_number bigint,
  p_clause_count integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_manifest public.reward_payout_manifests%rowtype;
  v_round public.reward_rounds%rowtype;
  v_existing public.reward_payout_transaction_settlements%rowtype;
  v_payout_count integer := 0;
  v_pending_count integer := 0;
  v_sending_count integer := 0;
  v_paid_count integer := 0;
  v_invitation_count integer := 0;
  v_total_amount numeric(78,0) := 0;
  v_paid_at timestamptz;
  v_settlement_id bigint;
begin
  p_manifest_hash := lower(btrim(p_manifest_hash));
  p_tx_id := lower(btrim(p_tx_id));
  p_tx_origin := lower(btrim(p_tx_origin));
  p_block_id := lower(btrim(p_block_id));
  p_finalized_head_id := lower(btrim(p_finalized_head_id));

  if p_manifest_id is null or p_manifest_id < 1 then
    raise exception 'manifest_id must be positive';
  end if;

  if p_manifest_hash is null or p_manifest_hash !~ '^0x[0-9a-f]{64}$' then
    raise exception 'manifest_hash must be a lowercase 32-byte hex value';
  end if;

  if p_tx_id is null or p_tx_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'tx_id must be a lowercase 32-byte hex value';
  end if;

  if p_tx_origin is null or p_tx_origin !~ '^0x[0-9a-f]{40}$' then
    raise exception 'tx_origin must be a lowercase VeChain address';
  end if;

  if p_block_id is null or p_block_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'block_id must be a lowercase 32-byte hex value';
  end if;

  if p_finalized_head_id is null or p_finalized_head_id !~ '^0x[0-9a-f]{64}$' then
    raise exception 'finalized_head_id must be a lowercase 32-byte hex value';
  end if;

  if p_block_number is null or p_block_number < 0 then
    raise exception 'block_number must be non-negative';
  end if;

  if p_block_timestamp is null or p_block_timestamp < 0 then
    raise exception 'block_timestamp must be non-negative';
  end if;

  if p_finalized_head_number is null or p_finalized_head_number < p_block_number then
    raise exception 'transaction block is not finalized';
  end if;

  if p_clause_count is null or p_clause_count < 1 then
    raise exception 'clause_count must be positive';
  end if;

  select *
  into v_manifest
  from public.reward_payout_manifests
  where id = p_manifest_id;

  if not found then
    raise exception 'reward payout manifest not found';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'veinvite_reward_finalize_' || v_manifest.round_id::text,
      0
    )
  );

  select *
  into v_existing
  from public.reward_payout_transaction_settlements
  where manifest_id = p_manifest_id;

  if found then
    if v_existing.tx_id = p_tx_id
       and v_existing.manifest_hash = p_manifest_hash
       and v_existing.tx_origin = p_tx_origin
       and v_existing.block_id = p_block_id
       and v_existing.block_number = p_block_number
       and v_existing.block_timestamp = p_block_timestamp
       and v_existing.clause_count = p_clause_count then
      return jsonb_build_object(
        'settlement_id', v_existing.id,
        'created', false,
        'round_id', v_existing.round_id,
        'tx_id', v_existing.tx_id,
        'paid_count', v_existing.clause_count,
        'paid_at', v_existing.paid_at
      );
    end if;

    raise exception 'reward payout manifest already has a different immutable settlement';
  end if;

  if exists (
    select 1
    from public.reward_payout_transaction_settlements s
    where s.tx_id = p_tx_id
      and s.manifest_id <> p_manifest_id
  ) then
    raise exception 'transaction is already bound to another reward manifest';
  end if;

  if exists (
    select 1
    from public.reward_payouts rp
    where rp.tx_id = p_tx_id
      and rp.round_id <> v_manifest.round_id
  ) then
    raise exception 'transaction is already referenced by another reward round';
  end if;

  if v_manifest.manifest_hash <> p_manifest_hash then
    raise exception 'manifest hash does not match stored immutable manifest';
  end if;

  if v_manifest.operator_wallet <> p_tx_origin then
    raise exception 'transaction origin does not match manifest operator wallet';
  end if;

  if v_manifest.payout_count <> p_clause_count then
    raise exception 'transaction clause count does not match payout manifest';
  end if;

  select *
  into v_round
  from public.reward_rounds
  where id = v_manifest.round_id
  for update;

  if not found then
    raise exception 'reward round not found';
  end if;

  if v_round.status <> 'CREATED' then
    raise exception 'reward round must be CREATED before verified settlement';
  end if;

  if v_round.network <> v_manifest.network
     or v_round.app_id <> v_manifest.app_id then
    raise exception 'reward round identity does not match payout manifest';
  end if;

  v_paid_at := to_timestamp(p_block_timestamp);

  if v_paid_at < v_manifest.created_at - interval '60 seconds' then
    raise exception 'transaction predates payout manifest and cannot be reused';
  end if;

  select
    count(*),
    count(*) filter (where status = 'PENDING' and tx_id is null),
    coalesce(sum(amount_wei), 0)
  into
    v_payout_count,
    v_pending_count,
    v_total_amount
  from public.reward_payouts
  where round_id = v_manifest.round_id;

  if v_payout_count <> v_manifest.payout_count
     or v_pending_count <> v_payout_count then
    raise exception 'all manifest payouts must still be PENDING with no tx_id';
  end if;

  if v_total_amount <> v_manifest.total_amount_wei
     or v_total_amount <> v_round.distributable_wei then
    raise exception 'payout total no longer matches manifest and reward round';
  end if;

  insert into public.reward_payout_transaction_settlements(
    manifest_id,
    round_id,
    network,
    manifest_hash,
    tx_id,
    tx_origin,
    block_id,
    block_number,
    block_timestamp,
    finalized_head_id,
    finalized_head_number,
    clause_count,
    paid_at
  ) values (
    v_manifest.id,
    v_manifest.round_id,
    v_manifest.network,
    v_manifest.manifest_hash,
    p_tx_id,
    p_tx_origin,
    p_block_id,
    p_block_number,
    p_block_timestamp,
    p_finalized_head_id,
    p_finalized_head_number,
    p_clause_count,
    v_paid_at
  )
  returning id into v_settlement_id;

  update public.reward_payouts
  set
    status = 'SENDING',
    tx_id = p_tx_id,
    attempt_count = attempt_count + 1,
    error_message = null,
    updated_at = now()
  where round_id = v_manifest.round_id
    and status = 'PENDING'
    and tx_id is null;

  get diagnostics v_sending_count = row_count;

  if v_sending_count <> v_manifest.payout_count then
    raise exception 'could not atomically bind all payouts to verified transaction';
  end if;

  update public.reward_payouts
  set
    status = 'PAID',
    paid_at = v_paid_at,
    error_message = null,
    updated_at = now()
  where round_id = v_manifest.round_id
    and status = 'SENDING'
    and tx_id = p_tx_id;

  get diagnostics v_paid_count = row_count;

  if v_paid_count <> v_manifest.payout_count then
    raise exception 'could not atomically finalize all payouts as PAID';
  end if;

  update public.reward_rounds
  set
    status = 'COMPLETED',
    started_at = coalesce(started_at, v_paid_at),
    completed_at = v_paid_at
  where id = v_manifest.round_id
    and status = 'CREATED';

  if not found then
    raise exception 'reward round could not be finalized';
  end if;

  update public.invitations i
  set
    reward_status = 'PAID',
    reward_paid_at = v_paid_at
  where exists (
    select 1
    from public.reward_payouts rp
    where rp.round_id = v_manifest.round_id
      and rp.invite_code = i.invite_code
      and rp.status = 'PAID'
      and rp.tx_id = p_tx_id
  );

  get diagnostics v_invitation_count = row_count;

  if v_invitation_count <> v_manifest.payout_count then
    raise exception 'paid invitation count does not match payout manifest';
  end if;

  return jsonb_build_object(
    'settlement_id', v_settlement_id,
    'created', true,
    'round_id', v_manifest.round_id,
    'tx_id', p_tx_id,
    'paid_count', v_paid_count,
    'paid_at', v_paid_at
  );
end;
$$;

revoke all on function public.finalize_reward_payout_manifest(
  bigint, text, text, text, text, bigint, bigint, text, bigint, integer
) from public, anon, authenticated;
grant execute on function public.finalize_reward_payout_manifest(
  bigint, text, text, text, text, bigint, bigint, text, bigint, integer
) to service_role;

commit;
